### ISSUE TITLE
md-input two way data binding is not working.

### ISSUE THREAD

**Issue by Muthu2020** [angular/material2#844] opened 2016-07-12 06:41 UTC
I have used the following tag in html.

```jade
"<md-input placeholder='Organization Name',name='name',[(ngModel)]='orgSettings.name',ngControl='name',[ngClass] = "{'text-danger-error': !orgForm.controls.name.valid && isSubmitted}">"
```

I have added following code in typescript within the constructor.
this.orgSettings['name'] ='test';

Versions used
angular2-2.0.0rc4
@angular/forms - 0.2.0
material2-alpha6

Can you please guide me to resolve this issue

**Comment by mmrath** [comment] 2016-07-12 06:52
You don't need those commas I think. Better make a plunker with the issue if you still are facing it.

**Comment by Muthu2020** [comment] 2016-07-12 07:02
Actually, I have used that tag in jade. Its looks like
md-input(placeholder='Organization Name',name='name',[ngModel] = 'orgSettings.name',ngControl='name',[ngClass] = "{'text-danger-error': !orgForm.controls.name.valid && isSubmitted}")``

**Comment by snolflake** [comment] 2016-07-13 10:53
Show us how you're loading those templates in your code. If you're using webpack for example tell us which loaders are you using, how you configured it, etc...

**Comment by Muthu2020** [comment] 2016-07-13 10:58
Actually, this issue is fixed by adding value attribute in md-input tag. Thank you for your reply.

**Comment by jelbourn** [comment] 2016-07-14 23:18
@Muthu2020 can you reproduce this in a plunker so that we can see it?

**Comment by alenaksu** [comment] 2016-07-15 10:15
Hi @jelbourn, I have the same problem, you can see it [here](http://plnkr.co/edit/KqsgYbc6gQ65Hh8emOiB?p=preview)

**Comment by jrmoser** [comment] 2016-07-18 17:41
@alenaksu The only issue you are having with Material, is that when you use ngModel you must include the name attribute. However you wouldn't have found this out without fixing the bigger issue that you were having, which was with Angular's forms. They are currently going through a [deprecation phase](https://angular.io/docs/ts/latest/guide/forms.html) and so there are some things you must do to make your plunker work. [Here is a working plunker](http://plnkr.co/edit/j0NsmfvIQPOeDpmmfS3K?p=preview) and the code I adjusted to make it work was:

app/main.ts

`...
import { disableDeprecatedForms, provideForms } from '@angular/forms';
...

bootstrap(AppComponent, [
  disableDeprecatedForms(),
  provideForms(),
  ]);
`

then on your input don't forget to put in the name attribute:

`<md-input ... name="email"></md-input>`

**Comment by kara** [comment] 2016-07-20 22:14
As @jrmoser explained (thanks @jrmoser!), the plunker is missing the name attribute and the proper bootstrapping. Once these issues are fixed, md-input works as expected.  Closing, as this doesn't seem to be a bug.  Please feel free to open another issue with a plunker example if you run into anything else that looks like it could be a bug.

**Closed by kara** 2016-07-20 22:14 UTC
Labels: cannot reproduce

**Comment by jonathan-casarrubias** [comment] 2016-07-20 22:43
Thanks for clarifying!! I just had this issue

**Comment by vapits** [comment] 2016-08-18 14:42
Is this related with this #1073  ?

**Comment by sumitramteke** [comment] 2017-11-03 09:30
For me it is working as 

```html
<md-form-field>
      <input mdInput name="uname" [(ngModel)]="uname" placeholder="username">
</md-form-field>
```

**@angular/material: 2.0.0-beta.10**
**@angular/forms: 4.3.6**
**@angular/core: 4.3.6**

**Comment by naderafshari** [comment] 2018-01-01 20:38
two way binding works for me in localhost mode but not in production mode!
If I don't use material then it works in production too

This don't work in production....
  <mat-form-field *ngIf="userInfo">
    <input matInput name="userInfo.lastName" [(ngModel)]="userInfo.lastName" placeholder="Last Name.."> 
  </mat-form-field>


This works in production...
  <input *ngIf="userInfo" [(ngModel)]="userInfo.lastName" placeholder="Last Name.."> 


Angular CLI: 1.6.2
Node: 6.12.0
OS: linux x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.2
@angular/cli: 1.6.2
@angular/material: 5.0.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0

**Comment by EddyChina** [comment] 2018-02-21 04:25
@naderafshari yes, I got the same problem in both 'ng build --prod' and 'ng i18n'.  however, the application runs well on localhost,  even just 'ng build' is ok. BUT NOT '--prod'.

**Comment by maifs** [comment] 2018-05-27 09:32
Hi,  i am getting an exception while  using it.
        <mat-form-field [floatLabel]="options.value.floatLabel">
            <mat-label>Password:</mat-label>
            <input matInput [type]="hide ? 'password' : 'text'"
                   *ngIf="userLogin"
                   name="password"
                   [(ngModel)]="userLogin.password"
                   placeholder="Enter your password"                   
                   >
            <mat-icon matSuffix (click)="hide = !hide">{{hide ? 'visibility' : 'visibility_off'}}</mat-icon>
        </mat-form-field>


"@angular/cli": "^6.0.3",
    "@angular/compiler-cli": "^6.0.2",
Node: V10.0.0
OS: windows 10 x64
Angular: 6.0.2
 "@angular/animations": "^6.0.2",
    "@angular/cdk": "^6.0.2",
    "@angular/common": "^6.0.2",
    "@angular/compiler": "^6.0.2",
    "@angular/core": "^6.0.2",
    "@angular/forms": "^6.0.2",
    "@angular/http": "^6.0.2",
    "@angular/material": "^6.0.2",
    "@angular/platform-browser": "^6.0.2",
    "@angular/platform-browser-dynamic": "^6.0.2",
    "@angular/router": "^6.0.2",
    "@ngx-translate/core": "^10.0.1",

"ts-node": "~6.0.3",
    "tslint": "~5.10.0",
    "typescript": "^2.7.2"


ERROR Error: 
      ngModel cannot be used to register form controls with a parent formGroup directive.  Try using
      formGroup's partner directive "formControlName" instead.  Example:

      
    <div [formGroup]="myGroup">
      <input formControlName="firstName">
    </div>
