### ISSUE TITLE
No valuechange when invalid date

### ISSUE THREAD

**Issue by lousley** [angular/material2#11931] opened 2018-06-26 07:56 UTC
**Bug, feature request, or proposal:**

Bug
**What is the expected behavior?**

https://github.com/angular/material2/blob/8050f633b56b6c048fc72dad2ab79304afdfad19/src/lib/datepicker/datepicker-input.ts#L332

This line of code produces a problem. If an invalidate is returned by a MomenDateAdpater in the parse method and the value was previously zero, no event is thrown.

**What are the steps to reproduce?**

Go to https://material.angular.io/components/datepicker/overview and navigate to "Datepicker that uses Moment.js dates". Clean the value and input 'asdf'. No error is displayed.

**What is the use-case or motivation for changing an existing behavior?**

I want enter a invalid date after cleaning the input field and will see an error

**Which versions of Angular, Material, OS, TypeScript, browsers are affected?**

Angular 6
Material 6.3.0
Typescript: 2.7.2
All browswers

**Comment by lousley** [comment] 2018-08-15 07:04
Why is this bug low? 
This error also occurs in the initial case..that means, if the user still has no value in his date field, he can enter an invalid value and does not see that .. with an input mask where the user must enter his date of birth, that is very problematic

**Comment by lemoinem** [comment] 2018-09-05 13:29
This issue also trigger the other way around.
If a date picker field with an invalid is cleared, the field remained marked as error (invalid date).
I have **no** validator (e.g., required) on the field.

Coalescing null and invalid values does not sound like the correct behavior.

**Comment by Pamasich** [comment] 2018-10-15 13:18
Why is this only at low priority? Is there some workaround or something?

**Comment by lemoinem** [comment] 2018-10-15 14:08
This is linked to, if not a duplicate of: #13346 (That's classified as P1/regression)

**Comment by crisbeto** [comment] 2019-04-06 16:04
Looks like the related PR got merged in, but it wasn't labelled properly so the issue didn't close on its own.

**Closed by crisbeto** 2019-04-06 16:04 UTC
Labels: P4
