### ISSUE TITLE
md-nav-list inside sidenav selects first item

### ISSUE THREAD

**Issue by robindijkhof** [angular/material2#5385] opened 2017-06-27 20:25 UTC
#### Bug:
The first item in the md-nav-list is selected when inside an sidenav

#### What is the expected behavior?
It shouldn't be selected

#### What is the current behavior?
It is selected

#### What are the steps to reproduce?
https://plnkr.co/edit/Gp8bsaiOdpEvwsM6NFzP?p=preview

open the sidenav and see the first item

#### What is the use-case or motivation for changing an existing behavior?
Current behaviour is illogical

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.1.3
node: 6.10.2
os: win32 x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4

#### Is there anything else we should know?
no

**Comment by willshowell** [comment] 2017-06-27 21:01
https://github.com/angular/material2/issues/5129#issuecomment-308583396 is relevant here

**Comment by tinayuangao** [comment] 2017-06-27 22:55
Duplicate of #5129

**Closed by tinayuangao** 2017-06-27 22:55 UTC
