### ISSUE TITLE
Md-dialog size scaling

### ISSUE THREAD

**Issue by theunreal** [angular/material2#1952] opened 2016-11-21 17:37 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-dialog to open unblurred when a big image inside the dialog. See unblured version:

![image](https://cloud.githubusercontent.com/assets/6171883/20493449/7e2d5eaa-b021-11e6-8a2c-6d4f1fef00af.png)

#### What is the current behavior?
The md-dialog is blurred when big image inside. See blurred version with an image inside:

![image](https://cloud.githubusercontent.com/assets/6171883/20493469/9cb80e10-b021-11e6-978f-70b01a53b645.png)

See this comparison:

![image](https://cloud.githubusercontent.com/assets/6171883/20493513/cd5e009c-b021-11e6-981f-98ae8ece49c0.png)

You can notice the the left version is much sharper.

This blur behavior happens usually when using CSS3 scale.

#### What are the steps to reproduce?
Put a big image inside md dialog and notice the text changes 

#### What is the use-case or motivation for changing an existing behavior?
Make md-dialog works unblurred when a big image inside

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-alpha10

**Comment by jelbourn** [comment] 2016-11-21 19:56
Dupe of #932

**Closed by jelbourn** 2016-11-21 19:56 UTC
