### ISSUE TITLE
virtual scroll for mat-table

### ISSUE THREAD

**Issue by fusionUI** [angular/material2#14169] opened 2018-11-16 09:53 UTC
#### Bug, feature request, or proposal:
i am using material mat-table and there is a requirement to show the table rows using virtual scrolling.I know the Virtual scrolling is a recent feature in Material 2,Can this be intergharted with Mat-table as well.
<mat-table #table [dataSource]="dataSource">  ??

#### What is the expected behavior?
Virtual scroll is needed for the Mat-Table rows.
 please keep this separate from the below , as that seems a generic enhancement 
https://github.com/angular/material2/issues/10122

#### What is the current behavior?
Mat-Table does not provide a way to integrate this.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
**example of virtual scroll**
https://stackblitz.com/edit/angular-material-mipznb?file=app%2Fvirtual-scroll%2Fvirtual-scroll.component.html

**Comment by jelbourn** [comment] 2018-11-17 00:05
Duplicate of #10122

**Closed by jelbourn** 2018-11-17 00:05 UTC

**Comment by fusionUI** [comment] 2018-11-17 04:52
Hi jelbourn,

From the #10122 its hard to figure out that Virtual scroll is available now within Mat-table or not.It would be really great if you can comment on that.
