### ISSUE TITLE
dialog double scrollbars

### ISSUE THREAD

**Issue by shahraship** [angular/material2#6835] opened 2017-09-05 01:41 UTC
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
Would like md-dialog to only have one scrollbar

#### What is the current behavior?
md-dialog with scrollable content has double scrollbars

#### What are the steps to reproduce?
Just look at: https://material.angular.io/components/dialog/overview
the section: Dialog with header, scrollable content and actions

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
https://plnkr.co/edit/uUoGG8orawNYiqBEBF31?p=preview

#### What is the use-case or motivation for changing an existing behavior?
It's not very user friendly to have two scollbars

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
2.0.0-beta.10 découpage-panjandrum, all browsers

**Comment by gise88** [comment] 2017-09-05 02:40
This happens only on the small screens. Around 650px or less

**Comment by donroyco** [comment] 2017-09-05 08:33
Have you checked #6584?

**Comment by tinayuangao** [comment] 2017-09-05 23:13
Duplicate of #6584. Closing this issue.

**Closed by tinayuangao** 2017-09-05 23:13 UTC
