### ISSUE TITLE
Progress Bar / Spinner Animation Broken When Loading Items

### ISSUE THREAD

**Issue by Kyderman** [angular/material2#9050] opened 2017-12-19 15:30 UTC
#### Bug, feature request, or proposal:
If I'm loading in a lot of items and creating objects out of them, the progress bar and spinner in indeterminate mode will not render correctly. I assume this is because the thread is blocked.

#### What is the expected behavior?
The animations to work as expected

#### What is the current behavior?
The animations do not work

#### What are the steps to reproduce?
Its quite difficult to replicate this in a plunker etc

#### What is the use-case or motivation for changing an existing behavior?
I want a nice animation for whilst I am waiting for loading of data sets

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All latest

**Comment by josephperrott** [comment] 2017-12-19 16:06
Can you try to provide a reproduction case? 

I was not able to reproduce it with ~150 spinners [here](https://stackblitz.com/edit/angular-material2-issue-mytfrn?file=app%2Fapp.component.ts)

**Comment by Kyderman** [comment] 2017-12-19 16:12
I think you misunderstood my question a bit.

The issue is when i start a spinner / indeterminate progress bar, load in data from a server (say 10000 items) and create objects from them (lets say they are users), and then the spinner is hidden.

When its active, as the data is being read in, the animation is broken. If I unhide the spinner/bar after the work is done, the animation works fine.

**Comment by josephperrott** [comment] 2018-01-02 23:24
Yes, I did misunderstand the situation.

When you say the animation is broken, does it stop entirely or is choppy?

I have not yet been able to reproduce it in my stackblitz repro.  Does the creation of these objects trigger change detection?

**Comment by Kyderman** [comment] 2018-01-03 09:11
@josephperrott I'll try get something together today.

The animation is just weird and nothing like what it should be, not choppy, but weirdly offset and doesnt complete.

As per the code from the previous comment I made, while isLoading is true, the bar is meant to show, and then it is hidden. So if await this.equipmentService.getAllEquipment() is quite large (which is a service, which is then creating a large number of instances of an object). Then the loading bar should show which it does, but the animation is completely broken. I assume that the creation of objects is blocking the UI thread (as clicking elements on the page wont work either). So this may be a limitation of Angular too?

**Comment by Kyderman** [comment] 2018-01-03 11:32
So im trying to get a stackblitz together at https://stackblitz.com/edit/angular-material2-issue-12hjxr

In Stackblitz, i cant even get the loading bar to show up, I'm logging out the "isLoading" variable so I know that the progress bar should be showing and hiding, yet it doesnt. The only difference between this and my app is that the objects being created are more complicated and being fetched from a server, whereas here you can see it is just a large loop

**Comment by jlaverdure-talis** [comment] 2018-01-12 12:43
I have the exact same problem, the animation is broken like in the video shown before.
Do we have a solution to fix it?

**Comment by Kyderman** [comment] 2018-01-12 13:18
My solution was to implement pagination on the server side and split all tables on the page into separate components with their own loading bars. If you have less elements this is way less problematic.

However, the creation of Objects will block the UI thread and make this effect happen on a large set of data.

**Comment by josephperrott** [comment] 2018-01-18 17:20
Closing as this seems to be an issue of creating too many objects in this main thread.

Creating the items asynchronously, or in a worker thread may be a viable alternative.

**Closed by josephperrott** 2018-01-18 17:20 UTC
Labels: P4: minor, animation

**Comment by BabysbreathJJ** [comment] 2018-08-08 06:08
In @angular/cli 6.1.2, @angular/material 6.4.2, the buffer mode does not work, the progress bar is hidden.
