### ISSUE TITLE
[Feature Request] Add a mat-ink-bar to mat-nav-list

### ISSUE THREAD

**Issue by mhebrard** [angular/material2#13527] opened 2018-10-10 07:45 UTC
#### Bug, feature request, or proposal:
Add a mat-ink-bar to the component mat-nav-list to indicate which route is active

#### What is the expected behavior?
display a vertical ink bar beside the mat-list-item that is active

#### What is the current behavior?
no possibility to distinguish the active item from the other.

#### What are the steps to reproduce?
see [StackBlitz](https://stackblitz.com/edit/angular-material2-issue-8czgcn)

#### What is the use-case or motivation for changing an existing behavior?
mat-nav-list is often use in navigation drawer. It is important to notify the user of where he currently is.

#### Is there anything else we should know?
It would be nice to add a input "active" to mat-item-list similar to mat-tab-link

**Comment by TheCom3di4n** [comment] 2018-10-10 09:46
See https://github.com/angular/material2/pull/13115

**Comment by jelbourn** [comment] 2018-10-10 23:04
Duplicate of #13084

**Closed by jelbourn** 2018-10-10 23:04 UTC
