### ISSUE TITLE
Inconsistencies in the md-select implementation compared to md-input

### ISSUE THREAD

**Issue by rdinicut** [angular/material2#2963] opened 2017-02-07 08:58 UTC
#### Proposal:
 md-select should have the floatPlaceholder input property and it should be able to use md-placeholder as ContentChild. 

#### What is the use-case or motivation for changing an existing behavior?

With the current implementation you can not place the label/placeholder on the left side. With md-input you can achieve this by setting floatPlaceholder="always" and with some custom css.

You could argue that you can not use the placeholder property in order to achieve this, but if you want to keep the label colouring functionality depending on the component state  it's a pain to implement.

Maybe all form components should have a property placeholderPlacement:"top"|"left".

**Comment by crisbeto** [comment] 2017-02-07 09:07
The `floatingPlaceholder` option will be added in https://github.com/angular/material2/pull/2571

**Comment by kara** [comment] 2017-02-08 00:10
Closing as a dupe of #2569

**Closed by kara** 2017-02-08 00:10 UTC
Labels: feature, has pr
