### ISSUE TITLE
MatSnackBar - Wrong behavior when open() come from CustomErrorHandler.

### ISSUE THREAD

**Issue by operandom** [angular/material2#15411] opened 2019-03-07 11:58 UTC
#### What is the expected behavior?
SnackBar should appear on the bottom of the page and action should close it.

#### What is the current behavior?
SnackBar appear on top left of the page.  
A click on action make it reappear on the bottom.  
You need to click the action button and then outside of the SnackBar to make it disappear.

#### What are the steps to reproduce?
Stackblitz project has an error with the injection of the MatSnackBar but you can download the project to make it works...  
https://stackblitz.com/edit/angular-material2-issue-ydr3cr

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

- @angular/animations7.2.8
- @angular/cdk7.3.3
- @angular/common7.2.8
- @angular/compiler7.2.8
- @angular/core7.2.8
- @angular/forms7.2.8
- @angular/http7.2.8
- @angular/material7.3.3
- @angular/platform-browser7.2.8
- @angular/platform-browser-dynamic7.2.8
- @angular/router7.2.8
- core-js2.6.5
- hammerjs2.0.8
- rxjs6.4.0
- web-animations-js2.3.1
- zone.js0.8.29

#### Is there anything else we should know?
The process in the project is simple : I catch errors with a custom error handler, send them to a notification service and the app component open a SnackBar from the notifications
The problem with the SnackBar is the same if I try to open it in the custom error handler.

**Comment by josephperrott** [comment] 2019-03-07 15:53
Closing as duplicate of #7233

**Closed by josephperrott** 2019-03-07 15:53 UTC
