### ISSUE TITLE
*ngIf affects button focus order

### ISSUE THREAD

**Issue by jasonpell** [angular/material2#13034] opened 2018-09-07 19:58 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I would expect focus to go to the first button in the overlay menu.

#### What is the current behavior?
If I navigate to a simple overlay menu via keyboard and enter it, focus goes to the first button that doesn't contain an ngIf attribute, regardless of if the ngIf conditional is true.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-zf82u8

1. Go to https://angular-zf82u8.stackblitz.io/
2. Tab to the button, then hit the space bar.
Note that focus goes to the second button instead of the first.

**Comment by josephperrott** [comment] 2018-09-07 20:44
Upon initial investigation this is occuring because `MatMenuItem`s add themselves to their menu via the `addItem` method during initialization.  Since it is in initialization order, items which are being stamped out by structural directives will be placed in the `KeyListManager` order after all of the non-structural directives.

**Comment by crisbeto** [comment] 2018-09-07 20:57
https://github.com/angular/material2/pull/11720 sorts this out.

**Comment by crisbeto** [comment] 2018-09-10 16:33
Closing as a duplicate of https://github.com/angular/material2/issues/11652.

**Closed by crisbeto** 2018-09-10 16:33 UTC
Labels: G, P3
