### ISSUE TITLE
[md-grid-list] should trigger an event when it changes the layout

### ISSUE THREAD

**Issue by herkulano** [angular/material2#1958] opened 2016-11-22 09:29 UTC
#### Feature request:
**md-grid-list**
should trigger an event when it changes the layout, so that the child components can make adjustments.

#### What is the current behavior?
It doesn't trigger any event.

#### What are the steps to reproduce?
http://plnkr.co/edit/1fMrhlZgJ3K0TMJEKmB9?p=preview
check the console for the values

#### What is the use-case or motivation for changing an existing behavior?
Having a svg/d3 chart component inside the md-grid-tile that needs to be resized manually.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.2
Material 1.0.0-Beta.10

**Comment by jelbourn** [comment] 2016-11-30 00:26
Dupe of #1072

**Closed by jelbourn** 2016-11-30 00:26 UTC
