### ISSUE TITLE
Rich Text Editor 

### ISSUE THREAD

**Issue by Taitalus** [angular/material2#7440] opened 2017-09-30 08:10 UTC
Proposal:
Are you guys planning to have a rich text editor?? anything like ckeditor, tinymce or froala??

**Comment by donroyco** [comment] 2017-09-30 09:56
Please use the search function to see if your question already has been covered. See #4444, where @jelbourn states:

> We might start exploring the space in Q2 depending on how other stuff goes. In terms of larger projects, virtual-scrolling, tree, table improvements, and data visualization are all higher up on the list.

**Comment by jelbourn** [comment] 2017-10-01 13:20
Duplicate of #444

**Closed by jelbourn** 2017-10-01 13:20 UTC

**Comment by donroyco** [comment] 2017-10-01 13:40
@jelbourn You mean #4444 instead of #444 😉
