### ISSUE TITLE
Select: Comparison by reference

### ISSUE THREAD

**Issue by AKuzmanoski** [angular/material2#5614] opened 2017-07-08 22:22 UTC
#### Bug, feature request, or proposal:
Bug, feature request

#### What is the expected behavior?
Select should have trackBy property as input. Sometimes complex objects can be used as a value of the options (country in my case). In this case comparison by reference can lead to false negatives.

#### What is the current behavior?
Comparison of values is done with === operator

#### What are the steps to reproduce?
1. Use reactive forms
2. Create select with few options which have complex objects as value
3. Set the value of the select to the copy of one of the objects.

#### What is the use-case or motivation for changing an existing behavior?
More use-cases covered, more accurate, and faster

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.2.6
Angular Material: 2.0.0-beta.8
OS: Windows 10
Typescript: 2.4.3
Browsers: all

**Comment by willshowell** [comment] 2017-07-09 14:52
Duplicate of https://github.com/angular/material2/issues/2785

**Closed** 2017-07-09 16:32 UTC
