### ISSUE TITLE
Content of expansion-panel is visible when parent component (expansion-panel) is closed

### ISSUE THREAD

**Issue by Anderson2000** [angular/material2#9688] opened 2018-01-30 14:36 UTC
#### What is the expected behavior?
![screen shot 2018-01-30 at 4 34 13 pm](https://user-images.githubusercontent.com/20068815/35571649-75d1a66a-05db-11e8-9ea6-2b95fd92fb57.png)

Inputs must be hidden 

#### What is the current behavior?
![screen shot 2018-01-30 at 4 31 11 pm](https://user-images.githubusercontent.com/20068815/35571602-47f0c3d4-05db-11e8-8d62-e216627c516c.png)

https://stackblitz.com/edit/angular-8wrc26?embed=1&file=app/expansion-steps-example.html

#### What are the steps to reproduce?

open (Personal data) -> open (Personal data2) -> open (Personal data3) ->close (Personal data2)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    
Angular CLI: 1.5.5
Node: 6.11.5
OS: darwin x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.1.0-4523556
@angular/cli: 1.5.5
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.1.0-4523556
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.5
@schematics/angular: 0.1.16
typescript: 2.4.2
webpack: 3.8.1

**Comment by josephperrott** [comment] 2018-01-30 16:11
Closing as duplicate of: #8754

**Closed by josephperrott** 2018-01-30 16:11 UTC
