### ISSUE TITLE
md-checkbox click event behaves strange

### ISSUE THREAD

**Issue by tomascharad** [angular/material2#684] opened 2016-06-14 20:19 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The click "(click)" event should just trigger once, sometime is triggering twice and seemly equal parameters, but no identical.

#### What is the current behavior?
The click event, on some checkboxes s triggering two times.

#### What are the steps to reproduce?
Create to separate md-list of checkboxes, to me it happened in elements with odd index starting from 0. 

#### What is the use-case or motivation for changing an existing behavior?
I don't want to use (change) listener, I would like to use click instead, so I can follow redux architecture.

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular/common": "2.0.0-rc.1"
"@angular2-material/checkbox": "^2.0.0-alpha.5-2"

**Comment by DevVersion** [comment] 2016-06-14 20:20
Duplicate of #651

**Comment by jelbourn** [comment] 2016-06-14 20:40
Dupe of #651

**Closed by jelbourn** 2016-06-14 20:40 UTC
