### ISSUE TITLE
Md Grid with media query supports

### ISSUE THREAD

**Issue by MiguelAngelLV** [angular/material2#4660] opened 2017-05-18 20:14 UTC
#### Feature request

Posibility of set colspan value depend of windows size

#### What is the expected behavior?

Media query options as Material 1

https://material.angularjs.org/latest/api/directive/mdGridTile

#### What is the current behavior?

Only flexbox has media query support and it not offers the same options that Md Grid

**Comment by jelbourn** [comment] 2017-05-18 20:50
Dupe of #1072

**Closed by jelbourn** 2017-05-18 20:50 UTC
