### ISSUE TITLE
Change in the material design spec

### ISSUE THREAD

**Issue by Tetrygon** [angular/material2#6624] opened 2017-08-24 14:22 UTC
#### Bug, feature request, or proposal:
Yes..

Inputs have changed in the material design spec. For instance, textareas now include a border.

Labels now replace placeholders and placeholders are something a bit different. (Issue #6240)

Found here:
https://material.io/guidelines/components/text-fields.html#text-fields-field-types

**Comment by willshowell** [comment] 2017-08-24 14:49
Dupe of https://github.com/angular/material2/issues/3984

**Comment by jelbourn** [comment] 2017-08-24 19:44
Duplicate of #3984

**Closed by jelbourn** 2017-08-24 19:44 UTC
