### ISSUE TITLE
Input placeholder do not animate correctly while there is a  autocomplete list.

### ISSUE THREAD

**Issue by flowfire** [angular/material2#6469] opened 2017-08-15 04:15 UTC
#### Bug, feature request, or proposal:
The placeholder of input box with autocomplete list below, won't animate correctly.

#### What is the expected behavior?
The placeholder move & scale by transition.

#### What is the current behavior?
The placeholder just move without any animation

#### gif:
![Imgur](http://i.imgur.com/hg8j6UN.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli          v1.3.0
@angular/animation          4.3.4
@angular/material          2.0.0-beta8

**Comment by CarstenHouweling** [comment] 2017-08-16 05:53
Can confirm

@angular/cli v1.2.6
@angular/animation v4.3.3
@angular/material v2.0.0-beta.8

**Comment by willshowell** [comment] 2017-08-16 15:23
Duplicate of https://github.com/angular/material2/issues/5755

**Comment by jelbourn** [comment] 2017-08-16 21:29
Duplicate of #5755

**Closed by jelbourn** 2017-08-16 21:29 UTC
