### ISSUE TITLE
ng-content doesn't work with ng-container

### ISSUE THREAD

**Issue by greenGoby** [angular/material2#8258] opened 2017-11-06 21:27 UTC
#### Bug, feature request, or proposal:
When you have an ng-container, transclusion doesn't work

#### What is the expected behavior?
I would expect the selector of the transclusion to pull in the element

#### What is the current behavior?
The element is not selected for

#### What are the steps to reproduce?
http://plnkr.co/edit/NqAbVgUclJkOSQCrS97H?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Found when putting md-error inside ng-container.  md-input-field selector for md-error does not work
https://github.com/angular/material2/blob/9b4f4355bc89cb83295f10b8d1bea6ba3ab4d6d5/src/lib/form-field/form-field.html#L47

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5

**Comment by willshowell** [comment] 2017-11-06 22:01
Unfortunately, this is expected behavior in Angular. See https://github.com/angular/material2/issues/5263, https://github.com/angular/material2/issues/5292, and https://github.com/angular/material2/issues/6625.

**Comment by josephperrott** [comment] 2017-11-06 22:13
Closing as duplicate of the issues above:

> This is a consequence of how content project works; only the top-level elements inside the container are projected, so adding the intermediate container make it not work. Something to potentially file an issue on for Angular Core.

**Closed by josephperrott** 2017-11-06 22:13 UTC

**Comment by greenGoby** [comment] 2017-11-06 22:28
Sorry for that I actually meant to put that on the angular core one.  Sounds like they are already aware though.
