### ISSUE TITLE
Select form gets sluggish and not responsive  

### ISSUE THREAD

**Issue by azizalali** [angular/material2#7974] opened 2017-10-23 12:06 UTC
I have raised this issue [in more details here](https://stackoverflow.com/questions/46882661/angular-material-causing-components-rendering-repeatedly-when-navigation). The dropdown list shows with no problem. Once an item is selected, the whole menu gets sluggish and not responsive unless page is refreshed. 

Any idea?

**Comment by willshowell** [comment] 2017-10-23 15:42
Can you create a reproduction?

**Comment by azizalali** [comment] 2017-10-24 13:31
yes!

**Comment by jelbourn** [comment] 2017-10-29 19:54
Duplicate of #5113 

(I assume for lack of other information)

**Closed by jelbourn** 2017-10-29 19:54 UTC
