### ISSUE TITLE
Add another Input to allow "All" option in table Paginator

### ISSUE THREAD

**Issue by ienzam** [angular/material2#9746] opened 2018-02-02 00:22 UTC
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
In Paginator, I expect to show users an option to show the whole table, so page size dropdown list will contain an option like "All" [10, 20, 50, All]

#### What is the current behavior?
In current api, we can only give numeric options and no way to add custom options in Paginator (may be if we hack the i10n, but not desirable).

#### What is the use-case or motivation for changing an existing behavior?
Same table can show few rows for small customers and a lot of rows for big customers.
For small tables, customers want to see the whole table together.
Sometimes for big tables also, customers want to see the whole table for easy comparison.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All.

#### Is there anything else we should know?
One issue with "All" is that for some tables, we may not know how many rows exist.
That's why having an opt-in option will be great.

**Comment by andrewseguin** [comment] 2018-04-23 17:41
Dupe of #8150

**Closed by andrewseguin** 2018-04-23 17:41 UTC
Labels: feature
