### ISSUE TITLE
 md-sidenav-container > div.mat-drawer-content unwanted margin

### ISSUE THREAD

**Issue by mohitook** [angular/material2#6958] opened 2017-09-09 12:16 UTC
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
There should be no unnecessary margin between the sidenav and the normal content.

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/15103326/30240042-e902678e-9568-11e7-96ab-24b66ca2f726.png)

#### What are the steps to reproduce?
`<md-toolbar class="mat-elevation-z5" color="primary">

    
    <button md-button routerLink="/">
      <md-icon>home</md-icon> 
          {{title}}</button>
  
      
      <span class="fill-remaining-space"></span>
      <div fxLayout="row" fxShow="false" fxShow.gt-sm>
          <button md-button routerLink="/products">Products</button>
          <button md-button routerLink="/dashboard">Dashboard</button>
      </div>
      <button md-button [md-menu-trigger-for]="menu" fxHide="false" fxHide.gt-sm>
       <md-icon>menu</md-icon>
      </button>

  </md-toolbar>

  <md-menu x-position="before" #menu="mdMenu">
      <button md-menu-item routerLink="/products">Products</button>
      <button md-menu-item routerLink="/dashboard">Dashboard</button>
      
  </md-menu>

<md-sidenav-container class="myTestClass">

  <md-toolbar color="primary" style="margin-left:0px">
      <button *ngIf="isMobileView" md-icon-button (click)="sidenav.toggle()">
          <md-icon class="md-24" >menu</md-icon>
      </button>
  </md-toolbar>

    
    <md-sidenav #sidenav class="app-sidenav"  mode="{{isMobileView?'over':'side'}}" opened="{{!isMobileView}}" disableClose="{{!isMobileView}}">
      <md-nav-list >
          <a md-list-item (click)="onLinkClick(sidenav)" >Majom Csimpánz Viziló</a>
          <a md-list-item href="page2.html">Page 2</a>
          <a md-list-item href="page3.html">Page 3</a>
      </md-nav-list>
    </md-sidenav>
        
          <div class="app-content" style="padding-top:50px;"
          >
          <router-outlet></router-outlet>
        </div>

</md-sidenav-container>`

Please ignore the unnecessary codes.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
newest

#### Is there anything else we should know?
After I resize the window and the sidenav goes to mobile mode, and back -> the unwanted margin is gone...

**Comment by willshowell** [comment] 2017-09-09 16:14
Can you reproduce in a plunker?

**Comment by mohitook** [comment] 2017-09-09 18:31
Plnkr :
http://plnkr.co/edit/etkptgACMyo2Ty0SUyjX?p=preview
Unfortunately I  can't reproduce this behaviour.. but I have an idea:
the problem is with this element:
md-sidenav-container > div.mat-drawer-content
here:
![image](https://user-images.githubusercontent.com/15103326/30242803-8c52ebc8-959d-11e7-9846-540687c2099c.png)

The margin-left is the property what is wrong. The interesting thing is that is is a counted value based on the sidenav's width. I don't know why but it adds + a few pixel to it what makes this issue..

**Comment by willshowell** [comment] 2017-09-10 15:27
This happens consistently? Can you show the styles and computed styles of the `md-sidenav`? Since you can't replicate in a fresh plunker, it sounds like you may have some overriding css somewhere else.

**Comment by sina-masoud-ansari** [comment] 2017-09-11 00:19
I'm having the same issue, sidenav-wdith 250px, margin-left on Safari 399px.

**Comment by mohitook** [comment] 2017-09-11 10:20
so the problem is real. I won't use scss until I have no other option, but thanks for the workaround!

**Comment by dereekb** [comment] 2017-09-12 17:37
I've had this issue on macOS Safari too, but haven't seen it appear in Chrome.

**Comment by josephperrott** [comment] 2017-09-27 22:17
It looks like the logic controlling this was updated in #6712 

If you are still seeing this issue please provide a reproduction plunker/stackblitz for us to investigate.

**Comment by dereekb** [comment] 2017-09-27 22:55
I’ll try and reproduce it when I get a chance, but it only occurred in Safari. I’ll try it on both Sierra and High Sierra.

**Comment by tylerbrockett** [comment] 2017-10-05 22:53
Could it be related to the scrollbar? I can confirm the issue, it looks about the width of a scrollbar for me.

**Comment by tylerbrockett** [comment] 2017-10-06 17:19
It looks like it might be related to the scrollbar. My sidenav has looked like OP's at one point, and also [looked like this at another](https://imgur.com/PwYZtxw)

**Comment by craftyInstigator** [comment] 2017-10-06 23:25
In the release 2.0.0-beta.12 the right margin is randomly miscalculated for mat-sidenav-content when sidenav in in side mode. If the sidenav mode is dynamically switched between over and side, the problem randomely resolves itself. There must be some kind of timing issue in calculating the mat-sidenav-content right margin.

**Comment by Karankang007** [comment] 2017-10-20 14:31
This issue is reproducible for me.

**Comment by afarbman** [comment] 2018-01-10 12:02
having the same issue

**Comment by mmalerba** [comment] 2018-01-17 00:21
This sounds like it might be related to https://github.com/angular/material2/issues/5698 which I filed a chrome bug for: https://bugs.chromium.org/p/chromium/issues/detail?id=787628

**Comment by mmalerba** [comment] 2018-01-27 04:52
Those of you experiencing issues, have you tried the [`autosize`](https://material.angular.io/components/sidenav/overview#resizing-an-open-sidenav) option? does it help?

**Comment by tpeyrard** [comment] 2018-02-05 13:15
@mmalerba it's worse because it makes the problem appear 100% of time.

If I open the sidenav, it adds 215px margin-left, that I don't want. However, if I load another component while the sidenav is open, the 215px are correctly applied (they're applied from the left of the screen, not from the right of the sidenav.

Tried on Firefox 58.

**Comment by mmalerba** [comment] 2018-02-05 17:40
@tpeyrard can you provide a stackblitz repro? here's our template: https://stackblitz.com/edit/angular-material2-issue

**Comment by ishan123456789** [comment] 2018-02-13 12:30
Removing all the animations helped me fix the issue.Hope this helps someone.

**Comment by specialkk** [comment] 2018-02-14 23:56
I believe this is a dupe of #5698

**Comment by mmalerba** [comment] 2018-02-16 00:20
I'm assuming this is the same issue as #9837, check out the plunker I posted on that issue for a workaround

**Closed by mmalerba** 2018-02-16 00:20 UTC
Labels: P3: important
