### ISSUE TITLE
Snackbar margin-bottom animation overlap

### ISSUE THREAD

**Issue by avechuche** [angular/material2#10870] opened 2018-04-15 20:41 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Maybe it would be better than before the new message is shown, the previous one has been completely hidden.

#### What is the current behavior?
If you try to open the snackbar several times, the animations overlap. 

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-pkf1xq

I have added a bottom margin to the snackbar and i see at a small visual error when wanting to open the message several times, the animations overlap.

Click several times on the button to show the snackbar issue

> .cdk-overlay-pane {
>   margin-bottom: 15px !important;
> }

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material 5.2.4
Browser: All

**Comment by donroyco** [comment] 2018-04-16 06:08
You should only display one snackbar at a time as per the [official Material Design guidelines](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage).

> **[Consecutive snackbars](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage)**
There is _only ever one snackbar displayed_. When a second snackbar is triggered while the first is displayed, the first should start the contraction motion downwards before the second one animates upwards.

**Comment by avechuche** [comment] 2018-04-16 11:45
Hi @donroyco Yes, I understand that, what I think is wrong, is that the animations overlap one over the other while the first one is hidden and the second is shown

**Comment by josephperrott** [comment] 2018-07-27 20:36
Closing as this is working as expected.  The overlap you are seeing is caused by margin-bottom that you have added to `.cdk-overlay-pane'.  If you add `overflow: hidden;` to the `.cdk-overlay-pane` styling you will see that the overlap does not occur since the snackbar is positioned beyond the edge of the `<cdk-overlay-pane>` element.  You can see this in [this fork](https://stackblitz.com/edit/angular-pkf1xq-wnqxq8?file=styles.css) of your stackblitz you provided

**Closed by josephperrott** 2018-07-27 20:36 UTC
