### ISSUE TITLE
FocusMonitor, still element focused when opening mat menu

### ISSUE THREAD

**Issue by ricardojbertolin** [angular/material2#10378] opened 2018-03-12 17:15 UTC
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
When opening a matMenu inside a component using cdkMonitorSubtreeFocus directive, not to lose focus

#### What is the current behavior?
When the matMenu is opened, the output of cdkMonitorSubtreeFocus (called cdkFocusChange) emits empty (that means that it has lost focus). It happens only if you have a mat-menu-item.

#### What are the steps to reproduce?
https://angular-material2-issue-es3jey.stackblitz.io/
By following the steps, you click on tab (this tab has the cdkMonitorSubtreeFocus and its output is binding to a class). Then, open the matMenu and you can check that it lost the focus.

#### What is the use-case or motivation for changing an existing behavior?
If you have a component focused and open a matMenu inside, the focus is lost. For example, if you have some classes attached to such component on focus, you lost it.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest material and angular versions

**Comment by crisbeto** [comment] 2018-03-13 10:59
Your toggle loses focus, because Material moves focus into the menu once it's opened, which ends up re-closing the menu.

**Comment by ricardojbertolin** [comment] 2018-03-13 13:35
Yes, this is true. But what I'm proposing is that you don't lost focus on the directive cdkMonitorSubtreeFocus - in other words, that the menu is considered a children of my component.

**Comment by crisbeto** [comment] 2018-03-13 13:39
API-wise that would be very confusing, in addition to breaking the accessibility of the menu.

**Comment by josephperrott** [comment] 2018-03-26 15:21
Closing as this is working as intended.

**Closed by josephperrott** 2018-03-26 15:21 UTC
