### ISSUE TITLE
Cannot explicitly focus Input in Overlay

### ISSUE THREAD

**Issue by M4R1KU** [angular/material2#6415] opened 2017-08-11 13:14 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I've created a Directive which can focus or select an input field. It works fine (as seen in the Plunker) as long at it is not in an overlay container. It should also work in the overlay.

#### What is the current behavior?
The input is not focused when opening the overlay.

#### What are the steps to reproduce?
I added a demo for the normal use of the directive and the overlay use.
Plunker link: http://plnkr.co/edit/X7y15FUpjRdwCeIivDbI?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material Beta 7

#### Is there anything else we should know?
I am not really that sure whether it is a bug or if I am missing some important things about the behaviour of overlays.

**Comment by leocaseiro** [comment] 2017-08-15 06:09
Perhaps it's working on `@angular/material@2.0.0-beta.8`.

I updated the material on your plunker and it seems working check it out:
http://plnkr.co/edit/aFXWjomQbdtZv0jwANeT?p=preview

**Comment by josephperrott** [comment] 2017-09-27 18:10
Closing, it looks like the reproduction you provided no longer shows this issue as the `input` autofocuses.

**Closed by josephperrott** 2017-09-27 18:10 UTC

**Comment by M4R1KU** [comment] 2017-09-28 19:01
@josephperrott Did you change anything? For me it still does not work.
