### ISSUE TITLE
Support disable drag

### ISSUE THREAD

**Issue by TKul6** [angular/material2#13787] opened 2018-10-24 11:59 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Have the ability to disable the drag behavior in certain cases.

#### What is the current behavior?
Any element with **dragData** directive can be dragged, event if it makes no since to drag it in a certain scenario.

#### What are the steps to reproduce?
Just add div with **cdkDrag** directive in it and try to disable the behavior.

#### What is the use-case or motivation for changing an existing behavior?
In some cases the entities with the **cdkDrag** directive are disable (like a read only state, you can view the items but can't preform any action).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular CLI: 7.0.2
Node: 9.0.0
OS: win32 x64
Angular: 7.0.0
... compiler, core

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.2
@angular-devkit/core         7.0.2
@angular-devkit/schematics   7.0.2
@angular/cli                 7.0.2
@schematics/angular          7.0.2
@schematics/update           0.10.2
rxjs                         6.3.3
typescript                   3.1.3
material                               7.0.1

**Comment by crisbeto** [comment] 2018-10-24 13:08
Duplicate of https://github.com/angular/material2/issues/13651.

**Closed by crisbeto** 2018-10-24 13:08 UTC
