### ISSUE TITLE
Unexpected navigation behavior in MatAutocomplete when styling options

### ISSUE THREAD

**Issue by varunrramani** [angular/material2#13207] opened 2018-09-20 05:50 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Scrolling should be consistent regardless of styling applied to options in autocomplete panel

#### What is the current behavior?
When styling the options for example changing the font size and line height of the options in autocomplete panel and navigating using keyboard, selected option is not the last option as it would have been if styling was not provided.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-vbcan5?file=app/autocomplete-overview-example.html

Please look at the second autocomplete panel.

#### What is the use-case or motivation for changing an existing behavior?
Should be able to stylize the options in dropdown panel.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Able to replicate on the latest version of Angular and Material.
Tested on Windows 7, Chrome 68

**Comment by crisbeto** [comment] 2018-09-20 18:28
It's because we assume that the options will have a particular height. Closing as a duplicate of https://github.com/angular/material2/issues/3419.

**Closed by crisbeto** 2018-09-20 18:28 UTC

**Comment by varunrramani** [comment] 2018-09-21 06:07
Is there a solution we can apply so this works?
