### ISSUE TITLE
Publish saas files with npm package

### ISSUE THREAD

**Issue by TheCaptainDate** [angular/material2#595] opened 2016-06-01 08:35 UTC
Hello!

Currently scss files are not published together with @angular2-material/core, so it is impossible to use material2 styles in my own component "out of box".
Can you publish scss files inside core package to allow people use them as base for their own components?

**Comment by jelbourn** [comment] 2016-06-01 16:24
Dupe of #533

**Closed by jelbourn** 2016-06-01 16:24 UTC
