### ISSUE TITLE
mdInput Multi Line Suppport

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#565] opened 2016-05-28 17:42 UTC
Hi,

Does mdInput support multiple lines input? As per the design specs (https://www.google.com/design/spec/components/text-fields.html) it should support the following types:

Single-line
Multi-line
Full-width

**Comment by fxck** [comment] 2016-05-28 18:06
https://github.com/angular/material2/issues/546

**Comment by jelbourn** [comment] 2016-05-29 16:25
Dupe of #546

**Closed by jelbourn** 2016-05-29 16:25 UTC
