### ISSUE TITLE
mat-option: Unable to Set Height

### ISSUE THREAD

**Issue by mikeomeara1** [angular/material2#8054] opened 2017-10-26 19:23 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Changing the height of a `mat-option` element shouldn't impact where the selected item appears inside 
 `mat-select-content`

#### What is the current behavior?
Pre Beta.12 setting an explicit height for `mat-option` worked as excepted. Post Beta.12 modifying the option height makes the selected option appear outside the visible `mat-select-content` area.

#### What are the steps to reproduce?
[https://plnkr.co/edit/CULSXZovARH9HdKFm3d4?p=preview](https://plnkr.co/edit/CULSXZovARH9HdKFm3d4?p=preview)

This is a standard `mat-select` with an explicit height set on `mat-option` (35px).

1. Open select
2. Selected item is not visible

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.4.3
Material: 2.0.0-beta.12
OS: Windows 10
Typescript: 2.2.2
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Many apologies guys if this one is already logged too. I am searching around before logging but sometimes it's hard to find open/related issues.

Thanks so much!

**Comment by crisbeto** [comment] 2017-10-26 20:18
Closing as a duplicate of https://github.com/angular/material2/issues/3419. Also FWIW, setting the option height has never been supported.

**Closed by crisbeto** 2017-10-26 20:18 UTC

**Comment by mikeomeara1** [comment] 2017-10-26 20:45
@crisbeto Fair enough on the dupe I suppose but I can confirm to you that explicit height on `mat-option` (`md-option`) did in fact work in Beta.10 and stopped working sometime between Beta.11-Beta.12.

[https://plnkr.co/edit/RkT5Y7JPq5mmqrp9A1QY?p=preview](https://plnkr.co/edit/RkT5Y7JPq5mmqrp9A1QY?p=preview)

**Comment by crisbeto** [comment] 2017-10-26 20:48
Yep it may have worked, but all our calculations are based around a certain height for the options.

**Comment by mikeomeara1** [comment] 2017-10-26 20:56
Bummer. OK thanks for clearing that up.
