### ISSUE TITLE
Append placeholder required asterix to Validators.required

### ISSUE THREAD

**Issue by tomgruszowski** [angular/material2#10261] opened 2018-03-04 19:31 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Input label/placeholder asterix (*) is appended based on FormControl - Validators.required and not just the HTML 'required' element attribute. The code should check the required attribute and the FormControl Validators for auto inserting the asterix.

#### What is the current behavior?
Required asterix only works with the **input required** attribute.

#### What is the use-case or motivation for changing an existing behavior?
Reactive forms moves the validation complexity away from markup and onto the code; this forces the markup and code to have the same duplicate required validation.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest ng/mat 5.x

**Comment by crisbeto** [comment] 2018-03-05 02:48
Closing as a duplicate of https://github.com/angular/material2/issues/2574.

**Closed by crisbeto** 2018-03-05 02:48 UTC
