### ISSUE TITLE
md-tab-group selected index does not update immediately after adding a tab

### ISSUE THREAD

**Issue by dmacfarlane** [angular/material2#1885] opened 2016-11-16 15:01 UTC
#### Bug, feature request, or proposal:
Bug or possibly usage clarification

#### What is the expected behavior?
Setting the `selectedIndex` immediately after adding a new tab should cause the new tab to be selected.

#### What is the current behavior?
The tab selection does not change.

#### What are the steps to reproduce?
`this.tabs.push('New');`
`this.index = this.tabs.length - 1;`

http://plnkr.co/edit/Mxs2Dmo8YWBEkuBLAAc4?p=preview

#### What is the use-case or motivation for changing an existing behavior?
To display a new tab after it has been added.

#### Which versions of Angular, Material, OS, browsers are affected?
Since angular 2.0.0 final, material 2.0.0-alpha.8

#### Is there anything else we should know?
The desired behavior was working with previous version of angular < ~2.0.0-rc.4

There is a `setTimeout` workaround in the Plunker. Please clarify if that is required.

**Comment by jelbourn** [comment] 2016-11-16 16:42
@andrewseguin dupe of what you're already working on?

**Comment by andrewseguin** [comment] 2016-11-16 17:01
Yes, this is a dupe of #1692 and in progress right now

**Closed by andrewseguin** 2016-11-16 17:01 UTC
