### ISSUE TITLE
Material doesn't play well with Karma and the CLI

### ISSUE THREAD

**Issue by farley911** [angular/material2#4438] opened 2017-05-09 00:03 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When running `ng test` tests should run without warning about Angular Material or HammerJS

#### What is the current behavior?
Any component that involves Angular Material will throw a warning when running `ng test` which causes the results to be cluttered and difficult to read.

#### What are the steps to reproduce?

- Create a new project with the CLI
- Add Angular Material to the project
- Create a custom theme and set Material to use it for all components
- Add a Angular Material component (i.e. md-input-container) to a template
- Run `ng test`
- The tests will log warnings that say "Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming" and "Could not find HammerJS. Certain Angular Material components may not work correctly."

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
Test results should be clear and uncluttered with warnings.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.0, Angular CLI 1.0.1, Angular Material 2.0.0-beta.3, Karma 1.4.1

#### Is there anything else we should know?
n/a

**Comment by willshowell** [comment] 2017-05-09 12:31
Dupe of #4056

**Comment by jelbourn** [comment] 2017-05-11 23:53
Dupe of #4056 as @willshowell 

I consider this to be something that's just missing guidance / documentation

**Closed by jelbourn** 2017-05-11 23:53 UTC
