### ISSUE TITLE
Change the position of the overlay of md-select

### ISSUE THREAD

**Issue by kirapoetica974** [angular/material2#7147] opened 2017-09-18 16:11 UTC
#### Bug, feature request, or proposal:
Change the position of the overlay of the md-select

#### What is the expected behavior?
The position is calculate automatically by the private method _calculateOverlayPosition and the overlay is placed over the select field.

#### What is the current behavior?
The overlay can be placed on the bottom of the select field.

**Comment by josephperrott** [comment] 2017-09-25 19:01
Closing as this is working as intended as the overlay is being placed automatically by the position rules.

**Closed by josephperrott** 2017-09-25 19:01 UTC

**Comment by avinashrd** [comment] 2018-04-27 11:02
@josephperrott Can you please let me know if it is possible to fix the postion of the mat-select overlay to the bottom of the select box?
