### ISSUE TITLE
[menu] inconsistent scroll strategy between body and cdkScrollable

### ISSUE THREAD

**Issue by willshowell** [angular/material2#8278] opened 2017-11-07 16:53 UTC
#### Bug, feature request, or proposal:
Bug

#### Current behavior

On [material.angular.io](https://material.angular.io/components/menu/overview):

* Mobile: scroll is caught and menu repositions itself
* Desktop: backdrop seems to block scrolling events and cannot scroll while menu is open

#### Expected behavior

Menu trigger dictates reposition strategy. If that's not ideal or expected, then block should be used.

#### What are the steps to reproduce?

Can be seen on docs site and demo-app. The difference between mobile and desktop is a result of the fixed sidenav, specifically use of `cdkScrollable`, not a difference in browsers.

cc @crisbeto

**Comment by crisbeto** [comment] 2017-11-09 08:55
Will be sorted out by https://github.com/angular/material2/pull/7779. Also a dupe of https://github.com/angular/material2/issues/6927.

**Closed by crisbeto** 2017-11-09 08:55 UTC
