### ISSUE TITLE
Fix #12245 does not seem to be part of the released package 6.4.1

### ISSUE THREAD

**Issue by benoitbzl** [angular/material2#12386] opened 2018-07-26 09:38 UTC
#### Bug:

The fix #12245 does not seem to be part of the generated npm package located at https://registry.npmjs.org/@angular/material/-/material-6.4.1.tgz (see function MatTabGroup.prototype.ngAfterContentInit function for example).

The release source archive does contain the fix.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1
Angular Material 6.4.1
Windows 10
Typescript 2.7.2
Chrome 67

**Comment by DevVersion** [comment] 2018-07-26 11:41
Can reproduce that as well. (https://unpkg.com/@angular/material@6.4.1/bundles/material-tabs.umd.js).

@josephperrott can you have a look?

**Comment by josephperrott** [comment] 2018-07-27 17:19
It looks like something went wonky with our release process and the fix should be included in our next patch release.

**Comment by josephperrott** [comment] 2018-07-30 22:43
Closing as this change is included in [`6.4.2`](https://unpkg.com/@angular/material@6.4.2/bundles/material-tabs.umd.js)

**Closed by josephperrott** 2018-07-30 22:43 UTC
