### ISSUE TITLE
Strange border on the first and last <mat-expansion-panel> children of <mat-accordion> when using the Chrome browser

### ISSUE THREAD

**Issue by asmolenic** [angular/material2#14686] opened 2018-12-31 12:54 UTC
#### What is the expected behavior?
Identical look and feel across all major/known/usual browsers.

#### What is the current behavior?
Currently when using the **Chrome** browser I get strange looking `<mat-expansion-panel>` borders, more specifically on a `<mat-accordion>`'s first and last `<mat-expansion-panel>` elements during their **collapsed** state.

#### What are the steps to reproduce?
The issue can be observed at https://material.angular.io/components/expansion/examples on the **collapsed** `<mat-expansion-panel>` elements when using the latest version of Chrome (71.0.3578.98 (Official Build) (64-bit)).
https://www.screencast.com/t/HWwmpIfA6ksg

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
The issue seems to be related to "@angular/material" 7.2.0 as it can be observed in the official documentation pages. I've only been able to detect this issue using Chrome (71.0.3578.98 (Official Build) (64-bit) on my PC. On the mobile Chrome browser the issue is not manifesting.
The issue is **NOT** manifesting on IE 11.472.17134.0 (update versions 11.0.101), Microsoft Edge 42.17134.1.0 and Firefox 64.0 (64-bit).

#### Is there anything else we should know?
It seems like the **box-shadow** of the first and last `<mat-expansion-panel>` elements is somehow shifted towards the bottom-right corner as it is too thick on the bottom and right side of those `<mat-expansion-panel>` elements and it is not present almost at all on the left side.

**Comment by asmolenic** [comment] 2019-01-11 16:01
Has anyone else encountered this issue? Can anyone reproduce it? One would only have to visit https://material.angular.io/components/expansion/examples and play with the examples

**Comment by sambaptista** [comment] 2019-01-14 16:02
I confirm on chrome  71.0.3578.98 and angular material 7.1.1. I can reproduce on the demo stackblitz (simply by adding a third panel) and on my local project.

**Comment by earshinov** [comment] 2019-02-08 11:46
I experience a related issue of missing shadows on expansion panel elements in collapsed state except for first and last.

StackBlitz: https://stackblitz.com/edit/angular-material-expansion-panel-shadows

![missing shadow](https://user-images.githubusercontent.com/52021/52476625-3a11e300-2bb0-11e9-8226-c56980a7b2e4.png)

Chrome 71.0.3578.98 (Official Build) (64-bit)

**Comment by sambaptista** [comment] 2019-02-08 11:54
In fact, the shadow is on the left on all but first and last items.

![capture 2019-02-08 at 12 50 05](https://user-images.githubusercontent.com/5111137/52476811-25c5ea00-2ba0-11e9-831c-76d9d3fd59d8.png)

**Comment by earshinov** [comment] 2019-02-09 07:08
Did anyone find a related issue in the bug tracker of Chrome (https://bugs.chromium.org/p/chromium/issues/list) or perhaps file a new one? This case is easily reproducible and could help Chrome devs to fix the bug.

**Comment by asmolenic** [comment] 2019-02-11 08:39
> Did anyone find a related issue in the bug tracker of Chrome (https://bugs.chromium.org/p/chromium/issues/list) or perhaps file a new one? This case is easily reproducible and could help Chrome devs to fix the bug.

I didn't file a new bug as I don't know yet where the issue originates from, Chrome or Angular Material.

**Comment by earshinov** [comment] 2019-02-11 15:57
Here is the bug: https://bugs.chromium.org/p/chromium/issues/detail?id=878195.
Should be fixed in Chrome 72.

**Comment by earshinov** [comment] 2019-02-11 16:02
For reference, here is a screenshot taken programmatically in Chrome 66:

![screenshot chrome66](https://user-images.githubusercontent.com/52021/52575319-07295280-2e2f-11e9-8f8c-cd76822d8dbb.png)

Script (index.js):

```
const puppeteer = require('puppeteer');

function timeout(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
};

(async() => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setViewport({width: 640, height: 480})
    await page.goto('https://angular-material-expansion-panel-shadows.stackblit$
    await timeout(20000)
    await page.screenshot({path: 'example.png'});
    browser.close();
})();
```

Requirements:
1. NodeJS
2. npm package `puppeteer` for the required version of Chrome (https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md)

**Comment by asmolenic** [comment] 2019-02-15 14:13
Chrome 72 has landed and the issue seems fixed. Can anyone else confirm so I can close the issue?

**Comment by fjauer** [comment] 2019-02-15 15:07
it works for me (Chrome 72.0.3626.96)!

**Closed** 2019-02-18 14:59 UTC
