### ISSUE TITLE
Provide "Decade" calendar starting view

### ISSUE THREAD

**Issue by bratanp9** [angular/material2#9160] opened 2017-12-29 10:56 UTC
#### Bug, feature request, or proposal:
Please include a feature where the user can not only select a Month and Year view, but also a Decade view.

#### What is the expected behavior?
As a user, I would like to be able to move a decade back/forward using the calendar widget in order to quickly reach historical dates. 
As a developer, I should be able to set the starting view as Decade.

#### What is the current behavior?
As a user, I am only able to move back/forward one year/month at a click.
As a developer, I am only able to set the starting view as Month or Year.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

Click on the date toggle button and open the calendar widget. You can only switch between Month and Year view.

#### What is the use-case or motivation for changing an existing behavior?

Application which shows historical events and allows users to type in a date and use a calendar widget. User should be able to go through time in a quicker manner. E.g. to access "Start of First World War in 1914", he should not be required to press the back button 103 times.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
_Angular version:_ 5.0.0
_Material version:_ 5.0.0-rc.1
_OS:_ Windows 10 Pro
_TypeScript version:_ 2.3.5
_Browsers:_ 
Microsoft Edge 40.15063.674.0 (PC)
Google Chrome 62.0.3202.94 (PC)
Firefox Quantum 57.0 (PC)
Google Chrome 62.0.3202.84 (Android 6.0)

**Comment by dimitrov-db** [comment] 2017-12-29 12:34
+1,  this is a pain point for my users as well.

It's hard for people over 50 to register to my site. Most of them don't want to type in their date of birth and at the same time they get frustrated to click the back button 50+ times so they leave the site.

As this was causing a decrease in the conversion rate, I decided to remove the widget and force them to type in their date, however I'd love to reintroduce it.

**Comment by julianobrasil** [comment] 2017-12-29 12:52
Dupe of #5845.

It has already an aproved PR and will be available in the next minor release.

**Comment by jelbourn** [comment] 2018-01-02 23:21
Duplicate of  #5845

**Closed by jelbourn** 2018-01-02 23:21 UTC
