### ISSUE TITLE
In "mat-expansion-panel" there is a event called "opened"

### ISSUE THREAD

**Issue by rahul-tech** [angular/material2#7734] opened 2017-10-12 09:34 UTC
#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by TheRedD0t** [comment] 2017-10-12 09:43
Duplicate of #7733.

**Closed** 2017-10-12 10:49 UTC
