### ISSUE TITLE
Multiple MdDialog on IE11

### ISSUE THREAD

**Issue by ricio91** [angular/material2#7004] opened 2017-09-12 11:08 UTC
#### Bug, feature request, or proposal:
On IE11 i'm unable to open an MdDialog inside another MdDialog.
On Chrome and Firefox it works properly.

#### What is the expected behavior?
Open an MdDialog inside another MdDialog

#### What is the current behavior?
Nothing happens.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
IE 11

**Comment by mortenamby** [comment] 2017-09-12 13:50
Strange I thought I searched for IE 11 issues. Just close this one then.

**Comment by AlesDo** [comment] 2017-09-13 16:46
The same issue happens also in Edge with the beta.10 release with beta.8 it worked.

**Comment by crisbeto** [comment] 2017-09-13 18:34
Closing as a duplicate of https://github.com/angular/material2/issues/6719.

**Closed by crisbeto** 2017-09-13 18:34 UTC
