### ISSUE TITLE
Focus is getting lost only on second click outside component

### ISSUE THREAD

**Issue by vibingopal** [angular/material2#8317] opened 2017-11-08 21:37 UTC
#### Bug, feature request, or proposal:
Hi Team,

We are using material multi select component and the focus of the component is loosing only after two clicks outside
Below is the plunker:
https://plnkr.co/edit/D3RvLerihVtQOjMNNXva?p=preview 

 Material : 2.0.0-beta.12
Angular : 4.4.4

**Comment by julianobrasil** [comment] 2017-11-08 21:47
I tried your plunk over here and it worked fine. The focus is lost after the first click.

I tried it out on Windows 10 + Google Chrome

Anyway, if it's possible, try upgrading to Angular 5.0.0 and Material 5.0.0-rc0

**Comment by vibingopal** [comment] 2017-11-08 21:49
Thanks for the response . If you see the plunker, the value for the recent select will only getting updated after second click. Please check the console.

**Comment by julianobrasil** [comment] 2017-11-08 21:59
Look:

![image](https://media.giphy.com/media/l2QE2XjOFCBWF2d1e/giphy.gif)

**Comment by vibingopal** [comment] 2017-11-08 22:01
Ok Thanks. First time when you click Mushroom,Onions and then click outside why the component is still on focus mode(Blue Underline). There my problem exists.

**Comment by julianobrasil** [comment] 2017-11-08 22:16
Oh, now I see. I thought the component was keeping opened after the first click.

**Comment by vibingopal** [comment] 2017-11-08 22:19
Ok :) Any idea to resolve the issue ?

**Comment by julianobrasil** [comment] 2017-11-08 22:20
The problem seems to be the absence of the `<mat-form-field>` wrapping `<mat-select>` in the second example.

**Comment by vibingopal** [comment] 2017-11-08 22:25
mat-select exists within the mat-form-field. Is this an open issue-" focus won't get lost after a single click"?

**Comment by willshowell** [comment] 2017-11-08 22:42
@vibingopal if I understand what you're explaining, it is expected behavior. The first click outside the select panel is a click on the backdrop, which autofocuses the select again.

I think you'd be more interested in the `close` event than `blur`.

**Comment by josephperrott** [comment] 2017-11-08 23:16
Closing as this is working as intended.

As @willshowell said, when we click outside the panel and it closes the panel, the input is focused again.  This happens because we are returning focus to where the user placed focus when the menu was opened.

**Closed by josephperrott** 2017-11-08 23:16 UTC

**Comment by mhosman** [comment] 2017-12-18 02:28
This is happening with mat-menu-item too!

**Comment by salemdar** [comment] 2017-12-29 15:21
This is especially bothering if you are setting `{ updateOn: 'blur' }` on the form control. It should be somehow configurable.

**Comment by julianobrasil** [comment] 2017-12-29 15:32
@salemdar, take a look at #8905 (the last comments)

There's a proposed workaround over there for the datepicker. Maybe it fits in this case with some ajustments.
