### ISSUE TITLE
md-input placeholder does not move up after model update / also after *ngIf

### ISSUE THREAD

**Issue by ktersius** [angular/material2#4814] opened 2017-05-26 09:29 UTC
Running material beta 6 and ng 4.0.3, Chrome Version 58.0.3029.110 (64-bit)

I have two issues.

1. After loading and setting the model in the promise .then() the input placeholders do not not move up. I can solve this by calling ChangeDetectorRef.detectChanges() after setting the model, which should not be needed correct? Or by interacting with the form. 

``` typescript
 this.clientService.getClient(clientId)
        .then((client: any) => {
          this.client = new Client(client);
          // this.ref.detectChanges();
        });
```
![md input issue 1](https://cloud.githubusercontent.com/assets/6417718/26489141/783deed4-4206-11e7-97c9-0e030562ee0d.gif)

2. I have a group box selection and if I toggle this, which causes elements  to be shown or hidden the placeholders again fail to move up.

An html snippet of the template with the *ngIf
``` html
    <md-radio-group  fxFlex="0 1 auto" [(ngModel)]="client.type">
      <md-radio-button value="Personal">Personal</md-radio-button>
      <md-radio-button value="Business">Business</md-radio-button>
    </md-radio-group>

   <div fxFlex="50" fxFlex.lt-md="100">
      <md-input-container>
        <input mdInput [(ngModel)]="client.name" placeholder="Name" required>
      </md-input-container>
    </div>

    <div *ngIf="isPersonal()" fxFlex="50" fxFlex.lt-md="100">
      <md-input-container>
        <input mdInput [(ngModel)]="client.surname" placeholder="Surname" required>
      </md-input-container>
    </div>
```

![md input issue 2](https://cloud.githubusercontent.com/assets/6417718/26489160/8f280eb8-4206-11e7-88c0-8b88434d995c.gif)

**Comment by hecof** [comment] 2017-05-28 15:05
Same behavior:
`<div style="display:flex; flex-direction: column;" *ngIf="_showProcess">
        <md-input-container>
          <input mdInput placeholder="Module">
        </md-input-container>
        <div>
          <button md-raised-button color="primary" (click)="_process($event)">Process</button>
        </div>
    </div>`

**Comment by YeomansIII** [comment] 2017-05-30 17:46
Same issue here.
This is only occurring when using OnPush change detection strategy. Fields are populating but the placeholder is not moving up.

<img width="970" alt="screen shot 2017-05-30 at 13 40 34" src="https://cloud.githubusercontent.com/assets/3809115/26596872/2fe9f214-453e-11e7-814f-79621bc3df8b.png">

```
  editProfile() {
    this.editData = {};
    this.editData.name = this.user.name;
    this.editData.username = this.user.username;
    this.editData.website = this.user.website;
    this.editData.biography = this.user.biography;
    this.editingProfile = true;
    this.ChangeDetectorRef.markForCheck();
  }
```

**Comment by willshowell** [comment] 2017-05-30 20:07
Seems like a dupe of https://github.com/angular/material2/issues/3005?

**Comment by YeomansIII** [comment] 2017-05-30 20:24
@willshowell Looks like it, thanks. Hopefully we can get some progress, that has been open since February.

**Comment by mmalerba** [comment] 2017-05-30 23:46
Closing as dupe

**Closed by mmalerba** 2017-05-30 23:46 UTC

**Comment by ktersius** [comment] 2017-06-01 12:31
Hi this occurs on Default strategy as well.
```typescript
@Component({
  selector: 'client-info',
  templateUrl: 'client-info.component.html',
  styleUrls: ['client-info.component.scss'],
  changeDetection: ChangeDetectionStrategy.Default
})
```

**Comment by willshowell** [comment] 2017-06-01 13:17
@ktersius do you mind reproducing in a plunker?

**Comment by ktersius** [comment] 2017-06-01 13:47
@willshowell I've changed those forms to model based forms and I'm not experiencing the issue any longer.
