### ISSUE TITLE
[Tabs] Ink bar doesn't show if tabs are initially hidden

### ISSUE THREAD

**Issue by pedrolsamaral** [angular/material2#8149] opened 2017-10-31 11:18 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The ink-bar should automatically show whenever tabs are shown

#### What is the current behavior?
If tabs are not shown when the page is loaded (i.e. a container div is not rendered or not displayed), when the tabs show, the ink-bar won't appear. After selecting another tab if will start working as it should

#### What are the steps to reproduce?
https://plnkr.co/edit/rzkGgw8co9lTEClQwpQb?p=preview

Click on button 'Show'

#### What is the use-case or motivation for changing an existing behavior?
We only want to show content when all data is fetched from the server, for that purpose the div container that wraps all content is hidden until the end of the data retrieval.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.5
Material 2.0.0-beta.12
TypeScript 2.3.3
Windows 7
Chrome

**Comment by julianobrasil** [comment] 2017-10-31 12:13
There are many issues aparently related to this one: #5269, #7274, #5932, #5505, #5503

**Comment by josephperrott** [comment] 2017-10-31 16:02
Closing as duplicate of #7274

**Closed by josephperrott** 2017-10-31 16:02 UTC
