### ISSUE TITLE
Issue: md-menu doesn't close if clicking outside the menu on another md-component

### ISSUE THREAD

**Issue by palsch** [angular/material2#1410] opened 2016-10-03 11:59 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Menu should close if clicking outside the menu independent of the component clicked on.

#### What is the current behavior?
It stays oppened.
The only way to close it is to:
* click on a menu button
* click on a place on the page without components
* click on the small place on the menu between menu-button and the corner.

#### What are the steps to reproduce?
I was not able to create a plunker example.

#### What is the use-case or motivation for changing an existing behavior?
Google Material specification for Dismissing menus:
"Dismiss a menu by tapping outside of the menu, or by tapping the emitting button (if visible).
Selecting a menu item should also dismiss the menu. An exception is when a menu allows for multiple items to be chosen, for example, by using checkmarks."
--> "Dismiss a menu by tapping outside of the menu" doesn't work.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular v2.0.0, Material 2.0.0-alpha.8-2,
Tested on Windows with latest Chrome and Firefox

#### Is there anything else we should know?
Maybe related to #1360

**Comment by fxck** [comment] 2016-10-03 12:27
happened to me when I had menu inside sidenav.. when you close sidenav, menu stays open and is impossible to close

**Comment by Ploppy3** [comment] 2016-10-03 15:05
Duplicate of [https://github.com/angular/material2/issues/1360](url)

**Comment by jelbourn** [comment] 2016-10-19 15:51
Dupe of #1360 (same underlying issue)

**Closed by jelbourn** 2016-10-19 15:51 UTC
