### ISSUE TITLE
Expansion panel closes on data refresh

### ISSUE THREAD

**Issue by theunreal** [angular/material2#8476] opened 2017-11-16 12:05 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Expansion panel should not close on data changes

#### What is the current behavior?
Expansion panel is closing after data is updated

#### What are the steps to reproduce?

http://plnkr.co/edit/KMgrqrb1gsOHK0AofCOf?p=preview

#### What is the use-case or motivation for changing an existing behavior?

Users shouldn't re-open the expansion panel when data is updating (e.g http request)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0
material 5.0.0
typescript 2.4.2
all browsers

**Comment by willshowell** [comment] 2017-11-16 14:09
This is expected behavior and due to you assigning a new array to `packs`. I would suggest looking into [`trackBy`](https://angular.io/api/core/TrackByFunction).

http://plnkr.co/edit/OA7SaaVBmeimsOHLDk60?p=preview

**Comment by josephperrott** [comment] 2017-11-16 17:03
Closing as this is working as expected.

The expansion panel is not being closed but rather an entirely new expansion panel is being rendered and the old one is destroyed as the object is modified.  As @willshowell noted, you can use `trackBy` to perform the function you are looking for.

**Closed by josephperrott** 2017-11-16 17:03 UTC

**Comment by NaveenAmresh** [comment] 2019-04-26 19:33
Write this following code you may solve this issue
ngOnInit() {
    this.href = this.router.url;
    console.log(this.href);
  }

[expanded]="[this.href === 'routelink']"
