### ISSUE TITLE
bug(tabs + expansion panel): wrong display of expansion panel in hidden tabs

### ISSUE THREAD

**Issue by merlosy** [angular/material2#8933] opened 2017-12-11 17:09 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Expansion panels on other tabs should look normal

#### What is the current behavior?
expansion panel is open by default + heading has a wrong size

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
http://plnkr.co/edit/i6eg0f?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Consistency and usability

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
At least since 5.0.0-rc.3 up to 5.0.0

#### Is there anything else we should know?
Since 5.0.0-rc.3:
- Wrapping in a div with ngIf is not working anymore as a workaround!

**Comment by josephperrott** [comment] 2017-12-11 17:23
Closing as duplicate of #5269

**Closed by josephperrott** 2017-12-11 17:23 UTC
