### ISSUE TITLE
mat-expansion-panel re-renders (n + n^2) times when used with *ngFor (OnPush)

### ISSUE THREAD

**Issue by mfursov** [angular/material2#14953] opened 2019-01-25 03:48 UTC
#### What is the expected behavior?
mat-expansion-panel inside *ngFor loop renders as many times as there are iterations in the loop.

#### What is the current behavior?
mat-expansion-panel re-renders (n + n^2) times where n is the number of iterations in the loop.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-nxejpq?file=app%2Fexpansion-overview-example.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.2.1, Chrome 71.

#### Is there anything else we should know?
This bug makes expansion panel with a large (~100) amount of items (or subitems) practically unusable in the default (with animations) mode.

**Comment by josephperrott** [comment] 2019-02-19 19:39
Closing as duplicate of #14952

**Closed by josephperrott** 2019-02-19 19:39 UTC
