### ISSUE TITLE
Second select is opening from two clicks

### ISSUE THREAD

**Issue by anjmao** [angular/material2#10232] opened 2018-03-02 08:03 UTC
#### Bug report:
It is not possible to select second dropdown using mouse from one click if first dropdown is opened. This also apply to other components like dropdown, autocomplete.

#### What is the expected behavior?
Each component should be selectable with one mouse click.

#### What is the current behavior?
It requires two mouse clicks to open second select if value was not selected in the first dropdown.

#### What are the steps to reproduce?
1) Go to https://material.angular.io/components/select/overview.
2) Open first select.
3) While it is opened click on second select.
4) Second select is not opened because click event will be applied to invisible overlay to close first select.
5) Click again on second select, now second select is opened.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All versions, can be reproduced in demo page.

#### Is there anything else we should know?
Adding overlay is good approach, I'm also using it in https://github.com/ng-select/ng-select. It allows to get rid of global document click event listener in each select, but in this case it can be quite annoying for users.

**Comment by crisbeto** [comment] 2018-03-02 09:28
Closing as a duplicate of https://github.com/angular/material2/issues/9320.

**Closed by crisbeto** 2018-03-02 09:28 UTC
