### ISSUE TITLE
md-button on mobile/touch device need to be touched twice to take effect

### ISSUE THREAD

**Issue by sunshineo** [angular/material2#1467] opened 2016-10-11 02:46 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Touch once should work

#### What is the current behavior?
You need to touch the button twice to work.

#### What are the steps to reproduce?
On your phone, go to http://dev.craigsmenu.com
Touch "Nearby" or "Recently-Uploaded" at the top. You need to touch twice for it to work.
First touch simply highlight it.

#### What is the use-case or motivation for changing an existing behavior?
Of course we need to touch once

#### Which versions of Angular, Material, OS, browsers are affected?
mobile safari, mobile chrome.

#### Is there anything else we should know?
I have verified that if I do not use md-button and have just a plain button, it works.

**Comment by ciesielskico** [comment] 2016-10-11 06:57
Duplicate of https://github.com/angular/material2/issues/1316

**Comment by jelbourn** [comment] 2016-10-11 14:21
Dupe of #1316

**Closed by jelbourn** 2016-10-11 14:21 UTC

**Comment by sunshineo** [comment] 2016-10-11 16:23
Sorry about the dupe. I did search a little before file the ticket, but did not see the other issue.
