### ISSUE TITLE
MdIcon directive won't work after minifaction

### ISSUE THREAD

**Issue by Loebe123** [angular/material2#402] opened 2016-05-08 17:26 UTC
**Note: for support questions, please use one of these channels:**
https://github.com/angular/material2/blob/master/CONTRIBUTING.md#question.
This repository's issues are reserved for feature requests and bug reports.

* **Do you want to request a *feature* or report a *bug*?**
Depends

* **What is the current behavior?**
After minification using [UglyfyJS ](https://github.com/mishoo/UglifyJS2), the MdIcon directive won't work any longer. The following element will then be created in DOM:
`<md-icon _ngcontent-dgw-1="" fonticon="fa-bars" role="img" class="fa"></md-icon>`
As you can see, the default font set class (`mdIconRegistry.setDefaultFontSetClass('fa')`) was added correctly to the elements class, but the directive fails to add the font class 'fa-bars'.

* **If the current behavior is a bug,
please provide steps to reproduce and if possible a minimal demo of the problem**
via https://plnkr.co or similar.
I'm building with Webpack and use the [UglifyJsPlugin](http://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin). The rest is done exactly like the [Material2 DemoApp](https://github.com/angular/material2/tree/master/src) suggests. Simply adding UglyfyJS to the build should cause the issue. I think, best use the [Angular2-Webpack Starter](https://github.com/AngularClass/angular2-webpack-starter) and add an font-awsome icon like done in the Material2 DemoApp.

* **What is the expected behavior?**
The font class (in my case 'fa-bars') is added to the elements class.
`<md-icon _ngcontent-dgw-1="" fonticon="fa-bars" role="img" class="fa fa-bars"></md-icon>`

* **What is the motivation / use case for changing the behavior?**
Making JS minifaction possible.

* **Which version of Angular and Material, and which browser and OS does this issue affect?**
Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.
Angular2 RC.0, Angular Material2 Alpha.4, Chrome, Windows 10.

* **Other information**
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)
I tried to deactivate the responsible feature of UglyfyJs that causes the behaviour. But I failed in that. After disabling compression and mangling, MdIcon still fails.
`new UglifyJsPlugin({mangle: false,compress: false}),`
Removing UglifyJsPlugin from the build fixed the problem, but olso deactivated minification.

**Comment by jelbourn** [comment] 2016-05-09 23:45
@Loebe123 what was the actual use of `<md-icon>` in your template?

**Comment by Loebe123** [comment] 2016-05-13 12:35
The template is simply `<md-icon fontIcon="fa-bars"></md-icon>`

**Comment by robertmesserle** [comment] 2016-05-17 21:00
@Loebe123 @jelbourn I tried running the latest code on master through UglifyJS with and without mangle and compress enabled, but was unable to reproduce this error.  I'm wondering if either (a) the issue is something other than minification or (b) something in master has changed.

**Comment by robertmesserle** [comment] 2016-05-17 21:07
Closing for now - will reopen if further instructions are provided and we are able to reproduce the issue.

**Closed by robertmesserle** 2016-05-17 21:07 UTC
