### ISSUE TITLE
The click attribute of a button doesn't appear in the generated html

### ISSUE THREAD

**Issue by cdouine39** [angular/material2#4194] opened 2017-04-21 12:26 UTC
#### Bug:
In the html template, we have a button with a click action attached to it.
When inspecting our page from the browser for that button, the click action is not appearing.
This is needed for Protactor testing for ex.

#### What is the expected behavior?
The generated html should contain the click action.

#### What is the current behavior?
The generated html doesn't contain the click action.

#### What are the steps to reproduce?
Create a component, and in its template, add a button with a click action : 
`<button md-button (click)='clickAction()'>Flat button</button>`
Open the page with a browser. 
The html rendered is : 
```
<button _ngcontent-c0="" md-button="" class="mat-button">
  <span class="mat-button-wrapper">Flat button</span>
  <!--bindings={ "ng-reflect-ng-if": "true"}-->
  <div class="mat-button-ripple mat-ripple" md-ripple="" ng-reflect-trigger="[object HTMLButtonElement]" ng-reflect-centered="false"></div>  
  <div class="mat-button-focus-overlay"></div> 
</button>
```

Plunker template: https://plnkr.co/edit/vPCEmmWJfvjKXHWq19GT?p=preview
(based on the plunker of [material button](https://material.angular.io/components/component/button) )

#### What is the use-case or motivation for changing an existing behavior?
To test with protractor, the click is needed in the html to be able to execute the action.
In our case, this opens a popup. 
Without the click action, the test returns an error "Failed: unknown error: Element <button....> is not clickable a point(...)"

#### Which versions of Angular, Material, OS, browsers are affected?
Tested with Windows7, Protractor v5.1.1, Angular 4.0.1, Angular Material 2.0.0-beta.3, Chrome v57

Thanks for your help

**Comment by kara** [comment] 2017-04-21 17:03
Events like `(click)` are always stripped in Angular. You'll see that after removing the `md-button` attribute, it's still not present. This is expected behavior.

It sounds like your Protractor test is failing because the button is being covered by another element or is hidden on the screen. In any case, this isn't a Material issue, so closing.

**Closed by kara** 2017-04-21 17:03 UTC
