### ISSUE TITLE
Opening dialog while another closes does not work as expected

### ISSUE THREAD

**Issue by mitchellwills** [angular/material2#7438] opened 2017-09-30 02:43 UTC
#### Bug, feature request, or proposal:
Opening a dialog, the closing it, but opening a second dialog after closing the first, but before it finishes closing causes the second dialog to not display and resolve with the same value as the first.

#### What is the expected behavior?
Second dialog opens and the first finishes closing

#### What is the current behavior?
See bug description
Things that do work
 * Open both dialogs then close the first, the second remains open and can be resolved separately
 * Open one dialog, close it and wait for it to close. Then open a second dialog and close it

#### What are the steps to reproduce?
https://plnkr.co/edit/DISxAqvBdNJZmBy5fiwk?p=preview
Click the button, then click ok on the first dialog, see the results of the two dialogs in the console

#### What is the use-case or motivation for changing an existing behavior?
being able to call dialogRef.close() and then immediately open a dialog

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all?

**Comment by julianobrasil** [comment] 2017-09-30 16:24
Related to #6560.

Try calling your second dialog from inside the afterClose() observer.

**Comment by crisbeto** [comment] 2017-10-26 18:34
Closing as a dupe of https://github.com/angular/material2/issues/6560.

**Closed by crisbeto** 2017-10-26 18:34 UTC
