### ISSUE TITLE
[mdDatepickerToggle] re #6053 closed

### ISSUE THREAD

**Issue by MatteoNY** [angular/material2#7230] opened 2017-09-21 16:06 UTC
This was closed as per:  #6053 input disabled.
Stated in next release, I'm reporting it does not appear to be fixed in 2.0.0-beta.10
Next release? Input field gets disabled but button does not. If I add "disable" 
on the md-datepicker-toggle it will be disabled. Tried using ng-disabled and disabled="booleanValue" does not complain but does not disable. Also needed to use a [formControl] to force the input field for the datepicker to be disabled ng-disable= or disable= did not work as expected. 

Thanks!

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by willshowell** [comment] 2017-09-21 17:29
Also as a note, I think the `disabled` interactions between the input, toggle, and datepicker should be explicitly stated in the docs.

**Comment by MatteoNY** [comment] 2017-09-22 17:04
I was able to get the button to be disabled by using the following:
 @ViewChild('pickerReturnDate') pickerReturnDate: any;
When I want the button to be disabled I'm using:  this.pickerReturn.disabled = this.isTrueValue;
The above is a work-around when the input is disabled via  [formControl]="date2Ctrl", for example,   this.disableReturnDate ? this.date2Ctrl.disable() : this.date2Ctrl.enable(); This snippet disabled or enables the date picker's input field but the button remains enabled. The @ViewChild sort of fixes it but the button looks enabled but when you click gets disabled. Not as smooth but workable. I hope this will be fixed in the future. Great work all is good with NVDA screen reader tests. :-)

**Comment by willshowell** [comment] 2017-09-22 17:06
Oh it may be a duplicate of https://github.com/angular/material2/issues/6973. Didn't see you were using reactive forms.

**Comment by mmalerba** [comment] 2017-11-21 20:51
I suspect this was fixed by #7514 please feel free to open a new issue if that is not the case

**Closed by mmalerba** 2017-11-21 20:51 UTC
Labels: P3: important
