### ISSUE TITLE
Cards incompatible with inputs, downscaled placeholder blurry

### ISSUE THREAD

**Issue by rubyduby** [angular/material2#4669] opened 2017-05-19 08:51 UTC
#### Bug, feature request, or proposal:
Placedholders get blurry when downscaled from 14px, which is default font-size for <md-card-content>. 

#### What is the expected behavior?
Better support for input elements in cards e.g. forms with default font-size of 16px and above.

#### What is the current behavior?
font-size: 14px 

#### What are the steps to reproduce?
Just combining <md-inputs> with <md-card>

#### What is the use-case or motivation for changing an existing behavior?
Readability

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material beta 5

**Comment by ocarreterom** [comment] 2017-05-19 09:41
Blurry dup https://github.com/angular/material2/issues/4558.
For the font-size problem, for the moment, I solve it adding the inputs just into the `md-card`.
```html
<md-card>
  <md-input-container>
    <input mdInput>
  </md-input-container>
</md-card>
```
Maybe it change in the future (https://github.com/angular/material2/issues/4245).

**Comment by jelbourn** [comment] 2017-06-07 21:40
Dupe of #4558

**Closed by jelbourn** 2017-06-07 21:40 UTC
