### ISSUE TITLE
Select shouldn't have padding-top when floatPlaceholder="false"

### ISSUE THREAD

**Issue by vegarda** [angular/material2#7523] opened 2017-10-04 11:22 UTC
#### Bug, feature request, or proposal:
When floatPlaceholder="false" there is still padding-top for space for the placeholder

#### What is the expected behavior?
No padding-top when floatPlaceholder="false" and select to be centered vertically correctly

#### What is the current behavior?
padding-top when floatPlaceholder="false"

#### What is the use-case or motivation for changing an existing behavior?
Centering a select vertically

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
4.4.3, material-beta10

**Comment by willshowell** [comment] 2017-10-04 15:20
I don't believe this is an issue on master anymore with the switch to `mat-form-field`

http://plnkr.co/edit/tE0HSIpQ2GTBNTzuUruB?p=preview

**Comment by Tempus35** [comment] 2017-10-05 15:41
@willshowell Sadly that plunker is using the nightly builds of material which allows that to work. If you force it to use the last release you get "Error: md-form-field must contain a MdFormFieldControl. Did you forget to add mdInput to the native input or textarea element?". Seems it will work at some point but not this release.

**Comment by josephperrott** [comment] 2017-10-06 23:10
It looks like this is working as expected as of `beta.12` as seen [here](https://stackblitz.com/edit/angular-material2-issue-afo7eq?file=app%2Fapp.component.html)

**Comment by Tempus35** [comment] 2017-10-06 23:20
@josephperrott I can confirm it is working in the newest release now.

**Comment by josephperrott** [comment] 2017-10-31 18:02
Closing per last update.

**Closed by josephperrott** 2017-10-31 18:02 UTC
