### ISSUE TITLE
(mat-form-field) with <input matInput type="date">  misalignment in flex box

### ISSUE THREAD

**Issue by TishchenkoAlex** [angular/material2#9686] opened 2018-01-30 12:48 UTC
#### Bug, feature request, or proposal:
Bug

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-ydn8vz

```
<div style="display: flex">
	<mat-form-field>
		<input matInput type="text" placeholder="type='text'">
	</mat-form-field>
	<mat-form-field>
		<input matInput type="date" placeholder="type='date'">
	</mat-form-field>
	<mat-form-field>
		<input matInput type="number" placeholder="type='number'">
	</mat-form-field>
</div>
```
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.2, TypeScript 2.6.2, Material 5.1.1, Chrome 63

**Comment by mmalerba** [comment] 2018-01-31 03:47
This looks like a dupe of #8012

**Closed by mmalerba** 2018-01-31 03:47 UTC
