### ISSUE TITLE
Angular materal is HUGE (aot size)

### ISSUE THREAD

**Issue by maciejsobala** [angular/material2#4163] opened 2017-04-19 21:17 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Application which uses angular material should be definetely smaller after AOT compilation.

#### What is the current behavior?
Wann make your application over 50% higher? Use angular material.
```
krk-mp5bp:angular2-webpack-starter-master msobala$ du -hd0 dist/
916K	dist/   <<<size without material
krk-mp5bp:angular2-webpack-starter-master msobala$ du -hd0 dist/
1.4M	dist/  <<< size with material
```
#### What are the steps to reproduce?

I have used this repo: https://github.com/AngularClass/angular2-webpack-starter as boiler plate and made one simple addition in app.module.ts:

```
import { MaterialModule } from '@angular/material';

/*
some other code
*/

@NgModule({
  bootstrap: [ AppComponent ],
  declarations: [
//some declarations
  ],
  imports: [ // import Angular's modules
//some modules
MaterialModule.forRoot()
  ],
  providers: [ // expose our Services and Providers into Angular's dependency injection
    ENV_PROVIDERS,
    APP_PROVIDERS
  ]
})

```

#### What is the use-case or motivation for changing an existing behavior?
1,5MB is in my opinion definetely too much for production app.

#### Which versions of Angular, Material, OS, browsers are affected?

material2-beta.3
angular 4.0.2

**Comment by jelbourn** [comment] 2017-04-20 00:19
Dupe of #4137

**Closed by jelbourn** 2017-04-20 00:19 UTC
