### ISSUE TITLE
Menu appears after md-card instead of over it.

### ISSUE THREAD

**Issue by andregs** [angular/material2#983] opened 2016-08-10 13:20 UTC
Hi, guys!

In my opinion, this menu should appear over the `md-card`, just below the trigger button, right?

```javascript
'use strict';

import { Component } from '@angular/core';

@Component({
	selector: 'tbv-test',
	template: `
	<md-toolbar color="primary">
		<button md-icon-button disableRipple [md-menu-trigger-for]="menu">
			<md-icon>more_vert</md-icon>
		</button>
		<md-menu #menu>
			<button md-menu-item> I shouldn't </button>
			<button md-menu-item> be here :'( </button>
		</md-menu>
	</md-toolbar>
	<md-card>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis quibusdam laboriosam minus accusamus, possimus delectus quos, id autem repellendus. Facilis fuga earum accusamus aut totam nisi maxime adipisci, cum saepe.</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis quibusdam laboriosam minus accusamus, possimus delectus quos, id autem repellendus. Facilis fuga earum accusamus aut totam nisi maxime adipisci, cum saepe.</p>
	</md-card>
	`,
})
export class TestComponent {
	constructor() {}
}
```

![image](https://cloud.githubusercontent.com/assets/712092/17554806/19a08e24-5ee3-11e6-9da6-8a8a49e8b647.png)

I'm using Angular 2.0.0-rc.5 and material 2.0.0-alpha.7 on both Chrome and Edge.

**Comment by kara** [comment] 2016-08-10 16:22
@andregs It looks like your markup might not be right.  The menu trigger expects an MdMenu instance, not the element.   When you use `#menu` alone, you're just linking to the element.  Can you try the following?

```
<md-menu #menu="mdMenu">
            <button md-menu-item> I shouldn't </button>
            <button md-menu-item> be here :'( </button>
        </md-menu>
```

**Comment by andregs** [comment] 2016-08-10 16:38
Thanks for the explanation but the issue still persists.

**Comment by zigzag95** [comment] 2016-08-10 16:46
Look if you have an overlay div at the end of body

**Comment by kara** [comment] 2016-08-10 16:58
I can't seem to reproduce this.  Can you verify that you're following the instructions in the [README](https://github.com/angular/material2/tree/master/src/components/menu) and there are no errors in the console?  An example plunker would expedite this.



<img width="334" alt="screen shot 2016-08-10 at 9 56 21 am" src="https://cloud.githubusercontent.com/assets/3871688/17562725/ecb72ea6-5ee0-11e6-8ce0-c811f53241a1.png">

**Comment by andregs** [comment] 2016-08-10 18:12
I couldn't create a working plunker, but I created this tiny project so you can reproduce the issue:

[menu-issue.zip](https://github.com/angular/material2/files/411793/menu-issue.zip)

Just type `npm install && npm run dev` to start the server and browse to `localhost:3000`

**Comment by ivoviz** [comment] 2016-08-10 22:07
@andregs Although I haven't checked your code, I had a very similar issue. In my case I had to manually load `core/overlay/overlay.css`, otherwise every single element that used overlay was positioned way off, just like in your case. I might just overlooked it, but it should either be mentioned in the docs or make it load automatically somehow. Similar issue to #972 imo.

**Comment by andregs** [comment] 2016-08-10 22:27
I was facing #972 too - thanks for your tip! To sum up:
- Loading `core/style/core.css` solves the ripple problem in #972.
- Loading `core/overlay/overlay.css` solves this menu issue.

**Comment by kara** [comment] 2016-08-10 22:53
Ah, we forgot to include that in the README.   Added an issue to update the docs, but it doesn't look like a bug, so I'm closing this one: 

https://github.com/angular/material2/issues/989

**Closed by kara** 2016-08-10 22:53 UTC
Labels: cannot reproduce
