### ISSUE TITLE
Quickly toggling expansion panel leaves it in undefined state

### ISSUE THREAD

**Issue by willshowell** [angular/material2#5743] opened 2017-07-13 21:23 UTC
#### Bug, feature request, or proposal:
Bug

#### Current behavior
![expansion-bug](https://user-images.githubusercontent.com/6475576/28188131-0ed4cf30-67ef-11e7-96ba-9c01f8400814.gif)

#### Reproduction
http://plnkr.co/edit/PaoRWzPQe29y1x7BBnvr?p=preview

#### Is there anything else we should know?
Maybe similar to https://github.com/angular/material2/issues/4932?

**Comment by willshowell** [comment] 2017-08-18 18:28
Note that to replicate

1. Start with the panel open
2. Quickly close -> open

**Comment by crisbeto** [comment] 2017-08-18 18:30
Another way is to slow down the animation and toggle between accordions.

**Comment by willshowell** [comment] 2017-08-18 18:42
I think you've mentioned it elsewhere, but here's a plunker showing that it is likely a bug in angular/animations@4.3.5:

http://plnkr.co/edit/1Lk0pj6B9V1lCFqSlms8?p=preview

Do the same thing to replicate:

1. Start with panel open
2. Quickly close -> open

**Comment by willshowell** [comment] 2017-09-05 14:48
The original issue seems to be fixed with the latest animations updates, but the toggle icon still rotates the wrong way when quickly closing and then opening.

![expansion-updated-2](https://user-images.githubusercontent.com/6475576/30067058-b9e3c220-9227-11e7-8646-344afa0e6f67.gif)

**Comment by crisbeto** [comment] 2017-11-04 05:17
Closing since I'm having a hard time reproducing it anymore and even in that case the issue is on the `@angular/animations` side.

**Closed by crisbeto** 2017-11-04 05:17 UTC
Labels: P3: important
