### ISSUE TITLE
Modal not closing when hasBackdrop is false

### ISSUE THREAD

**Issue by willwsharp** [angular/material2#7740] opened 2017-10-12 14:54 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Modal should close on clicking outside of it, even if the hasBackdrop is false

#### What is the current behavior?
Modal does not close when clicking outside of it

#### What are the steps to reproduce?
Open the modal and try to close it by clicking outside of it
Here's a plunkr:
https://plnkr.co/edit/6D8rfx?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Modals should be able to be closed by clicking outside of them

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.4

**Comment by willshowell** [comment] 2017-10-12 15:30
This is expected behavior. The backdrop's purpose is to catch clicks and dispatch them to the dialog to close itself. You're probably wanting to make it transparent? Try using 

```
backdropClass: 'cdk-overlay-transparent-backdrop'
```

or any other custom class.

**Comment by crisbeto** [comment] 2017-10-12 16:33
@willshowell's comment is correct. Closing since everything works as expected.

**Closed by crisbeto** 2017-10-12 16:33 UTC
