### ISSUE TITLE
DatePicker inside NgForm launches from any mdInput (bug)

### ISSUE THREAD

**Issue by ryanpm40** [angular/material2#4777] opened 2017-05-24 16:53 UTC
#### Bug, feature request, or proposal:
When nesting both an mdInput and an mdDatePicker inside an ngForm, hitting the 'Enter' key in the mdInput will open the datepicker in the mdDatePicker.

#### What is the expected behavior?
Form controls should behave separately from each other. Hitting enter in one field should not affect another.

#### What are the steps to reproduce?

I've edited the example plunker below. Type the 'Enter' key when inside the first input field:

https://plnkr.co/edit/VMU3GspvB3uvrbN6Mpu7?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.0.2, Material 2.0.0-beta.5, Win 7 & 10, Typescript 2.2.2, Chrome

**Comment by willshowell** [comment] 2017-05-24 17:05
Duplicate of https://github.com/angular/material2/issues/4530. Fixed in https://github.com/angular/material2/pull/4531.

**Comment by jelbourn** [comment] 2017-05-24 17:24
Closing as dupe

**Closed by jelbourn** 2017-05-24 17:24 UTC

**Comment by ryanpm40** [comment] 2017-05-24 17:41
@jelbourn @willshowell Great, thanks for the links, guys. I was searching for bugs based on the 'enter' key, so I hadn't seen that dupe.
