### ISSUE TITLE
Bug: mat-checkbox does not work inside mat-form-fields

### ISSUE THREAD

**Issue by Kopleman** [angular/material2#12072] opened 2018-07-05 08:42 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Its shoud be ok like other components for example select

#### What is the current behavior?
Error - `mat-form-field must contain a MatFormFieldControl`

#### What are the steps to reproduce?
[StackBlitz](https://stackblitz.com/edit/angular-material2-issue-cpxwc9)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

- Angular: 6.0.6
- Material: 6.3.1

**Comment by crisbeto** [comment] 2018-07-07 10:40
Duplicate of #7891.

**Closed by crisbeto** 2018-07-07 10:40 UTC
