### ISSUE TITLE
alwaysFloatLabel attribute for md-input-container

### ISSUE THREAD

**Issue by amardeep** [angular/material2#2490] opened 2017-01-02 03:20 UTC
Feature request

Please add a alwaysFloatLabel option to md-input-container

For eg., that is supported in paper-input
https://elements.polymer-project.org/elements/paper-input

**Comment by DevVersion** [comment] 2017-01-02 13:27
Should be a duplicate of #2466

**Closed by DevVersion** 2017-01-02 13:27 UTC
