### ISSUE TITLE
The autocomplete component doesn't work well on the Microsoft IE 11

### ISSUE THREAD

**Issue by krasnoff** [angular/material2#3768] opened 2017-03-24 20:56 UTC
#### Bug, feature request, or proposal:
The autocomplete component doesn't work well on the Microsoft IE 11

#### What is the expected behavior?
I should be able to select an item. when I select an item it should be displayed on the textbox

#### What is the current behavior?
When I select an item, the dropdown menu disappear but I can't see the selection in the text box

#### What are the steps to reproduce?
you can see this bug on https://material.angular.io/components/component/autocomplete.
go to the examples tab and try to use the component on ie 11

#### What is the use-case or motivation for changing an existing behavior?
I want 100% compatibility with IE 11

#### Which versions of Angular, Material, OS, browsers are affected?
I use the latest versions of angular 2 and the angular 2 material

**Comment by AAAnderson7301** [comment] 2017-03-24 22:32
Issue is already tracked in [Issue #3351 ](https://github.com/angular/material2/issues/3351) and a PR already exists for this [PR #3188 ](https://github.com/angular/material2/pull/3188)

**Comment by jelbourn** [comment] 2017-04-09 02:55
Dupe of #3351

**Closed by jelbourn** 2017-04-09 02:55 UTC
