### ISSUE TITLE
Material 2 Makes Fonts Blurry

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#1357] opened 2016-09-28 17:32 UTC
Please have a look at the attached files.

One picture doesn't have any material component and the font looks smooth.

The screenshot which has material Checkbox, the font looks blurry in it.

![material-font-02](https://cloud.githubusercontent.com/assets/7761180/18925036/bc19ec18-85cb-11e6-80be-407896808292.jpg)

![material-font-01](https://cloud.githubusercontent.com/assets/7761180/18925037/bc23e47a-85cb-11e6-8b5b-b85f4a38c8fe.jpg)

**Comment by jelbourn** [comment] 2016-09-30 01:06
Dupe of #932

**Closed by jelbourn** 2016-09-30 01:06 UTC
