### ISSUE TITLE
Proposal(feature): Expansion Panels

### ISSUE THREAD

**Issue by httpNick** [angular/material2#3664] opened 2017-03-18 08:18 UTC
#### Proposal:
Add expansion panels as outlined [here](https://material.io/guidelines/components/expansion-panels.html#expansion-panels-usage) to the material2 pool of components. I have a (very) base setup project that I was using to start implementing the expansion panels element. Before I got any further, and since I am following the material spec, I wanted to propose moving this into the official material2 code base and modify what I have to follow the material2 coding standards/guidelines. My plan was to fork this repository and integrate the basics of what I have to fit into this code base. I have researched pretty heavily into the datepicker that is in progress in order to understand how styling and themes are applied to material componets, so I could work on getting my current progress modified right away to fit the material2 practices in use. 

Also, a question - is this a duplication of work? I have looked around a bit and haven't seen anything started for expansion panels (at least that follow this spec). 

I'd love to hear the communities thoughts!

**Comment by fxck** [comment] 2017-03-18 10:07
@jelbourn is currently working on table, but I doubt this will be part of the initial release 

https://github.com/jelbourn/material2/tree/table-prototype
https://github.com/jelbourn/material2/tree/new-table-api

best you can do is to start with a design doc https://docs.google.com/document/d/1kpQStAn9L-NX_1bGz_4fXNeZgerWC0mUJHun72bF240/preview

**Comment by httpNick** [comment] 2017-03-18 21:10
@fxck Thanks! I will start creating the design doc and post it back onto this proposal when ready for review.

**Comment by jelbourn** [comment] 2017-03-21 23:25
Hi @httpNick:

Could you just add a brief comment about the API and use-cases you're imagining for an expansion panel?

**Comment by httpNick** [comment] 2017-04-17 08:23
@jelbourn sorry to be MIA, I have some updates for the previous question you asked.

The basic API I was thinking of is here (in the README): https://github.com/httpNick/material2/tree/expansion-panels/src/lib/expansion-panel

I closely followed https://material.io/guidelines/components/expansion-panels.html#expansion-panels-specs in designing the selectors to include, and also I made the expansion-panel being editable an option via `@Input editable`.

The current branch I have adds the expansion-panel to the repo following how other components have been added. I also created a demo-app section for it. It's still a WIP of course, but I thought I was at a good spot to get some feedback before moving forward more.

Let me know if I need to answer on anything else (I will respond more quickly this time 😄 ), or give a better answer!

**Comment by jelbourn** [comment] 2017-04-17 17:04
@httpNick since my last comment @josephperrott starting working on this already :)

We're looking to do an API that's more in line with the native [`details`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) element

**Comment by httpNick** [comment] 2017-04-17 18:48
@jelbourn ah ok thanks for the info.

You snooze, you lose ;). 

@josephperrott would you like any contribution or would you like me to close this?

**Comment by csvn** [comment] 2017-06-02 12:58
This issue can probably be closed, since it's a duplicate of #995 now that this feature is being worked on by the Angular Material team.

@josephperrott Nice work! The API for the component in the demo looks great so far.

**Comment by jelbourn** [comment] 2017-06-02 15:28
Closing into #995

**Closed by jelbourn** 2017-06-02 15:28 UTC
Labels: discussion, feature
