### ISSUE TITLE
bug, mdInput and textarea not On the same horizontal line in table

### ISSUE THREAD

**Issue by stevenmi** [angular/material2#6730] opened 2017-08-30 12:44 UTC
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
 mdInput and textarea not On the same horizontal line in table
![1](https://user-images.githubusercontent.com/14286935/29872880-f7072a92-8dc3-11e7-86c2-4e5004065683.png)

#### What is the current behavior?
 mdInput and textarea On the same horizontal line in table

#### What are the steps to reproduce?
```
<table>
    <tr>
               
      <td>
        <md-input-container>
          <input mdInput placeholder="input" >
        </md-input-container>
      </td>
      <td>
        <md-input-container>
          <input mdInput placeholder="input2" >
        </md-input-container>
      </td>
      <td>
        <md-input-container>
          <textarea mdInput placeholder="textarea" ></textarea>
        </md-input-container>
      </td>
    </tr>
  </table>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular: 2.0.0-beta.10-70bd5fc

**Comment by donroyco** [comment] 2017-08-30 12:46
Partly tracked in #2124

**Comment by josephperrott** [comment] 2017-09-27 18:52
Closing as duplicate of: #2124

**Closed by josephperrott** 2017-09-27 18:52 UTC
