### ISSUE TITLE
Drag Drop: CdkDropList not adding class cdk-drop-list-dragging if ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by abdulkareemnalband** [angular/material2#13815] opened 2018-10-25 14:34 UTC
#### Bug:
`CdkDropList` not adding class `cdk-drop-list-dragging` if `ChangeDetectionStrategy.OnPush`

#### What is the expected behavior?
`CdkDropList` should add  class `cdk-drop-list-dragging` while dragging

#### What is the current behavior?
`CdkDropList` not adding class `cdk-drop-list-dragging` while dragging

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-crbqu5

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.0.3
Node: 10.12.0
OS: win32 x64
Angular: 7.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cli                      7.0.3
@ngtools/webpack                  7.0.3
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1

**Comment by crisbeto** [comment] 2018-10-25 15:56
Duplicate of https://github.com/angular/material2/issues/13680.

**Closed by crisbeto** 2018-10-25 15:56 UTC
