### ISSUE TITLE
Date field label overlap when entering an incorrect date

### ISSUE THREAD

**Issue by thduttonuk** [angular/material2#8734] opened 2017-11-30 11:55 UTC
#### Bug, feature request, or proposal:
When a date value is null from entering an incorrect date the label overlaps the input box

#### What is the expected behavior?
Label should not overlap if a value is entered in the input

#### What is the current behavior?
Label overlaps

#### What are the steps to reproduce?
Got to https://material.angular.io/components/datepicker/overview
Enter a string value in a date field. The label will overlap.

#### What is the use-case or motivation for changing an existing behavior?
Even if a value is incorrect the label should not overlap as it looks terrible

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
   "@angular/animations": "^5.0.3",
    "@angular/cdk": "^5.0.0-rc.2",
    "@angular/common": "^5.0.3",
    "@angular/compiler": "^5.0.3",
    "@angular/core": "^5.0.3",
    "@angular/forms": "^5.0.3",
    "@angular/material": "^5.0.0-rc.2",
    "@angular/platform-browser": "^5.0.3",
    "@angular/platform-browser-dynamic": "^5.0.3",
    "@angular/router": "^5.0.3",

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/5237694/33429292-240a4dc4-d5c4-11e7-8a79-59dfb5febbcd.png)

**Comment by crisbeto** [comment] 2017-11-30 17:47
Closing as a duplicate of https://github.com/angular/material2/issues/8575.

**Closed by crisbeto** 2017-11-30 17:47 UTC
