### ISSUE TITLE
Vertical disalignment of floating labels

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#4755] opened 2017-05-23 18:59 UTC
#### Bug, feature request, or proposal:
Bug, I think. Not sure if it's related to material components or the flex layout.

#### What is the expected behavior?
When an input and a select are disposed side by side, the underline must be aligned. The disalignment affects the floating labels too, as shown in the following printscreen (after an 5px offset was applied - margin-bottom - in the select component to correct the underline disalignement):

![image](https://cloud.githubusercontent.com/assets/25405143/26372584/d3f301f8-3fd4-11e7-8e92-db45d6630966.png)

#### What is the current behavior?
The underlines aren'tt aligned when using Flex Layout

#### What are the steps to reproduce?

Just use a layout like this:
 ```
<div fxLayout="row" fxLayoutAlign="start center">
    <div fxFlex="nogrow">
      <md-select placeholder="Favorite food">
        <md-option>
          Orange
        </md-option>
      </md-select>
    </div>
    
    <div fxFlex="nogrow">
      <md-input-container>
        <input mdInput placeholder="Test">
      </md-input-container>
    </div>
  </div>
```

Plunker is here: https://plnkr.co/edit/0w7TVJTZr7G9HinaXq1C?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.0.4
node: 6.10.3
os: win32 x64
@angular/animations: 4.1.3
@angular/cli: 1.0.4
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/compiler-cli: 4.1.3
@angular/core: 4.1.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.5
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3

Typescript: 2.3.2

#### Is there anything else we should know?
No

**Comment by tinayuangao** [comment] 2017-05-23 23:11
Duplicate of #2124

**Closed by tinayuangao** 2017-05-23 23:11 UTC
