### ISSUE TITLE
mat-select panelClass isn't adding CSS rules

### ISSUE THREAD

**Issue by ljmerza** [angular/material2#14033] opened 2018-11-07 21:47 UTC
#### Bug, feature request, or proposal:
mat-select panelClass input isn't working

#### What is the expected behavior?
panelClass should add the CSS class and allow the rules to be used

#### What is the current behavior?
No change when trying to add CSS classes to panelClass  input

#### What are the steps to reproduce?
https://stackblitz.com/angular/nqgbrbknjje
The background color is supposed to change but it's not

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.0.1
material 7.0.2
typescript 3.1.4

**Comment by josephperrott** [comment] 2018-11-07 23:09
Closing as duplicate of #13686 

This was fixed in #13691 and will be included in the next release of the docs site.  It looks like it was inadvertently not cherry-picked into the release branch causing the issue to continue on the docs site.

**Closed by josephperrott** 2018-11-07 23:09 UTC
