### ISSUE TITLE
Angular Material Snackbar not shown correctly

### ISSUE THREAD

**Issue by JulidaRocks** [angular/material2#14197] opened 2018-11-19 05:57 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
 I implemented a global error handler and a global loading component (angular material spinner) to my angular 7 project. When detecting a HttpErrorResponse the loader should be removed and an angular material snackbar should be shown.

The snackbar should open at the bottom of the page and should close when clicking "x".

#### What is the current behavior?
But instead it opens at the upper left side.
When clicking "x" it closes and opens again at the expected position. But then it doesn't react to clicks anymore. It disappears after clicking "x" and then clicking a different position of the window.

This behaviour is also shown when removing the loading spinner.

![2018-11-13_10h18_01](https://user-images.githubusercontent.com/39371377/48688828-14d09280-ebc8-11e8-9a4a-d4d00856204c.png)

#### What are the steps to reproduce?
[Stackblitz Example](https://stackblitz.com/edit/angular-qqf5ox)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
tested with 7.0.3

#### Is there anything else we should know?
also asked at [stackoverflow](https://stackoverflow.com/questions/53277691/angular-material-snackbar-not-shown-correctly)

**Comment by josephperrott** [comment] 2018-11-20 18:21
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

**Comment by JulidaRocks** [comment] 2018-11-21 15:34
Sorry, I already linked a stackblitz example, just forgot to insert a link name so it was not visible. Corrected this now (see first post)

**Comment by JulidaRocks** [comment] 2018-11-26 15:29
Could you already check the Stackblitz example? I'm really in trouble with this behaviour. Thanks!

**Comment by vizjerai** [comment] 2018-11-27 14:45
I ran into a similar issue and the solution is to make sure the snackbar is being called inside of angular's zone. Answered on stackoverflow but also here for anyone else who may run into this issue.

```ts
import { Injectable, NgZone } from '@angular/core';
import { MatSnackBar, MatSnackBarRef, SimpleSnackBar, MatSnackBarConfig } from '@angular/material';

@Injectable({
  providedIn: 'root'
})
export class SnackbarService {

  constructor(
    public snackbar: MatSnackBar,
    private zone: NgZone,
  ) { }

  error(message: string) {
    const config = new MatSnackBarConfig();
    config.panelClass = ['background-red'];
    config.verticalPosition = 'bottom';
    config.horizontalPosition = 'center';
    this.zone.run(() => {
      this.snackbar.open(message, 'x', config);
    });
  }

}
```

**Comment by josephperrott** [comment] 2018-11-27 15:24
Closing as duplicate of #7233

**Closed by josephperrott** 2018-11-27 15:24 UTC
Labels: cannot reproduce

**Comment by JulidaRocks** [comment] 2018-11-27 17:11
@vizjerai Waaaaaaaaaah that's it! Thank you thank you thank you! You definitely made my day, woohoo!
