### ISSUE TITLE
matTextareaAutosize gets focus on initialization

### ISSUE THREAD

**Issue by palpatine1991** [angular/material2#11451] opened 2018-05-22 14:25 UTC
#### Bug, feature request, or proposal:

Textarea with `matTextareaAutozize` directive gets the focus on initialization.

#### What is the expected behavior?

It should not get focus if it is not explicitly focused.

#### What is the current behavior?

It is now focused during initialization. This for example breaks the `ng-touched`/`ng-untouched` classes and therefore validation behavior.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-r4nqhk?file=app/input-overview-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 6.0.2
Angular Material 6.1.0

#### Is there anything else we should know?

Only reproducible on Safari (both desktop/mobile), Edge, IE11

**Comment by pfeigl** [comment] 2018-05-22 19:14
Probably a duplicate of https://github.com/angular/material2/issues/11308
However the affected user base seems to be bigger as initially described, if this is not only iOS.

**Closed** 2018-05-23 03:59 UTC
Labels: P3, has pr
