### ISSUE TITLE
Datepicker calendar breaks down in firefox

### ISSUE THREAD

**Issue by zggb** [angular/material2#8305] opened 2017-11-08 14:00 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Datepicker calendar should works in firefox with all years.

#### What is the current behavior?
Datepicker calendar breaks near 1985 year

#### What are the steps to reproduce?
1. go to the https://material.angular.io/components/datepicker/examples in firefox and open browser console
2. choose  1984 year in basic datepicker
3. you will see ERROR Error: Invalid date "1" for month with index "3". in console

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
firefox 56.0.2 (64-bit)
material and angular on https://material.angular.io/components/datepicker/examples
also it reproduces locally with: 
- angular 4.3.1
- @angular/material": "^2.0.0-beta.10" and "@angular/material": "^2.0.0-beta.8",
![cleanagedeidolonhelvum-size_restricted](https://user-images.githubusercontent.com/8955744/32552860-ee4495be-c49d-11e7-9154-f3a970dcff1b.gif)

<img width="1413" alt="screen shot 2017-11-08 at 16 01 27" src="https://user-images.githubusercontent.com/8955744/32552928-1f8cca6a-c49e-11e7-983a-7abe5eb0eba9.png">

**Comment by DragoTechInnovations** [comment] 2017-11-08 15:40
My issue is similar to yours.
https://github.com/angular/material2/issues/8295

**Comment by mmalerba** [comment] 2017-11-17 00:13
I'm not able to reproduce this in firefox 57, will download 56 and give it a shot

**Comment by mmalerba** [comment] 2017-11-21 19:23
Just tried with firefox 56.0.2 on mac and not able to reproduce there either. @zggb is this still happening for you?

**Comment by zggb** [comment] 2017-12-06 11:59
yes, still the same behavior in the Firefox 57.0.2

Yo don't need to choose exactly 1985, just open basic datepicker, switch to the year choosing, and decrease year by left arrow. Between 1075-1985 you will see this

<img width="508" alt="screen shot 2017-12-06 at 13 57 16" src="https://user-images.githubusercontent.com/8955744/33660686-656d804c-da8d-11e7-8956-44281f00ff02.png">

**Comment by mmalerba** [comment] 2017-12-06 16:54
I opened the calendar at 2017 and went all the way back to year 1 but did not encounter this issue. Couple ideas though: 
- Have you tried clearing your cache? maybe you have an old version of the docs site with a bug in it. 
- May I ask what timezone your machine is set to? it may be a timezone-specific issue

**Comment by zggb** [comment] 2017-12-08 12:11
yes, I delete cache, use different firefox (dev edition), but still the same
my zone is +2 hours. Kiev

<img width="372" alt="screen shot 2017-12-08 at 14 10 34" src="https://user-images.githubusercontent.com/8955744/33765499-baef8dae-dc21-11e7-921b-4ac4b6b46b01.png">
<img width="1283" alt="screen shot 2017-12-08 at 14 10 11" src="https://user-images.githubusercontent.com/8955744/33765500-bb098308-dc21-11e7-8c62-0682dd7ee5e4.png">

**Comment by mmalerba** [comment] 2017-12-08 15:56
I believe this is the same issue as #8295 I believe it only affects the `NativeDateAdapter` so if you're able to use the `MomentDateAdapter` that should solve the problem in the mean time

**Comment by mmalerba** [comment] 2017-12-08 15:58
I'll use #8295 to track this issue, so closing this one

**Closed by mmalerba** 2017-12-08 15:58 UTC
Labels: cannot reproduce

**Comment by zggb** [comment] 2017-12-14 12:10
with MomentDateAdapter works fine, thank you @mmalerba

**Comment by DragoTechInnovations** [comment] 2017-12-15 05:40
Um... can  someone help me with moment date adapter? Like how to import it? I can find it.

**Comment by Chan4077** [comment] 2017-12-15 06:13
@DragoTechInnovations Follow these steps to get a moment date adapter:
1. Install `@angular/material-moment-adapter` from npm:
    ```bash
    npm install @angular/material-moment-adapter --save
   ```
2. Import `MatMomentDateModule` from `@angular/material-moment-adapter` and place it in your `imports` array in your app's module:
   ```typescript
   import { MatMomentDateModule } from '@angular/material-moment-adapter';
   // ...
   @NgModule({
       imports: [
           // ...
           MatMomentDateModule
       ]
   }
   ```

[More info](https://material2-docs-dev.firebaseapp.com/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings)

**Comment by DragoTechInnovations** [comment] 2017-12-15 08:07
@Chan4077 How to add a version compatible with material 2.0.0-beta.12?
