### ISSUE TITLE
Unable to set disable on md-input when using model driven forms

### ISSUE THREAD

**Issue by ccpony** [angular/material2#1397] opened 2016-10-01 16:40 UTC
#### What is the current behavior?

Unable to initialize disabled state on <md-input> when using ng2 model-driven forms
#### What are the steps to reproduce?

...
      let account_idCtrl = this.formBuilder.control({
        value: '',
        disabled: true     <=== doesn't work.  Control is not disabled.
      }, Validators.required);
      let account_nameCtrl = this.formBuilder.control({
        value:''
      })

```
  this.myForm = this.formBuilder.group({
      account_id: account_idCtrl,
      account_name: account_nameCtrl
  })
```

...

Providing a Plunker (or similar) is the _best_ way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
#### Which versions of Angular, Material, OS, browsers are affected?

@angular 2.0.1
material: experimental
angular-cli: 1.0.0.0-beta.16

**Comment by RoxKilly** [comment] 2016-10-02 10:06
May be related to #1171

**Comment by jelbourn** [comment] 2016-11-04 01:39
Dupe of #1171

**Closed by jelbourn** 2016-11-04 01:39 UTC
