### ISSUE TITLE
Material 2 Components Build Error - sourceMappingURL

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#562] opened 2016-05-28 12:18 UTC
I have installed material2 components using package.json file.

Now whenever I try to build using systemjs, I received below errors:

Error: ENOENT: no such file or directory, open 'node_modules\@angular2-material\core\rtl\usr/local/google/home/jelbourn/material2/tmp/broccoli_type_script_compiler-input_base_path-IydvmmBU.tmp/0/components/input/input.js.map'

When I opened the input file.js in node_modules\@angular2-material\input I found the below line at the end of the file.

//# sourceMappingURL=/usr/local/google/home/jelbourn/material2/tmp/broccoli_type_script_compiler-input_base_path-IydvmmBU.tmp/0/components/input/input.js.map

it seems that the sourceMappingURL provided in js files of all components is incorrect.

Can anyone please guide?

**Comment by DevVersion** [comment] 2016-05-28 12:22
This is a duplicate of #541

**Comment by naveedahmed1** [comment] 2016-05-28 12:31
Thank you Paul for the update, I will follow that ticket.

**Comment by jelbourn** [comment] 2016-05-31 16:36
Closing as dupe of #541

**Closed by jelbourn** 2016-05-31 16:36 UTC
