### ISSUE TITLE
[IE11] Mat-Table rows are not centered vertically

### ISSUE THREAD

**Issue by tbnovaes** [angular/material2#12296] opened 2018-07-20 16:14 UTC
#### Bug, feature request, or proposal:
When using mat-table on IE11 the content from header row and rows are not vertically centered

#### What is the expected behavior?
To have the content centered vertically

#### What is the current behavior?
Content is positioned on the top

#### What are the steps to reproduce?
Create a mat-table
Add some content to it
Content is correctly align in every browser except IE11

#### What is the use-case or motivation for changing an existing behavior?
Create consistency between browsers, unfortunately some people still use IE11

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular @6.0.4
Angular Material @6.3.0
Typescript @2.7.2
OS Windows 10 (Parallels)
Browsers IE11

**Comment by crisbeto** [comment] 2018-07-20 18:54
Closing as a duplicate of https://github.com/angular/material2/issues/11470.

**Closed by crisbeto** 2018-07-20 18:54 UTC
