### ISSUE TITLE
Md-Select and Hint

### ISSUE THREAD

**Issue by Caloman** [angular/material2#2624] opened 2017-01-13 09:44 UTC
_Newbie doubts_
Md-select does not accept hints and breaks pattern with input or i'm doing it wrong?

Usage in forms compromised!

**Comment by codef0rmer** [comment] 2017-01-14 18:27
I know where you are coming from. I usually use `md-hint` for validation errors which is not ideal BTW. A hacky way would be,

```
<md-input-container>
    <input style="display:none" md-input>
    <md-select placeholder="Favorite food" [(ngModel)]="selectedValue" name="food">
        <md-option *ngFor="let food of foods" [value]="food.value">
            {{food.viewValue}}
        </md-option>
    </md-select>
    <md-hint align="end">Select something</md-hint>
</md-input-container>
```

**Comment by kryzys69** [comment] 2017-02-05 14:11
I thing it would be nice if you can embed `md-select` and in the future `md-datepicker` and maybe other components in `md-input-container`, just like you can in Material 1...

**Comment by kara** [comment] 2017-02-10 03:22
Tracking this in https://github.com/angular/material2/issues/2498. Closing as a dupe.

**Closed by kara** 2017-02-10 03:22 UTC
Labels: feature, P4: nice to have

**Comment by tgiddings** [comment] 2017-03-24 07:29
@codef0rmer can you elaborate on the css to hide the fake input in your trick? I've tried variations of
```
.select-input-container .mat-input-underline{
  display:none;
}
```
where `select-input-container` is a class I add to the input container. Not only does this have no effect on the extra underline, but this rule doesn't even show up in firefox's inspector as being considered for the underline element. you mention a `div.md-input-underline`, but there is no div in the inspector with that class; the divs' classes all start with the prefix `mat-`.

**Comment by antonyboom** [comment] 2017-03-31 18:48
@tgiddings finally after couple hours, I figured out how to fix it. here is working code

style.css
```
.tricky-select {
  width: 100%;
}
.tricky-select .mat-input-underline {
  display: none;
}
```
```
  <md-input-container class="tricky-select">
      <input type="text" mdInput class="form-full-width" [ngStyle]="{'display':'none'}" >
      <md-select placeholder="client" class="form-full-width" [(ngModel)]="dialog.stuff" required name="stuff" #stuff="ngModel" [disabled]="dialog.used">
        <md-option *ngFor="let item of items" [value]="item.id" >
          {{ item.name }}
        </md-option>
      </md-select>
      <md-hint *ngIf="f.submitted && (stuff.untouched || !stuff.valid)" [ngStyle]="{'color': 'red'}" align="end">Country is required</md-hint>
    </md-input-container>
```

**Comment by gcfabri** [comment] 2017-04-01 13:25
@antonyboom I tried this but didn't work... Could you provide a plunk?

**Comment by antonyboom** [comment] 2017-04-03 17:08
@gcfabri I'm sorry cannot reproduce it in plunker because official example doesn't work and I couldn't force to work it. It requires to import BrowserAnimationsModule which is not accessible from cloudflare at this moment

**Comment by ramshinde92** [comment] 2017-07-06 08:49
@antonyboom Not working for me either.

**Comment by jeanpchr** [comment] 2017-07-10 20:24
@gcfabri @ramshinde92 
Place the "tricky" at the end of your material scss file, that did the trick for me.

**Comment by M3enjamin** [comment] 2017-07-17 09:38
for that css problem, another way is to use /deep/
like this: 
.tricky-select /deep/ .mat-input-underline {
  display: none;
}

**Comment by mackelito** [comment] 2017-07-17 10:12
What does /deep/ do?

**Comment by willshowell** [comment] 2017-07-17 12:29
@mackelito for components that have ViewEncapsulation, it will break through it. For example, with ViewEncapsulation, 

```css
.tricky-select .mat-input-underline { }

// compiles to...

.tricky-select[_ngcontent-c1] .mat-input-underline[_ngcontent-c1] { }

```

```css
.tricky-select /deep/ .mat-input-underline { }

// compiles to...

.tricky-select[_ngcontent-c1] .mat-input-underline { }
```

**Comment by mackelito** [comment] 2017-07-17 13:42
Aaah Good to know! What does the "deep" stand for?

**Comment by willshowell** [comment] 2017-07-17 13:47
Presumable just the word "deep" for accessing elements that belong to "deeper" components? Note, however, that it is being deprecated. You can read more here https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep
