### ISSUE TITLE
Material Data table master detail view

### ISSUE THREAD

**Issue by pantonis** [angular/material2#6081] opened 2017-07-27 09:58 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
You have done a great job on the Material Data table but there is an important piece of the puzzle that is missing. Can you please implement master detail view in Data table. 

Thank you

**Comment by nni123** [comment] 2017-07-27 21:11
material 2 is slow compare to other commercial UI libraries in terms of features & component set. 

You can try devextreme if you are doing nonprofit work (free for them but fee for commercial use)

https://js.devexpress.com/Overview/Angular/

**Comment by pantonis** [comment] 2017-07-27 21:19
Agree that is slow dev but is more performant and of course design. Other commercial libraries are very very ugly. UX is also very bad. This is where material lib differentiates. Hope google dedicate more people on this promising project. Still wonder why they dont actuallt

**Comment by andrewseguin** [comment] 2017-07-27 23:03
Can you provide more information on what you are looking for?

**Comment by stevenmi** [comment] 2017-07-28 03:22
@andrewseguin , i want to know your team whether have the plan to add Features for data-table such as:
Row grouping,  Complex headers (rowspan and colspan),  frozen column，  column resize,   stripe style,
  the most import is row selection.
thanks you and your team's good work on material2

**Comment by pantonis** [comment] 2017-07-28 04:42
@stevenmi This ticket is for master detail view feature request. Any other features please open another ticket. 

@andreseguin I am looking for a master detail view tablem It is very often that a table needs to be created in master detail view. It is core functionality of a datatable

**Comment by nni123** [comment] 2017-07-28 07:45
@pantonis, I am looking for same feature set. 

In fact, material 2 datagrid won't take array as datasource (got JSON from simple http call to express server). They have plan for Simple Table with following features (copy-paste from doc
======================================
In the near future, we will provide a simplified version of the data-table with an easy-to-use interface, material styling, array input, and more out-of-the-box features (sorting, pagination, and selection).
======================================

I am pretty sure providing above feature set will take sometime & adding master-detail will be next. Unless someone from dev team can update if I am wrong.

In meantime, devextreme datagrid provide same features with simple codebase. 

https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/MasterDetailView/Angular/Light/

BTW:  My current combo for UI library primeng + material 2. PrimeNG datagrid got everything - master/detail feature...ahh played with many UI libraries

**Comment by pantonis** [comment] 2017-07-28 07:47
@nni123 I am using primeng but it has lots of bugs and its design is not compared to material. 
Also havent been able to find example of master detail of that datatable.

**Comment by nni123** [comment] 2017-07-28 08:06
@pantonis 
In meantime, devextreme datagrid provide same features with simple codebase. 

[DevExtreme datagrid with master/detail examples
](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/MasterDetailView/Angular/Light/)

[Use DevExtreme for your next web project for free
with a non-commercial, non-competitive license](https://js.devexpress.com/NonCommercial/)

Sorry mod for posting third party info but relevant to the post.

**Comment by willshowell** [comment] 2017-07-28 14:05
@pantonis is [this](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/MasterDetailView/jQuery/Light/) approximately what you're looking for?

![screen shot 2017-07-28 at 10 04 20 am](https://user-images.githubusercontent.com/6475576/28720787-328d9e50-737c-11e7-9ab7-f45f1de88583.png)

**Comment by andrewseguin** [comment] 2017-07-28 17:40
Dupe of #6095 - will track this feature there

**Closed by andrewseguin** 2017-07-28 17:40 UTC
Labels: md-table

**Comment by pantonis** [comment] 2017-08-07 14:37
Still the #6095  does not answer this question/feature
The guys at #6095 talk about expanding rows and detail page.  like the screenshot that @willshowell posted above.

**Comment by willshowell** [comment] 2017-08-07 14:52
@pantonis is it not the same concept? Don't you wish to be able to expand a row to show additional details about it?

![](https://user-images.githubusercontent.com/17860925/28689547-9f318db0-72db-11e7-8047-539f58852c6c.png)

---

![](https://user-images.githubusercontent.com/6475576/28720787-328d9e50-737c-11e7-9ab7-f45f1de88583.png)

**Comment by pantonis** [comment] 2017-08-08 06:11
That is one part of the question. The other part is to embed another table inside the existing one.

**Comment by willshowell** [comment] 2017-08-08 13:16
Ah I guess I wasn't clear on the master/detail concept. I still think it's the same to embed a table. My expectation (very well could be wrong) is that you'll be able to inject any component, even one including a table, into the row.

**Comment by pmsa29** [comment] 2018-01-15 23:07
When would be ready master-detail view?

**Comment by jducobu** [comment] 2018-07-26 11:13
I found this : https://www.npmjs.com/package/ngx-nested-data-table
