### ISSUE TITLE
FileUpload component missing

### ISSUE THREAD

**Issue by nni123** [angular/material2#5988] opened 2017-07-23 21:59 UTC
I don't see file upload component in existing list or In progress, planned, and unplanned features. It is an important component for SPA. 

If requesting features is wrong on this forum, please close with updates.

Thanks

**Comment by julianobrasil** [comment] 2017-07-24 00:08
[Material specs](https://material.io/guidelines/) doesn't say anything about it and I've seen nothing in the [design docs](https://github.com/angular/material2/wiki/Design-doc-directory) too. 

Maybe if we have a community material 2 components repo someday (#5250) then we'll have a FileUpload component.

**Comment by xuanshenbo** [comment] 2017-07-24 00:29
Dupe of #1347

**Comment by nni123** [comment] 2017-07-24 02:07
Amazing this is not on their roadmap...it is most important element but to use another library (using PrimeNG) for one element make little sense...

Again, adobe flex was so good at SPA or Rich Internet application (whatever that term was) fits the bill.

Google has the habit of making half-baked stuff GWT comes to mind, but I will stop here...

Closing this before they do.

Closing

**Comment by nni123** [comment] 2017-07-28 00:57
I would like someone officially tell me if they won't implement file upload even in future (weird for sure).

It is very useful & not overly complicated like datagrid...

**Closed** 2017-08-11 23:10 UTC

**Comment by merlosy** [comment] 2017-08-28 14:04
Hi, 
If this helps I made my own => https://gist.github.com/merlosy/ab33dd7edaacfd92d6c9a5daea0a1240
Working good so far (Angular 4.3.x)

**Comment by nni123** [comment] 2017-10-08 06:04
It takes little to make simple file upload but funny material design don't care enough...sometime google is weird for sure and real pain to keep up with breaking changes...hate angular sometime


Style the button for 4.4.3 & material 2 build 12

`     <div class="button-row">
      <button mat-button color="accent" mat-mini-fab (click)="imgFileInput.click()"><mat-icon>attachment</mat-icon></button>
      <input hidden type="file"  #imgFileInput (change)="previewImage($event)"/>
    </div>`

css part

`.example-button-row {
  display: flex;
  align-items: center;
  justify-content: space-around;
}`
