### ISSUE TITLE
can provide file upload component?

### ISSUE THREAD

**Issue by littledian** [angular/material2#10324] opened 2018-03-08 09:07 UTC

**Comment by donroyco** [comment] 2018-03-08 11:07
Duplicate of #3262

**Comment by donroyco** [comment] 2018-03-08 11:10
And as @mmalerba stated in #7751:

> You could create your own file upload component and make it work inside the form field (guide on how to do this has been written but not pushed to our docs site yet, you can find it here: https://github.com/angular/material2/blob/master/guides/creating-a-custom-form-field-control.md)

**Comment by crisbeto** [comment] 2018-03-08 11:10
Closing as a duplicate.

**Closed by crisbeto** 2018-03-08 11:10 UTC
