### ISSUE TITLE
bug(MdDialogRef) close not work in catch or finally

### ISSUE THREAD

**Issue by nansCabanac** [angular/material2#7861] opened 2017-10-17 19:51 UTC
Hello,

Version Material :    @angular/material@2.0.0-beta.11
Version Angular     4.4.5
    
I am not sur if it 's a bug but i can't close an MdDialogRef in catch/finally function.

<pre> <code>
myFunction(data){
	this.httpWaitingService.show().subscribe();	
	
	return  this.http.post(this.baseUrl+"/search",JSON.stringify(data),this.options)
	.map(response => response.json())
	.finally(() => this.httpWaitingService.close());
}
</code></pre>

In httpWaitingService, i have :  
- 1 function  to show a new MdDialogRef  with an material spinner and waiting text
- 1 function  to close current MdDialogRef

The close function only work if **this.httpWaitingService.close();** it's out finally, but it's not the goal !

I have try create : **let self = this;** at begin of the function and replace call of **this** by **self**  but without sucess...

Thank for help !

#EDIT 
I have downgrade angular in 4.4.3 and it's work normaly now ! It's an angular bug i think ....

**Comment by willshowell** [comment] 2017-10-18 14:42
The exact same code behaves differently in 4.4.3 and 4.4.5? Think you could create a StackBlitz reproduction?

**Comment by crisbeto** [comment] 2017-10-26 20:24
It's most likely because change detection isn't triggered. Can you try closing the dialog inside `NgZone.run`?

**Comment by jelbourn** [comment] 2017-11-03 22:45
Closing for lack of response

**Closed by jelbourn** 2017-11-03 22:45 UTC
