### ISSUE TITLE
[FR] mat-expansion-panel perf opti

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#11318] opened 2018-05-14 13:48 UTC
#### Bug, feature request, or proposal:
Feature request:
Within an accordion, apply `backface-visibility: hidden;` to `mat-expansion-panel`s to prevent repaint of the ones bellow it.

#### What are the steps to reproduce?
Showing basic repaint issue: 

https://angular-dz7pfv.stackblitz.io/

- devtools > rendering > enable 'paint flashing'
- click 'more info' on first node
- notice every single row bellow it repaints
- restart from the beginning with 'prevent repaint' set to true
(prevent repaint only add the css rule from above to each row)
- notice that only the affected row is being repainted

Official doc example with perf opti applied https://stackblitz.com/edit/angular-8wyt5j?file=styles.css

Note that the performance impact can be big when animations are applied on complex pages.
See https://is-angular-ivy-ready.firebaseapp.com/#/status

#### What is the use-case or motivation for changing an existing behavior?
Perf matters.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
6.0.1

#### Is there anything else we should know?
- Note sure if this should be added to the `mat-accordion`, to prevent the repaint of the content bellow the accordion. Needs more investigation.

- I also need help regarding `mat-dialogs` to identify an issue. On my mid-range Nexus 5x, opening a dialog with content that scrolls makes the animations stutter a lot, maybe down to only a few fps.

**Comment by Ploppy3** [comment] 2018-06-01 23:18
@josephperrott @crisbeto Note that even with the perf opti applied, there is a page repaint, I can't find a way to prevent it.

**Comment by josephperrott** [comment] 2018-07-02 16:29
After investigating further, it looks like there is not anything we can do to prevent a repaint because we are adjusting the height directly of `div`s.  Its possible that `will-change` could help slightly though repaints will still occur.  Additionally, overapplying `will-change` can have negative effects on performance overall as the browser will eagerly attempt optimizations which can take a fair bit of resources.

The only real way to "improve performance" is to prevent the animation between the state of the heights, which is is not really improve performance as much as just avoiding everything.

**Comment by josephperrott** [comment] 2018-07-02 16:29
In light of this I am going to close this as a duplicate of #8287

**Closed by josephperrott** 2018-07-02 16:29 UTC
