### ISSUE TITLE
Dense spacing between text fields

### ISSUE THREAD

**Issue by coder925** [angular/material2#7104] opened 2017-09-15 15:24 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
In forms with many or crowded fields, you should be able to apply ***Dense spacing*** as described in the [Text fields section of the Material Design Guidelines](https://material.io/guidelines/components/text-fields.html).

I would like to be able to apply a ```spacing="dense"``` , or similar directive, to the ```<md-form-field>```.

#### What is the current behavior?
All form fields have ***Normal spacing***.
There is no available Material directive to apply _dense spacing_ as answered in this [StackOverflow question](https://stackoverflow.com/questions/46225748/how-to-apply-dense-spacing-between-text-fields).

#### What are the steps to reproduce?
Plunker: https://embed.plnkr.co/73T9rURSb71kLbGUKa0G/

#### What is the use-case or motivation for changing an existing behavior?
In a desktop business app it can be motivated to have areas with many fields.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by willshowell** [comment] 2017-09-15 15:24
See https://github.com/angular/material2/issues/4597

**Comment by jelbourn** [comment] 2017-09-15 16:12
Duplicate of #4597

**Closed by jelbourn** 2017-09-15 16:12 UTC
