### ISSUE TITLE
Migration from angular-material 1, css name clash

### ISSUE THREAD

**Issue by stefan-leye** [angular/material2#2698] opened 2017-01-17 19:49 UTC
#### Bug, feature request, or proposal:

I'm currently migrating from an angular 1 project using angular-material to angular 2. I'm also using some of the angular-material 2 components (md-input-container, md-dialog). While the basic javascript part can be mirgrated quite easily there are lots of name clashes between material 1 and 2 css/scss classes, which hampers using both in one project and therefore migration.

#### What is the expected behavior?

Use different css class names in angular-material 2 than angular-material 1.

#### What is the current behavior?

Using components like md-input-container or md-dialog from angular-material 2 and angular-material 1 results in strange styling behaviour.

#### What are the steps to reproduce?

Create an md-input-container field with angular-material 2 and angular-material 1 in the same project.

#### What is the use-case or motivation for changing an existing behavior?

Migration from angular(-material) 1 to angular(-material) 2.

#### Which versions of Angular, Material, OS, browsers are affected?

angular-material 1.1.1 and angular-material 2.0.0.beta.1

**Comment by DevVersion** [comment] 2017-01-17 19:53
@jelbourn worked a compatibility module that ensures that M1 components don't interfere with M2 (https://github.com/angular/material2/pull/2093)

**Comment by stefan-leye** [comment] 2017-01-19 09:44
Thank you. This looks like a good starting point. A lot of the "mat" selectors seem to be buggy, however or I use them in a wrong way. Is there documentation for this?

**Comment by jelbourn** [comment] 2017-01-19 23:47
@stefan-leye the no-conflict mode isn't done yet; it will hopefully be in the next release

**Comment by jelbourn** [comment] 2017-01-25 00:16
Closing as dupe of #1479

**Closed by jelbourn** 2017-01-25 00:16 UTC

**Comment by cdouine39** [comment] 2017-03-15 13:33
Hi,

I know this issue got closed, but as it looks like no-conflict mode is now done, i was wondering how to turn it on ?
Should it be enough to import NoConflictStyleCompatibilityMode module in app.module ?

When doing so, i get an error :
