### ISSUE TITLE
md-menu offset

### ISSUE THREAD

**Issue by riankol** [angular/material2#2016] opened 2016-11-29 08:56 UTC
#### Bug, feature request, or proposal:
I noticed md-menu is not longer an 'Initial version', but the 'custom off-set support' is not implemented yet. Can you give me any indication when this is expected to be implemented?

#### What is the expected behavior?
With defining a x-offset or y-offset, I should be able to set a 'number of pixels to offset the menu from the trigger, for fine-tuning.' 

#### What is the current behavior?
Md-menu doesn't accept an offset yet.

## What is the use-case or motivation for changing an existing behavior?
I would like to place the menu beneath the button, instead of on top of it.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular material 2.0.0-alpha.10

#### Is there anything else we should know?
The behavior is announced in the [md-menu docs](https://docs.google.com/document/d/1cSUrY2WAqSN8ePldLLqrEVkk2BkYbPB2fysC6brvj4Q/preview).

**Comment by jelbourn** [comment] 2016-11-30 00:11
@kara we do need a way to position the menu "next to" the trigger instead of "over" it.

**Comment by kara** [comment] 2016-11-30 01:47
Yeah, it's been on my planning board for md-menu (https://github.com/angular/material2/projects/3). Closing as a dupe of https://github.com/angular/material2/issues/1672.

**Closed by kara** 2016-11-30 01:47 UTC
Labels: P3: important
