### ISSUE TITLE
Input element using mdInput when binding model has initial state as dirty in IE

### ISSUE THREAD

**Issue by thanhpd** [angular/material2#3201] opened 2017-02-20 08:57 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Input element using mdInput when binding model has initial state as pristine in IE

#### What is the current behavior?
Input element using mdInput when binding model has pristine state as pristine in IE

#### What are the steps to reproduce?
Plunker template: https://plnkr.co/edit/0W0Q9nSRmmKSLUnSdoO5?p=preview
Inspect input in browser development tool. `input` element using `mdInput` has `ng-pristine` CSS class in Chrome/Firefox/Edge while they have `ng-dirty` CSS class in IE

|                                     | IE       | Chrome/Firefox/Edge |
|-------------------------------------|----------|---------------------|
| `input` without `mdInput` directive | pristine | pristine            |
| `input` with `mdInput` directive    | dirty    | pristine            |

#### Which versions of Angular, Material, OS, browsers are affected?
Material 2.0-beta2
Angular ^2.3
IE 11

#### Is there anything else we should know?
This did not happen in Material2.0-beta1

**Comment by mmalerba** [comment] 2017-03-03 16:12
duplicate of #3256

**Closed by mmalerba** 2017-03-03 16:12 UTC
