### ISSUE TITLE
'mat-ink-bar' with `mat-stretch-tabs` responsive bug on 'mat-sidenav' open 

### ISSUE THREAD

**Issue by raphael22** [angular/material2#12234] opened 2018-07-16 15:51 UTC
#### Bug, feature request, or proposal:
Bug: `mat-ink-bar` element didn't resize correctly when `nav-tab` is used inside a `mat-sidenav`.

#### What is the expected behavior?
`mat-ink-bar` element should resize on sidenav events even with `mat-stretch-tabs` attribute

#### What is the current behavior?
`mat-ink-bar` element kept is old width/position value on sidenav open/close.

![screenshot from 2018-07-16 17-46-49](https://user-images.githubusercontent.com/3912356/42768631-55e3f466-8920-11e8-8ca8-369a6e196583.png)
![screenshot from 2018-07-16 17-47-14](https://user-images.githubusercontent.com/3912356/42768634-575e42ce-8920-11e8-807f-39104c2194d2.png)

#### What are the steps to reproduce?
Click on a Tab then toggle sidenav. There should be a visual bug like in screenshots above.

[https://stackblitz.com/edit/angular-owgx3w](https://stackblitz.com/edit/angular-owgx3w)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular : 6.0.9
@material: 6.3.3
Linux/Windows
Typescript 2.7.2/2.9
Browsers: Chrome/Firefox

**Comment by dannye** [comment] 2018-08-17 13:39
I just noticed this myself today. Is it possible there is some kind of css workaround until this bug is fixed?

**Comment by dannye** [comment] 2018-08-17 18:30
The only workaround I've thought of so far is firing a window resize event when the sidenav is opened/closed/toggled.

```
  toggleSideNav() {
    this.mainNav.toggle();
    setTimeout(() => {
      if (typeof(Event) === 'object') {
        // IE
        var resizeEvent = window.document.createEvent('UIEvents');
        resizeEvent.initUIEvent('resize', true, false, window, 0);
        window.dispatchEvent(resizeEvent);
      }
      else {
        // everything else
        window.dispatchEvent(new Event('resize'));
      }
    }, 150);
  }
```

Although this isn't ideal at all.
The reason the resize event is in a timeout is because the ink bar needs to be updated after the sidenav is finished opening/closing, otherwise the ink bar will still be a few pixels off - but of course the delay looks awkward.
Another problem with this workaround is IE lags really badly when resize events are created programmatically (at least for me), even though it works very smooth in Chrome/FF.

However I noticed that the ink bar always behaves correctly (when the sidenav is opened/closed) if the tab group has the pagination controls enabled.
Is there a way to force the tab group to enable pagination controls even when they're not needed? (as in both pagination arrows would be grayed out)
This would be a decent temporary workaround in my opinion.

**Comment by Spanja** [comment] 2018-08-17 23:07
duplicate of #6130 I guess

**Comment by mmalerba** [comment] 2018-08-20 16:04
closing as dup

**Closed by mmalerba** 2018-08-20 16:04 UTC
