### ISSUE TITLE
Proposal: Split Layout

### ISSUE THREAD

**Issue by hwalyonglance** [angular/material2#9185] opened 2018-01-01 23:16 UTC
[https://vaadin.com/elements/vaadin-split-layout/html-examples/split-layout-integration-demos](https://vaadin.com/elements/vaadin-split-layout/html-examples/split-layout-integration-demos)

**Comment by Chan4077** [comment] 2018-01-02 08:26
Duplicate of #7940. Please search issues before posting.

**Comment by josephperrott** [comment] 2018-01-02 19:14
closing as duplicate of #7940

**Closed by josephperrott** 2018-01-02 19:14 UTC
