### ISSUE TITLE
Bug paginator with zoom in css

### ISSUE THREAD

**Issue by Draksoux** [angular/material2#12501] opened 2018-08-03 10:54 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
pop-up when i click on "items per page" should be re-sized and well positionned

#### What is the current behavior?
pop-up insn't well positionned and not re-sized

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-v87lkq

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
See on stackblitz

#### Is there anything else we should know?
Is there alternatives to re-size all my app to get a zoom of 80%?

**Comment by crisbeto** [comment] 2018-08-03 11:32
Closing as a duplicate of https://github.com/angular/material2/issues/10924.

**Closed by crisbeto** 2018-08-03 11:32 UTC
