### ISSUE TITLE
mat-expansion-panel animates expanded to closed when nested in a mat-dialog

### ISSUE THREAD

**Issue by WrongWayJerry** [angular/material2#13936] opened 2018-11-01 21:49 UTC
#### Bug, feature request, or proposal:
With Angular 7 the mat-expansion-panel when it is in a mat-dialog will "flash" from expanded to closed when the dialog is initially displayed.

#### What is the expected behavior?
Should behave like Angular 6 and should not show as expanded and then immediately close when a dialog is opened.

#### What is the current behavior?
When displaying a mat-dialog the expansion panel will display its contents expanded and then immediately close.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

https://angular-wlrqxn.stackblitz.io

If you cannot open the sample add the following code to the mat-dialog example on the Angular 7 site - stackblitz example:

https://stackblitz.com/angular/koppvkvpmpdn?file=app%2Fdialog-overview-example-dialog.html

```
<div mat-dialog-content>
  <p>What's your favorite animal?</p>
  <mat-form-field>
    <input matInput [(ngModel)]="data.animal">
  </mat-form-field>
  <mat-expansion-panel>
        <mat-expansion-panel-header>
            <mat-panel-title>
                Hello
            </mat-panel-title>
        </mat-expansion-panel-header>
        <mat-card-content>
          <div>World!</div>
          <div>World!</div>
          <div>World!</div>
          <div>World!</div>
          <div>World!</div>
        </mat-card-content>
  </mat-expansion-panel>
</div>
```

#### What is the use-case or motivation for changing an existing behavior?
The content of the expansion panel should not display if the panel is closed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7,
Windows
Firefox and Chrome

**Comment by manklu** [comment] 2018-11-01 22:30
Duplicate of https://github.com/angular/material2/issues/13870

**Comment by crisbeto** [comment] 2018-11-02 06:35
Closing as a duplicate.

**Closed by crisbeto** 2018-11-02 06:35 UTC
