### ISSUE TITLE
md-tab-nav-bar wraps instead of scrolls

### ISSUE THREAD

**Issue by drosskopf** [angular/material2#7331] opened 2017-09-26 14:42 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I would expect that if I used the md-tab-nav-bar directive that it would have the same functionaliy as the 
md-tab-group except allowing you to use a router outlet.  With md-tab-group you have scroll tabs, however with md-tab-nav-bar the tabs are wrapping instead of scrolling.  

#### What is the current behavior?
Currently when using md-tab-nav-bar the tabs are wrapping instead of scrolling.  

#### What are the steps to reproduce?
1. Using the angular material example code
<nav md-tab-nav-bar>
  <a md-tab-link
     *ngFor="let link of navLinks"
     [routerLink]="link"
     routerLinkActive #rla="routerLinkActive"
     [active]="rla.isActive">
    {{tabLink.label}}
  </a>
</nav>

<router-outlet></router-outlet>

Add 5 more tabs, then view tabs on a cell phone, or a small screen.  Notice the tabs are wrapping instead of scrolling.  

#### What is the use-case or motivation for changing an existing behavior?
Scrolling tabs are needed for the best mobile experience.  

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All versions are affected

#### Is there anything else we should know?
Nope

**Comment by willshowell** [comment] 2017-09-26 14:46
See https://github.com/angular/material2/issues/2177

**Comment by josephperrott** [comment] 2017-09-26 15:30
Closing as duplicate of #2177

**Closed by josephperrott** 2017-09-26 15:30 UTC
