### ISSUE TITLE
Mat-menu dropdown positioned wrong on zoomed ipad

### ISSUE THREAD

**Issue by notBald** [angular/material2#14164] opened 2018-11-15 20:36 UTC
#### Bug, feature request, or proposal:
Bug

![screenshot from ios 12](https://user-images.githubusercontent.com/17722443/48579656-66092980-e91d-11e8-8712-b35530b0f07d.PNG)

#### What is the expected behavior?
Menu opens and stays in the right position when zoomed.

#### What is the current behavior?
Open a menu while zoomed, or zoom with a menu open, and its will be positioned wrongly.

#### What are the steps to reproduce?
Use an iPad.

Go to [angular.io](https://material.angular.io/components/menu/overview) Zoom in on the page. Open the basic menu. Or, open the basic menu then zoom the page.

#### What is the use-case or motivation for changing an existing behavior?
The dropdown should work on mobile devices while zoomed. A user might for instance zoom to make the text bigger, causing the menu to seemingly disappear from view.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.0.3, Material 7.04, iOS 10 and 12, not tested on 11, Browser is Safari

#### Is there anything else we should know?
This problem does not occur with ngBootstrap's dropdown. So there are ways to implement drop down menus without this issue.

Zooming out with the Basic menu open (on Angular Material's example page for Mat-Menu), can result in items disappearing from the menu.

**Comment by crisbeto** [comment] 2018-11-16 16:37
Duplicate of https://github.com/angular/material2/issues/10924.

**Closed by crisbeto** 2018-11-16 16:37 UTC

**Comment by notBald** [comment] 2018-11-16 18:18
> Duplicate of #10924.

This issue isn't about the zoom css property, it's pinch to zoom. Something that happens automatically when selecting an input on an iOS.

**Comment by crisbeto** [comment] 2018-11-17 09:13
The root of the issue is the same. The numbers provided by `getBoundingClientRect` are incorrect both when you use the `zoom` property and when you've zoomed in the page. There's a similar discussion on https://github.com/angular/material2/issues/13090 as well.

**Comment by notBald** [comment] 2018-11-17 13:11
> The root of the issue is the same. The numbers provided by `getBoundingClientRect` are incorrect both when you use the `zoom` property and when you've zoomed in the page. There's a similar discussion on #13090 as well.

I see. Thanks.

It is disappointing that this is a low priority issue. It makes a good number of controls problematic on iPad, as the iPad has a tendency to zoom automatically.
