### ISSUE TITLE
Resizing the mat-option with height and line-height for the mat-autocomplete alters the autocomplete keyboard scrolling

### ISSUE THREAD

**Issue by oscarlagatta** [angular/material2#10038] opened 2018-02-20 12:05 UTC
#### Bug, feature request, or proposal:
Once the .mat-option class height and line-height have been modified the keyboard scrolling looses focus of the active option

#### What is the expected behavior?
the autocomplete results should scroll with the keyboard active item selected

#### What is the current behavior?
if the size of the .mat-option is modified the autocomplete scrolling loses the active option selected by the keyboard arrow (up/down)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

apply the following css styling

**.mat-autocomplete-panel {
    max-height: 455px !important;
}
.mat-option {
    height: 25px !important;
    line-height: 25px !important;
}**

#### What is the use-case or motivation for changing an existing behavior?
to behave as expected while scrolling with the keyboard

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "^5.0.0",
"@angular/material": "^5.2.1",
WINDOWS
Typescript 2.7.1
Chrome Version 63.0.3239.84 (Official Build) (64-bit)

**Comment by crisbeto** [comment] 2018-02-20 18:08
Duplicate of https://github.com/angular/material2/issues/7211 (`mat-select` and `mat-autocomplete` use the same option component).

**Closed by crisbeto** 2018-02-20 18:08 UTC

**Comment by oscarlagatta** [comment] 2018-02-20 18:51
Thanks I don’t see how one is related to the other, can you pls explain ?

**Comment by crisbeto** [comment] 2018-02-20 19:00
We currently assume that all options will have a particular height, which is why we have to truncate them as well. Your issue comes from the fact that you're overriding the height.

**Comment by oscarlagatta** [comment] 2018-02-20 19:28
Thank you for the clarification, I wonder what’s the alternative, or just
won’t happen as it’s what I understand. You can close the ticket. Thank you
for your feedback

**Comment by supersinex** [comment] 2018-06-06 14:59
I would also love a fix for this. Some of our autocompletes are composed of two or more lines of information, so the ability to change the height of the `mat-option` while maintaining the ability to navigate with the arrow keys would be great.

**Comment by noririco** [comment] 2019-02-18 15:39
This issue is so annoying, And how the hell do you change the 
 AUTOCOMPLETE_OPTION_HEIGHT 
no docs no nothing ;/

**Comment by Sahil624** [comment] 2019-05-29 07:07
I think option height and autocomplete height should be configurations (@Input()).

**Comment by mohamed-badaoui** [comment] 2019-06-01 19:00
RIght now, the only way to overcome this is probably to add some global main style, like this :(

.mat-autocomplete-panel mat-option {
    height: 25px;
}

**Comment by meirg** [comment] 2019-06-13 23:08
> RIght now, the only way to overcome this is probably to add some global main style, like this :(
> 
> .mat-autocomplete-panel mat-option {
> height: 25px;
> }

The problem is this does not change the virtual scrolling item size so when you cycle through with the arrow keys it doesn't scroll the right amount

**Comment by deepthir9977** [comment] 2019-07-09 07:10
Hi guys,
i am using mat autocomplete i had Resizing the mat-option with height and line-height for the mat-autocomplete like below
 .mat-autocomplete-panel mat-option {
height: 25px;
}
i am not able to see the highlighted option on arrow key down.
is there any solution please help.

**Comment by Sahil624** [comment] 2019-07-09 07:32
> Hi guys,
> i am using mat autocomplete i had Resizing the mat-option with height and line-height for the mat-autocomplete like below
> .mat-autocomplete-panel mat-option {
> height: 25px;
> }
> i am not able to see the highlighted option on arrow key down.
> is there any solution please help.

I think height of autocomplete and mat-option is constant , so when you scroll with keys it will only scroll when that constant height is breached (I'm not 100% sure but I think it works like this). When you define height globally It only changes the height but not the constants hardcoded. I had same issue I fixed it with some rxjs but it created some new issues, so I reset global styles and used default styles by angular. 

**I don't think that there is any workaround. But if anyone knows any please comment**
