### ISSUE TITLE
Material Plunker XHR issues

### ISSUE THREAD

**Issue by j3ddesign** [angular/material2#5343] opened 2017-06-24 04:57 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Plunker example should load

#### What is the current behavior?
Whe loading the plunker, I get the loading state of "Loading the Angular Material App..." however the console gives me the following error:
```
zone.min.js:1 Error: (SystemJS) XHR error (404 Not Found) loading http://run.plnkr.co/6RW9gksgtEInIMCT/@angular/cdk.ts
	Error: XHR error (404 Not Found) loading http://run.plnkr.co/6RW9gksgtEInIMCT/@angular/cdk.ts
	    at d (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:10303)
	    at XMLHttpRequest.t [as _onreadystatechange] (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:730)
	    at e.invokeTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:15723)
	    at n.runTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:13076)
	    at XMLHttpRequest.invoke (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:16836)
	Error loading http://run.plnkr.co/6RW9gksgtEInIMCT/@angular/cdk.ts as "@angular/cdk" from https://rawgit.com/angular/material2-builds/master/bundles/material.umd.js
	    at d (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:10303)
	    at XMLHttpRequest.t [as _onreadystatechange] (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:730)
	    at e.invokeTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:15723)
	    at n.runTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:13076)
	    at XMLHttpRequest.invoke (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:16836)
	Error loading http://run.plnkr.co/6RW9gksgtEInIMCT/@angular/cdk.ts as "@angular/cdk" from https://rawgit.com/angular/material2-builds/master/bundles/material.umd.js
```

#### What are the steps to reproduce?
Load the plunker template and open console
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome

**Comment by donroyco** [comment] 2017-06-24 08:52
Already being tracked in #5285

**Comment by jelbourn** [comment] 2017-06-24 12:51
Dupe of #5245

Please search for existing issues before filing.

**Closed by jelbourn** 2017-06-24 12:51 UTC
