### ISSUE TITLE
nested json object in Data Table

### ISSUE THREAD

**Issue by tanmayparmar** [angular/material2#14432] opened 2018-12-09 06:09 UTC
#### Please describe the feature you would like to request.
How can i display nested json object in Material Data table. 

#### What is the use-case or motivation for this proposal?
Display nested json object in Data Table

#### Is there anything else we should know?
my nested json ovject is like this ..

code: 200
data:
eduqualification: (3) [{…}, {…}, {…}]
immigration: (4) [{…}, {…}, {…}, {…}]
membercategory: (4) [{…}, {…}, {…}, {…}]
occupation: (3) [{…}, {…}, {…}]
user: (5) [{…}, {…}, {…}, {…}, {…}]

i want to access user object in this directive "*matCellDef="let allYuvaks""

**Comment by andrewseguin** [comment] 2018-12-10 22:36
If you ask our community on StackOverflow or Gitter, I'm sure someone can help you out. Closing since this is not a bug or feature request

**Closed by andrewseguin** 2018-12-10 22:36 UTC
