### ISSUE TITLE
[mdDatepickerToggle] Error in compatibility mode in v2.0.0-beta.10

### ISSUE THREAD

**Issue by aatkin** [angular/material2#6942] opened 2017-09-08 13:07 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-datepicker-toggle should render button correctly in compatibility mode.

#### What is the current behavior?
Error is thrown when rendering mat-datepicker-toggle:
`
Error: The "md-" prefix cannot be used in ng-material v1 compatibility mode. It was used on an "button" element.
`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.0-RC.0
Angular material 2.0.0-beta.10
Chrome 60.0.3112.113

#### Is there anything else we should know?
Error cause seems to be in this file: https://github.com/angular/material2/blob/master/src/lib/datepicker/datepicker-toggle.html

md-icon-button directive is included in the button element, which is forbidden in the compatibility mode (as far as I understand).

**Comment by andrewseguin** [comment] 2017-09-08 18:16
This is due to `datepicker-toggle.html` using `md-icon` and `md-icon-button`. Forcing compat mode off for this component should fix that

**Comment by willshowell** [comment] 2017-09-22 01:24
@andrewseguin @jelbourn I don't believe https://github.com/angular/material2/pull/7219 fixed this

Reproduction: http://plnkr.co/edit/byxfI089teHANckdiqE1?p=preview (check console)

**Comment by jelbourn** [comment] 2017-09-26 04:46
Closing since it should be fixed in beta.11

**Closed by jelbourn** 2017-09-26 04:46 UTC
Labels: has pr
