### ISSUE TITLE
Tab's change animation breaks rendering of mat-paginator (mat-table) and mat-checkbox contained in the tabs

### ISSUE THREAD

**Issue by ps1dr3x** [angular/material2#8517] opened 2017-11-17 17:53 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Tab is changed and the contained view is rendered correctly

#### What is the current behavior?
The animation on tab change causes mat-paginator and checkboxes to be pushed up and out of the view of the table row/cell. It is curious that if a very quickly switch from tab A to tab B and back to A is made, A is rendered correctly.

#### What are the steps to reproduce?
I have a mat-tab-group with three tabs, each one containing a paginated mat-table with some mat-checkbox, when i switch from a tab to another, all the views inside tabs are incorrectly rendered.
I'll provide an example as soon as i have a moment.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.0.2
Material: 5.0.0-rc0
OS: Windows 10 (I'll try to reproduce on Debian sid later at home)
Typescript: 2.6.1
Browser: Electron 1.7.9 (Chromium: 58.0.3029.110, V8: 5.8.283.38)

#### Is there anything else we should know?
User @abcox described the same problem on #4227 
Maybe it's related to #5269

**Comment by josephperrott** [comment] 2017-11-17 18:28
Can you provide a reproduction in either [Plunker](https://goo.gl/uDmqyY) or [StackBlitz]( https://goo.gl/wwnhMV).  This will aide us in finding the issue you are seeing.

**Comment by abcox** [comment] 2017-11-17 19:25
[Plunker](https://plnkr.co/edit/1IshspkytcAgq7b6eYqC?p=preview) of my issue related to animation rendering checkbox incorrectly in table row.

**Comment by julianobrasil** [comment] 2017-11-19 10:37
@abcox, curisously, if you get rid of all your custom classes, and replace your `<input type="checkbox">` with any other element, it works fine: https://plnkr.co/edit/B3fJLuV1Y2DPK9G0tlrM?p=preview

![image](https://media.giphy.com/media/xUOxfcAdU3NzO9mms0/giphy.gif)

**Comment by wandri** [comment] 2017-11-21 14:30
Same problem here. The work-around of @julianobrasil doesn't work for me with angular material 5.0.0-rc.1 and 5.0.0-rc0.

What is strange is:
- When i click on the checkbox, it moves to the top. But in the debuger, when i remove one of the styles of _.mat-checkbox-ripple_ and then, I add it again. the checkbox get back to its normal position.

**Comment by skonx** [comment] 2017-12-19 15:00
Hi there. I've fixed this strange issue with a `&nbsp;` between the mat-chechbox tags.

**Comment by julianobrasil** [comment] 2017-12-19 18:20
@josephperrott, you've marked this issue with a "cannot reproduce" but by visiting https://plnkr.co/edit/IF1rRPZp1H53DcnN3Vv8?p=preview, I can see it happening in my Windows 10 machine using:

1. Chrome (the checkbox is shifted up considerably, like is shown in the animated gif above)
2. IE11
3. Edge

It's working fine in the last beta of Firefox.

**Comment by andrewseguin** [comment] 2018-01-22 22:47
This seems to be a problem separate from table, but exposed by how the cell styles work.

Here's an example of the checkbox's behavior in the same CSS structure:
https://stackblitz.com/edit/angular-zc9dkd?file=app/checkbox-overview-example.html

**Comment by andrewseguin** [comment] 2018-01-22 22:50
Note that the best way to work around this for now was posted above. Use `overflow: visible` for the affected cells

**Comment by andrewseguin** [comment] 2018-01-23 19:11
Closing as dupe of #8600

**Closed by andrewseguin** 2018-01-23 19:11 UTC
