### ISSUE TITLE
`display: flex` on `.md-tab-body-wrapper` is causing problems

### ISSUE THREAD

**Issue by fxck** [angular/material2#1416] opened 2016-10-03 18:05 UTC
It causes this..

![image](https://cloud.githubusercontent.com/assets/1303561/19047943/5d4ff56a-89a4-11e6-920c-e7539fc30476.png)

..any inner content is only as wide as need be.. which is not something you usually want. Is there any particular reason for that `flex`? Can't it be just `block`, which would solve it?

**Comment by jelbourn** [comment] 2016-10-05 16:46
Yeah, I would consider this a bug.

**Comment by andrewseguin** [comment] 2016-11-11 00:33
I don't believe this is a problem anymore. There have been a good amount of changes made recently to how tab content is created.

Here's an example of tabs with simple text bodies that span the width of the tab group.
http://plnkr.co/edit/pEqGa6YwmTE2fxBDEGJf?p=preview

Please reopen if you can reproduce the issue.

**Comment by fxck** [comment] 2016-11-14 17:37
What @Salma7amed said still is not fixed https://github.com/angular/material2/issues/1416#issuecomment-253118189 there are `overflow`s set that are causing the content to be clipped, for example when you use `md-card` inside a tab content, shadows are clipped.

@andrewseguin

**Comment by fxck** [comment] 2016-11-14 17:39
See http://plnkr.co/edit/29KyvgWew3qktBFhTIZM?p=preview

**Comment by JacobBrandt** [comment] 2017-03-10 18:44
@fxck Can you please reopen this?  This is still an issue as your plnkr clearly demonstrates.

**Comment by fxck** [comment] 2017-03-10 18:47
Don't have the option.

**Comment by JacobBrandt** [comment] 2017-03-10 18:51
@fxck Ah ok.
I'm going to tag @andrewseguin since he closed it.  Hopefully he has the power to open it for you.

**Comment by andrewseguin** [comment] 2017-03-10 19:51
Just to make sure I'm capturing the right issue here, I'll run through what has been discussed.

This issue began as the body wrapper not spanning the width of the tabs. That appears fixed.

The second issue presented is that dropdown menus do not overflow correctly. It appears that is because the menu overlay was placed within the tab. MdSelect does not have this issue since the overlay is placed on the page body.

The third issue seems to be that the md-card does not show shadows when the card's width and height matches the width and height of the tab. I'm not sure I understand the requested behavior. Do you want the shadows to extend beyond the bottom and sides of the tab?

Here's a plunker we can use as a template for this discussion: https://plnkr.co/edit/Zf4mLF1iTiosrmMo0wkr?p=preview

**Comment by andrewseguin** [comment] 2017-03-10 19:52
Note that my goal here is to close this issue after we figured out if a new issue should be created based on this discussion. This thread has already diverted away from the original issue.

**Comment by JacobBrandt** [comment] 2017-03-10 19:53
@andrewseguin I agree.  I think new issues should be created.

**Comment by andrewseguin** [comment] 2017-03-14 17:41
Encapsulation set to None is one option, there are two others.

1. Use /deep/ in your CSS selectors
2. Use a global style sheet that is loaded outside of Angular (not a part of any styleUrls).

Closing the issue now since there is no activity, but please feel free to open it back up if there are any remaining issues that cannot be resolved. Just please use the issue template, it helps us tremendously :)

**Closed by andrewseguin** 2017-03-14 17:41 UTC
Labels: P3: important
