### ISSUE TITLE
Implement Placeholder Text for MdInput as per material.io guideline

### ISSUE THREAD

**Issue by borislemke** [angular/material2#4930] opened 2017-06-02 11:40 UTC
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Able to add hint / helper text alongside label

#### What is the current behavior?
It is not possible to have a label AND helper text (or actual input placeholder) together.

![alt text](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B5ZSepuCX1xOT2Jzcm5LclUzTTg/placeholder.png "Input Placeholder")

#### What are the steps to reproduce?
API for this feature does not currently exist

#### What is the use-case or motivation for changing an existing behavior?
Follow official material guideline

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by mmalerba** [comment] 2017-10-13 20:06
closing as duplicate of #6194

**Closed by mmalerba** 2017-10-13 20:06 UTC
Labels: discussion, feature
