### ISSUE TITLE
button will append one <div lass="md-ripple-foreground md-ripple-fade-in" style="..."> when clicked

### ISSUE THREAD

**Issue by dennis-xlc** [angular/material2#997] opened 2016-08-11 08:27 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?

`<div lass="md-ripple-foreground md-ripple-fade-in" style="...">` will disappeared after clicked

#### What is the current behavior?

`<div lass="md-ripple-foreground md-ripple-fade-in" style="...">` remain at DOM after click

#### What are the steps to reproduce?
1. add one button at the template
`
<button md-icon-button>
  <md-icon>menu</md-icon>
</button>
`
2. click on the button repeatedly until exceed current height of DOM
3. check the source of DOM, will find many `<div lass="md-ripple-foreground md-ripple-fade-in" style="...">`

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
cannot reproduced at Plunker

#### What is the use-case or motivation for changing an existing behavior?
This behavior will break the normal DOM

#### Which versions of Angular, Material, OS, browsers are affected?
Angular Version: 2.0.0-rc.5
Material Version: @angular2-material/button@2.0.0-alpha.7-2
OS: Windows 7
Browser Version: Google Chrome 52.0.2743.116 m

**Comment by colinfang** [comment] 2016-08-11 10:49
Dupe of #972

**Comment by ultrapromedia** [comment] 2016-08-11 11:17
Confirmed

**Comment by jelbourn** [comment] 2016-08-31 01:37
Closing as dupe.

**Closed by jelbourn** 2016-08-31 01:37 UTC
