### ISSUE TITLE
md-input type number in firefox

### ISSUE THREAD

**Issue by michaelhornak** [angular/material2#6251] opened 2017-08-03 15:33 UTC
**Do you want to request a feature or report a bug?**

BUG

**Bug Report**

in firefox input type number placeholder doubles the text in placeholder. you can see the behavoir here
https://embed.plnkr.co/wRcNOWKpZUq9dDa1HR6w/

The issue is also mentioned here https://github.com/Teradata/covalent/issues/792

**What is the expected behavior?**

to work like in chrome

**Which version of Angular and Material, and which browser and OS does this issue affect?**

Browser Firefox

**Comment by princemaple** [comment] 2017-08-04 00:35
https://github.com/angular/material2/issues/6194

**Comment by mmalerba** [comment] 2017-08-04 06:06
duplicate of #4621 It will be fixed in the next version of Firefox (55). 

Also I plan to separate the `placeholder` and `label` which should fix this issue for versions of Firefox older than 55 (see #6240)

**Closed by mmalerba** 2017-08-04 06:06 UTC
