### ISSUE TITLE
IE11: Cannot open a dialog from inside a dialog

### ISSUE THREAD

**Issue by mortenamby** [angular/material2#7005] opened 2017-09-12 11:34 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Opening a new dialog from within a dialog should work in Internet Explorer 11.

#### What is the current behavior?
When opening a dialog from within another dialog, the new dialog is not displayed.

#### What are the steps to reproduce?
1. Open a dialog instance.
2. From inside this instance, try to open another different dialog (without closing the first one).
3. In IE11 nothing happens.

#### What is the use-case or motivation for changing an existing behavior?
It may be desirable to open a new modal from an existing one, and it works for Chrome so there's no reason it shouldn't work for IE too

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Currently running:
@angular/material: 2.0.0-beta.10
@angular/core: 4.2.4
@angular/cdk 2.0.0-beta.10

#### Is there anything else we should know?
I'd provide a plunker but since plunker is not affected by what browser you're using it is irrelevant. Instead it can be tested with a quick sample through the CLI.

**Comment by donroyco** [comment] 2017-09-12 12:38
You didn't see #7004?

**Comment by crisbeto** [comment] 2017-09-13 18:34
Closing as a duplicate of https://github.com/angular/material2/issues/6719.

**Closed by crisbeto** 2017-09-13 18:34 UTC
