### ISSUE TITLE
sidenav-container's content does not relocate after sidenav's resize

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#8613] opened 2017-11-23 13:45 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
sidenav-container's content should relocate when sidenav width changes

#### What is the current behavior?
sidenav-container's content  does not relocate when sidenav width changes

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-nmafhq

#### What is the use-case or motivation for changing an existing behavior?
Modifying/adding/removing content from the sidenav breaks UI.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material: 5.0.0-rc0
Chrome (At least): 62.0.3202.94

**Comment by crisbeto** [comment] 2017-11-23 19:52
Closing as a duplicate of https://github.com/angular/material2/issues/6743.

**Closed by crisbeto** 2017-11-23 19:52 UTC
