### ISSUE TITLE
Allow passing TemplateRef/component type to tooltip

### ISSUE THREAD

**Issue by IliaVolk** [angular/material2#8357] opened 2017-11-10 12:51 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Allow creating tooltip from ng-template or component type and change it dynamically
At least ng-template
Something like:

```
<span [matTooltip]="tooltipTemplate">I have a tooltip</span>
<ng-template #tooltipTemplate>
     <b>Bold</b> message
</ng-template>
```
#### What is the current behavior?
Only strings allowed

#### What is the use-case or motivation for changing an existing behavior?
Allow to greater customize tooltip message

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all

**Comment by willshowell** [comment] 2017-11-10 14:29
See https://github.com/angular/material2/issues/5440#issuecomment-313740211 for why the team doesn't plan to support it.  You may be interested in https://github.com/angular/material2/issues/2691.

**Comment by josephperrott** [comment] 2017-11-10 16:48
Closing as duplicate of #5440

**Closed by josephperrott** 2017-11-10 16:48 UTC
