### ISSUE TITLE
[mat-table] data not re-rendered when sort and/or paginator is set.

### ISSUE THREAD

**Issue by MarioJonckers** [angular/material2#12452] opened 2018-07-31 07:15 UTC
Our customer wants to be able to cancel made changes to the data in the MatTableDataSource at any time before saving. So I need to reset the data to the original data when he decides to cancel his changes.

#### Bug:
When I reset the data property of the MatTableDataSource and render the table rows, the changes do not reflect in the view. You have to loop over the data in the MatTableDataSource and manually set the properties back to their original values...

But if you have pagination and sorting enabled, you also have to remove them from the MatTableDataSource BEFORE rendering the table rows, and then you can reset these as well...

After days of searching I managed to get it working like described above.

#### What is the expected behavior?
I expect I can just set the data property of the MatTableDataSource to a complete new set of data, and render the rows and the view reflects to the changed data.
I do not want to loop over the data of the MatTableDataSource to manually reset the properties.
Also I do not expect I have to remove the sort and paginator before I render the rows to get it working.

#### What is the current behavior?
You can only reset values of the current data in the MatTableDataSource, so not completely re-initialize new data. There can not be a MatSort or MatPaginator set to the MatTableDataSource to reflect the changes after rendering the rows.

#### What are the steps to reproduce?
After days of research and trial/error I managed to get the cancelable changes working like described above. I have made a simple example on StackBlitz here https://stackblitz.com/edit/angular-material-cancelable-table

If you do not remove the sort or paginator, the view doesn't pick up these changes.

#### What is the use-case or motivation for changing an existing behavior?
We have a customer who wants to be able to cancel made changes in the data of the MatTableDataSource at any time (if he hasn't saved his changes of course) and when he cancels his changes, we need to re-initialize the data.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular - 6.1.0
Angular-Material - 6.4.1

#### Is there anything else we should know?
No

**Comment by josephperrott** [comment] 2018-08-08 17:32
Closing, from looking at your reproduction it looks like the issue you were encountering is actually an issue with the objects within your dataset not changing in reference, but just changing the properties within.  This causes the change detection to treat them as the same value and not mark them for check, so the view does not update (in your case showing a checked state).

I have [forked your reproduction](https://stackblitz.com/edit/angular-material-cancelable-table-nxlib5?file=app/component/table.component.ts), where you can see that by replacing the `data` attribute on `MatTableDataSource` with an array of new objects (with difference object references) it works as you expected.

You do not need to modify the `MatPaginator` or `MatSort` on the `MatTableDataSource` since a change in the `data` property causes a new emit on the subject which cascades through all of the filter, pagination and sorting.

**Closed by josephperrott** 2018-08-08 17:32 UTC
