### ISSUE TITLE
Errors after taking 2.0.0-alpha.5

### ISSUE THREAD

**Issue by pkapare** [angular/material2#587] opened 2016-05-31 16:44 UTC
#### Bug, feature request, or proposal:
After taking latest build i.e. 2.0.0-alpha.5 from NPM I am getting following errors.
node_modules/@angular2-material/core/gestures/MdGestureConfig.d.ts(4,40): error TS2304: Cannot find name 'HammerManager'.
node_modules/@angular2-material/core/overlay/overlay.d.ts(5,31): error TS2306: File 'd:/xxx/node_modules/@angular2-material/core/overlay/position/viewport-ruler.d.ts' is not a module.
node_modules/@angular2-material/core/overlay/position/connected-position-strategy.d.ts(3,31): error TS2306: File 'd:/xxx/node_modules/@angular2-material/core/overlay/position/viewport-ruler.d.ts' is not a module.
node_modules/@angular2-material/core/overlay/position/connected-position-strategy.d.ts(4,10): error TS2305: Module '"d:/xxx/node_modules/@angular2-material/core/overlay/position/connected-position"' has no exported member 'ConnectionPair'.
node_modules/@angular2-material/core/overlay/position/connected-position-strategy.d.ts(12,22): error TS2420: Class 'ConnectedPositionStrategy' incorrectly implements interface 'PositionStrategy'.
  Property 'apply' is missing in type 'ConnectedPositionStrategy'.
node_modules/@angular2-material/core/overlay/position/global-position-strategy.d.ts(6,22): error TS2420: Class 'GlobalPositionStrategy' incorrectly implements interface 'PositionStrategy'.
  Property 'apply' is missing in type 'GlobalPositionStrategy'.
node_modules/@angular2-material/core/overlay/position/overlay-position-builder.d.ts(1,31): error TS2306: File 'd:/xxx/node_modules/@angular2-material/core/overlay/position/viewport-ruler.d.ts' is not a module.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by pkapare** [comment] 2016-05-31 19:13
Added hammer typings. 'HammerManager' error fixed however other errors still showing up.

**Comment by carathorys** [comment] 2016-05-31 20:57
It seems the overlay is broken in alpha 5, there were some missing exports. 
As far as i can see in the current source code, the next release will fix this problem, until then, you should use alpha 4, or just avoid using overlay.

**Comment by DennisSmolek** [comment] 2016-06-01 14:40
I'm not having the same issues, try doing uninstall/reinstall `npm uninstall @angular2-material/core --save` then `npm install @angular2-material/core --save`

I'm using both the overlay and regular core code, no hammer stuff though

**Comment by jelbourn** [comment] 2016-06-01 16:24
Dupe of #535

**Closed by jelbourn** 2016-06-01 16:24 UTC
