### ISSUE TITLE
Layout not displaying properly inside MD-Dialog

### ISSUE THREAD

**Issue by paistipoikka** [angular/material2#2446] opened 2016-12-28 14:12 UTC
#### Bug, feature request, or proposal:

Bug

Using angular/flex-layout I am trying to create a layout that is 400px wide for use inside an <md-dialog>.

```
<form role="form" (ngSubmit)="authorize(loginForm)" novalidate  #loginForm="ngForm">
        <div fxLayout="row"> 
            <h3>Enter Login Credentials</h3>
        </div>
        <div fxLayout="row"> 
            <p class="validation-message" *ngIf="authorisationErrorMessage">{{authorisationErrorMessage}}</p>
        </div>
        <div fxLayout="row">
            <div fxFlex="400px" fxFlex.gt-xs="400px" fxFlex.xs="300px">
                <md-input-container class="fullwidth"> 
                    <input md-input 
                        name="licenceNumber"
                        placeholder="Licence Number" >   
                </md-input-container>
            </div>
        </div>
        <div fxLayout="row">
            <div fxFlex="400px" fxFlex.xs="300px">
                <md-input-container class="fullwidth"> 
                    <input md-input 
                        name="email"
                        placeholder="Email">       
                </md-input-container> 
            </div> 
        </div>
        <div fxLayout="row">
            <div fxFlex="400px" fxFlex.xs="300px">
                <md-input-container class="fullwidth"> 
                    <input md-input 
                        name="plainPassword"
                        placeholder="Password"
                        type="password">     
                </md-input-container>
            </div>  
        </div>
        <div fxLayout="row">
            <div fxFlex="400px" fxFlex.xs="300px">
                <button md-raised-button color="primary" type="submit">Login</button>
            </div>
        </div> 
</form>
```
In this case I am expecting a form that is 400px wide yet when I measure it is only 320px. It appears as if the dimensions for the layout are being ignored. 

This has been raised with the Flex-Layout team and they have indicated that this is a material problem. For the details see:

https://github.com/angular/flex-layout/issues/68

#### What are the steps to reproduce?

See Plunkr:

https://plnkr.co/edit/ea51R3?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?

Chrome on OSX

**Comment by crisbeto** [comment] 2016-12-28 16:25
It's because the minimum width for the wrappers is provided via `flex-basis` (e.g. `flex: 1 1 400px`), however this doesn't work inside the dialog, because we're using flexbox to center it. It can be reproduced with the following, which more or less represents what our DOM looks like:

```html
<!-- works -->
<div style="flex: 1 1 400px; height: 300px; background: #ccc; margin: 50px 0;"></div>

<!-- doesn't work -->
<div style="display: flex; align-items: center; justify-content: center;">
  <div>
    <div style="flex: 1 1 400px; height: 300px; background: #ccc;"></div>
  </div>
</div>
```

This can be worked around by giving your elements a minimum width (in this case it's `400px`). It might be worth adding the `min-width`, in addition to the `flex-basis` in the layouts module. What do you think @thomasburleson?

**Comment by ThomasBurleson** [comment] 2016-12-28 16:56
So if you add CSS to the [Plunkr Demo](https://plnkr.co/edit/ea51R3?p=preview)

```css
form > div {  
  min-width:400px;
}
```

it definitely seems to work better.

@crisbeto  - I will check... mostly I worry about regressions. Thx.

**Comment by crisbeto** [comment] 2017-01-06 20:52
I'll close this since https://github.com/angular/flex-layout/commit/3fe5ea3b16d1add8f7cf60636085db3237b966d1 should've sorted it out.

**Closed by crisbeto** 2017-01-06 20:52 UTC
