### ISSUE TITLE
when horizontal and more than 1row, there will be a legible drag and drop.

### ISSUE THREAD

**Issue by lichangfeng** [angular/material2#14741] opened 2019-01-07 06:26 UTC
#### Bug:
There are too many elements for drag and drop(horizontal), that one row cannot contain them, so the rest of them will bee  the second row. Then the drag and drop is confused.

#### What is the expected behavior?
when horizontal and more than 1row, there will be a legible drag and drop.

#### What is the current behavior?
the drag and drop is confused.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-furjhv

#### Is there anything else we should know?

**Comment by raphael22** [comment] 2019-01-08 10:09
Tracked here https://github.com/angular/material2/issues/13372 but not tagged as critical as it should be :(

**Comment by andrewseguin** [comment] 2019-01-09 23:07
Closing as duplicate of #13372

**Closed by andrewseguin** 2019-01-09 23:07 UTC
