### ISSUE TITLE
MatPaginator.html gives TypeError: Cannot read property 'subscribe' of undefined

### ISSUE THREAD

**Issue by ApoorvBarwa** [angular/material2#13004] opened 2018-09-06 14:26 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?

No Errors

#### What is the current behavior?

Currently while using Material Table `<table mat-table #sort="matSort" [dataSource]="dataSource" matSort matSortDisableClear></table>` 

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-va2xwy?file=src%2Fapp%2Fapp.component.ts

#### What is the use-case or motivation for changing an existing behavior?

The error i get is the same but it also points me to MatPaginator.html. Below is the exact error that i face.
`MatPaginator.html:1 ERROR TypeError: Cannot read property 'subscribe' of undefined
    at Observable.push../node_modules/rxjs/_esm5/Observable.js.Observable._subscribe (Observable.js:231)
    at Observable.push../node_modules/rxjs/_esm5/Observable.js.Observable._trySubscribe (Observable.js:172)
    at Observable.push../node_modules/rxjs/_esm5/Observable.js.Observable.subscribe (Observable.js:160)`

I face the same issue while using other material elements and those sometimes break. I believe these issues are related and just a configuration change or a package version change would solve it for us.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular CLI: 6.1.5
Node: 8.11.3
OS: win32 x64
Angular: 6.1.6
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cdk                      6.4.7
@angular/cli                      6.1.5
@angular/material                 6.4.7
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              5.6.0-forward-compat.5
typescript                        2.9.2
webpack                           4.9.2

#### Is there anything else we should know?
I searched a lot but could not find a solution to my problem. If you have any resources that would help me fix my issue then please point me towards it

**Comment by josephperrott** [comment] 2018-09-07 16:44
Closing as it seems that the issue you was caused by a mismatch in the versions of angular's platform packages being used. 

`@angular/forms` was at `6.0.0` while other `@angular` platform packages were `6.1.7`, upon moving `@angular/forms` to `6.1.7` everything works as expected.

**Closed by josephperrott** 2018-09-07 16:44 UTC

**Comment by lsnpiotrszprega** [comment] 2018-09-11 13:14
I have the same problem but just on prod

**Comment by 1011178l** [comment] 2018-09-12 12:11
I have the same problem

**Comment by ApoorvBarwa** [comment] 2018-09-13 18:16
@manklu : I am currently using rxjs 5.6.0-forward-compat.5. so is it a case that this is a bug if we use material 6.4.7 with this version of rxjs. The reason i am not updating to rxjs 6 currently is that there are many breaking changes and migrating the application from rxjs 5 to 6 would take some time. Is there any workaround for this currently that anyone might be aware of???

**Comment by 1011178l** [comment] 2018-09-14 11:46
For the people who have same issue:

The problem caused by mismatch version of rxjs and the material. We have to use rxjs 6+, rxjs forward compat doesn't work.

Because our project cannot upgrade the rxjs, so we have to back to material 5. 

Hope this info may help any one.

**Comment by nombrekeff** [comment] 2019-07-18 16:47
Hey there, my error was I was trying to translate the paginator, when removing this provider it worked:
```ts
import { MatPaginatorIntl } from '@angular/material';
...
providers: [
  {
     // Provide custom MdI18 provider
     provide: MatPaginatorIntl,
     useClass: MdI18n,
     useValue: LOCALE,
   },
]
```
