### ISSUE TITLE
Selecting item from nested mat-menu is not user-friendly

### ISSUE THREAD

**Issue by diminutivesloop** [angular/material2#9428] opened 2018-01-16 22:28 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Users should be able to quickly select the desired item from a menu.

#### What is the current behavior?
If a user attempts to select an item from a nested menu and their mouse leaves the currently selected menu item before reaching the sub-menu, then the sub-menu closes before the user is able to click their desired item.

#### What are the steps to reproduce?
![mat-menu-sub-menu-delay](https://user-images.githubusercontent.com/667716/35015445-6aeec510-fae2-11e7-8571-149ca9722fae.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 5.0.4

**Comment by jelbourn** [comment] 2018-01-16 23:22
[We discussed this a bit back when the nested menu was first added](https://github.com/angular/material2/pull/5493#issuecomment-313526471) but never got to actually adding it.

**Comment by crisbeto** [comment] 2018-01-17 17:28
Closing as a duplicate of https://github.com/angular/material2/issues/6548.

**Closed by crisbeto** 2018-01-17 17:28 UTC
Labels: P3: important
