### ISSUE TITLE
<md-slide-toggle> change handler not firing properly.

### ISSUE THREAD

**Issue by raceloop** [angular/material2#7168] opened 2017-09-19 11:42 UTC
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

The `<md-slide-toggle>` change event fires as component values changes

#### What is the current behavior?

component value is not passed to change handler when toggle value changes.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

For example:

```
<md-slide-toggle #showArchivedInput="ngModel"
                    [(ngModel)]="showArchived"
                    name="showArchived"
                    color="primary"
                    (change)="showArchived(showArchivedInput.value)">
                    Show Archived
                </md-slide-toggle>

...


showArchived(archived: boolean): void {
    console.log(archived); // incorrectly shows the inverse of the toggle state
}
```

#### What is the use-case or motivation for changing an existing behavior?

This was working as intended.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

material 2.0.0-beta.10
Angular 4.3.6
#### Is there anything else we should know?

this was working as intended. This was broken in the current release.

**Comment by DevVersion** [comment] 2017-09-19 12:13
Duplicate of https://github.com/angular/material2/issues/7074. Will be fixed with https://github.com/angular/material2/pull/7076

**Closed by DevVersion** 2017-09-19 12:13 UTC

**Comment by RaphyLi** [comment] 2017-09-22 11:44
Hi. 
I have the same problem despite the update beta.11.
But you can use the formControl until the pull to be approuved and included in next update.
