### ISSUE TITLE
Autocomplete issue with iPhone

### ISSUE THREAD

**Issue by mahmood-sajjadi** [angular/material2#6440] opened 2017-08-13 11:15 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Material2 Autocomplete should work with latest iPhones as lots of users using iPhone!

#### What is the current behavior?
User will not see the drop down for auto complete (is there is some data on top of auto complete)
so the user will not be able to select from drop down list

#### What are the steps to reproduce?
plunker : https://plnkr.co/edit/yUbHV4dZpfiwETGrF1e2?p=preview

1. just add some content on top of angular material2 demo : https://material.angular.io/components/autocomplete/examples
or just open provided plunker in iPhone

2. in iPhone scroll to reach autocomplete element
3. type something
4. drop down is not there but if you scroll carefully(focus shouldn't change or drop down will close) you will find drop down top of the page, far far away from autocompleting text box
5. you already saw the issue but if you still keep your finger on screen for scrolling you will find the speed of moving drop down and other contents are different(if you keep scrolling, dropdown will move faster than texts)

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
using Material for mobile first design and responsive design

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest, current demo, master

#### Is there anything else we should know?
This issue is not reproducible in simulators, you should use actual iPhone device
I checked this issue on two different version of iPhone, safari
1. 10.2.1
2. 10.3.3
same issue :(

**Comment by crisbeto** [comment] 2017-08-13 11:24
Closing as a duplicate of https://github.com/angular/material2/issues/6341.

**Closed by crisbeto** 2017-08-13 11:24 UTC
