### ISSUE TITLE
Setting FormControl value to null does not uncheck radio button

### ISSUE THREAD

**Issue by eyalhakim** [angular/material2#6697] opened 2017-08-29 16:39 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
setting form control value to null should uncheck radio button.

#### What is the current behavior?
setting form control value to null does not uncheck radio button.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.

this example doesn't work for me with the last beta 8 version:
http://plnkr.co/edit/1pMpIqTiVwOaRpkvAKh0?p=preview

when trying to install latest build, with latest build of CDK i have errors from CDK.

was this fixed?

**Comment by jelbourn** [comment] 2017-08-30 00:25
@tinayuangao is this the intended behavior?

**Comment by eyalhakim** [comment] 2017-08-31 16:21
@jelbourn still doesn't work for me in beta 10

**Comment by willshowell** [comment] 2017-08-31 18:32
@eyalhakim your plunker shows the radio button unchecking when you press the button. Based on 70bd5fc.

**Comment by eyalhakim** [comment] 2017-08-31 18:56
@willshowell as i said, it does work on the plunkr but not on the latest beta 10 release. Was this fixed in [70bd5fc](https://github.com/angular/material2/commit/70bd5fc20e7fe6b1749b334d29e842cb3681609d)?

**Comment by willshowell** [comment] 2017-08-31 19:18
Here it is with beta.10

https://plnkr.co/edit/FqGtndD2JgwjolSwunnF?p=preview

**Comment by eyalhakim** [comment] 2017-08-31 22:23
Thank you @willshowell it must be something different in my environment, not sure what though.
How do you advice me to debug this?

**Comment by willshowell** [comment] 2017-08-31 23:40
🤷‍♂️ I dunno without a reproduction

**Comment by eyalhakim** [comment] 2017-09-01 08:55
@willshowell got it:
https://plnkr.co/edit/WNCHDtop1oiAPMAs2HMs?p=preview

**Comment by willshowell** [comment] 2017-09-01 13:02
@eyalhakim I see. It looks like clicking on a radio button does change the form control value, but changing the form control value to _anything_ (not just `null`), is not reflected in the DOM.

**Comment by eyalhakim** [comment] 2017-09-01 14:07
@willshowell good catch, I actually didn't try other values.

**Comment by tinayuangao** [comment] 2017-09-02 00:24
@eyalhakim It's not a bug in checkbox. https://plnkr.co/edit/SQCP4NaoG3Btl50L0VUu?p=preview
After removed the list wrapper it works as intended (unchecked the radio button).

**Comment by eyalhakim** [comment] 2017-09-02 08:06
@tinayuangao please reopen this issue.
We know that it works without the list wrapper, this was the whole conversation above.

However, this radio button functionality should still work when used in conjunction with ng-template - which it doesn't.

**Comment by willshowell** [comment] 2017-09-05 14:36
@tinayuangao, I think @eyalhakim's concern is that the example works fine with native radios:

https://plnkr.co/edit/ChrSw7jb4NcOZTTLnNwM?p=preview

**Comment by eyalhakim** [comment] 2017-09-05 16:10
@willshowell yes, that's another way to explain it. Thank you

**Comment by tinayuangao** [comment] 2017-09-19 17:32
The problem is `ContentChildren` could not get `md-radio-button`s inside `ng-template`.

**Comment by eyalhakim** [comment] 2017-09-19 19:35
@tinayuangao i see, are you intending to fix this anytime soon?

**Comment by tinayuangao** [comment] 2017-11-16 19:17
Should be fixed by #7842 

Please reopen if it's not fixed

**Closed by tinayuangao** 2017-11-16 19:17 UTC

**Comment by eyalhakim** [comment] 2017-12-10 00:15
@tinayuangao unfortunately, this is still not fixed

**Comment by Ian5015** [comment] 2018-05-30 16:58
Confirmed, not fixed. Using Angular 6.0.0.

**Comment by eyalhakim** [comment] 2018-08-26 12:29
@tinayuangao @willshowell please reopen this issue.
