### ISSUE TITLE
Click targets are too small for buttons

### ISSUE THREAD

**Issue by dgfranklin** [angular/material2#9525] opened 2018-01-22 21:46 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Material Design spec says that [all touch targets much be at least 48x48.](https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-touch-target-size)

#### What is the current behavior?
Icon buttons and mini fab buttons are 40x40.  Basic buttons and raised buttons sizes are determined by their content but are generally also undersized (for example on the [reference page](https://material.angular.io/components/button/examples)).

#### What are the steps to reproduce?
Go to demo at https://stackblitz.com/edit/angular-cf8thc (a slightly stripped down version of the existing button demo)
Note that:
- All buttons have touch target size less than 48px vertically
- Icon buttons and mini fab buttons have touch target size less than 48px horizontally
- No non-standard styling has been applied to the buttons.

#### What is the use-case or motivation for changing an existing behavior?
This change would make us better align with the Material spec and make Angular Material more accessible.

**Comment by jelbourn** [comment] 2018-01-23 23:41
Duplicate of #8000

**Closed by jelbourn** 2018-01-23 23:41 UTC
