### ISSUE TITLE
Sidenav dynamic mode update backdrop

### ISSUE THREAD

**Issue by patrickhousley** [angular/material2#6805] opened 2017-09-02 03:18 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When the mode input is dynamically updated from over to side, the backdrop should be removed if it is currently present on the screen.

#### What is the current behavior?
When the mode input is dynamically updated from over to side, the backdrop is not removed if it is currently present on the screen.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
This should be considered a bug fix.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.6
Material 2.0.0-beta.10
OS X 10.11.6
TS 2.3.4
Chrome 60.0.3112.113

**Comment by willshowell** [comment] 2017-09-05 16:24
See https://github.com/angular/material2/issues/6271

**Comment by josephperrott** [comment] 2017-09-27 16:47
Closing as duplicate of #6271

**Closed by josephperrott** 2017-09-27 16:47 UTC
