### ISSUE TITLE
md-select change event not firing

### ISSUE THREAD

**Issue by Dgiulian** [angular/material2#2359] opened 2016-12-22 22:31 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
After the user selects a value from the select box, the change event must be fired.

#### What is the current behavior?
None. The change function asociated with the event is never executed.

#### What are the steps to reproduce?

Plunker: http://plnkr.co/edit/sSprD4?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?

"@angular/common": "2.3.1",   
"@angular/material": "^2.0.0-alpha.11-3",

**Comment by jmpmscorp** [comment] 2016-12-23 06:06
You could use (ngModelChange) instead of (change). This works for me:

`<md-select *ngIf="cultivos" placeholder="Cultivo" formControlName="idCultivo"  (ngModelChange)="cultivoChange()" class="input-form">
    <md-option *ngFor="let cultivo of cultivos" [value]="cultivo.idCultivo">{{cultivo.usoSigpac}} - {{cultivo.fruto}} - {{cultivo.variedad}}</md-option>
  </md-select>

**Comment by kara** [comment] 2016-12-28 02:41
Dupe of https://github.com/angular/material2/issues/2248.

**Closed by kara** 2016-12-28 02:41 UTC

**Comment by Eduard011** [comment] 2018-08-24 14:03
@Dgiulian 
Para que el evento (change)="onChange($event)" funcione debes de importar MdSelectChange 

import { MdSelectChange } from '@angular/material';

//Evento (change)
onChangeSelect(event: MdSelectChange) {
        console.log(event.value)
    }
