### ISSUE TITLE
Expansion panel + Sidenav + Router Active Not working

### ISSUE THREAD

**Issue by keatkeat87** [angular/material2#14200] opened 2018-11-19 13:56 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
when page load, the routerLinkActive.isActive should let expand-panel open.

#### What is the current behavior?
expand-panel not open.

#### What are the steps to reproduce?
i m sorry, i try StackBlitz import from github, but run into error. please git clone
https://github.com/keatkeat87/angular-material-expansion-panel-router-active-sidenav
the main code is in product.component.html

#### What is the use-case or motivation for changing an existing behavior?
this is a common control panel ui request.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.0.4
Material 7.0.4
Typescript 3.1.6
Windows 10
Chrome 70

#### Is there anything else we should know?
if i remove the sidenav, only expand panel + router active, it work perfect.

**Comment by josephperrott** [comment] 2018-11-20 18:18
Closing as duplicate of #13870

**Closed by josephperrott** 2018-11-20 18:18 UTC
