### ISSUE TITLE
matTextareaAutosize causes error in Universal

### ISSUE THREAD

**Issue by dottodot** [angular/material2#10497] opened 2018-03-20 14:55 UTC
The following `matTextareaAutosize` setup causes an error in Universal

```
        <mat-form-field>
            <textarea matInput formControlName="message" placeholder="Enter your message" matTextareaAutosize matAutosizeMinRows="3"
                matAutosizeMaxRows="10"></textarea>
        </mat-form-field>
```
error is 
```
TypeError: Invalid event target
    at Function.FromEventObservable.setupSubscription (/server.js:258536:19)
    at FromEventObservable._subscribe (/server.js:258558:29)
    at FromEventObservable.Observable._trySubscribe (/server.js:24479:25)
    at FromEventObservable.Observable.subscribe (/server.js:24467:93)
    at AuditOperator.call (/server.js:176277:23)
    at Observable.subscribe (/server.js:24464:22)
    at TakeUntilOperator.call (/server.js:58513:23)
    at Observable.subscribe (/server.js:24464:22)
    at /server.js:154913:26
    at ZoneDelegate.invoke (/server.js:222468:26
```

**Comment by crisbeto** [comment] 2018-03-20 18:01
The error looks like it's [coming from here](https://github.com/angular/material2/blob/master/src/cdk/text-field/autosize.ts#L90), however we already have a check around it and I wasn't able to reproduce it locally. What version of Material and Angular are you running?

**Comment by dottodot** [comment] 2018-03-20 18:03
Here's my current versions

```
Angular CLI: 1.7.3
Node: 8.9.4
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular/material-moment-adapter: 5.2.4
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack-bundle-analyzer: 2.10.0
webpack: 3.11.0
```

**Comment by dottodot** [comment] 2018-03-20 18:18
Ok I found it. I had the following in my webpack config. Can't remember why I added it now, maybe it was to fix an issue prior to material being fully universal ready

```
  module: {
    rules: [
      {
        test: /@angular(\\|\/)material/,
        use:
          "imports-loader?window=>global,CSS=>null,navigator=>{get userAgent(){return Zone.current.get('req')['headers']['user-agent'];}}"
      }
    ]
  },
```

**Comment by crisbeto** [comment] 2018-03-20 18:20
Thanks, closing as a non-issue.

**Closed by crisbeto** 2018-03-20 18:20 UTC
