### ISSUE TITLE
IE11: matInput does not get focused when clicking on mat-form-field

### ISSUE THREAD

**Issue by philipooo** [angular/material2#15792] opened 2019-04-11 13:23 UTC
#### What is the expected behavior?
The focus ist set to the matInput Field when clicking on some part of the mat-form-field which is not the <input> element.

#### What is the current behavior?
Currently there is some wierd behaviour. When clicking e.g. slightly abouve the <input> element on the mat-form-field, the placeholde moves and i looks like the field is focues but there is no carret... sometimes the carret appears at the correct or wrong location but I cant type anything.

#### What are the steps to reproduce?

**With bug**

1. Open IE11 with https://angular-material2-issue-fsayjw.stackblitz.io (https://stackblitz.com/edit/angular-material2-issue-zteuux)
2. Click slighly above the placeholder
3. => No focus

**Without bug**
There is an working example using an **older version** of angular/angular-material
https://angular-material2-issue-fsayjw.stackblitz.io/ (https://stackblitz.com/edit/angular-material2-issue-fsayjw)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
See stackblitz

**Comment by macjohnny** [comment] 2019-04-12 05:25
duplicate of https://github.com/angular/material2/issues/15093

**Closed** 2019-04-12 07:30 UTC
