### ISSUE TITLE
Expansion Panel descriptions align horizontally

### ISSUE THREAD

**Issue by gatimus** [angular/material2#10024] opened 2018-02-19 18:01 UTC
#### Bug, feature request, or proposal:
feature request (could be a bug, the material guide lines show the descriptions aligned horizontally but don't explicitly say )

#### What is the expected behavior?
Expansion Panel descriptions align horizontally.

#### What is the current behavior?
Different title lengths push descriptions.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-4u1yaz

#### What is the use-case or motivation for changing an existing behavior?
To look like https://material.io/guidelines/components/expansion-panels.html#expansion-panels-usage

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all

#### Is there anything else we should know?
The following fixes:

    .mat-expansion-panel-header-description, .mat-expansion-panel-header-title {
      flex-basis: 0;
    }

**Comment by julianobrasil** [comment] 2018-02-20 14:23
Dupe: #5173

**Comment by josephperrott** [comment] 2018-02-20 15:23
Closing as duplicate of #5173

**Closed by josephperrott** 2018-02-20 15:23 UTC
