### ISSUE TITLE
Angular material Editing Inline Datatables

### ISSUE THREAD

**Issue by victorsolaya** [angular/material2#6015] opened 2017-07-25 06:33 UTC
#### Bug, feature request, or proposal:

Proposal

#### What is the expected behavior?

Allows edit angular2 datatables

#### What are the steps to reproduce?

Allows to edit fields in a datatable

**Comment by m98** [comment] 2017-07-25 07:32
Could you please clarify what do you mean from Angular 2 datatables? 
Do you mean Material tables?

**Comment by victorsolaya** [comment] 2017-07-25 07:34
Of course.

I mean this datatables 
https://material.angular.io/components/table/overview

I would like to edit the data inside the table

**Comment by rodaz** [comment] 2017-07-25 07:59
duplicate of #5982

**Closed** 2017-07-25 17:12 UTC
