### ISSUE TITLE
autocomplete: panel does not reposition on page scroll

### ISSUE THREAD

**Issue by axtho** [angular/material2#7897] opened 2017-10-19 07:18 UTC
#### Bug, feature request, or proposal:
Bug?

#### What is the expected behavior?
The overlay panel of autocomplete should reposition on mat-sidenav-container scolling underneath

#### What is the current behavior?
The panel stays put on it original position. Consider this code:

```HTML
<form class="person-form"
      #personEditForm="ngForm"
      [formGroup]="form"
      (ngSubmit)="save(form.value)"
      (keyup)="onKey($event)"
      novalidate>

    <fieldset fxFlex="100">
        <legend i18n>Status &amp; Tags</legend>
        <mh-tags [source]="tagSource"
                 formControlName="status"
                 placeholder="Status"></mh-tags>
    </fieldset>
...
```
The component (**mh-tags**) HTML looks like this:
```HTML
<mat-form-field floatPlaceholder="always">
  <mat-chip-list #chipList>
    <mat-icon matPrefix>label_outline</mat-icon>
    <mat-chip *ngFor="let tag of _value" (remove)="remove(tag)">
      {{tag.text}} <mat-icon matChipRemove>cancel</mat-icon>
    </mat-chip>
    <input [matChipInputFor]="chipList"
           [matChipInputAddOnBlur]="false"
           (matChipInputTokenEnd)="addNew($event)"
           [matAutocomplete]="auto"
           placeholder="{{placeholder}}"
           #chipInput>
  </mat-chip-list>
  <mat-autocomplete #auto="matAutocomplete" [displayWith]="displayFn" (optionSelected)="add($event)">
    <mat-option *ngFor="let tag of sourceFiltered()" [value]="tag">
      <span>{{ tag.text }}</span>
    </mat-option>
  </mat-autocomplete>
</mat-form-field>
```

Here is [the layout for it](https://github.com/digitaldeacon/memberhive2/blob/master/web/src/app/viewport/view.component.html).

**EDIT**
Produces this:
<img width="846" alt="bildschirmfoto 2017-10-19 um 08 57 15" src="https://user-images.githubusercontent.com/11181579/31766759-d8b75798-b4c8-11e7-9c43-2e1c6b17a43e.png">

#### What are the steps to reproduce?
Could not reproduce on stackblitz because mat-sidenav-container seems not to be part of beta.12.
I am using the nightly builds.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.4.4
Typescript: 2.5.3
Material/cdk: nightlies
cli: 1.5.0-rc.1

#### Is there anything else we should know?
I know there has been a few issues (https://github.com/angular/material2/issues/4557, https://github.com/angular/material2/issues/5797, https://github.com/angular/material2/issues/4093) on this already, plus a couple of PRs (https://github.com/angular/material2/pull/4293, https://github.com/angular/material2/pull/4500, https://github.com/angular/material2/pull/4855, https://github.com/angular/material2/pull/5134) that must have fixed this.

However, in my case it sill remains. May it is because of the way the sticky sidenav works now?

I have tried to apply the `cdkScrollable` directive to almost every parent element of the autocomplete. No cigar.

**Comment by jbw91** [comment] 2018-01-16 20:53
Any update on this? I have this issue as well, opening it attaches correctly to the element, but when I scroll down it doesn't reposition, it simply stays at the same position on the page. I can't use the autocomplete for what I need without this working properly.

**Comment by lucacicala** [comment] 2018-04-16 08:46
Having the same problem using

"@angular/material": "^5.2.4",

any update on this?

**Comment by axtho** [comment] 2018-04-16 08:49
No, in fact it has not been touched since the issue was opened. Maybe @crisbeto can give us a little info on the way ahead. It is quite annoying.

**Comment by flannanbrody** [comment] 2018-04-17 00:58
I'm having the same issue....but doesn't make sense that on the examples page it works fine 
https://material.angular.io/components/autocomplete/overview

example...https://stackblitz.com/edit/angular-hifphm?file=app/autocomplete-auto-active-first-option-example.html

**Comment by flannanbrody** [comment] 2018-04-17 15:04
Is there any know workarounds?

**Comment by sarthair** [comment] 2018-04-18 06:48
I am having the same issue with this. Have not found any workarounds to this.

**Comment by vjpc** [comment] 2018-06-14 13:11
Any updates on this. Do we have any fix for it.

**Comment by noggin182** [comment] 2018-07-02 17:22
The example page works fine, however if you open it in  stackblitz and wrap it in a scrollable div you can see the same problem: https://stackblitz.com/edit/angular-sc6bfp

**Comment by ferakiii** [comment] 2018-07-09 03:15
I've got the exact same problem @noggin182, did you find a workaround?

**Comment by bastienlemaitre** [comment] 2018-07-19 07:30
Any news ?

**Comment by GiovanyR** [comment] 2018-07-30 22:05
any update on this issue?

**Comment by IlyaSolovyov** [comment] 2018-07-31 12:04
Looking forward to a workaround, at the very least.

**Comment by crisbeto** [comment] 2018-07-31 18:41
The autocomplete (and all other overlay-based components) will only react to scrolling on the `body`/`html` elements, because doing so on absolutely all other elements would be terrible for performance. If your content is inside a different scrollable container, you can add the `cdkScrollable` attribute to let the CDK know that it should reposition when that element is scrolled.

**Comment by crisbeto** [comment] 2018-08-10 19:00
Closing this issue since the autocomplete is working as expected.

**Closed by crisbeto** 2018-08-10 19:00 UTC
Labels: P3

**Comment by kkblues** [comment] 2018-11-14 13:57
https://stackblitz.com/edit/angular-sc6bfp-ft5zvw?file=app%2Fautocomplete-overview-example.html

The issue is still there if you want bigger mat-option content.For example if we set the map-option height style , for example style="height:97px" by navigating with down arrow key the scrolling doesnt work properly

**Comment by Natanael1234** [comment] 2018-12-09 20:32
Still happening in 5.2.5.
