### ISSUE TITLE
Form Controls Alignment Issue

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#5868] opened 2017-07-19 11:14 UTC
#### Bug, feature request, or proposal:
Using multiple form controls in a form causes alignment issue. For example If we put a select under an input it moves the placeholder of select too close to the input.

Similarly, if we put input and select list side by side the underline of the fields is not aligned properly. The underline of select is shown few pixels above the input field underline bar.

Similar issue has been reported in this comment as well:

https://github.com/angular/material2/issues/118#issuecomment-270218055

#### What is the expected behavior?
Since the input is placed inside md-input-container, it seems it requires some adjustment for the select list.

#### What is the current behavior?
Alignment of the form controls should be same for all form controls whether the controls are placed vertically or horizontally.

Please also add two example forms to docs, containing all of the available form items, showing controls usage in horizontal as well as vertical forms.

**Comment by donroyco** [comment] 2017-07-19 18:39
Have you checked/tracked #2124

**Comment by naveedahmed1** [comment] 2017-07-19 19:15
@donroyco thanks for pointing out. It seems I missed it.

**Comment by kara** [comment] 2017-07-20 22:53
Yeah, this is a dupe of #2124.

**Closed by kara** 2017-07-20 22:53 UTC
