### ISSUE TITLE
Fix header position in table

### ISSUE THREAD

**Issue by lutchit** [angular/material2#6601] opened 2017-08-23 11:48 UTC
#### Bug, feature request, or proposal:
Request

#### What is the expected behavior?
Be able to scroll into a table without losing header display view.

#### What is the current behavior?
When you scroll into a table, the header is not fix, it's scrolling with the table.

#### What is the use-case or motivation for changing an existing behavior?
Improve a best visibility of data in the table when there a lot of rows and columns.

**Comment by donroyco** [comment] 2017-08-23 11:55
Duplicate of #5885

**Closed** 2017-08-23 12:14 UTC
