### ISSUE TITLE
mat-select not resetting filtered list when options unchecked

### ISSUE THREAD

**Issue by robphoenix** [angular/material2#13833] opened 2018-10-26 20:24 UTC
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

I am filtering an array based on the selected options in a multiple `mat-select`. The filtering works fine, except when I deselect the selected options. I would expect the Array to return to it's original state. This is what happens when I have an input form field and use it's value as a search term to filter the array.

#### What is the current behavior?

When selecting an option the array is filtered based on that option, when deselecting the option the entire array is empty and so nothing is rendered. This occurs whether using a pipe or a method with `selectionChange`.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-yehvm6
	

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 6, TypeScript 3

**Comment by josephperrott** [comment] 2018-10-26 21:01
Closing as this is working as expected.  When you deselect all of the values, the event that is emitted is an empty array(`[]`) as intended/expected.


Your `filterPizzas` method sets `pizzas` to `[]` when an empty array is provided as the parameter.  When you deselect all of the options, `[]` is the value in the event and the `filterPizzas` method sets `pizzas` to `[]`.

**Closed by josephperrott** 2018-10-26 21:01 UTC

**Comment by robphoenix** [comment] 2018-10-29 08:19
Thanks @josephperrott I'm embarrassed to admit that my issue actually stemmed from a fundamental JS error, expecting `if (!selectedToppings) {}` to handle this case, where what I wanted to do was `if (!selectedToppings || selectedtoppings.length === 0) {}`. Sorry for blaming the library :roll_eyes: end of day friday frustration blues. Thanks again. :+1:
