### ISSUE TITLE
Menu button is focused after close sidenav

### ISSUE THREAD

**Issue by guoyunhe** [angular/material2#10233] opened 2018-03-02 09:16 UTC
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Menu button should not be focused if clicked a link to close sidenav

#### What is the current behavior?

Menu button is focused, with a dark background after closing sidenav

![screenshot_20180302_111727](https://user-images.githubusercontent.com/5836790/36891756-52a0a766-1e0b-11e8-842a-f93b4615fc20.png)

#### What are the steps to reproduce?

https://angular-xst9gx.stackblitz.io

This example is modified from sidenav responsive example. The only difference is that add a click listener to each nav link so they will close sidenav after clicking.

1. Click the menu icon button. Sidenav menu should open.
2. Click any link on sidenav menu. Sidenav menu should be closed.
3. Check the status of menu icon button. It is focused with a dark background. This isn't what I expected.

#### What is the use-case or motivation for changing an existing behavior?

On mobile devices, when sidenav is in "over" mode, users may want to close sidenav after they clicked a menu item. This is the same behavior as normal Android applications, like Gmail. But normal Android app will not focus menu button after closing sidenav.

**Comment by ZiruZanrgeiff** [comment] 2018-03-02 11:20
The same happens to me when I open and close a MatDialog.

**Comment by julianobrasil** [comment] 2018-03-02 15:12
I think this is the expected behavior. If so, you'll have to try to redirect the focus by yourself.

**Comment by tinayuangao** [comment] 2018-03-02 18:20
@mmalerba Is this the expected behavior?

**Comment by mmalerba** [comment] 2018-03-02 19:40
It is intentional that the sidenav button is focused, but since the sidenav was closed by clicking a link, the `FoucsOrigin` would ideally be set as `mouse` and we wouldn't see the focus indicator. However if the user pressed <kbd>enter</kbd> to trigger the link the `FocusOrigin` would be `keyboard` and the focus indicator would be shown.

@crisbeto and I had a long discussion about trying to apply the correct `FocusOrigin` in cases like these. I can't remember where we wound up, but the TL;DR was that doing the right thing automatically in every case was really hard.

**Comment by josephperrott** [comment] 2018-03-26 15:03
Closing as this is working as intended.

**Closed by josephperrott** 2018-03-26 15:03 UTC
