### ISSUE TITLE
<md-input> value does not update when databound model is set to null

### ISSUE THREAD

**Issue by RoxKilly** [angular/material2#473] opened 2016-05-19 14:07 UTC
Angular 2 rc.1
Angular 2 Material alpha 4
Firefox 46.0.1

**Template**
```html
<md-input [(ngModel)]="inputValue" ></md-input>
<button (click)="clearInput()">Clear</button>
```
**Component**
```ts
inputValue:string;

clearInput(){
  this.inputValue=null;
}
```
**To reproduce**
1.  Enter some text in the input
2.  Click the button
3.  Try to enter more text in the input

Once `inputValue` is nulled, the binding between `md-input` and the model breaks down.  From there, one of two things happen for me.  Either (1) the text from the input remains even after `clearInput()` is run, or (2) Trying to enter text after `clearInput()` throws an exception: `TypeError: e is null`

The problems disappear if `this.inputValue=null` is changed to `this.inputValue=""`

**Comment by jelbourn** [comment] 2016-05-19 15:44
I tried this on master (both Chrome and Firefox) and could not reproduce.
```html
<md-input placeholder="test" #foo [(ngModel)]="someModel"></md-input>
<button (click)="clearModel()">Set to null</button>
{{someModel}}
```
```ts
someModel: string;
clearModel() {
  this.someModel = null;
}
```

Either it's fixed on master or there's something else about your case that's missing in the example. If you can reproduce it in a plunker (or similar) we can take another look.

**Closed by jelbourn** 2016-05-19 15:44 UTC
