### ISSUE TITLE
[MatTooltip] UI issue in differenet browsers 

### ISSUE THREAD

**Issue by helenasilkina** [angular/material2#10623] opened 2018-03-29 15:10 UTC
Bug, feature request, or proposal:
Tooltip Text isn't align to left in Chrome browser

What is the expected behavior?
Tooltip Text should be left align for long unbreakable string

What is the current behavior?
Incorrect behavior in Chrome: https://prnt.sc/iy2seu
Correct behavior in Firefox:   https://prnt.sc/iy2wn6

Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/material 5.0 and 5.2

**Comment by josephperrott** [comment] 2018-03-29 16:02
Closing as this is something that is caused by the browser and not by the `MatToolip`.

A [reproduction](https://stackblitz.com/edit/typescript-bqc36v?file=index.html) with only html and a style attribute shows this occurring as well.

**Closed by josephperrott** 2018-03-29 16:02 UTC
