### ISSUE TITLE
Build using npm package.json script

### ISSUE THREAD

**Issue by shotleybuilder** [angular/material2#912] opened 2016-07-23 15:13 UTC
#### feature request:

I'd like to be able to build using npm.  In particular using node-sass.  But I keep running into a problem highlighted here: https://github.com/sass/node-sass/issues/1222 

Many of the project's .scss files include @import statements without the .css or .scss extension.

node-sass then complains "it's not clear which file to import ..."

#### What is the expected behavior?

I'd like to compile the .css at run time using @import statements in my main.scss file (the way I use ng2-material).

#### What is the use-case or motivation for changing an existing behavior?

I think there should be a way of building using npm.

The suggested method here https://www.angular-meteor.com/tutorials/socially/angular2/angular-material-and-custom-angular-auth-forms of individually importing .css files seems a bit clunky?

I raised an SO Q some time ago that's been viewed a few times now:
http://stackoverflow.com/questions/36666096/installing-angular2-material-using-package-json-and-npm

**Comment by Dona278** [comment] 2016-07-25 07:51
It's the same of #887

**Comment by jelbourn** [comment] 2016-07-25 16:35
Dupe of #887

**Closed by jelbourn** 2016-07-25 16:35 UTC
