### ISSUE TITLE
MdDialog does not respect custom size

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/material2#6636] opened 2017-08-25 11:46 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Dialog UI to fit custom size of the dialog.

#### What is the current behavior?
Dialog UI  does not fit to custom size of the dialog.

#### What are the steps to reproduce?

[simple modification of the official plunker](https://plnkr.co/edit/SsMnIYvsecrtqSYoUZmR?p=preview)
![dialog bug](https://user-images.githubusercontent.com/11920691/29712786-de0316c2-899b-11e7-94dd-d70988ba2b2c.PNG)

#### What is the use-case or motivation for changing an existing behavior?
bad user experience

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 5.0.0-beta.4
material 2.0.0-beta.8
Windows 10
Typescript 2.4.2
Chrome

**Comment by willshowell** [comment] 2017-08-25 12:25
Can you expand on what your expected behavior would be?

**Comment by GeorgeKnap** [comment] 2017-08-26 07:24
I would expect the dialog to fit to full size set by width & height.

**Comment by julianobrasil** [comment] 2017-08-26 10:17
@GeorgeKnap, the bottom-fixed actions part is being tracked via #4609.

**Comment by josephperrott** [comment] 2017-09-27 16:32
Closing as duplicate of #4609

**Closed by josephperrott** 2017-09-27 16:32 UTC
