### ISSUE TITLE
FormGroup.reset() does not reset validation

### ISSUE THREAD

**Issue by farley911** [angular/material2#9347] opened 2018-01-11 22:41 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`FormGroup.reset()` should reset the form validation

#### What is the current behavior?
`FormGroup.reset()` sets the form classes to `ng-pristine` and `ng-untoched` but `FormControl.hasError(...)` still returns truthy.

#### What are the steps to reproduce?
Plunker: http://embed.plnkr.co/Hlivn4/
- Create reactive form
- Add fields and set the validation to required
- Enter something into the fields
- Call FormGroup.reset() method

#### What is the use-case or motivation for changing an existing behavior?

`FormGroup.reset()` should reset the form to it's initial state including removing validation errors.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular ^5.0.0, Material 5.0.0

**Comment by willshowell** [comment] 2018-01-12 14:15
Please see https://github.com/angular/material2/issues/4190 and particularly https://github.com/angular/material2/issues/4190#issuecomment-311488176.

If you want to customize under which conditions `mat-error` is shown, consider implementing your own [`ErrorStateMatcher`](https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown).

**Comment by josephperrott** [comment] 2018-01-16 15:43
Closing as duplicate of #4190

**Closed by josephperrott** 2018-01-16 15:43 UTC
