### ISSUE TITLE
[Tooltip] Overlay gets cut off by left of screen

### ISSUE THREAD

**Issue by rvoltolini** [angular/material2#7126] opened 2017-09-16 14:19 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
if(left < 0); left = 0;

#### What is the current behavior?
Start of tooltip is overflowing the window.

![captura de tela de 2017-09-16 11-13-10](https://user-images.githubusercontent.com/30928235/30512920-299fabaa-9ad0-11e7-8567-53facd8ff4c8.png)

#### What are the steps to reproduce?
Use a tooltip in an icon on the left side of the page

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/material": "^2.0.0-beta.10"

**Comment by julianobrasil** [comment] 2017-09-16 19:02
A plunk to show it: https://plnkr.co/edit/y8ytd61JRRLJZd0GMznY?p=preview

**Comment by crisbeto** [comment] 2017-12-19 20:37
Closing since this shouldn't be an issue anymore on master.

**Closed by crisbeto** 2017-12-19 20:37 UTC
Labels: P3: important

**Comment by benb7760** [comment] 2018-01-06 16:50
@crisbeto Not sure if the same issue, but I am still able to reproduce this problem in 5.0.3

https://angular-material2-issue-cqddwx.stackblitz.io

**Comment by julianobrasil** [comment] 2018-01-06 21:08
Yeap... it's still there: http://plnkr.co/edit/kw44zy?p=preview

![image](https://user-images.githubusercontent.com/25405143/34643973-f416022a-f314-11e7-8d11-7578cf0a9c40.png)

**Comment by crisbeto** [comment] 2018-01-07 11:22
That example doesn't work, because the trigger element is 100% wide, meaning that the tooltip can't fit on either side. The current positioning doesn't support pushing the element into the viewport if it doesn't fit, but once #9153 gets in, it'll be easy to do.
