### ISSUE TITLE
[Bug Report][Radio] Odd Behaviors Among Radio Group

### ISSUE THREAD

**Issue by Daeluse** [angular/material2#1205] opened 2016-09-08 15:41 UTC
#### Bug, feature request, or proposal:

Most Likely a Bug, Possible a Feature Request
#### What is the expected behavior?

In my current application, I have two radio selects which cannot be in the same md-radio-group since they are in separate cells of a table, however they still need to function as ngModel compliant. To do this I have built two md-radio-groups and set the name attribute on each of them, which produces the desired outcome except in one way. If the value dictating the data bound [ngModel] changes, the first change will be accepted, however further changes will not.
#### What is the current behavior?

See Plunker in Next Section

Currently, when the value which the [ngModel] is bound to changes, the first time it is changed after the page loads, the radio boxes will update as expected, however, any further changes have no effect on the radio box. If this behavior is due to the way I am utilizing md-radio-group, what would be the proper way to set this up?
#### What are the steps to reproduce?

Plunker - http://plnkr.co/edit/W1XjA5Ja1RbnXYtWbvEG?p=preview

The top row of radio buttons will change the value of the data bound [ngModel] for the bottom row of radio buttons. Upon clicking either of the buttons in the top row, you initially see that the wrong radio is checked on the bottom row. Clicking on the whitespace to trigger the onBlur event will properly select the desired radio button, however, clicking on either of the radio buttons in the top row further have no effect on the bottom row, even though the value of the [ngModel] is being updated.
#### What is the use-case or motivation for changing an existing behavior?

I have a table which has two columns of radio buttons, the table cannot have a default behavior selected, so the user must explicitly state what they want (Business Rules) which is why a single checkbox or slide-toggle cannot be used. I need to have two md-radio-groups which are linked together so that their child md-radio-buttons function as if they were in the same group.
#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2 RC5
Angular 2 Material 7-2a
Google Chrome 52.0.2743.116
Windows 10

**Comment by jelbourn** [comment] 2016-11-04 00:51
@tinayuangao I suspect this is the same underlying issue as #831

**Comment by tinayuangao** [comment] 2016-11-04 20:29
Cannot reproduce this issue in current master, while I can reproduce #831 .

Close this issue for now.

**Closed by tinayuangao** 2016-11-04 20:29 UTC
Labels: P3: important

**Comment by Daeluse** [comment] 2016-11-18 16:28
I'm still experiencing this issue at alpha.10 with angular 2.1.1, I've also created a new plunk which illustrates the bug in a different way if it helps.
http://embed.plnkr.co/Rd7zhws9kIUC223t5pyX/

**Comment by tinayuangao** [comment] 2016-11-18 21:36
This will be fixed at alpha.11
