### ISSUE TITLE
mdMenu : x-position & y-position not working

### ISSUE THREAD

**Issue by Robouste** [angular/material2#2611] opened 2017-01-12 14:47 UTC
#### Bug, feature request, or proposal:
Bug or missunderstanding of the doc ?

#### What is the expected behavior?
Set the position of the menu with y-position or x-position attribute

#### What is the current behavior?
None

#### What are the steps to reproduce?
[Plunkr](http://plnkr.co/edit/dOuo5k)

#### What is the use-case or motivation for changing an existing behavior?
This behavior should works

#### Which versions of Angular, Material, OS, browsers are affected?
Material 2.0.0-beta.1
Chrome 55.0.2883.87 m (64-bit)
Windows 10

**Comment by dirkjacobs** [comment] 2017-01-16 11:31
I have the same problem.
I would indeed expect the menu get rendered under the button (if mentioned y-position : below). This way, it would be possible to build a 'typical' menu with a button and a dropdown mark (triangle) and a menu expanding below when pressed

**Comment by bsteffl** [comment] 2017-01-26 19:46
The x and y positioning seem to be working correctly. `y-position: below` places your menu in the direction going down as a dropdown. `y-position="above"` makes the menu dropup. Likewise `x-position` aligns the menu left aligned (before) and right aligned (after). What seems to not be working is the `overlapTrigger` which determines if it will be positioned on top of your trigger button or not.

**Comment by kara** [comment] 2017-01-27 02:32
@Robouste I'm not clear on what you're expecting to happen from saying "it should work". When I open your plunker, it does work as intended in that the bulk of the menu panel is oriented below the trigger (rather than above).  "Below" is a measure of orientation, rather than a measure of "overlapping". If you are trying to get the panel to display below *and not overlap* the trigger, it sounds like you want the `overlapTrigger` property that will become available in our next release. As that is already implemented and in master, I'm closing the issue.

**Closed by kara** 2017-01-27 02:32 UTC
Labels: P3: important

**Comment by Robouste** [comment] 2017-01-27 08:16
@kara I thought that 'position-x : below' meant under the button but like you said, it's more a matter of orientation (maybe it would be a better choice to name it 'direction' or 'orientation').

Can't wait for the next release ! Thx

**Comment by miguelcaravantes** [comment] 2017-07-10 20:49
@Robouste  I agree with you position for orientation is very confuse

**Comment by kamok** [comment] 2018-01-16 15:38
I wish the `MenuPositionX` were clearer that they were strings of `before` and `after`

I read the docs, couldn't figure out what they were, and found this thread for it. Should be more clear.
