### ISSUE TITLE
Datatable with simple array

### ISSUE THREAD

**Issue by pantonis** [angular/material2#9385] opened 2018-01-14 11:32 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Use datatable with array

#### What is the current behavior?
Datatable is now being used with a datasource.

#### What are the steps to reproduce?
N/A

#### What is the use-case or motivation for changing an existing behavior?
 In a project where I have dozens of datatables I have to create dozens of datasources for each one of the tables. This is redundant and It is difficult to maintain. All other datatables out there they just work with a simply array binding

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5, Material 5

**Comment by CDDelta** [comment] 2018-01-14 12:29
Related to #5889

**Comment by crisbeto** [comment] 2018-01-14 13:55
Closing as a duplicate of #5889.

**Closed by crisbeto** 2018-01-14 13:55 UTC
