### ISSUE TITLE
Feature: md-error for md-select

### ISSUE THREAD

**Issue by mtpultz** [angular/material2#5500] opened 2017-07-04 22:17 UTC
#### Bug, feature request, or proposal:
Feature

#### What is the requested behavior?
If a select is invalid have the option to show a message

#### What is the current behavior?
If an validation error occurs no message is displayed

#### What is the use-case or motivation for changing an existing behavior?
I can understand why you might not have md-error initially since it is a select, but we're finding that there are use cases where being able to provide more information based on either a selection or lack of a selection indicating what this means would be very useful.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.5, Angular Material 2.0.0-beta.7, Windows 10

**Comment by willshowell** [comment] 2017-07-05 14:21
Dupe of https://github.com/angular/material2/issues/4673 and sort of https://github.com/angular/material2/issues/2498

**Comment by crisbeto** [comment] 2017-07-05 16:44
Closing as a duplicate.

**Closed by crisbeto** 2017-07-05 16:44 UTC

**Comment by blitzkrieg92** [comment] 2017-07-06 11:34
@crisbeto None of these duplicates #4673, #2498 contain a solution. Do we have any other ticket which shows how to achieve this ?

**Comment by crisbeto** [comment] 2017-07-06 11:45
It's not currently possible. Those issues are for tracking the implementation.

**Comment by finalxcode** [comment] 2017-08-18 08:35
@crisbeto when to achieve this?

**Comment by willshowell** [comment] 2017-08-18 12:29
@finalxcode it's coming soon. See https://github.com/angular/material2/pull/6488

**Comment by Cornevur** [comment] 2017-09-09 22:29
Have the same issue with md-error for md-select
