### ISSUE TITLE
Dialog doesn't open on another dialog in IE11 with Angular material beta 10

### ISSUE THREAD

**Issue by Jay588** [angular/material2#6898] opened 2017-09-07 02:48 UTC
#### Bug, feature request, or proposal

After updating to angular material beta 10 from beta 7,  dailog unable to trigger another dialog (doesn't open on another dialog) in IE11 and on the other side it is working on chrome as expected.

**Comment by crisbeto** [comment] 2017-09-07 07:46
Closing as a duplicate of https://github.com/angular/material2/issues/6719.

**Closed by crisbeto** 2017-09-07 07:46 UTC
