### ISSUE TITLE
Add optional 'jump to page' feature

### ISSUE THREAD

**Issue by mchl18** [angular/material2#9008] opened 2017-12-15 13:36 UTC
#### Bug, feature request, or proposal:

feature request

#### What is the expected behavior?

jump to certain page

#### What is the current behavior?

it is only possible to navigate one page at a time

#### What is the use-case or motivation for changing an existing behavior?

we are using the paginator for very long lists that are loaded dynamically and we have use cases with more than 700 pages containing lots of data being loaded. Having to click through every page to get e.g. to the last one is really time consuming

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

` "@angular/material": "5.0.0" `

**Comment by dushkostanoeski** [comment] 2017-12-15 13:48
Dupe of #7615

**Comment by josephperrott** [comment] 2017-12-15 15:20
Closing as duplicate of #7615

**Closed by josephperrott** 2017-12-15 15:20 UTC
