### ISSUE TITLE
Datatable Sort header showing T instead of arrow

### ISSUE THREAD

**Issue by isurendrasingh** [angular/material2#10817] opened 2018-04-12 08:09 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
To show arrow (upwards or downwords)

#### What is the current behavior?

![screenshot 14](https://user-images.githubusercontent.com/7621607/38664328-d53ef324-3e56-11e8-97eb-f6a289e16e4b.png)

**Comment by isurendrasingh** [comment] 2018-04-12 09:01
::ng-deep .mat-sort-header-arrow.ng-trigger.ng-trigger-arrowPosition {
    opacity: 0;
}

::ng-deep .mat-sort-header-pointer-left.ng-trigger.ng-trigger-leftPointer{
    transform: rotate(-45deg);
}
::ng-deep .mat-sort-header-pointer-right.ng-trigger.ng-trigger-rightPointer{
    transform: rotate(45deg);
}

**Comment by WizardPC** [comment] 2018-04-12 15:59
Link to #8396 ? @andrewseguin

**Comment by tinayuangao** [comment] 2018-04-12 23:44
I think this is a duplicate of #9758.

**Closed by tinayuangao** 2018-04-12 23:44 UTC
