### ISSUE TITLE
[mat-menu] floats outside window

### ISSUE THREAD

**Issue by vegarda** [angular/material2#9946] opened 2018-02-14 11:39 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-menu to be contained below top and above bottom

#### What is the current behavior?
mat-menu expands up outside window

#### What are the steps to reproduce?
[https://material.angular.io/components/menu/overview](https://material.angular.io/components/menu/overview)
Adjust window until menu floats outside window

#### What is the use-case or motivation for changing an existing behavior?
Menu items become unreachable

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.5
Material 5.2.1

#### Is there anything else we should know?
Example below where mouse is howering on top element
![Image example: https://i.imgur.com/g6seQpv.png](https://i.imgur.com/g6seQpv.png)

**Comment by julianobrasil** [comment] 2018-02-14 16:49
I think this other issue has the same root cause: https://github.com/angular/material2/issues/6965

If so, have a look over there, speciffically from https://github.com/angular/material2/issues/6965#issuecomment-339479909

**Comment by josephperrott** [comment] 2018-02-15 22:51
Closing as duplicate of #6965

**Closed by josephperrott** 2018-02-15 22:51 UTC
