### ISSUE TITLE
Ability to change snackbar location on screen

### ISSUE THREAD

**Issue by ukrukarg** [angular/material2#4103] opened 2017-04-14 21:32 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
I should be able to specify the location of the snackbar (eg. I want it to show up on the right-top side of the screen instead of bottom).

#### What is the current behavior?
Snack bar can only be shown at the very bottom of the screen.

#### What is the use-case or motivation for changing an existing behavior?
Users should not be restricted over where snack bar shows up.

**Comment by josephperrott** [comment] 2017-04-15 21:19
Closing as a duplicate of #3577

**Closed by josephperrott** 2017-04-15 21:19 UTC
Labels: feature, P3: important
