### ISSUE TITLE
mdSelect missing padding

### ISSUE THREAD

**Issue by robindijkhof** [angular/material2#4835] opened 2017-05-26 22:43 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Properly display mdSelect label when a value is selected

#### What is the current behavior?
Missing padding, causing the label to fall off

#### What are the steps to reproduce?
https://plnkr.co/edit/GPyk6vzdQKfMUtKrmJ5i?p=preview select a value

#### What is the use-case or motivation for changing an existing behavior?
The label falling off

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.1.3
2.0.0-beta.6
windows 10
Typescript 2.3.2
Chrome 58

**Comment by donroyco** [comment] 2017-05-29 11:15
I think it's intentional, because it expects to be inside of a `md-card` and `md-card-content`, which has the needed padding.

**Comment by robindijkhof** [comment] 2017-05-29 11:56
I don't think so. Putting it in a form looks terrible. Also, two of them after earchother result in overlapping:
https://plnkr.co/edit/uE4w4wBCRJfgpXK9Wvep?p=preview

**Comment by donroyco** [comment] 2017-05-29 13:07
It's being tracked in #4755

**Comment by mmalerba** [comment] 2017-05-30 23:51
Closing as dupe of #2124

**Closed by mmalerba** 2017-05-30 23:51 UTC
