### ISSUE TITLE
Menu opens in wrong position in rtl mode

### ISSUE THREAD

**Issue by mrdimaan** [angular/material2#11543] opened 2018-05-28 11:22 UTC
#### Bug, feature request, or proposal:
Menu does not open in right position

#### What is the expected behavior?
menu should open where the trigger is clicked

#### What is the current behavior?
it will open far from the trigger button always sticking to left side of screen

#### What are the steps to reproduce?
any project in rtl direction

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
this happened after upgrading to angular 6

**Comment by crisbeto** [comment] 2018-05-28 14:21
It's hard to tell based on the description, but assuming it's a duplicate of https://github.com/angular/material2/issues/11387.

**Closed by crisbeto** 2018-05-28 14:21 UTC
