### ISSUE TITLE
Bug | Material Tabs animation doesn't work well with dir="rtl"

### ISSUE THREAD

**Issue by netanelm54** [angular/material2#10571] opened 2018-03-26 13:13 UTC
#### The Broblen
When the direction of 'mat-tab-group' or container div changed to "rtl" the animation of sliding tabs doesn't work well. work only in "ltr"

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "5.2.0"

#### Is there anything else we should know?
On the previous version (When it was 'md-tab-group') it's work well.

**Comment by crisbeto** [comment] 2018-03-26 18:57
Closing as a duplicate of https://github.com/angular/material2/issues/9465.

**Closed by crisbeto** 2018-03-26 18:57 UTC
