### ISSUE TITLE
md-menu wrong position

### ISSUE THREAD

**Issue by dreday966** [angular/material2#1116] opened 2016-08-25 07:04 UTC
#### Bug, feature request, or proposal:
md-menu wrong position

#### What is the expected behavior?
md-menu postion on button

#### What is the current behavior?
md-menu showing on the bottom of page

![2016-08-25 14-49-36](https://cloud.githubusercontent.com/assets/9654172/17959792/23c9b1f2-6ad5-11e6-812c-93ece510d29b.png)

**Comment by dreday966** [comment] 2016-08-25 07:05
when i click the button,the menu appear on bottom...

**Comment by bonaparte89** [comment] 2016-08-25 10:15
same issue here...

**Comment by jmcgoldrick** [comment] 2016-08-25 11:48
Hey all, check out the getting_started file, you'll be missing this, specifically this:

> For alpha.7, you need to include the overlay styles in your app via a link element. This will look something like:

`<link href="vendor/@angular2-material/core/overlay/overlay.css" rel="stylesheet">`

> In future releases, all of the core styles will be combined into a single distributed css file.

**Comment by theunreal** [comment] 2016-08-26 10:04
Same problem. @jmcgoldrick, it has nothing to do with this css file. 

Reported already at https://github.com/angular/material2/issues/1085

**Comment by jelbourn** [comment] 2016-08-31 01:10
Closing this into #1139

@theunreal if you can reproduce this in a setup that has the core styles loaded can you file a separate issue for this? AFAIK, this issue has been caused by missing the core styles.

**Closed by jelbourn** 2016-08-31 01:10 UTC

**Comment by theunreal** [comment] 2016-08-31 06:42
Hey @jelbourn, There is already a plunker for this in https://github.com/angular/material2/issues/1085#issuecomment-242399239. This is not about the core styles.

https://plnkr.co/edit/yuPzIJ?p=preview

The core styles are imported but the tooltip appears in a wrong position. same for menus.

**Comment by jelbourn** [comment] 2016-08-31 15:37
@theunreal the missing styles is still the issue; the problem is that the overlay styles weren't included in `core.css` (which was wrong), so you also need `overlay.css` until it's fixed:
https://plnkr.co/edit/fXznny6aMl5cvajDDuOM?p=preview

**Comment by theunreal** [comment] 2016-08-31 15:46
@jelbourn Well the plunker wasn't RTL as my issue
https://plnkr.co/edit/5dJE21K2rqMHQupaAm3C?p=preview

In RTL the positioning is all wrong, with or without the styles. I can't even see the tooltip/menu

**Comment by dreday966** [comment] 2016-09-01 03:01
add css resolve the issue👌
