### ISSUE TITLE
mat-slider: second thumb

### ISSUE THREAD

**Issue by IliaVolk** [angular/material2#10333] opened 2018-03-08 23:19 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Allow to have 2 (at least) or more thumbs [(even jQuery has it)](http://jqueryui.com/slider/#range)
Client should allow or not them to intersect, choose directions of 'track' (`.mat-slider-track-wrapper`)
Each thumb should have as more as possible separated API properties, like `disabled`, `value`, `input`, `change`,  `NG_VALUE_ACCESSOR`, `invert`, `min`, `max`.

#### What is the current behavior?

Only one thumb is allowed.

#### What is the use-case or motivation for changing an existing behavior?
Allow user to select interval range. 
Allow adding disabled thumbs (my designer drew them).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

<=6.0.0-beta.4

#### Is there anything else we should know?
Maybe smth like this? (super customizable)
```
<mat-slider>
    <mat-slider-thumb-group formControlName="name" *ngIf="valueBetweenThumbs; else valuesAroundThumbsTemplate">
        <mat-slider-thumb max="10"></mat-slider-thumb>
        <mat-slider-thumb></mat-slider-thumb>
    </mat-slider-thumb-group>
    <ng-template #valuesAroundThumbsTemplate>
        <mat-slider-thumb formControlName="other"></mat-slider-thumb>
        <mat-slider-thumb formControlName="moreOne" [invert]="true" min="50"></mat-slider-thumb>
        <mat-slider-thumb [disabled]="true" value="25"></mat-slider-thumb>
    </ng-template>
</mat-slider>
```
This will allow implementing custom thumb appearance and behavior too.

**Comment by jelbourn** [comment] 2018-03-09 00:44
Duplicate of #1331

**Closed by jelbourn** 2018-03-09 00:44 UTC
