### ISSUE TITLE
MatSelect with visible MatIcon after select

### ISSUE THREAD

**Issue by launcelot66** [angular/material2#15030] opened 2019-01-31 09:01 UTC
#### What is the expected behavior?
After select item from MatSelect display mat icon

#### What is the current behavior?
After select item from MatSelect i saw material icon name (text)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-t52yj2

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
    "@angular/animations": "~7.0.0",
    "@angular/cdk": "^7.0.0",
    "@angular/material": "^7.0.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/forms": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
    "core-js": "^2.5.4",
    "rxjs": "^6.3.3",
    "zone.js": "^0.8.26"
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.2",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1"
```

#### Is there anything else we should know?
try to do that without using formGroup and still have same problem

**Comment by macjohnny** [comment] 2019-01-31 12:48
this also happens without a custom `mat-select-trigger` element, e.g.
```html
<mat-form-field>
    <mat-select placeholder="Label">
      <mat-option value="bla">
        <mat-icon>brightness_1</mat-icon> bla
      </mat-option>
    </mat-select>
</mat-form-field>
```
![image](https://user-images.githubusercontent.com/5589029/52055136-d6a80580-255e-11e9-886d-77724150f50d.png)

See https://stackblitz.com/edit/angular-fwamza?file=src/app/app.component.html

**Comment by macjohnny** [comment] 2019-01-31 13:00
your `<mat-select-trigger *ngIf="label">` is never true, since `label` is not a controller property.
Instead, you need to get the currently selected label and use it as follows
```html
<mat-select placeholder="Label" formControlName="label">
      <mat-select-trigger *ngIf="getSelectedLabel() as selectedLabel">
        <mat-icon [ngStyle]="{'color': selectedLabel.color}">brightness_1</mat-icon>&nbsp;{{selectedLabel.name}}
      </mat-select-trigger>
    ...
  <mat-select>
```
Result:

![image](https://user-images.githubusercontent.com/5589029/52055667-52568200-2560-11e9-9cfe-7fb200eb0614.png)

See https://stackblitz.com/edit/angular-8jce6t?file=src/app/app.component.html

Since this is not a bug, this issue should be closed.

**Comment by crisbeto** [comment] 2019-02-02 11:03
@macjohnny is correct. Closing since it works as expected.

**Closed by crisbeto** 2019-02-02 11:03 UTC
