### ISSUE TITLE
[mat-dialog]: Proposal to add type safety for dialog result value

### ISSUE THREAD

**Issue by reppners** [angular/material2#8834] opened 2017-12-06 09:00 UTC
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Type safety for MatDialog result values.

#### What is the current behavior?
No generic type in the signature of MatDialogRef to support typing the expected return value.
This makes dialog result handling error prone.

#### What is the use-case or motivation for changing an existing behavior?
Improve type safety by getting rid of `any` on dialog result values.

Introduce a second generic parameter on MatDialogRef<TComponent, TResult> that enables to be more specific on the type of the dialog result value.

**Comment by crisbeto** [comment] 2017-12-06 09:02
This is exactly what https://github.com/angular/material2/pull/8766 does. Closing as a duplicate of #8760.

**Closed by crisbeto** 2017-12-06 09:02 UTC

**Comment by reppners** [comment] 2017-12-06 09:04
Cool! Didn't find it when searching. Thx!
