### ISSUE TITLE
mdInput - Bug: Placeholder does not float on ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by mbellezi** [angular/material2#3610] opened 2017-03-15 01:48 UTC
#### Bug, feature request, or proposal:
Bug:
mdInput does not float the Placeholder when changes on a FormControl value associated with the input is done outside the main detection process of OnPush (on a @Input change or event inside the component). Without the ChangeDetectionStrategy.OnPush, it works as expected.

#### What is the expected behavior?
mdInput should update the Placeholder float class of the control on a FormControl value change.

#### What is the current behavior?
It does not update the floating state of the Placeholder.

#### What are the steps to reproduce?

Plunker template: https://plnkr.co/edit/cnjdIETvMgcffUZqfpbg?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.9, Material 2.0.0-beta.2, Chrome 56, MacOS

**Comment by fxck** [comment] 2017-03-15 06:00
dupe of https://github.com/angular/material2/issues/3005

**Closed** 2017-03-15 12:28 UTC
