### ISSUE TITLE
bug(md-tooltip): maximum call stack exceeded when tooltip-position is not "below" - RC6

### ISSUE THREAD

**Issue by ivoviz** [angular/material2#1157] opened 2016-09-01 22:35 UTC
Angular @ 2.0.0-rc.6
Material @ 2.0.0-alpha.7-12

When `tooltip-position` is set to something else than default (eg. `after`) the site completely breaks with `Maximum call stack size exceeded` exception.

Since there is no base plunker with these versions I won't be posting one. The error is easily reproducible though: change https://github.com/angular/material2/blob/master/src/demo-app/tooltip/tooltip-demo.ts#L12 from `below` to `after` and run the demo app.

Edit: Haven't really looked at the code in depth, but it seems like [this](https://github.com/angular/material2/blob/master/src/lib/tooltip/tooltip.ts#L42) line causes the error. It creates multiple `overlayRef` for a single tooltip. Removing it makes the component work perfectly. Although it didn't throw before rc.6, it still created way too many `overlayRef`.

**Comment by thegnuu** [comment] 2016-09-11 15:11
I have the same error with v2.0.0-alpha.8-1

**Comment by rbaumi** [comment] 2016-09-13 08:41
Same here... before RC.6 everything worked fine. For me default "below" value also throws an error, but in this case the element that the tooltip is set to is shown. Stacktrace:

```
ORIGINAL EXCEPTION: Maximum call stack size exceeded
ErrorHandler.handleError @ core.umd.js:5997
next @ core.umd.js:9458
schedulerFn @ core.umd.js:8705
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ core.umd.js:8697
onError @ core.umd.js:8922
onHandleError @ core.umd.js:8793
ZoneDelegate.handleError @ zone.js:196
Zone.runTask @ zone.js:128
ZoneTask.invoke @ zone.js:293
core.umd.js:6000 
```

All angular2-material modules I have in version 2.0.0-alpha.8-1 and import them as shown in your [all.ts](https://github.com/angular/material2/blob/master/src/lib/all/all.ts) file (without the dialog module that is not yet published to npm).

**Comment by ocarreterom** [comment] 2016-09-14 14:48
Angular @ 2.0.0-rc.7
Material @ 2.0.0-alpha.8-1

Same problem.

**Comment by rbaumi** [comment] 2016-09-15 07:37
Updated ng2 to 2.0 final release, material still at 2.0.0-alpha.8-1.

Same problem.

**Comment by Kosmonaft** [comment] 2016-09-29 06:39
Angular @ 2.0.0
Material @ 2.0.0-alpha.7-4

Same Problem

**Comment by jmurphzyo** [comment] 2016-09-30 14:27
Whatever position is set as the default works. If I manually change the predefined position inside the tooltip.js file that position will work and all of the others fail.

**Comment by bfwg** [comment] 2016-10-04 05:49
Angular @ 2.0.0-rc.5
Material @ 2.0.0-alpha.8-2

Same Problem

**Comment by Ionaru** [comment] 2016-10-05 11:40
Issue still present in

Angular @ 2.0.1
Material @ 2.0.0-alpha.9-3

**Comment by alexlacasa86** [comment] 2016-10-17 12:19
Hi guys,

I am having this issue only when I try to load the page that contains the component via URL. If I navigate to that page from any other page (via routing) it works perfectly. As I'm using _ng2-translate_ to display text in it, it is clear to me that this is related with the async text... Whenever the text is already loaded, it works perfectly.

Not sure if this is redundant... I hope it is any useful.

**Comment by alexlacasa86** [comment] 2016-10-17 12:44
Hi guys,

I made a workaround that consist in adding a `*ngIf` to the tooltip with a boolean subscribed to the async text (the translate service in my case), so I change the bool value to true whenever the async text has been initialized.

`
// HTML FILE
...
 <i class="material-icons" *ngIf="translationLoaded" md-tooltip="{{ infoMessage | translate }}">help_outline</i>
...

// TS FILE
...
ngOnInit() {
  this.translate.get(this.infoMessage).subscribe(data => {
    this.translationLoaded = true;
  });
}
...
`

**Comment by Miiekeee** [comment] 2016-10-24 08:40
Got the same thing :)

**Comment by jelbourn** [comment] 2016-11-04 00:28
@andrewseguin can you confirm that this issue is fixed on master?

**Comment by andrewseguin** [comment] 2016-11-09 19:45
Cannot reproduce the issue in master now that tooltip logic has been drastically changed. Looks like this issue was fixed.

**Closed** 2016-11-09 19:46 UTC
Labels: P2: required
