### ISSUE TITLE
MatSnackBarConfig.viewContainerRef is not honored

### ISSUE THREAD

**Issue by cl0udninja** [angular/material2#11038] opened 2018-04-26 22:23 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When `MatSnackBar.open` is called with a `MatSnackBarConfig` like
```
{
  ...
  viewContainerRef: myContainerRef
  ...
}
```
according to the documentation:
```
viewContainerRef: ViewContainerRef       The view container to place the overlay for the snack bar into.
```
it's overlay of the snackbar should be placed inside the provided container ref.

#### What is the current behavior?
It's attached directly to `<body>`

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-1jgbvq

#### What is the use-case or motivation for changing an existing behavior?
I want to show the snackbar inside of a container and not globally

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.2.9
Material: 5.2.5
OS: MacOS v10.13.3
TypeScript: 2.4.2
Browser: Chrome v65.0.3325.181

#### Is there anything else we should know?
Nope

**Comment by tmburnell** [comment] 2018-04-30 15:54
I was told when i brought this issue up that the option described is only to change the order of change detection ... not display. 
I have the following: https://stackblitz.com/edit/angular-material-tooltip-in-container-fbuspp?file=app%2Fapp.module.ts
where you can change the display of a snackbar

**Comment by cl0udninja** [comment] 2018-04-30 16:02
If that's the case the documentation should say so IMHO. But it states otherwise. Thank you for your example I'll be sure to check it out. I'd love to use the built in component over my custom one!

**Comment by tmburnell** [comment] 2018-04-30 16:51
#10679 
In my example if you did not have my could you would not be able to see the snack bar without the logic.  So mine allows you to still see it because I scope it to a div.

**Comment by cl0udninja** [comment] 2018-04-30 17:04
Ah I see your point.

**Comment by josephperrott** [comment] 2018-05-03 21:39
Closing as this is working as intended, the `ViewContainerRef` determines the snackbars placement in the angular logic tree, it does not have any bearing on its location in the DOM tree.

**Closed by josephperrott** 2018-05-03 21:39 UTC

**Comment by cl0udninja** [comment] 2018-05-03 21:43
@josephperrott  Can you at least update the ambiguous documentation? Because the documentation says the place in the logic tree, it says 'The view container to place the overlay for the snack bar into.' And that's totally not happening.

**Comment by michelcve** [comment] 2018-07-09 12:53
@josephperrott I would vote for a documentation change as well. Got fooled by the current documentation as well.
