### ISSUE TITLE
[mat-checkbox] Impossible to synchronize model with checkbox

### ISSUE THREAD

**Issue by vadjs** [angular/material2#14135] opened 2018-11-14 07:46 UTC
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
I expect to have actual model value in DOM when using checkox state modification.

#### What is the current behavior?
If you use `[checked]='value'` in checkbox and bind to `(change)` event any function that modifies `value` you will get different checkbox states in DOM and model.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-8dhrjd?file=app%2Fcheckbox-configurable-example.ts

#### What is the use-case or motivation for changing an existing behavior?
This case usable when you use confirm dialogs, like "Are you sure to want to ckeck this item?".

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all

**Comment by vadjs** [comment] 2018-11-16 08:14
I researched this bug deeper and updated stackblitz example. This case really looks like bug.

**Comment by josephperrott** [comment] 2018-11-26 21:42
From what I can tell this is working as expected.

To look at each case you provided:
- `[checked]`/`[ngModel]` will correctly set the initial state and reflect the state of whatever the `value` property value is.  However if the `value` property updates without a change (i.e `false` => `false`) it does not cause an update the UI because the checkbox component change detector is not triggered since the value did not actually change.  So for cases such as the UI and `value` property both showing false, when a click occurs, the UI updates, but the `value` property for the component, which is provided to the input is never updated to `true`.  So when the `makeValueFalse` method is called, it is updating from `false` to `false`.  In this case, by handling the input and output separately like this, it is up to you to ensure that the state your property (the model) matches the state of what the checkbox thinks the value is.
- `[(checked)]` ends of as equivalent to `[checked]` because there is no `checkedChange` event from the checkbox, so it will never be called.
- `[(ngModel)]` works as you expected because the input and output bindings on `ngModel` "automatically" ensure that the your property (the model) and the checkbox are in the same state.  Because you immediately (though asynchronously) set the value back to false, it appears as if this instance cannot set the value of the checkbox to true.

**Comment by josephperrott** [comment] 2019-01-14 16:05
Closing as no reproduction has been provided and we were not able to create one.

**Closed by josephperrott** 2019-01-14 16:05 UTC
Labels: cannot reproduce

**Comment by Amber711** [comment] 2019-06-20 00:27
encountering the same issue. 

like if you use [checked]='value' in checkbox and bind to (change) event, in the change event,  modifying the value that checked property is bound to, the DOM won't be synchronized with the model..

Any advice? 

Thanks!

**Comment by amorel** [comment] 2019-08-25 09:16
I had the case where I change the value only if I confirm with a dialog box. If I cancel, the checkbox remains checked while the value has not changed. So, the value no longer reflect the state of the check box now. The trick I found is to change the state twice.

Example:

> DOM => [checked]='value'

--------------------------

```
constructor(private changeDetectorRef: ChangeDetectorRef) { }

func() {
    this.value= true;
    this.changeDetectorRef.detectChanges();
    this.value= false;
    this.changeDetectorRef.detectChanges();
}
```
