### ISSUE TITLE
perf(MatSnackBar) resize event runs in the `ngZone`

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#13263] opened 2018-09-22 15:51 UTC
#### Bug:
Injecting the `MatSnackBar` service create an event which runs in the `ngZone`

#### What is the expected behavior?
This event should not run in the zone unless there are changes to reflect in the view.

#### What is the current behavior?
This event triggers many angular change detection cycles.

#### What are the steps to reproduce?
Inject the `MatSnackBar` service in a component. Listen to `ngDoCheck()` lifecycle hook.
https://stackblitz.com/edit/angular-5fs538?file=src/app/app.component.ts

#### What is the use-case or motivation for changing an existing behavior?
Performance matters.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
`@angular/material: 6.4.7`

**Comment by crisbeto** [comment] 2018-09-22 18:57
Closing as a duplicate of https://github.com/angular/material2/issues/12883.

**Closed by crisbeto** 2018-09-22 18:57 UTC
