### ISSUE TITLE
MdDialog documentation is incomplete

### ISSUE THREAD

**Issue by moui72** [angular/material2#3088] opened 2017-02-14 00:09 UTC
#### Bug, feature request, or proposal:
docs bug

#### What is the expected behavior?
a complete example

#### What is the current behavior?
[the example](https://material.angular.io/components/component/dialog) does not show the HTML for [the dialog itself](https://github.com/angular/material2/blob/master/src/examples/dialog-result/dialog-result-example-dialog.html) ... it took a moment to figure out that the buttons needed `(click)="dialogRef.close('Option 2')"` rather than just `click="close('Option 2')"` without that file being part of the example.

**Comment by andrewseguin** [comment] 2017-02-17 00:51
Duplicate of #2934

**Closed by andrewseguin** 2017-02-17 00:51 UTC
