### ISSUE TITLE
Ripples not being cleaned up in certain cases in Edge and IE

### ISSUE THREAD

**Issue by crisbeto** [angular/material2#1943] opened 2016-11-20 18:07 UTC
In certain cases (`md-menu` and `md-select` in particular) the ripples don't get removed and can start stacking up in Edge and IE (the `.md-ripple-foreground` is the element that sticks around). [I've tracked it down to this handler not being fired](https://github.com/angular/material2/blob/master/src/lib/core/ripple/ripple-renderer.ts#L144), although I'm not quite sure why it's happening. I've tried playing around with the timing and tweaking the CSS, but I didn't manage to get it to work. For reference:

![bug](https://cloud.githubusercontent.com/assets/4450522/20465007/fb01c8b8-af53-11e6-90f4-b89633ff583d.gif)

A potential solution can be to have a timeout that cleans it up after a while, but I'm not sure how we would handle the event data that is being passed to the callback. 

CC @jelbourn

**Comment by fxck** [comment] 2016-11-20 21:45
happens when you put checkbox inside as well

**Comment by crisbeto** [comment] 2016-11-21 16:32
What I _think_ is happening here is that the `transitionend` event isn't being fired, because the parent gets removed from the DOM before the transition has finished. [According to this discussion, that's according to the spec.](https://bugs.webkit.org/show_bug.cgi?id=51945)

**Comment by jelbourn** [comment] 2016-11-21 17:25
@tinayuangao is already working on a fix for this in #1915

**Comment by jelbourn** [comment] 2016-11-21 17:28
Dupe of #1818

**Closed by jelbourn** 2016-11-21 17:28 UTC
Labels: windows
