### ISSUE TITLE
Slidnav Documentation Problems

### ISSUE THREAD

**Issue by raminqaf** [angular/material2#5075] opened 2017-06-12 03:32 UTC
#### Bug, feature request, or proposal:
Hi, there is a bug in opening the slidenav documentation. You should take a look: https://material.angular.io/components/component/sidenav

**Comment by julianobrasil** [comment] 2017-06-12 10:10
It's being tracked here: https://github.com/angular/material2/issues/4969

**Comment by kara** [comment] 2017-06-14 23:30
Dupe of #4969

**Closed by kara** 2017-06-14 23:30 UTC
