### ISSUE TITLE
Select option should be able to display fully (with line break)

### ISSUE THREAD

**Issue by kblestarge** [angular/material2#9310] opened 2018-01-09 21:34 UTC
Feature request (or help with custom CSS)

#### What is the expected behavior?
I want the text in the option of the select to be able to break to the next line instead of being hidden with three dots at the end of a single line.

#### What is the current behavior?
A combination of `overflow: hidden;` and `text-overflow: ellipsis;` is preventing a really long option from being fully displayed. It is limited to one single line with three dots (`...`) at the end when it is too long.

#### What are the steps to reproduce?
http://plnkr.co/edit/1H1D9A?p=preview
click on the color select element to see the options box popup.

#### What is the use-case or motivation for changing an existing behavior?
When the option text is important to see in it's entirety, I want the user to be able to see it in it's entirety.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 1.6.0
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
@angular/cdk: 5.0.0-rc0
@angular/cli: 1.6.0
@angular/material: 5.0.0-rc0

**Comment by crisbeto** [comment] 2018-01-10 08:17
Closing as a dupe of https://github.com/angular/material2/issues/7211.

**Closed by crisbeto** 2018-01-10 08:17 UTC
Labels: discussion, feature
