### ISSUE TITLE
md-menu + md-icon uses two lines in Firefox

### ISSUE THREAD

**Issue by allanbond** [angular/material2#2453] opened 2016-12-28 23:38 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The md-icon is displayed on the same line as the button text

#### What is the current behavior?
The md-icon is shown on one line and the button text on another in Firefox (Chrome is OK)

#### What are the steps to reproduce?
Plunker template: http://plnkr.co/edit/eTi4iKWptRl154WnwgzT

#### What is the use-case or motivation for changing an existing behavior?
n/a

#### Which versions of Angular, Material, OS, browsers are affected?
Angular - 2.4.1
Material - latest (master), 2.0.0-beta.0
Browser - Firefox 50.1.0 (possibly other versions)

**Comment by dahaupt** [comment] 2016-12-29 00:10
Firefox doesn't support `display: flex` in a button. 
`Just put a div inside of your <button>, and make that div display:flex.`

This should solve your problem for Firefox temporary. 

http://stackoverflow.com/questions/24289251/flexbox-not-working-in-buttons-in-firefox

@kara Any ideas on this?

**Comment by jermowery** [comment] 2016-12-29 03:16
Duplicate of #2435

**Comment by DevVersion** [comment] 2016-12-29 03:44
@dahaupt Can you re-post your thoughts on the original issue?

**Closed** 2016-12-29 03:43 UTC

**Comment by dahaupt** [comment] 2016-12-29 04:07
@DevVersion Yeah for sure :)
