### ISSUE TITLE
[Table] dense layout for mat-table

### ISSUE THREAD

**Issue by bracco23** [angular/material2#7995] opened 2017-10-24 14:38 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Like for `mat-list`, a dense layout mode should be available to show tables with a modified row height and font size to show more packed information

#### What is the current behavior?
No such layout exist

#### What is the use-case or motivation for changing an existing behavior?
Table with a lot of rows and no particularly crowded cells might use it to show more rows in a single page.

**Comment by willshowell** [comment] 2017-10-24 15:06
This should be pretty easy by overriding a little css. Or making your own version from CdkTable. Otherwise, probably covered under https://github.com/angular/material2/issues/4597

**Comment by jelbourn** [comment] 2017-10-29 19:50
Duplicate of #4597

**Closed by jelbourn** 2017-10-29 19:50 UTC
