### ISSUE TITLE
Need a search in select component for multi-select/select

### ISSUE THREAD

**Issue by Ishangidwani** [angular/material2#14362] opened 2018-12-03 08:10 UTC
I need a search for multiselect and select where input search may work as api to get filtered result
 
Sorry not able to upload image due to corporate policies, here is the reference that i want for select

https://angular-ui.github.io/ui-select/demo-disable-search.html

**Comment by crisbeto** [comment] 2018-12-03 08:46
Duplicate of https://github.com/angular/material2/issues/2812.

**Closed by crisbeto** 2018-12-03 08:46 UTC
