### ISSUE TITLE
Bug can't bring mat table checkbox ripple to top.

### ISSUE THREAD

**Issue by tatsujb** [angular/material2#11646] opened 2018-06-04 12:57 UTC
#### Bug, feature request, or proposal:

bug

#### What is the expected behavior?

being able to show see the full checkbox ripple when the mat table line size has been reduced.

#### What is the current behavior?

If you reduce the line size the checkbox ripple will be cut off. 
using /deep/ + !important + parent position static + target position absolute or any other trick does not work. As soon as you see the full ripple that means your checkbox no longer moves when you scroll.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-1vg9gn-suw5ff?file=app%2Ftable-basic-example.ts

#### What is the use-case or motivation for changing an existing behavior?

having thinner lines.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular 6 
material 6
typescript 2.7.2
chrome
windows 10 pro

**Comment by andrewseguin** [comment] 2018-06-07 17:00
Duplicate of #9526

To fix, add this to your styles:
```css

.mat-checkbox {
  display: inline-flex;
  margin: 15px;
}
```

https://stackblitz.com/edit/angular-1vg9gn-skb3sl?file=app/table-basic-example.css

**Closed by andrewseguin** 2018-06-07 17:00 UTC
