### ISSUE TITLE
Radio buttons are not tab stops in Safari

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#417] opened 2016-05-10 23:10 UTC
Native radio-buttons are tab stops in Safari (given you have the option "Press Tab to highlight each item on a webpage" turned on). 

However, `MdRadioButton` is _not_ a tab stop on Safari, though it works fine in Chrome / Firefox/ IE.

**Comment by robertmesserle** [comment] 2016-05-13 20:08
@jelbourn This may be fixed by 10ac2be9807defcc806e0bdabf2147c463dfe0d0 since I changed the way that radio buttons hid their input elements.  Will confirm.

**Comment by robertmesserle** [comment] 2016-05-13 20:10
Confirmed that this is fixed - closing.

**Closed by robertmesserle** 2016-05-13 20:10 UTC
Labels: a11y, P2: required
