### ISSUE TITLE
`Table retrieving data through HTTP` demo does not provide HttpClientModule

### ISSUE THREAD

**Issue by crutchcorn** [angular/material2#8936] opened 2017-12-11 18:19 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`Table retrieving data through HTTP` demo should load properly with everything loaded properly

#### What is the current behavior?
The page loads white because HttpClientModule is not provided in the demo

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>
https://stackblitz.com/angular/gjjmmmajovkn

#### What is the use-case or motivation for changing an existing behavior?
Allow the template code to be ran without modification

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by donroyco** [comment] 2017-12-11 19:01
Duplicate of #8861

**Closed** 2017-12-11 19:03 UTC
