### ISSUE TITLE
mat sort not sort properly 

### ISSUE THREAD

**Issue by tzru** [angular/material2#14137] opened 2018-11-14 11:35 UTC
#### Bug, feature request, or proposal:
Bug
#### What is the expected behavior?
Sort properly when text contains letters and numbers

#### What is the current behavior?
columns that contains letters and numbers are not sorted properly

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-f6yovq?file=app%2Ftable-sorting-example.ts
try to sort column 'Name'.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
As specified in the package.json

**Comment by willshowell** [comment] 2018-11-14 15:53
See https://github.com/angular/material2/issues/9966

**Comment by josephperrott** [comment] 2018-11-14 16:34
Closing as duplicate of 9966

**Closed by josephperrott** 2018-11-14 16:34 UTC

**Comment by tzru** [comment] 2018-11-15 07:44
Thank you.
The workaround works great for me too.
