### ISSUE TITLE
Release 2.0.0-beta.12 with angular universal not working - TypeError: ctor is not a constructor

### ISSUE THREAD

**Issue by yosigolan** [angular/material2#7649] opened 2017-10-09 06:35 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
works smoothly

#### What is the current behavior?
when running with angular universal, when the server sire rendering take place the following exception is thrown: 
TypeError: ctor is not a constructor
    at _createClass (C:\GitRepos\WebApp\node_modules\@angular\core\bundles\core.umd.js:9564:17)
    at _createProviderInstance$1 (C:\GitRepos\WebApp\node_modules\@angular\core\bundles\core.umd.js:9532:26)
    at initNgModule (C:\GitRepos\WebApp\node_modules\@angular\core\bundles\core.umd.js:9486:13)
    at new NgModuleRef_ (C:\GitRepos\WebApp\node_modules\@angular\core\bundles\core.umd.js:10600:9)
    at Object.createNgModuleRef (C:\GitRepos\WebApp\node_modules\@angular\core\bundles\core.umd.js:10584:12)
    at NgModuleFactory_.create (C:\GitRepos\WebApp\node_modules\@angular\core\bundles\core.umd.js:13888:25)
    at C:\GitRepos\WebApp\node_modules\@angular\core\bundles\core.umd.js:4529:61
    at ZoneDelegate.invoke (C:\GitRepos\WebApp\node_modules\zone.js\dist\zone-node.js:392:26)
    at Object.onInvoke (C:\GitRepos\WebApp\node_modules\@angular\core\bundles\core.umd.js:3922:33)
    at ZoneDelegate.invoke (C:\GitRepos\WebApp\node_modules\zone.js\dist\zone-node.js:391:32)

#### What are the steps to reproduce?
create a simple project with angular universal starter, import the modules:
 MatDialogModule,
    MatAutocompleteModule,
    MatInputModule,
    MatSnackBarModule,

run in server side rendering mode and see the exception.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.4.4

#### Is there anything else we should know?
this does not happen with beta 11.

**Comment by naveedahmed1** [comment] 2017-10-10 02:10
Same here, any possible workaround?

**Comment by neilhem** [comment] 2017-10-10 03:57
Does it mean release 2.0.0-beta.12 is not AOT compatible?

**Comment by naveedahmed1** [comment] 2017-10-10 10:49
Its AOT compatible but have issues only when using server-side rendering.

**Comment by naveedahmed1** [comment] 2017-10-14 01:53
I can confirm that 2.0.0-beta.12 is working with SSR. I removed node_modules, restored packages again and it started working. though I am not using MatAutocompleteModule.

**Comment by leo6104** [comment] 2017-10-14 01:58
With angular 5.0.0-rc.2 & material-beta.12, SSR works in my project. 

@naveedahmed1 if you use material import like this,
```
import {MatSnackBarModule} from '@angular/material';
```
change to
```
import {MatSnackBarModule} from '@angular/material/snack-bar'; 
```

**Comment by naveedahmed1** [comment] 2017-10-14 12:27
@leo6104 thanks for sharing this what about MatRippleModule I couldnt find @angular/material/ripple ?

**Comment by leo6104** [comment] 2017-10-14 13:49
You can use import like this. (core module)
```
import {MatRippleModule} from '@angular/material/core'; 
```

**Comment by jelbourn** [comment] 2018-01-09 23:13
Closing since beta.12 is pretty old now. Feel free to open a new issue with any new problems.

**Closed by jelbourn** 2018-01-09 23:13 UTC
