### ISSUE TITLE
Keyboard interaction md-select

### ISSUE THREAD

**Issue by vovikdrg** [angular/material2#6187] opened 2017-08-01 03:27 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
When user focuses md-select and hit keyboard values then options should change

#### What is the current behavior?
Don't react on values

#### What are the steps to reproduce?
in md select add options 1 2 3 4 5 6, then focus on it and press any of those numbers on keyboard, md-select does not react on them

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material beta.8

#### Is there anything else we should know?
This is how normal dropdown works..

**Comment by kemmis** [comment] 2017-08-01 17:45
+1

**Comment by vovikdrg** [comment] 2017-08-02 00:20
@tinayuangao  @kara I can contribute to this issue if its approved, as i see its now very complicated and i need that feature soon :)

**Comment by crisbeto** [comment] 2017-08-02 04:27
Closing as a duplicate of https://github.com/angular/material2/issues/2668.

**Closed by crisbeto** 2017-08-02 04:27 UTC
Labels: feature

**Comment by m0v0nage** [comment] 2017-09-18 19:37
@crisbeto Is this actually a duplicate? #2668 seems to be asking for the behavior when the menu is already open. @vovikdrg seems to be asking for this "autocomplete" behavior when the md-select is focused, before it is opened. I believe the current functionality is as follows:

1. Focus md-select with tab
2. Press enter
3. Type first few letters of desired selection

The user shouldn't have to press enter to start typing their selection.

**Comment by vovikdrg** [comment] 2017-09-19 00:05
@crisbeto  @m0v0nage  This is partly fixed. It has different behaviour from normal select.

Reason i am asking about this is my app i have date picker as select boxes, because of some reason it must be like that, so for instance user can just simply focus on select and type 21 then 21 will be selected.

**Comment by kemmis** [comment] 2017-09-19 12:23
+1 for this. 

>  The user shouldn't have to press enter to start typing their selection. 

Please re-open.

**Comment by jfox459** [comment] 2017-12-21 20:58
+1
