### ISSUE TITLE
Using Angular Material without `@angular/http` depandency

### ISSUE THREAD

**Issue by DmitryKrekota** [angular/material2#5869] opened 2017-07-19 11:16 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`@angular/material` must work without `@angular/http` depandency in `package.json`.

#### What is the current behavior?
Without `@angular/http` depandency I have an error: `@angular/material/typings/icon/icon-registry.d.ts (10,22): Cannot find module '@angular/http'`: https://cl.ly/2a0a1e3q010v .

#### What are the steps to reproduce?
Run `npn i` and then `ng build` for project with package.json without `@angular/http` depandency.

#### What is the use-case or motivation for changing an existing behavior?
Convenience of work with Angular Material library.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular - 4.3.0
Material - 2.0.0-beta.8
OS - Windows 10

#### Is there anything else we should know?
In my project I use `@angular/common/http` module instead of `@angular/http`, so currently `@angular/http` module is necessary only for `@angular/material` and I want to get rid of `@angular/http` depandency in my `package.json`.

**Comment by willshowell** [comment] 2017-07-19 14:40
https://github.com/angular/material2/issues/5814

**Comment by DevVersion** [comment] 2017-07-19 15:22
Duplicate of #5814

**Closed by DevVersion** 2017-07-19 15:22 UTC
