### ISSUE TITLE
use of TooltipVisibility

### ISSUE THREAD

**Issue by phsims** [angular/material2#13304] opened 2018-09-25 14:39 UTC
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
tooltip should be visible when matTooltipVisibility="visible" is set on HTML

#### What is the current behavior?
matTooltipVisibility doesn't seem to do anything

I am trying to have them displayed as a default in some areas

**Comment by crisbeto** [comment] 2018-09-25 19:15
There is no input for `matTooltipVisibility`.

**Comment by jelbourn** [comment] 2018-09-27 00:16
Closing as working as intended.

**Closed by jelbourn** 2018-09-27 00:16 UTC
