### ISSUE TITLE
Datepicker keyboard navigation stops working if min/max applied to input element

### ISSUE THREAD

**Issue by Mufasa** [angular/material2#7802] opened 2017-10-14 17:33 UTC
#### Bug, feature request, or proposal:
Bug discovered if min or max attributes are applied to the input element associated with a mat-datepicker.

#### What is the expected behavior?
Keyboard navigation of the datepicker popup should work (e.g. left/right/up/down arrow keys should move the selected date marker and enter key should select the date under the marker).

#### What is the current behavior?
Keyboard navigation stops working if either min, max or both min and max attributes are specified on the input element associated with mat-datepicker.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
https://embed.plnkr.co/CK3qnKNX8gnIDKBdW4ZA/

#### What is the use-case or motivation for changing an existing behavior?
Consistency of behaviour.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I am using Angular 4.4.5, Material 2.0.0-beta.12, OS Mac Sierra 10.12.6, Chrome 61.0.3163.100 (Official Build) (64-bit), TypeScript 2.5.3

#### Is there anything else we should know?
Also tried with TypeScript 2.1.1 and get same behaviour

**Comment by crisbeto** [comment] 2017-10-15 08:42
The issue comes from the fact that you're using a function to determine the `minDate` and `maxDate`. This means that every time Angular runs change detection (for example every keypress in the calendar) it'll get a new date object for `min` and `max` which ends up throwing off the datepicker. It works if you replace the functions with properties. [Here's a forked Plunkr.](https://plnkr.co/edit/9KUSMA9V2yv65llzEdFX?p=preview) @mmalerba is this something that we want to handle?

**Comment by Mufasa** [comment] 2017-10-15 09:54
Thanks for the explanation and workaround. Unfortunately I cannot use the proposed workaround because, in my case, the min/max dates change depending on other fields in my form. This is why I made them both functions. Is there a way you can think of that will cater for my requirements?

**Comment by crisbeto** [comment] 2017-10-15 10:00
Rather than returning the dates from a function, you can assign them after any other the other fields have changed. I think the issue is only that the dates change while the calendar is open (which is what happens when it's in the function). It's slightly less convenient, but it should be more resource-efficient since you're not creating and throwing out date objects all the time.

**Comment by Mufasa** [comment] 2017-10-15 10:05
OK - so I guess I'll have to add listeners to all the fields that could change the min/max dates. On a slightly related note, I am using dynamic forms where I add Validators to each of my form fields. Since I am adding min/max attributes to the input element associated with mat-datepicker then would it be reasonable for me not to specify field validators for the date fields? (the date field Validators I have also check that the date entered is within the given min/max dates)

**Comment by crisbeto** [comment] 2017-10-15 10:14
The datepicker already attaches its own validators (`matDatepickerMin`, `matDatepickerMax` etc.) when you set the `min` and `max` so you shouldn't have to add any more validators on top it.

**Comment by Mufasa** [comment] 2017-10-15 10:16
Great - thanks for all your help - greatly appreciated

**Comment by Mufasa** [comment] 2017-10-15 10:20
Actually I have one edge case that I'd like your opinion on. The min date for one of my dates is set to  **new Date()** (i.e. today's date). With my original implementation this automatically changed at mid-night to the next date. However, with properties, the min date will remain at the same fixed date. Is there some smart way to automagically update the min date property so that it keeps in track with "today" as time passes?

**Comment by mmalerba** [comment] 2017-10-15 20:16
How about something like this?

```ts
ngAfterContentInit() {
  this.scheduleUpdateDate();
}

scheduleUpdateDate() {
  let today = new Date();
  let tomorrow = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1);
  setTimeout(() => this.updateDate(), tomorrow.getTime() - today.getTime())
}

updateDate() {
  // do update...
  this.scheduleUpdateDate();
}
```

**Comment by crisbeto** [comment] 2017-11-04 05:15
Closing since the datepicker is working as expected.

**Closed by crisbeto** 2017-11-04 05:15 UTC
