### ISSUE TITLE
Request: Support ngValue on md-option within md-select

### ISSUE THREAD

**Issue by MoxxNull** [angular/material2#4161] opened 2017-04-19 17:44 UTC
#### Bug, feature request, or proposal:
Request

#### What is the expected behavior?
Support [ngValue] for binding to Objects (not just strings)

#### What is the current behavior?
[ngValue] is not supported in md-option / md-select as it is on plain <option> items

#### What are the steps to reproduce?
-

#### What is the use-case or motivation for changing an existing behavior?
It makes life a loooot easier :), and as it is supported by standard-option items , md-select should support it aswell.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.0 / Mat 2.0.0-beta.3

#### Is there anything else we should know?
Keep up the good work!

**Comment by willshowell** [comment] 2017-04-19 18:35
Could this be a duplicate of #2785?

**Comment by kara** [comment] 2017-04-20 23:34
@MoxxNull We actually already support objects in options, so there's no need for a second `ngValue` property (core only has this to avoid breaking people using the native `value`). See plunker here: 

http://plnkr.co/edit/djxiu9qPS0LzkBfcJFpb?p=preview

If you're running into object equality issues, `compareWith` would be the right way to address. As @willshowell mentioned, this is tracked in #2785.

**Closed by kara** 2017-04-20 23:34 UTC

**Comment by MoxxNull** [comment] 2017-04-21 06:25
Sorry, absolutly correct... I was just trying to use ngValue instead of simply trying value... my bad :(
