### ISSUE TITLE
mat-datepicker as year picker

### ISSUE THREAD

**Issue by sivahanuman** [angular/material2#10658] opened 2018-04-02 06:21 UTC
Hi,
Can i use mat-datepicker as year picker, i want to select year only.

**Comment by donroyco** [comment] 2018-04-02 07:49
Duplicate of #4853

**Comment by josephperrott** [comment] 2018-04-02 16:34
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate

**Closed by josephperrott** 2018-04-02 16:34 UTC
