### ISSUE TITLE
No carousel component is present

### ISSUE THREAD

**Issue by bgity** [angular/material2#14661] opened 2018-12-28 07:32 UTC
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by jotatoledo** [comment] 2018-12-28 13:09
https://github.com/angular/material2/issues/5693

**Comment by crisbeto** [comment] 2019-01-05 08:50
Closing as a duplicate of #5693.

**Closed by crisbeto** 2019-01-05 08:50 UTC
