### ISSUE TITLE
incorrect styling on dropdowns in mat-select and mat-autocomplete

### ISSUE THREAD

**Issue by CPfi12** [angular/material2#9826] opened 2018-02-07 15:33 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Dropdowns are functional, but styling is off:
 - Gray background for hover should go across whole row
 - On selecting of option, animation should be limited to the row of interest
 - pointer cursor over options
 - If text for an option is too long, should so "..." at end but stay on same row

#### What is the current behavior?
- Gray background for hover only wraps around the text on that line
- On selecting of option, animation is a circle from the upper left corner
- No pointer cursor over options, but can click
- If text for an option is too long, goes onto a second row

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome

**Comment by crisbeto** [comment] 2018-02-08 19:14
All of these behaviors should be in place already. Can you post an example of it breaking?

**Comment by CPfi12** [comment] 2018-02-11 04:14
<img width="275" alt="screen shot 2018-02-10 at 11 12 55 pm" src="https://user-images.githubusercontent.com/26070671/36069447-1ec2008c-0eb8-11e8-9c63-abe04dc70427.png">

**Comment by crisbeto** [comment] 2018-02-11 08:36
That looks like there might be other styles in your app that are interfering or some of Material's structural styles weren't included for some reason. [Here's what it looks like when everything is setup up correctly.](https://material.angular.io/components/select/overview)

**Comment by mth654** [comment] 2018-02-24 22:47
The results in your screenshot happen when you have material >= 5.2.0 but your other angular dependencies are < 5.2.0. The inline style for mat-option doesn't get written for some reason.

**Comment by josephperrott** [comment] 2018-03-30 14:54
Closing as no reproduction has been provided.

**Closed by josephperrott** 2018-03-30 14:54 UTC
Labels: cannot reproduce
