### ISSUE TITLE
Feature Request : Features like drag and drop, gesture detection as part of CDK

### ISSUE THREAD

**Issue by rahulsahay19** [angular/material2#10443] opened 2018-03-16 05:44 UTC
Hi Team,

Just a question, last year in angular mix, it was announced that features like **drag and drop feature and gesture capturing** will be part angular component development kit. Just wanted to understand, whether it will be part of the release planned in april 6.

Here is the link which I am referring to https://www.youtube.com/watch?v=kYDLlfpTLEA. If this is not the right place to ask question, then kindly redirect me to correct forum.

Thanks,
Rahul

**Comment by rahulsahay19** [comment] 2018-03-16 05:54
@jelbourn @crisbeto 

Hello Sir, 

Any update on the above feature request. I mean whether it will be part **April 6** release or it will be released later?

Thanks,
 Rahul

**Comment by fxck** [comment] 2018-03-16 09:03
https://github.com/angular/material2/issues/8963

**Comment by crisbeto** [comment] 2018-03-16 11:23
Closing as a dupe of #8963.

**Closed by crisbeto** 2018-03-16 11:23 UTC
