### ISSUE TITLE
No value accessor for from control

### ISSUE THREAD

**Issue by cschroeter** [angular/material2#1018] opened 2016-08-12 12:55 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
There should be an value accessor.

#### What is the current behavior?
```
main.987e5bf….bundle.js:17 EXCEPTION: No value accessor for form control with name: 'username'
```

#### What are the steps to reproduce?
This bug occurs only if you run ```ng build --prod ```. 

Use angular-cli@webpack to create a new project.

```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MdCardModule } from '@angular2-material/card/card';
import { MdInputModule } from '@angular2-material/input/input';
import { MdButtonModule } from '@angular2-material/button/button';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    CommonModule,
    ReactiveFormsModule,
    MdCardModule,
    MdInputModule,
    MdButtonModule,
  ],
  providers: [],
  entryComponents: [AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule {

}
``` 

```html
<form [formGroup]="form">
  <md-card>
    <md-card-title>{{title}}</md-card-title>
    <md-card-content>
      <md-input placeholder="Username" formControlName="username"></md-input>
      <md-input placeholder="Password" formControlName="password"></md-input>
    </md-card-content>
    <md-card-actions align="end">
      <button md-button color="primary" type="submit">LOGIN</button>
    </md-card-actions>
  </md-card>
</form>
```

#### What is the use-case or motivation for changing an existing behavior?
Build an Angular2 app with prod flag.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular@RC.5, Angular-CLI@webpack.2, Material@alpha.7-2, OSX 10.11.5

#### Is there anything else we should know?
As mentioned above, this only happens with the prod flag

**Comment by SamiAl90** [comment] 2016-08-13 08:18
You are missing the FormsModule import from @angular/forms I think. ReactiveModule is not enough afaik.

**Comment by cschroeter** [comment] 2016-08-13 16:03
I think I had a reference on FormModules at some point. But If it is really needed here, it should not work in dev mod either

**Comment by YeomansIII** [comment] 2016-08-14 17:58
I'm also getting this error using ngModel on an input that is not even inside of a form.
```
<md-input placeholder="Track ID" name="track_id" [(ngModel)]="data.track_id"></md-input>
<md-input placeholder="Cover URL" name="cover_url" [(ngModel)]="data.cover_url"></md-input>
```

Getting the error `No value accessor for form control with unspecified name` within browser_adapter.js.

I have FormsModule and I just tested with ReactiveFormsModule as well after reading this thread.  Still getting the same error.

**Comment by Sabartius** [comment] 2016-08-17 09:33
@YeomansIII  I also got the error `No value accessor for form control with unspecified name`
It was resolved by importing `FormsModule` **and** `ReactiveFormsModule`

**Comment by jelbourn** [comment] 2016-08-31 01:39
@cschroeter is this still happening with the latest version of webpack angular-cli?

**Comment by cschroeter** [comment] 2016-09-05 09:09
@jelbourn works with `angular-cli@webpack.8` and `@angular2-material/*: 2.0.0-alpha.8-1`

**Comment by JSMike** [comment] 2016-09-07 14:49
Just looking at this from a Model Driven Form approach. is it possible to bind to a [formControl] instead of [(ngModel)]? We shouldn't be using ngModel at all with model driven forms. It looks like current mdInput field definition is only meant to work with template driven forms.

**Comment by jeffreymolina** [comment] 2016-09-23 03:51
Not working with angular 2.0.0 release, 2.0.0-alpha.8-2, imported FormsModule and ReactiveFormsModule.  Interchanging md-input with input using the same ngModel works fine.

**Closed** 2016-10-19 23:58 UTC

**Comment by karvapallo** [comment] 2017-02-21 18:09
Still getting this in the `md-select` control using `@angular/** 2.2.1`.

**Comment by maxime1992** [comment] 2017-05-05 20:34
With `material 2.0.0-beta.3` we now have to import every modules one by one and I forgot `MdSelectModule` which gave me this error. (might help someone)

**Comment by splurtcake** [comment] 2017-09-29 02:36
Still getting this with `md-radio-button`

**Comment by ltfleming** [comment] 2017-09-29 03:42
Also having this with md-radio-button

**Comment by VictorSDK** [comment] 2017-09-30 10:07
Find out that some other missing material modules can be the cause of this issue. I was getting this error because I forgot to import MatCheckboxModule, but the error points to a line where there is a [value] attribute in a <mat-option> of a <mat-select>

**Comment by ganeshpatil0101** [comment] 2017-10-09 08:30
I am also getting the same error for md-select, earlier it was working fine.
_@angular/cli: 1.2.7
node: 8.6.0
os: linux x64
@angular/animations: 4.3.3
@angular/cdk: 2.0.0-beta.11
@angular/cli: 1.2.7
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/platform-server: 4.3.3
@angular/router: 4.3.3
@angular/compiler-cli: 4.4.3__

**Comment by silentHoo** [comment] 2017-11-10 09:17
I'm getting this same error when testing `md-checkbox` together with reactive forms like this. When I build or run the app in dev mode it works as expected.

```
<mat-checkbox
  id="allDay"
  type="checkbox"
  formControlName="allDay">
      <!-- i18n: @@event.allDay -->All Day Event?<!-- /i18n -->
</mat-checkbox>
```

The error is:

```
Failed: No value accessor for form control with name: 'allDay'
  Error: No value accessor for form control with name: 'allDay'
      at _throwError <path_to_my_project>/node_modules/@angular/forms/@angular/forms.es5.js:1918:1)
      at setUpControl <path_to_my_project>/node_modules/@angular/forms/@angular/forms.es5.js:1828:1)
      at FormGroupDirective.webpackJsonp.../../../forms/@angular/forms.es5.js.FormGroupDirective.addControl <path_to_my_project>/node_modules/@angular/forms/@angular/forms.es5.js:4808:1)
      at FormControlName.webpackJsonp.../../../forms/@angular/forms.es5.js.FormControlName._setUpControl <path_to_my_project>/node_modules/@angular/forms/@angular/forms.es5.js:5396:1)
      at FormControlName.webpackJsonp.../../../forms/@angular/forms.es5.js.FormControlName.ngOnChanges <path_to_my_project>/node_modules/@angular/forms/@angular/forms.es5.js:5314:1)
      at checkAndUpdateDirectiveInline <path_to_my_project>/node_modules/@angular/core/@angular/core.es5.js:10845:1)
      at checkAndUpdateNodeInline <path_to_my_project>/node_modules/@angular/core/@angular/core.es5.js:12349:1)
      at checkAndUpdateNode <path_to_my_project>/node_modules/@angular/core/@angular/core.es5.js:12288:1)
      at debugCheckAndUpdateNode <path_to_my_project>/node_modules/@angular/core/@angular/core.es5.js:13149:22)
      at debugCheckDirectivesFn <path_to_my_project>/node_modules/@angular/core/@angular/core.es5.js:13090:1)
```

Code works for `<mat-form-field>` without problems:

```
<mat-form-field>
  <input
    matInput
    type="text"
    formControlName="name">
</mat-form-field>
```

Is this still a bug or do I miss something?

**Comment by rajeshkumarsampath** [comment] 2017-12-20 14:04
Add ngDefaultControl to the custom-input component. This adds two-way databinding, you shouldn't have to implement the value accessor methods unless you are doing something unique.

`<custom-input name="firstName" [(ngModel)]="firstName" ngDefaultControl></custom-input>`

**Comment by mfdeveloper** [comment] 2018-05-08 12:38
@rajeshkumarsampath This solution doesn't works. This directive will apply `DefaultValueAcessor` that contains a default implementation of `writeValue()`. This is not a real solution, because the custom control implements `ControlValueAccessor` interface and override this method.

Import `ReactiveFormsModule` and `FormsModule` into my module too like @Sabartius said, doesn't works too. In my case, the custom component that inherit implements `ControlValueAccessor` is nested into another component. When move to outside from them, it works!!

**Comment by mluis** [comment] 2018-05-22 10:56
I'm having the exact same issue as @VictorSDK . Any solution for this?
