### ISSUE TITLE
The sticky in the table doesn't work!

### ISSUE THREAD

**Issue by kinmy** [angular/material2#12010] opened 2018-07-02 08:55 UTC
#### Bug, feature request, or proposal:
The sticky in the table doesn't work!

#### What is the expected behavior?
Sticky the first and the second td element.

#### What is the current behavior?
Sticky doesn't work!

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Be easier to watch the table information on the phone.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "^6.0.3",
"@angular/material": "^6.2.0",
OS: macOS High Sierra 10.13.4,
"typescript": "~2.7.2",
chrome:67.0

**Comment by eTallang** [comment] 2018-07-02 17:21
There is an example on how to use the sticky rows/columns in the docs:
https://material.angular.io/components/table/overview#sticky-rows-and-columns

We're using sticky columns in our project and they work just as intended.

**Comment by kinmy** [comment] 2018-07-03 03:07
I also added sort and asynchronously acquired data, and when I finally wanted to add sticky, I found that it didn't work.

**Comment by kinmy** [comment] 2018-07-03 03:10
I also added sort and retrieving data through HTTP, and when I finally wanted to add sticky, I found that it didn't work.

**Comment by kinmy** [comment] 2018-07-03 06:59
This is the chrome error log:
Uncaught Error: Template parse errors:
Can't bind to 'matHeaderRowDefSticky' since it isn't a known property of 'tr'. (""let element"> {{ element.volume }}</td>
            </ng-container>
            <tr mat-header-row [ERROR ->]*matHeaderRowDef="displayedColumns; sticky: true"></tr>
            <tr mat-row *matRowDef="let row; "): ng:///AppModule/ProjectDetailComponent.html@168:31
Property binding matHeaderRowDefSticky not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("t-cell *matCellDef="let element"> {{ element.volume }}</td>
            </ng-container>
            [ERROR ->]<tr mat-header-row *matHeaderRowDef="displayedColumns; sticky: true"></tr>
            <tr mat-row *m"): ng:///AppModule/ProjectDetailComponent.html@168:12
    at syntaxError (compiler.js:215)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:14702)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:22709)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:22696)
    at compiler.js:22639
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:22639)
    at compiler.js:22549
    at Object.then (compiler.js:206)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:22548)

**Comment by eTallang** [comment] 2018-07-03 07:04
From the looks of it, you're using `@angular/material@6.2.0`. The `sticky`-attribute was introduced in version 6.3.0. Try updating your dependency to `@angular/material` and `@angular/cdk` and see if that helps.

**Comment by kinmy** [comment] 2018-07-03 09:47
Thx so much!Sticky is worked when I have updated my material & cdk!

**Comment by kinmy** [comment] 2018-07-04 04:18
Now I have a new problem.I found the border-right in the sticky td cannot sticky. The border-right in the sticky td is also move when I move the content after the sticky td(my sticky td is on the first and second td).Can you help me solve it?

**Comment by kinmy** [comment] 2018-07-04 04:32
All right.

**Comment by kinmy** [comment] 2018-07-04 05:35
I added border-right in sticky td, but when I moved the table, the border-right would also move along. Now I want to move the table, border-right is fixed.

**Comment by bmercier-manakin** [comment] 2018-07-10 12:32
@kinmy can you provide an example of your behavior.
If you can't, can you try to add the border on the last child of the td tag, instead of the td itself ?

**Comment by josephperrott** [comment] 2018-07-16 21:14
Closing this issue since the initial issue reported seems to be sorted out.

**Closed by josephperrott** 2018-07-16 21:14 UTC
