### ISSUE TITLE
hammerjs import error

### ISSUE THREAD

**Issue by crossme** [angular/material2#2862] opened 2017-01-30 04:59 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
You need to 'import hammers' at @angular2-material/core/gestures/MdGestureConfig.d.ts

#### What is the current behavior?
Error for import.

**Comment by crisbeto** [comment] 2017-01-30 08:53
Closing as a dupe of #2863.

**Closed by crisbeto** 2017-01-30 08:53 UTC
