### ISSUE TITLE
feat: TimePicker

### ISSUE THREAD

**Issue by odahcam** [angular/material2#11156] opened 2018-05-04 14:19 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Being able to pick hours trough the material TimePicker.

#### What is the current behavior?
Just DatePicker.

#### What are the steps to reproduce?
https://stackblitz.com/edit/material-time-control

#### What is the use-case or motivation for changing an existing behavior?
No changes.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
v6

#### Is there anything else we should know?
List of resources:
- Good look: https://github.com/SteveDunlap13/MaterialTimeControl
- Same as before, but a fork with demo: https://github.com/Gaiidenn/MaterialTimeControl
- Not Ng Material, but allows to drag the picker pointer: https://owsolutions.github.io/amazing-time-picker/Examples

**Comment by josephperrott** [comment] 2018-05-04 16:07
Closing as duplicate of https://github.com/angular/material2/issues/5648

**Closed by josephperrott** 2018-05-04 16:07 UTC

**Comment by odahcam** [comment] 2018-05-04 16:26
I did think DatePicker and TimePicker weren't the same.

**Comment by torabian** [comment] 2018-11-23 11:02
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.

**Comment by tiaguinho** [comment] 2019-01-23 11:38
@odahcam If you are still interested, I had developed this component inside [Material Community Components](https://github.com/tiaguinho/material-community-components).
