### ISSUE TITLE
Autocomplete option not clickable

### ISSUE THREAD

**Issue by JacobBrandt** [angular/material2#4465] opened 2017-05-10 16:38 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should be able to click option in autocomplete.

#### What is the current behavior?
Unable to click option in autocomplete.

#### What are the steps to reproduce?
https://material.angular.io/components/component/autocomplete
Launch version 45.7 of Firefox.  Use the example provided by the material website.  I don't know why but for some reason I could not reproduce the issue within a plunker.  The material website demonstrates the problem I am having though with this version of Firefox.

#### What is the use-case or motivation for changing an existing behavior?
It's a bug

#### Which versions of Angular, Material, OS, browsers are affected?
Firefox v45.7

#### Is there anything else we should know?
Nope

**Comment by crisbeto** [comment] 2017-05-10 17:15
The issue should be fixed in master. You can try installing the latest build:

```bash
npm install https://github.com/angular/material2-builds.git
```

**Comment by JacobBrandt** [comment] 2017-05-10 18:17
@crisbeto I'll try the latest build later today and see if it works.  Thanks.

**Comment by jelbourn** [comment] 2017-05-11 23:31
Closing since @crisbeto says it's already fixed on master, feel free to comment if that's not the case

**Comment by JacobBrandt** [comment] 2017-05-12 00:52
@jelbourn @crisbeto Well after doing npm install of latest build like you both suggested.  I can't even bring up my application now.  Lots of Typescript errors.  For instance.

ERROR in node_modules/@angular/material/typings/button/button.d.ts (40,22): Class 'MdButton' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MdButton'.

**Comment by jfilgairacordon** [comment] 2017-05-12 09:05
I'm having the same issue using Geecko v45.0.22.0. I'm making a copy of my project. Once it finish, I will try to update material to the last version and try it again. I will comment if it works later.

**Comment by jfilgairacordon** [comment] 2017-05-12 10:57
I have updated my project and resolved all the problems. The autocomplete still not working on Geecko v45.0.22.0.

**Comment by crisbeto** [comment] 2017-05-12 11:03
I'm still not able to reproduce it in Firefox. Can you post an example? 
![a](https://cloud.githubusercontent.com/assets/4450522/25995584/5767ed70-3713-11e7-86d6-9b34fcdb085a.gif)

**Comment by jfilgairacordon** [comment] 2017-05-12 11:14
I'm using an embeded (WebBrowser) geckofx package from NuGet on a windows form application that allows me to use this engine on our application. For some dev reasons we have to use this.

When the user clicks over an option, the autocomplete disapears and the ngModel does not get the new value.

![image](https://cloud.githubusercontent.com/assets/7438628/25995778/455043c0-3714-11e7-89a5-b10be0b70655.png)

![githubautocompleteproblem](https://cloud.githubusercontent.com/assets/7438628/25995932/e5c4567a-3714-11e7-8729-8da0a4402b4d.gif)

**Comment by crisbeto** [comment] 2017-05-12 11:31
Not sure why it might be breaking for you, but I just noticed that we have a regression for a similar issue in IE. My guess is that it's related.

**Comment by sabithpocker** [comment] 2017-05-12 12:18
`cdk-overlay-container` has `z-index:1000`. `cdk-overlay-pane` also has the same `z-index:1000` shouldn't it be `z-index:1001` for `cdk-overlay-pane` or just omit `z-index` for `idk-overlay-pane`?

**Comment by jfilgairacordon** [comment] 2017-05-12 12:31
I've try with z-index: 1001 (cia Harcoded CSS) and still not working.

**Comment by crisbeto** [comment] 2017-05-12 12:50
@jfilgairacordon I've tried it against all the supported browsers/devices that I could find (as well as some unsupported, like Firefox 45) and I couldn't reproduce it anywhere. My guess is that it's something specific to your setup. I'm sorry, but there's no way to help without a repro case. The issue can be reopened if you manage to isolate it in a Plunkr. We're also open to pull requests, if you manage to track the issue down on your own.

@sabithpocker the `z-index` isn't relevant here. The overlays will stack correctly, because even though they have the same `z-index`, every newly-added overlay will be added after all others in the DOM.

**Closed by crisbeto** 2017-05-12 12:50 UTC

**Comment by JacobBrandt** [comment] 2017-05-12 12:51
@crisbeto Are you sure you are trying with version 45.7 of Firefox?  Every single one of my coworkers with this version has this problem.  It works with latest version of Firefox but that's not possible for our users to do at the moment.

**Comment by crisbeto** [comment] 2017-05-12 13:02
Yes @JacobBrandt, here's an example with Firefox 45.0 against the current `master`:

![a](https://cloud.githubusercontent.com/assets/4450522/25999056/fa8e0088-3723-11e7-8186-eaa3526a1b22.gif)

**Comment by JacobBrandt** [comment] 2017-05-12 16:03
@crisbeto Thank you for trying older browsers to try and reproduce.  Like I said I am using version 45.7.  I see you are saying 45.0.  If you could try this version maybe you will be able to reproduce the problem.

Also I've tried master branch like you suggested but I can't get webpack to build with it because of the errors I mentioned earlier.

**Comment by willshowell** [comment] 2017-05-12 16:32
I was able to reproduce @JacobBrandt's issues on macOS 10.12.4 with Firefox 45.0 and 45.7

## 45.0
![45-0 issue](https://cloud.githubusercontent.com/assets/6475576/26007521/d92cdfa0-370e-11e7-858a-e078b38cb900.gif)


## 45.7
![45-7 issue](https://cloud.githubusercontent.com/assets/6475576/26007527/dd1b87c4-370e-11e7-803c-c2c4c8049a06.gif)

## 53.0 (working)
![53-0 working](https://cloud.githubusercontent.com/assets/6475576/26007537/e2dbcec6-370e-11e7-8f18-9e43deac4085.gif)

**Comment by crisbeto** [comment] 2017-05-12 17:30
I can also reproduce it on the demo site (which is running beta.3) @willshowell, but it's gone in `master` (verified it with Firefox 45 on a Mac). It was fixed by https://github.com/angular/material2/pull/3188.

**Comment by willshowell** [comment] 2017-05-12 18:48
@crisbeto Oh yeah hah. You're right - just tested on FF 45.7 with latest and it worked fine

**Comment by jfilgairacordon** [comment] 2017-05-15 09:26
After upgrading to the new beta 5 of material the autocomplete component works fine!
