### ISSUE TITLE
md-datepicker not rendered in an appropriate direction

### ISSUE THREAD

**Issue by alanpurple** [angular/material2#4813] opened 2017-05-26 08:38 UTC
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
render direction should properly set so calendar can be seen

#### What is the current behavior?
always render to left below

rendering option ( fixed(in 4 ways), auto )

**Comment by fxck** [comment] 2017-05-26 09:14
dupe of https://github.com/angular/material2/issues/4406

**Closed** 2017-05-26 09:50 UTC
