### ISSUE TITLE
Datepicker component close my md-dialog

### ISSUE THREAD

**Issue by yoanasdrubal** [angular/material2#4563] opened 2017-05-15 14:07 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When use datepicker component inside md-dialog component do not close md-dialog component

#### What is the current behavior?
I am using datepicker component inside md-dialog component, when I click button to pick date that event close my md-dialog component

#### What are the steps to reproduce?
CODE:
![spectacle tj2363](https://cloud.githubusercontent.com/assets/28707787/26061432/f08369dc-3955-11e7-8ca6-e9a7e4c69565.png)

This is md-dialog component
![spectacle lh1421](https://cloud.githubusercontent.com/assets/28707787/26061224/48fc4a30-3955-11e7-94b7-7c0a698939ad.png)

In this way behaves, displays the calendar at the same time as it hides the dialog and then closes the calendar
![spectacle tj2225](https://cloud.githubusercontent.com/assets/28707787/26061525/2c12faa8-3956-11e7-9d8d-6c86916d4de8.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I am using: 
Firefox 52.0.1
 Angular 4.0.3, 
Angular/material 2.0.0-beta.5-6121fa1  typescript 2.3.2

**Comment by crisbeto** [comment] 2017-05-15 14:46
Closing as a duplicate of https://github.com/angular/material2/issues/4530.

**Closed by crisbeto** 2017-05-15 14:46 UTC
