### ISSUE TITLE
SystemJS-builder errors when project uses angular 2 material components

### ISSUE THREAD

**Issue by RoxKilly** [angular/material2#561] opened 2016-05-28 07:08 UTC
I use [systemjs-builder 0.15.18](https://www.npmjs.com/package/systemjs-builder) along with `gulp` to bundle all compiled JS files into one.  This works fine until I attempt to use Angular Material 2 (alpha 5) components/services. Having the `import {MdIcon} from '@angular2-material/icon'` at the top of the file is no problem, but as soon as I add `MdIcon` or any other Material component or service to the `directives` or `providers` arrays, I get an error during the build process such as:
```
{ [Error: Error on fetch for node_modules/@angular2-material/icon/icon.js at file:///c:/websites/learn/angular2/node_modules/@angular2-material/icon/icon.js
	Loading app//app/my-app.component.js
	Loading app//main.js
	ENOENT, open 'c:\websites\learn\angular2\node_modules\@angular2-material\icon\usr\local\google\home\jelbourn\material2\tmp\broccoli_type_script_compiler-input_base_path-IydvmmBU.tmp\0\components\icon\icon.js.map']
  originalErr: 
   { [Error: ENOENT, open 'c:\websites\learn\angular2\node_modules\@angular2-material\icon\usr\local\google\home\jelbourn\material2\tmp\broccoli_type_script_compiler-input_base_path-IydvmmBU.tmp\0\components\icon\icon.js.map']
     cause: 
      { [Error: ENOENT, open 'c:\websites\learn\angular2\node_modules\@angular2-material\icon\usr\local\google\home\jelbourn\material2\tmp\broccoli_type_script_compiler-input_base_path-IydvmmBU.tmp\0\components\icon\icon.js.map']
        errno: -4058,
        code: 'ENOENT',
        path: 'c:\\websites\\learn\\angular2\\node_modules\\@angular2-material\\icon\\usr\\local\\google\\home\\jelbourn\\material2\\tmp\\broccoli_type_script_compiler-input_base_path-IydvmmBU.tmp\\0\\components\\icon\\icon.js.map' },
     isOperational: true,
     errno: -4058,
     code: 'ENOENT',
     path: 'c:\\websites\\learn\\angular2\\node_modules\\@angular2-material\\icon\\usr\\local\\google\\home\\jelbourn\\material2\\tmp\\broccoli_type_script_compiler-input_base_path-IydvmmBU.tmp\\0\\components\\icon\\icon.js.map' } }
```
It seems the routine is trying to load `icon.js.map` from the wrong location.  Instead of the directory `c:\websites\learn\angular2\node_modules\@angular2-material\icon\`, it's looking for `c:\websites\learn\angular2\node_modules\@angular2-material\icon\usr\local\google\home\jelbourn\material2\tmp\broccoli_type_script_compiler-input_base_path-IydvmmBU.tmp\0\components\icon\`

I am new to both Material, Gulp and SystemJS-builder so I'm not sure where to start looking for the problem.  I came here because without Material, the bundling works fine even if I use angular 2's services. Any ideas?

**Comment by vincentpalita** [comment] 2016-05-28 07:30
@RoxKilly this is related to #541

**Comment by RoxKilly** [comment] 2016-05-28 07:40
Thanks. I'd like to try the workaround mentioned there if I find a way to remove or fix the references automatically on a Windows machine.

**Comment by DevVersion** [comment] 2016-05-28 08:25
As @vincentpalita said, this is a duplicate of #541. We should track all our information in #541.

**Closed** 2016-05-28 10:09 UTC
