### ISSUE TITLE
md-tabs ripple effect speed

### ISSUE THREAD

**Issue by djleonskennedy** [angular/material2#3220] opened 2017-02-21 12:48 UTC
#### Bug, feature request, or proposal:
clarification

#### What is the expected behavior?
fast ripple effect

#### What is the current behavior?
very slow ripple effect

#### What are the steps to reproduce?
```
  <md-tab-group  (selectChange)="tabSelect($event)" mat-stretch-tabs>
    <md-tab label="All"></md-tab>
    <md-tab label="Pinned"></md-tab>
  </md-tab-group>
```

Can provide plunker cause in plunker all ripple effect works fine
in my case effect is very slow

#### What is the use-case or motivation for changing an existing behavior?
existing behavior isn't changed

#### Which versions of Angular, Material, OS, browsers are affected?
angular ~2.4.3, material2: 2.0.0-beta.2l
chrome @latest, IE11

#### Is there anything else we should know?
no extra steps was made

Q: Can we change speed duration of ripple ?

**Comment by Kyderman** [comment] 2017-02-21 13:28
I can confirm this bug is present for me too.

**Comment by DevVersion** [comment] 2017-02-21 21:50
Thanks for the issue. This should have been fixed with SHA https://github.com/angular/material2/commit/5c7a96ba4370b8bb0aefe7cd0363636331795d37

**Closed by DevVersion** 2017-02-21 21:50 UTC

**Comment by djleonskennedy** [comment] 2017-02-22 08:48
Is it in last release? material2: 2.0.0-beta.2l

**Comment by Kyderman** [comment] 2017-02-22 09:23
@djleonskennedy, I assume not because the bug was present on latest version for me.

Next release probably.

If you cant wait, mod your own node_modules version of meterial2.
