### ISSUE TITLE
Mat menu position from fixed trigger element

### ISSUE THREAD

**Issue by Trysor** [angular/material2#12220] opened 2018-07-15 16:05 UTC
#### Bug, feature request, or proposal:

When the trigger for a matMenu is within or itself a position: fixed element, the menu ignores it and appears relative to the scroll position of the page.

#### What is the expected behavior?

For the menu to appear as intended, given its input values, relative to its trigger, regardless of having scrolled, and regardless of fixed, absolute or static positioning values of the trigger or the trigger's ancestors.

#### What is the current behavior?

The matMenu appears further down the page if the page has scrolled; not relative to its trigger. If you continue to scroll with the menu open the menu will go up or down with the page.

#### What are the steps to reproduce?

1. Create a trigger within a div that is fixed to the top of the page.
2. Add a matMenu to be triggered. Can also be a child of said div -- does not matter.
3. Add content or styling such that the page has a sizeable scroll
4. Load page, scroll partially down the page, trigger the menu

#### What is the use-case or motivation for changing an existing behavior?

Allow menus to be triggered from fixed elements; such as sticky headers

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular: 6.1.0-rc.0
Material / CDK: 6.3.3

#### Is there anything else we should know?

"Bob" at the top is the trigger:

![2018-07-15_18-02-31](https://user-images.githubusercontent.com/4071575/42735712-4b5146b0-8859-11e8-9db2-80022bb44e05.png)

**Comment by crisbeto** [comment] 2018-07-15 16:56
Duplicate of https://github.com/angular/material2/issues/11365.

**Closed by crisbeto** 2018-07-15 16:56 UTC
