### ISSUE TITLE
[slider,tab @alpha.9-3] slider cannot be used within tab (verbose API)

### ISSUE THREAD

**Issue by RoxKilly** [angular/material2#1726] opened 2016-11-04 05:38 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`MdSlider` should work within tabs

#### What is the current behavior?
When a slider is used within a tab that uses the verbose API

 - Slider value is set to max allowed as soon as slider receives focus
 - thumbtack cannot be moved
 - slider value remains at max indefinitely

#### What are the steps to reproduce?
Just put a slider within a tab ([see this plunk](http://plnkr.co/edit/7Bp7X5XkPB8e1CWrSoXJ?p=preview)):
```
<md-tab-group>
  <md-tab>
     <template md-tab-label>Tab</template>
     <template md-tab-content>	    
          <md-slider min="0" max="20"></md-slider>                
     </template>
  </md-tab>
</md-tab-group>
```

#### What is the use-case or motivation for changing an existing behavior?
bug-fixing

#### Which versions of Angular, Material, OS, browsers are affected?
`Angular 2.0.1`, `Material 2 alpha 9-3`

#### Is there anything else we should know?
I have not tested the compact tab-group API

**Comment by mmalerba** [comment] 2016-11-04 18:08
duplicate of #1389

**Closed by mmalerba** 2016-11-04 18:08 UTC
