### ISSUE TITLE
Underline the input on hover.

### ISSUE THREAD

**Issue by jaesung2061** [angular/material2#7236] opened 2017-09-21 20:15 UTC
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
I would like for form inputs to hover when it is hovered.

#### What is the current behavior?
It is underlined only on focus.

#### What are the steps to reproduce?
Hover and focus on input.

#### What is the use-case or motivation for changing an existing behavior?
Make it a little more obvious that it is a form input. I imagine it might not be uncommon for users to overlook that it is a form.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest release.

**Comment by willshowell** [comment] 2017-09-21 20:31
I think this falls under https://github.com/angular/material2/issues/3984

**Comment by josephperrott** [comment] 2017-09-25 16:51
Closing as duplicate of #3984

**Closed by josephperrott** 2017-09-25 16:51 UTC
