### ISSUE TITLE
SnackBar don't show from ErrorHandler.

### ISSUE THREAD

**Issue by shalugin** [angular/material2#7470] opened 2017-10-02 11:31 UTC
#### Bug, feature request, or proposal:

Probably it's a bug.

#### What is the expected behavior?

SnackBar don't show from ErrorHandler.

#### What is the current behavior?

SnackBar show from ErrorHandler.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material2-issue-zkyrh5

1. Open app, click on the button.
1. SnackBar is hidden (I expect visible, because of CORS error).
1. Click on the button again.
1. SnackBar is visible.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Latest angular and material2, FF, Chrome

#### Is there anything else we should know?

Maybe it's some kind of change detection bug.

Is there any workaround for this?

**Comment by josephperrott** [comment] 2017-10-02 17:18
Closing as duplicate of #7233.  This occurs because the ErrorHandler is not called within the Angular zone.

**Closed by josephperrott** 2017-10-02 17:18 UTC

**Comment by shalugin** [comment] 2017-10-03 11:45
@josephperrott Thanks.

I use this as solution (maybe it would be helpful fo somebody):

```
import { Injectable } from '@angular/core';
import { HttpEvent, HttpHandler, HttpInterceptor, HttpRequest, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs/Observable';
import { MdSnackBar } from '@angular/material';

@Injectable()
export class HttpErrorInterceptor implements HttpInterceptor {

  constructor(private _snackBar: MdSnackBar) {
  }

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(req).do(event => {
      if (event instanceof HttpResponse) {
        if (event.body && event.body.error === true && event.body.errorMessage) {
          throw new Error(event.body.errorMessage);
        }
      }
    }).catch((err) => {
      this._snackBar.open(err, 'OK', { duration: 5000 });
      return Observable.empty<HttpEvent<any>>();
    });
  }
}
```

**Comment by Furqanaa** [comment] 2019-03-30 10:44
In my case, The solution was using this.handleError.bind(this) as shown below:

  public post<T>(url: string, data: any, options?: HttpOptions): Observable<T> {
    return this.http.post<T>(this.baseUrl + url, data, options).pipe(
      map((res: T) => {
        return res as T;
      }),
      catchError(this.handleError.bind(this))
    );
