### ISSUE TITLE
CSS is broken when built with -prod (CLI)

### ISSUE THREAD

**Issue by manekinekko** [angular/material2#1089] opened 2016-08-20 02:23 UTC
#### Bug, feature request, or proposal:
- [x] Bug

#### What is the expected behavior?
![image](https://cloud.githubusercontent.com/assets/1699357/17828253/ea1a32ac-668c-11e6-8132-3e6c41331fec.png)

![image](https://cloud.githubusercontent.com/assets/1699357/17828259/04af9814-668d-11e6-9cfa-60ffbde68eaa.png)

#### What is the current behavior?
![image](https://cloud.githubusercontent.com/assets/1699357/17828245/d3d84736-668c-11e6-913c-6fa952adc56a.png)

![image](https://cloud.githubusercontent.com/assets/1699357/17828269/303e367a-668d-11e6-9fea-e6d4460ac7c1.png)

#### What are the steps to reproduce?

Simply use any card or button components and build in prod mode.

```
$ ng build -prod # is breaking
$ ng build -dev # OK
```

#### Which versions of Angular, Material, OS, browsers are affected?
`angular2@2.0.0-rc5`, `angular-cli@1.0.0-beta.10`, `@angular2-material@2.0.0-alpha-7-3`

**Comment by Kosmonaft** [comment] 2016-08-21 23:28
Hi, 

This is a know issue. Check this 2 issues from angular and  angular-cli
[#10618](https://github.com/angular/angular/issues/10618)
[#1662](https://github.com/angular/angular-cli/pull/1662)

The problem is in the minify-ing

**Comment by jelbourn** [comment] 2016-08-22 16:24
Closing since it appears to be an issue with angular-cli

**Closed by jelbourn** 2016-08-22 16:24 UTC
