### ISSUE TITLE
mdTooltip when button is disabled

### ISSUE THREAD

**Issue by Miiekeee** [angular/material2#2576] opened 2017-01-09 15:39 UTC
#### Bug, feature request, or proposal:
For the app we are building we would like to have the option to add a tooltip to a button when it is disabled. 

#### What is the current behavior?
No tooltip when a button is disabled.

#### What is the use-case or motivation for changing an existing behavior?
We are using [attr.title]="model.IsActive ? 'This model is active' : 'This model is inactive'" to give the user a reason as for why they can't click on the button so they can take correct actions. We would like to use mdTooltip for this purpose.

**Comment by crisbeto** [comment] 2017-01-09 16:19
We had this issue on Material 1 as well. The problem is that the browser doesn't fire mouse events for disabled buttons. The two workarounds are to either wrap it in a div and set the tooltip on the wrapper, or use a div and style it as a button.

**Comment by jelbourn** [comment] 2017-01-27 02:13
Closing this as it's a browser behavior working as expected.

**Closed by jelbourn** 2017-01-27 02:13 UTC
