### ISSUE TITLE
Issues with 'iconRegistry.addSvgIcon' and Universal (document is not defined)

### ISSUE THREAD

**Issue by Renader** [angular/material2#7229] opened 2017-09-21 15:50 UTC
#### Bug, feature request, or proposal:

- **BUG**

#### What is the expected behavior?

I add an icon via `iconRegistry.addSvgIcon` and it works via universal build 

#### What is the current behavior?

I have a simple Angular Universal project that uses Material 2. When I use the iconRegistry to add custom icons from svg files my application fails to render those icons via server side rendering. 

Error Message from my node console:

`Error retrieving icon: document is not defined`

app.component.ts
```
    iconRegistry.addSvgIcon(
        'angular',
        sanitizer.bypassSecurityTrustResourceUrl(`${originUrl}/assets/angular.svg`))

```

this is probably due to:

https://github.com/angular/material2/blob/1cb8907a664dd0b4b56505a3eac2b219150a6395/src/lib/icon/icon-registry.ts#L407
```

**Comment by CanKattwinkel** [comment] 2017-09-30 06:57
Duplicate of https://github.com/angular/material2/issues/6787

**Comment by crisbeto** [comment] 2017-11-16 21:50
Closing as a duplicate of #6787.

**Closed by crisbeto** 2017-11-16 21:50 UTC
Labels: needs investigation
