### ISSUE TITLE
Proposal: Add a Validator for Autocompletes to force user to pick/type one of the autocomplete results

### ISSUE THREAD

**Issue by MarkGunlogson** [angular/material2#9079] opened 2017-12-20 22:55 UTC
#### Bug, feature request, or proposal:
proposal

#### What is the use-case or motivation for changing an existing behavior?
Right now, autocompletes will show options from a datasource but there's no way to restrict the user to only picking from those options. Users can still type in whatever they want into the field. I've implemented a custom AsyncValidator that takes a list of acceptable options and marks the control invalid when the current value doesn't match one of these. It's quite easy to pass it the same datasource observable that the autocomplete listens to. It might be better to build this behavior into the control, but the Validator works really well and is simple. 

The code is currently in a commercial project but I don't think it would be hard to get permission from the owner to merge this validator into Material if you're interested.

**Comment by rafaelss95** [comment] 2017-12-20 23:00
Duplicata #3334.

**Comment by josephperrott** [comment] 2017-12-20 23:12
Closing as duplicate of #3334

**Closed by josephperrott** 2017-12-20 23:12 UTC
