### ISSUE TITLE
[MdListOption] selectChange/deselected events don't emit

### ISSUE THREAD

**Issue by Tomek91** [angular/material2#7396] opened 2017-09-28 20:44 UTC
#### Bug, feature request, or proposal:
MdListOption's output EventEmitters selectChange, and deselected do not fire when the item is selected/deselected.
I think selectChange property schould call emit method and it will solve the problem.
When can i expect the solution will be in branch?
#### What is the expected behavior?
They should activate the angular expression bound to them.

#### What is the current behavior?
The selectChange and deselected EventEmitters are never activated.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 2.0.0-beta.11

**Comment by josephperrott** [comment] 2017-09-28 21:25
Can you please provide a reproduction plunker/stackblitz of the issue?

**Comment by josephperrott** [comment] 2017-09-28 21:37
Looks like this actually will be fixed by #6901

**Closed by josephperrott** 2017-09-28 21:37 UTC

**Comment by Tomek91** [comment] 2017-09-29 07:20
ok, so my last question: in which version it will be correct?  2.0.0-beta.12 or greater? I have to work on official release Material Design.

**Comment by willshowell** [comment] 2017-09-29 15:26
@Tomek91 there are no guarantees as to when a PR will get in, but that one has already been reviewed and is merge ready, so you can expect in the next 1-2 releases.
