### ISSUE TITLE
Md-checkbox doesn't change when user has the shift key pressed on Firefox 55.0.3

### ISSUE THREAD

**Issue by StoianCatalin** [angular/material2#7773] opened 2017-10-13 15:12 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When the user maintains the shift key pressed and he clicks on md-checkbox, the checkbox changes it's ng-model.

#### What is the current behavior?
The md-checkbox doesn't change it's ng-model if user has the shift key pressed.

#### What are the steps to reproduce?
You can check the issue on official website of angular material ([https://material.angular.io/components/checkbox/examples](https://material.angular.io/components/checkbox/examples))
If you press shift and try to change the checkbox (keep in mind you must be on firefox, on the other browsers it will works) it will not change.

#### What is the use-case or motivation for changing an existing behavior?
I want to implement multiple selection using shift key like in gmail.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.5, Material 2.0.0-beta.11, Windows 10, Typescript 2.2.2,
It works fine on all browsers except Firefox(I tried just on firefox 55.0.3

#### Is there anything else we should know?
For the moment I don't think so.

**Comment by tinayuangao** [comment] 2017-11-16 19:20
Duplicate of #6232

**Closed by tinayuangao** 2017-11-16 19:20 UTC
