### ISSUE TITLE
MatAutocomplete - add option to restrict model values to selected options only.

### ISSUE THREAD

**Issue by grant77** [angular/material2#13392] opened 2018-10-02 19:16 UTC
#### Bug, feature request, or proposal:
Currently, the value of the underlying form control will be the plain text in the input even when no option has been selected.  

In most of our cases, however, we want to restrict the underlying value to selected options only.  i.e., If they type text in the input, but don't select an option, then the value should be null even though there is text in the input.

The old angularjs UI Bootstrap Typeahead had such an option called "typeahead-editable".  See https://angular-ui.github.io/bootstrap/#!#typeahead.

#### What is the expected behavior?
Have an option on the MatAutocomplete called "editable" that defaults to true.  If set to false, then the underlying FormControl value will be null unless the user has actually selected a value from the options.

#### What is the current behavior?
The underlying FormControl value is either the text in the input or the selected value in the options, depending on whether or not the user selected a value.

#### What are the steps to reproduce?
I have created a workaround.  Note: this demo defaults to the current behavior.  You must uncheck the checkbox for my workaround to kick in.

https://stackblitz.com/edit/angular-material2-issue-sacyjr

#### What is the use-case or motivation for changing an existing behavior?
Another option is needed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "^7.0.0-beta.2"

#### Is there anything else we should know?
No.

**Comment by jelbourn** [comment] 2018-10-03 16:41
Duplicate of #3334

**Closed by jelbourn** 2018-10-03 16:41 UTC
