### ISSUE TITLE
Autocomplete observable async error

### ISSUE THREAD

**Issue by ask007java** [angular/material2#3243] opened 2017-02-22 17:06 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
To handle observable

#### What is the current behavior?
Throws the following error: Cannot find a differ supporting object '[object Object]' of type 'object'

#### What are the steps to reproduce?
https://plnkr.co/edit/YQ5dLMXChxnLM7bRWMl7?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
material: 2.0.0-beta.2

**Comment by willshowell** [comment] 2017-02-22 20:45
The issue is your use of `map` here:
```
this.autoCompleteList  = this.searchCtrl.valueChanges
  .startWith(null)
  .map(txt => this.filterSearchResults(txt))
```   
Instead, you should be using [`switchMap`](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-switchMap).

To get your plunker to work, you'll need to make the `switchMap` change as well as these:

```
import 'rxjs/add/observable/from';

...

filterSearchResults(val: string){
  return val ? this.getResults(): Observable.from([]);
}
```

**Comment by kara** [comment] 2017-02-22 22:14
Thanks for looking into it, @willshowell! It does look like `switchMap` would be more appropriate here. `ngFor` + the async pipe expects the bound observable to emit iterables, not nested observables.  Closing, as it works as intended.

**Closed by kara** 2017-02-22 22:14 UTC
