### ISSUE TITLE
Datepicker calendar displays wrong month

### ISSUE THREAD

**Issue by mzernetsch** [angular/material2#4561] opened 2017-05-15 12:45 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When the datepicker calendar is opened after a date has been selected, it should show the currently selected month.

#### What is the current behavior?
When the datepicker calendar is opened after a date has been selected, it shows the wrong month. 
It seems to interpret the day as month, like when the 2. of january has been selected, it initially shows february when opened.

#### What are the steps to reproduce?
1. Open the demo page (https://material.angular.io/components/component/datepicker) in Chrome.
2. Select the 2. of january in the datepicker calendar.
3. Open the datepicker calendar again.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 2.0.0-beta.5
Chrome (58.0.3029.96 (64-bit))

#### Is there anything else we should know?
~~Firefox works flawlessy.~~ It also works in Chrome, when i input the 2. of january directly into the input field.
I would guess it has to do with german date formats (DD.MM.YYYY).

Edit: Firefox does not work flawlessy, it just always resets to the current month.

![datepicker_bug](https://cloud.githubusercontent.com/assets/22171609/26058102/a38ca626-397c-11e7-8932-fd89c47e6af4.png)

**Comment by ocarreterom** [comment] 2017-05-15 13:51
Datepicker requires the `YYYY-MM-DD` input format.

**Comment by fxck** [comment] 2017-05-15 17:38
dupe of https://github.com/angular/material2/issues/4358#issuecomment-299661961

**Comment by jelbourn** [comment] 2017-05-18 23:54
See #4358

**Closed by jelbourn** 2017-05-18 23:54 UTC
