### ISSUE TITLE
[md-select] When adjusting mat-option to a smaller size scroll goes out of sync when using key down

### ISSUE THREAD

**Issue by penrique** [angular/material2#7205] opened 2017-09-20 15:03 UTC
#### Bug, feature request, or proposal:
When applying this style, in order to have smaller <md-option> items inside <md-select>:
```
.mat-option {
	height: 28px !important;
	line-height: 28px !important;
	font-size: 14px !important;
}
```

scrolling goes out of sync and the selected option stays behind when using the arrows to navigate the list.

#### What is the expected behavior?
Always show the selected option when using the arrows to navigate the list of options

#### What is the current behavior?
Selected option loses visibility

#### What are the steps to reproduce?
```
//Some relatively big array
items = [1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10]
<md-select>
  <md-option *ngFor="let item of items" [value]="item.value">
    {{ item}}
  </md-option>
</md-select>
```
Apply style
```
.mat-option {
	height: 28px !important;
	line-height: 28px !important;
	font-size: 14px !important;
}
```

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material 2.0.0-beta.10

**Comment by willshowell** [comment] 2017-09-20 15:23
That would be due to this

https://github.com/angular/material2/blob/dcf3b270746096c1ba3bd4eb7230b920e4c42a60/src/lib/select/select.ts#L78-L81

See https://github.com/angular/material2/issues/3419

**Comment by josephperrott** [comment] 2017-09-25 17:33
Closing as duplicate of #3419

**Closed by josephperrott** 2017-09-25 17:33 UTC
