### ISSUE TITLE
Alpha 10 - Links disabled

### ISSUE THREAD

**Issue by kenp77** [angular/material2#1919] opened 2016-11-17 22:28 UTC
Hi,

When i updated to Alpha 10, most of my links are disabled by default and are gray  (login, logout, etc) ! Why that change ? or is that a bug ? 
Thanks

**Comment by jelbourn** [comment] 2016-11-18 00:03
Dupe of #1801 (already fixed in master)

**Closed by jelbourn** 2016-11-18 00:03 UTC
