### ISSUE TITLE
Autocomplete scrolling bug

### ISSUE THREAD

**Issue by anton-arsentyev** [angular/material2#3631] opened 2017-03-16 11:09 UTC
Have problems with scrolling when using acutocomplete component:

1. Open autocomplete from demo:

<img width="1060" alt="start-position" src="https://cloud.githubusercontent.com/assets/22887126/23993536/35411860-0a41-11e7-8e0f-84590be94150.png">

2. Try to scroll down:

<img width="1042" alt="scroll-down" src="https://cloud.githubusercontent.com/assets/22887126/23993534/353a86f8-0a41-11e7-8f55-babc6c179365.png">

2. Try to scroll up:

<img width="1042" alt="scroll-up" src="https://cloud.githubusercontent.com/assets/22887126/23993535/353d444c-0a41-11e7-8a8c-35ce7fe63fbb.png">

**Comment by diicar** [comment] 2017-03-16 12:15
duplicate of #3219

**Comment by jelbourn** [comment] 2017-03-16 23:15
Closing as dupe of #3219

**Closed by jelbourn** 2017-03-16 23:15 UTC
