### ISSUE TITLE
md-select with ngModel freezes browser if other errors

### ISSUE THREAD

**Issue by emin93** [angular/material2#2950] opened 2017-02-06 14:56 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Normal Angular2 unhandled error in console output

#### What is the current behavior?
Browser/tab freezes

#### What are the steps to reproduce?
Simple md-select with an ngModel and another component after the md-select which throws an error.

**WARNING: If you open the following plunker template, your browser/tab WILL FREEZE (tested in Chrome and Safari)**
Plunker template: https://embed.plnkr.co/BARX13/

**Comment by emin93** [comment] 2017-02-06 15:04
Here is the Plunker link without preview, so code inspection is possible without tab freezing: https://plnkr.co/edit/BARX13?p=info

**Comment by crisbeto** [comment] 2017-02-06 18:55
Great catch. This should be fixed in https://github.com/angular/material2/pull/2722, but I'll check if I can backport it to master as well.

**Comment by mrlund** [comment] 2017-02-07 19:08
Seems related to #2716 - I think the issue is the infinite loop caused when another error on the page prevents the MdSelect from rendering its options, and thus passing the `if (!this.options) ` clause.

```
    /**
     * Sets the select's value. Part of the ControlValueAccessor interface
     * required to integrate with Angular's core forms API.
     *
     * @param value New value to be written to the model.
     */
    MdSelect.prototype.writeValue = function (value) {
        var _this = this;
        if (!this.options) {
            // In reactive forms, writeValue() will be called synchronously before
            // the select's child options have been created. It's necessary to call
            // writeValue() again after the options have been created to ensure any
            // initial view value is set.
            Promise.resolve(null).then(function () { return _this.writeValue(value); });
            return;
        }
        this._setSelectionByValue(value);
    };
```

**Closed** 2017-02-09 19:46 UTC
Labels: has pr, P3: important
