### ISSUE TITLE
Source map paths are incorrect in published packages

### ISSUE THREAD

**Issue by gdi2290** [angular/material2#212] opened 2016-03-20 09:52 UTC
during build you need to set sourceRoot to the correct path
```
WARNING in ./~/@angular2-material/toolbar/toolbar.js
Cannot find SourceMap '../../../../components/toolbar/toolbar.js.map': Error: Cannot resolve 'file' or 'directory' ../../../../components/toolbar/toolbar.js.map in /Users/patrick/Documents/AngularClass/angular2-webpack-starter/node_modules/@angular2-material/toolbar

WARNING in ./~/@angular2-material/sidenav/sidenav.js
Cannot find SourceMap '../../../../components/sidenav/sidenav.js.map': Error: Cannot resolve 'file' or 'directory' ../../../../components/sidenav/sidenav.js.map in /Users/patrick/Documents/AngularClass/angular2-webpack-starter/node_modules/@angular2-material/sidenav

WARNING in ./~/@angular2-material/button/button.js
Cannot find SourceMap '../../../../components/button/button.js.map': Error: Cannot resolve 'file' or 'directory' ../../../../components/button/button.js.map in /Users/patrick/Documents/AngularClass/angular2-webpack-starter/node_modules/@angular2-material/button

WARNING in ./~/@angular2-material/progress-circle/progress-circle.js
Cannot find SourceMap '../../../../components/progress-circle/progress-circle.js.map': Error: Cannot resolve 'file' or 'directory' ../../../../components/progress-circle/progress-circle.js.map in /Users/patrick/Documents/AngularClass/angular2-webpack-starter/node_modules/@angular2-material/progress-circle

WARNING in ./~/@angular2-material/checkbox/checkbox.js
Cannot find SourceMap '../../../../components/checkbox/checkbox.js.map': Error: Cannot resolve 'file' or 'directory' ../../../../components/checkbox/checkbox.js.map in /Users/patrick/Documents/AngularClass/angular2-webpack-starter/node_modules/@angular2-material/checkbox

WARNING in ./~/@angular2-material/radio/radio.js
Cannot find SourceMap '../../../../components/radio/radio.js.map': Error: Cannot resolve 'file' or 'directory' ../../../../components/radio/radio.js.map in /Users/patrick/Documents/AngularClass/angular2-webpack-starter/node_modules/@angular2-material/radio

WARNING in ./~/@angular2-material/card/card.js
Cannot find SourceMap '../../../../components/card/card.js.map': Error: Cannot resolve 'file' or 'directory' ../../../../components/card/card.js.map in /Users/patrick/Documents/AngularClass/angular2-webpack-starter/node_modules/@angular2-material/card
```
`//# sourceMappingURL=../../../../components/button/button.js.map`
hsould be 
`//# sourceMappingURL=button.js.map`

**Comment by DevVersion** [comment] 2016-03-20 11:34
Maybe a duplicate of #203?

**Comment by jgutix** [comment] 2016-04-03 22:12
As of now it's apparently not possible to run any of the components through npm dependency because they are still referencing the 'components' folder, wich if installed through npm doesn't exist.
See: https://github.com/angular/material2/blob/master/src/components/button/button.ts#L28
` templateUrl: './components/button/button.html',`

This line is kept when published to npm therefore, the component is throwing:
`angular2.dev.js:23730 EXCEPTION: Error: Uncaught (in promise): Failed to load components/button/button.html`

The only workaround I have found is to build the project (this) and copy the folder `/dist/components` to my project, which I guess it's not the intended usage, right?

**Closed** 2016-04-06 20:41 UTC
Labels: P2: required
