### ISSUE TITLE
Allow use of virtual scroll with table

### ISSUE THREAD

**Issue by joedjc** [angular/material2#13221] opened 2018-09-20 16:29 UTC
The current method for creating a table (e.g. with 'dataSource' and 'matRowDef') doesn't seem compatible with virtual scrolling (e.g. using 'cdkVirtualFor').

Will it be possible to integrate virtual scrolling in an angular table for the table rows?

**What is the expected behavior?**

Virtual scroll should be compatible with the Angular Material method of creating tables

**What is the current behavior?**

Difficult to see how to incorporate virtual scroll in an Angular Material table as it doesn't use a *ngFor method

**What are the steps to reproduce?=**
**What is the use-case or motivation for changing an existing behavior?**

Allow Angular Material tables to benefit from virtual scrolling

**Which versions of Angular, Material, OS, TypeScript, browsers are affected?**
Angular CLI: 6.2.2
Node: 8.12.0
OS: win32 x64
@angular/material 7.0.0-beta.1

**Is there anything else we should know?**

**Comment by IlCallo** [comment] 2018-09-24 08:05
Following this as well.
I think Virtual Scrolling should actually be enabled by default on the table component...

**Comment by jelbourn** [comment] 2018-10-03 17:41
Duplicate of #10122

**Closed by jelbourn** 2018-10-03 17:41 UTC
