### ISSUE TITLE
bug(tab): fails to render expansion panels

### ISSUE THREAD

**Issue by merlosy** [angular/material2#8362] opened 2017-11-10 16:01 UTC
#### Bug, feature request, or proposal:

Bug with accordion / expansion panels rendered inside a tab (unselected)

#### What is the expected behavior?

accordions should be displayed correctly

#### What is the current behavior?

- panel header height is wrong
- content is displayed by default

#### What are the steps to reproduce?
http://plnkr.co/edit/vy1CjH?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Consistency

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest

**Comment by merlosy** [comment] 2017-11-10 16:50
Found a very inefficient hacky (but working) workaround:
It bascally reproduces what a proper init should do.

in component.html:
```html
<mat-expansion-panel *ngFor="let item of items">
    <mat-expansion-panel-header #panelHeaders>
        <mat-panel-title>{{item.title}}</mat-panel-title>
        <mat-panel-description>{{item.description}}</mat-panel-description>
    </mat-expansion-panel-header>

    <div #panelContents>
        <p>{{item.content}}</p>
    </div>
</mat-expansion-panel>
```

in component.ts :
```ts
    @ViewChildren('panelHeaders') panelHeaders: QueryList<MatExpansionPanelHeader>;
    @ViewChildren('panelContents') panelContents: QueryList<ElementRef>;

    ngAfterViewChecked(): void {
        this.panelHeaders.forEach(header => {
            if (header) {
                this.renderer.setStyle((<any>header)._element.nativeElement, 'height', '48px');
            }
        });
        this.panelContents.forEach(content => {
            if (content) {
                this.renderer.setStyle(content.nativeElement.parentElement.parentElement, 'visibility', 'hidden');
                this.renderer.setStyle(content.nativeElement.parentElement.parentElement, 'height', '0px');
            }
        });
    }
```

**Comment by josephperrott** [comment] 2017-11-10 16:54
Closing as duplicate of #5269

**Comment by merlosy** [comment] 2017-11-10 16:54
seems a duplicate of https://github.com/angular/material2/issues/5269

**Closed by josephperrott** 2017-11-10 16:54 UTC
