### ISSUE TITLE
md-radio-button Error: ApplicationRef.tick is called recursively

### ISSUE THREAD

**Issue by tomascharad** [angular/material2#885] opened 2016-07-19 21:01 UTC
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

An error throws when using md-radio-button
#### What is the current behavior?

If [checked] and (change) are used together, then I get the following error when clicking on the button: 

```
Error: ApplicationRef.tick is called recursively
```
#### What are the steps to reproduce?

This is my usage:

```
<md-radio-button 
  [checked]="answer.getIn(['userAnswer', 'value'])"
  (change)="actions.toggleUserAnswer(userTest.get('questionForms'), questionForm, answer)"
>
  {{answer.get('name')}}
</md-radio-button>
```

Changing (change) to (click), solves the problem.
md-checkbox, though works ok with (change)
#### Which versions of Angular, Material, OS, browsers are affected?

"@angular/common": "^2.0.0-rc.4",
"@angular2-material/core": "^2.0.0-alpha.6",
"@angular2-material/radio": "^2.0.0-alpha.6",

**Comment by jelbourn** [comment] 2016-07-26 23:19
@DevVersion is this fixed by your PR?

**Comment by DevVersion** [comment] 2016-07-27 18:36
@jelbourn I can't really reproduce this issue.

@tomascharad Can you please some code?

**Comment by tomascharad** [comment] 2016-07-27 21:05
Hi @DevVersion , I have changed my code a lot since this happened, so I cannot reproduce this issue very easy.
But I think that I was also missing the '<md-radio-group>' wrapper. Are you able to reproduce this if you do something like this:

```
<md-list-item *ngFor="let answer of questionForm.getIn(['question', 'answers'])">
  <md-radio-button
    (click)="actions.selectUserAnswer(userTest.get('questionForms'), questionForm, answer)"
    [checked]="answer.getIn(['userAnswer', 'value'])"
  >
    {{answer.get('name')}}
  </md-radio-button>
</md-list-item>
```

**Comment by DevVersion** [comment] 2016-07-28 18:11
@tomascharad Thanks for the reply. I'm currently stucking at your TypeScript code. How is the `[checked]` binding changing?

**Comment by tomascharad** [comment] 2016-07-28 18:14
@DevVersion, the selectUserAnswer triggers a change in the state of the app the 'value' attribute of the userAnswer object is changed.

**Comment by jelbourn** [comment] 2016-11-03 21:08
@tinayuangao can you reproduce?

**Comment by tinayuangao** [comment] 2016-11-03 23:29
Can't reproduce this issue.

**Closed** 2016-11-04 01:58 UTC
Labels: cannot reproduce, P3: important
