### ISSUE TITLE
mat-select-trigger is invisible if value is undefined or null

### ISSUE THREAD

**Issue by dynameis** [angular/material2#7758] opened 2017-10-13 02:53 UTC
#### Bug, feature request, or proposal:

`md-select-trigger` is invisible if value is `undefined` or `null`
when `MD_PLACEHOLDER_GLOBAL_OPTIONS` set to `{ float: 'always' }`(use to show field name)
i cant show 'All' or 'Please Select ... ' on the `md-select`

#### What is the expected behavior?

need a way to show hint text / empty option alternative text

#### What is the current behavior?

`mat-select-trigger` is invisible if value is `undefined `or `null`

#### What are the steps to reproduce?
[https://stackblitz.com/edit/angular-material2-issue-vyqfqf](https://stackblitz.com/edit/angular-material2-issue-vyqfqf?file=app%2Fapp.component.html)

#### What is the use-case or motivation for changing an existing behavior?
use select as a list filter, or form control with a hint text

**Comment by crisbeto** [comment] 2017-10-14 08:36
This is the intended behavior. Options with a value of `undefined` or `null` act as blank options which reset the value.

**Comment by willshowell** [comment] 2017-10-14 18:12
@crisbeto while this is currently intended behavior, is there any wisdom in always rendering the trigger value if `mat-select-trigger` is defined?

**Comment by mmalerba** [comment] 2017-10-14 22:24
@crisbeto But you should be able to put your own display value for when nothing is selected like `"-- Please select --"` or something.

**Comment by crisbeto** [comment] 2017-10-15 06:35
@mmalerba we used to do that initially, but the problem is knowing when to show it. We probably don't want to show it and float the label on a blank select that the user hasn't interacted with, because it makes it stand out next to other blank fields and we can't know whether a value of `undefined` came from the consumer passing in `undefined` or the control not having a value at all. I see a couple of solutions:

1. Making it so only the `undefined` options act as resets, while the `null` ones could be used as the `-- Please select --` placeholder. I can see this approach being a little confusing for users.
2. Instead of floating the label for `undefined` and `null`, we replace it with the option's label. This could be a little confusing, because it makes the options act as placeholder text, but it seems like it might be what we want.

**Comment by mmalerba** [comment] 2017-10-15 19:58
I see. I have an issue filed for input to separate the concept of label vs placeholder (https://github.com/angular/material2/issues/6194) to make it match the [latest mocks](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B8wSqcLwbhFuREg4Q0R4M3VGejA/TextFields-PressLight-01.webm). Maybe a similar sort of thing could work for the select, when the label floats we reveal the `null`/`undefined` display value.

**Comment by dynameis** [comment] 2017-10-16 03:42
Why don't we show the trigger whenever the label floats?

**Comment by jandsu** [comment] 2017-10-23 15:44
I believe that there is  similar issue when the select is _multiple_ and no value is selected: the value is then an empty array, evaluating to a falsy value just as null or undefined.... 

Please let me know if this deserves another issue or not. I wanted to remain on the less-noisy option by default.

**Comment by mmalerba** [comment] 2017-11-08 17:23
@crisbeto assigning to you since its related to the label / placeholder split

**Comment by PhilHuot** [comment] 2017-12-01 15:06
ETA on this please?

**Comment by ggranum** [comment] 2018-01-11 16:28
@crisbeto, regarding when to show it: I would strongly argue that if the value for 'trigger' is not empty, it should *always* be displayed. The developer has full control over the value provided to the trigger, and with a simple 'Placeholder will not display unless the triggerValue is empty' in the docs, it's clear enough what needs to be done. 

If that is not an option, then it should be one, via a flag. 

For a use case, I present a multi-select where 'No Selection' is allowed. I would like to display 'All', 'Partial ({{count}})' or 'None'. I cannot display None, because the selection is empty thus the (empty) placeholder is displayed instead.

**Comment by xagon** [comment] 2018-03-20 09:35
Do you guys have a workaround for this one? Any ETA?

**Comment by dynameis** [comment] 2018-06-08 02:32
now we have mat-label for this
`<mat-form-field>
      <mat-label>Status</mat-label>
      <mat-select placeholder="Please Select">...</mat-select>
    </mat-form-field>`

**Closed** 2018-06-15 04:59 UTC
Labels: P2

**Comment by akvaliya** [comment] 2019-07-08 14:27
I have used placeholder & label both. I am still facing the issue. There is a no way for user to know that list is empty. It's just looks like click is not working on select.

I don't understand why this issue is closed.

**Comment by hsinyu-chen** [comment] 2019-07-08 23:01
@akvaliya placeholder only shows when select's value is undefined or null
if the list is empty placeholder  should be displayed.

**Comment by hsinyu-chen** [comment] 2019-07-08 23:22
@akvaliya 
https://stackblitz.com/edit/angular-kzuy4y
did you set floatLabel to always ?

**Comment by akvaliya** [comment] 2019-07-09 06:48
That's not my requirements. It float on click. User should be able to know that list is empty.
