### ISSUE TITLE
Autocomplete should have an input for panelClass

### ISSUE THREAD

**Issue by asw225** [angular/material2#7021] opened 2017-09-12 18:06 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
There should be a way to style the panel created by the autocomplete component.

#### What is the current behavior?
The mat-autocomplete-panel div is added dynamically, outside the current component. The only way to specify styles would be to use a `/deep/` selector. But this only works globally, so there would be no way to style the panels of individual autocompletes.

#### What are the steps to reproduce?
Any use of mat-autocomplete.

#### What is the use-case or motivation for changing an existing behavior?
Sizing is one possible use case for specifying styles on the autocomplete panel. Current behavior will truncate the options if their widths exceed the width of the panel. Adding a style to the panel such as `min-width: fit-content` would be a desirable solution.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All versions.

#### Is there anything else we should know?
The solution should be essentially the same as #4485

**Comment by willshowell** [comment] 2017-09-13 00:19
PR has been opened https://github.com/angular/material2/pull/6618 but not yet reviewed

**Comment by Splaktar** [comment] 2017-09-16 05:47
Seems like a duplicate of https://github.com/angular/material2/issues/4196.

**Comment by crisbeto** [comment] 2017-09-19 17:50
Closing as a dupe of https://github.com/angular/material2/issues/4196.

**Closed by crisbeto** 2017-09-19 17:50 UTC
