### ISSUE TITLE
CdkDropList: Drop position is wrong after scrolling

### ISSUE THREAD

**Issue by abdulkareemnalband** [angular/material2#13823] opened 2018-10-26 06:22 UTC
#### Bug
`CdkDropList`: Drop position is wrong after scrolling
#### What is the expected behavior?
Drop target should match element under mouse pointer after scroll

#### What is the current behavior?
Scrolling is not taken into consideration while calculating drop element 

#### What are the steps to reproduce?
https://stackblitz.com/edit/cdk-drop-list-scroll

Steps: 

1.Start dragging top most element
2. Drag past container towards down
3. Wait till everything is scrolled down
4. now drag element back into container
5. Drop the element 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.0.3
Node: 10.12.0
OS: win32 x64
Angular: 7.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cli                      7.0.3
@ngtools/webpack                  7.0.3
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1

**Comment by ryanrborn** [comment] 2018-10-26 22:00
Similarly, when using cdkDragHandle, it doesn't allow for scrolling with touch.
https://cdk-drop-list-scroll-hrbp1g.stackblitz.io

**Comment by josephperrott** [comment] 2018-10-30 20:47
Closing as duplicate of #13588

**Closed by josephperrott** 2018-10-30 20:47 UTC

**Comment by abdulkareemnalband** [comment] 2018-10-31 05:33
@josephperrott 
#13588 is about implementing aUto scroll on drag outside
This issue is about after scroll drop is in wrong position

Both are related to scroll but totally different issues

Can you reopen please?
