### ISSUE TITLE
[sidenav] container styles not updated after sidenav destroy or mode change

### ISSUE THREAD

**Issue by willshowell** [angular/material2#6271] opened 2017-08-04 13:53 UTC
#### Bug, feature request, or proposal:
Regression

#### Expected
* Destroying a open sidenav should update container styles
* Modifying an open sidenav's mode should update container styles

#### Reproduction

http://plnkr.co/edit/eKqzpiCPUXGVHjknmq6F?p=preview

cc @crisbeto

**Comment by crisbeto** [comment] 2017-08-04 15:53
Probably best to wait for this until https://github.com/angular/material2/pull/6260 is merged.

**Comment by willshowell** [comment] 2017-09-13 14:29
@crisbeto, @mmalerba no major refactors are underway right now are they? I feel like this is a very important regression, especially the mode changing aspect.

**Comment by rosslavery** [comment] 2017-09-27 20:18
This one is a really painful regression, any chance of getting an expedited merge, even so we can start using it via `material2-builds`?

**Comment by mmalerba** [comment] 2017-09-27 20:22
The fix for changing modes has been merged: #6260. The fix for drawer removal is ready but not merged yet: #7060

**Comment by rosslavery** [comment] 2017-09-27 23:24
@mmalerba I don't this the fix in #6260 is working then, because switching modes only takes effect if you toggle the sidenav.

For example, if it's open and set to `side` and then you set it to `over` while it is open, it doesn't update. You need to close and re-open the sidenav for the new mode to take effect.

See Plunkr (based on issue template plunkr): http://plnkr.co/edit/ODfeJBJEece2dvMJesNj?p=preview

Should I create a new issue?

**Comment by willshowell** [comment] 2017-09-27 23:27
@rosslavery I _think_ @mmalerba meant https://github.com/angular/material2/pull/6712 for the mode changes.

**Comment by rosslavery** [comment] 2017-09-27 23:42
Ah...well then that one doesn't seem to be working either? Or is #6712 not
in beta 11?

Now I'm just confused 😛

On Sep 27, 2017 7:28 PM, "Will Howell" <notifications@github.com> wrote:

@rosslavery <https://github.com/rosslavery> I *think* @mmalerba
<https://github.com/mmalerba> meant #6712
<https://github.com/angular/material2/pull/6712> for the mode changes.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/angular/material2/issues/6271#issuecomment-332683867>,
or mute the thread

**Comment by willshowell** [comment] 2017-09-28 13:14
@rosslavery I think it just barely missed beta.11. It's also not yet available in the material2-builds yet due to some CI issue

**Closed** 2017-09-29 20:13 UTC
Labels: has pr
