### ISSUE TITLE
Can't bind to matRippleDisabled matRippleCentered matRippleTrigger

### ISSUE THREAD

**Issue by mat-luc** [angular/material2#9367] opened 2018-01-13 00:10 UTC
#### Bug, feature request, or proposal:
Bug

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by benb7760** [comment] 2018-01-13 00:16
@mat-luc duplicate of #9368

**Comment by mat-luc** [comment] 2018-01-13 00:28
Thank you so much for quick reply, so sorry, i'm a newbie so i apologize.

I imported
MatRippleModule
Everything compiled fine, but got another error,
compiler.js:485 Uncaught Error: Unexpected module 'MatRippleModule'
declared by the module 'AppModule'. Please add a
@Pipe/@Directive/@Component annotation.

**Comment by DevVersion** [comment] 2018-01-13 11:10
```ts
import {MatRippleModule} from '@angular/material';

@NgModule({
  imports: [
    // Just add this to your NgModule imports
    MatRippleModule,
  ]
})
export class MyAppModule {}
```

**Closed by DevVersion** 2018-01-13 11:10 UTC
