### ISSUE TITLE
tab doesnot get auto selected when we use multiple tab

### ISSUE THREAD

**Issue by ietuday** [angular/material2#8124] opened 2017-10-30 13:45 UTC
When I use multiple tab in md-tabgroup and inside one tab I use another tabgroup,But when i goto that tab 
1st tab doesn't get automatic selected. 

I am also attaching screenshot of my issue. Have a look ....
Please Help....... Thanks in advance.

![screenshot from 2017-10-30 19-14-18](https://user-images.githubusercontent.com/14893665/32173977-9b97cc4e-bda6-11e7-99dc-abe1cf0deab4.png)

**Comment by ietuday** [comment] 2017-10-30 14:39
I waiting guys ????????

Anyone?????

**Comment by willshowell** [comment] 2017-10-30 19:47
See https://github.com/angular/material2/issues/7274.

In the future, please follow the issue template. The team has hundreds of issues to work through, so following the defined template and providing a reproduction will drastically increase the chance your issue is prioritized. Also consider giving them more than one hour to respond..

**Comment by josephperrott** [comment] 2017-10-30 22:17
Closing as duplicate of #7274

**Closed by josephperrott** 2017-10-30 22:17 UTC
