### ISSUE TITLE
md-select: md-option for [value]="false" not displayed

### ISSUE THREAD

**Issue by AxxlForce** [angular/material2#4904] opened 2017-06-01 08:30 UTC
#### Bug, feature request, or proposal:

bug

#### What is the expected behavior?

md-option for [value]="false" should be displayed when ngModel of md-select is false and not undefined

#### What is the current behavior?

md-option is not shown

#### What are the steps to reproduce?

http://plnkr.co/edit/cyqZ32ozoxXX5seXQ7G5?p=preview

**Comment by julianobrasil** [comment] 2017-06-01 08:54
There's a similar issue: #4854.

**Comment by crisbeto** [comment] 2017-06-01 09:13
Closing as a duplicate of #4854.

**Closed by crisbeto** 2017-06-01 09:13 UTC
