### ISSUE TITLE
Demo App on material.angular.io not working

### ISSUE THREAD

**Issue by SamuelSchepp** [angular/material2#3818] opened 2017-03-28 17:07 UTC
#### Bug, feature request, or proposal:
The Demo App on material.angular.io is not working properly.

#### What is the expected behavior?
Demo App loads.

#### What is the current behavior?
- It says "Loading document..." on the page 
- StackTrace with message "Unhandled Promise rejection: Cannot read property 'document' of undefined"
- Whole Page unresponsive

#### What are the steps to reproduce?
Open https://material.angular.io/guide/material2-app

**Comment by Chan4077** [comment] 2017-03-28 23:57
Duplicate of #3388

**Comment by jelbourn** [comment] 2017-03-29 03:09
Duplicate of #3388

**Closed by jelbourn** 2017-03-29 03:09 UTC
