### ISSUE TITLE
matInput doesn't reflect type if set via component

### ISSUE THREAD

**Issue by richavyas** [angular/material2#15141] opened 2019-02-11 07:42 UTC
#### What is the expected behavior?
In case of `matInput`, if type is set as `number` using property binding, it's type should be fetched as number in component and not string. e.g. 
```
<matInput [type]="typePropetyNameInComponent">

typePropetyNameInComponent: string = "number"; 
```

doesn't work as expected while type="number" does.

#### What is the current behavior?
When type is set as `number` using property binding, it reflects the changes in template in terms of validation, but when value is fetched in component, it's type is `string` instead of `number`. The same thing works perfectly when type is directly set in template like `type="number"`

#### What are the steps to reproduce?
Here's the example of this behavior: https://stackblitz.com/edit/example-angular-material-reactive-form-vxs2mu

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.0.0
Material: 7.0.1

**Comment by macjohnny** [comment] 2019-02-11 12:03
This isn't specific to `matInput`, but it also happens for `<input [type]="typePropetyNameInComponent" formControlName="myCtrl"/>`, see this modified example: https://stackblitz.com/edit/example-angular-material-reactive-form-pjfzc1?file=app%2Fapp.component.html

This is due to the selector of `NumberValueAccessor `
`selector: 'input[type=number][formControlName],input[type=number][formControl],input[type=number][ngModel]'`
See https://github.com/angular/angular/blob/81329c85b3194d3ee1b3614b6349edc6c2fd6a60/packages/forms/src/directives/number_value_accessor.ts#L43-L53

accessing actual number values only works for 
`<input type="number" formControlName="myCtrl"/>`

This is the corresponding angular issue: https://github.com/angular/angular/issues/13243

**Comment by jelbourn** [comment] 2019-02-11 23:38
Duplicate of https://github.com/angular/angular/issues/13243

**Closed by jelbourn** 2019-02-11 23:38 UTC
