### ISSUE TITLE
The toggle method on mat-checkbox does not emit to valueChanges

### ISSUE THREAD

**Issue by gizm0bill** [angular/material2#14245] opened 2018-11-23 08:05 UTC
Bug, feature request, or proposal:
Bug

What is the expected behavior?
valueChanges should emit whenever the checkbox's value changes

What is the current behavior?
If the checkbox changes value via the toggle() method, valueChanges does not emit

What are the steps to reproduce?
https://stackblitz.com/edit/angular-uzu4zf

What is the use-case or motivation for changing an existing behavior?
Sometimes there are other places in the app that toggle a checkbox, and it's common sense

Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material 7.1.0

Is there anything else we should know?
You have a PR approved since August here https://github.com/angular/material2/pull/11902 why the heck don't you merge it?!

**Comment by crisbeto** [comment] 2018-11-23 08:08
Duplicate of https://github.com/angular/material2/issues/12369.

**Closed by crisbeto** 2018-11-23 08:08 UTC
