### ISSUE TITLE
md-grid-list Error after npm install

### ISSUE THREAD

**Issue by mareva** [angular/material2#589] opened 2016-05-31 18:42 UTC
Hello!

After installing grid-list via npm (npm install @angular2-material/grid-list --save) i can not launch my application. The errors are:

"node_modules/@angular2-material/grid-list/grid-list.d.ts(3,22): error TS2420: Class 'MdGridList' incorrectly implements interface 'AfterContentChecked'.
  Property 'ngAfterContentChecked' is missing in type 'MdGridList'.
node_modules/@angular2-material/grid-list/grid-list.d.ts(3,22): error TS2420: Class 'MdGridList' incorrectly implements interface 'OnInit'.
  Property 'ngOnInit' is missing in type 'MdGridList'."

Version:
@angular2-material/grid-list@2.0.0-alpha.4-3

**Comment by jelbourn** [comment] 2016-06-01 16:32
Dupe of #535 
(same underlying problem)

**Closed by jelbourn** 2016-06-01 16:32 UTC
