### ISSUE TITLE
Ability to use text input while menu is open

### ISSUE THREAD

**Issue by MurhafSousli** [angular/material2#12481] opened 2018-08-02 06:17 UTC
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?

Ability to use the text input while the menu is open, it should work like `<auto-complete>` but without filtering results.

#### What is the current behavior?

When `<mat-menu>` is used on `<mat-form-field>` and the menu opens it takes the focus from the input

#### What are the steps to reproduce?

[Check this stackblitz](https://stackblitz.com/edit/angular-material2-issue-mn9pxn?file=app%2Fapp.component.html)

#### What is the use-case or motivation for changing an existing behavior?

Improves user experience, adds more control over the menu and its behavior

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular: 6.1.0
Material: 6.4.0

#### Is there anything else we should know?

#9857 is some how related but not the same

**Comment by josephperrott** [comment] 2018-08-06 16:01
Closing as duplicate of #9857

**Closed by josephperrott** 2018-08-06 16:01 UTC
Labels: P4, feature
