### ISSUE TITLE
CdkScrollable in <mat-list>

### ISSUE THREAD

**Issue by ajonp** [angular/material2#11042] opened 2018-04-27 06:41 UTC
#### Bug, feature request, or proposal:
Can CdkScrollable be added to <mat-list>? CdkScrollable shows as undefined now.

#### What is the expected behavior?
The scroll details are presented.

#### What is the current behavior?
Observable sends undefined.

#### What are the steps to reproduce?
https://angular-material2-issue-oyggnp.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?
Allowing for Firestore infinite scroll
https://angularfirebase.com/lessons/infinite-scroll-firestore-angular/

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All?
Tested on 5.0-6.0rc

#### Is there anything else we should know?
An example of anything working with this would be great. The only thing I have seen is the mat-drawer.

**Comment by josephperrott** [comment] 2018-05-02 15:37
Closing as there does not seem to be enough information for us to triage the issue.  If you are still seeing an issue, please open another issue with more information about the issue you are seeing.

**Closed by josephperrott** 2018-05-02 15:37 UTC

**Comment by ajonp** [comment] 2018-05-02 23:51
There isn't enough detail in the stackblitz? It literally throws undefined.

**Comment by josephperrott** [comment] 2018-05-03 15:42
Sorry about that, when I initially loaded the stackblitz I did not see any modifications to the base stackblitz we provide.

After looking at your stackblitz it is working as intended.  It looks like the issue you are running into is that there is no `register`-ed `cdkScrollable` element in the component.

The `scrolled` method returns an observable "that emits an event whenever any of the registered Scrollable references (or window, document, or body) fire a scrolled event." [link to scrolling docs](https://material.angular.io/cdk/scrolling/api)

Because there are no elements registered as `CdkScrollable`, each emitted value is sent with `void`.
