### ISSUE TITLE
md-select issue : md-option with [value]="0" will never be selected

### ISSUE THREAD

**Issue by toxnico** [angular/material2#4929] opened 2017-06-02 08:57 UTC
#### Bug, feature request, or proposal:
Bug.
<md-option [value]="0"> will never be selected if [(ngModel)] value == 0.

This behaviour is probably caused by [this line](https://github.com/angular/material2/blob/master/src/lib/select/select.ts#L585). Options with a falsy value are ignored.

#### What is the expected behavior?
md-option with value==0 must be selectable.

#### What is the current behavior?
The option with [value]==0 cannot be selected.

#### What are the steps to reproduce?
http://plnkr.co/edit/bfm4WzFkdjODhaorW4Dw?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Allow any value to be associated with md-option.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "^4.0.3",
"@angular/material": "^2.0.0-beta.1",
"typescript": "^2.0.10",

**Comment by crisbeto** [comment] 2017-06-02 09:19
Closing as a duplicate of https://github.com/angular/material2/issues/4854.

**Closed by crisbeto** 2017-06-02 09:19 UTC

**Comment by toxnico** [comment] 2017-06-02 09:31
Oh sorry... I searched however :)
