### ISSUE TITLE
Remove `transform: translate3d(0,0,0);`

### ISSUE THREAD

**Issue by robindijkhof** [angular/material2#4873] opened 2017-05-29 21:03 UTC
#### Proposal:
Remove `transform: translate3d(0,0,0);` from everywhere

#### What is the expected behavior?
`position: fixed` should work.

#### What is the current behavior?
`position: fixed` behaves like `absolute`

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
https://plnkr.co/edit/uWzvxBSWlMari58qGdZ0?p=preview scroll the page. As you can see the button won't stay in the same place. Opening the console and removing `transform: translate3d(0,0,0);` from the underlaying items resolves the problem.

#### What is the use-case or motivation for changing an existing behavior?
Make `position: fixed` work

**Comment by fxck** [comment] 2017-05-30 05:35
dupe of https://github.com/angular/material2/issues/998

**Comment by josephperrott** [comment] 2017-09-25 23:23
Closed per: #998

**Closed by josephperrott** 2017-09-25 23:23 UTC
