### ISSUE TITLE
mat-input-placeholder-wrapper doesn't align with mat-select-placeholder

### ISSUE THREAD

**Issue by frankspin89** [angular/material2#3429] opened 2017-03-04 07:06 UTC
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

![expected](https://cloud.githubusercontent.com/assets/4480104/23576879/09050dc2-00b1-11e7-96f5-b57004029943.png)

Expected that both placeholders would align vertical with each other in floating state.

#### What is the current behavior?

![current](https://cloud.githubusercontent.com/assets/4480104/23576883/10696c02-00b1-11e7-9305-71fd0ff95c59.png)

There is a little miss alignment in the vertical spacing.

#### What is the use-case or motivation for changing an existing behavior?

Styling should be consistent. 

#### Which versions of Angular, Material, OS, browsers are affected?

OS: macOs Sierra
Chrome: Version 56.0.2924.87 (64-bit)
Angular: 4.0.0-rc.2
Material: 2.0.0-beta.2

#### Is there anything else we should know?

A possible solution is changing the .mat-input-placeholder-wrapper top property.

Current
```
.mat-input-placeholder-wrapper {
  top: -1em;
}
``` 

```
.mat-input-placeholder-wrapper {
  top: -.7em;
}
```

**Comment by kara** [comment] 2017-03-04 22:47
Looks like a dupe of https://github.com/angular/material2/issues/2124

**Closed by kara** 2017-03-04 22:47 UTC
