### ISSUE TITLE
Md-Sidenav open mode bootstrap animation

### ISSUE THREAD

**Issue by jsorr2** [angular/material2#6865] opened 2017-09-06 06:34 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When using universal, the sidenav (in side mode) will be rendered already open in the initial page load, and then when the app bootstraps, it will stay open.

#### What is the current behavior?
The initial pre-rendered page loads with the sidenav closed, and then when the app boostraps, the sidenav animates open.

#### What is the use-case or motivation for changing an existing behavior?
In beta 8, it worked perfectly. The initial pre-rendered html file aligned with the bootstrap re-render.
Now, the page loads with the sidenav closed, and after a number of seconds later (when the app bootstraps) the sidenav suddenly animates open, which is quite distracting.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.3, material 2.0.0-beta8, windows 10

**Comment by CaerusKaru** [comment] 2017-09-17 08:57
I'd like to believe that the culprit here is a882546debb92bd9cf52937bf73eee8548d61bf0, which was for some reason left out of the CHANGELOG (this would also correspond to your timing that this worked in beta-8 and not beta-10 or beta-11).

Universal rendering doesn't support Angular Animations (yet), since it can't affect the `document` object (see https://github.com/angular/angular/issues/15098 and https://github.com/angular/angular/issues/14784). It looks like the beta-8 method relied exclusively on CSS-based animations, which would've rendered just fine.

cc @crisbeto @jelbourn Thoughts? (I.e. is it worth the tradeoff in perf/is there a workaround, and if not, is it worth the impact on UX for non-JS users who will never see the sidenav open?)

**Comment by CaerusKaru** [comment] 2017-09-17 22:10
Might be duplicate of #7007, resolved by #7129

**Comment by CaerusKaru** [comment] 2017-09-30 01:53
The problem here is actually deeper than anticipated. See here:

https://github.com/angular/material2/blob/20a23f16e8ac1ced29172709cc837fa500b6377b/src/lib/sidenav/drawer.ts#L347-L350

https://github.com/angular/material2/blob/20a23f16e8ac1ced29172709cc837fa500b6377b/src/lib/sidenav/drawer.ts#L553-L585

Since the margins for the `mat-drawer-content` depend on `nativeElement`, Universal can't possibly predict the width, leaving it static at 0, and populated on bootstrap on the client. The "animation" is really just the transition CSS firing once the width is populated.

@mmalerba Is there a possible refactoring we can do here, maybe by searching the element tree for CSS width if none other is available?

**Comment by CaerusKaru** [comment] 2017-10-15 00:22
As documented in #7795, there's also an issue with `transform: translate3d(0,0,0)` not being applied correctly.

**Comment by CaerusKaru** [comment] 2017-10-15 00:27
There's also currently an issue open https://github.com/angular/angular/issues/19235 that is tracking an issue with `style.property` not being applied correctly if the property name is in camelCase (in drawer, this is `marginRight` and `marginLeft`).

**Comment by mmalerba** [comment] 2017-11-28 23:55
should be fixed by #8488

**Comment by CaerusKaru** [comment] 2017-12-05 18:14
@mmalerba Issue not resolved by #8488

**Closed** 2017-12-05 22:49 UTC
Labels: has pr, P3: important, regression

**Comment by CaerusKaru** [comment] 2017-12-06 00:22
@crisbeto Still not fixed

**Comment by agustinhaller** [comment] 2018-03-13 13:42
Hi, any updates on this? In my case it was working OK with Angular `5.0.2` and material `5.0.0.rc0` but stop working when updated to Angular `5.2.8` and material `5.2.4`
