### ISSUE TITLE
Material theming support for Angular Material

### ISSUE THREAD

**Issue by geoffnewell** [angular/material2#11510] opened 2018-05-25 08:10 UTC
#### Bug, feature request, or proposal:
As announced at Google IO '18: https://material.io/design/material-theming/#material-theming
Is there a timeline (or not) when this level of theming might be applied to Angular Material components?

#### What is the expected behavior?
Enhanced styling support across all Angular Material components.

#### What is the current behavior?
Material theming is currently limited to pre-existing Material behaviour.

#### What is the use-case or motivation for changing an existing behavior?
Will enable users to build more attractive apps with enhanced styling. Other benefit will be that AngularMaterial will continue to track the Material feature roadmap.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All.

**Comment by pfeigl** [comment] 2018-05-27 11:32
There have been quite some requests on this topic in here already, please use the search functionality.

See #11401, #11222, #11039

**Comment by josephperrott** [comment] 2018-05-31 20:40
Closing as duplicate of #11039

**Closed by josephperrott** 2018-05-31 20:40 UTC
