### ISSUE TITLE
input type date has a different height than every other input types

### ISSUE THREAD

**Issue by pwhissell** [angular/material2#9718] opened 2018-01-31 18:46 UTC
#### Bug, feature request, or proposal:
minor visual bug

#### What is the expected behavior?
I expect an input of type "date" to have the same height as any other input

#### What is the current behavior?
When multiple inputs are inline in a flex container, they all have a height of 18px except the input who's type is "date". Forcing a height of 18px on the input tag makes it the right size but the arrow buttons are 24px high and therefore overflow the input.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-xbvsqq?file=app/input-overview-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 5.1.1 
Windows 10
chrome 63

**Comment by donroyco** [comment] 2018-01-31 19:17
Duplicate of #8012

**Closed** 2018-02-09 17:37 UTC
