### ISSUE TITLE
Plunker examples no longer working

### ISSUE THREAD

**Issue by GregKass** [angular/material2#8418] opened 2017-11-13 16:30 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Plunker links should work

#### What is the current behavior?
Plunker links are not working at the moment

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>
Go to materials page and click plunker link example (Edit in Plunker). I've mostly been looking at tables.

#### Is there anything else we should know?
I updated the sorting table example in this plunker:

https://plnkr.co/edit/AVeUu5xiwt4tZayv8MP5?p=preview

where I edited ```systemjs.config.js``` so that the plunker works again.  I also provided the same change to this Real-Time Progress Bar example and got it working:

https://plnkr.co/edit/V1nTxG?p=preview

I believe this file update should get most of the plunkers working again, but some examples may require some extra file mappings.

(I could submit a PR with links to fixes for each of the examples, but then I would have ownership of the edited plunkers.)

**Comment by willshowell** [comment] 2017-11-13 18:46
The plunkers from the docs site are [generated](https://github.com/angular/material.angular.io/tree/master/src/app/shared/plunker). I think a PR there would be very welcome, and you don't need to worry about plunker ownership, since they are written by the docs site itself.

**Comment by GregKass** [comment] 2017-11-14 08:01
I checked out the updates in:

https://github.com/angular/material.angular.io/blob/master/src/assets/plunker/systemjs.config.js

and it contains all of the necessary file updates. Looks like it just needs to be published.

**Comment by pabloxn** [comment] 2017-11-15 04:38
The plunkers with the moment adaptor are also not working.

**Comment by lnaie** [comment] 2017-11-16 12:15
Aslo Datepicker with custom formats. Important!

**Comment by neonguru** [comment] 2017-11-16 15:36
I think the problem is it still uses the HttpModule:
import {HttpModule} from '@angular/http';

I removed it and the import from one plunker and it started working.

**Comment by amcdnl** [comment] 2017-11-19 18:54
We are moving to stackblitz and it removes system.js so this might not even be an issue very soon.

**Comment by Misiu** [comment] 2017-11-22 10:28
@amcdnl so all examples from https://material.angular.io/ will be migrated from Plunker to Stackblitz?

**Comment by Teamop** [comment] 2017-11-27 06:59
Hi @amcdnl , I had a PR about this issue, already 18 days ago. angular/material.angular.io#325

**Closed** 2017-12-02 16:48 UTC
Labels: P2: required
