### ISSUE TITLE
The library breaks webpack build

### ISSUE THREAD

**Issue by katzz0** [angular/material2#3596] opened 2017-03-14 16:17 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Webpack should build the app

#### What is the current behavior?
```
ap\lib\source-node.js:95
          var code = nextLine.substr(0, mapping.generatedColumn -
                             ^

TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (C:\work\git\portal\projects\Portal.UI\node_modules\source-map\lib\source-node.js:95:30)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (C:\work\git\portal\projects\Portal.UI\node_modules\source-map\lib\source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (C:\work\git\portal\projects\Portal.UI\node_modules\source-map\lib\source-node.js:80:24)
    at SourceMapSource.node (C:\work\git\portal\projects\Portal.UI\node_modules\webpack-sources\lib\SourceMapSource.js:42:20)
    at ReplaceSource.node (C:\work\git\portal\projects\Portal.UI\node_modules\webpack-sources\lib\ReplaceSource.js:69:29)
    at CachedSource.node (C:\work\git\portal\projects\Portal.UI\node_modules\webpack-sources\lib\CachedSource.js:12:23)
    at C:\work\git\portal\projects\Portal.UI\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (C:\work\git\portal\projects\Portal.UI\node_modules\webpack-sources\lib\ConcatSource.js:39:60)
    at C:\work\git\portal\projects\Portal.UI\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (C:\work\git\portal\projects\Portal.UI\node_modules\webpack-sources\lib\ConcatSource.js:39:60)
    at C:\work\git\portal\projects\Portal.UI\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (C:\work\git\portal\projects\Portal.UI\node_modules\webpack-sources\lib\ConcatSource.js:39:60)
    at C:\work\git\portal\projects\Portal.UI\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (C:\work\git\portal\projects\Portal.UI\node_modules\webpack-sources\lib\ConcatSource.js:39:60)
    at ConcatSource.proto.sourceAndMap (C:\work\git\portal\projects\Portal.UI\node_modules\webpack-sources\lib\SourceAndMapMixin.js:28:18)
    at CachedSource.sourceAndMap (C:\work\git\portal\projects\Portal.UI\node_modules\webpack-sources\lib\CachedSource.js:51:28)
    at Compilation.<anonymous> (C:\work\git\portal\projects\Portal.UI\node_modules\webpack\lib\SourceMapDevToolPlugin.js:57:32)
```

#### What are the steps to reproduce?
I use webpack with source map loader so it doesn't work. I added @angular/materia as dependency and added `import {MaterialModule} from '@angular/material';` into one of my modules.

#### Which versions of Angular, Material, OS, browsers are affected?
angular 2.4.1
material 2.0.0-beta.2
Windows 7
browser - all

#### Is there anything else we should know?
no

**Comment by jelbourn** [comment] 2017-03-14 22:02
This seems unlikely to be caused by Material itself, especially since we haven't received any other reports of a similar issue since the last release. Can you share more information about your webpack setup? 

cc @DevVersion

**Comment by jelbourn** [comment] 2017-03-16 23:20
Closing this since we can't reproduce. Feel free to open a new issue with more information.

**Closed by jelbourn** 2017-03-16 23:20 UTC
