### ISSUE TITLE
Illegal state: Could not load the summary for directive CdkObserveContent in node_modules/@angular/cdk/observers/typings/index.d.ts.

### ISSUE THREAD

**Issue by TitanNano** [angular/material2#8558] opened 2017-11-20 18:12 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The angular compiler should be able to find everything he needs

#### What is the current behavior?
Some summary meta data is missing:
```
Illegal state: Could not load the summary for directive CdkObserveContent in node_modules/@angular/cdk/observers/typings/index.d.ts
```

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cdk: 5.0.0-rc0
@angular/compiler-cli: 5.0.2

**Comment by jelbourn** [comment] 2017-11-20 21:51
Duplicate of #8070

Feel free to open a new issue if you can provide a reproduction

**Closed by jelbourn** 2017-11-20 21:51 UTC
