### ISSUE TITLE
Issue in File Upload

### ISSUE THREAD

**Issue by munjalpandya** [angular/material2#7815] opened 2017-10-16 04:04 UTC
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected? Angular 4, Material 2.0.0-beta.10

Currently, I think material doesn't have any support for File upload. How to implement file upload control along with other mdInput controls?

**Comment by mackelito** [comment] 2017-10-16 05:53
https://github.com/angular/material2/issues/3262

**Comment by merlosy** [comment] 2017-10-16 15:22
I believe it is not on the roadmap..

Though, based on the [new guidelines](https://material.angular.io/guide/creating-a-custom-form-field-control), I updated my gist with **custom file input** working with Angular 4.4.x + Material Beta 12

https://gist.github.com/merlosy/ab33dd7edaacfd92d6c9a5daea0a1240

I'll set up a plunker and drop the link on the [gist readme](https://gist.github.com/merlosy/ab33dd7edaacfd92d6c9a5daea0a1240#file-readme-md)

**Comment by josephperrott** [comment] 2017-10-16 15:52
Closing as duplicate of #7815

**Closed by josephperrott** 2017-10-16 15:52 UTC

**Comment by mackelito** [comment] 2017-10-17 06:37
@josephperrott just a note but you closed it as a dupe of itself ;)

**Comment by josephperrott** [comment] 2017-10-17 14:51
Whoops, my bad, meant as a duplicate of #3262

**Comment by munjalpandya** [comment] 2017-10-19 03:29
@merlosy , custom control made by you seems to be really good. Will be checking the same in my project.

**Comment by munjalpandya** [comment] 2017-10-19 07:38
[package.zip](https://github.com/angular/material2/files/1397485/package.zip)


@merlosy I think you have updated the material version to 2.0.0-beta.12. I was having 2.0.0-beta.10, but when I tried to update the version to 2.0.0-beta.11 and follow the steps to make required changes, I am getting error.

Do you have any idea about the same?

Please find my package.json in attachment.
