### ISSUE TITLE
[Mat-Menu] Feature Request : add mat-menu-trigger to overlay when [overlapTrigger]="false"

### ISSUE THREAD

**Issue by seedy** [angular/material2#9943] opened 2018-02-14 10:21 UTC
#### Bug, feature request, or proposal:
mat-menu can be configured not to overlap its trigger.
The trigger though is no more accessible because of the backdrop added when opening a menu.
Material guidelines tell the trigger should allow us to close the menu as well as a click out of it.
Therefore I'd recommend making the trigger button accessible when backdrop is active.
#### What is the expected behavior?
Trigger should be accessible if menu is not overlapping it.

#### What is the current behavior?
Backdrop disables access to anything else than the menu, even if it doesn't overlap the trigger.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-bcfxwg?file=app%2Fmenu-overview-example.html

#### What is the use-case or motivation for changing an existing behavior?
Dismiss a menu by tapping outside of the menu, or by tapping the emitting button (if visible). (https://material.io/guidelines/components/menus.html#menus-behavior)

#### Is there anything else we should know?

**Comment by josephperrott** [comment] 2018-02-15 22:50
Closing as duplicate of #9938

**Closed by josephperrott** 2018-02-15 22:50 UTC
