### ISSUE TITLE
cdkDragDrop drop zone

### ISSUE THREAD

**Issue by bechtold** [angular/material2#14149] opened 2018-11-15 09:48 UTC
#### Bug, feature request, or proposal:
If I'm not completely mistaken there is currently no such thing as a drop zone other than dropList. But these automatically order the elements. Since I want to swap two elements once there are dropped on each other I don't want them to be sorted.
When I drop the dragged element somewhere else on the page it returns to its original position.
I tried with one dropList but it will always move all elements in the list, but only the dragged and the dropped elements should be affected.
So I tried with one drop zone per draggable element to get the drop event and not affect all elements. Still, the hovered element moves away.

#### What is the expected behavior?
Hover one element over the other and the element that is hovered over stays in place. When I get the dropped event I can swap both elements.

#### What is the current behavior?
The element that is hovered over moves away to make room for the dragged element.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-cdk-drop

#### What is the use-case or motivation for changing an existing behavior?
I want to have multiple tiles on the page that can be swapped by hovering them over each other. I'm trying to create an image puzzle where randomized tiles can be sorted.
Basically, I want to achieve what has been done here in the sortable grid example: http://james2doyle.github.io/zepto-dragswap/

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.0.6
Node: 8.11.2
OS: darwin x64
Angular: 7.0.3
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.6
@angular-devkit/build-angular     0.10.6
@angular-devkit/build-optimizer   0.10.6
@angular-devkit/build-webpack     0.10.6
@angular-devkit/core              7.0.6
@angular-devkit/schematics        7.0.6
@angular/animations               7.0.2
@angular/cdk                      7.0.4
@angular/cli                      7.0.6
@angular/material                 7.0.4
@ngtools/webpack                  7.0.6
@schematics/angular               7.0.6
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

**Comment by crisbeto** [comment] 2018-11-18 17:45
Duplicate of https://github.com/angular/material2/issues/13340.

**Closed by crisbeto** 2018-11-18 17:45 UTC

**Comment by uareurapid** [comment] 2018-11-21 12:44
hi @crisbeto 
why is this closed? is there such thing as a drop zone already? looking at the code it doesn't seem to. 
also, is there a way to know the index in which a new element is entering a drop list? (on cdkDropListEnter)
so...to know if i'm dragging the element to position 1, 3, etc of the drop list?  Seems this is currently not possible either (the sort event doesn't work for this sadly ), and the "copy/move" feature referenced on duplicates  works on the drop event only.
thanks in advance
