### ISSUE TITLE
Sidenav: Screen reader focuses items below overlay when sidenav is open

### ISSUE THREAD

**Issue by kara** [angular/material2#592] opened 2016-05-31 22:18 UTC
Currently, when you open the sidenav and try to close it by clicking on the overlay, you end up focusing the items below the overlay.  Sidenav isn't close-able.

Probably will depend on the larger focus-trapping solution we are planning.

**Comment by jelbourn** [comment] 2016-06-01 16:32
Dupe of #50

**Closed by jelbourn** 2016-06-01 16:32 UTC
Labels: a11y
