### ISSUE TITLE
Table component sample code compiler error

### ISSUE THREAD

**Issue by tianyu94** [angular/material2#15664] opened 2019-03-30 14:35 UTC
#### What is the expected behavior?
none complier errors.

#### What is the current behavior?
official: https://material.angular.io/components/table/overview

**line: 16**

```typescript
  @ViewChild(MatPaginator, {static: true}) paginator: MatPaginator;
```

**errors:**

`Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.`

#### What are the steps to reproduce?

https://stackblitz.com/angular/egkyqnreoxr?file=app%2Ftable-pagination-example.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- angular 7.2.11
- material 7.3.6
- MacOS 10.13.6
- TypeScript 3.2.2
- IDE IntelliJ Idea 2019.1

#### Is there anything else we should know?

none

**Comment by crisbeto** [comment] 2019-03-31 09:20
Duplicate of https://github.com/angular/material2/issues/15632.

**Closed by crisbeto** 2019-03-31 09:20 UTC

**Comment by Eberzinho** [comment] 2019-06-10 07:26
It only works like this:

@ViewChild(MatPaginator) paginator: MatPaginator;

**Comment by jaideepghosh** [comment] 2019-06-10 10:45
PR 30948 should be the solution for your problem.
