### ISSUE TITLE
Drag Zone without Drop Zone

### ISSUE THREAD

**Issue by ReactionCode** [angular/material2#14537] opened 2018-12-15 21:35 UTC
### Use-Case
I have a project to create a WYSIWYG application, so I expected to achieve with the cdkDragDrop an static zone to only Drag elements to another Drop zone.

### Issue
If I'm not wrong, with the actual cdkDragDrop 7.1.1 is not possible, because a Drag Zone should have to be nested into a DropList, this makes always you drag an element, the element is reordering inside the Drag zone list when I expect an static zone.

### Solution
Would be great some of these solutions:
- Create Drag Zones whithout a DropList
- Disable Drop intearction on DropList like "cdkDragDisable" disables Drag interactions
- A new feature to make DropList static with only Drag actions

If someone knows how to do this with cdkDragDrop 7.1.1 let me know.

**Comment by crisbeto** [comment] 2018-12-16 08:39
Duplicate of https://github.com/angular/material2/issues/13340.

**Closed by crisbeto** 2018-12-16 08:39 UTC
