### ISSUE TITLE
https://material.angular.io/ is down

### ISSUE THREAD

**Issue by deanapeterson** [angular/material2#11965] opened 2018-06-28 14:35 UTC
https://material.angular.io/ is down.

**Comment by mtrdp642** [comment] 2018-06-28 16:17
The site is up - [here's](https://github.com/angular/material.angular.io/issues/436#issuecomment-390924245) a workaround for getting it to load in Chrome.

**Comment by sircuri** [comment] 2018-06-28 16:20
That is not the issue. I'm getting 404 errors. Solution suggested from that other ticket is not going to fix that:

https://material.angular.io/runtime.6afe30102d8fe7337431.js (404)

**Comment by ThunderRoid** [comment] 2018-06-28 16:37
Happened to me thrice this week.

**Comment by crisbeto** [comment] 2018-06-29 19:18
Closing as a duplicate of #11745. Usually this can also be fixed by clearing your cache.

**Closed by crisbeto** 2018-06-29 19:18 UTC

**Comment by 24hours** [comment] 2018-07-12 02:57
This issue seems to caused by cached index.html / service worker. imho this is bad bad user experience. We added no-cache flag on index.html, forcing refresh on client when 404 on chunk.js file.
