### ISSUE TITLE
feat(datepicker): add setting to define the first day of a week

### ISSUE THREAD

**Issue by mzernetsch** [angular/material2#7197] opened 2017-09-20 08:08 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
The developer should be able to set the first day of a week in a datepicker.

#### What is the current behavior?
The first day of the week is always sunday.

#### What is the use-case or motivation for changing an existing behavior?
In north america it is common that a week starts with sunday, but for example in germany (and i guess most european countries) the first day of the week is usually considered monday. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 2.0.0-beta.10

#### Is there anything else we should know?
First day of the week in ISO 8601 is also defined to be monday.

**Comment by julianobrasil** [comment] 2017-09-20 09:24
You can do it by creating your custom date adapter. If there's no special needs, just extends the Material NativeDateAdapter and overide the **`getFirstDayOfWeek()`** function. It must return the number of the first day of the week (0 - Sunday, 1 - Monday etc).

Here is a plunk for brazilian portuguese, setting Tuesday as the first day of the week: https://plnkr.co/edit/9hEJki?p=preview

```js
getFirstDayOfWeek(): number {
   return 2;
  }
```

**Comment by mzernetsch** [comment] 2017-09-20 12:03
Thank you, i didn't expected it to be part of the date adapter so i didn't searched there. 

Currently in the NativeDateAdapter implementation it defaults to 0 because it can't be defined using native JS dates:
```js
getFirstDayOfWeek(): number {
  // We can't tell using native JS Date what the first day of the week is, we default to Sunday.
  return 0;
}
```

I think setting the first day of a week is part of i18n. So maybe there could be a property for that on the `MdDatepickerIntl` service?

**Comment by josephperrott** [comment] 2017-09-25 18:11
Closing, working as intended to use the `DateAdapter` as mentioned

**Closed by josephperrott** 2017-09-25 18:11 UTC
