### ISSUE TITLE
Expanded panel arrow is not set correctly when expanded is true

### ISSUE THREAD

**Issue by VitoAlbano** [angular/material2#11582] opened 2018-05-30 16:29 UTC
#### Bug, feature request, or proposal:
Using the expanded panel into a material tab and setting 'expanded' attribute to 'true' shows the panel open for both tab but for the second one the expanded panel arrow is wrongly set.

#### What is the expected behavior?
Both the panel opened by default in a tab should behave in the same way

#### What is the current behavior?
The arrow is in 'closed' state when the second tab is clicked.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
i've created a simple case here : https://angular-npcth3.stackblitz.io
Click on the second tab and notice that the arrow is closed but the content of the expansion panel is showed.

#### Is there anything else we should know?
https://stackblitz.com/edit/angular-npcth3

**Comment by josephperrott** [comment] 2018-05-30 16:40
Closing as the issue you are seeing is actually caused by animations not running on the hidden tab before it is shown.  Once interacted with the expansion panel will go to the correct state.  To use the expansion panels inside of the tab you should lazy load the tab content.

```html
<mat-tab-group>
  <mat-tab label="Tab 1">
    <ng-template matTabContent>
      <mat-expansion-panel expanded="true">
        <mat-expansion-panel-header>Panel 1</mat-expansion-panel-header>
        <p>I'm visible because I am open</p>
      </mat-expansion-panel>
    </ng-template>
  </mat-tab>
  <mat-tab label="Tab 2">
    <ng-template matTabContent>
  <mat-tab label="Tab 1">
    <ng-template matTabContent>
      <mat-expansion-panel expanded="true">
        <mat-expansion-panel-header>Panel 2</mat-expansion-panel-header>
        <p>I'm visible because I am open</p>
      </mat-expansion-panel>
    </ng-template>
  </mat-tab>    </ng-template>
  </mat-tab>
</mat-tab-group>
```

**Closed by josephperrott** 2018-05-30 16:40 UTC
