### ISSUE TITLE
mat-accordion nested with mat-tab

### ISSUE THREAD

**Issue by alfbrizz** [angular/material2#9086] opened 2017-12-21 11:47 UTC
#### Bug, feature request, or proposal:

Bug?
when i insert <mat-tab-group> in  <mat-accordion> nested in another <mat-accordion> the inkbar and others  are always visible when the container accordion of <mat-tab-group> is closed...

Another problem in the previous configuration is that the contents of the first card are sometimes not shown when switching from one accordion to another and from one card to another. I inspected and saw that the style does not change ... transform: translate3d (-100%, 0px, 0px);
this problem does not easily reproduce on stackblitz.

With Material2 v. 2.0.0-beta.12 is OK
#### What is the expected behavior? 
Not visible when the accordion is closed

#### What is the current behavior?
inkbar and other components remain visible

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-wi2xqb

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.x.x
Material 5.x.x

**Comment by josephperrott** [comment] 2017-12-21 16:45
Closing as duplicate of #5269

**Closed by josephperrott** 2017-12-21 16:45 UTC
