### ISSUE TITLE
Feature: Shows asterisk automatically when input has RequiredValidator in ReactiveForms

### ISSUE THREAD

**Issue by dev054** [angular/material2#4865] opened 2017-05-29 14:09 UTC
#### Bug, feature request, or proposal:
Feature Request.

#### What is the expected behavior?
Actually there's an `property` in `input` called `required`. I'm wondering if is there any chance to have it built-in in reactive forms? I mean, if an input has the `Validators.required` it will automatically shows the `asterisk` indicating that's *required*. To disallow this behavior people could use `[hideRequiredMarker
]="true"`.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta.6

#### Is there anything else we should know?
It would help a lot since you wouldn't need to put `Validators.required` in component and also `[required]` in template.

**Comment by willshowell** [comment] 2017-05-29 17:06
Looks like dupe of https://github.com/angular/material2/issues/2574

**Comment by dev054** [comment] 2017-05-29 22:01
Woops, I didn't said this issue. Thanks @willshowell

**Closed** 2017-05-29 22:01 UTC
