### ISSUE TITLE
mat-sidenav-content right margin does not get updated resulting in content overlap

### ISSUE THREAD

**Issue by craftyInstigator** [angular/material2#7614] opened 2017-10-07 06:36 UTC
#### Bug, feature request, or proposal:
mat-sidenav-content right margin does not get updated when the side nav content size changes. This causes the mat-sidenav align="end" mode="side" to overlap the sidenav content.

#### What is the expected behavior?
mat-sidenav sits to the right of mat-sidenav-content without overlap

#### What is the current behavior?
mat-sidenav overlaps mat-sidenav-content

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-vlq5sr

#### What is the use-case or motivation for changing an existing behavior?
Sidenav content can change for a variety of reasons. In my case the sidenav content is responsive, and change based on window resize. The timing of the responsive content sizing calculation of flex layouts preseeds the calculation of sidenav margins resulting in overlap bug.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta.12

**Comment by sambaptista** [comment] 2017-10-29 15:41
Dup of #6743 ?

**Comment by josephperrott** [comment] 2017-10-31 18:33
closing as duplicate of #6743

**Closed by josephperrott** 2017-10-31 18:33 UTC
