### ISSUE TITLE
Bug(sidenav and button) Wrong initial hover effect on a button in the sidenav

### ISSUE THREAD

**Issue by HristoEftimov** [angular/material2#3282] opened 2017-02-24 11:14 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When sidenav opens all navigation buttons have be without any hover effect

#### What is the current behavior?
When sidenav opens and hover somewhere on the sidenav makes the first navigation button with hover effect.

#### What are the steps to reproduce?
Plunker: https://plnkr.co/edit/pNv9Bx4o1qQSF2bpOqyM?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/material: 2.0.0-beta.1
Google Chrome Version 56.0.2924.87 (64-bit)
Firefox Version 51.0.1 (64-bit)

**Comment by joh04667** [comment] 2017-02-24 17:01
This seems to be directly related to the `md-button` directive. The first sidenav element with an `md-button` always gets stuck in the hovered state when any `md-button` in the sidenav is hovered. 

As a workaround, add an element with `md-button` with `height: 0;` or something similar to the beginning of the sidenav. 

Plunker example: https://plnkr.co/edit/i572Ask8Lxlj8uKffFkO?p=preview

(I also positioned it absolutely so it didn't mess with the positioning of the other elements).

**Comment by kara** [comment] 2017-02-24 17:44
This looks like a dupe of https://github.com/angular/material2/issues/3215

**Closed by kara** 2017-02-24 17:44 UTC
