### ISSUE TITLE
mat-select options are partly hidden if text is too long

### ISSUE THREAD

**Issue by ianfdk** [angular/material2#12779] opened 2018-08-21 18:46 UTC
#### Bug, feature request, or proposal:
As stated in the title, my mat-select options (I'm using the `multiple` option in case that matters) have part of their text hidden if being viewed on a small screen.

What would be the correct way to fix this? I guess, ideally, the text would wrap to multiple lines so we can read all of it. Am open to other suggestions too. 

#### What is the expected behavior?
Should be able to see the whole text

#### What is the current behavior?
Text is cropped with a "..." at the end

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-gtr4uc

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.7
Material 6.4.2

#### Is there anything else we should know?
At first, I wanted to use a multiple checkboxes type of component and after some research, it seemed that this was the "correct" component for this. I might be wrong though.

**Comment by josephperrott** [comment] 2018-09-07 15:02
Closing as this is intended by design as the Material Design spec warns against options whose text goes beyond a single line.

You can however target the option styling to unset the `height` and `white-space`:
```css
.mat-select-panel mat-option.mat-option {
  height: unset;
}

.mat-option-text.mat-option-text {
  white-space: normal;
}
```

**Closed by josephperrott** 2018-09-07 15:02 UTC

**Comment by skadav** [comment] 2019-02-11 07:48
try this,  its work

.mat-select-panel mat-option.mat-option {
    margin: 1rem 0;
    overflow: visible;
    line-height: initial;
    word-wrap: break-word;
    white-space: pre-wrap;
}
  
.mat-option-text.mat-option-text {
    white-space: normal;
}

**Comment by bellamira** [comment] 2019-04-10 14:27
A slightly more concise option:

**Comment by ReinrodDMD** [comment] 2019-05-22 17:49
Is there a way to know when the text is truncated to enable a tooltip?

Here's what I was testing with:
`<mat-option *ngFor="let documentType of documentTypes" [value]="documentType"
              matTooltip="{{documentType.name}}" matToolTipPosition="after" matTooltipShowDelay="100"
              matTooltipHideDelay="100">
              {{ documentType.name }}
            </mat-option>`
