### ISSUE TITLE
md-hint message/text gets overlapped by placeholder/label of succeeding mdinput element

### ISSUE THREAD

**Issue by AhmedHasnaoui** [angular/material2#7326] opened 2017-09-26 12:08 UTC
#### Bug, feature request, or proposal:
md-hint message overlaps placeholder of focused input field, if hint message is line breaking.

#### What is the expected behavior?
Expected is that the container takes the whole height (input field + hint) and therefore pushing the next element further down if the line is breaking

#### What is the current behavior?
the hint field is position absolute, thus not considered in DOM flow and the placeholder -> label transition is pushing the label onto the md-hint text/message

#### What are the steps to reproduce?
see: [https://plnkr.co/edit/BHntUzYjEa0Mu6Qovrci?p=preview](https://plnkr.co/edit/BHntUzYjEa0Mu6Qovrci?p=preview)

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
creating flawless forms with material

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta.10 & 11 

#### Is there anything else we should know?
Can't think of anything else right now.

**Comment by donroyco** [comment] 2017-09-26 13:13
See #4580

**Comment by AhmedHasnaoui** [comment] 2017-09-26 13:19
thanks, I used the search function but could not find anything

**Comment by josephperrott** [comment] 2017-09-26 15:45
Closing as duplicate of #4580

**Closed by josephperrott** 2017-09-26 15:45 UTC
