### ISSUE TITLE
Unable to scroll behind overlays (mat-menu, mat-select, etc)

### ISSUE THREAD

**Issue by adamdport** [angular/material2#12254] opened 2018-07-17 20:33 UTC
#### Bug, feature request, or proposal:
When a `mat-menu`, `mat-select`, or any other overlay that uses a `repositionScrollStrategy` is open, the user cannot scroll

#### What is the expected behavior?
According to [the docs](https://material.angular.io/cdk/overlay/overview#scroll-strategies), 
> RepositionScrollStrategy will re-position the overlay element on scroll. 

#### What is the current behavior?
When an overlay is open, scrolling is blocked

#### What are the steps to reproduce?
I'm having trouble recreating it in a stackblitz, but it's broken in the material docs themselves: https://material.angular.io/components/menu/overview

Open a menu and then try to scroll the page

#### What is the use-case or motivation for changing an existing behavior?
According to [the docs](https://material.angular.io/cdk/overlay/overview#scroll-strategies), 
> RepositionScrollStrategy will re-position the overlay element on scroll. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/core": "6.0.7",
    "@angular/material": "6.3.2",

#### Is there anything else we should know?

**Comment by crisbeto** [comment] 2018-07-18 05:07
This is a side-effect of the backdrop which will be fixed by https://github.com/angular/material2/pull/7779. You can also work around it by making the `body` the scrollable element. Closing as a duplicate of https://github.com/angular/material2/issues/6927.

**Closed by crisbeto** 2018-07-18 05:07 UTC
