### ISSUE TITLE
Sidenav component errors

### ISSUE THREAD

**Issue by eddieklc** [angular/material2#5104] opened 2017-06-13 08:50 UTC
It's just that you have errors on your showcase page... Chrome 59.0.3071.86 (64-bit)

![screenshot_1](https://user-images.githubusercontent.com/15689404/27074045-27dd9222-5026-11e7-85f2-e8a416eba59d.png)

**Comment by donroyco** [comment] 2017-06-13 08:53
Being tracked at #4969

**Comment by jelbourn** [comment] 2017-06-14 23:27
Dupe of #4969

**Closed by jelbourn** 2017-06-14 23:27 UTC
