### ISSUE TITLE
Feature request: Rowspan in CDK-Table

### ISSUE THREAD

**Issue by isametal88** [angular/material2#8954] opened 2017-12-12 13:34 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
It would be very nice if the cdk-table could have a multirow option for the cells, like a standard html table: https://www.w3schools.com/tags/att_td_rowspan.asp. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.1.0
Angular Material 5.0.0

**Comment by andrewseguin** [comment] 2017-12-12 20:09
Duplicate of https://github.com/angular/material2/issues/8332

**Closed by andrewseguin** 2017-12-12 20:09 UTC
