### ISSUE TITLE
Can't call methods on SideNav when building for prod

### ISSUE THREAD

**Issue by igolfs** [angular/material2#1115] opened 2016-08-25 01:33 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
SideNav methods work in prod as in dev

#### What is the current behavior?
When building via ng build --prod, calls to sidenav methods fail with:
zone.js:260 Uncaught TypeError: this.sidenav.toggle is not a function

#### What are the steps to reproduce?
Create an app with a sidenav-layout with a button whose (click) opens the sidenav
build it with ng build --prod

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

can't reproduce in plunker, must build for prod

#### Which versions of Angular, Material, OS, browsers are affected?
angular2: 2.0.0-rc.5
angular2-material: 2.0.0-alpha.7-7
angular-cli: 1.0.0-beta.10
node: 6.2.2
os: linux x64
Description:	Linux Mint 17.3 Rosa

**Comment by helzgate** [comment] 2016-08-27 20:14
I had this same annoying issue.  I fixed it by manually setting references to the elements.  
[Angular2 RC5 & MD2 Sidenav](http://plnkr.co/ksQiEw8XImKrcjW6HthQ)

**Comment by igolfs** [comment] 2016-08-28 11:40
The problem went away when I upgraded to the latest angular-cli branch.

**Comment by jelbourn** [comment] 2016-08-31 00:57
Closing since it was likely caused by angular-cli

**Closed by jelbourn** 2016-08-31 00:57 UTC
