### ISSUE TITLE
 A floating action button transforming into a toolbar

### ISSUE THREAD

**Issue by Mehul1995** [angular/material2#7844] opened 2017-10-17 11:01 UTC
## Proposal 

A floating action button transforming into a toolbar.
[Like the one seen here ](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions)

## What is the expected behavior?
The floating action button can transform into a toolbar upon press or from a toolbar upon scroll. The toolbar can contain related actions, text and search fields, or any other items that would be useful at hand.

**Comment by donroyco** [comment] 2017-10-17 11:35
See @jelbourn's statement in #860 on this

> Status on this: we have no plans to add fab-speed-dial or fab-toolbar to the library at this time. Our reasoning is that these components are somewhat out of vogue now. They're also relatively high-complexity and less commonly used, so we think our resources are better spent on other work.
>
> Keeping the issue open so that people can find the status.

**Comment by ArmaProjects** [comment] 2017-10-18 15:17
What are the alternatives (in vogue), to replace the multiple actions button?

**Comment by josephperrott** [comment] 2017-10-31 18:47
Closing as duplicate of #860

**Closed by josephperrott** 2017-10-31 18:47 UTC
