### ISSUE TITLE
[macOS/Safari] mat-input value gets highlighted when you double click floating label

### ISSUE THREAD

**Issue by kwiniarski97** [angular/material2#15830] opened 2019-04-16 08:23 UTC
#### What is the expected behavior?
Double clicking a label doesn't do anything. Just like in other browsers.

#### What is the current behavior?
Double click highlights value inside mat-input. 

#### What are the steps to reproduce?
Open on Safari https://material.angular.io/components/input/overview double click label.
https://streamable.com/rtwvw

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Browsers: Safari( i was able to reproduce on newest version)

**Comment by macjohnny** [comment] 2019-04-16 10:19
clicking the label focuses the input field, e.g. in Chrome, which is what I would expect.

**Comment by kwiniarski97** [comment] 2019-04-16 10:26
@macjohnny this is inconsistent behavior as in every browser except safari clicking label doesn't select text inside input.

**Comment by macjohnny** [comment] 2019-04-16 10:38
if you previously selected the text, clicking the label will select the text again in Chrome.
However, I believe this is a general issue concerning the focus behavior of safari, although I cant find the issue that discussed a similar case.

**Comment by crisbeto** [comment] 2019-04-16 13:39
This is how native input labels work as well (see https://stackblitz.com/edit/angular-2jgbpy). Closing since this isn't something caused by Material.

**Closed by crisbeto** 2019-04-16 13:39 UTC
