### ISSUE TITLE
md-input text is partially cut with different body font sizes

### ISSUE THREAD

**Issue by Dunos** [angular/material2#9208] opened 2018-01-03 11:18 UTC
#### What is the current behavior?
When the body size of the document/html is something different that 16px, the input text gets cut for some letter like "p", "g", "q".

#### What are the steps to reproduce?
Working demo of the issue in [this stackblitz demo](https://stackblitz.com/edit/angular-nbrvl9)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 5.0.3 (it happens since beta version)
Angular 5.1.2
Sierra OS
Chrome 63 / Firefox 57

**Comment by julianobrasil** [comment] 2018-01-03 12:34
I can't see the cuts (windows 10, Chrome):

![image](https://user-images.githubusercontent.com/25405143/34520800-9cf817e4-f071-11e7-8073-0d41b5c2bd09.png)

**Comment by Dunos** [comment] 2018-01-03 13:23
@julianobrasil Forgot to say that I'm using MAC, with Chrome (v63) but it is also happening in Firefox (v57).

<img width="665" alt="captura de pantalla 2018-01-03 a las 14 21 14" src="https://user-images.githubusercontent.com/1147823/34522119-788b7b7e-f091-11e7-8612-6c8d7f7ebdaa.png">

**Comment by yooRabbit** [comment] 2018-01-05 01:26
same problem so I fixed by myself
```
.input {                  
  div.mat-form-field-infix {
    padding: .3em 0;
    input.mat-input-element {
      height: 17px;
      vertical-align: top;
    }
  }
}
div.mat-form-field-wrapper{
  padding-bottom: 1.15em;
}
```
add class `input` in your `<mat-form-field></mat-form-field>` tag. to make sure `mat-select` avoid this problem, use:
```
.select {
  div.mat-input-infix {
    padding: .3em 0;
  }
  div.mat-select-value{
    height: 17px;
    vertical-align: top;
  }
}
```
also add class `select` in your `<mat-form-field></mat-form-field>` tag.
PS: test in `<mat-form-field></mat-form-field>` tag `font-size:14px;`

**Comment by Dunos** [comment] 2018-01-05 09:59
Yeah I also solve this thing with custom CSS for now, but I think we should not be doing this

**Comment by mmalerba** [comment] 2018-02-23 23:47
Closing as a dupe of #9738

**Closed by mmalerba** 2018-02-23 23:47 UTC
Labels: P3: important

**Comment by KissBalazs** [comment] 2019-01-10 15:14
I honestlly belive that this is not a duplication of the said ticket. That refers to the mat-hint, and this ticket is about the md-input text.

Also, this still happens on my setup still:
![image](https://user-images.githubusercontent.com/10611667/50977468-a2f33600-14f2-11e9-8479-203e869c1097.png)
Angular 7.0.1, Material 7.0.2, Chrome: Version 69.0.3497.100 (Official Build) Ubuntu 16.04LTS (64-bit)

**Comment by ryannewelluk** [comment] 2019-04-25 08:38
Did you fix this? 
By commenting out the line-height in .mat-form-field seemed to fix this for me.

**Comment by dougrday** [comment] 2019-07-02 17:51
This is not a duplicate - the referenced issue is for a different part of the component.
