### ISSUE TITLE
selectionChange fires twice in Select component while clearing the value

### ISSUE THREAD

**Issue by mohanskumar** [angular/material2#13108] opened 2018-09-13 15:07 UTC
#### Bug, feature request, or proposal:
 selectionChange output in the select component fires twice when clearing the value which got selected. 

#### What is the expected behavior?
Should fire once

#### What is the current behavior?

firing twice
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

select an item from select list. ( selectionChange fires once, which is expected)
select 'None' from the list ( selectionChange fires twice which is unexpected)
https://stackblitz.com/edit/angular-pmbyc3-65mwhu?file=app/select-value-binding-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular 6.1.7 angular material 6.4.7

**Comment by crisbeto** [comment] 2018-09-13 15:49
Closing as a duplicate of https://github.com/angular/material2/issues/10675.

**Closed by crisbeto** 2018-09-13 15:49 UTC
