### ISSUE TITLE
[FormField] Fields hidden when using non-stock theme

### ISSUE THREAD

**Issue by rcanacci** [angular/material2#8960] opened 2017-12-12 17:50 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
User should be able to see the form fields (mat-form-field) displayed on the page.

#### What is the current behavior?
When using one of the stock angular material themes, such as '.../prebuilt-themes/deeppurple-amber.css', the fields display without issue. However, using a custom theme, the mat-form-fields are hidden by default. They are rendered on the page, but are invisible until clicked upon. When clicked, the animation occurs and moves the label up to the top (stock behavior), and the field clicked becomes visible. Also, tabbing through the fields, once one field has focus, reveals the fields one by one.

#### What are the steps to reproduce?
Best way to get familiar with the issue is to look here:
https://github.com/angular/material2/issues/3196

It's the same issue, previously closed, but I was not missing the DOCTYPE in my index.html, nor am I missing the BrowserAnimationsModule.

#### What is the use-case or motivation for changing an existing behavior?
No idea. Need your help to resolve that. :-)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Browsers
--
Chrome 62+
Edge 40.15+
Firefox 56.0 (32-bit)

Angular
--
@angular/core 5.0.5
@angular/material 5.0.0

OS
--
Windows 10

TypeScript
--
2.4.2

#### Is there anything else we should know?
See the description below.

If I use one of the stock angular material themes such as:
@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';
... my inputs appear as follows...

![image](https://user-images.githubusercontent.com/8365271/33863181-8c1690be-deb4-11e7-9ce9-50aabc898f22.png)

... as soon as I try to implement a custom theme, here is what happens:

![image](https://user-images.githubusercontent.com/8365271/33863224-ba86b186-deb4-11e7-9fe9-e1a19e510625.png)

... as you can see, its basically the same the others who are experiencing the same issue... the matInputs are there but invisible.

Clicking into them does begin the animation and properly display them (one at a time).

![image](https://user-images.githubusercontent.com/8365271/33863311-1dfdcfd8-deb5-11e7-917c-aeabe3925f0f.png)

**Comment by rcanacci** [comment] 2017-12-12 19:00
Sure thing!
Thanks for following up!!!
Ron Canacci rcanacci@yahoo.com330-259-1253 

    On Tuesday, December 12, 2017, 1:57:32 PM EST, Kristiyan Kostadinov <notifications@github.com> wrote:  
 
 
Can you post what your theme looks like?

**Comment by rcanacci** [comment] 2017-12-15 20:43
@mmalerba - hey there... just wanted to say thank you for looking into this issue.

I was curious if there had been any progress during the course of the last few days... or even just an idea as to the nature of the issue... how likely you feel it would be to being solved, etc.  No pressure regarding time, just curious for a status update / thoughts on how this issue looks.

Thanks in advance for all of the assistance on this issue.

**Comment by mmalerba** [comment] 2017-12-15 21:22
It looks like you're using a dark theme, but in your screenshot the background is white. Dark themes expect to be used on a dark background.

You could try adding this to your CSS:
```scss
.alt-button-theme {
  @include mat-button-theme($alt-button-theme);

  // Add dark color background to root alternate theme element
  $background: map-get($dark-theme, background);
  background: map-get($background, card);
}
```

**Comment by rcanacci** [comment] 2017-12-18 15:25
@mmalerba - Thank you for responding. 

Adding the code change that you suggested prevents the code from compiling.

Are you inferring here that $dark-theme should be an altogether separate theme that should be defined and then applied here?

re:
$background: map-get($dark-theme, background);

At this point, $dark-theme is not defined. 

Thanks.

**Comment by mmalerba** [comment] 2017-12-18 18:41
Oh sorry I didn't notice your alternate theme only applied to the button anyways. But your custom theme is also defined as a dark theme

> ```scss
> $custom-theme: mat-dark-theme($custom-primary, $custom-accent);
> @include angular-material-theme($custom-theme);
> ```

If you want the colors to show up right for a dark theme you need to make the background element a dark color. If you actually wanted a light theme use `mat-light-theme` instead.

**Comment by dannythebestguy** [comment] 2017-12-22 18:43
So does this mean that in a dark theme, the forms cannot be displayed in a white background ?

Normally Forms are on white background irrespective of dark/light themes of a website.

In any way can we change the component's light/dark feature and keep the main theme as it is ?

**Comment by mmalerba** [comment] 2017-12-22 19:08
You can use a dark theme for your app and a light theme for your forms if you like. Explanation of how to use multiple themes is here: https://material.angular.io/guide/theming#multiple-themes

Closing this issue since it's not a bug.

**Closed by mmalerba** 2017-12-22 19:08 UTC
