### ISSUE TITLE
Importing `MdButtonModule` breaks AOT

### ISSUE THREAD

**Issue by pfrendo** [angular/material2#6023] opened 2017-07-25 14:46 UTC
#### Bug, feature request, or proposal:
Importing `MdButtonModule` breaks AOT

#### What is the expected behavior?
AOT works

#### What is the current behavior?
AOT doesn't work when importing  `MdButtonModule`

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.1, Material 2.0.0-beta.8, Windows, TypeScript 2.4.2

**Comment by crisbeto** [comment] 2017-07-25 14:53
Can you post a stack trace and a code sample? We have an AoT CI check that is passing.

**Comment by ybaassini** [comment] 2017-07-25 15:33
I have the same problem but not because of MdButtonModule but because of MdDatepickerModule after the upgrade to "@angular/material": "=2.0.0-beta.8".

ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 29:10 in the original .ts file), resolving symbol ɵw in /Users/yassinebaassini/Documents/Keley/renault-base/ng2/node_modules/@angular/material/typings/index.d.ts, resolving symbol _MdPseudoCheckboxBase in /Users/yassinebaassini/Documents/Keley/renault-base/ng2/node_modules/@angular/material/typings/index.d.ts, resolving symbol MdPseudoCheckbox in /Users/yassinebaassini/Documents/Keley/renault-base/ng2/node_modules/@angular/material/typings/index.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/yassinebaassini/Documents/Keley/renault-base/ng2/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

**Comment by jelbourn** [comment] 2017-07-25 17:11
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a more detailed reproduction.

Also see our [docs site](https://github.com/angular/material.angular.io/) which uses beta.8 and uses AOT.

**Closed by jelbourn** 2017-07-25 17:11 UTC
Labels: cannot reproduce

**Comment by willshowell** [comment] 2017-07-25 17:43
@ybaassini @pfrendo may be worth wiping and reinstalling your node_modules

**Comment by greenZebraQuest** [comment] 2017-07-25 17:52
We had a similar issue with the upgrade from Material 2.0.0-Beta.8 when
using a carrot ^ in our package.json and when you freshly installed
node_modules. Became dependent on @angular/cdk which needed to be included
in package.json. not sure if its related but worth a shot.

**Comment by ybaassini** [comment] 2017-07-25 20:27
this is my package.json:

`{
  "name": "ng2",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "build": "webpack",
    "dist": "ng build --prod && gulp dist",
    "start": "gulp && ng serve --proxy-config proxy.conf.json --port=9000",
    "test": "karma start ./karma.conf.js",
    "single-test": "karma start ./karma.conf.js --single-run",
    "prepree2e": "npm start",
    "pree2e": "webdriver-manager update --standalone false --gecko false --quiet",
    "e2e": "protractor ./protractor.conf.js",
    "gulp": "gulp",
    "doc": "./node_modules/.bin/compodoc -p tsconfig.json --name \"Renault Online Car Sales Platform\" --theme 'readthedocs'",
    "doc-serve": "./node_modules/.bin/compodoc -p tsconfig.json --name \"Renault Online Car Sales Platform\" --theme 'readthedocs' --serve --watch",
    "open-doc": "http-server documentation",
    "dist-serve": "npm run dist && rm -rf ../web/front && ../app/console app:generate_front:exec && http-server -p 8081 -P http://127.0.0.1:8000 ../web/front",
    "prepush": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "=4.0.0",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "=4.0.0",
    "@angular/compiler": "=4.0.0",
    "@angular/core": "=4.0.0",
    "@angular/forms": "=4.0.0",
    "@angular/http": "=4.0.0",
    "@angular/material": "^2.0.0-beta.8",
    "@angular/platform-browser": "=4.0.0",
    "@angular/platform-browser-dynamic": "=4.0.0",
    "@angular/platform-server": "=4.0.0",
    "@angular/router": "=4.0.0",
    "@ng-bootstrap/ng-bootstrap": "=1.0.0-alpha.22",
    "@ngui/map": "^0.18.3",
    "@ngx-translate/core": "=6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "@types/googlemaps": "^3.26.14",
    "angular-calendar": "=0.15.2",
    "angular2-moment": "=1.3.3",
    "bootstrap": "=4.0.0-alpha.6",
    "core-js": "=2.4.1",
    "font-awesome": "=4.7.0",
    "intl": "=1.2.5",
    "jquery": "=3.2.1",
    "moment": "=2.18.1",
    "ng2-owl-carousel": "=0.1.15",
    "ng2-select": "=1.2.0",
    "ngx-cookie": "=1.0.0",
    "rxjs": "=5.1.0",
    "script-loader": "=0.7.0",
    "slick-carousel": "=1.6.0",
    "typedoc-plugin-external-module-name": "=1.0.9",
    "typescript": "2.2.1",
    "web-animations-js": "=2.2.5",
    "yamljs": "=0.2.8",
    "zone.js": "=0.7.8"
  },
  "devDependencies": {
    "@angular/cli": "=1.0.0",
    "@angular/compiler-cli": "=4.0.0",
    "@compodoc/compodoc": "=1.0.0-beta.7",
    "@types/jasmine": "2.5.38",
    "@types/jquery": "=2.0.41",
    "@types/node": "=6.0.60",
    "autoprefixer": "=6.5.3",
    "codelyzer": "^3.1.2",
    "css-loader": "=0.26.1",
    "cssnano": "=3.10.0",
    "exports-loader": "=0.6.3",
    "file-loader": "=0.10.0",
    "gulp": "=3.9.1",
    "gulp-concat": "=2.6.1",
    "gulp-rename": "=1.2.2",
    "http-server": "^0.10.0",
    "husky": "^0.14.3",
    "istanbul-instrumenter-loader": "=2.0.0",
    "jasmine-core": "=2.5.2",
    "jasmine-spec-reporter": "=3.2.0",
    "json-loader": "=0.5.4",
    "karma": "=1.4.1",
    "karma-chrome-launcher": "=2.0.0",
    "karma-cli": "=1.0.1",
    "karma-coverage-istanbul-reporter": "=0.2.0",
    "karma-jasmine": "=1.1.0",
    "karma-jasmine-html-reporter": "=0.2.2",
    "karma-sourcemap-loader": "=0.3.7",
    "less-loader": "=2.2.3",
    "postcss-loader": "=0.13.0",
    "postcss-url": "=5.1.2",
    "protractor": "=5.1.0",
    "raw-loader": "=0.5.1",
    "run-sequence": "=1.2.2",
    "sass-loader": "=4.1.1",
    "script-loader": "=0.7.0",
    "source-map-loader": "=0.1.5",
    "style-loader": "=0.13.1",
    "stylus-loader": "=2.4.0",
    "ts-node": "=2.0.0",
    "tslint": "=4.4.2",
    "typedoc-dash-theme": "=1.1.0",
    "typescript": "=2.2.1",
    "url-loader": "=0.5.7",
    "webpack-dev-server": "=2.3.0"
  }
}
`
does ^ before the number version change the way to install packages??

**Comment by pfrendo** [comment] 2017-07-26 06:52
Firstly I am using webpack, angular/cdk is also installed and this happens when I import the `MdButtonModule` on it's own...

```
ERROR in ./$$_gendir/~/@angular/material/typings/index.ngfactory.ts
    Module parse failed: C:\git\myApp\$$_gendir\node_modules\@angular\material\typings\index.ngfactory.ts Unexpected token (16:34)
    You may need an appropriate loader to handle this file type.
    | import * as i5 from '@angular/forms';
    | import * as i6 from '@angular/http';
    | export const MdCoreModuleNgFactory:i0.NgModuleFactory<i1.MdCoreModule> = i0.ɵcmf(i1.MdCoreModule,
    |     ([] as any[]),(_l:any) => {
    |       return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
     @ ./$$_gendir/ClientApp/app/components/counter/counter.component.ngfactory.ts 9:0-102
     @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
     @ ./ClientApp/boot-server.ts
```

**Comment by kemmis** [comment] 2017-08-07 23:18
@pfrendo Did you solve this problem you were having? I'm experiencing the same issue.

**Comment by Jerferson** [comment] 2017-08-21 20:31
Estou com esse problema após instalar o pacote do material
`ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 29:10 in the original .ts f
ile), resolving symbol ɵu in C:/2017-2/erp-angular/griza-app/node_modules/@angular/material/typings/index.d.ts, resolving symbol _
MdPseudoCheckboxBase in C:/2017-2/erp-angular/griza-app/node_modules/@angular/material/typings/index.d.ts, resolving symbol MdPseu
doCheckbox in C:/2017-2/erp-angular/griza-app/node_modules/@angular/material/typings/index.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\2017-2\erp-angular\griza-app\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts`

Estou começando a trabalhar com angular 4 agora, e me deparei com esse problema.
Se alguém puder me ajudar agradeço

**Comment by finalxcode** [comment] 2017-11-06 09:28
same problem
