### ISSUE TITLE
<md-dialog-actions>: Buttons are not correctly aligned

### ISSUE THREAD

**Issue by rubenlagus** [angular/material2#4895] opened 2017-05-31 16:23 UTC
#### What is the expected behavior?
As defined in Material guidelines, buttons should be on the right side

![image](https://cloud.githubusercontent.com/assets/2874352/26642426/fced0158-462d-11e7-8d5c-8d471185865e.png)

#### What is the current behavior?
Currently buttons are aligned on the left side

![image](https://cloud.githubusercontent.com/assets/2874352/26642430/03fb67f0-462e-11e7-8669-9fa8fe48df74.png)

#### What are the steps to reproduce?
See Plunker:
https://plnkr.co/edit/lQv6rdtGGl48vbsPXPn0?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Match Material Design spec.

**Comment by rubenlagus** [comment] 2017-05-31 16:23
Related to #3528

**Comment by julianobrasil** [comment] 2017-05-31 16:46
Doesn't the using of `<md-dialog-actions align="end">` solve the issue for you?

**Comment by crisbeto** [comment] 2017-05-31 17:55
Closing as a dupe of #3528. Also @julianobrasil is correct in that you can use the `align` option to set the button alignment.

**Closed by crisbeto** 2017-05-31 17:55 UTC
