### ISSUE TITLE
Datepicker: datepicker is shown partially when inside a modal

### ISSUE THREAD

**Issue by adaojunior** [angular/material2#4786] opened 2017-05-24 21:03 UTC
#### Bug:

Datepicker is shown only partially when inside a modal

#### What are the steps to reproduce?

<img width="1270" alt="screen shot 2017-05-24 at 4 55 02 pm" src="https://cloud.githubusercontent.com/assets/4921294/26425394/929c1b44-40a2-11e7-8b4a-3a95390c4228.png">

See, it is missing the last week of the month.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Google Chrome - Version 58.0.3029.110 (64-bit)

**Comment by willshowell** [comment] 2017-05-24 21:07
Duplicate of #4406

**Comment by fxck** [comment] 2017-05-24 21:34
Not really I don't think @willshowell I'm running a version with https://github.com/angular/material2/pull/4696 in and it's still broken inside a modal.

**Comment by willshowell** [comment] 2017-05-24 21:50
@fxck I just ran that PR as is (4a47f89) and it seems to be working fine 



<img width="826" alt="screen shot 2017-05-24 at 5 46 29 pm" src="https://cloud.githubusercontent.com/assets/6475576/26427039/19b80646-40a9-11e7-9520-8289da5ead2a.png">

**Comment by julianobrasil** [comment] 2017-05-29 23:02
Another thing is that it's fixed on the screen, so when you resize the view port, the dialog mooves to try to stay at the center, but the date picker seems to stick where it initially was:

![image](https://cloud.githubusercontent.com/assets/25405143/26563527/b0e18066-44a9-11e7-8584-a06211884302.png)

After resizing:

![image](https://cloud.githubusercontent.com/assets/25405143/26563531/c61a657e-44a9-11e7-88e0-dfb68a4a6096.png)

**Comment by willshowell** [comment] 2017-05-30 14:49
@adaojunior @julianobrasil could you check against the master build? #4696 was merged after the beta-6 release.

**Comment by julianobrasil** [comment] 2017-05-30 17:48
@willshowell , it worked for me (it follows the dialog when the view port is resized ande the dialog tries to be centered). Also it popups in the most logical direction (upward if the component is near the bottom of the viewport, and downward if the input if near the top).

**Comment by mmalerba** [comment] 2017-05-30 23:36
sounds like this has been fixed

**Closed by mmalerba** 2017-05-30 23:36 UTC
