### ISSUE TITLE
Floating input placeholder is aligned to the right of the prefix

### ISSUE THREAD

**Issue by gtranter** [angular/material2#4428] opened 2017-05-08 15:39 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The floating placeholder should be left aligned with the left side of the entire md-input-container, above any prefix if there is one.

#### What is the current behavior?
When an input's placeholder is floating (whether automatic or deliberate) and the input also has a prefix via MdPrefix, the placeholder is left aligned with the right side of the prefix.

#### What are the steps to reproduce?
Plunker template: http://plnkr.co/tiBos98s7cX9Lz0cCVQu

    <div>
      <md-input-container floatPlaceholder="always">
        <input mdInput type="text" placeholder="Label">
      </md-input-container>
    </div>
    <div>
      <md-input-container floatPlaceholder="always">
        <input mdInput type="number" placeholder="Amount">
        <span mdPrefix>$</span>
      </md-input-container>
    </div>
    <div>
      <md-input-container floatPlaceholder="always">
        <input mdInput type="text" placeholder="Note">
      </md-input-container>
    </div>

#### What is the use-case or motivation for changing an existing behavior?
The current alignment looks bad - especially in a list of inputs that all have different prefixes or some have no prefix.

#### Which versions of Angular, Material, OS, browsers are affected?
Material2 2.0.0-beta3

**Comment by willshowell** [comment] 2017-05-08 16:47
Dupe of #3660

**Comment by mmalerba** [comment] 2017-05-08 17:50
Closing as dupe of #3660

**Closed by mmalerba** 2017-05-08 17:50 UTC

**Comment by gtranter** [comment] 2017-05-08 17:51
Sorry about the dupe - I did a search, but found nothing - must have chosen the wrong search terms.
