### ISSUE TITLE
Autocomplete panel attached to "wrong" element?

### ISSUE THREAD

**Issue by mackelito** [angular/material2#9228] opened 2018-01-04 09:10 UTC
#### Bug, feature request, or proposal:
Proposal

I might be off here but similar to this pattern: https://material.io/guidelines/patterns/search.html#search-in-app-search
I think the panel should attach to the autocomplete element instead?

#### What is the expected behavior?
The panel should be attached to the wrapper element and not to the input it self..

#### What is the current behavior?
Panel attaches to the input (.mat-input-flex .mat-form-field-flex)

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
https://material.angular.io/components/autocomplete/overview

Perhaps there could be an option similar to the Menu component where we can specify placement?

**Comment by willshowell** [comment] 2018-01-04 13:39
Similar to https://github.com/angular/material2/issues/5205?

**Comment by jelbourn** [comment] 2018-01-04 23:43
Duplicate of #5205

**Closed by jelbourn** 2018-01-04 23:43 UTC

**Comment by mackelito** [comment] 2018-01-05 09:39
Yeah.. that was a better summary of the issue 😄 
Searched but did't came across that issue.. thx! 👍
