### ISSUE TITLE
[Form field] matPrefix/Suffix don't work if nested in a ng-container

### ISSUE THREAD

**Issue by IlCallo** [angular/material2#12060] opened 2018-07-04 14:58 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
matPrefix/Suffix directive should work even when inside a ng-container

#### What is the current behavior?
The div with class `mat-form-field-prefix/suffix` is not created

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-ugvzbw

#### What is the use-case or motivation for changing an existing behavior?
In my case, I must conditionally show different types of form fields based on a switch structural directive.
For the "date" type I must print 3 elements (input, datepicket toggle and datepicker itself).
Given those premises, I had to group them using a ng-container.
The bug will show off every time someone uses a ng-container to conditionally show some content in a mat-field and one of those elements have a matPrefix or matSuffix directive.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.6
Material 6.3.2

**Comment by IlCallo** [comment] 2018-07-04 15:19
I checked the underlying code.
[Here](https://github.com/angular/material2/blob/89cad3fd1511def6ea9aa17c867f9872bf774f2c/src/lib/form-field/form-field.ts#L233) you can see that prefix and suffix (and everything else) is retrieved via `@ContentChildren` without `{descendants: true}` option.

    @ContentChildren(Pane, {descendants: true}) arbitraryNestedPanes: QueryList<Pane>

[documentation](https://angular.io/api/core/ContentChildren)

I think that `@ContentChildren` should bypass ng-container tags by default, but this is an angular compiler issue rather than angular material I guess.
As a workaround, adding `{descendants: true}` could work, can anyone confirm this?
Will there be any side-effects accepting nested `@ContentChildren`?

**Comment by IlCallo** [comment] 2018-07-05 09:59
So... Shall I open an issue on `angular/angular` repo for ng-container behaviour with `@ContentChildren` or is this "working as intended"?
If it's the first one, can the one I proposed be a solution/temporary fix?

If not, I'll keep searching for a way to fix it on my side, at least.
Some trick like always adding it and using `display: none` to hide it when not necessary or something like that

**Comment by crisbeto** [comment] 2018-07-05 18:34
I think that this is working as intended. Angular only projects the direct descendants of an element.

**Comment by jelbourn** [comment] 2018-07-11 23:50
Yeah, this is just the way that Angular behaves. Closing this as working-as-expected.

**Closed by jelbourn** 2018-07-11 23:50 UTC

**Comment by IlCallo** [comment] 2018-07-12 15:24
I understand, even if it seems strange because `ng-container` and `ng-template` are described as transparent elements which shouldn't alter the behaviour of the underlying template if not for the structural directives you use them for.

I temporarly fixed the problem taking the datepicker and the toggle outside the ng-template and ng-container and applying

    <mat-datepicker-toggle matPrefix [for]="datePicker" [style.display]="field.type != 'date' ? 'none' : ''"></mat-datepicker-toggle>
    <mat-datepicker #datePicker></mat-datepicker>

but this feel hacky.

I'll open an issue on Angular and see if it gains attention.
