### ISSUE TITLE
Opening MdDialog in ngOnInit throws ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by fredrikredflag** [angular/material2#5268] opened 2017-06-21 07:28 UTC
#### Bug:
When opening a `MdDialog` inside `ngOnInit` of a component a `ExpressionChangedAfterItHasBeenCheckedError` error is thrown. If the `MdDialog` is opened in the constructor of a component no error is thrown.

Temp workaround is to open the `MdDialog` inside a `setTimeout(() => this._dialog.open(MyComponent))`

#### What are the steps to reproduce?

http://plnkr.co/edit/aE6LNzRVYnKB01bMej87?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
This only seems occur with material-beta.7 and angular 4.2.0+. 

Works fine with material-beta.7 and angular 4.1.3.

**Comment by julianobrasil** [comment] 2017-06-21 10:50
A workaround is using

`setTimeout(() => this._dialog.open(DialogContentComponent), 0);`

**Comment by fredrikredflag** [comment] 2017-06-21 10:53
@julianobrasil yes, as I mentioned in the issue report :)

**Comment by danwulff** [comment] 2017-07-11 00:31
Seeing the same thing.

@angular/cdk: 2.0.0-beta.8
@angular/material2: 2.0.0-beta.8
@angular/_____: 4.2.6

Here is a minimal repo duplicating the error: https://github.com/danwulff/mdDialog_error
```
Copy and run in terminal:
git clone https://github.com/danwulff/mdDialog_error && cd mdDialog_error/ && npm install && ng serve
```

Using the silly timeout workaround for now. Probably related to this: https://github.com/angular/angular/issues/17572

**Comment by johnpapa** [comment] 2017-09-02 19:56
Is there an update on this one yet?

@ThomasBurleson have you seen this?

**Comment by willshowell** [comment] 2017-09-05 15:24
It looks like https://github.com/angular/angular/issues/15634 covers it

**Comment by josephperrott** [comment] 2017-09-26 23:00
Closing as this is actually working as expected as noted by it requiring a feature request in `@angular/angular`.

If https://github.com/angular/angular/issues/15634 is implemented then this request would also be fulfilled here upon release of the feature.

**Closed by josephperrott** 2017-09-26 23:00 UTC

**Comment by angelopolotto** [comment] 2018-06-28 19:57
I had the same problem here when I tried open the MatDialog:

`
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'id: undefined'. Current value: 'id: mat-dialog-0'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?
`

**Comment by toddwseattle** [comment] 2018-08-14 16:52
Landed here from googling around.  An easy way to fix this if you want a dialog to open after doing some data check when loading a view is just to put it later in the lifecycle (see lifecycle hooks: https://angular.io/guide/lifecycle-hooks ).  Works great for me on the latest one; which fit my needs, AfterViewInit (ngAfterViewInit).

**Comment by vrbagal** [comment] 2018-08-20 17:45
workaround- use  Promise.resolve()

     ```
 Promise.resolve().then(() => {
        this.$loadingDialog = this.dialog.open(LoaddingDialogComponent, {
          width: '350px',
          disableClose: true 
        });
      });
```

**Comment by odahcam** [comment] 2018-08-28 18:09
Another workaround is to put the dialog openning inside a `setTimeout` callback. e.g.:

```typescript
  ngOnInit() {
    setTimeout(() => this.dialog.open(MyComponent))
  }
```

**Comment by medinsky** [comment] 2018-10-31 20:14
in my case placing open modal in ngAfterViewInit worked

**Comment by odahcam** [comment] 2018-11-01 00:07
> Closing as this is actually working as expected as noted by it requiring a feature request in `@angular/angular`.
> 
> If [angular/angular#15634](https://github.com/angular/angular/issues/15634) is implemented then this request would also be fulfilled here upon release of the feature.

Actually, isn't there any way to show a clearer error message?

**Comment by wottpal** [comment] 2019-03-26 19:28
Why is this issue closed?

**Comment by tuanbs** [comment] 2019-04-12 03:04
I got the same error today and moving the call into **constructor** or using **setTimeout()** fixes it. Why is that?

**Comment by odahcam** [comment] 2019-04-12 05:44
It is all about change detection, and is working as intended, all we can do is ask for a better error message guys.
