### ISSUE TITLE
Bottom Navigation Component?

### ISSUE THREAD

**Issue by ThunderRoid** [angular/material2#14961] opened 2019-01-25 19:17 UTC
#### Please describe the feature you would like to request.
Bottom navigation Component

#### What is the use-case or motivation for this proposal?
Bottom navigation bars allow movement between primary destinations in an app.

#### Is there anything else we should know?
https://material.io/design/components/bottom-navigation.html
https://developer.android.com/reference/android/support/design/widget/BottomNavigationView

**Comment by ThunderRoid** [comment] 2019-01-26 02:17
Well it is not a matter of debate. Bottom navigation is officially a part of Material Design so I should be a matter of when we can expect it implemented in angular material.

**Comment by mainawycliffe** [comment] 2019-01-26 02:21
Its already marked as a feature, the debate is about how to best to implement it and still satisfy the Material Design Guidelines.

**Comment by ThunderRoid** [comment] 2019-01-26 02:30
> Be patient, there is some hope [here](https://github.com/angular/material2/issues/408#issuecomment-359226739)

Now that look promising. Thank you

**Comment by ThunderRoid** [comment] 2019-01-26 02:32
https://github.com/angular/material2/issues/408#issuecomment-432103481

Well, not really. He is very busy....

**Comment by mainawycliffe** [comment] 2019-01-26 02:35
Sorry, missed that.

**Comment by jelbourn** [comment] 2019-02-06 19:54
Duplicate of #408

**Closed by jelbourn** 2019-02-06 19:54 UTC
