### ISSUE TITLE
Raised Button

### ISSUE THREAD

**Issue by renanpaiva64** [angular/material2#6565] opened 2017-08-20 17:16 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Text color black

#### What is the current behavior?
Text color white

#### What are the steps to reproduce?
Add a Raised Button inside a Toolbar

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
fork date: 08/20/2017 2:12:12 PM

#### What is the use-case or motivation for changing an existing behavior?
The text becames unreadeable

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
To fix I add a simple style: 
button[class='mat-raised-button']{
    color: black !important;
}

the default css is setting the color to current wich in this case already is White. So We got White background and White text color.

**Comment by donroyco** [comment] 2017-08-21 07:22
Duplicate of #4614

**Closed** 2017-08-21 18:51 UTC
