### ISSUE TITLE
Add datetimepiker and timepiker

### ISSUE THREAD

**Issue by valeravorobjev** [angular/material2#2867] opened 2017-01-30 13:04 UTC

**Comment by fxck** [comment] 2017-01-30 14:41
it's being worked on https://github.com/angular/material2/issues/2519#issuecomment-275792252 https://github.com/angular/material2/pull/2578

Altho it's gotta be said that there was no mention of datetimepicker, are you planning to do that at the same time as datepicker by any chance @mmalerba ? Or at least design it in a way that would allow timepicker extension? From my experience you almost always need both date and time and having it split into two components is both ux unfriendly as well as a little pain in the arse when it comes to combining the two(the way forms work).. this does http://code.promactinfo.com/md2/#/datepicker a fairly good job at combining the two

**Comment by mmalerba** [comment] 2017-01-30 17:41
Yeah, probably no time in the initial implementation, but it will be added after. We will probably go with something pretty similar to that on mobile, but I'm not sure how well it works for desktop. Hopefully the material design team will have some guidance for how to adapt it to desktop soon.

**Comment by mmalerba** [comment] 2017-02-01 15:57
I'm going to start working on this in the datepicker branch, here's the design doc: https://docs.google.com/document/d/1RwPFESCbSSLMSDqxWo7jg4UUpGJTrXX6p5wYlb9pmNc/preview

**Comment by kara** [comment] 2017-02-17 22:16
This looks like a duplicate of https://github.com/angular/material2/issues/675, where we're tracking datepicker's initial version. Specific time support will probably be a later feature and will get its own issue at that time.

**Closed by kara** 2017-02-17 22:16 UTC
Labels: feature

**Comment by SteveDunlap13** [comment] 2017-11-14 00:30
For those looking for a angular5/material2 / latest flex time picker, I banged one out last night for a personal project. Feel free to rip it to your needs. https://github.com/SteveDunlap13/MaterialTimeControl
