### ISSUE TITLE
Fix docs main page

### ISSUE THREAD

**Issue by Somebi** [angular/material2#9691] opened 2018-01-30 15:24 UTC
https://material.angular.io/ not working...

Uncaught SyntaxError: Unexpected end of input #

Probably broken build passed?

How this could have happened/passed...?

**Comment by donroyco** [comment] 2018-01-30 15:44
Duplicate of #9680

**Comment by josephperrott** [comment] 2018-01-30 16:12
Closing as this will be tracked in: https://github.com/angular/material.angular.io/issues/378

**Closed by josephperrott** 2018-01-30 16:12 UTC
