### ISSUE TITLE
CDK split screen

### ISSUE THREAD

**Issue by djleonskennedy** [angular/material2#10492] opened 2018-03-20 12:33 UTC
#### Bug, feature request, or proposal:
[proposal]

#### What are the steps to reproduce?
https://plnkr.co/bxgcK29PNl9lexw6z6Ym

#### What is the use-case or motivation for changing an existing behavior?
Have several project that require split screen functionality, would be nice to see it in CDK.
example: https://github.com/wannabegeek/ng2-split-pane

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest

**Comment by djleonskennedy** [comment] 2018-03-20 18:43
related: https://github.com/angular/material2/issues/7940

**Comment by josephperrott** [comment] 2018-03-26 15:59
closing as duplicate of #7940

**Closed by josephperrott** 2018-03-26 15:59 UTC

**Comment by djleonskennedy** [comment] 2018-03-27 10:32
@josephperrott isn't duplicate, it's just related, i'm about CDK
