### ISSUE TITLE
Nested MdDialog doesn't work

### ISSUE THREAD

**Issue by Namkem** [angular/material2#9660] opened 2018-01-29 14:32 UTC
#### What are the steps to reproduce?
import { MdDialogRef, MdDialog } from '@angular/material';
import { Injectable } from '@angular/core';
import {MyDialogComponent} from './MyDialogComponent';

@Component({
  selector: 'app-component1',
  templateUrl: './component1.html',
  styleUrls: ['./component1.css']
})

export class Component1 {
	constructor(public dialog: MdDialog) {}
	openDialog() {
    let dialogRef = this.dialog.open(MyDialogComponent, {
      disableClose : true
    }); // This opens 1st dialog
    dialogRef.afterClosed().subscribe(result => {
      console.log(`Dialog closed: ${result}`);
      this.dialogResult = result;
    });
  }
}

import { MdDialogRef, MdDialog } from '@angular/material';
import { Injectable } from '@angular/core';
import {MyDialogComponent2} from './MyDialogComponent2';

@Component({
  selector: 'app-dialog',
  templateUrl: './dialog.html',
  styleUrls: ['./dialog.css']
})

export class MyDialogComponent {
	constructor(public dialog: MdDialog) {}
	openDialog() {
    let dialogRef = this.dialog.open(MyDialogComponent2, {
      disableClose : true
    }); // This should open 2nd dialog but it will not and no error will be displayed
    dialogRef.afterClosed().subscribe(result => {
      console.log(`Dialog closed: ${result}`);
      this.dialogResult = result;
    });
  }
}

#### Is there anything else we should know? When second MdDialog box doesn't open I noticed in the dialog service that its id, stored in MdDialogRef, is the same as the id of the "parent" MdDialog. But when I open/close the first dialog it changes the id. The pattern of the id is md-dialog-# . # is increased by 1 each time the dialog opens. But in the case of the nested dialog box it takes the same one from the parent. I guess that what makes it block the second dialog from opening.

I can post the .ts files for you to check if that is necessary for the research.

**Comment by tinayuangao** [comment] 2018-01-30 23:40
@Namkem Could you please provide a StackBlitz reproduction?
StackBlitz starter: https://goo.gl/wwnhMV

**Comment by josephperrott** [comment] 2018-02-13 23:17
Closing as we are not able to reproduce the issue without a reproduction.

**Closed by josephperrott** 2018-02-13 23:17 UTC
