### ISSUE TITLE
Datepicker hidden

### ISSUE THREAD

**Issue by cocaux** [angular/material2#4712] opened 2017-05-22 09:38 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
See the datepicker

#### What is the current behavior?
The datepicker is hidden.

#### What are the steps to reproduce?
Have a datepicker at the end of the page.
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular: 4.1.3,
@angular/material: 2.0.0-beta.5,

#### Is there anything else we should know?
![screen shot 2017-05-22 at 11 03 14 am](https://cloud.githubusercontent.com/assets/20585623/26300575/c801c4fc-3ede-11e7-8a68-bef41c9bf484.png)

**Comment by crisbeto** [comment] 2017-05-22 10:15
Closing as a duplicate of https://github.com/angular/material2/issues/4406.

**Closed by crisbeto** 2017-05-22 10:15 UTC
