### ISSUE TITLE
Datepicker: Support of multiple Calendars, BCE dates, and various Precisions

### ISSUE THREAD

**Issue by tobiasschweizer** [angular/material2#8586] opened 2017-11-22 09:51 UTC
#### Bug, feature request, or proposal:

feature request

#### What is the expected behavior?

Support of:
- dates Before Christ (BC) / Before Common Era (BCE)
- other calendar formats besides Gregorian (e.g., Julian calendar), including automatic conversion of the selected date when changing the calendar
- precisions: day, month, year

Internally, Julian Day Numbers could be used for calculations. 

#### What is the current behavior?

Currently, Datepicker supports the selection of a Gregorian CE date with day precision.

#### What are the steps to reproduce?

N/A

#### What is the use-case or motivation for changing an existing behavior?

The use of Datepicker in the context of humanities disciplines. We are developing a GUI based on Angular v4  (https://github.com/dhlab-basel/Salsah) for our backend Knora (http://www.knora.org). Knora internally uses Julian Day Numbers and currently supports Gregorian and Julian Calendar dates (BCE and CE): http://www.knora.org/documentation/manual/rst/knora-ontologies/knora-base.html?highlight=bce#datevalue.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

N/A

#### Is there anything else we should know?

Before creating this issue, I made a post on stackoverflow: https://stackoverflow.com/questions/47352386/angular-material-datepicker-support-of-bce-dates-and-calendars/47400894#47400894

I really do not want to create another datepicker from scratch. I would rather like to help implement the requested features based on the existing material 2 datepicker. I think there are already enough JS date libraries that could be used for calculations between different calendar formats (http://npmjs.com/package/moonbeams).

**Comment by jelbourn** [comment] 2017-11-23 00:02
Duplicate of #2519

**Closed by jelbourn** 2017-11-23 00:02 UTC
