### ISSUE TITLE
md-select: underline is higher than md-input

### ISSUE THREAD

**Issue by Leonzen** [angular/material2#5293] opened 2017-06-22 05:49 UTC
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
When placing an md-select and md-input next to each other, the underline should be on the same level

#### What is the current behavior?
The underline is higher then the underline of md-input. I have to correct it with "margin-top 9px".

#### What is the use-case or motivation for changing an existing behavior?
For a consistent looking of input fields, please change the height of the md-select underline

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.1.2
Material: 2.0.0-beta.5
TypeScript: 2.1
Browser: Tested with Chrome but probably same bug in all browsers

**Comment by kara** [comment] 2017-06-26 22:16
Dupe of https://github.com/angular/material2/issues/2124

**Closed by kara** 2017-06-26 22:16 UTC
