### ISSUE TITLE
Calendar Component

### ISSUE THREAD

**Issue by jimmy-khalifa** [angular/material2#8433] opened 2017-11-14 14:35 UTC
#### Proposal:
I have noticed that the calendar component exists within the code via MatDatepickerModule. I had to hack into the code in order to be able to use only the calendar since the documentation doesn't mention this. 

#### What is the expected behavior?
Being able to use directly the Calendar component

#### What is the current behavior?
Calendar component exists within the DatePicker Component

#### What are the steps to reproduce?
Providing a Plunker preview for the result
https://plnkr.co/edit/x3CvqEPVtzHdOgMLtgEL?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I needed a Calendar for my personal project and since I was using Angular Material I wanted it to be compliant. Also the result I had of the Calendar which was great

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.1 , Angular Material 5.0.0-rc0, Typescript 2.6.1

**Comment by Chan4077** [comment] 2017-11-14 15:17
Duplicate of #8173 and #4801

**Comment by jelbourn** [comment] 2017-11-14 17:19
Duplicate of #4801

**Closed by jelbourn** 2017-11-14 17:19 UTC
