### ISSUE TITLE
md-select doesn't become smaller in md-card

### ISSUE THREAD

**Issue by Stas-tolpekin** [angular/material2#7075] opened 2017-09-14 14:17 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If I use md-select into md-card-content I expect md-select will have font-size (and height) same as md-form-field font-size.

#### What is the current behavior?
Currently, md-form-field font-size become smaller, but md-select font-size doesn't.

#### What are the steps to reproduce?
https://plnkr.co/edit/YYH1vUHacnYOKDgtc2FA
You can see: 
Outside from md-card md-form-field and md-select has same font-size = 16px
Inside md-card md-form-field has font-size = 14px, but md-select has font-size = 16px

#### What is the use-case or motivation for changing an existing behavior?
Form controls have different height and different position of underline. It looks messy.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.5
Material 2.0.0-beta.10
TypeScript 2.5.2
Browsers: Chrome, IE and others
OS: Windows 10

**Comment by willshowell** [comment] 2017-09-14 14:19
See https://github.com/angular/material2/issues/7044. This will be resolved by #6488.

**Comment by josephperrott** [comment] 2017-09-14 21:43
Closing as duplicate of #7044

**Closed by josephperrott** 2017-09-14 21:43 UTC
