### ISSUE TITLE
The oficial documentation page don work ok look at sidenav example SOS

### ISSUE THREAD

**Issue by atlabiz** [angular/material2#5103] opened 2017-06-13 08:49 UTC
#### Bug, feature request, or proposal:
Bug

https://material.angular.io/components/component/sidenav

#### What is the current behavior?
![sidenav error](https://user-images.githubusercontent.com/26713354/27073952-474eb53e-502e-11e7-932b-623865ac1338.PNG)
![default](https://user-images.githubusercontent.com/26713354/27073951-474a9ea4-502e-11e7-8c72-810bbfe76569.PNG)

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by donroyco** [comment] 2017-06-13 08:53
Being tracked at #4969

**Comment by kara** [comment] 2017-06-14 23:28
Dupe of #4969

**Closed by kara** 2017-06-14 23:28 UTC
