### ISSUE TITLE
Mat-Dialog opening animation slow on Chrome

### ISSUE THREAD

**Issue by lucabrasi83** [angular/material2#11330] opened 2018-05-15 05:01 UTC
#### Bug, feature request, or proposal:
Bug: Mat-Dialog opening animation is laggy on Chrome. Tested with Firefox, Edge, Safari and no issue seen.

#### What is the expected behavior?
The opening of dialog should be as smooth on Chrome as other browsers

#### What is the current behavior?
Laggy Mat-Dialog opening animation

#### What are the steps to reproduce?
Stackblitz: [https://stackblitz.com/edit/angular6-fast-dialog](https://stackblitz.com/edit/angular6-fast-dialog)

Stackoverflow topic: [https://stackoverflow.com/questions/50329776/angular-6-mat-dialog-slow-opening-with-chrome](https://stackoverflow.com/questions/50329776/angular-6-mat-dialog-slow-opening-with-chrome)
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI 6.0.1 / Angular Material 6.0.1

#### Is there anything else we should know?

**Comment by fxck** [comment] 2018-05-15 19:48
Noticed this as well, for me it seems to get the slower the higher my browser window is. But then again, that makes sense I guess, more content to paint.

**Comment by fredericojesus** [comment] 2018-06-03 01:29
The animation performance is very very slow, specially when you have an infinite scrolling list without virtual scrolling. When you have a lot of items rendered, it starts getting slower and slower. I just wanted to change to an opacity animation or just completely remove it.

**Comment by dadepra** [comment] 2018-06-11 04:19
Hi guys, I Have The same issue here. This bug broken UI performance.

**Comment by hijamoya** [comment] 2018-06-11 04:44
Same issue here, especially open a dialog in a complicated page

**Comment by btxtiger** [comment] 2018-06-17 00:02
I am getting this only on Chrome Mobile when the keyboard opens immediately because of the embedded input field in the dialog.

**Comment by ngehlert** [comment] 2018-07-05 13:52
also getting the same issue in chrome. are there any plans to fix this in the near future? or good workarounds?

**Comment by pshurygin** [comment] 2018-07-24 13:29
Still an issue with 6.1.0-rc.3
When opening dialog for the first time on Chrome, the animation is really sloppy. After the first time it becomes smooth.
This is not an issue in the latest Firefox

**Comment by muralikrrish279** [comment] 2018-09-17 12:43
Is there any update this issue? Its quite obvious mat dialog is slower in chrome for the first time load.

**Comment by nicolashenry** [comment] 2018-09-28 12:08
It seems to be better after adding this in my case:
```css
.mat-dialog-container {
	will-change: transform;
}
```

**Comment by schankam** [comment] 2018-10-26 05:36
The problem is still present at the moment, and I hope it will be fixed soon. Like @abductedMind said, we will keep using it for the moment because it is usable, but it would be very nice if this could be fixed ASAP. All the other animations we are doing on our side are fluids and smooth, but the one on the Material Dialog is not, which make it pretty annoying. Please, I'm happy to use material but these kind of things are crucial, specially for a UI framework.

**Comment by rvalimaki** [comment] 2018-11-02 08:44
@schankam do you use Material version 6 or 7? I have seen reports about Material 7 animations being much better.

We are still on Material 6 currently.

**Comment by schankam** [comment] 2018-11-14 11:49
So some updates here: I've updated to Material 7 and the modal animation is now fast and smooth !

@rvalimaki Thanks for your comment, it helped :)

**Comment by crisbeto** [comment] 2018-11-14 17:42
Closing the issue since people are reporting that it's fixed. We also have an option now to disable the animation.

**Closed by crisbeto** 2018-11-14 17:42 UTC

**Comment by lppedd** [comment] 2018-11-28 15:21
@crisbeto What's the option?

**Comment by fxck** [comment] 2019-02-13 00:29
I still find it pretty slow.

**Comment by ljunokas** [comment] 2019-06-25 10:06
The problem is when you are using two animations at once - opening sidenav and backdrop transition. Quick fix is to put transition-delay on backdrops transition like 0.3s

**Comment by dlarr** [comment] 2019-08-26 13:34
To me, the problem is not fixed. I noticed this sloppy behaviour with mat-tab-group

Here the blitzstack comming from https://material.angular.io/components/tabs/overview 
https://stackblitz.com/angular/yrjaxnymmqk?file=app%2Ftab-group-animations-example.ts

Try to compare the slow animation in Chrome VS Firefox.

Firefox >>> Chrome here.
