### ISSUE TITLE
MD-TAB does not support [disabled] property

### ISSUE THREAD

**Issue by sinisarudan** [angular/material2#880] opened 2016-07-18 16:57 UTC
#### Bug, feature request, or proposal:
MD-TAB does not support [disabled] property
https://github.com/angular/material2/tree/master/src/components/tabs

#### What is the expected behavior?
for the code
```html
<md-tab-group>
    <md-tab [disabled]="true"></md-tab>
    <md-tab></md-tab>
</md-tab-group>
```
the first tab should be disabled
#### What is the current behavior?
both tabs are enabled, operational

#### What are the steps to reproduce?
create a code like this:
```html
<md-tab-group>
    <md-tab [disabled]="true"></md-tab>
    <md-tab></md-tab>
</md-tab-group>
```

#### What is the use-case or motivation for changing an existing behavior?
in Angular Material 1 it is functional:
https://material.angularjs.org/latest/demo/tabs

**Comment by robertmesserle** [comment] 2016-08-01 16:32
Duplicate of #645.

**Closed by robertmesserle** 2016-08-01 16:32 UTC
Labels: feature, has pr
