### ISSUE TITLE
How to change Columns Order into a table using Angular2 , Using DnD

### ISSUE THREAD

**Issue by davidgk** [angular/material2#8196] opened 2017-11-02 16:10 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
When I click on a column, and move it between columns, It would be nice to reordeer the columns order

#### What is the current behavior?
Doesn't happen, Also I tried with several libraries, And I couldn't get the expected behaviour. Some other advice so I can solve this trouble ( there is some with angular 1, but nothing for typescript.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by josephperrott** [comment] 2017-11-02 17:27
Closing as duplicate of #6522 


From #6522
> There is nothing built into the table; eventually we'll have some guidance on how to do things like this, but it won't ever be baked directly into md-table or cdk-table

**Closed by josephperrott** 2017-11-02 17:27 UTC
