### ISSUE TITLE
mat-checkbox is not responsive

### ISSUE THREAD

**Issue by hoangnguyen208** [angular/material2#9659] opened 2018-01-29 14:31 UTC
When the text inside `mat-checkbox` is too long (more than one line), it just goes beyond any parents div or screen width. I checked demo examples, it has the same issue.

![untitled](https://user-images.githubusercontent.com/24925823/35515444-db8c5650-0511-11e8-8fbe-060da1eb5f0d.png)

**Comment by donroyco** [comment] 2018-01-29 15:02
Duplicate of #8416. For future issue reports, please use the [issue template](https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by crisbeto** [comment] 2018-01-29 19:15
Closing as a duplicate.

**Closed by crisbeto** 2018-01-29 19:15 UTC
