### ISSUE TITLE
Date input doesn't render properly in some browsers

### ISSUE THREAD

**Issue by ross-nordstrom** [angular/material2#1333] opened 2016-09-26 19:36 UTC
#### Bug, feature request, or proposal:

Several modern browsers (Firefox, IE, Safari) [do not natively support the `date` input.](http://caniuse.com/#search=date)  
Does (or will) Material2 provide the needed shims for this?
#### What is the expected behavior?

`date` inputs should consistently render across browsers.

![2016-09-26-131149_408x386_scrot](https://cloud.githubusercontent.com/assets/3299155/18848986/0a1b1e08-83ee-11e6-886d-30bbf7d253ca.png)
#### What is the current behavior?

`date` input doesn't render into anything meaningful on non-Chrome browsers (below: Firefox)

![2016-09-26-133556_288x173_scrot](https://cloud.githubusercontent.com/assets/3299155/18849022/2bb10cb2-83ee-11e6-8e77-8a1370008478.png)
#### What are the steps to reproduce?

``` html
<md-input type="date"></md-input>
```

http://plnkr.co/edit/nL8iy9hJ2usy8sfPOZsN?p=preview
#### What is the use-case or motivation for changing an existing behavior?

As a UI framework, I think it's appropriate to say that Material is responsible for ensuring consistent component behavior across browsers.
#### Which versions of Angular, Material, OS, browsers are affected?

I think all versions, but definitely `v2.0.0-alpha.7-4`, and the latest (`v2.0.0-alpha.8-2`)

**Comment by lucasvanhalst** [comment] 2016-09-27 11:14
duplicate of #675

**Comment by jelbourn** [comment] 2016-11-04 01:28
Yep, follow #675 for the full datepicker component.

**Closed by jelbourn** 2016-11-04 01:28 UTC
