### ISSUE TITLE
Datatable 

### ISSUE THREAD

**Issue by pantonis** [angular/material2#579] opened 2016-05-29 19:01 UTC
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?
The most important component out there is not implemented. Datatable is very important especially in the enterprise development. I think it is very very important to have this control. Everyone is asking for it. I have seen following datatable which is state of the art but is built using material 1 for angular 1.xx

https://github.com/daniel-nagy/md-data-table

Currently nothing exists out there for NG2

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by DevVersion** [comment] 2016-05-29 19:05
This is a duplicate of #358 and #224

**Comment by pantonis** [comment] 2016-05-29 19:54
@DevVersion

The duplicate issue does not say anything apart from people stating that they want this control.

Is it going to be implemented? What's your estimate for this?

Thanks

**Comment by DevVersion** [comment] 2016-05-29 20:17
You're issue actually not differentiating from the other issues.

As said in #224:
> We definitely plan on building one of these eventually, but it's a long way off due to the complexity of building something that will be feature-rich, performant, and accessible. Closing this issue for now since it's not actionable in the short-term. Towards the end of 2016 we might have more to say on the subject.

**Comment by kara** [comment] 2016-05-30 00:08
As Jeremy has already indicated the timeline in the comment DevVersion quoted, closing this for now.

**Closed by kara** 2016-05-30 00:08 UTC
