### ISSUE TITLE
Expansion Panel inside Tabs is displaying incorrectly

### ISSUE THREAD

**Issue by lmcnulty4** [angular/material2#8821] opened 2017-12-05 16:16 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Expansion panel inside a Tabs module Tab which is not the default tab should display correctly

#### What is the current behavior?
The content of an expansion panel is shown, pushing up the expansion panel title making it shorter. "Opening" and closing the expansion panel makes it display correctly.

#### What are the steps to reproduce?
http://plnkr.co/edit/r5jF0AzKsCAAYz6iKRqd?p=preview

The expansion panel on Tab1 (the default tab) displays correctly, but on Tab2 it's broken as described above.
This plunkr was forked from [issue 8754](https://github.com/angular/material2/issues/8754) which may or may not be related.

#### What is the use-case or motivation for changing an existing behavior?
Bug fix

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material: 5.0.0-rc.2.
Angular: 5.0.3
OS: Windows 10
Typescript: 2.4.2
Browsers: Microsoft Edge 41.16299.15.0, Chrome 62.0.3202.94 and Firefox Nightly 59.0a1 are all affected.

**Comment by josephperrott** [comment] 2017-12-05 18:59
Closing as duplicate of #5269

**Closed by josephperrott** 2017-12-05 18:59 UTC
