### ISSUE TITLE
[mat-tab-group] matTabContent gets duplicated when switching tabs

### ISSUE THREAD

**Issue by hneuer** [angular/material2#14751] opened 2019-01-08 14:02 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Each tab's content should be displayed just once

#### What is the current behavior?
Some tab's content gets duplicated when the tabs are switched frequently.

#### What are the steps to reproduce?
- open this StackBlitz: https://stackblitz.com/edit/angular-q2pkcy?file=app/tab-group-lazy-loaded-example.html
- switch fast (i.e. before the animation ends) between the three tabs (in the order Third, First, Second). At some point the content of one of the tabs will be duplicated:

![image](https://user-images.githubusercontent.com/1545118/50834813-4eff1a80-1355-11e9-9f22-81f8fd1523d1.png)

**Note:** I could reproduce this only with a div element right under the ng-template. It was not reproducible with just the text in there as it is in the original StackBlitz

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 7.2.1
Chrome (maybe others)

**Comment by Ploppy3** [comment] 2019-01-08 15:15
Yes, it only seems to happen when the content is lazily loaded.

**Comment by manklu** [comment] 2019-01-08 17:39
Possible duplicate of https://github.com/angular/material2/issues/10938
Possibly related to angular/angular#26133

**Comment by andrewseguin** [comment] 2019-01-09 23:05
Thanks for reporting the issue, will close as a duplicate of #10938

**Closed by andrewseguin** 2019-01-09 23:05 UTC
