### ISSUE TITLE
Unselect-all state in tree example is not transmitted up to root

### ISSUE THREAD

**Issue by ducalai** [angular/material2#13420] opened 2018-10-04 09:47 UTC
#### Bug, feature request, or proposal:
Checkbox tree doesn't work properly when unselecting all checkboxes inside a parent
(related to official documentation example https://material.angular.io/components/tree/examples)

#### What is the expected behavior?
When all checkboxes are unselected inside a parent, parent should be unselected and so should be grand-parents up to root if no other checkbox is selected  

#### What is the current behavior?
Only parent is unselected. But grand-parents and root stay in undeterminated state

#### What are the steps to reproduce?
Use official example https://material.angular.io/components/tree/examples

1. Expand Groceries, Fruits and Berries
![expand](https://user-images.githubusercontent.com/13022458/46465979-606ede80-c7ca-11e8-9cec-b78802c70486.PNG)

2. Check Berries
![check](https://user-images.githubusercontent.com/13022458/46465992-65339280-c7ca-11e8-9506-7841b8458ef4.PNG)

3. Uncheck Blueberry
![uncheck1](https://user-images.githubusercontent.com/13022458/46465999-69f84680-c7ca-11e8-9f79-b1076a16ef23.PNG)

4. Unckeck Raspberry
![uncheck2](https://user-images.githubusercontent.com/13022458/46466007-6d8bcd80-c7ca-11e8-8901-c1eac2224308.PNG)

This is issue and [#13314](https://github.com/angular/material2/issues/13314) are really confusing comportement of TreeView

Thanks for your help. 
Alain

**Comment by jelbourn** [comment] 2018-10-05 00:56
Is this not a duplicate of #13314?

**Comment by ducalai** [comment] 2018-10-08 07:48
In this issue, I unchecked the children and the parent's state became correctly unchecked. But parent's ancestors stayed checked, even if no more child is checked.

In [#13314](https://github.com/angular/material2/issues/13314), unchecking the parent of partially unchecked children causes the children to be unselected, but parent remains checked

I do not think you can consider this as duplicate
Thanks

**Comment by jelbourn** [comment] 2018-10-08 16:52
Closing as a duplicate since the issue boils down to "The select-all state is wrong"

Duplicate of #13314

**Closed by jelbourn** 2018-10-08 16:52 UTC
Labels: needs clarification
