### ISSUE TITLE
[mat-sidenav] opened="true" - appears closed in Universal rendered view

### ISSUE THREAD

**Issue by MrCroft** [angular/material2#7795] opened 2017-10-14 13:03 UTC
#### Bug, feature request, or proposal:
[x] - bug

#### What is the expected behavior?
Given `opened="true"` on `mat-sidenav`, the sidenav should appear opened in the server-rendered html.

#### What is the current behavior?
Right now, it doesn't get `transform: translate3d(0px, 0px, 0px)` applied when rendering server-side (I have included `NoopAnimationsModule` in my `app.server.module.ts`. The sidenav appears closed in the server-rendered view and only opens after the client kicks-in.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: **5.0.0-rc.2**
Material: **2.0.0-beta.12**

**Comment by CaerusKaru** [comment] 2017-10-15 00:24
Duplicate of #6865. @MrCroft The issue you've documented with the missing `transform` is compounded with the missing margins applied to the `mat-sidenav-content`. If we just patch the `transform`, the `mat-sidenav` will just overlap the content. But great catch on noticing this was missing. I've added it to #6865 for tracking.

cc @mmalerba

**Closed** 2017-10-19 22:59 UTC
