### ISSUE TITLE
Allow mat-expansion-panel to be inside a component under mat-accordion

### ISSUE THREAD

**Issue by eyalhakim** [angular/material2#8930] opened 2017-12-11 14:32 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
when nested inside components, mat-expansion-panels should still behave the same when nested inside a mat-accordion:

<mat-accordion>
      <my-component>
             <mat-expansion-panel></mat-expansion-panel>
      </my-component>
      <my-component>
             <mat-expansion-panel></mat-expansion-panel>
      </my-component>
</mat-accordion>

#### What is the current behavior?
mat-expansion-panels have no space between them when opened

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by willshowell** [comment] 2017-12-11 14:34
See https://github.com/angular/material2/issues/6870

**Comment by josephperrott** [comment] 2017-12-11 16:00
Closing as duplicate of #6870  - [see comment](https://github.com/angular/material2/issues/6870#issuecomment-327847741)

**Closed by josephperrott** 2017-12-11 16:00 UTC
