### ISSUE TITLE
Set selected md-tab programmatically 

### ISSUE THREAD

**Issue by askurdjel** [angular/material2#1764] opened 2016-11-08 09:16 UTC
Bug

I am trying to set last open tab to be selected by using [selectedIndex] on md-tab-group, but it is first tab always selected

**Comment by Superd22** [comment] 2016-11-08 16:32
duplicate of #1692

**Comment by jelbourn** [comment] 2016-11-09 04:24
Dupe of #1692

**Closed by jelbourn** 2016-11-09 04:24 UTC
