### ISSUE TITLE
Drag and drop breaks when element is removed from array

### ISSUE THREAD

**Issue by rafaelwalter** [angular/material2#13498] opened 2018-10-08 22:14 UTC
#### Bug, feature request, or proposal:
Remove draggable element from the array while dragging  shouldn't break drag and drop.

#### What is the expected behavior?
Keep dragging element (copy of it) until dropped.

#### What is the current behavior?
Stops dragging.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

Virtual Scroll + Drag and Drop => when dragging and scrolling at the same time the draggable element dissapears when the item (cdkDrag) is removed from the DOM by virtual-scroll.

#### What is the use-case or motivation for changing an existing behavior?
Scalability. cdk/drag-drop prevents default browser event from scrolling while dragging and also stop dragging when we enforce scrolling of elements while dragging. Drag and drop doesn't looks good when the browser is at the same time handling on the DOM a list of 13k elements so virtual-scroll is needed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.0.0-beta.2

#### Is there anything else we should know?
I tried moving the element as the list is scrolled but things got ugly xD

**Comment by crisbeto** [comment] 2018-10-09 04:49
The issue comes from the fact that the `cdkDrag` instance will be destroyed when it's removed from the array and we have no way of telling in `ngOnDestroy` whether it'll be re-inserted or whether it's removed forever.

**Comment by mayrmax** [comment] 2018-10-09 09:04
Got the same problem when I have items that can be removed from the list. One i remove one everything breaks. The explanation from @crisbeto seems logical. The solution would be to just remove them forever and readd them after they get visible or added again. The current drag item could be saved in a additional dom element that gets added once drag is happening or something like that.

**Comment by crisbeto** [comment] 2018-10-09 09:12
The idea is that you're not really supposed to change the data while an item is being dragged. You can do it safely inside the `dropped` callback.

**Comment by mayrmax** [comment] 2018-10-09 09:15
I dont do any dragging/dropping just removing one element from the list with a delete button. Just like a ordered task lisk.

**Comment by crisbeto** [comment] 2018-10-09 09:18
Can you post a code sample? It definitely shouldn't be breaking down just from removing something from the list.

**Comment by mayrmax** [comment] 2018-10-09 09:35
You are right, deleting is working my problems seems to be something else. I get the same error @rafaelwalter on initialization but it might be because of my setup.

**Comment by crisbeto** [comment] 2018-10-29 21:10
Closing since there hasn't been any activity in a while. It can be reopened if there's a reproduction example.

**Closed by crisbeto** 2018-10-29 21:10 UTC
