### ISSUE TITLE
webpack setting for the material 2

### ISSUE THREAD

**Issue by cyberat** [angular/material2#1182] opened 2016-09-06 09:29 UTC
Good afternoon!
Prompt for configuring webpack to work with the material 2
I have such a configuration:
(webpack.config.js) http://pastebin.com/fiTy2P07
app.main.ts : http://pastebin.com/5EQ0XdMf
app.module.ts:  http://pastebin.com/b8RLxLDg
app.component http://pastebin.com/Mfe2WQ4U

tsconfig.json 
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution":  "node",
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noEmitHelpers": false,
    "sourceMap": true,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": false
  },
  "awesomeTypescriptLoaderOptions": {
    "useWebpackText": true,
    "emitRequireType": false
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "buildOnSave": false
}
typings.json
{
  "globalDependencies": {
    "core-js": "registry:dt/core-js#0.0.0+20160725163759",
    "hammerjs": "registry:dt/hammerjs#2.0.8+20160724063812",
    "jasmine": "registry:dt/jasmine#2.2.0+20160621224255",
    "node": "registry:dt/node#6.0.0+20160831021119"
  }
}
Webpack performance of the team from the console
I get: 

> 
E:\Web\NGTest>webpack
clean-webpack-plugin: E:\Web\NGTest\build has been removed.
ts-loader: Using typescript@1.8.10 and E:\Web\NGTest\tsconfig.json
Hash: 0594e8fd186d1a403d09
Version: webpack 1.13.2
Time: 6385ms
                          Asset       Size  Chunks             Chunk Names
    app.2a15cde129ee75711eec.js    2.77 MB       0  [emitted]  app
app.2a15cde129ee75711eec.js.map    3.26 MB       0  [emitted]  app
                     index.html  449 bytes          [emitted]
    + 350 hidden modules

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\overlay\overlay-directives.d.ts
(12,14): error TS1005: '=' expected.

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\overlay\overlay-directives.d.ts
(12,24): error TS1005: ';' expected.

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\overlay\overlay-directives.d.ts
(24,14): error TS1005: '=' expected.

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\overlay\overlay-directives.d.ts
(24,24): error TS1005: ';' expected.

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\overlay\overlay-directives.d.ts
(12,14): error TS2304: Cannot find name 'elementRef'.

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\overlay\overlay-directives.d.ts
(24,14): error TS2304: Cannot find name 'overlayRef'.

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\overlay\position\connected-position-strategy.d.ts
(24,14): error TS1005: '=' expected.

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\overlay\position\connected-position-strategy.d.ts
(24,23): error TS1005: ';' expected.

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\overlay\position\connected-position-strategy.d.ts
(24,47): error TS1005: '=' expected.

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\overlay\position\connected-position-strategy.d.ts
(24,14): error TS2304: Cannot find name 'positions'.

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\portal\portal.d.ts
(14,14): error TS1005: '=' expected.

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\portal\portal.d.ts
(14,24): error TS1005: ';' expected.

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\portal\portal.d.ts
(53,14): error TS1005: '=' expected.

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\portal\portal.d.ts
(53,20): error TS1005: ';' expected.

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\portal\portal.d.ts
(14,14): error TS2304: Cannot find name 'isAttached'.

ERROR in E:\Web\NGTest\node_modules\@angular2-material\core\portal\portal.d.ts
(53,14): error TS2304: Cannot find name 'origin'.
Child html-webpack-plugin for "index.html":
        + 1 hidden modules
> 
Please tell me what I'm doing wrong.

typescript version 1.8.10

Thank you!

**Comment by jelbourn** [comment] 2016-09-06 13:13
Closing this issue since it is a question, not a bug / feature request. Please direct questions to the mailing list, gitter, etc.

**Closed by jelbourn** 2016-09-06 13:13 UTC
