### ISSUE TITLE
md components regularly throwing error 

### ISSUE THREAD

**Issue by KevinMind** [angular/material2#7192] opened 2017-09-20 03:06 UTC
#### Bug, feature request, or proposal:

ERROR MESSAGE IN DEVELOPER TOOLS:
```
compiler.es5.js:1690 Uncaught Error: Template parse errors:
'md-panel-title' is not a known element:
1. If 'md-panel-title' is an Angular component, then verify that it is part of this module.
2. If 'md-panel-title' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" <md-expansion-panel (opened)="setStep(0)" hideToggle="true">
    <md-expansion-panel-header>
      [ERROR ->]<md-panel-title>
        Personal data
      </md-panel-title>
"): ng:///ItemModule/ItemDetailComponent.html@3:6
```
I've gotten this with countless md components and I cannot figure out why.

#### What is the expected behavior?

1. I've imported all MD components to my module.ts file  in UI/shared/ui.module.ts which is imported to app.module.ts

2. I've added MD components to imports and exports of @NgModule({

3. I include proper markup in component html file. app/items/item-detail/item.detail.component.html

When I ng serve

I should see the md components rendered on the page like normal. I've had simple inputs and buttons working, but every time I add a new component from md it throws the mentioned error.

#### What are the steps to reproduce?

https://github.com/KevinMind/home-inventory-app-official

git clone
npm install
ng serve 

to get it running. To make it run without error go to 
app/items/item-details/item.detail.component.html

**Comment by willshowell** [comment] 2017-09-20 13:47
At a glance it looks like you aren't importing the correct Material modules into your feature modules. `ItemModule` doesn't import `MdExpansionModule`. It looks like you created a `UiModule` as a container for all the Material modules, but you need to import that into _every_ module that uses Material components, not just the `AppModule`.

**Comment by josephperrott** [comment] 2017-09-25 16:53
Closing as this was caused by not importing all components being used.

**Closed by josephperrott** 2017-09-25 16:53 UTC
