### ISSUE TITLE
directive with detectChanges() prevent md-menu from closing

### ISSUE THREAD

**Issue by Kergan** [angular/material2#5477] opened 2017-07-03 02:53 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-menu must be closed

#### What is the current behavior?
md-menu does not close

#### What are the steps to reproduce?
https://embed.plnkr.co/Ml2CPR/
just click the button

**Comment by julianobrasil** [comment] 2017-07-03 10:34
Maybe this is related to the fact that Material 2 components are switching to OnPush strategy (not sure when or how they are doing this). Just try markForCheck() instead of detectChanges().

**Comment by crisbeto** [comment] 2017-07-03 17:21
This looks really weird. The issue is that triggering change detection manually, before the Material components have initialized, seems to cause any subsequent directives not to fire their lifecycle hooks (in the menu case it's `ngAfterViewInit`. This also broke all of the icons that we have on the demo page. 

cc @jelbourn

**Comment by Kergan** [comment] 2017-07-07 03:49
Related angular issue:
angular/angular#17035

**Comment by josephperrott** [comment] 2018-03-07 20:47
Closing as this was fixed upstream in angular/angular.  Working example [here](https://stackblitz.com/edit/angular-material2-issue-hkjjhf?file=app%2Fapp.module.ts)

**Closed by josephperrott** 2018-03-07 20:47 UTC
Labels: P2: required
