### ISSUE TITLE
md-tab-group does not initialize properly in a container with display: none

### ISSUE THREAD

**Issue by drakenfly** [angular/material2#7006] opened 2017-09-12 12:11 UTC
#### Bug, feature request, or proposal:
When creating a tab-group inside a container element, that has it's `display`-property set to `none`, the selected tab does not seem to be selected once the element is revealed.

#### What is the expected behavior?
When I switch the container's `display`-property from `none` to `block`, the first tab (or the one defined via `[selectedIndex]` should have it's floating ink bar indicating, that the tab is selected.

#### What is the current behavior?
The first tab does not seem to be selected (even though it's content is shown, but the animations are broken on the first tab change (dynamicHeight)) when creating the tab-group in a container that has `display: none;` set.

#### What are the steps to reproduce?
See this plunker: http://plnkr.co/edit/tE1Jmfl3xnSOhu2AahHt?p=preview

#### What is the use-case or motivation for changing an existing behavior?
In some accordion components it is quite common to just 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
"@angular/animations": "^4.3.6",
"@angular/cdk": "^2.0.0-beta.10",
"@angular/common": "^4.2.4",
"@angular/compiler": "^4.2.4",
"@angular/core": "^4.2.4",
"@angular/forms": "^4.2.4",
"@angular/http": "^4.2.4",
"@angular/material": "^2.0.0-beta.10",
"@angular/platform-browser": "^4.2.4",
"@angular/platform-browser-dynamic": "^4.2.4",
"@angular/router": "^4.2.4"
```

**Comment by josephperrott** [comment] 2017-09-26 22:44
Duplicate of #7274

**Closed by josephperrott** 2017-09-26 22:44 UTC
