### ISSUE TITLE
[Datepicker] offset -1

### ISSUE THREAD

**Issue by rvoltolini** [angular/material2#6871] opened 2017-09-06 13:34 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Start Month at day 1

#### What is the current behavior?
Start Month at day 31 (offset -1), when i select the date at datepicker the date in input is updated correctly.
This error also happens when I select the month

![captura de tela de 2017-09-06 10-21-58](https://user-images.githubusercontent.com/30928235/30114462-3e795bf0-92ee-11e7-9df8-a1e7e2d5ca3e.png)
![captura de tela de 2017-09-06 10-24-14](https://user-images.githubusercontent.com/30928235/30114461-3e76ab80-92ee-11e7-972b-c8a2d292600c.png)
![captura de tela de 2017-09-06 10-26-48](https://user-images.githubusercontent.com/30928235/30114465-3f5c6422-92ee-11e7-9013-8a12a0acf86a.png)

#### What are the steps to reproduce?
Open Datepicker in https://material.angular.io/components/datepicker/overview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
OS Ubuntu 17.04 (update today)
Chrome/Firefox (update today)

#### Is there anything else we should know?
Last week I didn't have problems, I used a lot of times testing the system that I'm developing.
I updated the OS thinks this could be the problem, but I didn't get sucess

**Comment by julianobrasil** [comment] 2017-09-06 16:16
@mmalerba, it seems to be related to that daylight saving time issue...

**Comment by mmalerba** [comment] 2017-09-06 16:53
@julianobrasil have you had any luck reproducing? It looks normal for me

**Comment by rvoltolini** [comment] 2017-09-06 16:56
I think not. Daylight in Brazil starts in october.
I opened Datepicker in other Pc and it worked normally.
I think it's something in my notebook but i don't know how discovery it.
I updated OS, deleted node_modules (including home folder), change angular/material version (beta 10 and 8) and the problem remained.

**Comment by julianobrasil** [comment] 2017-09-06 17:03
> @julianobrasil have you had any luck reproducing? It looks normal for me

@mmalerba, not really. I tried out with known past dst dates which I used as testing cases in the past (and a lot of other dates, over a decade), but with no luck. 

It looks like a new issue, maybe caused by some particular configuration as @rvoltolini mentioned.

**Comment by jt-helsinki** [comment] 2017-10-17 06:30
I think this is related to [#7167](https://github.com/angular/material2/issues/7167)

**Comment by mmalerba** [comment] 2017-10-17 18:42
likely dupe of #7167

**Closed by mmalerba** 2017-10-17 18:42 UTC
