### ISSUE TITLE
mat-tab-nav-bar -> no horizontal scrolling

### ISSUE THREAD

**Issue by nickwinger** [angular/material2#11674] opened 2018-06-05 13:58 UTC
#### Bug, feature request, or proposal:
When using mat-tab-nav-bar instead of the mat-tab-group the horizontal scrolling does not appear (when overflowing)

#### What is the expected behavior?
Horizontal scrolling like the mat-tab-group

#### What is the current behavior?
No horizontal scrolling when width gets smaller and mat-tab-nav-bar is overflowing

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by andrewseguin** [comment] 2018-06-07 16:52
Duplicate of #2177

**Closed by andrewseguin** 2018-06-07 16:52 UTC
