### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by HansS** [angular/material2#9683] opened 2018-01-30 10:11 UTC
error code: Uncaught SyntaxError: Invalid Unicode escape sequence (in main file from webpack)

**Comment by EvAlex** [comment] 2018-01-30 11:33
Chrome says: `Uncaught SyntaxError: Unexpected end of input`

**Comment by donroyco** [comment] 2018-01-30 11:49
Duplicate of #9680

**Closed** 2018-01-30 11:54 UTC
