### ISSUE TITLE
Compilation fail because of not assignable type

### ISSUE THREAD

**Issue by Shikanime** [angular/material2#15036] opened 2019-01-31 14:18 UTC
#### What is the current behavior?

For some reason, there is a type error that I can't find in the sources, I wonder if it's my side error. 

```shell
➜  xlayers git:(build/bazel-integration) ✗ bazel run //src:prodserver --verbose_failures
INFO: Invocation ID: f1e90566-427f-49bf-851c-96c8451153ec
DEBUG: /private/var/tmp/_bazel_shikanime/0454a0eebf8b9ca80b000c06f6823ee2/external/bazel_skylib/lib.bzl:30:1: WARNING: lib.bzl is deprecated and will go awa
y in the future, please directly load the bzl file(s) of the module(s) needed as it is more efficient.
INFO: Analysed target //src:prodserver (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_shikanime/0454a0eebf8b9ca80b000c06f6823ee2/external/angular_material/src/lib/core/BUILD.bazel:10:1: Compiling Angular templat
es (ngtsc) @angular_material//src/lib/core:core failed (Exit 1): ngc-wrapped failed: error executing command
  (cd /private/var/tmp/_bazel_shikanime/0454a0eebf8b9ca80b000c06f6823ee2/execroot/xlayers && \
  exec env - \
  bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped '--node_options=--expose-gc' @@bazel-out/darwin-fastbuild/bin/external/angular_material/src/lib/core/core_es5_tsconfig.json)
Execution platform: @bazel_tools//platforms:host_platform
external/angular_material/src/lib/core/option/option.ts(267,54): error TS2322: Type '"" | "checked"' is not assignable to type '"unchecked" | "checked" | "indetermina
te" | undefined'.
  Type '""' is not assignable to type '"unchecked" | "checked" | "indeterminate" | undefined'.
external/angular_material/src/lib/core/option/option.ts(268,9): error TS2322: Type '"" | "checked"' is not assignable to type 'MatPseudoCheckboxState'.
  Type '""' is not assignable to type 'MatPseudoCheckboxState'.
external/angular_material/src/lib/core/ripple/ripple.ts(200,19): error TS6133: 'init' is declared but its value is never read.
external/angular_material/src/lib/core/selection/pseudo-checkbox/pseudo-checkbox.ts(62,19): error TS6133: 'init' is declared but its value is never read.
external/angular_material/src/lib/core/selection/pseudo-checkbox/pseudo-checkbox.ts(63,43): error TS6133: 'ctx' is declared but its value is never read.

Target //src:prodserver failed to build
INFO: Elapsed time: 1.848s, Critical Path: 1.42s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
 - OS: macOS Mojave 10.14.2 (18C54)
 - Bazel: 0.20.0-homebrew
 - Material: 7.1.3

#### Is there anything else we should know?

WORKSPACE: 
```python
workspace(name = "xlayers")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_NODEJS_VERSION = "0.16.5"
http_archive(
    name = "build_bazel_rules_nodejs",
    url = "https://github.com/bazelbuild/rules_nodejs/archive/%s.zip" % RULES_NODEJS_VERSION,
    strip_prefix = "rules_nodejs-%s" % RULES_NODEJS_VERSION,
)

RULES_TYPESCRIPT_VERSION = "0.22.0"
http_archive(
    name = "build_bazel_rules_typescript",
    url = "https://github.com/bazelbuild/rules_typescript/archive/%s.zip" % RULES_TYPESCRIPT_VERSION,
    strip_prefix = "rules_typescript-%s" % RULES_TYPESCRIPT_VERSION,
)

# The @angular repo contains rule for building Angular applications
ANGULAR_VERSION = "7.1.3"
http_archive(
    name = "angular",
    url = "https://github.com/angular/angular/archive/%s.zip" % ANGULAR_VERSION,
    strip_prefix = "angular-%s" % ANGULAR_VERSION,
)

# RxJS
RXJS_VERSION = "6.3.3"
http_archive(
    name = "rxjs",
    url = "https://registry.yarnpkg.com/rxjs/-/rxjs-%s.tgz" % RXJS_VERSION,
    strip_prefix = "package/src",
)

# Rules for compiling sass
RULES_SASS_VERSION = "1.15.1"
http_archive(
    name = "io_bazel_rules_sass",
    url = "https://github.com/bazelbuild/rules_sass/archive/%s.zip" % RULES_SASS_VERSION,
    strip_prefix = "rules_sass-%s" % RULES_SASS_VERSION,
)

# Rules for material design framework
MATERIAL_VERSION = "7.1.1-compat-ng-7.1.3"
http_archive(
    name = "angular_material",
    sha256 = "75bec457885ddf084219a9da152ff79831d84909bb036552141ca3aadee64a04",
    strip_prefix = "material2-%s" % MATERIAL_VERSION,
    url = "https://github.com/gregmagolan/material2/archive/%s.zip" % MATERIAL_VERSION,
)

load("@angular//packages/bazel:package.bzl", "rules_angular_dependencies")
rules_angular_dependencies()

load("@build_bazel_rules_typescript//:package.bzl", "rules_typescript_dependencies")
rules_typescript_dependencies()

load("@build_bazel_rules_nodejs//:package.bzl", "rules_nodejs_dependencies")
rules_nodejs_dependencies()

load("@build_bazel_rules_nodejs//:defs.bzl", "check_bazel_version", "node_repositories", "yarn_install")
check_bazel_version("0.18.0")
node_repositories()
yarn_install(
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

load("@io_bazel_rules_webtesting//web:repositories.bzl", "browser_repositories", "web_test_repositories")
web_test_repositories()
browser_repositories(
    chromium = True,
    firefox = True,
)

load("@build_bazel_rules_typescript//:defs.bzl", "ts_setup_workspace")
ts_setup_workspace()

load("@io_bazel_rules_sass//sass:sass_repositories.bzl", "sass_repositories")
sass_repositories()

load("@angular//:index.bzl", "ng_setup_workspace")
ng_setup_workspace()

load("@angular_material//:index.bzl", "angular_material_setup_workspace")
angular_material_setup_workspace()
```

cc: @manekinekko

**Comment by crisbeto** [comment] 2019-01-31 19:53
The ones on `option.ts` do look legit, although they won't actually break anything. On the other hand, the ones pointing to `pseudo-checkbox.ts` seem like they're referencing code generated by the compiler. Perhaps there's something in your build that ends up running the TS compiler over generated code?

**Comment by Shikanime** [comment] 2019-02-03 16:36
Hello @crisbeto,

Sorry for the delay 😣

I use Angular Bazel as mentioned (using the official repo as example: https://github.com/angular/angular-bazel-example) which uses the Angular compiler under the hood. But I have no much control over its configuration except the fact that i use the AOT compiler flag (ref: https://github.com/angular/angular-bazel-example/issues/263).

This bug type also occurred when I tried to integrate Bazel with my application in December but it did occur in the CDK part.

**Comment by jelbourn** [comment] 2019-02-06 19:20
@Shikanime can you share a full reproduction?

**Comment by Shikanime** [comment] 2019-02-07 13:43
@jelbourn I create a complete reproduction here: https://github.com/Shikanime/bazel-material

**Comment by Shikanime** [comment] 2019-02-08 10:24
After investigation, I discovered this error was due to the Ivy compiler enabled via the Bazel flag `build --define=compile=aot`.

**Comment by jelbourn** [comment] 2019-02-14 19:42
Closing since Ivy is not released yet.

**Closed by jelbourn** 2019-02-14 19:42 UTC
Labels: cannot reproduce, needs clarification
