### ISSUE TITLE
DtableComponent.html:100 ERROR TypeError: this._overlayRef.getState is not a function

### ISSUE THREAD

**Issue by cfficaurzua** [angular/material2#7497] opened 2017-10-03 17:37 UTC
#### Bug, feature request, or proposal:

bug
#### What is the expected behavior?
open a dialog

#### What is the current behavior?
opens dialog with the following error 
```
DtableComponent.html:100 ERROR TypeError: this._overlayRef.getState is not a function
    at MdDialogRef.webpackJsonp.../../../material/esm5/dialog.es5.js.MdDialogRef._getPositionStrategy (dialog.es5.js:414)
    at MdDialogRef.webpackJsonp.../../../material/esm5/dialog.es5.js.MdDialogRef.updateSize (dialog.es5.js:398)
    at MdDialog.webpackJsonp.../../../material/esm5/dialog.es5.js.MdDialog._attachDialogContent (dialog.es5.js:629)
    at MdDialog.webpackJsonp.../../../material/esm5/dialog.es5.js.MdDialog.open (dialog.es5.js:528)
    at DtableComponent.webpackJsonp.../../../../../src/app/components/dtable/dtable.component.ts.DtableComponent.viewOrder (dtable.component.ts:217)
    at Object.eval [as handleEvent] (DtableComponent.html:100)
    at handleEvent (core.es5.js:12023)
    at callWithDebugContext (core.es5.js:13493)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:13081)
    at dispatchEvent (core.es5.js:8615)
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular/core 4.4.4
angular/cdk 2.0.0-beta.11-ac70420
angular/material 2.0.0-beta.11
typescript2.3.4

#### Is there anything else we should know?
dtable.component.ts
import {MdDialog} from '@angular/material';

@Component({
  selector: 'app-dtable',
  templateUrl: './dtable.component.html',
  styleUrls: ['./dtable.component.css']
})
constructor( public dialog: MdDialog){  }

viewOrder(_key){
    this.db.object(`/orders/${_key}`).update({status:"processing"});
    this.dialog.open(ItemOrderDtableComponent, {
      data:_key,
      width: '50%'});
  }

Item-order-dtable.component.ts

import { MdDialogRef, MD_DIALOG_DATA} from '@angular/material';

Component({
  selector: 'app-item-order-dtable',
  templateUrl: './item-order-dtable.component.html',
  styleUrls: ['./item-order-dtable.component.css']
})
export class ItemOrderDtableComponent implements OnInit {

  constructor( public dialogRef: MdDialogRef<ItemOrderDtableComponent>, @Inject(MD_DIALOG_DATA) public data: any ){
     console.log(data)
  }

}

**Comment by crisbeto** [comment] 2017-10-03 18:59
Closing as a duplicate of #7501.

**Closed by crisbeto** 2017-10-03 18:59 UTC

**Comment by drtobal** [comment] 2017-10-06 15:41
same here
