### ISSUE TITLE
ERROR Error: No provider for Scrollable! (The symbol 'Scrollable' was not found in the index)

### ISSUE THREAD

**Issue by mackelito** [angular/material2#7489] opened 2017-10-03 09:56 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
should be importable

#### What is the current behavior?
It´s not :)

#### What are the steps to reproduce?
This works fine:
import { ScrollDispatcher } from '@angular/cdk/scrolling';

This does NOT work
import { ScrollDispatcher, Scrollable } from '@angular/cdk/scrolling';

**Comment by DevVersion** [comment] 2017-10-03 12:31
This happens because the `ScrollDispatchModule` is not imported.

Not sure if it would make sense to rename it to `ScrollingModule`.

**Comment by josephperrott** [comment] 2017-10-31 18:00
Closing as this is caused by not having the necessary `NgModule`

**Closed by josephperrott** 2017-10-31 18:00 UTC
