### ISSUE TITLE
mat-autocomplete-panel not styling with classes inherited from mat-autocomplete

### ISSUE THREAD

**Issue by JaimeStill** [angular/material2#11764] opened 2018-06-12 14:42 UTC
#### Bug, feature request, or proposal:
Bug and Documentation Clarification - Adding a class to `mat-autocomplete` applies the class to the `mat-autocomplete-panel`, but any defined styles are not applied. Would like to see an example in the documentation for `matAutocomplete - classList`.

#### What is the expected behavior?
Classes added to `mat-autocomplete-panel` should be styled appropriately.

#### What is the current behavior?
Classes are applied to `mat-autocomplete-panel` from `mat-autocomplete`, but styles are not applied.

#### What are the steps to reproduce?
``` html
<mat-form-field floatLabel="never">
  <mat-label>Filter Items</mat-label>
  <input matInput [matAutocomplete]="auto" #filter>
  <mat-autocomplete #auto="matAutocomplete" class="extended">
    <mat-option *ngFor="let i of service.items$ | async" [value]="i">{{i}}</mat-option>
  </mat-autocomplete>
</mat-form-field>
```

``` css
.mat-autocomplete-panel.extended {
  max-height: 512px; // double default max-height
}
```

[StackBlitz Example](https://stackblitz.com/edit/mat-autocomplete-class-issues?file=app%2Froutes%2Fhome.component.html)  

![mat-autocomplete-class](https://user-images.githubusercontent.com/14102723/41297275-cdb5cde8-6e2c-11e8-9019-da084f734366.png)

#### What is the use-case or motivation for changing an existing behavior?
Styling the overlay panel for `matAutocomplete` should be clarified in the documentation in the event that the above means of doing so is wrong.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
`@angular: 6.0.1`
`@angular/material: 6.0.1`

**Comment by josephperrott** [comment] 2018-06-26 16:12
Closing as from looking at your stackblitz reproduction, it looks like the issue is that your components css styling does not actually apply to the autocomplete.

Since your component is using `ViewEncapsulation.Emulated` your css rule has an additional element attribute selector added to it for the component which causes it to not match the autocomplete panel.  You should be able to either use `ViewEncapsulation.None` or you can use `::ng-deep` until its removal from Angular ([deprecation note](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep))

**Closed by josephperrott** 2018-06-26 16:12 UTC

**Comment by JaimeStill** [comment] 2018-06-26 17:52
@josephperrott, can the best practice usage of `classList` in [MatAutocomplete](https://material.angular.io/components/autocomplete/api#MatAutocomplete) be clarified then?
