### ISSUE TITLE
Autocomplete suggestion  not visible in Chrome on mobile

### ISSUE THREAD

**Issue by victorantos** [angular/material2#7958] opened 2017-10-22 15:42 UTC
#### Bug
Autocomplete suggestion  ot visible on iPhone 8plus in. Chrome 
https://youtu.be/MHc2-bzlxUc
#### What is the expected behavior?
The suggestion should be visible without scrolling 

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### Is there anything else we should know?

**Comment by amcdnl** [comment] 2017-10-23 17:45
Looks like on keydown it should be repositioning the dropdown overlay.

**Comment by crisbeto** [comment] 2017-10-23 18:44
Closing as a duplicate of https://github.com/angular/material2/issues/6341.

**Closed by crisbeto** 2017-10-23 18:44 UTC
