### ISSUE TITLE
need indication that mat-autocomplete value was selected by mouse click

### ISSUE THREAD

**Issue by BatshevaKl** [angular/material2#8434] opened 2017-11-14 15:01 UTC
**Bug, feature request, or proposal:**
proposal

**What is the expected behavior?**
event to indicate that mat-autocomplete value was selected by mouse click

**What is the current behavior?**
No way to know if an option was just clicked by mouse

**What are the steps to reproduce?**
Using mat-autocomplete of material2.

on blur of the input, "validate" function is called to check if the user wrote a valid value (without selecting it in the list).

If yes, then it is being "selected" for him by code, and if it is not valid, the value of the input is being cleared.

This is for a case the user wrote a value and didn't select it from the list.

```
<mat-form-field>
   <input matInput placeholder="city"
          [matAutocomplete]="cityAuto"
          formControlName="city"
          (blur)="validate()"/>
   <mat-autocomplete #cityAuto="matAutocomplete"
                     [displayWith]="displayFn">
      <mat-option *ngFor="let city of cities | async" [value]="city">
        <span>{{city.name}}</span>
      </mat-option>
   </mat-autocomplete>
</mat-form-field>
```
TS:

```
validate(){
  let val = this.locationForm.controls['city'].value;
  if (citiesListContainsValue(val)){
      this.locationForm.patchValue({
                       city:getItemFromcitiesList(val)
      });
  } else {
         form.patchValue({
              city:{code:-1,name:''}
          });
  }
}
```
Now here is the problematic case:

If the user started to type in the input (e.g. he wrote "New"), and then the auto complete list was opened and the user selected an option (e.g. "New York") using the mouse click, then the validate function is fired, but the value of the control ("this.locationForm.controls['city'].value") is only what the user was typing ("New") so the validate function clears the input, which is of course not the expected behavior.

I need an indication in the validate() function to know if the user just clicked a value in the list with the mouse and if so - just skip this funtion.

Any idea how to do this? or a different idea?

**Comment by BobBDE** [comment] 2017-11-14 16:35
Hi,
Not sure if I understand everything but can't you use the Output event 'optionSelected' of the mat-autocomplete ? It is the event that is emitted whenever an option from the list is selected.
See https://material.angular.io/components/autocomplete/api

**Comment by willshowell** [comment] 2017-11-14 16:38
You may be interested in some of the conversations in https://github.com/angular/material2/issues/3334

**Comment by jelbourn** [comment] 2017-11-14 17:19
Duplicate of #3334

**Closed by jelbourn** 2017-11-14 17:19 UTC

**Comment by BatshevaKl** [comment] 2017-11-15 07:04
@BobBDE - Thanks for that, but I tried it already and the event is not firing. I guess this is because the "validate" clears the selection

**Comment by vaibhavphutane** [comment] 2018-10-25 07:39
Issue is before value get set to target blur event getting called.
Workaround for this is use
 setTimeOut(()=>{
**your blur function**
}, 500)

**Comment by seba161189** [comment] 2019-02-26 18:17
<input (click)="focusOut()" type="text" matInput [formControl]="inputControl"
  [matAutocomplete]="auto">
   <mat-autocomplete #auto="matAutocomplete" [displayWith]="displayFn" >
     <mat-option (onSelectionChange)="submitValue($event)" *ngFor="let option of 
      options | async" [value]="option">
      {{option.name | translate}}
     </mat-option>
  </mat-autocomplete>

TS
focusOut() {
this.inputControl.disable();
this.inputControl.enable();
}
