### ISSUE TITLE
`FocusMonitorDirectivesExample` Not Working (Needs `A11yModule`)

### ISSUE THREAD

**Issue by swseverance** [angular/material2#14761] opened 2019-01-09 10:31 UTC
#### What is the expected behavior?
The example should indicate when buttons gain focus.

#### What is the current behavior?
No observable change when buttons gain focus. Updating `DemoMaterialModule` to export `A11yModule` appears to fix the example.

#### What are the steps to reproduce?
[Current Prod StackBlitz](https://stackblitz.com/angular/ryldjqekgvd?file=app%2Ffocus-monitor-directives-example.ts)

**Comment by crisbeto** [comment] 2019-01-09 18:13
How did you create that example? It seems to work for me when I fork it from the docs: https://stackblitz.com/edit/angular-vvy3pz.

**Comment by swseverance** [comment] 2019-01-09 19:01
@crisbeto the link I provided is where you are directed by after clicking the 'Edit in StackBlitz' button on https://material.angular.io/cdk/a11y/overview#cdkmonitorelementfocus-and-cdkmonitorsubtreefocus

**Comment by crisbeto** [comment] 2019-01-09 20:54
Thank you, I can reproduce it now. Closing the issue since the bug is in another repo. I've submitted https://github.com/angular/material.angular.io/pull/571 that'll fix it.

**Closed by crisbeto** 2019-01-09 20:54 UTC
Labels: P4, has pr
