### ISSUE TITLE
Warning eb24, ea23 in version 6.3.0

### ISSUE THREAD

**Issue by mattma** [angular/material2#11834] opened 2018-06-18 23:29 UTC
#### Bug, feature request, or proposal:
My app works with **6.2.1**. It outputted many warnings after I installed **6.3.0**. The app still works as expected, just too many warning in the console.

#### What is the expected behavior?
No Warning.

#### What is the current behavior?
```
WARNING in /.../node_modules/@angular/material/esm5/material.es5.js
27:0-244 "export 'ɵa24' was not found in '@angular/material/menu'

WARNING in /.../node_modules/@angular/material/esm5/material.es5.js
40:0-371 "export 'ɵc23' was not found in '@angular/material/tabs'
```

#### What are the steps to reproduce?
Installed Material and CDK version **6.3.0**

**Comment by fetters5** [comment] 2018-06-19 00:02
same issue except it wont work for me when I build with the -prod flag

**Comment by Chifilly** [comment] 2018-06-19 05:44
I'm having a similar issue, except I have slightly different warnings:
```
WARNING in ./src/app/page-header/page-header.component.ngfactory.js
116:163-170 "export 'ɵf23' (imported as 'i6') was not found in '@angular/material/menu'

WARNING in ./src/app/shared/dialogs/manage-streams.dialog.ngfactory.js
142:165-173 "export 'ɵf23' (imported as 'i13') was not found in '@angular/material/menu'

WARNING in ./src/app/page-header/page-header.component.ngfactory.js
148:862-869 "export 'ɵf23' (imported as 'i6') was not found in '@angular/material/menu'

WARNING in ./src/app/shared/dialogs/manage-streams.dialog.ngfactory.js
162:165-173 "export 'ɵf23' (imported as 'i13') was not found in '@angular/material/menu'

WARNING in ./src/app/shared/dialogs/manage-streams.dialog.ngfactory.js
173:566-574 "export 'ɵf23' (imported as 'i13') was not found in '@angular/material/menu'

WARNING in ./src/app/twitch-stream/twitch-stream.component.ngfactory.js
202:164-172 "export 'ɵf23' (imported as 'i12') was not found in '@angular/material/menu'

WARNING in ./node_modules/@angular/material/menu/typings/index.ngfactory.js
20:680-687 "export 'ɵd23' (imported as 'i1') was not found in '@angular/material/menu'

WARNING in ./src/app/twitch-chats/twitch-chats.component.ngfactory.js
222:165-173 "export 'ɵf23' (imported as 'i16') was not found in '@angular/material/menu'

WARNING in ./src/app/twitch-stream/twitch-stream.component.ngfactory.js
223:164-172 "export 'ɵf23' (imported as 'i12') was not found in '@angular/material/menu'

WARNING in ./src/app/twitch-chats/twitch-chats.component.ngfactory.js
238:165-173 "export 'ɵf23' (imported as 'i16') was not found in '@angular/material/menu'

WARNING in ./src/app/twitch-chats/twitch-chats.component.ngfactory.js
254:166-174 "export 'ɵf23' (imported as 'i16') was not found in '@angular/material/menu'

WARNING in ./src/app/page-header/page-header.component.ngfactory.js
270:1632-1639 "export 'ɵf23' (imported as 'i6') was not found in '@angular/material/menu'

WARNING in ./src/app/twitch-chats/twitch-chats.component.ngfactory.js
270:166-174 "export 'ɵf23' (imported as 'i16') was not found in '@angular/material/menu'

WARNING in ./src/app/page-header/page-header.component.ngfactory.js
270:920-927 "export 'ɵf23' (imported as 'i6') was not found in '@angular/material/menu'

WARNING in ./src/app/twitch-chats/twitch-chats.component.ngfactory.js
293:1337-1345 "export 'ɵf23' (imported as 'i16') was not found in '@angular/material/menu'

WARNING in ./src/app/twitch-stream/twitch-stream.component.ngfactory.js
293:390-398 "export 'ɵf23' (imported as 'i12') was not found in '@angular/material/menu'

WARNING in ./src/app/shared/dialogs/manage-favourites.dialog.ngfactory.js
311:166-174 "export 'ɵf23' (imported as 'i11') was not found in '@angular/material/menu'

WARNING in ./src/app/shared/dialogs/manage-favourites.dialog.ngfactory.js
362:567-575 "export 'ɵf23' (imported as 'i11') was not found in '@angular/material/menu'

WARNING in ./node_modules/@angular/material/menu/typings/index.ngfactory.js
49:191-198 "export 'ɵf23' (imported as 'i1') was not found in '@angular/material/menu'

WARNING in ./node_modules/@angular/material/menu/typings/index.ngfactory.js
68:152-159 "export 'ɵf23' (imported as 'i1') was not found in '@angular/material/menu'

WARNING in ./src/app/app.module.ngfactory.js
71:5416-5424 "export 'ɵd23' (imported as 'i31') was not found in '@angular/material/menu'

WARNING in ./src/app/page-header/page-header.component.ngfactory.js
73:162-169 "export 'ɵf23' (imported as 'i6') was not found in '@angular/material/menu'

WARNING in ./src/app/page-header/page-header.component.ngfactory.js
99:1739-1746 "export 'ɵf23' (imported as 'i6') was not found in '@angular/material/menu'

WARNING in ./src/app/page-header/page-header.component.ngfactory.js
99:455-462 "export 'ɵf23' (imported as 'i6') was not found in '@angular/material/menu'
```
And as fetters5 said, it doesn't work when built with --prod

**Comment by iGreat** [comment] 2018-06-19 08:05
I deleted all files in node_modules, and no warns showed.

**Comment by paviad** [comment] 2018-06-19 10:06
For those using VSTS build agent, you want to delete your `_work` folder to make sure the `node_modules` folder is clean there as well.

**Comment by jelbourn** [comment] 2018-06-19 17:14
Duplicate of #11844

**Closed by jelbourn** 2018-06-19 17:14 UTC

**Comment by mattma** [comment] 2018-06-20 02:17
Fresh installation works perfect without any warning.
