### ISSUE TITLE
Weird position of input placeholder when using prefix

### ISSUE THREAD

**Issue by jindrichruzicka** [angular/material2#8353] opened 2017-11-10 10:16 UTC
#### Bug:
When using material form field with input with floating placeholder (auto or always) set up, once there is a prefix and placeholder floats the result looks awkward.

#### What is the expected behavior?
When there is floating placeholder and it floats, it's position should be top left.

#### What is the current behavior?
When there is floating placeholder and it floats, it's position is on the top but there is some space to the left based on the prefix. Non-floating placeholders are OK but once they float, they should move to the left.

#### What are the steps to reproduce?
https://material.angular.io/components/form-field/overview
Example with the 'Amount' input, the placeholder is floating but it's not aligned properly because the prefix. It should be aligned with 'Enter your password' placeholder to make smooth user experience.

#### What is the use-case or motivation for changing an existing behavior?
Make proper user experience.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on Angular 4.4.4, material 2.0.0-beta.11, seems it's not affected by browser, OS, TypeScript version.

#### Is there anything else we should know?
Yes, all of us should learn, but I guess I can't help you with that.

**Comment by mmalerba** [comment] 2017-11-17 00:01
duplicate of #3660

**Closed by mmalerba** 2017-11-17 00:01 UTC
