### ISSUE TITLE
md-button click event in *ngIf;else template doesn't work

### ISSUE THREAD

**Issue by jponeill** [angular/material2#3461] opened 2017-03-06 17:00 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?

click event should work w/in *ngIf "else" branch template. 

#### What is the current behavior?

function assigned to click event doesn't get called in else template

#### What are the steps to reproduce?
Create a component w/ the following template and a "testClick" method.

`<div *ngIf="true;else #disp">`
`  <button md-button (click)="testClick()">works (when condition above is true)</button>`
`</div>`
`<button md-button (click)='testClick()'>works (not in template)</button>`
`<ng-template #disp>`
`<button md-button (click)="testClick()">doesn't work</button>`
`<button (click)="testClick()">works (not md-button)</button>`
`</ng-template>`

#### Which versions of Angular, Material, OS, browsers are affected?

Angular 4.0.0-rc.2
Material 2.0.0-beta.2
Chrome 56

#### Is there anything else we should know?
Using 4.x *ngIf;else so might be a Angular4 compatibility issue

**Comment by leo6104** [comment] 2017-03-06 18:24
I think this problem is caused by #14873

**Comment by sasxa** [comment] 2017-03-15 00:00
Does https://github.com/angular/angular/pull/15066 fix this issue? I also noticed `mdTooltip` isn't working with elements that transpile content `<ng-template>`, `<ng-container>` is this caused by same issue?

**Comment by leo6104** [comment] 2017-03-15 04:18
@sasxa the pull request angular/angular#15066 merged after angular rc.3 released. Please wait for next release - rc.4.

**Comment by leo6104** [comment] 2017-03-24 04:48
@jponeill You can close this issue. This problem was solved with Angular 4.0 rc.4 update :)

**Closed** 2017-03-24 12:41 UTC
Labels: potential Angular 4.0 issue
