### ISSUE TITLE
Responsive Grid List

### ISSUE THREAD

**Issue by raminqaf** [angular/material2#5069] opened 2017-06-11 10:52 UTC
#### Bug, feature request, or proposal:
Hi,
could you please make angular material 2 more responsive? The grid system needs different col sizes depending on your device size. The current cols just takes one attribute. You could have for example "cols-md", "cols-xs" and so on...
Thanks

**Comment by donroyco** [comment] 2017-06-11 12:41
Dupe of #1072

**Comment by lax20attack** [comment] 2017-06-13 02:15
You can do  it yourself on window resize.

**Comment by jelbourn** [comment] 2017-06-14 23:51
Dupe of #1072

**Closed by jelbourn** 2017-06-14 23:51 UTC

**Comment by rexebin** [comment] 2018-01-15 16:54
Is the feature dropped in favour of angular/flex-layout please?
