### ISSUE TITLE
Material Datepicker problem in IE 11 

### ISSUE THREAD

**Issue by kirillika** [angular/material2#7407] opened 2017-09-29 07:19 UTC
#### Bug

There seems to be a problem with the date picker when used as shown below. When "9/2a9/2017" is entered into the input field, IE 11 errs out with this message: TypeError: Invalid procedure call or argument.  (notice the 'a' in there). 

When this happens, ngModelChange is not triggered and there is no validation error coloring/text rendered for the input field. 

Another problem with IE 11 is similar.  When "a9/29/2017" is entered, there is no validation error coloring/text rendered for the input field, however, ngModelChange is triggered, but the date that is passed with the event is decremented by one day, so the result is 9/28/2017. There is a workaround to read the value of the input field as soon as the ngModelChange event comes in and validate the date with custom logic, so this problem is less severe than the first one, but still...  

#### What are the steps to reproduce?

 HTML:

  `<md-form-field>
    <input mdInput
           [mdDatepicker]="picker"
           placeholder={{label}}
           [ngModel]="myDate"
           (ngModelChange)="updateMyDate($event,true)"
           [max]="maxDate"
           #dateInput>

    <md-hint align="end">mm / dd / yyyy</md-hint>
    <md-error *ngIf="dateFormControl.hasError('required')">
      Valid date is <strong>required</strong>
    </md-error>
    <md-datepicker-toggle mdSuffix [for]="picker"></md-datepicker-toggle>
    <md-datepicker #picker ></md-datepicker>
  </md-form-field>
`

TS:

public dateFormControl:FormControl = new FormControl('', [
    Validators.required
  ]);

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

  IE 11 

  "dependencies": {
    "@angular/animations": "^4.4.3",
    "@angular/cdk": "^2.0.0-beta.11",
    "@angular/common": "^4.4.3",
    "@angular/compiler": "^4.4.3",
    "@angular/compiler-cli": "^4.4.3",
    "@angular/core": "^4.4.3",
    "@angular/forms": "^4.4.3",
    "@angular/http": "^4.4.3",
    "@angular/material": "^2.0.0-beta.11",
    "@angular/platform-browser": "^4.4.3",
    "@angular/platform-browser-dynamic": "^4.4.3",
    "@angular/platform-server": "^4.4.3",
    "@angular/router": "^4.4.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.2",
    "typescript": "^2.5.3",
    "zone.js": "^0.8.14"
  }

**Comment by donroyco** [comment] 2017-09-29 07:43
Why open another issue? #7406

**Comment by josephperrott** [comment] 2017-09-29 16:40
Can you please provide a reproduction case using [Plunker](https://goo.gl/DlHd6U)/[StackBlitz](https://goo.gl/wwnhMV)?

**Comment by kirillika** [comment] 2017-09-29 18:33
Here is the sample I created by inserting the datepicker into the template at StackBlitz:

https://stackblitz.com/edit/angular-material2-issue-j3nv8f

The code is very simple. 

It loads in FF and Chrome. It does not load in IE 11.  If you can get passed IE 11 errors (shown below) related to the StackBlitz template code, you should be able to reproduce the issue.

IE 11 errors:

_**Unhandled promise rejection Error: Object doesn't support property or method 'includes'**_

**Comment by djleonskennedy** [comment] 2017-10-02 10:59
@kirillika here you can get polyfill :)

[includes mdn](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

**Comment by jelbourn** [comment] 2018-01-17 00:05
Closing since this is a polyfill issue.

**Closed by jelbourn** 2018-01-17 00:05 UTC
Labels: cannot reproduce

**Comment by tabruzzomufg** [comment] 2018-12-04 19:46
Why was this closed there is still an issue with material Datepicker when using IE11.
You can simply see the issue by opening the following page with IE11, the calendar comes up blank.

https://material.angular.io/components/datepicker/overview

**Comment by mieszczans** [comment] 2018-12-19 07:40
The problem is not only as in the topic but there are no colors at all - black and white version.

**Comment by ayoubde** [comment] 2019-03-21 15:52
the following solution handles that issue as well.
https://github.com/angular/material2/issues/15400
