### ISSUE TITLE
DatePicker: fixed size?

### ISSUE THREAD

**Issue by tdekoekkoek** [angular/material2#5906] opened 2017-07-20 14:16 UTC
#### Bug, feature request, or proposal:
Maintain a fixed size of the date picker

#### What is the expected behavior?
Have functionality more like other JavaScript date pickers such as Bootstrap where the size of the control is fixed.

#### What is the current behavior?

When clicking through months on the date picker, some months have more days than others and the datepicker resizes.  This makes navigating annoying as now you have to click higher or lower to keep navigating depending on the size of the calendar
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by julianobrasil** [comment] 2017-07-20 14:27
All the jarring are being tracked in #5426. It has a PR.

**Comment by jelbourn** [comment] 2017-07-20 18:19
Dupe of  #5426

**Closed by jelbourn** 2017-07-20 18:19 UTC
