### ISSUE TITLE
Checkbox for md-select should have option to turn off any javascript animation for performance 

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#1813] opened 2016-11-10 19:43 UTC
#### proposal:
When brining in many items(rows) that are previously checked the performance is degraded severely... I notice that the animation is most likely the reason for this performance degradation.  The animation should only occur for newly checked items not items that have already been checked.  

#### What is the expected behavior?
to not have performance degrade when using a plugin... should be css styling only

#### What is the current behavior?
slowed loading for previously checked items loading many rows

#### What are the steps to reproduce?
load up a bunch of items that are previously checked with md-select

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2 material

#### Is there anything else we should know?
nope

**Comment by crisbeto** [comment] 2016-11-10 20:04
Could you provide a demo that shows the issue? It may be better to address the performance issue, rather than disabling the animation altogether.

**Comment by jelbourn** [comment] 2016-11-10 21:03
It wouldn't surprise me if the SVG animation was just inherently slow (it's built the way it is now to be exactly, perfectly on-spec). We should profile it and explore our options.

**Comment by crisbeto** [comment] 2016-11-11 20:38
Doesn't look like the animation is the cause: even if I disable it or I use a browser that doesn't support animating SVG, there's still a pretty decent delay on a list of 200 checkboxes. Seems like something is causing a bunch of style recalculations. My bet for now is that it's all of those classes being toggle on and off.

**Comment by jelbourn** [comment] 2016-11-11 22:21
@crisbeto which classes?

**Comment by crisbeto** [comment] 2016-11-11 22:25
These are the ones that are being watched, although not all of them get toggled at the same time. This is my best guess so far since I couldn't see much else that could be causing the recalcs. I'll take a better look tomorrow:

- md-checkbox-indeterminate
- md-checkbox-checked
- md-checkbox-disabled
- md-checkbox-align-end
- md-checkbox-focused

**Comment by jelbourn** [comment] 2017-06-06 21:52
I think this is resolved by the existence of pseudo-checkbox.

**Closed by jelbourn** 2017-06-06 21:52 UTC
Labels: perf

**Comment by xtianus79** [comment] 2017-06-07 06:22
@jelbourn what is pseudo-checkbox

**Comment by matte00** [comment] 2017-09-14 13:09
@xtianus79 

> Component that shows a simplified checkbox without including any kind of "real" checkbox.
 * Meant to be used when the checkbox is purely decorative and a large number of them will be
 * included, such as for the options in a multi-select. Uses no SVGs or complex animations.
 * Note that theming is meant to be handled by the parent element, e.g.
 * `mat-primary .mat-pseudo-checkbox`.
