### ISSUE TITLE
Expansion panel in tab shows its content in collapsed state when tab become active

### ISSUE THREAD

**Issue by ipassynk** [angular/material2#7916] opened 2017-10-20 01:57 UTC
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
content should be collapsed

#### What is the current behavior?
Expansion panel in tab shows its content in collapsed state when tab become active

#### What are the steps to reproduce?
1. Have a tabs and each tab has an expansion panel.
2. The first active tab shows the expansion panel correctly - collapsed state
3. Click on the second tab
4. Observe that the expended panel in the tab shows the content (it is not hidden)

https://stackblitz.com/edit/angular-material2-issue-vqp5mt

```
<mat-tab-group>
	<mat-tab label="1">

		<mat-expansion-panel>
			<mat-expansion-panel-header>
				header1
			</mat-expansion-panel-header>
			content1
		</mat-expansion-panel>

	</mat-tab>


	<mat-tab label="2">

		<mat-expansion-panel>
			<mat-expansion-panel-header>
				header2
			</mat-expansion-panel-header>
			content2
		</mat-expansion-panel>

	</mat-tab>
</mat-tab-group>
```

![image](https://user-images.githubusercontent.com/1403841/31801559-1b43a88e-b517-11e7-948d-3219c3a8da3b.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

![image](https://user-images.githubusercontent.com/1403841/31801573-2baa8832-b517-11e7-8394-6229302836ff.png)

**Comment by josephperrott** [comment] 2017-10-20 16:08
Duplicate of #5269

**Closed by josephperrott** 2017-10-20 16:08 UTC
