### ISSUE TITLE
md-tab-nav-bar: ink doesn't change with resizing tabs

### ISSUE THREAD

**Issue by willshowell** [angular/material2#3845] opened 2017-03-30 13:20 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
When the window hits the `$mat-xsmall` breakpoint, min widths for `.mat-tab-label` and `.mat-tab-link` change from 160px to 72px. The ink bar does not reflect that.

#### What are the steps to reproduce?

http://plnkr.co/edit/6NlXoXhzaDHsHtTo9JWn?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Master

#### Other Info
Related to #3044 but does not require tabs to be stretched.

**Comment by jelbourn** [comment] 2017-04-09 20:04
Dupe of #3044

**Closed by jelbourn** 2017-04-09 20:04 UTC
Labels: has pr
