### ISSUE TITLE
md-card-header not full width of card

### ISSUE THREAD

**Issue by yentheo** [angular/material2#2112] opened 2016-12-08 10:20 UTC
#### Bug, feature request, or proposal:
Either of the above

#### What is the expected behavior?
It's not really a bug, but I would like the container for the card header text, the div with class .md-card-header-text, to be the full width of the card if I don't have an avatar, or the remaining width when I have an avatar.

#### What is the current behavior?
It just take the width it needs.

#### What are the steps to reproduce?

So a simple md-card with a title, let's say I want to align the title right of the card, it won't work because the md-card-header-text element isn't full width

http://plnkr.co/edit/Nb8XbzcwnwrrSOVp3Exs?p=preview

#### What is the use-case or motivation for changing an existing behavior?
The align right isn't my real use case, in my project I have a subtitle with source -> destination, the destination should be all the way to the right.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.0.1
Material 2.0.0-alpha.10

**Comment by jelbourn** [comment] 2016-12-09 22:21
@yentheo does setting `width: 100%` on the element not meet what you need?

**Comment by yentheo** [comment] 2016-12-10 01:34
@jelbourn if you have an avatar, I don't think 100% is correct, because the width of the avatar is added. Besides that, the element with class md-card-header-text is added after angular adds the css to it, so if you want to do this, you have to do it with global css. This is my current solution, but these are all things you shouldn't want to do

**Comment by demetrio812** [comment] 2017-05-21 22:25
I'm having exactly the same problem, and because of that I cannot put an icon on the right side of the header, globally setting the md-card-header-text width works...

**Comment by jelbourn** [comment] 2017-06-06 21:50
Closing this because, after looking at the component, I believe it is working as intended. The individual card elements are meant to be conveniences that capture common use-cases; if you want to do something more custom, any custom element/css can be used in the card.

**Closed by jelbourn** 2017-06-06 21:50 UTC

**Comment by jimmykane** [comment] 2017-07-01 21:39
@jelbourn, on the other hand, why would the title content not be 100% by default, and we do have to override **globally** the `mat-card-header-text` `width`?

**Comment by vcjayan** [comment] 2019-08-27 05:07
Please use the below for card width in css

width: fit-content
