### ISSUE TITLE
Datepicker appears half in the screen and half out of the screen

### ISSUE THREAD

**Issue by omarcespedes** [angular/material2#4627] opened 2017-05-17 18:11 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Datepicker should calculate the height of the screen and decide to appear on the bottom or to the top of the field

#### What is the current behavior?
It always appear at the bottom of the field and if the field is at the edge of the window the datepicker goes out of the screen

#### What are the steps to reproduce?
scroll to a field that is almost at the edge of the bottom of the window and open the datepicker

**Comment by crisbeto** [comment] 2017-05-17 19:14
Looked into it a bit and there are a couple of issues:
1. We haven't set up the fallback positions for the datepicker.
2. Even if we had set up the fallback position, the `ConnectedPositionStrategy` measures the element too early and won't determine the proper positioning.

**Comment by fxck** [comment] 2017-05-17 20:02
dupe of https://github.com/angular/material2/issues/4406

**Comment by crisbeto** [comment] 2017-05-17 20:05
Closing as a dupe of #4406.

**Closed by crisbeto** 2017-05-17 20:05 UTC
