### ISSUE TITLE
md-radio problem with initializing value from ngModel in ngFor

### ISSUE THREAD

**Issue by maciejsobala** [angular/material2#831] opened 2016-07-08 13:09 UTC
#### Bug, feature request, or proposal:

I have problem with initialize radio button selected value, from radio-group
#### What is the expected behavior?

When I provide [(ngModel)] to radio-group inside ngFor, proper radio-button should be selected (depending on ngModel value)
#### What is the current behavior?

Nothing is selected
#### What are the steps to reproduce?

Code to reproduce:

``` ts
import {Component} from '@angular/core';
import { NgForm } from '@angular/common';
import {MD_RADIO_DIRECTIVES} from '@angular2-material/radio';
import {
  MdUniqueSelectionDispatcher
} from '@angular2-material/core/coordination/unique-selection-dispatcher';


class ItemType {
  constructor(public id: number, public name:string){}

}

class Item {
  constructor(public id:number, public name:string, public type:Type){}

}

@Component({
  selector: 'attributes',
  providers: [MdUniqueSelectionDispatcher],
  template: `
  <div *ngFor="let item of items">
  <md-radio-group name="type" [(ngModel)]="item.type" >
        <md-radio-button  *ngFor="let type of types" (change)="change(item)" [value]="type">{{type.name}}</md-radio-button>
      </md-radio-group>
      </div>

      <div>
      single item:
  <md-radio-group name="type" [(ngModel)]="oneItem.type" >
        <md-radio-button *ngFor="let type of types" (change)="change(oneItem)" [value]="type">{{type.name}}</md-radio-button>
      </md-radio-group>
      </div>
  `,

  directives: [
    MD_RADIO_DIRECTIVES
  ],
  styleUrls: ['app/productsSettings/formList.css'],
})


export class AttributesComponent {
  public types:ItemType[];
  public items:Item[];
  public oneItem:Item;


  constructor(){
     this.types = [
      new ItemType(1, "type A"),
      new ItemType(2, "type B"),
      new ItemType(3, "type C")
    ];

    this.items = [
      new Item(1, "item A", this.types[1]),
      new Item(3, "item B", this.types[0]),
      new Item(2, "item C", this.types[2])
    ];

    this.oneItem = this.items[1];
  }


  public change(item:Item){
    console.log(item);
    console.log(item.type);
  }
}
```
#### Which versions of Angular, Material, OS, browsers are affected?

Angular: 2.0.0-rc.4
Material: 2.0.0-alpha.6
Browsers: Safari, Chrome, FireFox
OS: OS X El Capitan, iOS 9.3
#### Workaround

To make proper radio selected add something like:

`[checked]="item.type==type"`

```
<md-radio-group name="type" [(ngModel)]="item.type" >
        <md-radio-button *ngFor="let type of types | async" [checked]="item.type==type" (click)="update(item)" [value]="type">{{type.name}}</md-radio-button>
      </md-radio-group>
```

**Comment by maciejsobala** [comment] 2016-07-08 14:32
Workaround:

To make proper radio selected add something like:

`[checked]="item.type==type"`

```
<md-radio-group name="type" [(ngModel)]="item.type" >
        <md-radio-button *ngFor="let type of types | async" [checked]="item.type==type" (click)="update(item)" [value]="type">{{type.name}}</md-radio-button>
      </md-radio-group>
```

**Comment by jelbourn** [comment] 2016-07-14 23:22
@maciejsobala can you provide a plunker that reproduces the issue?

**Comment by DevVersion** [comment] 2016-07-17 17:50
When I tested that out, everything worked as expected.
![image](https://cloud.githubusercontent.com/assets/4987015/16902188/a8662072-4c57-11e6-8d41-8bc3a2e05af4.png)

**Comment by maciejsobala** [comment] 2016-07-19 11:25
On my end it is not working:

It looks like my <md-group> are treated as big one, isntead 4 seperated groups:

<img width="546" alt="screen shot 2016-07-19 at 1 11 56 pm" src="https://cloud.githubusercontent.com/assets/15926528/16948037/b3845b52-4db2-11e6-8b89-47debec75e86.png">


My point is, that if I am setting [(ngModel)]="item.type" of <md-radio-group>, 
```
<md-radio-group name="type" [(ngModel)]="item.type" >
```

and inside group I am generating radios as:
```
 <md-radio-button  *ngFor="let type of types" (change)="change(item)" [value]="type">{{type.name}}</md-radio-button>
```

I expect that finally one of radio buttons inside group will be checked (that one which represents given type).

The important thing is, objects decalaration:
```
this.types = [
      new ItemType(1, "type A"),
      new ItemType(2, "type B"),
      new ItemType(3, "type C")
    ];

    this.items = [
      new Item(1, "item A", this.types[1]),
      new Item(3, "item B", this.types[0]),
      new Item(2, "item C", this.types[2])
    ];
```

As you can see every  item.type is referring to one of objects to each also reffers array.

Unfornatelly I am unable to use radio button in plunker. Here is partial code (not working), maybe you know how to import radios to it properly:

http://embed.plnkr.co/w12HPNJBdVGbiLh1Z0gH/

**Comment by carbosound1** [comment] 2016-09-02 10:08
It's working perfectly. Try doing something like this:

`<md-radio-group [name]="item.id" [(ngModel)]="item.type" >
    <md-radio-button  *ngFor="let type of types" (change)="change(item)" (click)="createItem()" [value]="type">{{type.name}}</md-radio-button>
  </md-radio-group>`

Each radio group should have it's own name otherwise it can not differentiate between those.

**Comment by krigton** [comment] 2016-10-10 09:13
Hello,

I'm also trying to use the m-radion-button-group and I'm not sure, but is the value two way binding working for you? (latest release). As I can see from your snippet you are not using two way binding on the value.

thanks

**Comment by jelbourn** [comment] 2016-11-03 21:01
I believe the issue here is that when `NgModel` writes the value via `writeValue`, change detection isn't always happening because the checkbox is `OnPush`. We need to use the `changeDetectorRef` to make sure change detection happens when `NgModel` writes the value.

**Comment by jelbourn** [comment] 2016-11-03 21:01
(also applies to radio-button and toggle-buttons)

**Comment by krigton** [comment] 2016-11-03 22:21
What we should do about the value two way binding? thanks

**Comment by tinayuangao** [comment] 2016-11-05 00:03
Tried the code on Plunker and it works perfectly if we set the correct names for different radio groups. The four radio-group should have different names, otherwise they're merged into one big radio group.

`writeValue ` is triggered every time `ngModel` is changed, but I can double check for the `changeDetectorRef`.

**Comment by tinayuangao** [comment] 2016-11-09 18:56
For different radio groups, you should use different `name`. By using `<md-radio-group name="type" [(ngModel)]="item.type" >`, all radio groups' names are set to "type". 

`[name]="item.id"` will fix this. Closing this issue.

**Closed by tinayuangao** 2016-11-09 18:56 UTC
Labels: good for community contribution, P2: required

**Comment by dotsneelam** [comment] 2019-08-29 09:53
g

**Comment by dotsneelam** [comment] 2019-08-29 09:53
use this code =>
 <mat-radio-group *ngFor="let type of goupApiResponse" name="type">
          <mat-radio-button  (change)="SelectDesignation(type)" [value]="type">{{type}}
          </mat-radio-button>
        </mat-radio-group>

it wroks
