### ISSUE TITLE
Functions multiple times in _theming.scss

### ISSUE THREAD

**Issue by krigton** [angular/material2#4281] opened 2017-04-26 07:24 UTC
#### Bug, feature request, or proposal:
Why is same function declared many times in the _theming.scss? 

like mat-color()

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, browsers are affected?
material 2.0.0-beta.3

**Comment by krigton** [comment] 2017-04-26 07:27
Looks that the file repeats the same thing over and over

**Comment by fxck** [comment] 2017-04-26 07:43
dupe of https://github.com/angular/material2/issues/3931

**Comment by krigton** [comment] 2017-04-26 08:33
we can close it

**Closed** 2017-04-26 08:37 UTC
