### ISSUE TITLE
Select's panelClass input not working

### ISSUE THREAD

**Issue by LAlves91** [angular/material2#5450] opened 2017-06-30 20:40 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When the panelClass input is set with a class, the styles inside that class should affect the overlay panel shown when you open a Select component.

#### What is the current behavior?
Select's panelClass input isn't working here. I set it to a custom class, and despite that class being set inside the class property of the div in question, none of the properties I set inside the CSS seem to stick (insinde chrome's style inspection, my class isn't even shown).

**Comment by donroyco** [comment] 2017-07-01 05:51
Please add a Plunker to reproduce the issue.

**Comment by LAlves91** [comment] 2017-07-03 18:28
Here's a Plunker reproducing the problem:
https://embed.plnkr.co/Bis1n7S4bqkRv6qP7UlA/
There, I'm trying to set a new background color and reset the max-width property inside the panel. If you inspect the result, you'll see that my custom class is inside the div's class declaration, but none of the styles I set are working.

**Comment by willshowell** [comment] 2017-07-03 18:48
It's important to know that overlay components are inside a global overlay container and won't be affected by your styles due to view encapsulation. You should either set your component's view encapsulation to None or add your custom styles to your global stylesheet.

Once your styles are applied, you'll find that the max-width is still being overwritten. This is due to selector specificity, and you should increase the specificity of your selector.

See this updated plunker
https://plnkr.co/edit/6kTUd1HnzFGucH33wy6J?p=preview

**Comment by LAlves91** [comment] 2017-07-03 19:32
Oh, I thought the idea of the panelClass input was to go through the view encapsulation somehow and apply the styles set inside the custom class. 
Sorry about my confusion, I'm fairly new to Angular. And thank you very much for the answer!

**Comment by mmalerba** [comment] 2017-07-05 22:13
Closing as it sounds like this has been resolved

**Closed by mmalerba** 2017-07-05 22:13 UTC
