### ISSUE TITLE
Dialog component not working in production?

### ISSUE THREAD

**Issue by Richi2293** [angular/material2#11963] opened 2018-06-28 11:28 UTC
#### Bug, feature request, or proposal:
It appears that the Dialog component does not work in the production version.

#### What is the expected behavior?
Since it works in a local development environment it should also work in production

#### What is the current behavior?
When I start the development environment with the command "ng serve" it works fine but when I do a test with the production version with the command "ng serve --prod" then it returns an error when trying to open the Dialog.

![image](https://user-images.githubusercontent.com/5848941/42031590-15bca1f0-7ad7-11e8-8586-cf4d2539a7a7.png)

#### What are the steps to reproduce?
Try the Dialog component with this version of my package.json

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
This is my package.json

> {
>   "name": "angular",
>   "version": "0.0.0",
>   "license": "MIT",
>   "scripts": {
>     "ng": "ng",
>     "start": "ng serve",
>     "build": "ng build",
>     "test": "ng test",
>     "lint": "ng lint",
>     "e2e": "ng e2e"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular/animations": "6.0.6",
>     "@angular/cdk": "^6.1.0",
>     "@angular/common": "6.0.6",
>     "@angular/compiler": "6.0.6",
>     "@angular/core": "6.0.6",
>     "@angular/flex-layout": "^5.0.0-beta.13",
>     "@angular/forms": "6.0.6",
>     "@angular/http": "6.0.6",
>     "@angular/material": "^6.1.0",
>     "@angular/platform-browser": "6.0.6",
>     "@angular/platform-browser-dynamic": "6.0.6",
>     "@angular/router": "6.0.6",
>     "@fortawesome/angular-fontawesome": "0.1.0-10",
>     "@fortawesome/fontawesome-svg-core": "^1.2.0",
>     "@fortawesome/free-solid-svg-icons": "^5.1.0",
>     "@ng-bootstrap/ng-bootstrap": "^1.0.1",
>     "angular-calendar": "^0.22.3",
>     "angular2-moment": "^1.8.0",
>     "core-js": "^2.5.4",
>     "font-awesome": "^4.7.0",
>     "jquery": "^3.3.1",
>     "ng-zorro-antd": "^0.6.15",
>     "ngx-chips": "^1.6.7",
>     "ngx-onsenui": "^4.1.0",
>     "onsenui": "^2.9.2",
>     "primeng": "^5.2.4",
>     "rxjs": "^6.2.1",
>     "rxjs-compat": "^6.2.1",
>     "sha1": "^1.1.1",
>     "zone.js": "^0.8.26"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "~0.6.8",
>     "@angular/cli": "^6.0.8",
>     "@angular/compiler-cli": "6.0.6",
>     "@angular/language-service": "6.0.6",
>     "@types/jasmine": "~2.8.6",
>     "@types/jasminewd2": "~2.0.3",
>     "@types/node": "~8.9.4",
>     "codelyzer": "^4.2.1",
>     "jasmine-core": "~2.99.1",
>     "jasmine-spec-reporter": "~4.2.1",
>     "karma": "~1.7.1",
>     "karma-chrome-launcher": "~2.2.0",
>     "karma-cli": "~1.0.1",
>     "karma-coverage-istanbul-reporter": "~2.0.0",
>     "karma-jasmine": "~1.1.1",
>     "karma-jasmine-html-reporter": "^0.2.2",
>     "protractor": "~5.3.0",
>     "ts-node": "~5.0.1",
>     "tslint": "~5.9.1",
>     "typescript": "~2.7.2"
>   }
> }
> 
> 

This is the angular.json

> {
>   "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
>   "version": 1,
>   "newProjectRoot": "projects",
>   "projects": {
>     "angular": {
>       "root": "",
>       "sourceRoot": "src",
>       "projectType": "application",
>       "architect": {
>         "build": {
>           "builder": "@angular-devkit/build-angular:browser",
>           "options": {
>             "outputPath": "dist",
>             "index": "src/index.html",
>             "main": "src/main.ts",
>             "tsConfig": "src/tsconfig.app.json",
>             "polyfills": "src/polyfills.ts",
>             "assets": [
>               "src/assets",
>               "src/favicon.ico"
>             ],
>             "styles": [
>               "src/styles-app-loading.scss",
>               "src/styles.css",
>               "node_modules/angular-calendar/css/angular-calendar.css",
>               "node_modules/font-awesome/css/font-awesome.min.css",
>               "node_modules/primeng/resources/themes/omega/theme.css",
>               "node_modules/primeng/resources/primeng.min.css",
>               "node_modules/onsenui/css/onsenui.css",
>               "node_modules/onsenui/css/onsen-css-components.css"
>             ],
>             "scripts": []
>           },
>           "configurations": {
>             "production": {
>               "optimization": true,
>               "outputHashing": "all",
>               "sourceMap": false,
>               "extractCss": true,
>               "namedChunks": false,
>               "aot": true,
>               "extractLicenses": true,
>               "vendorChunk": false,
>               "buildOptimizer": true,
>               "fileReplacements": [
>                 {
>                   "replace": "src/environments/environment.ts",
>                   "with": "src/environments/environment.prod.ts"
>                 }
>               ]
>             }
>           }
>         },
>         "serve": {
>           "builder": "@angular-devkit/build-angular:dev-server",
>           "options": {
>             "browserTarget": "angular:build"
>           },
>           "configurations": {
>             "production": {
>               "browserTarget": "angular:build:production"
>             }
>           }
>         },
>         "extract-i18n": {
>           "builder": "@angular-devkit/build-angular:extract-i18n",
>           "options": {
>             "browserTarget": "angular:build"
>           }
>         },
>         "test": {
>           "builder": "@angular-devkit/build-angular:karma",
>           "options": {
>             "main": "src/test.ts",
>             "karmaConfig": "./karma.conf.js",
>             "polyfills": "src/polyfills.ts",
>             "tsConfig": "src/tsconfig.spec.json",
>             "scripts": [],
>             "styles": [
>               "src/styles-app-loading.scss",
>               "src/styles.css",
>               "node_modules/angular-calendar/css/angular-calendar.css",
>               "node_modules/font-awesome/css/font-awesome.min.css",
>               "node_modules/primeng/resources/themes/omega/theme.css",
>               "node_modules/primeng/resources/primeng.min.css",
>               "node_modules/onsenui/css/onsenui.css",
>               "node_modules/onsenui/css/onsen-css-components.css"
>             ],
>             "assets": [
>               "src/assets",
>               "src/favicon.ico"
>             ]
>           }
>         },
>         "lint": {
>           "builder": "@angular-devkit/build-angular:tslint",
>           "options": {
>             "tsConfig": [
>               "src/tsconfig.app.json",
>               "src/tsconfig.spec.json"
>             ],
>             "exclude": [
>               "**/node_modules/**"
>             ]
>           }
>         }
>       }
>     },
>     "angular-e2e": {
>       "root": "",
>       "sourceRoot": "e2e",
>       "projectType": "application",
>       "architect": {
>         "e2e": {
>           "builder": "@angular-devkit/build-angular:protractor",
>           "options": {
>             "protractorConfig": "./protractor.conf.js",
>             "devServerTarget": "angular:serve"
>           }
>         },
>         "lint": {
>           "builder": "@angular-devkit/build-angular:tslint",
>           "options": {
>             "tsConfig": [
>               "e2e/tsconfig.e2e.json"
>             ],
>             "exclude": [
>               "**/node_modules/**"
>             ]
>           }
>         }
>       }
>     }
>   },
>   "defaultProject": "angular",
>   "schematics": {
>     "@schematics/angular:component": {
>       "prefix": "app",
>       "styleext": "scss"
>     },
>     "@schematics/angular:directive": {
>       "prefix": "app"
>     }
>   }
> }

**Comment by Sabutha** [comment] 2018-07-06 11:20
I have the same problem. It shows this error: Uncaught Error: Attempting to attach an unknown Portal type. BasePortalOutlet accepts either a ComponentPortal or a TemplatePortal.

**Comment by Richi2293** [comment] 2018-07-07 08:47
I'm having similar problems with other graphics components, I don't know why there is this problem in production

**Comment by josephperrott** [comment] 2018-07-16 21:12
Unfortunately I cannot reproduce this myself.

From the looks of your error it looks like `document` is not being injected.  

Specifically `@Inject(DOCUMENT) private _document: any,` in the `Overlay` constructor seems to be undefined.

If you can provide a reproduction via stackblitz that would allow us to be able to investigate further.

**Comment by josephperrott** [comment] 2018-09-10 22:18
Closing as we are not be able to reproduce this issue.

**Closed by josephperrott** 2018-09-10 22:18 UTC
Labels: cannot reproduce
