### ISSUE TITLE
mat-error doesn't show

### ISSUE THREAD

**Issue by mluis** [angular/material2#11555] opened 2018-05-29 10:08 UTC
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

mat-error should show

#### What is the current behavior?

mat-error doesn't show

#### What are the steps to reproduce?
```
 <mat-form-field>
            <input name="address" #address="ngModel" [(ngModel)]="ethernet.address" matInput placeholder="Static IP Address">
            <mat-error *ngIf="!(ethernet.address | ValidateIP)">
              Invalid IP Address
            </mat-error>
 </mat-form-field>
```

#### Is there anything else we should know?

Angular 5.2.9

**Comment by CDDelta** [comment] 2018-05-29 10:27
You need to provide a proper reproduction through StackBlitz to show the problem here. Is it possible that your `ValidateIP` pipe is not working correctly? I really doubt the problem is with material here.

**Comment by mluis** [comment] 2018-05-29 10:35
@CDDelta as I change <mat-error> do <div> the message shows and hide as expected, but not as mat-error, naturally.

**Comment by CDDelta** [comment] 2018-05-29 10:37
What version of material are you using?

**Comment by mluis** [comment] 2018-05-29 10:38
"@angular/material": "^5.2.4"

**Comment by CDDelta** [comment] 2018-05-29 10:49
Can you create a StackBlitz of your problem? I can't reproduce it. [https://stackblitz.com/edit/angular-qdzsd4?file=app/form-field-error-example.html](Example)

**Comment by mluis** [comment] 2018-05-30 16:29
@CDDelta thanks for the stackblitz. I managed to change it and the result is here: [https://stackblitz.com/edit/angular-qdzsd4-6ejnba?file=app%2Fform-field-error-example.html](https://stackblitz.com/edit/angular-qdzsd4-6ejnba?file=app%2Fform-field-error-example.html)
As you can see, I have hardcoded a string to the pipe test and if you change `mat-error` to `div` then the message appears.

**Comment by josephperrott** [comment] 2018-05-31 20:54
Closing as this is working as expected.  The `mat-error` element only becomes visible through the form field control failing validation.

**Closed by josephperrott** 2018-05-31 20:54 UTC

**Comment by mluis** [comment] 2018-06-14 16:57
I'm trying to have the right behaviour with a validator but probably I'm doing something wrong. Would you mind checking out this stackblitz ?  [https://stackblitz.com/edit/angular-qdzsd4-6ejnba?file=app%2Fvalidate-ip.directive.ts](https://stackblitz.com/edit/angular-qdzsd4-6ejnba?file=app%2Fvalidate-ip.directive.ts)

**Comment by kylecordes** [comment] 2018-06-26 14:37
I realize the current behavior is not considered a bug, but I did find it surprisingly inconvenient and unexpected. There are many cases where  the user will benefit from seeing a validation error immediately while still typing a value into a field; to do that, following the documentation, I have to write a custom error matcher. Of course this is easy to do, but it also seems like a long way around the block for what could be a trivial switch. So I guess this is also a feature request to improve the developer ergonomics around choosing between different common ways of using a mat-error.

**Comment by simeyla** [comment] 2019-01-03 22:50
This stackoverflow question is useful

https://stackoverflow.com/questions/46745171/angular-material-show-mat-error-on-button-click

One common situation you'll see this is in a username/password form where you hit enter inside the 'password' field. This field does NOT count as touched - therefore the error won't show even though `form.controls.password == 'INVALID'`. Because `form.controls.password.touched == false` it's not showing.

To demonstrate this: try focussing (click) on password, then go back to username, then password and hit enter (with bad credentials). It will then show the error since it was previously touched.

I do actually believe it's a bug in the documentation. It currently says:

> By default, these error messages are shown when the control is invalid and either the user has interacted with (touched) the element or the parent form has been submitted.

But this isn't true. The control must have been touched even if the parent form is submitted.
