### ISSUE TITLE
Deleting selection and re-choosing causes wrong selection

### ISSUE THREAD

**Issue by inthegarage** [angular/material2#4356] opened 2017-05-02 12:59 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When deleting an old selection and choosing a new one and then select enter it should choose the new selection. 

#### What is the current behavior?
When deleting an item and then selecting the new one only the new one should be sent to onSelection change. Delete the current one several times and select a new one, you will see eventually in the console that the new one and then the old one are reported, the old one being last.  The old selection is actually being seen on onSelectionChange. Do not use the mouse as that works fine, use keyboard arrows and enter.

#### What are the steps to reproduce?
http://plnkr.co/edit/9ECG85?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
4.1.0 + 2.0.0-beta.3 &Windows & all browsers (FF & Chrome/Opera)

**Comment by willshowell** [comment] 2017-05-02 13:26
Looks like a dupe of #4094. Fix on the way in #4187

**Comment by inthegarage** [comment] 2017-05-02 13:28
Thanks Will, I can check via the plunkr at any-time. github search wasn't being helpful on the search, hence the possible duplicate.

**Closed** 2017-05-04 16:48 UTC
