### ISSUE TITLE
add "disabled" properties in md-chip with it's description.

### ISSUE THREAD

**Issue by hiepxanh** [angular/material2#5527] opened 2017-07-06 02:21 UTC
#### What is the expected behavior?
- add disabled properties in [chips api](https://material.angular.io/components/chips/api)
- add Description about disabled.
- add the example using chips with disabled.

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/16970990/27892663-349ef1ce-622b-11e7-889e-b037ce1b00b4.png)
md chip missing "disabled" Properties in [chips api](https://material.angular.io/components/chips/api)

#### What are the steps to reproduce?
I think this is not necessary

#### What is the use-case or motivation for changing an existing behavior?
I create tags input.
I use the input textbox to enter tags value, then map the value to a tag list. then show it on chips.
So it necessary to disable the chips.  Look like this:
![image](https://user-images.githubusercontent.com/16970990/27892806-e1b7f0ae-622b-11e7-8834-57f4dd9da727.png)
It takes me 4 hours to investigate this property because the docs are missing.
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
it on current docs on material.angular.io.

#### Is there anything else we should know?
nothings, just add more guide to the docs.
thanks you

**Comment by willshowell** [comment] 2017-07-06 13:11
Duplicate of https://github.com/angular/material2/issues/5284

**Closed** 2017-07-06 13:13 UTC
