### ISSUE TITLE
Datepicker selects the wrong date 

### ISSUE THREAD

**Issue by p-jan** [angular/material2#4588] opened 2017-05-16 12:58 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Datepicker always selects the correct date

#### What is the current behavior?
If you select a date like 10/10/1995 in the popup, it will actually select as value 10/9/1995
Although strangely enough selecting 10/10/1996 happens just fine

#### What are the steps to reproduce?
See:
http://plnkr.co/edit/7aH7SRuQAKs6Qe15PBzK?p=preview

**Comment by fxck** [comment] 2017-05-16 13:44
Dupe of #4358, read https://github.com/angular/material2/issues/4358#issuecomment-299661961

You need to write your own adapter along with your own parser, or use something third party, like `momentjs` (which is the only lib I'm aware of being able to parse properly). 

`date-fns` will support parsing eventually and is much smaller than momentjs, but it doesn't at the moment.

**Comment by jelbourn** [comment] 2017-05-18 23:54
See #4358

**Closed by jelbourn** 2017-05-18 23:54 UTC
