### ISSUE TITLE
Mat-Table : Add vertical scrolling only on mat rows and not on mat header row.

### ISSUE THREAD

**Issue by razorhenry1** [angular/material2#10698] opened 2018-04-04 12:39 UTC
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Scroll should start from mat-rows ( tbody ) and not mat-header-rows (thead) .

#### What is the current behavior?
Right now , adding a scroll to mat-table, adds an overflow, starting from the header row level.

#### What are the steps to reproduce?
https://stackblitz.com/angular/jxdglymymvg?file=app%2Ftable-filtering-example.ts
Scroll appears at thead level ( mat-header- rows )

#### What is the use-case or motivation for changing an existing behavior?
The header usually remained fixed and overflow starts from tbody level.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Version : 5.1
Angular Material Version : 5.1.1

**Comment by donroyco** [comment] 2018-04-04 13:16
Duplicate of #5885

**Closed** 2018-04-04 16:58 UTC

**Comment by bit7** [comment] 2018-08-23 20:39
How do we still not have scrollable tables in the year 2018?  Who's running the show around here?

**Comment by lramondev** [comment] 2019-01-15 19:42
https://v0.material-ui.com/#/components/table
