### ISSUE TITLE
(datepicker) supports UNIX time

### ISSUE THREAD

**Issue by msc117** [angular/material2#7435] opened 2017-09-30 00:52 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
`startAt` `min` `max` properties support UNIX time input
https://github.com/angular/material2/blob/master/src/lib/datepicker/coerce-date-property.ts#L22

#### What is the current behavior?
Throws error
https://github.com/angular/material2/blob/master/src/lib/datepicker/coerce-date-property.ts#L33

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-hir6qs

#### What is the use-case or motivation for changing an existing behavior?
Allow UNIX time formats

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest

**Comment by julianobrasil** [comment] 2017-09-30 01:33
Dupe of #7286

**Comment by jelbourn** [comment] 2017-10-01 13:21
Duplicate of #7286

**Closed by jelbourn** 2017-10-01 13:21 UTC
