### ISSUE TITLE
Focus effect for slider not working

### ISSUE THREAD

**Issue by myrubapa** [angular/material2#3442] opened 2017-03-05 14:11 UTC
#### Bug
Focus effect for radio-button and checkbox not working

#### What is the expected behavior?
I use hotkey(Tab or Shift+Tab) to switch between elements. I should know my current position
(https://material.angularjs.org/latest/demo/checkbox) round effect when focusing checkbox

#### What is the current behavior?
For select and other components work somehow but radio-button and checkbox nothing effect
(https://material.angular.io/components/component/checkbox)

#### Which versions of Angular, Material, OS, browsers are affected?
2.4.0, 2.0.0, ArchLinux, Chromium

#### Is there anything else we should know?
Not

**Comment by myrubapa** [comment] 2017-03-05 20:05
Same bug in slider component

**Comment by kara** [comment] 2017-03-05 21:30
This looks like a dupe of https://github.com/angular/material2/issues/3102. Fixed in https://github.com/angular/material2/pull/3402 and https://github.com/angular/material2/pull/3403, so you should see it in the next release.

I'm not seeing the focus indication on slider, though.  + @mmalerba

**Closed** 2017-03-13 21:13 UTC
Labels: a11y, has pr, P3: important
