### ISSUE TITLE
Lazy Loaded MatMenu duplicates content when opened too fast

### ISSUE THREAD

**Issue by DanielNetzer** [angular/material2#11432] opened 2018-05-21 09:24 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
MatMenu to show the content only one time

#### What is the current behavior?
MatMenu duplicates the content when opened/closed fast

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
https://stackblitz.com/edit/angular-h1j24x?file=src%2Findex.html
open and close one of the menu's fast and it will duplicate the contents.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
version ^6.0.0

**Comment by crisbeto** [comment] 2018-05-21 09:33
Closing as a duplicate of https://github.com/angular/material2/issues/11331.

**Closed by crisbeto** 2018-05-21 09:33 UTC
