### ISSUE TITLE
Disabled input cuts off lowercase descenders

### ISSUE THREAD

**Issue by LauraTGail** [angular/material2#9916] opened 2018-02-13 11:19 UTC
Line height needs setting on disabled input fields, to prevent descender of lowercase words being cut off.

<input matInput placeholder="Name" value="the bottom of the g will be cut off" disabled>

Only visible in Google Chrome Version 64.0.3282.140 (64-bit). No issues when testing in Edge.

**Comment by mmalerba** [comment] 2018-02-15 23:20
dupe of #9738

**Closed by mmalerba** 2018-02-15 23:20 UTC
