### ISSUE TITLE
Angular Material theming - different primary color

### ISSUE THREAD

**Issue by theunreal** [angular/material2#13856] opened 2018-10-29 12:16 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Color should be the same in all components

#### What is the current behavior?
I have 2 themes.
1. Default
2. Alternative, used when a condition is met

theme.scss

```
$candy-app-primary: mat-palette($mat-blue, A700);
$candy-app-accent:  mat-palette($mat-orange, A200, A100, A400);
$candy-app-warn:    mat-palette($mat-red);
$candy-app-theme: mat-light-theme($candy-app-primary, $candy-app-accent, $candy-app-warn);

@include angular-material-theme($candy-app-theme);

.alternate-theme {
  $alternate-primary: mat-palette($mat-light-blue);
  $alternate-accent:  mat-palette($mat-orange, A200, A100, A400);
  $alternate-warn:   mat-palette($mat-red);
  $alternate-theme:   mat-light-theme($alternate-primary, $alternate-accent, $alternate-warn);
  @include angular-material-theme($alternate-theme);
}

@include alternative($candy-app-theme);
```

alternative.scss
```
@import '../node_modules/@angular/material/theming';
@mixin alternative($theme) {
  // Extract whichever individual palettes you need from the theme.
  $primary: map-get($theme, primary);
  $accent: map-get($theme, accent); // Use mat-color to extract individual colors from a palette as necessary.

  .extend-toolbar {
    background-color:  mat-color($primary);
    color: white;
  }

  .primaryBg {
    background-color:  mat-color($primary) !important;
    color: #eee !important;
  }

}
```

In my main component:

```
              this.overlayContainer.getContainerElement().classList.add('alternate-theme');
              this.componentCssClass = 'alternate-theme';
```

Look at the following picture: 
![image](https://user-images.githubusercontent.com/6171883/47648966-5e5b2e00-db84-11e8-8ab0-42b801e39399.png)

One chip is in one component, the chip in the bottom is in another component. Both assigned color="primary", but the first one shows the default theme color (dark blue), while the other one shows the alternate color (light blue).
Both should have the light blue primary color (alternate theme).

#### What are the steps to reproduce?
Not yet

#### What is the use-case or motivation for changing an existing behavior?
Bugfix

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.0.1 / Material 7.0.2

**Comment by josephperrott** [comment] 2018-10-30 17:29
After reading through your issue I am not quite sure of the issue you are seeing.  The way I read it, it sounds to be working as expected.

Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

**Comment by theunreal** [comment] 2018-10-31 07:43
@josephperrott There are 2 mat-chips in the picture I posted. both of them use color="primary" attribute and both show different colors (no extra styles on them).

How is it possible?

**Comment by josephperrott** [comment] 2018-11-27 15:18
Since theming is done via css styling, it is possible that the second button in the image is within a container that which causes the css selector to be matches for a different theme.

For example if you have in your sass:
```sass
@include angular-material-theme($default-theme);

.alternate-theme {
  @include angular-material-theme($alternate-theme);
}
```

If you resulting DOM in your application is the following:
```html
<body>
...
<button mat-button color="primary">...</button>
<div class="alternate-theme">
  <button mat-button color="primary">...</button>
</div>
```

The first button would be a different theme than the second.  Closing as its not possible to weigh in further without a reproduction.

**Closed by josephperrott** 2018-11-27 15:18 UTC
Labels: cannot reproduce
