### ISSUE TITLE
[radio-button] Unable to one-way bind to a property accessible only via a getter

### ISSUE THREAD

**Issue by RoxKilly** [angular/material2#1036] opened 2016-08-13 18:45 UTC
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

Radio button selection should work when its value is one-way bound to a property readable only via `get property()`
#### What is the current behavior?

It's impossible to select or deselect a radio button.
#### What are the steps to reproduce?
- Open [this plunker](http://plnkr.co/edit/rEVJtUIPSjAgk6waw0xz?p=preview)
- Notice that the 3rd radio group cannot be interacted with. This is true of all radio groups whose buttons are one-way bound to a model property declared like

```
get options_3(){
    return [
        { name:'One', value:1},
        {name:'Two', value:2}
];};
```

And bound with a template like

```
<md-radio-group name="group_3">
<md-radio-button *ngFor="let o of options_3" [value]="o.value">{{o.name}}</md-radio-button>
</md-radio-group>
```
#### What is the use-case or motivation for changing an existing behavior?

It's a bug
#### Which versions of Angular, Material, OS, browsers are affected?

`Angular 2 rc.5`, `Material alpha 7-2`, `Win 7 x64`, `Firefox 48`
#### Is there anything else we should know?

This is a regression. I noticed the bug after upgrading from `Angular 2 rc.4`, `Material alpha 6` to the versions above.

**Comment by tinayuangao** [comment] 2016-11-04 00:02
The problem is `get options_3` returns a new map whenever `options_3` is called. In that case, the `md-radio-group` will generate a new list of `md-radio-button`. 

Clicking on the radio buttons (and other activities) will trigger the `options_3` function and cause the existing radio buttons to be replaced by new ones. The new buttons haven't received any selection event, so they behave like not clickable.

**Comment by tinayuangao** [comment] 2016-11-04 00:05
The correct way to do it is your `get options_2` if you really need a function in the `*ngFor` loop. Closing this issue.

**Closed by tinayuangao** 2016-11-04 00:05 UTC
Labels: P2: required
