### ISSUE TITLE
Datepicker User Experience - Position should not change

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#5548] opened 2017-07-06 18:35 UTC
#### What is the expected behavior?
When navigating between months in Datepicker, the position of the datepicker dialog should not change.

#### What is the current behavior?
If the datepicker appears above the control and we have to navigate between the months, switching to another month changes the height of the datepicker dialog, which ultimately changes its position. Which creates inconvenience since we have to reposition the mouse pointer on navigation control.

#### What are the steps to reproduce?

Visit https://material.angular.io/components/datepicker/examples
Resize the browser window and scroll the page such that the datepicker control is at the bottom of the windows. 
Now click the datepicker icon, it should open the datepicker above the text box control.
Try navigating between months.

**Comment by julianobrasil** [comment] 2017-07-06 18:47
I noticed it too. It's kind of anoying if you have to jump fast through 5 or 6 months. In fact I'm working in a page right now with the console open that caused it. I click in in the left arrow and the calendar shrinks making the next click hitting the page background.

![image](https://user-images.githubusercontent.com/25405143/27927390-fd2b4db4-6261-11e7-83ff-fa82d50c3ce8.png)

![image](https://user-images.githubusercontent.com/25405143/27927412-0b9e1b42-6262-11e7-8e20-83daa50e6869.png)

**Comment by julianobrasil** [comment] 2017-07-06 18:52
@mmalerba, maybe something like what is sugested in #5543, could avoid this in an elegant way.

**Comment by jelbourn** [comment] 2017-07-07 04:08
Dupe of #5426

**Closed by jelbourn** 2017-07-07 04:08 UTC

**Comment by naveedahmed1** [comment] 2017-07-07 09:52
@jelbourn just clarify, I am referring to switching between months using the next/previous arrows shown on top right of the datepicker.
