### ISSUE TITLE
Input placeholder doesnt rise when set value after beta.10

### ISSUE THREAD

**Issue by Knoxvillekm** [angular/material2#7066] opened 2017-09-14 07:46 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The placeholder should be placed above the input.

#### What is the current behavior?
When set value with { emitEvent: false }, the placeholder however, stays in the field, overlapping the value. See screenshot below:
![input](https://user-images.githubusercontent.com/11072464/30417792-94d94cc0-9939-11e7-8584-a03600490b88.jpg)

#### What are the steps to reproduce?
Plunker template: https://plnkr.co/edit/sJzdfPYWoENNXHcQcLwG?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.6
Angular Material 2.0.0-beta.10
Windows 10
Typescript 2.5.2

**Comment by julianobrasil** [comment] 2017-09-14 12:05
Related to #6837 (with PR #6839).

**Comment by jlkeiper** [comment] 2017-09-14 15:06
I see the same behavior on non-visible forms rendered in a hidden but initialized component, using `2.0.0-beta.11-f6c9172`.

**Comment by gise88** [comment] 2017-09-15 03:46
@jlkeiper same issue! I have followed the workaround that have pointed out @julianobrasil [here](https://github.com/angular/material2/issues/7070#issuecomment-329503789) and I solved

**Comment by jlkeiper** [comment] 2017-09-15 12:45
@gise88 thanks, I was hoping to allow the component to initialize (makes a few calls while setting things up), but realize that may not be necessary if I pull it up a level. I'll try this out!

**Comment by jlkeiper** [comment] 2017-09-21 15:16
Looks like a fix was committed yesterday, waiting for my local to catch up to it on `material2-builds`. Can't wait for beta-11!

**Closed** 2017-09-24 13:07 UTC

**Comment by vokk** [comment] 2017-09-25 06:07
Don't work with emitEvent: false in beta.11.

**Comment by julianobrasil** [comment] 2017-09-25 09:29
@vokk, could please reproduce it here: https://plnkr.co/edit/vJ74Wy9AqqkqVFZJ4mG8?p=preview

It worked for me.

**Comment by Knoxvillekm** [comment] 2017-09-25 09:44
add setTimeout or do this on button click.
https://plnkr.co/edit/ctAIbwPeAB1tK2LsU4L4?p=preview

**Comment by dzolnjan** [comment] 2017-09-28 10:17
@DevVersion it doesnt work if value it set after component is initialized (setTimeout and button click)
check examples above created by @Knoxvillekm
