### ISSUE TITLE
Nav Tabs line acts strange

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#3754] opened 2017-03-24 09:31 UTC
#### Bug, feature request, or proposal:
Right after initializing the component the bottom line of the tab has a wrong size;

![image](https://cloud.githubusercontent.com/assets/6654388/24288143/92afec2e-107c-11e7-9aa0-96912411b66a.png)

As soon as you navigate to the second tab (DRV in my screenshot) and then back to the first one the line has the correct size;

![image](https://cloud.githubusercontent.com/assets/6654388/24288198/c068e0b2-107c-11e7-891b-c635df0a3764.png)

Tabs are initialized like this:
 <a md-tab-link
           *ngFor="let c of clusters"
           [routerLink]="[c.id]"
           routerLinkActive #rla="routerLinkActive"
           [active]="rla.isActive">
          {{c.name}}
        </a>

#### What is the expected behavior?
Line should habe the correct size

#### What is the current behavior?
See screenshots

#### Which versions of Angular, Material, OS, browsers are affected?
NG 2.3.1
Material 2.0.0-beta.2

**Comment by willshowell** [comment] 2017-03-24 13:41
Looks like a dupe of #3495

**Comment by willshowell** [comment] 2017-03-30 13:24
@mbeckenbach with #3622 landed, are you still seeing the issue?

**Comment by mbeckenbach** [comment] 2017-03-31 08:45
@willshowell As far as i understand this, it should be fixed in master? At the moment i can't update my app from beta.2 to something newer for deadline reasons.

**Comment by willshowell** [comment] 2017-03-31 13:15
Yes, it should be fixed in master. I say *should* because that PR was really set out to solve a different issue with layout direction changes, but I'm not able to replicate the issue anymore using a Plunker based on master.

**Comment by jelbourn** [comment] 2017-04-09 03:03
Closing this as "suspected to be fixed". Feel free to re-open if it's still an issue.

**Closed by jelbourn** 2017-04-09 03:03 UTC
