### ISSUE TITLE
mat-chip selected no matter what

### ISSUE THREAD

**Issue by Corsseir** [angular/material2#11842] opened 2018-06-19 11:03 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
[selectable]="false" should works properly.

#### What is the current behavior?
[selectable]="false" doesn't work

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
```
    <mat-form-field>
      <mat-chip-list #phraseList class="mat-chip-list-stacked" ngDefaultControl formControlName="phrases" [selectable]="false">
        <mat-chip *ngFor="let phrase of phrases.value" [selectable]="false" [selected]="false" [removable]="true" [disabled]="true">
          <span fxFlex="100%">{{ phrase }}</span>
        </mat-chip>
        <input class="w-100" fxFlex="0%" placeholder="Phrase" [matChipInputFor]="phraseList" [matChipInputSeparatorKeyCodes]="separatorKeysCodes"
          [matChipInputAddOnBlur]="true" (matChipInputTokenEnd)="addPhrase($event)" />
      </mat-chip-list>
    </mat-form-field>

    this.form = new FormGroup({
      phrases: new FormControl(new Array<string>())
    });

    addPhrase(e: MatChipInputEvent): void {
        const input = e.input;
        const value = e.value;
        const phrases = this.phrases.value;

        if ((value || '').trim()) {
          phrases.push(value.trim());
          this.phrases.setValue(phrases);
        }

        if (input) {
          input.value = '';
        }
    }

    get phrases() {
        return this.form.get('phrases');
    }
```

#### What is the use-case or motivation for changing an existing behavior?
-

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
6.0.4

#### Is there anything else we should know?
![screenshot from 2018-06-19 13-03-19](https://user-images.githubusercontent.com/11137173/41593689-305f6960-73c1-11e8-818d-ea8d2344357b.png)

**Comment by tinayuangao** [comment] 2018-06-19 18:13
@Corsseir Could you please provide a stackblitz reproduction? I cannot reproduce this issue

`[selectable]="false"` is working properly here: https://stackblitz.com/edit/angular-wcfsvk?file=app%2Fchips-input-example.html

**Comment by 1083** [comment] 2018-07-09 20:39
@tinayuangao That's not working properly for me: what difference do you see when toggling `[selectable]`? I get no behavior change, and chips are always selectable. Setting `[removable]="false"` also does nothing for me.

**Comment by Ferrin13** [comment] 2018-08-09 18:35
@tinayuangao This is what appears for me what I click on a chip (or tab to it) in Chrome 68.0.3440.84 and Firefox 61.0.2 for the stackblitz you provided. Toggling the selectable flag has no visual effect when selecting/de-selecting the chip. 

Is `[selectable]` only supposed to cause the selected state to be ignored? Reading the documentation, it does not explicitly state that the chip will not be selectable visually, though that seems like a logical conclusion of not being selectable. 

![selectablebroken](https://user-images.githubusercontent.com/25914476/43918544-908d07de-9bd0-11e8-9a0f-c43eda48c667.png)
![selectablebroken2](https://user-images.githubusercontent.com/25914476/43918508-7ec433ba-9bd0-11e8-8f6d-c239eeda820d.jpg)

**Comment by crisbeto** [comment] 2018-08-15 18:34
@Ferrin13 the example that you're showing isn't the selected state, it's the focused state. The selected state looks like this and it's toggled by pressing space on a selectable chip:

![angular-wcfsvk_-_stackblitz_-_google_chrome_2018-08-15_20-33-58](https://user-images.githubusercontent.com/4450522/44166024-96e18480-a0ca-11e8-88a7-744a86a57ab1.png)

**Comment by Ferrin13** [comment] 2018-08-15 18:58
@crisbeto Ah, I assumed the selected state would be toggled by clicking. I assume in order to prevent any visual change from occurring on focus I would need to add custom CSS?

**Comment by crisbeto** [comment] 2018-08-15 19:00
Yes, you should be able to target the `.mat-standard-chip:focus` selector.

**Comment by Bored-Bohr** [comment] 2018-08-21 19:33
It seems that `[selectable]` works with `mat-chip` but not `mat-chip-list`

https://stackblitz.com/edit/angular-pkocrr?file=app/chips-overview-example.html
notice that you are unable to select `One` but can select the rest

**Comment by josephperrott** [comment] 2018-09-06 21:12
Closing as the initial issue has been resolved as a miscommunication about what the meaning of selected in the context of MatChips.

**Closed by josephperrott** 2018-09-06 21:12 UTC
