### ISSUE TITLE
Input required form field indactor missing

### ISSUE THREAD

**Issue by ghaddon** [angular/material2#8114] opened 2017-10-29 22:26 UTC
#### Bug, feature request, or proposal:
 On Input control flagged as required does not show when using FormBuilder.

#### What is the expected behavior? 
Would expect same behavior using template design method.

#### What is the current behavior?
 No required indicator showing to the right of placeholder value when using the model method and Buildform.

#### What are the steps to reproduce?
Create input form control using FormBuilder and require field.

#### What is the use-case or motivation for changing an existing behavior?
Shows required indicator in template form creation but not FormBuilder method.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I see it in Chrome Version: 61.0.3163.100 (Official Build) (64-bit).
Using Angular Version: 4.4.5
Using Angular Material Version: 2.0.0-beta.12
Using TypeScript Version: 2.3.3

#### Is there anything else we should know?
Nope

**Comment by donroyco** [comment] 2017-10-30 13:17
Can you add a Plunker or StackBlitz that describes your issue?

Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by willshowell** [comment] 2017-10-30 16:25
See https://github.com/angular/material2/issues/2574

**Comment by josephperrott** [comment] 2017-10-30 22:14
Closing as duplicate of #2574

**Closed by josephperrott** 2017-10-30 22:14 UTC

**Comment by ghaddon** [comment] 2017-10-31 17:22
Have not had time to create Plunker to show the problem. I read #2574 but, not sure it is the same. Can you direct me to the build to expect @2574 is fixed?

**Comment by willshowell** [comment] 2017-10-31 17:47
@ghaddon if you can show a reproduction that is distinctive from the description in #2574, then that would be worth looking into. But your description of the issue is nearly identical to that one.

**Comment by ghaddon** [comment] 2017-10-31 20:58
Will,

Just completed sample of error I'm getting. can find on[https://angular-material2-issue.stackblitz.io]( https://angular-material2-issue.stackblitz.io). 

Thanks,
Gary

**Comment by willshowell** [comment] 2017-10-31 21:02
@ghaddon try forking the stackblitz. Your link just points to the default template.

**Comment by ghaddon** [comment] 2017-10-31 21:06
I forked it and it gave me the following https://angular-material2-issue-nagunv.stackblitz.io.
Gary
   On Tuesday, October 31, 2017, 2:03:24 PM MST, Will Howell <notifications@github.com> wrote: 
 
 
@ghaddon try forking the stackblitz. Your link just points to the default template.

**Comment by willshowell** [comment] 2017-10-31 21:13
@ghaddon it's still empty

**Comment by ghaddon** [comment] 2017-10-31 21:34
Try this url: https://angular-material2-issue-ei1ca7.stackblitz.io

   On Tuesday, October 31, 2017, 2:14:14 PM MST, Will Howell <notifications@github.com> wrote: 
 
 
@ghaddon it's still empty

**Comment by willshowell** [comment] 2017-11-01 01:43
@ghaddon yeah the issue you are describing is exactly the same as #2574

"MatInput doesn't set required asterisk when the validator is set in reactive forms"

**Comment by ghaddon** [comment] 2017-11-01 16:38
Thanks Will.
   On Tuesday, October 31, 2017, 6:43:46 PM MST, Will Howell <notifications@github.com> wrote: 
 
 
@ghaddon yeah the issue you are describing is exactly the same as #2574

"MatInput doesn't set required asterisk when the validator is set in reactive forms"
