### ISSUE TITLE
md-select does not show selected value when options are initiliased after ngInit

### ISSUE THREAD

**Issue by hkoelewijn** [angular/material2#2580] opened 2017-01-10 07:31 UTC
#### Bug, feature request, or proposal:
When  you use md-select with an array of options that is initialised after ngInit has run the current value is not shown.

#### What is the expected behavior?
When initializing the options array at any time, md select should show the current value.

#### What is the current behavior?
When initializing the options array at any time, md select does not show the current value

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
 http://embed.plnkr.co/VSvOY4/

#### What is the use-case or motivation for changing an existing behavior?
The md-select should mimic the behaviour of the select as much as possible

#### Which versions of Angular, Material, OS, browsers are affected?
Material: 2.0.0-alpha.11-3
angular: 2.2.1
Chrome 55 
(I did not test other browsers or versions)

#### Is there anything else we should know?
The plunker example shows the difference in behaviour of the md-select and the select. As you can see, the select dropdown picks up the changes, while the md-select does not in exactly the same scenario
The select does work if the options are initialised directly (in the template or using an array that is initialised in the constructor)

**Comment by crisbeto** [comment] 2017-01-10 08:07
Closing as a duplicate of https://github.com/angular/material2/issues/2497. Also there's a pending fix for it.

**Closed by crisbeto** 2017-01-10 08:07 UTC
