### ISSUE TITLE
md-datepicker min max error in reactive forms

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#5971] opened 2017-07-22 20:02 UTC
#### Bug, feature request, or proposal:

When using min/max with md-datepicker in reactive forms, it throws below error in console:

```
errors.ts:42 ERROR TypeError: date.getFullYear is not a function
    at NativeDateAdapter.getYear (http://localhost:49547/node_modules/@angular/material/bundles/material.umd.js:4276:21)
    at NativeDateAdapter.DateAdapter.compareDate (http://localhost:49547/node_modules/@angular/material/bundles/material.umd.js:4189:46)
    at MdDatepickerInput._minValidator (http://localhost:49547/node_modules/@angular/material/bundles/material.umd.js:19994:36)
    at eval (http://localhost:49547/node_modules/@angular/forms/bundles/forms.umd.js:474:49)
    at Array.map (native)
    at _executeValidators (http://localhost:49547/node_modules/@angular/forms/bundles/forms.umd.js:474:23)
    at MdDatepickerInput.eval [as _validator] (http://localhost:49547/node_modules/@angular/forms/bundles/forms.umd.js:430:33)
    at MdDatepickerInput.validate (http://localhost:49547/node_modules/@angular/material/bundles/material.umd.js:20160:39)
    at eval (http://localhost:49547/node_modules/@angular/forms/bundles/forms.umd.js:722:52)
    at eval (http://localhost:49547/node_modules/@angular/forms/bundles/forms.umd.js:474:49)
```

**Comment by willshowell** [comment] 2017-07-22 20:26
Dupe of https://github.com/angular/material2/issues/5417?

**Comment by naveedahmed1** [comment] 2017-07-22 20:37
Thanks @willshowell for pointing out, my situation is similar to https://github.com/angular/material2/issues/5417#issuecomment-315518257 and I am using latest beta of Material and latest version of Angular.

**Comment by willshowell** [comment] 2017-07-22 20:39
Are you initializing the value to a string or Date? IIRC the error occurs sometimes when using string

**Comment by naveedahmed1** [comment] 2017-07-22 20:45
Yes, below is my code:


```
<div>
                        <md-input-container>
                            <input mdInput
                                   formControlName="lastDate"
                                   [min]="minDate"
                                   [mdDatepicker]="mdDatepicker"
                                   placeholder="Last Date"
                                   (focus)="mdDatepicker.open()" style="pointer-events:none;" />

                            <button mdSuffix [mdDatepickerToggle]="mdDatepicker" md-tooltip="Select Date"></button>

                        </md-input-container>

                        <md-datepicker #mdDatepicker></md-datepicker>
                    </div>
```


`    public minDate: any = new Date();`

**Comment by willshowell** [comment] 2017-07-22 21:08
I believe to resolve the error, you must use a Date for `lastDate` too

**Comment by mmalerba** [comment] 2017-07-24 17:51
I would actually use `null` for no initial value, I'm not sure if empty string will work in the future

**Comment by mmalerba** [comment] 2017-07-24 17:52
duplicate of #5417

**Closed by mmalerba** 2017-07-24 17:52 UTC

**Comment by iosifpetre18** [comment] 2018-01-29 10:48
I have the same problem, how can I use [min] and [max] options on md2-datepicker with reactive forms?

**Comment by mmalerba** [comment] 2018-01-29 16:32
@iosifpetre18 this issue should be fixed now, so just update to the latest version of Angular Material. If you still see the error feel free to open a new issue with a stackblitz reproduction
