### ISSUE TITLE
[mat-table]: vertical alignment doesn't work on IE 11

### ISSUE THREAD

**Issue by clundberg1** [angular/material2#15124] opened 2019-02-08 03:02 UTC
#### What is the expected behavior?
The cell's content should be vertically aligned.

#### What is the current behavior?
Flex is clearly not working because of the min-height defined on the rows:

![image](https://user-images.githubusercontent.com/29963339/52456706-a1318800-2b1b-11e9-889c-068fa4fbc1c8.png)

**Comment by macjohnny** [comment] 2019-02-08 12:25
duplicate of https://github.com/angular/material2/issues/11470

**Comment by crisbeto** [comment] 2019-02-09 16:54
Closing as a duplicate of #11470.

**Closed by crisbeto** 2019-02-09 16:54 UTC
