### ISSUE TITLE
mat-radio-group data binding requires unique name

### ISSUE THREAD

**Issue by kwall2004** [angular/material2#10030] opened 2018-02-19 22:06 UTC
#### Bug, feature request, or proposal:
If a component contains mat-radio-group, and you create multiple instances of that component, the mat-radio-group names appear to collide.

#### What is the current behavior?
I have to ensure unique mat-radio-group names in order for data binding to work properly.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ujce61?file=app%2Ftest%2Ftest.component.html

**Comment by josephperrott** [comment] 2018-02-20 21:08
Closing as this is working as intended.  Within forms the name for a value control must be unique to prevent this collision.

**Closed by josephperrott** 2018-02-20 21:08 UTC

**Comment by kwall2004** [comment] 2018-02-20 22:10
Within a form, of course names must be unique, but in this example I had 5 separate forms.

In any case, I've updated the example to remove the form altogether and the issue remains.
