### ISSUE TITLE
When we put the condition in Mat-paginator, pagination is not working.

### ISSUE THREAD

**Issue by mdhvfrnd** [angular/material2#10474] opened 2018-03-19 09:56 UTC
Hi when we put the condition still this is not working.

<mat-paginator *ngIf="allItems ?.length > 0" #paginator [pageSize]="50" [pageSizeOptions]="[1,2,4,20, 40,100,150,200]">

If we remove the *ngIf="allItems ?.length > 0", this is working.

**Comment by fxck** [comment] 2018-03-19 10:27
Make a stackblitz reproduction of the problem.

**Comment by mdhvfrnd** [comment] 2018-03-19 10:30
If we put any condition it wont work.

There is no condition in below code.So it will work.
<mat-paginator  #paginator [pageSize]="50" [pageSizeOptions]="[1,2,4,20, 40,100,150,200]">


when we put the condition, this is not working.

<mat-paginator *ngIf="allItems ?.length > 0" #paginator [pageSize]="50" [pageSizeOptions]="[1,2,4,20, 40,100,150,200]">

**Comment by WizardPC** [comment] 2018-03-19 20:11
What if you encapsule the mat-paginator into a div ? To workaround for the moment.

**Comment by mdhvfrnd** [comment] 2018-03-20 05:07
After if condition, now sorting and pagination both are not working. If i will remove if condition both will work. But how i will add the if condition.

<div *ngIf="allItems ?.length > 0">

  <mat-table class="markstable" #table [dataSource]="dataSource" matSort>


    <ng-container matColumnDef="admissionno">
      <mat-header-cell class="markstable" *matHeaderCellDef mat-sort-header>
        <div class="tableheader">Admission No</div>
      </mat-header-cell>
      <mat-cell class="markscell" *matCellDef="let feePayment">
        {{feePayment.admissionno}}
         
         </mat-cell>
    </ng-container>
	
	<mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
    <mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>


  </mat-table>
  <mat-paginator  #paginator [pageSize]="50" [pageSizeOptions]="[2,20, 40,100,150,200]">
  </mat-paginator>
</div>

**Comment by mdhvfrnd** [comment] 2018-03-20 05:08
<div *ngIf="allItems ?.length > 0">

  <mat-table class="markstable" #table [dataSource]="dataSource" matSort>


    <ng-container matColumnDef="admissionno">
      <mat-header-cell class="markstable" *matHeaderCellDef mat-sort-header>
        <div class="tableheader">Admission No</div>
      </mat-header-cell>
      <mat-cell class="markscell" *matCellDef="let feePayment">
        {{feePayment.admissionno}}
         
         </mat-cell>
    </ng-container>
	
	<mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
    <mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>


  </mat-table>
  <mat-paginator  #paginator [pageSize]="50" [pageSizeOptions]="[2,20, 40,100,150,200]">
  </mat-paginator>
</div>

**Comment by mdhvfrnd** [comment] 2018-03-20 05:10
```
<div *ngIf="allItems ?.length > 0">
  <mat-table class="markstable" #table [dataSource]="dataSource" matSort>
    <ng-container matColumnDef="admissionno">
      <mat-header-cell class="markstable" *matHeaderCellDef mat-sort-header>
        <div class="tableheader">Admission No</div>
      </mat-header-cell>
      <mat-cell class="markscell" *matCellDef="let feePayment">
        {{feePayment.admissionno}}         
         </mat-cell>
    </ng-container>
	<mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
    <mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>
  </mat-table>
  <mat-paginator  #paginator [pageSize]="50" [pageSizeOptions]="[2,20, 40,100,150,200]">
  </mat-paginator>
</div> 
```

**Comment by josephperrott** [comment] 2018-03-26 15:58
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate

**Closed by josephperrott** 2018-03-26 15:58 UTC

**Comment by andrewseguin** [comment] 2018-03-27 16:57
I suspect you are trying to get the paginator using `ViewChild`, which won't work since the if statement will block it from getting the child.

**Comment by gauravdeshmukh612** [comment] 2019-02-07 04:54
Put pagination outside of NgIF and apply condition on paginator using following   
<div [hidden]="isLoading">
  <mat-table [dataSource]="dataSource">
  ...
  </mat-table>
</div>
