### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by AlphaIX** [angular/material2#8384] opened 2017-11-12 05:52 UTC
#### Bug, feature request, or proposal:
The master branch was Failed to compile,when I use command `gulp serve:devapp`

#### What is the current behavior?
here are the Error Code Stack:
```
Error: Error: /Users/ydy/Code/WorkSpace/WebstormProjects/material2/src/lib/input/input.ts:48:1: Error encountered in metadata generated for exported symbol 'MatInput': 
 /Users/ydy/Code/WorkSpace/WebstormProjects/material2/src/lib/input/input.ts:165:48: Metadata collected contains an error that will be reported at runtime: Expression form not supported.
  {"__symbolic":"error","message":"Expression form not supported","line":164,"character":47}
    at /Users/ydy/Code/WorkSpace/WebstormProjects/material2/node_modules/@angular/compiler-cli/src/metadata/collector.js:663:27
    at Array.forEach (<anonymous>)
    at validateMetadata (/Users/ydy/Code/WorkSpace/WebstormProjects/material2/node_modules/@angular/compiler-cli/src/metadata/collector.js:651:42)
    at MetadataCollector.getMetadata (/Users/ydy/Code/WorkSpace/WebstormProjects/material2/node_modules/@angular/compiler-cli/src/metadata/collector.js:508:17)
    at LowerMetadataCache.getMetadataAndRequests (/Users/ydy/Code/WorkSpace/WebstormProjects/material2/node_modules/@angular/compiler-cli/src/transformers/lower_expressions.js:263:39)
    at LowerMetadataCache.ensureMetadataAndRequests (/Users/ydy/Code/WorkSpace/WebstormProjects/material2/node_modules/@angular/compiler-cli/src/transformers/lower_expressions.js:209:27)
    at LowerMetadataCache.getRequests (/Users/ydy/Code/WorkSpace/WebstormProjects/material2/node_modules/@angular/compiler-cli/src/transformers/lower_expressions.js:204:21)
    at /Users/ydy/Code/WorkSpace/WebstormProjects/material2/node_modules/@angular/compiler-cli/src/transformers/lower_expressions.js:146:36
    at /Users/ydy/Code/WorkSpace/WebstormProjects/material2/node_modules/typescript/lib/typescript.js:2492:86
    at reduceLeft (/Users/ydy/Code/WorkSpace/WebstormProjects/material2/node_modules/typescript/lib/typescript.js:2188:30)


Failed to compile  using /Users/ydy/Code/WorkSpace/WebstormProjects/material2/src/lib/tsconfig-tests.json




adapter/moment-date-adapter.ts(10,44): error TS2307: Cannot find module '@angular/material'.
adapter/moment-date-adapter.ts(118,37): error TS2339: Property 'locale' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.ts(132,58): error TS2339: Property 'locale' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.ts(143,33): error TS2339: Property 'locale' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.ts(148,46): error TS2339: Property 'locale' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.ts(150,46): error TS2339: Property 'locale' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.ts(191,57): error TS2339: Property 'locale' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-formats.ts(9,30): error TS2307: Cannot find module '@angular/material'.
adapter/index.ts(15,8): error TS2307: Cannot find module '@angular/material'.
adapter/moment-date-adapter.spec.ts(11,64): error TS2307: Cannot find module '@angular/material/core'.
adapter/moment-date-adapter.spec.ts(168,20): error TS2339: Property 'sameDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(267,20): error TS2339: Property 'compareDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(268,20): error TS2339: Property 'compareDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(269,20): error TS2339: Property 'compareDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(270,20): error TS2339: Property 'compareDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(271,20): error TS2339: Property 'compareDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(272,20): error TS2339: Property 'compareDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(273,20): error TS2339: Property 'compareDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(277,20): error TS2339: Property 'clampDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(283,20): error TS2339: Property 'clampDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(289,20): error TS2339: Property 'clampDate' does not exist on type 'MomentDateAdapter'.

```

#### What are the steps to reproduce?
Here are some commands I've used as follows:
1. git clone 
2. npm install -g glup
3. cd material2
4. npm install
5. gulp serve:devapp 

and then compiling failed

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Mac OS 

#### Is there anything else we should know?
I was just beginning to learn about the `Angular`,maybe this is a easy question, I'll appreciate for any help

**Comment by crisbeto** [comment] 2017-11-12 10:15
Closing as a duplicate of https://github.com/angular/material2/issues/8380.

**Closed by crisbeto** 2017-11-12 10:15 UTC
