### ISSUE TITLE
Grid list is not responsive ?

### ISSUE THREAD

**Issue by TitaneBoy** [angular/material2#7154] opened 2017-09-18 22:21 UTC
#### Bug, feature request, or proposal:
Hi guys. I'm trying to have a collection of cards (on multiple line). So I thought that using a [Grid list](https://material.angular.io/components/grid-list/overview) would do the job. So I've used a grid list with 4 columns. I have something like 22 cards.. But When I'm trying to resize the browser to see the "responsive" side effect, What I see is that cards are just shrinked .. I thought that the number of columns will be reduced until to have just one column.

#### What is the expected behavior?
When reducing the browser, cards should not be shrinked and should be moved below, on the next row, keeping its size.

#### What is the current behavior?
Cards are shrinked and contents inside the cards disappear.

#### What are the steps to reproduce?
my-main-component.html
```
<md-grid-list cols="4">
  <md-grid-tile *ngFor="let reading of data.value"><rbwc-measurement-card [data]="reading" class="card-border"></rbwc-measurement-card></md-grid-tile>
</md-grid-list>
```

my-rbwc-measurement-card-component.html:

```
<md-card class="measurement-card" [style]="setCardAlarmStyle()">
  <md-card-header>
    <div md-card-avatar class="measurement-header-image" [style]=setMeasurementAvatar(data.name)></div>
    <md-card-title class="measurement-bold title-layout">{{data.name}}</md-card-title>
  </md-card-header>
  <md-card-content>
    <div> <span class="measurement-bold">Reading:</span> <span [style]="readingFont()">{{data.reading.value}} {{data.reading.units}}</span></div>
    <div *ngIf="data.trend"><span class="measurement-bold">Trend:</span> <span [style]="trendFont()">{{data.trend.value}} {{data.trend.units}}</span></div>
    <form>
      <fieldset *ngIf="data.limits" class="groupBox-border">
        <legend class="groupBox-text-size">Limits:</legend>
        <div *ngFor="let limit of data.limits">{{limit.name}}: <md-form-field floatPlaceholder="never" [style.width.px]="70"><input mdInput [disabled]="disableEdit()" placeholder="{{limit.name}}" type="number" value="{{limit.value}}"><md-icon [ngClass]="{'md-dark md-inactive': disableEdit()}" mdSuffix>mode_edit</md-icon></md-form-field> <span *ngIf="limit.name != limitsNames.TrendLimit">{{limit.units}}</span> <rbwc-trend-limit-units-options *ngIf="limit.name == limitsNames.TrendLimit" [trendReading]="limit"></rbwc-trend-limit-units-options></div>
      </fieldset>
    </form>
  </md-card-content>
  <md-card-actions>
    <button md-button>LIKE</button>
    <button md-button>SHARE</button>
  </md-card-actions>
</md-card>
```

Am I missing something or doing something wrong ? Thank you in advance for your help

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.4.0-RC.0
Material: 2.0.0-beta.10
Typescript: 2.5.2
Browser: Chrome (for now)

Multiple cards look before resizing the browser:
![image](https://user-images.githubusercontent.com/15614466/30567196-37a37ffa-9c9d-11e7-948c-54e5d1c1d47e.png)

Multiple cards look after resizing the browser:
![image](https://user-images.githubusercontent.com/15614466/30567238-78e7d48e-9c9d-11e7-8ab2-095b3bed55a4.png)

**Comment by leocaseiro** [comment] 2017-09-19 02:38
Duplicated of https://github.com/angular/material2/issues/1072

Please read https://github.com/angular/material2/pull/6777

**Comment by leocaseiro** [comment] 2017-09-19 02:43
Perhaps if you use [FlexLayout](https://github.com/angular/flex-layout) instead of Grid List, it would work fine for your use case.

Eq: https://tburleson-layouts-demos.firebaseapp.com/#/responsive

**Comment by jelbourn** [comment] 2017-09-19 04:56
Duplicate of #1072

**Closed by jelbourn** 2017-09-19 04:56 UTC

**Comment by TitaneBoy** [comment] 2017-09-19 21:08
@leocaseiro : Thank you for your references... In #6777 , I could find a [comment](https://github.com/angular/material2/issues/1072#issuecomment-316377292) that talk about an [responsive angular article](http://brianflove.com/2017/05/03/responsive-angular/) that just saved my life. That was what I needed.

Thanks again

**Comment by PurpleEdge2214** [comment] 2018-06-19 04:43
It would be good if the Angular Material website made some mention of responsive layout!

**Comment by rdineshkumar88** [comment] 2018-07-01 10:38
For Angular Material 6.2.1, here's the tutorial to create 12 columns responsive grid. 

https://ampersandacademy.com/tutorials/angular-material/responsive-grid-layout-in-angular-material

**Comment by edifortcarlos** [comment] 2018-07-18 13:11
Hi @PurpleEdge2214, i tryed to follow this exemple https://stackblitz.com/edit/angular-responsive-material-grid-leocaseiro that you sugest but i got this issues in the console

![image](https://user-images.githubusercontent.com/28525027/42881668-c4a82e74-8a8f-11e8-94fb-ddb421796714.png)

I am using "@angular ^6.0.3, @angular/material ^6.3.2 and @angular/flex-layout ^6.0.0-beta.16

Here is my code:

![image](https://user-images.githubusercontent.com/28525027/42883318-30a9439e-8a93-11e8-8bad-1207e1683ac0.png)


`import { Component, OnInit, Input, Output, EventEmitter, AfterContentInit, ViewChild} from '@angular/core';
import { CustomElement } from '../../model/custom-element';
import { MediaChange, ObservableMedia } from '@angular/flex-layout';
import { MatGridList } from '@angular/material';


const ELEMENT_DATA: CustomElement[] = [
  { name: 'Mateus Adelino', owner: 'eu', creation: new Date('10/07/2018'), size: 47 },
  { name: 'albino Pedro', owner: 'zola', creation: new Date('10/08/2018'), size: 57 },
  { name: 'Carlos Adelino', owner: 'eu', creation: new Date('11/07/2018'), size: 20 },
  { name: 'Carolina Pantilha', owner: 'yuri', creation: new Date('27/07/2018'), size: 60 },
  { name: 'Zenildo Garcia', owner: 'eu', creation: new Date('10/08/2018'), size: 30 },
  { name: 'Constantino Pereira', owner: 'eu', creation: new Date('10/07/2018'), size: 44 },
  { name: 'Mateus Quimaka', owner: 'zola', creation: new Date('15/06/2018'), size: 67 },
  { name: 'Pedro Soldado', owner: 'eu', creation: new Date('11/07/2018'), size: 57 },
  { name: 'Quintino Vemba', owner: 'eu', creation: new Date('10/07/2018'), size: 27 }
];

@Component({
  selector: 'app-content-viewer',
  templateUrl: './content-viewer.component.html',
  styleUrls: ['./content-viewer.component.css']
})
export class ContentViewerComponent implements OnInit, AfterContentInit {

  @ViewChild('matgrid') matgrid: MatGridList;

  @Input()
  grid: boolean;

  @Input()
  activeNodeUuid: string;

  @Output()
  clickNode = new EventEmitter<CustomElement>(); // Emissor de evento por click no No

  @Output()
  dblClickNode = new EventEmitter<string>(); // Emissor de evento por duplo click no No

  gridByBreakpoint = {
    xl: 8,
    lg: 5,
    md: 4,
    sm: 3,
    xs: 2
  };

  displayedColumns: string[] = ['name', 'owner', 'creation', 'size'];
  columnsToDisplay: string[] = this.displayedColumns.slice();
  data: CustomElement[] = ELEMENT_DATA;


  constructor(private observableMedia: ObservableMedia) {
  }

  ngOnInit() {
  }

  ngAfterContentInit() {
    this.observableMedia.asObservable().subscribe((change: MediaChange) => {
      this.matgrid.cols = this.gridByBreakpoint[change.mqAlias];
    });
  }

  addColumn() {
    const randomColumn = Math.floor(Math.random() * this.displayedColumns.length);
    this.columnsToDisplay.push(this.displayedColumns[randomColumn]);
  }

  removeColumn() {
    if (this.columnsToDisplay.length) {
      this.columnsToDisplay.pop();
    }
  }

  onSelect(node) {
    this.clickNode.emit(node);
  }

  doDblClickAction() {
    this.dblClickNode.emit('ESTAMOS A CAMINHAR');
  }

  isDate(x) {
    return (null != x) && !isNaN(x) && ('undefined' !== typeof x.getDate);
  }

}
`

I'm sorry if I did not express myself clearly, I'm still new here.
