### ISSUE TITLE
The customizing-the-parse-and-display-formats link does not work

### ISSUE THREAD

**Issue by jarodsmk** [angular/material2#8660] opened 2017-11-27 06:30 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The #customizing-the-parse-and-display-formats link should redirect to the relevant content

#### What is the current behavior?
Clicking on the link redirects to the home page with URL:
https://material.angular.io/#customizing-the-parse-and-display-formats

#### What are the steps to reproduce?

1. Navigate to: https://material.angular.io/components/datepicker/overview
2. Click on the 'Customizing the parse and display formats' link

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All browsers

**Comment by willshowell** [comment] 2017-11-27 16:59
I think the link you mean is,

https://material.angular.io/components/datepicker/overview#customizing-the-parse-and-display-formats

I do vaguely recall this being an issue once before, and you may be running a cached version of the docs site. Try hard reloading.

**Comment by jelbourn** [comment] 2017-11-27 19:27
Visit chrome://serviceworker-internals/ and unregister the worker for material.angular.io. This will clear the service worker cache, which persists through hard refresh.

**Comment by jarodsmk** [comment] 2017-11-28 08:15
@jelbourn - Tried unregistering the material.angular.io service worker, and;

@willshowell - Yea I think that's probably the right URL, didn't know what the right one was, but did try clearing the cache, even reinstalled a new version of Chrome on a colleagues new laptop, can still reproduce

**Comment by DevVersion** [comment] 2017-11-28 17:13
I can't reproduce as well. The issue should have been fixed by [this commit](https://github.com/angular/material.angular.io/blob/master/src/app/shared/doc-viewer/header-link.ts), which introduced the `headerLink` component for the doc-viewer.

Although there is still an issue with the documentation related to the same problem. See https://github.com/angular/material2/issues/8503. This can be fixed by https://github.com/angular/material.angular.io/pull/329

**Closed by DevVersion** 2017-11-28 17:13 UTC
