### ISSUE TITLE
Expansion Panel is always expanded when returned via Angular Universal (SSR)

### ISSUE THREAD

**Issue by patrickmichalina** [angular/material2#7646] opened 2017-10-09 02:40 UTC
#### Bug, feature request, or proposal:
Expansion Panel is always expanded when returned via Angular Universal (SSR)

#### What is the expected behavior?
To draw correctly (collapsed or expanded) from the server

#### What is the current behavior?
Remains open and with incorrect padding until the client takes control and corrects the render, which results in it finally being drawn correctly on screen

#### What is the use-case or motivation for changing an existing behavior?
Better user experience

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "5.0.0-rc.1"
"@angular/material": "^2.0.0-beta.12"
"typescript": "^2.5.3"

**Comment by josephperrott** [comment] 2017-12-01 00:47
I actually wasn't able to reproduce this.   I pushed my reproduction attempt [here](https://github.com/josephperrott/ssr-repo), the SSR seems to work as expected.

If you can extend this project to show the reproduction we can attempt to get to the bottom of the issue you are seeing.

**Comment by josephperrott** [comment] 2018-01-12 17:39
Closing as we are unable to reproduce this.

If you are able to find a reproduction in current version feel please open an issue for us to investigate.

**Closed by josephperrott** 2018-01-12 17:39 UTC
Labels: P3: important, needs investigation
