### ISSUE TITLE
MatSort.active returns 'created' when pristine

### ISSUE THREAD

**Issue by Drea1989** [angular/material2#11943] opened 2018-06-26 23:34 UTC
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
MatSort.active should return undefined if no sortables is selected.

#### What is the current behavior?
when the table is first initialised, clicking next on the paginator also triggers matSort.active with the value 'created'.
this happens using the angular material example code of table with pagination.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
i am now adding a statement to check if matSort is initialised and replacing the value of MatSort.active to undefined manually

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular "6.0.5", material "6.2.1", windows 10, "typescript": "2.6.2", chrome

**Comment by josephperrott** [comment] 2018-06-27 14:47
I was not able to reproduce the issue that you described.  As you can see in [this stackblitz](https://stackblitz.com/edit/angular-xpmpef?file=app/table-pagination-example.html), it looks to be that no value is give to `MatSort`'s `active` property until a sorting column is selected.

If you can provide a stackblitz reproduction, that will allow us to troubleshoot the issue you are seeing.

**Comment by josephperrott** [comment] 2018-09-10 22:17
Closing as we still have not be able to reproduce this issue.

**Closed by josephperrott** 2018-09-10 22:17 UTC
Labels: cannot reproduce
