### ISSUE TITLE
add backdropClick @Output in dialog

### ISSUE THREAD

**Issue by maxime1992** [angular/material2#3392] opened 2017-03-02 15:51 UTC
#### Bug, feature request, or proposal:

Sidenav has an `@Ouput` `backdropClick` :
![image](https://cloud.githubusercontent.com/assets/4950209/23513883/e1f2025e-ff65-11e6-8010-9533a365f491.png)

This is very handy when using ngrx for example so we can dispatch an action and keep a trace in UI reducer of the sidenav.

It would be very convenient to have such an output with the [dialog](https://material.angular.io/components/component/dialog) component.

**Comment by fxck** [comment] 2017-03-02 18:16
https://github.com/angular/material2/issues/3251

**Comment by kara** [comment] 2017-03-02 20:17
Yeah, looks like dupe of #3251. We'll keep tracking it there, but thanks for reporting.

**Closed by kara** 2017-03-02 20:17 UTC

**Comment by fxck** [comment] 2017-03-07 07:17
@maxime1992 https://github.com/angular/material2/pull/3460
