### ISSUE TITLE
Error Must provide a portal to attach

### ISSUE THREAD

**Issue by vicochips** [angular/material2#5206] opened 2017-06-19 12:53 UTC
Hello,

I'm currently doing an angular 4 application, and I have this error with md-tabs:

> ERROR Error: Must provide a portal to attach
    at throwNullPortalError (option.ts:212)
    at PortalHostDirective.BasePortalHost.attach (portal.ts:223)
    at MdTabBody.ngAfterViewChecked (tooltip.ts:416)
    at callProviderLifecycles (query.ts:1)
    at callElementProvidersLifecycles (provider.ts:619)
    at callLifecycleHooksChildrenFirst (provider.ts:603)
    at checkAndUpdateView (view.ts:413)
    at callViewAction (view.ts:765)
    at execEmbeddedViewsAction (view.ts:724)
    at checkAndUpdateView (view.ts:410)

>	View_MdTabGroup_5	@	MdTabGroup.html:1
DebugContext_.logError	@	services.ts:741
ErrorHandler.handleError	@	error_handler.ts:69
ApplicationRef_.tick	@	application_ref.ts:711
(anonymous)	@	application_ref.ts:574
ZoneDelegate.invoke	@	zone.js:391
onInvoke	@	ng_zone.ts:265
ZoneDelegate.invoke	@	zone.js:390
Zone.run	@	zone.js:141
NgZone.run	@	ng_zone.ts:135
next	@	application_ref.ts:574
schedulerFn	@	event_emitter.ts:99
SafeSubscriber.__tryOrUnsub	@	Subscriber.ts:250
SafeSubscriber.next	@	Subscriber.ts:202
Subscriber._next	@	Subscriber.ts:135
Subscriber.next	@	Subscriber.ts:95
Subject.next	@	Subject.ts:61
EventEmitter.emit	@	event_emitter.ts:80
NgZone.checkStable	@	ng_zone.ts:229
NgZone.onLeave	@	ng_zone.ts:279
onInvokeTask	@	ng_zone.ts:259
ZoneDelegate.invokeTask	@	zone.js:423
Zone.runTask	@	zone.js:191
ZoneTask.invoke	@	zone.js:486

####  My code

My code is like that : 
```
<md-tab-group [(selectedIndex)]="selectedIndex">
 <md-tab >
   <ng-template md-tab-label>
            <i class="material-icons">dashboard</i> Dashboard
    </ng-template>
</md-tab>
 <md-tab >
        <ng-template md-tab-label >
            <i class="material-icons">view_list</i> List
        </ng-template>
</md-tab>
</md-tab-group>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Using angular 4.2.3, material 2

Do you have any idea?

Regards,

**Comment by julianobrasil** [comment] 2017-06-19 14:24
Please, provide a plunker.

**Comment by crisbeto** [comment] 2017-06-19 17:24
I wasn't able to reproduce it @vicochips. Is there anything else that you're doing in your view?

**Comment by vicochips** [comment] 2017-06-19 19:53
Yes, but this is basic html, maybe the only thing is because I use browsersync?

**Comment by crisbeto** [comment] 2017-06-19 19:58
I tried the exact same HTML against our demo app and it worked. Do you have any other specific setup (e.g. different change detection strategy, lazy loaded modules)?

**Comment by vicochips** [comment] 2017-06-19 20:58
Hmmm I'm detecting some user information and so I'm doing some request to a Rest API in json. Then I'm displaying them on the different tabs

**Comment by crisbeto** [comment] 2017-06-19 21:01
Do you happen to have an `ngIf` on some of the tabs?

**Comment by jelbourn** [comment] 2017-06-20 01:10
Closing for now; feel free to re-open if there is more information.

**Closed by jelbourn** 2017-06-20 01:10 UTC
Labels: cannot reproduce

**Comment by vicochips** [comment] 2017-06-20 09:14
@crisbeto 

Yes, I have for example: 

` <h6 *ngIf="user.is_company == false">{{user.firstname}} {{user.lastname}}</h6>`

and also I have some table : 


```
 <table [md2Data]="mydemands"
               #md2="md2DataTable"
               [rowsPerPage]="10">
            <thead>
            <tr>
                <th md2SortBy="title">Title</th>
                <th md2SortBy="date">Date</th>
                <th >Status</th>
                <th >Actions</th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let i of md2.data">
                <td>{{i.title}}</td>
                <td>{{i.date | date: 'dd/MM/yyyy'}}</td>
                <td>En cours</td>
                <td >
                    <a *ngIf="i.haylpers.length === 1" (click)="showMyDemand(i)" class="collection-item table-link"><span class="new badge" data-badge-caption="réponse">{{i.haylpers.length}}</span></a>
                    <a *ngIf="i.haylpers.length > 1"  (click)="showMyDemand(i)" class="collection-item table-link"><span class="new badge" data-badge-caption="nouvelles réponses">{{i.haylpers.length}}</span></a>
                    <a class="table-link btn btn-flat waves-effect waves-light " (click)="showModification(i, modify)">
                        Modifier
                    </a>
                    <a class="table-link btn btn-flat waves-effect waves-light" (click)="showDelete(i, delete)">
                        Supprimer
                    </a>
                </td>
            </tr>
            </tbody>
            <tfoot>
            <tr>
                <td colspan="4">
                    <md2-pagination ></md2-pagination>
                </td>
            </tr>
            </tfoot>
        </table>
```

**Comment by crisbeto** [comment] 2017-06-20 18:09
That doesn't look related @vicochips , I meant whether you had any `ngIf` or `ngSwitch` on the tabs element itself.

**Comment by boswellsj** [comment] 2017-06-21 04:15
I'm seeing the same issue with the same table structure in the html.   

The cause is the ngFor in the row element: 
`<tr *ngFor="let i of md2.data">`

* remove that tag and this tab and all other tabs render--but obviously this tab then lacks the table rows.  
* include that tag and this tab renders, but all tabs after this tab in the md-tab-group fail to render, and you see repeated errors "Must provide a portal to attach."

I wish I could contribute more than "Me too!" and further details, but I've been using Angular for all of two weeks and this is the first blocker I've encountered.  :)

**Comment by julianobrasil** [comment] 2017-06-21 04:31
@vicochips, just a comment, probably not related to the issue: there's no date pattern like **`i.date | date: 'dd/MM/yyyy'`**. The year is represented by **y** or **yy** according to Angular docs.

**Comment by vicochips** [comment] 2017-06-21 07:57
@boswellsj aaaaah, thank you,

So how  can I do to solve it? I have to put the template into the component?


@julianobrasil hmm Yes it is true :) thank you

**Comment by julianobrasil** [comment] 2017-06-21 10:46
@vicochips, I put your template in a plunker. Can you please modify it and try to reproduce the error there?

Plunker link: http://plnkr.co/edit/uR1jfc?p=preview

**Comment by chris9r** [comment] 2017-07-05 12:12
@vicochips I ran into the same issue because I was iterating over an Array that was part of an Object I requested from my server. At the time the component is instantiated the array did not exist.

My solution was to initialize an empty object in the component constructor with an empty Array<any> inside it.

**Comment by kiwikern** [comment] 2017-09-17 00:44
This might actually be related to your internationalization pipe. Try importing the corresponding polyfill:
* Run `npm install --save intl`
* in your `polyfills.ts`: `import 'intl';`

**Comment by celestale** [comment] 2018-01-24 05:49
@crisbeto Hi, I have similar issues like this. I have `ngSwitch` on the elements. Do you know what is the probelm?
