### ISSUE TITLE
md-sidenav no longer has elevation set in "over" mode

### ISSUE THREAD

**Issue by sb3700** [angular/material2#6528] opened 2017-08-17 19:38 UTC
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

md-sidenav should have elevation in "over" mode, as currently shown in demo page https://material.angular.io/components/sidenav/overview

#### What is the current behavior?

md-sidenav does not have an elevation. See reproduction below.

#### What are the steps to reproduce?

https://plnkr.co/edit/qWHEEbEmnrBdca2xMZlU?p=preview

#### What is the use-case or motivation for changing an existing behavior?

Matching old behaviour and material spec https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-specs

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

The latest version of angular material introduces the bug. Not sure of version numbers, sorry.

#### Is there anything else we should know?

I believe it was caused by this commit https://github.com/angular/material2/commit/a882546debb92bd9cf52937bf73eee8548d61bf0#diff-1bbe0e0324a7c37430acb68a9d1f61eeL68

The change no longer sets the .mat-sidenav-opened class on the sidenav, so this style no longer does anything https://github.com/angular/material2/blob/d6f1a8d9bf089704e05e517c5773cf396708dd1e/src/lib/sidenav/sidenav.scss#L109

**Comment by GHVladimir** [comment] 2017-08-31 13:35
+1 
Mat-drawer doesn't change behaviour when mode is changed.

**Comment by RicardoVaranda** [comment] 2017-11-15 16:42
@jelbourn Any timeline on when this is being address?

**Comment by crisbeto** [comment] 2017-11-15 17:05
Closing as a duplicate of https://github.com/angular/material2/issues/8386.

**Closed by crisbeto** 2017-11-15 17:05 UTC
Labels: has pr
