### ISSUE TITLE
I cannot get the dark themes to work

### ISSUE THREAD

**Issue by Itagiba** [angular/material2#3298] opened 2017-02-25 16:55 UTC
I cannot find an open/closed issue with this but I found this: http://stackoverflow.com/questions/41967601/dark-theme-in-angular-material2-is-not-dark

For the contrast from white to dark to apply if you add a `$theme: mat-dark-theme($primary, $accent);` in struction

Everything just stays on the light theme no matter which theme you choose or create.

If you  `@import '~@angular/material/core/theming/prebuilt/purple-green';` to app.component.scss (using the default CLI project)

or create your own:

```
@include mat-core();

$primary: mat-palette($mat-indigo,A400);
$accent: mat-palette($mat-lime,A400);
$warn: mat-palette($mat-red);

$test: mat-dark-theme($primary, $accent, $warn);

@include angular-material-theme($test);
```
The colours are available but none of the stylings under `$mat-dark-theme-background` and `$mat-dark-theme-foreground` work.

**Comment by kara** [comment] 2017-03-01 00:32
@Itagiba Can you link to a repro case? It works in our demo app as intended, so we need more information.

**Comment by kara** [comment] 2017-03-03 02:55
There isn't enough info here to work on this, so I'm closing. Feel free to file a new issue with an extended code sample.

**Closed by kara** 2017-03-03 02:55 UTC
Labels: cannot reproduce

**Comment by JaimeStill** [comment] 2017-09-05 20:47
@kara, I have been having issues with dark themes as well and was able to make a [repro](https://jaimestill.github.io/material-dark-theme/). I kept things simple and, rather than trying to create toggle-able dark theme, I just made the default theme based on the dark theme:

**styles.scss**
``` scss
@import '~@angular/material/_theming.scss';
@include mat-core();

$default-theme: mat-dark-theme(mat-palette($mat-green, A400), mat-palette($mat-light-blue, A400));
@include angular-material-theme($default-theme);
...
```  

This project was built using Angular CLI and is at this [GitHub Repo](https://github.com/JaimeStill/material-dark-theme).

**Versions**
* @angular/* - ^4.2.4
* @angular/material - ^2.0.0-beta.10

**Comment by kara** [comment] 2017-09-05 21:50
@JaimeStill  When you add a Material dark theme, it only applies to Material components. In your app, the white part looks like part of `<section>` tags rather than a component, so that'd be what is expected. We try to scope styles to the components themselves so there aren't surprising side effects. e.g. you add a dark-themed card, and your whole app turns black. In this case, we'd suggest adding a custom style for that section.

**Comment by JaimeStill** [comment] 2017-09-05 22:48
@kara, I see. It was a little bit jarring going from using `md-sidenav-container` and having the content region styled as expected, as seen [here](http://material-platform.azurewebsites.net/).  

In the [theming guide](https://material.angular.io/guide/theming), it says:  
> In Angular Material, a theme is created by composing multiple palettes. In particular, a theme consists of:  
> - A primary palette: colors most widely used across all screens and components.
> - An accent palette: colors used for the floating action button and interactive elements.
> - A warn palette: colors used to convey error state.
> - A foreground palette: colors for text and icons.
> - A background palette: colors used for element backgrounds.  

This leads you to believe that if you apply a dark theme, the foreground palette and background palette will provide an appropriately styled foreground and background.  

I did, however, catch this (which was not in the theming guide the first time I read through it):  
> Finally, if your app's content is not placed inside of a `md-sidenav-container` element, you need to add the `mat-app-background` class to your wrapper element (for example the body). This ensures that the proper theme background is applied to your page.  

After reading this, I was able to get the results I wanted by adding `mat-app-background` to the root element in my app component, and a color styling in `styles.scss`: 

**app.component.html**  
``` html
<div class="mat-typography app-frame mat-app-background" fxLayout="column">
```  

**styles.scss**
``` scss
html, body, app-root, .app-frame {
    overflow: hidden;
    margin: 0;
    height: 100%;
    box-sizing: border-box;
    color: #e0e0e0;
}
```  

[![dark-fixed](https://user-images.githubusercontent.com/14102723/30086734-b266fd76-926a-11e7-99c4-d61ad6335df6.png)](https://user-images.githubusercontent.com/14102723/30086734-b266fd76-926a-11e7-99c4-d61ad6335df6.png)  

It might be helpful to have a similar `mat-app-foreground` class that allows you to opt into styling the background / foreground based on the active theme.
