### ISSUE TITLE
Dialog Component Animation

### ISSUE THREAD

**Issue by ArmaProjects** [angular/material2#10374] opened 2018-03-12 11:45 UTC
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Possibility to animate Dialog flying out  from "parent button" on open and flying back to "parent button" on close.
The way it was implemented in angularjs: https://material.angularjs.org/latest/demo/dialog

#### What is the current behavior?
The dialog component has no animation options.

#### What are the steps to reproduce?
Current: https://stackblitz.com/angular/eaaovbxppyne?file=app%2Fdialog-overview-example.ts
Desired: angularjs: https://material.angularjs.org/latest/demo/dialog

#### What is the use-case or motivation for changing an existing behavior?
The animation perception is more natural. The movement from parent on open and to parent on close.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by josephperrott** [comment] 2018-04-03 21:57
Closing as duplicate of #10544

**Closed by josephperrott** 2018-04-03 21:57 UTC

**Comment by mswilson4040** [comment] 2018-07-18 15:11
@ArmaProjects this SOF should give you the answer on how to do it:

https://stackoverflow.com/questions/43476958/how-can-i-position-a-dialog-above-the-triggering-button/50496251#50496251
