### ISSUE TITLE
Feature Request: Drag and Drop for Files

### ISSUE THREAD

**Issue by CharlieGreenman** [angular/material2#12824] opened 2018-08-24 21:24 UTC
#### Bug, feature request, or proposal:
Feature

#### What is the expected behavior?
When a user drops a file from their operating system, onto a webpage(, or specific component), it should trigger an event that has the data for that file, so that, that file can be sent through an http request someplace. 

#### What is the current behavior?
There is the cdk-drop, but it doesn't allow for a drop event to be registered if file is from outside of browser onto browser.

**Comment by fxck** [comment] 2018-08-25 07:44
You mean something like
```
<div (drop)="onDropped($event)"></div>
```

**Comment by CharlieGreenman** [comment] 2018-08-27 00:35
@fxck potentially yes, however, I can see `(drop)` using the above syntax can be seen as something the core Angular framework should deal with and not Material. I was thinking of something more along the lines of: 
```
<cdk-drop (drop)="onDropped($event)"> 
  <div class = "DataTable"></>
</cdk-drop>

**Comment by josephperrott** [comment] 2018-09-06 22:46
Closing as duplicate of https://github.com/angular/material2/issues/1347

As file uploads are not part of the material spec, there are not any plans to support file uploads whether via drag or input.

**Closed by josephperrott** 2018-09-06 22:46 UTC
