### ISSUE TITLE
Angular Material 2 Textarea Autosize Attribute (mdTextareaAutosize)

### ISSUE THREAD

**Issue by nickitatkach** [angular/material2#4138] opened 2017-04-18 14:37 UTC
I am using `@angular/material@2.0.0-beta.2`. I have textarea with `mdTextareaAutosize` attribute in container with `display:none` (popup). I call `setValue` method of angular form control. When I open popup the textarea has `height:0px` and initial value is not shown. When I click on the textarea and press any key the initial value appears.

If I add boolean condition to show textarea (`*ngIf`) and make this condition as true in 2 seconds then it works. But without `timeout` it does not work.

**Comment by willshowell** [comment] 2017-04-18 15:33
Looks like a duplicate of #4070, which has been fixed in master via #4084

**Comment by kara** [comment] 2017-04-18 23:14
As @willshowell mentioned, seems like it could be a duplicate. If this is *not* fixed in master for you, please feel free to open a new issue with a plunker demo (so we can repro).

**Closed by kara** 2017-04-18 23:14 UTC
