### ISSUE TITLE
MatSelect reset option trigger the selectionChange two times

### ISSUE THREAD

**Issue by mekhalil** [angular/material2#14557] opened 2018-12-18 11:16 UTC
#### What is the expected behavior?
Should be triggered one time after the user clicked on the reset option

#### What is the current behavior?
It's executed two times

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-jxnb9z

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7
Angular material 7

**Comment by crisbeto** [comment] 2018-12-18 12:11
Closing as a duplicate of https://github.com/angular/material2/issues/13579.

**Closed by crisbeto** 2018-12-18 12:11 UTC
