### ISSUE TITLE
Warning with @angular2-material/icon installation when updating to @angular rc2 from rc1

### ISSUE THREAD

**Issue by pramttl** [angular/material2#714] opened 2016-06-17 19:27 UTC
#### Bug

Angular2 rc.2 came out very recently. angular2-material gave no warnings with @angular/http@2.0.0-rc.1 but when I update to @angular/http@2.0.0-rc2 I get this warning:

npm WARN @angular2-material/icon@2.0.0-alpha.5 requires a peer of @angular/http@2.0.0-rc.1 but none was installed.

#### What is the expected behavior?

There should be no warning.

#### What are the steps to reproduce?

Have the following in package.json and remove other angular2 and material ref's. (Then run npm install)

```
    "@angular2-material/button": "2.0.0-alpha.5",
    "@angular2-material/card": "2.0.0-alpha.5",
    "@angular2-material/checkbox": "2.0.0-alpha.5",
    "@angular2-material/grid-list": "2.0.0-alpha.5",
    "@angular2-material/icon": "2.0.0-alpha.5",
    "@angular2-material/core": "2.0.0-alpha.5",
    "@angular2-material/input": "2.0.0-alpha.5",
    "@angular2-material/list": "2.0.0-alpha.5",
    "@angular2-material/progress-bar": "2.0.0-alpha.5",
    "@angular2-material/progress-circle": "2.0.0-alpha.5",
    "@angular2-material/radio": "2.0.0-alpha.5",
    "@angular2-material/sidenav": "2.0.0-alpha.5",
    "@angular2-material/slide-toggle": "2.0.0-alpha.5",
    "@angular2-material/tabs": "2.0.0-alpha.5",
    "@angular2-material/toolbar": "2.0.0-alpha.5",
    "@angular/http": "2.0.0-rc.2",
    "@angular/common": "2.0.0-rc.2",
    "@angular/compiler": "2.0.0-rc.2",
    "@angular/core": "2.0.0-rc.2",
    "@angular/platform-browser": "2.0.0-rc.2",
    "@angular/platform-browser-dynamic": "2.0.0-rc.2",
    "@angular/platform-server": "2.0.0-rc.2",
    "@angular/router": "2.0.0-rc.2",
    "@angular/router-deprecated": "2.0.0-rc.2",
```

**Comment by jelbourn** [comment] 2016-06-17 22:54
Dupe of #707

**Closed by jelbourn** 2016-06-17 22:54 UTC
