### ISSUE TITLE
MdDialog - closeAll() doesn't close dialogs

### ISSUE THREAD

**Issue by Cris13** [angular/material2#6520] opened 2017-08-17 15:31 UTC
#### What is the expected behavior?
For MdDialog, closeAll() should close all the open dialogs
worked perfectly with   "@angular/material": "2.0.0-beta.2"

#### What is the current behavior?
The dialog are not closed

#### What are the steps to reproduce?
I reproduced it in a really simplistic way in this plunker
https://plnkr.co/edit/pfREzLvFKDZiduJKDBdU?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.3, Material 2.0.0-beta.8

**Comment by willshowell** [comment] 2017-08-17 15:49
This is not a bug, you forgot the add event binding to you click handler

See https://plnkr.co/edit/XMzvliRQMlFjxPqOs0sz?p=preview

**Comment by crisbeto** [comment] 2017-08-17 17:08
Closing as a non-issue.

**Closed by crisbeto** 2017-08-17 17:08 UTC
