### ISSUE TITLE
mat-icon in buton is not vertical centering

### ISSUE THREAD

**Issue by wszgrcy** [angular/material2#15819] opened 2019-04-14 12:42 UTC
#### What is the expected behavior?
the icon in` Mini Fab Buttons` and `Fab Buttons` should really align center vertically(not `vertical-align:middle` )

#### What is the current behavior?
the icon is a little below in button and the code
```html
<button _ngcontent-c19="" mat-mini-fab="" class="mat-mini-fab mat-accent">
<span class="mat-button-wrapper"><mat-icon _ngcontent-c19="" aria-label="Example icon-button with a heart icon" class="mat-icon material-icons mat-icon-no-color" role="img" aria-hidden="true" >favorite</mat-icon></span><div class="mat-button-ripple mat-ripple mat-button-ripple-round" matripple=""></div><div class="mat-button-focus-overlay"></div></button>
```
`mat-button-wrapper` element is not `40px` but `41.11px`

#### What are the steps to reproduce?
Official Url:https://material.angular.cn/components/button/examples
see last 2 lines

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.3.7

**Comment by andrewseguin** [comment] 2019-04-19 18:11
Duplicate of #8842

**Closed by andrewseguin** 2019-04-19 18:11 UTC
