### ISSUE TITLE
MDButton inserting an div element under the button element after clicking on button

### ISSUE THREAD

**Issue by HazizKhan** [angular/material2#2069] opened 2016-12-03 06:47 UTC
After Clicking on button MDButton Inserting an div.md-ripple-foreground.md-ripple-fade-in element under the button.
take a look of these screenshots.

![btn1](https://cloud.githubusercontent.com/assets/13147389/20857425/e177ad50-b94d-11e6-95b3-5f3bdc27d8fc.png)
![btn2](https://cloud.githubusercontent.com/assets/13147389/20857426/e18f723c-b94d-11e6-8414-a80a91c23fdf.png)
![btn4](https://cloud.githubusercontent.com/assets/13147389/20857427/e19b6ff6-b94d-11e6-87f0-0e102618b5e0.png)

**Comment by crisbeto** [comment] 2016-12-03 09:17
This looks like it should get sorted out with https://github.com/angular/material2/pull/1915

**Comment by jelbourn** [comment] 2016-12-07 22:50
Dupe of #1818

**Closed by jelbourn** 2016-12-07 22:50 UTC
