### ISSUE TITLE
autocompletes overlay position works wrong on mobile devices

### ISSUE THREAD

**Issue by maku** [angular/material2#6341] opened 2017-08-08 06:01 UTC
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

Correct overlay position so that the component can be used on mobile devices
#### What is the current behavior?
On mobile devices (e.g iphone6+ with latest IOS, Android etc.) the position of the overlay is strange.
Sometimes the overlay disappears or the overlay overlaps the input fields ...

So autocomplete is NOT usable on mobile devices....

#### What are the steps to reproduce?

E.g. use the https://material.angular.io/ demo for autocomplete on mobile devices

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.3, Material 2.0.0-beta.8

**Comment by willshowell** [comment] 2017-08-08 13:54
The positioning of the autocomplete just changed to be more accurately connected to the input. Here is an example with the latest build: http://plnkr.co/edit/HnQwfr7WlNVLdP3P6ukQ?p=preview

However, I am still seeing some weird positioning in landscape mode with the keyboard open:

<img src="https://user-images.githubusercontent.com/6475576/29074991-17f2dd34-7c1f-11e7-8c0e-ff71cb725f7c.PNG" width="375px">

![img_4975](https://user-images.githubusercontent.com/6475576/29074995-1aa27224-7c1f-11e7-8ef0-c2d7cd7ec287.PNG)

**Comment by crisbeto** [comment] 2017-08-08 16:29
The issue is that the keyboard animation throws off the positioning logic. I've been considering whether having a `setTimeout` on focus for iOS and Android would make sense @jelbourn?

**Comment by jelbourn** [comment] 2017-08-08 16:59
@crisbeto that seems reasonable if we scope the delay to only apply for these cases. Let's address this after the overlay positioning refactor

**Comment by maku** [comment] 2017-08-14 10:04
@crisbeto is there any timeframe until func is getting better on IOS -> Otherwise I have to consider to replace autocomplete temporarly...

**Comment by crisbeto** [comment] 2017-08-14 10:15
The initial plan was to address this after we refactor some of our positioning logic, but I suppose that shouldn't really change what we do in the autocomplete. There should be a way for you to patch it on your side temporarily, but it'll be very hacky, because it would need to access private properties on the autocomplete trigger.

**Comment by maku** [comment] 2017-08-14 10:17
@crisbeto what is the way  to "patch" autocomplete so that it work better on IOS???

**Comment by crisbeto** [comment] 2017-08-14 20:40
I've been playing around with the approach I mentioned above, but it doesn't really work the way I expected it to. It seems like the autocomplete does figure out the proper position values, however iOS throws it off when it scrolls the input into the middle of the view. Delaying the positioning call doesn't help in this case.

**Comment by maku** [comment] 2017-08-16 05:07
@crisbeto Is there a solution to this problem? What is the recommended way to go?

**Comment by xiongemi** [comment] 2017-08-29 15:33
Any update on this issue?

**Comment by mahmood-sajjadi** [comment] 2017-08-31 04:31
@crisbeto, @maku is there any workaround or patch for this issue?

**Comment by crisbeto** [comment] 2017-08-31 05:01
This is somewhat tricky to fix on our end, because iOS seems to shift the coordinate grid when it focuses the into view, which makes it so we can't recalculate the position directly. The best approach for now might be to disable scrolling for the autocomplete altogether. See https://github.com/angular/material2/issues/5187#issuecomment-324371834.

**Comment by maku** [comment] 2017-08-31 12:54
@crisbeto dump question - how do other ui libraries handle this problem?

**Comment by crisbeto** [comment] 2017-08-31 16:27
The easiest way to handle it would be to use `position: absolute` to position the panel, however that is problematic when handling focus and overflow.

**Comment by maku** [comment] 2017-09-02 12:12
@crisbeto I would really appreciate an advice what to do... - should we drop using autocomplete?? and looking for an alternative  (also the fix #5187 does not work for me)
Is there anything in the pipeline? The component as it is is NOT usable on IOS.

Just to be curious - what problems does material2 have what other libs don't have (so that this stuff works on IOS)?

**Comment by maku** [comment] 2017-09-08 14:26
@crisbeto I really do not want to be annoying. But is there any kind of solution on the horizon?

**Comment by MatteoNY** [comment] 2017-10-04 17:12
Any updates? using latest and issue with iOS positioning as well as touch. I can not select an item from autoComplete component.  I'm using the code from your example to test. I have hammer js installed the toggle button works and requires hammer js as per your spec. Not sure why I can not select an item but positioning is still an issue. Thanks!

**Comment by LukasKlement** [comment] 2017-10-04 22:00
This very issue is causing headaches on my side too.

The following two suggestions have helped the situation and make the autocomplete somewhat usable on iOS:
1. Add cdkScrollable to your <main> element (@crisbeto, [#4557](https://github.com/angular/material2/issues/4557))
2. Add custom scrolling strategy (@aitboudad, [#5187](https://github.com/angular/material2/issues/5187))

**Comment by kasperhhk** [comment] 2017-10-26 08:08
We have a related issue, maybe it's the same.

For us, the dropdown list gets hidden entirely by the keyboard, instead of the dropdown list going upwards (the autosuggest field is in the middle of the page).

https://imgur.com/a/nrBUw

**Comment by murilobd** [comment] 2017-11-06 19:47
Any updates on this issue?! I'm facing the same problem!!

**Comment by michaeldev6** [comment] 2017-11-20 17:15
Just want to add my thoughts on this. As I am facing this issue as well. 

When testing on an iPad in debug mode connected to a MacBook, I noticed that when highlighting the AutoCompletePanel in the HTML element in the debugger, it does highlight the element, and the highlight is shown directly underneath the input field. So the positioning of the css is correct. 

But the kicker is that the browser is rendering the auto complete panel NOT where the highlighted HTML is. Which leads me to believe that it is something with how iOS Safari is rendering the HTML elements while the keyboard is up. 

This is just a comment supporting @crisbeto comment regaring iOS shifting it's coordinate grid.

**Comment by stevenmcountryman** [comment] 2017-12-01 16:59
For anyone still following this thread, hoping for a fix, I got tired of waiting for one and just scrapped the autocomplete from our project entirely and built my own component that looks identical but actually works, for all browsers and all platforms. 

The idea is this:

HTML 
```
<div>
    <mat-input-container class="//whatever class you have to make this the right width">
        <input #itemFilterInput matInput type="text" placeholder="ITEM" (click)="showItems = true">
    </mat-input-container>
    <mat-card [hidden]="!showItems" class="autocomplete">
        <mat-option *ngFor="let item of items" [value]="item.name" (click)="selectItem(item)">
            {{ item.name }}
        </mat-option>
    </mat-card>
</div>
```

TS
```
showItems: boolean = false;
@ViewChild('itemFilterInput') itemFilterInput: ElementRef;

ngOnInit() {
    Observable.fromEvent(this.itemFilterInput.nativeElement, 'keyup')
        .debounceTime(300)
        .distinctUntilChanged()
        .subscribe(() => {
            this.items = [];
            if (this.itemFilterInput.nativeElement.value && this.itemFilterInput.nativeElement.value.length > 1) 
            {
               this.itemService.getItemsBySearch(this.itemFilterInput.nativeElement.value).subscribe(items => {
               this.items = items;
               this.showItems = true;
            });
        }
    });
}

selectItem(item) {
    this.itemFilterInput.nativeElement.value = item.name;
    this.showItems = false;
}
```

CSS
```
.autocomplete {
    max-height: 150px; 
    overflow:auto; 
    position: fixed !important; 
    padding: 0 !important;
    z-index:1000;
}
```

**Comment by sava1192** [comment] 2018-01-05 09:09
Came to same approach as @stevenmcountryman. Created autocomplete by myself because MatAutocomplete is not usable on mobile at all.

**Comment by tomscript** [comment] 2018-01-09 20:31
Friendly ping please. I'm using this on an email field so I can't create my own autocomplete.

**Comment by Arnaud73** [comment] 2018-01-11 16:29
We ran into the same issue.

Any idea if we shall wait for a fix or start writing our own autocomplete component ?

**Comment by vovikdrg** [comment] 2018-02-05 01:19
I have same problem after testing it on iOS autocomplete is not working same way as on Android

I would say that on website it should say anything about this problem because currently it seems that autocomplete is not production ready.

**Comment by vovikdrg** [comment] 2018-02-05 21:09
Well a bit of frustration in this topic. I dont understand why this issue is not critical, its not that something is not perfect issue is that it just dont work. What the reason to improve if one of the features are not working. And again lib is production ready without any notes that its not working. I would understand if issue is on windows phone because nobody care but IPhone has huge audience....
Btw vue autocomplete is working 🥇 

For people who is looking for replacement http://leaverou.github.io/awesomplete. Seems to be easy to integrate.

**Comment by sava1192** [comment] 2018-02-06 08:03
@vovikdrg i understand you, and agree about note on main site, but that lib is still in beta so we have what we have...
Maybe it is possible to try some "simple" fix which will allow to position dropdown with styles, without fancy resizing and jumping below and above?

**Comment by vovikdrg** [comment] 2018-02-06 08:16
@sava1192  what do you mean it still in beta? its marked as stable for few month

**Comment by sava1192** [comment] 2018-02-06 09:43
@vovikdrg ohh, i missed it:) but problem remains :)

**Comment by sebastien-A256** [comment] 2018-02-07 11:03
Just tried to implement today the autocomplete module and I'm running out with the same issue. I hope this will be solved.

**Comment by joelcoxokc** [comment] 2018-02-07 17:10
Hello Material Team. 

I have been looking around trying to find where the logic may be, but I have been unsuccessful. 

It seems like the overlay doesn't respect the new screen size when the keyboard is opened. 

However, it's initial position, after keyboard is opened may be correct... but after you begin scrolling (while keyboard is open)... It looks like the panel's positioning is based on the screensize before the keyboard was opened. 

I hope this helps.. 

This is a critical bug in our backlog right now, So if no one is able to complete this soon, maybe someone can point me in the right direction and I can make the fix.

**Comment by mahmood-sajjadi** [comment] 2018-02-07 23:34
Hi @joelcoxokc

I believe this bug, it is not a screen size problem
because after virtual keyboard opened screen coordinate (point 0,0) will be pushed outside of the screen
You can verify it by adding an element with position fixed and top = 0
this is a wrong behavior and it is a safari bug
so the actual solution should be provided by safari team
as iPhone is popular we need a good and stable workaround, or we should ignore benefit s of positioning the overlay(which will work)

**Comment by anymos** [comment] 2018-02-13 08:02
Actually wondering what material 2 is good for...

the layout is not usable so I had to switch to bootstrap 2.

the more we are trying to use some of the widget the more bug are appearing.

quite a disapointment

**Comment by joelcoxokc** [comment] 2018-02-13 19:18
@mahmood-sajjadi Thank you. 

@anymos This isn't really the place to put comments about the library as a whole. 
If you are looking for a library to do a lot more Layout customization, try using https://teradata.github.io/covalent/#/. 
It is built on top of Angular/Material.

**Comment by sava1192** [comment] 2018-02-15 16:13
@joelcoxokc main problem with covalent is that it inherits all bugs from material...

**Comment by joelcoxokc** [comment] 2018-02-15 18:40
For now, our solution is using a full-screen dialog. with a search bar at the top, and a repeated list, filtered by the search value takes up the rest of the screen. 

It is pretty simple to do, and doesn’t require any positioning.

Until this bug is fixed. 

Just make sure you add the proper scrolling css properties for iOS

**Comment by misterjuicebox** [comment] 2018-03-22 23:02
This is a really bad problem for me too. Any word on when we can get a fix?

**Comment by MikaStark** [comment] 2018-03-29 15:14
No solution (fix or patch) for now ? This issue is 9 months old

**Comment by edwinpopham** [comment] 2018-03-30 23:54
+1 would like to see a fix for this also.

**Comment by vovikdrg** [comment] 2018-03-30 23:58
@MikaStark  for me solution is https://www.primefaces.org/primeng/#/autocomplete

**Comment by joelcoxokc** [comment] 2018-03-31 00:01
A full screen dialog with a list and search box at the top is the simplest
solution for now.

**Comment by MikaStark** [comment] 2018-03-31 10:15
I don’t want to use another dependency. My whole webapp is based on material. I can wait for a patch but i’m very surprised that kind of behavior tooks more than 9 months to be fixed.

**Comment by vovikdrg** [comment] 2018-03-31 10:26
@MikaStark good for you in my case I didn't have choice. I must support mobile..

**Comment by MikaStark** [comment] 2018-04-26 19:19
After 1 month, here is a little up 🙂

**Comment by waseemshaz** [comment] 2018-05-05 20:15
https://www.w3schools.com/tags/tag_datalist.asp

Guys use HTML 5 **Datalist**, its working awesome

**Comment by stevenmcountryman** [comment] 2018-05-05 22:07
@waseemshaz, looks like that isn't supported by Safari at all which makes it a no go

**Comment by joelcoxokc** [comment] 2018-05-06 01:28
Is it possible just to add a search field to the select? I think that is
why most people want autocomplete in the first place.

We just created our own custom component that puts an input inside the
mat-select-content

**Comment by MikaStark** [comment] 2018-06-06 10:12
June has come an no fix even after couple of material updates

**Comment by mhosman** [comment] 2018-06-12 20:59
No news about this one?

**Comment by MikaStark** [comment] 2018-06-12 21:16
Nope 😤 still P3 but no one cares 🤪

**Comment by sava1192** [comment] 2018-06-12 21:18
waitet for fix for so long, that switched to React allready

**Comment by jpzwarte** [comment] 2018-06-27 07:57
See the explanation in #11946 where (i think) the problem is in the code (my issue is unrelated to mdAutocomplete, but also involves the iOS keyboard).

**Comment by jpzwarte** [comment] 2018-06-27 08:56
So aside from the PR, i also added workaround to my custom component. The code below works for me on iOS: the overlay is positioned correct when scrolling with the keyboard visible:

```
    this.overlayDir.positionChange.subscribe((position: ConnectedOverlayPositionChange) => {
      const clientRect = this.overlayDir.overlayRef.hostElement.getBoundingClientRect();

      if (clientRect.top !== 0) {
        const overlayElement = this.overlayDir.overlayRef.overlayElement,
              top = parseInt(overlayElement.style.top);

        overlayElement.style.top = top + Math.abs(clientRect.top) + 'px';
      }
    });
```

**Comment by jinder** [comment] 2018-06-27 15:50
@jpzwarte your fix seems to work perfectly - thanks.  My overlays now position correctly when the iOS keyboard is out.

**Comment by geoFlux** [comment] 2018-06-28 14:14
@jpzwarte I don't understand your solution. How does one get a reference to overlayDir? Do you have a more complete example?

**Comment by vmachacek** [comment] 2018-07-05 03:32
@jinder I was not able to make it work with sample provided. Do you mind sharing plunker, please?

**Comment by itsanmax** [comment] 2018-07-05 11:45
@stevenmcountryman : Thanks for your solution provided here: https://github.com/angular/material2/issues/6341#issuecomment-348549272. I've applied same solution in my project.  This resolve issue of showing list options at correct position but getting issue with selecting option by clicking function "selectItem(item)". **Issue here is,  selectItem function fires on 2nd time click.** It doesn't fire on first time click. Any idea how to solve this issue? It would be really great help if you can help to sort out this issue.

**Closed** 2018-07-12 14:43 UTC
Labels: P3, has pr

**Comment by iamramo** [comment] 2018-07-26 21:16
I'm guessing this issue is now fixed. I had the same issue in one of my projects and after recent updates it seems to be fixed! 🎉 

Versions:
@angular/material - 6.4.1
iOS - 11.4.1
