### ISSUE TITLE
md-input-container placeholders can disappear behind input

### ISSUE THREAD

**Issue by hans-pragt** [angular/material2#2434] opened 2016-12-27 23:59 UTC
#### Bug, feature request, or proposal:

If the value of an `<input>` element is set through data binding, tabbing into and out of will cause the placeholder to act as if there is no input and lower itself behind the input text.

#### What is the expected behavior?

The placeholder works correctly regards of how the value of the input it set.

#### What is the current behavior?

The placeholder sits behind the text in the input.

#### What are the steps to reproduce?

You will see the wrong behavior here:

http://plnkr.co/edit/PHrAb1LPvmhhitdj8W4F?p=preview

After editing the text in the input, the placeholder will stay in the right spot.

#### Which versions of Angular, Material, OS, browsers are affected?

Windows 10 / Chrome 55.0.2883.87 m

#### Is there anything else we should know?

I like the new plunkr template, thanks for updating it.

**Comment by DevVersion** [comment] 2016-12-28 00:15
This seems to be a duplicate of https://github.com/angular/material2/issues/2363

**Closed** 2016-12-28 00:15 UTC

**Comment by hans-pragt** [comment] 2016-12-28 00:17
Yep, sorry!
