### ISSUE TITLE
Date text flickering (day/month switches) when using MAT_DATE_LOCAL + DatePicker

### ISSUE THREAD

**Issue by stevenxi** [angular/material2#12057] opened 2018-07-04 11:09 UTC
#### What is the expected behavior?
User can change content of the datepicker's input manually by typing.

#### What is the current behavior?
When set local to en-GB, if user update the date, it will switch day and month.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-wvita9?file=main.ts

In the text box "Angular forms"

0. As for today, the default value is "04/07/2018"
1. If you delete the last char '8', and type '9', or select the last digit by mouse and modify it. The date will become '07/04/2019'. (You may need to press enter, or click mouse outside of the input to make input lose focus).
2. Next, if you delete the last char '9', and type '5' (or any digit else), or select the last digit by mouse and modify it. The date will become '04/07/2015'

As you can see, the day 04 and month 07 are flickering each time when date updates.

#### What is the use-case or motivation for changing an existing behavior?
User may (very likely) modify the date manually without using the popup.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular material 6.3.2
The sample link above is a fork from Angular Material's official document.

**Comment by Bielik20** [comment] 2018-07-04 15:09
Possible duplicate: https://github.com/angular/material2/issues/11936

**Comment by stevenxi** [comment] 2018-07-05 08:37
Update: temporary fixed by https://stackoverflow.com/questions/44452966/angular-2-material-2-datepicker-date-format

**Comment by josephperrott** [comment] 2018-07-16 21:42
Closing as duplicate of #11936

**Closed by josephperrott** 2018-07-16 21:42 UTC
