### ISSUE TITLE
[Feature request] File upload

### ISSUE THREAD

**Issue by Leonzen** [angular/material2#7551] opened 2017-10-05 10:31 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Please implement a module for a file upload. 

#### What is the use-case or motivation for changing an existing behavior?
There are several use-cases for a file upload for example uploading an image to a server to set a profile picture.

**Comment by donroyco** [comment] 2017-10-05 10:36
See #3262, as stated by @mmalerba: 

> This is not currently on our roadmap

**Comment by josephperrott** [comment] 2017-10-05 16:14
Closing as duplicate of #3262

**Closed by josephperrott** 2017-10-05 16:14 UTC

**Comment by mmalerba** [comment] 2017-10-05 17:36
You could create your own file upload component and make it work inside the form field (guide on how to do this has been written but not pushed to our docs site yet, you can find it here: https://github.com/angular/material2/blob/master/guides/creating-a-custom-form-field-control.md)
