### ISSUE TITLE
MdSelect does not bind when the model value is null or 0.

### ISSUE THREAD

**Issue by Nathan-Ryan** [angular/material2#5158] opened 2017-06-16 01:36 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The appropriate MdOption is selected, even if the model is null or 0.

#### What is the current behavior?
The control does not show the option as being selected, even though the model value has a respective MdOption.

#### What are the steps to reproduce?
Define an MdSelect with two MdOptions, one should have a [value]="0". (I'm using an enum to define the option values)
Within the ngOnInit event, instantiate the FormGroup and set the model value to 0.

#### What is the use-case or motivation for changing an existing behavior?
To have a working form.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.2.2
Material: 2.0.0-beta.6
OS: Windows 10
TS: 2.3.4
Browser: Chrome 58.0.3029.110

#### Is there anything else we should know?
I noticed inconsistencies with the MdSelect binding before, now it fails all the time. 
There are far too many issues (styling, awkward and minimal keyboard control, no error message support) for such a simple control.
Can we please just have the native select supported with MdInputContainer?

**Comment by julianobrasil** [comment] 2017-06-16 02:09
Dupe of #5080.

It'll be solved next beta release.

**Comment by Nathan-Ryan** [comment] 2017-06-16 02:53
@julianobrasil Thanks for the heads up. Do we know when the next beta will be released?

**Closed** 2017-06-16 02:55 UTC

**Comment by julianobrasil** [comment] 2017-06-16 02:59
I have no idea. But you can try the latest build on master. This is already corrected there.
