### ISSUE TITLE
Error with progress bar : Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by trichetriche** [angular/material2#10171] opened 2018-02-27 13:10 UTC
#### Bug, feature request, or proposal:

Bug

#### Description

I'm sorry for posting my message here, but I can't seem to find any help online. I also can't seem to reproduce the issue on a stackblitz, but I do have the error on my project, and I thought that you could enlighten me on that issue.

Let me explain : 

- I have a progress bar in `app.component.html` with a `*ngIf="loading"`. App component has a router outlet and displays other components. 
- The value of loading is changed at every http request through a `BehaviorSubject` (app component is subscribing to that subject)
- I go from the route `/` to `/profile`. On profile init, I make a request, changing the value of `loading`.

Then, I get this error message : 

    ERROR TypeError: Cannot read property 'name' of undefined
        at checkBindingNoChanges (core.js:9912)
        at checkNoChangesNodeInline (core.js:13961)
        at checkNoChangesNode (core.js:13935)
        at debugCheckNoChangesNode (core.js:14764)
        at debugCheckDirectivesFn (core.js:14666)
        at Object.eval [as updateDirectives] (AppComponent.html:9)
        at Object.debugUpdateDirectives [as updateDirectives] (core.js:14648)
        at checkNoChangesView (core.js:13773)
        at callViewAction (core.js:14126)
        at execComponentViewsAction (core.js:14078)

![image](https://user-images.githubusercontent.com/7789922/36730266-1ccff5e2-1bc7-11e8-8cd5-babbba44e914.png)

The problem doesn't seem to appear on other components (for instance, `LoginComponent`). It also doesn't appear when I load the application on the profile component directly. It seems to only appear when I come to that component from a routing event. 

What I want to know is what exactly this issue means, or where does it comes from. Could you answer that ? 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

    "@angular/core": "^5.2.0",
    "@angular/material": "^5.1.0",
    "typescript": "~2.5.3"

I'm on Windows 10, using Google Chrome.

**Comment by trichetriche** [comment] 2018-02-27 13:55
It appears to trigger the error from this function : 

![image](https://user-images.githubusercontent.com/7789922/36732440-1b22e1a8-1bce-11e8-8f6d-a02acee5f17c.png)

And I can see an `expressionChangedAfterItHasBeenCheckedError` ! Maybe this is my issue, but the framework had another issue and could not throw this error ! 

I'm going to work around that and let you know on that ticket issue if I manage to resolve my problem.

**Comment by trichetriche** [comment] 2018-02-27 15:21
This was it ! I changed my lifecycle hook and used a timeout to get rid of the issue. In my profile component, this gives : 

    ngAfterViewInit() {
      setTimeout(() => {
        // My code
      });
    }

I'll let the issue opened, because it is still an error : the `expression changed` error that should have been thrown isn't.

**Comment by crisbeto** [comment] 2018-02-27 17:40
The progress bar component has no references to a `name` property. This looks like an error somewhere else in your code.

**Comment by trichetriche** [comment] 2018-02-27 17:42
I don't have it either. I provided the piece of code triggering that issue, it's from `core.js` maybe this is Angular and not Material related ?

**Comment by crisbeto** [comment] 2018-02-27 18:39
It could be anything. It's hard to tell without seeing the code that's triggering it.

**Comment by trichetriche** [comment] 2018-02-27 18:50
It comes from my html, just a progress bar with a condition on it, and the second screen shot shows the last method called from the stack trace, but I will post my code if you need it !

**Comment by josephperrott** [comment] 2018-03-26 15:01
Closing as the errors mentioned don't reference Material and we are not able to reproduce the issue.

**Closed by josephperrott** 2018-03-26 15:01 UTC
