### ISSUE TITLE
Mat-dialog: custom animation

### ISSUE THREAD

**Issue by AsafAgranat** [angular/material2#8957] opened 2017-12-12 14:50 UTC
#### Bug, feature request, or proposal:
Request: Expose the ability to define custom enter/leave animation for mat-dialog

#### What is the expected behavior?
A method to programatically (component animation) define the entering and leaving animations of dialogs

#### What is the current behavior?
Currently the dialog uses a single default

#### What is the use-case or motivation for changing an existing behavior?
in Angular Material v1 we could override the animation, programatically or via css. That benefited greatly to the flexibility of the library

**Comment by donroyco** [comment] 2017-12-12 15:03
Duplicate of #8857

**Closed** 2017-12-12 20:07 UTC
