### ISSUE TITLE
[input @alpha.8-1] Setting bound FormControl to disabled causes valueAccessor.setDisabledState error

### ISSUE THREAD

**Issue by RoxKilly** [angular/material2#1171] opened 2016-09-03 07:58 UTC
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

Angular recommends, when using reactive forms, to set `disabled` on the `FormControl` rather than the input element in the template:
![6](https://cloud.githubusercontent.com/assets/12346501/18223594/e13bf190-7189-11e6-988d-88f8127a85cb.png)
#### What is the current behavior?

Setting `disabled: true` on a `FormControl` bound to `md-input` will cause the app to crash with error:

> TypeError: this.valueAccessor.setDisabledState is not a function

This does not happen to the native text input.
#### What are the steps to reproduce?

[Open this plunker ](http://plnkr.co/edit/0Pw4kwS6jJ8CI5nKh5On?p=preview)and look at the console. If in `AppComponent` you replace:

```
nameCtrl = new FormControl({value:'Jane', disabled:true});
```

With

```
nameCtrl = new FormControl('Jane');
```

The error will go away
#### Which versions of Angular, Material, OS, browsers are affected?

`Angular 2 rc 6` with `Material alpha 8.1`

**Comment by zigzag95** [comment] 2016-09-09 07:36
+1

**Comment by zigzag95** [comment] 2016-09-09 07:37
@kara Help please

**Comment by corey-waymark** [comment] 2016-09-13 14:38
I'm seeing this with md-checkbox too, so I would assume it is a wider angular2-material issue.

**Comment by mehdi1802** [comment] 2016-09-13 19:41
+1

**Comment by tomwanzek** [comment] 2016-10-03 00:21
The issue still occurs, and ,unfortunately, leaves the `md-input` unusable in a purely reactive setting requiring state-driven disabling/enabling.

It reproduces on `angular-cli beta.16` with `material2 alpha.9-3`.

To add on to the above, the same applies, when using the `.disable()`, method on a FormGroup element, which wraps the `md-input` elements.

Thanks in advance.

**Comment by mhautman** [comment] 2016-10-04 08:36
Here is a work around that works for me:

this.form.controls['val1'].statusChanges.subscribe((newStatus) => {
  let val2 = this.form.controls['val2'];

  if (newStatus === VALID) {
    val2.enable();
  } else {
    val2.disable();
  }
}

**Comment by rbaumi** [comment] 2016-10-11 07:23
+1

Interface `ControlValueAccessor` has now one more method that has to be implemented: [setDisabledState](https://angular.io/docs/ts/latest/api/forms/index/ControlValueAccessor-interface.html#!#setDisabledState-anchor)

**Comment by krigton** [comment] 2016-10-18 13:53
There is `?` which means that it is optional

**Comment by krigton** [comment] 2016-10-18 15:34
It looks if I use  [disabled] on the `md-radio-group` even if it exposes a `disabled` Input I get the warning above. So this means that I cannot hook the `md-radion-group` to a model driven form group and use the `disabled` attribute of the radio group?

**Comment by tomwanzek** [comment] 2016-10-25 14:31
Is there any update on getting proper programmatic disabling to work for use with reactive forms?

**Comment by jelbourn** [comment] 2016-11-04 00:41
@crisbeto we should add `setDisabledState` to all of our forms components

**Comment by RoxKilly** [comment] 2016-11-16 19:51
@crisbeto  The error I originally reported is no longer raised, but setting `disabled=true` on a reactive form control fails to disable the `md-input`

[See this plunk](http://plnkr.co/edit/5wjZKvwxFWHznlbmWe9R?p=preview)

**Comment by crisbeto** [comment] 2016-11-16 20:03
The fix hasn't been merged yet @RoxKilly.

**Comment by Dominionys** [comment] 2016-11-24 21:51
"angular-cli": "1.0.0-beta.16"
material": "^2.0.0-alpha.10"

got this issue with checkbox. Any help?

**Comment by RoxKilly** [comment] 2016-11-25 18:04
@Dominionys The two posts immediately before yours show that the issue was not fixed in time for alpha 10.

**Closed** 2016-11-29 19:19 UTC
Labels: has pr, P2: required
