### ISSUE TITLE
Misalignment of [md-ink-bar] first active child

### ISSUE THREAD

**Issue by frankspin89** [angular/material2#3680] opened 2017-03-20 09:46 UTC
#### Bug, feature request, or proposal:
BUG

#### What is the current behavior?

On the initial load the first active child of the bar is not aligned correctly. After clicking on the child the active bar is positioned correctly. 

![hjgwxl4qbf](https://cloud.githubusercontent.com/assets/4480104/24094776/5f0c70ec-0d5a-11e7-9f4a-f120ca303533.gif)

#### Which versions of Angular, Material, OS, browsers are affected?

Angular 4.0.5 rc
Material beta 2

**Comment by fxck** [comment] 2017-03-20 11:38
most likely dupe of https://github.com/angular/material2/issues/3495

**Comment by jelbourn** [comment] 2017-03-21 23:17
Dupe of #3495

**Closed by jelbourn** 2017-03-21 23:17 UTC
