### ISSUE TITLE
angular/cdk/drag-drop incorrect horizontal multi row layout 

### ISSUE THREAD

**Issue by jendaneu1** [angular/material2#13506] opened 2018-10-09 10:35 UTC
#### Bug, feature request, or proposal:

Horizontal sortable does not work when using more rows of sortable items.

#### What is the expected behavior?
It should behave correctly when specified flex-wrap: wrap on the container.

#### What is the current behavior?
The items are not sorted in correct way and some unexpected drop zones or empty spaces are shown

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

Just look at this example: https://stackblitz.com/angular/gxaxdlegndb?file=app%2Fcdk-drag-drop-horizontal-sorting-example.ts and set flex-wrap: wrap on the list class.

**Comment by crisbeto** [comment] 2018-10-09 10:48
This isn't supported at the moment. As it's set up right now, it'll only look at one axis at a time to determine how the items are sorted.

**Comment by jendaneu1** [comment] 2018-10-09 10:52
OK thanks, is it planned for future? It would be great...

**Comment by JaxonWright** [comment] 2018-10-25 19:05
This would be amazing. My list of items is in a horizontal grid.

**Comment by josephperrott** [comment] 2018-10-30 20:50
Closing as duplicate of #13372

**Closed by josephperrott** 2018-10-30 20:50 UTC
