### ISSUE TITLE
Md-tabs not responsive

### ISSUE THREAD

**Issue by raunakmatai** [angular/material2#4453] opened 2017-05-10 05:52 UTC
#### What is the expected behavior?
the width of ink bar is expected to decrease or increase depending on size.

#### What is the current behavior?
Currently the ink bar width stays in the same until its clicked which is poor.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
It becomes more responsive and good looking in future.

#### Which versions of Angular, Material, OS, browsers are affected?
Material2

#### Is there anything else we should know?
the same component is working fine in angular material 1.
![untitled](https://cloud.githubusercontent.com/assets/13185473/25884745/25aa5cca-3572-11e7-8412-cf99094e58b3.png)
The image is attached above which should give you an idea.Moreover there is no current directive to make the tabs centric. I have to use margin or padding.

**Comment by donroyco** [comment] 2017-05-10 06:01
This has already been reported several times, see e.g. #3469 or #3044. Please use the search function before reporting this.

**Comment by jelbourn** [comment] 2017-05-11 23:44
Dupe of #3044

**Closed by jelbourn** 2017-05-11 23:44 UTC
