### ISSUE TITLE
Table with irregular headers

### ISSUE THREAD

**Issue by fad250** [angular/material2#6732] opened 2017-08-30 13:32 UTC
Feature proposal 1: 

![header](https://user-images.githubusercontent.com/15860769/29874518-9860d90e-8d71-11e7-9d9d-6a7ae106c917.PNG)

Will md-table support irregular headers / columns? 

There numerous places where this can be used while displaying analytics, I hope there is future support for this. 

Feature proposal 2: 
Also, will md-table allow support for dynamic table columns where the column name or number are always changing.

**Comment by willshowell** [comment] 2017-08-30 13:47
1: See https://github.com/angular/material2/issues/5997
2: See https://github.com/angular/material2/pull/5545 and followup https://github.com/angular/material2/issues/5927

**Comment by jelbourn** [comment] 2017-08-30 14:08
Duplicate of #5997

**Closed by jelbourn** 2017-08-30 14:08 UTC

**Comment by finalxcode** [comment] 2017-10-13 09:46
+1 reopen
