### ISSUE TITLE
matMenu ScrollStrategy

### ISSUE THREAD

**Issue by gwidonw** [angular/material2#11776] opened 2018-06-13 13:13 UTC
#### Bug, feature request, or proposal:
MatMenu do not block window scrolling what results in buggy matMenuPanel behaviour including wrong positioning, wrong calculating its size and in some cases hiding outside the screen

#### What is the expected behavior?
Similar to examples on material.angular.io - when mat-menu is visible window scroll is blocked

#### What is the current behavior?
Window scroll is not blocked when mat menu is shown. 

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-gmetyt

#### What is the use-case or motivation for changing an existing behavior?
-

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
6.2.1

#### Is there anything else we should know?
-

**Comment by crisbeto** [comment] 2018-06-13 15:46
`mat-menu` isn't supposed to block scrolling. The position issues will be fixed by https://github.com/angular/material2/pull/11628. Closing as a duplicate of #11365.

**Closed by crisbeto** 2018-06-13 15:46 UTC
