### ISSUE TITLE
Yet another ng add @angular/material error in Angular 6

### ISSUE THREAD

**Issue by Brumiko** [angular/material2#12039] opened 2018-07-03 14:05 UTC
#### Bug, feature request, or proposal:

Command `ng add @angular/material` does not work on fresh Angular 6 project.

#### What is the expected behavior?

Angular Material should be added to the project.

#### What is the current behavior?

Error:

> Cannot read property 'startTag' of undefined

#### What are the steps to reproduce?

Simply go with [official tutorial](https://material.angular.io/guide/getting-started) then to _Schematics_, run `ng add @angular/material`

Or, even more simple:

`ng new ngMatTut2`
`cd ngMatTut2`
`ng add @angular/material`

#### What is the use-case or motivation for changing an existing behavior?

To make it work. So far, I like Angular, and Material seems superior than, say, Bootstrap.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

 - Newest version of Angular/ Angular CL/ Angular Material
 - Ubuntu 16.04, NodeJS 9.11.2, NPM 5.6.0. Node and NPM were installed as bundle from Ubuntu repo.

#### Is there anything else we should know?

It seems to me that everything works only if I install previous version of Material with:
`ng add @angular/material@6.2.1`

It appears to be a lot of reporting here on GitHub of this or similar errors, and older version is the only solution that worked for me.

**Comment by crisbeto** [comment] 2018-07-03 14:44
Closing as a duplicate of https://github.com/angular/material2/issues/12027.

**Closed by crisbeto** 2018-07-03 14:44 UTC

**Comment by gopkhanin** [comment] 2018-07-04 02:58
Same Error
