### ISSUE TITLE
form validations on the input field for chips

### ISSUE THREAD

**Issue by LisaTatum** [angular/material2#9230] opened 2018-01-04 11:01 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
When 'Apple' chip already exists, but the user creates a 2nd 'Apple' I want to highlight an error somewhere around the md-chips component and the 'Apple' should not be added to the chips.

#### What is the current behavior?
I can add as much duplicate chips as I want

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

There are no steps to reproduce, as that feature does not exist yet...

#### What is the use-case or motivation for changing an existing behavior?
Its a common business requirement not to enter duplicate data

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest

#### Is there anything else we should know?
nope

**Comment by tinayuangao** [comment] 2018-01-09 23:35
Duplicate of #8819.

**Closed by tinayuangao** 2018-01-09 23:35 UTC

**Comment by LisaTatum** [comment] 2018-01-10 07:06
@tinayuangao  Why are you closing this request and refer to other closed requests which are refer to THIS closed request??? By doing this you close all requests... 

This is the only open request: https://github.com/angular/material2/issues/8801

but thats a total different topic => broken behavior:
"...It doesn't react to addition/insertions, so no validation can be trigger/shown..."

That guy does not ask for input validation with forms controls.
That guy does not ask for adding a unique chip to the chips list or prevent that via unique configuration.

**Comment by SearchingSoul** [comment] 2018-01-14 05:06
@LisaTatum, possible workaround that I have used is to remove 'apple' from the fruits array when added to the chips list.
You will have to push 'apple' to the fruits array when the 'apple' chip is removed.
