### ISSUE TITLE
problem in material2,md-list-item in md-list grows up on the screen instead of down.So i guess the md-list is not growing with the md-list-items

### ISSUE THREAD

**Issue by stefanaerts** [angular/material2#1640] opened 2016-10-28 12:39 UTC
#### Bug, feature request, or proposal:

The item list is not completely shown the screen,it just moves the data above the top of the screen. If i disable "display:flex or align-items:center" on the generated div.md-list-item in chrome devtools then it shows everything.

https://drive.google.com/open?id=0By7_cJqSCsKNMno4ZHM1RDZCOFU

Thanks
#### What is the expected behavior?

To see all data on the screen
#### What is the current behavior?

md-list-item in md-list grows up on the screen instead of down.So i guess the md-list is not growing with the md-list-items
#### What are the steps to reproduce?

just make a list with rows using md-list and md-list-item

Providing a Plunker (or similar) is the _best_ way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
#### Which versions of Angular, Material, OS, browsers are affected?

"@angular/material": "^2.0.0-alpha.9-3",

**Comment by stefanaerts** [comment] 2016-10-28 15:19
I found a workaround.
https://drive.google.com/open?id=0By7_cJqSCsKNQVBSXzA1VEVzM0U

But i still wonder why the default display was like that?

**Comment by stefanaerts** [comment] 2016-10-28 15:49
i found a workaround
![image](https://cloud.githubusercontent.com/assets/3684599/19812656/c13079a6-9d36-11e6-9769-6ce539bcae90.png)

the display:initial!important is the workaround.

**Comment by fxck** [comment] 2016-10-28 19:21
provide a non-working plunker reproduction

**Comment by stefanaerts** [comment] 2016-10-28 19:56
http://plnkr.co/edit/WaTKxqKMfCRKOjVQtLOf?p=info

![image](https://cloud.githubusercontent.com/assets/3684599/19820375/5f3ced4c-9d59-11e6-9505-2f879a420d8a.png)

**Comment by fxck** [comment] 2016-10-28 20:42
That's because `md-list-item` have height set to 48px, which is likely per spec. You are probably trying to use it for something it was never meant to be used for.

**Comment by stefanaerts** [comment] 2016-10-28 20:53
i am using a md-list within a md-list, so 2 ngfor loops,outer and inner, then i have this problem

**Comment by stefanaerts** [comment] 2016-10-29 09:14
@fxck I will not use the double ngFor loop.
But i need to find the best way to accomplish the following scenario:
ngfor "let item of ordered products"
some products are ordered multiple times, but with different options.

So the first field i show is a function getCount(product.key),
then i want to show the productname only 1 time when multiple times in this list,but the options need to be shown each time.
Something like this picture:
![image](https://cloud.githubusercontent.com/assets/3684599/19828529/dc5577d6-9dc7-11e6-87f0-b520018c9c30.png)

So the item "Product + bisquits" is more then 1 time in "let item of products" ,
but i want to show 1 time product.name but every time the item<product.options> lines.

If i do this with 2 ngfors in 2 md-lists i get problems with the display of the options lines.

**Comment by stefanaerts** [comment] 2016-10-31 17:29
@fxck  So its normal that the the container(md-list) does not grow in height when the list-items
get a bigger height?
https://drive.google.com/open?id=0By7_cJqSCsKNNnBLVHJEQzQ4YTg

**Comment by fxck** [comment] 2016-10-31 19:29
What you could do is changing this https://github.com/angular/material2/blob/master/src/lib/list/list.scss#L41 to be `min-height` instead of `height`.

**Comment by stefanaerts** [comment] 2016-11-01 10:24
@fxck  @kara 
https://drive.google.com/open?id=0By7_cJqSCsKNelhJMkU3M09BOXc

Its not a big issue for me to finish the screen i make, i can put a big padding-top on md-list for example.
But its just something i try to understand why its working that way and how to overwrite some settings to make it only grow dawn on the screen.
I guess more users who will use material in the future will have these kind of difficulties.
For sure when you don't have written a lot css and html before.

Kind Regards,
Stefan.

**Comment by jelbourn** [comment] 2017-06-06 21:33
Closing this since it's not clear what the original problem was. Feel free to open a new issue if there is still some bug that needs to be resolved.

**Closed by jelbourn** 2017-06-06 21:33 UTC
