### ISSUE TITLE
Material Design Angular Modal example not working in stackblitz

### ISSUE THREAD

**Issue by GRRedWings** [angular/material2#11229] opened 2018-05-08 19:38 UTC
I try to run the example from the example page in stackblitz and it throws an error.  I'm using Chrome

Example Page: https://material.angular.io/components/dialog/examples
StackBlitz Page: https://stackblitz.com/angular/lnadlexdqyl?file=app%2Fdialog-overview-example.html

Error in /turbo_modules/@angular/compiler@5.2.10/bundles/compiler.umd.js (529:34)
Unexpected value 'undefined' exported by the module 'DemoMaterialModule'
Evaluating main.ts
Booting application

**Comment by mtrdp642** [comment] 2018-05-09 00:33
Same issue as #11223. Temporary fix is to install the latest dependencies within StackBlitz for Material, CDK, rxjs, and all angular packages.

**Comment by jelbourn** [comment] 2018-05-09 20:37
Duplicate of #11223

**Closed by jelbourn** 2018-05-09 20:37 UTC
