### ISSUE TITLE
Keyboard-navigation not working with md-menu

### ISSUE THREAD

**Issue by vipdorian** [angular/material2#2657] opened 2017-01-14 17:35 UTC
#### Bug, feature request, or proposal:
Keyboard-navigation not working with md-menu

#### What is the expected behavior?
See design doc, section accessibility : https://docs.google.com/document/d/1cSUrY2WAqSN8ePldLLqrEVkk2BkYbPB2fysC6brvj4Q/preview
DOWN_ARROW: Focus next menu item
UP_ARROW: Focus previous menu item
ENTER: Select focused item

#### What is the current behavior?
No action when hitting, down_arrow, up_arrow or enter.

#### What are the steps to reproduce?
Browse to https://material.angular.io/components/component/menu
Open menu, hit DOWN_ARROW.

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0 beta 1

**Comment by codef0rmer** [comment] 2017-01-15 09:57
@vipdorian It's not a bug because for keyboard navigation to work, it has to regain focus which can be done using enter. Just open the menu by mouse click, hover over any menu item, press enter to close it, press enter to open it, and then use up/down arrow.

**Comment by vipdorian** [comment] 2017-01-15 15:04
@codef0rmer 
Thank you for the reply. Indeed, it is only a matter of focus. However, in version 1 of Angular Material, the menu would gain focus on click, this is not the case with angular/material2.

**Comment by codef0rmer** [comment] 2017-01-15 15:13
@vipdorian I see. It's a bug for sure!

**Comment by codef0rmer** [comment] 2017-01-15 15:33
@vipdorian Not sure which material framework is right. But having it fixed would require one less LOC :-)

https://github.com/angular/material2/blob/master/src/lib/menu/menu-trigger.ts#L145

**Comment by kara** [comment] 2017-01-24 18:00
This is intended behavior. The focus style is only applied if the menu was opened by the keyboard.

**Closed by kara** 2017-01-24 18:00 UTC
