### ISSUE TITLE
Custom class on select overlay

### ISSUE THREAD

**Issue by robianmcd** [angular/material2#3292] opened 2017-02-24 20:57 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the desired behavior?
There would be a way to specity a custom class on the overlay for a select element. e.g.
```HTML
<md-select overlayClass="my-theme-1"></md-select>
```

#### What is the current behavior?
No way to add a custom class to the overlay for a select

#### What is the use-case or motivation for changing an existing behavior?
I'm using multiple themes in the way described in the guide .e.g.

```
@include angular-material-theme($defaultTheme);

.my-theme-1 {
  @include angular-material-theme($myTheme1);
}

.my-theme-2 {
  @include angular-material-theme($myTheme2);
}
```

So if I have a select inside an element with `class="my-theme-1"` I would want the select to get the styles form `$myTheme1`. 

```HTML
<div class="my-theme-1">
  <md-select></md-select>
</div>
```

This doesn't work for the select's overlay as the overlay is appended to the body.

#### Which versions of Angular, Material, OS, browsers are affected?
Material: beta-2

**Comment by kara** [comment] 2017-02-24 21:26
This looks like a dupe of https://github.com/angular/material2/issues/2662. We have a PR waiting to merge [here](https://github.com/angular/material2/pull/2967) that will allow  easy adding of themes to overlay-based components, so should get in soon.

**Closed by kara** 2017-02-24 21:26 UTC

**Comment by robianmcd** [comment] 2017-02-24 21:30
@kara great thanks! I'll keep an eye on that PR
