### ISSUE TITLE
mat-datepicker required issue

### ISSUE THREAD

**Issue by dividebyz** [angular/material2#9942] opened 2018-02-14 10:12 UTC
#### Bug, feature request, or proposal:
mat-datepicker validator issue with required field.

#### What is the expected behavior?
mat-datepicker should not raise a required error when the input contains a value.

#### What is the current behavior?
mat-datepicker raises a required error even if input contains a value, on our test case, the value is not a valid date. When the date is valid, the required error is not raised (expected behavior).

#### What are the steps to reproduce?
https://angular-material2-issue-5fzzvu.stackblitz.io/

#### What is the use-case or motivation for changing an existing behavior?
Behaviour is not consistent with the rest of the Angular Forms.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.1
Angular Material: 5.2.0
Ubuntu 16.04 (via Vagrant on Windows 10)
Google Chrome (latest)

#### Is there anything else we should know?
In the StackBlitz provided, type a non valid date (e.g. 'bananas'), then remove the focus from the input (click outside), you will then see that two errors will appear:

- required
- matDatePickerParse

We were expecting not to have the required error, but the matDatePickerParse error only.

**Comment by mmalerba** [comment] 2018-02-15 23:09
This is consistent with native input parsing behavior (e.g. type=number):

See following example, enter "e" to the number input:
https://stackblitz.com/edit/angular-material2-issue-afgb7x?file=app/app.component.ts

Closing since it is working as intended

**Closed by mmalerba** 2018-02-15 23:09 UTC

**Comment by micobarac** [comment] 2019-08-13 09:20
This is insane logics. `required = true` shouldn't be set if date field is not empty, like any other input field using `Validators.required`.

Currently, even in Angular 8, there is no way to distinguish between empty datapicker and invalid datapicker value, which is a disaster.
