### ISSUE TITLE
feature request: datepicker add change event

### ISSUE THREAD

**Issue by stevenmi** [angular/material2#4733] opened 2017-05-23 04:30 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
when i select a date the change event will be emitted 

#### What is the current behavior?
when select a date the change event can not be emitted 

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
https://plnkr.co/edit/ulSNTMTMZmORzvkVTvch?p=preview

#### What is the use-case or motivation for changing an existing behavior?
when i select a date ,i can compare the date with another date , to set the submit button disable or enable

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.1.3
material material@2.0.0-beta.5-eecf897
win10
typescript 2.3.1
chrome 58.0.3029.110 (64-bit)

**Comment by willshowell** [comment] 2017-05-23 16:25
Dupe of https://github.com/angular/material2/issues/4615

**Comment by stevenmi** [comment] 2017-05-23 16:57
@willshowell  thanks

**Closed** 2017-05-23 23:28 UTC
