### ISSUE TITLE
mat tab inside tab selected index not working 

### ISSUE THREAD

**Issue by sorb999** [angular/material2#9108] opened 2017-12-23 08:13 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When tab inside tab then if selected index of sub tab is 1 then it should show as selected.

#### What is the current behavior?
Let parent tab has two tabs, it has `selectedIndex` is 0, and sub tab inside parent tab1 has `selectedIndex` = 1 then content inside it showing but is not showing as selected.

#### What are the steps to reproduce?
Providing a StackBlitz https://stackblitz.com/edit/angular-e3m6wb?file=app/tabs-overview-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All versions and browser

**Comment by julianobrasil** [comment] 2017-12-23 19:53
Probably has the same root cause as #5269.

**Comment by jelbourn** [comment] 2018-01-02 23:45
Closing since I think this is a duplicate of #5269 (same underlying cause).

**Closed by jelbourn** 2018-01-02 23:45 UTC

**Comment by sandroschmid** [comment] 2019-07-24 05:58
I just faced this issue with v7.3. Using lazy loading for the parent tabs solved it for me

https://v7.material.angular.io/components/tabs/overview#lazy-loading
