### ISSUE TITLE
CDK scrollDispatcher not subscribing to nativeElements' positions

### ISSUE THREAD

**Issue by akolybelnikov** [angular/material2#13162] opened 2018-09-17 11:19 UTC
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
a `scrollDispatcher.scrolled()` subscription should provide dynamically updated position values of the DOM elements when a scroll event fires.

#### What is the current behavior?
the position values of the elements remain static as of the moment the subscription starts, regardless of a `cdkScrollable ` directive put on the container element, or not

#### What are the steps to reproduce?

[here's the link to the stackblitz project](https://stackblitz.com/edit/angular-cdk-scrollable-event?file=src%2Fapp%2Fapp.component.ts)

#### What is the use-case or motivation for changing an existing behavior?
what is the purpose of an observable with frozen static values?

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3
Angular CDK 6.1.0

**Comment by jelbourn** [comment] 2018-10-04 22:47
Closing as intended behavior.

**Closed by jelbourn** 2018-10-04 22:47 UTC
