### ISSUE TITLE
Material Snackbar Does Not Allow For Positioning on the Left Only Center

### ISSUE THREAD

**Issue by mtpultz** [angular/material2#3940] opened 2017-04-06 19:42 UTC
#### Bug, feature request, or proposal:
Bug (more like missing functionality)

#### What is the expected behavior?
According to the material design spec toasts/snackbars should be either centered or left aligned at the bottom of the viewport.

#### What is the current behavior?
The only position available is centered.

#### What are the steps to reproduce?
This is a missing bit of functionality in the configuration of the MdSnackBar and doesn't need to be reproduced it just isn't available.

#### What is the use-case or motivation for changing an existing behavior?
It doesn't meet the material design spec.

#### Which versions of Angular, Material, OS, browsers are affected?
N/A

**Comment by crisbeto** [comment] 2017-04-06 20:02
Closing as a dupe of https://github.com/angular/material2/issues/3577.

**Closed by crisbeto** 2017-04-06 20:02 UTC
