### ISSUE TITLE
Menu with many items not showing up properly in small screen

### ISSUE THREAD

**Issue by zijianhuang** [angular/material2#12574] opened 2018-08-08 02:17 UTC
#### Bug:
When the menu has many items, and the view port is small, and the menu button is slightly above the middle of the view port, the menu is popping up far away from the menu button, and sometimes even outside the view port, so the user could not see it.

#### What is the expected behavior?

The popup should appear near the menu button. If the button is above the middle, the popup should appear downward and use at least half height of the view port. 

If the button is below the middle, the popup should appear upward and use at least half height of the view port

#### What are the steps to reproduce?
In the tutorial example, https://stackblitz.com/angular/lmgjakyxjvxo, update the following to https://stackblitz.com/angular/lmgjakyxjvxo?file=app%2Fmenu-icons-example.html
```html
<p>a</p>
 <p>b</p>
 <p>c</p>
 <p>a</p>
 <p>b</p>
 <p>c</p>
 <p>a</p>
 <p>b</p>
 <p>c</p>
 
 <button mat-icon-button [matMenuTriggerFor]="menu">
  <mat-icon>more_vert</mat-icon>
</button>
<mat-menu #menu="matMenu">
          <ng-template matMenuContent>
 <button mat-menu-item>
    <mat-icon>dialpad</mat-icon>
    <span>Redial</span>
  </button>
  <button mat-menu-item disabled>
    <mat-icon>voicemail</mat-icon>
    <span>Check voicemail</span>
  </button>
  <button mat-menu-item>
    <mat-icon>notifications_off</mat-icon>
    <span>Disable alerts</span>
  </button>  <button mat-menu-item disabled>
    <mat-icon>voicemail</mat-icon>
    <span>Check voicemail</span>
  </button>
  <button mat-menu-item>
    <mat-icon>notifications_off</mat-icon>
    <span>Disable alerts</span>
  </button>  <button mat-menu-item disabled>
    <mat-icon>voicemail</mat-icon>
    <span>Check voicemail</span>
  </button>
  <button mat-menu-item>
    <mat-icon>notifications_off</mat-icon>
    <span>Disable alerts</span>
  </button>  <button mat-menu-item disabled>
    <mat-icon>voicemail</mat-icon>
    <span>Check voicemail</span>
  </button>
  <button mat-menu-item>
    <mat-icon>notifications_off</mat-icon>
    <span>Disable alerts</span>
  </button>  <button mat-menu-item disabled>
    <mat-icon>voicemail</mat-icon>
    <span>Check voicemail</span>
  </button>
  <button mat-menu-item>
    <mat-icon>notifications_off</mat-icon>
    <span>Disable alerts</span>
  </button>  <button mat-menu-item disabled>
    <mat-icon>voicemail</mat-icon>
    <span>Check voicemail</span>
  </button>
  <button mat-menu-item>
    <mat-icon>notifications_off</mat-icon>
    <span>Disable alerts</span>
  </button>
          </ng-template>
</mat-menu>

<p>a</p>
 <p>b</p>
 <p>c</p><p>a</p>
 <p>b</p>
 <p>c</p><p>a</p>
 <p>b</p>
 <p>c</p><p>a</p>
 <p>b</p>
 <p>c</p>

```

1. Make the view port small, or just test in a smart phone, 
2. Make the menu button stay slight above or below the middle of the view port,
3. Click the menu button

#### What is the use-case or motivation for changing an existing behavior?
I want the same responsive design works on desktop, tablet and smart phone, and the context menu has a lot items, so it is good that the user could see the context menu even if the menu button is at the middle of the view port.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 6.10, Angular Material 6.4.2

**Comment by zijianhuang** [comment] 2018-08-08 02:30
In my smartphone with 1920x1080 resolution and Pixel Ratio 3, the menu is seemly not popping when the menu button is slightly above the middle of the screen. However, when moving the scrollable content along with the menu button upward or download a little bit, the menu will then appear.

**Comment by crisbeto** [comment] 2018-08-08 14:56
Closing as a duplicate of https://github.com/angular/material2/issues/11365.

**Closed by crisbeto** 2018-08-08 14:56 UTC
