### ISSUE TITLE
sidenav doesn't work, 'open' method bug

### ISSUE THREAD

**Issue by Halynsky** [angular/material2#4944] opened 2017-06-03 08:15 UTC
#### Bug, feature request, or proposal:
Bug is heppening when I try to call 'open' function of the sidenav

#### What is the expected behavior?

Sidenav content is shown on page

#### What is the current behavior?

Script error, sidenav content isn't shown on page

#### What are the steps to reproduce?

You can reproduce similar bug at https://material.angular.io/components/component/sidenav

http://prntscr.com/ffd33a

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

  "dependencies": {
    "@angular/animations": "^4.1.3",
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.1.3",
    "@angular/material": "2.0.0-beta.5",
    "@angular/flex-layout": "2.0.0-beta.8",
    "@covalent/core": "1.0.0-beta.4",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-browser-dynamic": "^4.1.3",
    "@angular/router": "^4.1.3",
    "@ngui/auto-complete": "^0.13.2",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "ng2-truncate": "^1.3.7",
    "rxjs": "^5.4.0",
    "zone.js": "^0.8.11",
    "node-sass": "^4.5.3"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.5",
    "@angular/compiler-cli": "^4.1.3",
    "@types/jasmine": "2.5.45",
    "@types/node": "~7.0.22",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.2.0"
  }

**Comment by crisbeto** [comment] 2017-06-03 09:04
I couldn't reproduce it in master. You can try out the latest build to see if it helps:

```
npm install https://github.com/angular/material2-builds.git
```

**Comment by dahaupt** [comment] 2017-06-03 10:14
Then it should be fixed in the docs site here https://github.com/angular/material.angular.io .

**Comment by crisbeto** [comment] 2017-06-03 10:16
The examples from the docs are hosted in this repo and they seem to work against master.

**Comment by andrewseguin** [comment] 2017-06-05 23:26
Note that the plunker example works fine. https://plnkr.co/edit/XClj0iC8G9JDZTU7gkCf?p=preview

Looks to be an issue with the docs site or the particular build of material it is using

**Comment by castamir** [comment] 2017-06-07 07:47
doc is not fixed so this issue should stay opened

**Comment by mmalerba** [comment] 2017-07-17 19:13
Not seeing this issue one the docs site anymore, so closing

**Closed by mmalerba** 2017-07-17 19:13 UTC
Labels: docs, P3: important
