### ISSUE TITLE
MdButton onclick GUI goes wrong, its border become distorted bigger on each click

### ISSUE THREAD

**Issue by 14Muhammad** [angular/material2#1105] opened 2016-08-23 17:40 UTC
#### Bug:
MdButton onclick GUI goes wrong, its border become distorted bigger on each click

#### What is the expected behavior?
It should not distorted on click event

#### What is the current behavior?
It border in spreads towards bottom side.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular version 2.0.0-rc.5
Material version 2.0.0-alpha.7-3
OS Windows
Google chrome

**Comment by 14Muhammad** [comment] 2016-08-23 17:40
[](url)

**Comment by 14Muhammad** [comment] 2016-08-23 17:41
[](url)

**Comment by RoxKilly** [comment] 2016-08-24 18:47
This error was not present in `alpha 6`. I first noticed it when I upgraded from 6 to `alpha 7-2` and it also affects `7-2`

I think the problem may have to do with button ripple animation taking ever more space with each click. After a few clicks, the scroll bars appear even though no content is visible.

**To reproduce:**
 - [Open this plunker](http://plnkr.co/edit/MuMvLWkvjT2mXncRM2an?p=preview)
 - In the `HomeComponent`, click the button `ng-Material button` 5 or 6 times. You'll see the scroll bars appear.
 - In the `LazyLoadedComponent`, click the button `Regular button`. No scroll bar appears even though the templates for the two components are the same.

In `HomeComponent`, changing: `<button md-raised-button ....>` to a simple `<button...>` will make the issue go away.

**Comment by armno** [comment] 2016-08-25 03:00
It looks like `<div class="md-ripple-background">`'s are created every time the button is clicked and get bigger but they don't go away.

Screenshot taken from @RoxKilly 's plunkr:

![ripple](https://cloud.githubusercontent.com/assets/911894/17955199/96067b0e-6aaa-11e6-950c-449d3f362d3b.png)

**Comment by msegers** [comment] 2016-08-25 07:43
Can confirm this happens on all my forms. I was thinking it was an issue with my own custom styling though couldn't find the problem.

**Comment by cladera** [comment] 2016-08-25 08:16
Same issue here

**Comment by RoxKilly** [comment] 2016-08-25 14:50
A temporary hack-around is to add the CSS styling:
```
.md-ripple-foreground {display:none}
```
I haven't looked into the side-effects of this hack

**Comment by ivoviz** [comment] 2016-08-25 19:12
See #972. Just simply load the `core.css` file from `@angular2-material/core/style/core.css`. Should be mentioned in the docs.

**Comment by RoxKilly** [comment] 2016-08-25 20:32
@ivoviz  Thanks for linking that other discussion. That's helpful.

**Comment by jelbourn** [comment] 2016-08-31 01:08
Closing this into #1139

**Closed by jelbourn** 2016-08-31 01:08 UTC
