### ISSUE TITLE
MatExpansionPanel content visible when closed 

### ISSUE THREAD

**Issue by bmrana** [angular/material2#10592] opened 2018-03-27 19:24 UTC
#### Bug, feature request, or proposal:
A tab group contains at least 2 tabs.  Each tab contains a series of cards.  Each card has an expansion panel.  Changing the visibility of cards on one tab from a selector on another tab causes the expansion panel content to be visible, although the panels are closed.

#### What is the expected behavior?
The content of an expansion panel should not be visible unless the panel is open.

#### What is the current behavior?
The content of an expansion panel is visible even though the state of the panel is closed.

#### What are the steps to reproduce?
Stackblitz       https://stackblitz.com/edit/angular-u3tyhk

1.  Load the above stackblitz
2.  Notice that Black is selected on the button toggle
3.  The Black card on the Colors tab displays correctly.
4.  Switch to the Words tab.
5.  Notice how the black card expansion panel is still in a closed state, but the expansion panel content is visible.
6.  Click the Red button in the button group and notice how the red card in Words now displays correctly.
7.  Switch to the Colors tab and notice that the Red card has the expansion panel content visible.

#### What is the use-case or motivation for changing an existing behavior?
The content of an expansion panel should never be visible if the panel is not open.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5 and Material 5.2.4

#### Is there anything else we should know?
This occurs when the content of the panel is in ng-template as well...the header shifts up and there is a blank content area below it.

**Comment by julianobrasil** [comment] 2018-03-28 03:36
Dupe: #5269

**Comment by josephperrott** [comment] 2018-03-28 15:53
Closing as duplicate of #5269

**Closed by josephperrott** 2018-03-28 15:53 UTC
