### ISSUE TITLE
md-select initial bind fails for value of zero

### ISSUE THREAD

**Issue by CraigWarford** [angular/material2#5142] opened 2017-06-15 01:59 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When an md-select is constructed and bound using [(ngModel)], the value should be used to select the option for all values.

#### What is the current behavior?
When the bound value is zero, no option is selected.

#### What are the steps to reproduce?
Create md-select with several entries, with values set to 0, 1, 2, 3.  Bind to a property that has 1 for the value.  Load it up, and note that the option with value of 1 behind it is selected.  Change the property value to 0, and reload.  Note that no options are selected.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
Can't seem to get plunker to load any Angular examples/templates at the moment...

#### What is the use-case or motivation for changing an existing behavior?
When reloading a form, if a value is zero, there is currently no way to show the actual representation of the value using a select box.  The behavior for zero differs from all other values.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.1, Angular Material 2.0.0 beta 6

**Comment by julianobrasil** [comment] 2017-06-15 02:27
Dupe of #5080.

It'll be solved next beta release.

**Closed** 2017-06-15 05:26 UTC
