### ISSUE TITLE
open contextmenu where mouse is clicked for mat-menu

### ISSUE THREAD

**Issue by gunjan11939** [angular/material2#8609] opened 2017-11-23 09:26 UTC
Actual Behavior:

position of menu is fixed irrespective of where mouse is clicked

Expected Behaviour:
Menu should be opened where the mouse is clicked

AngularJS Versions: *

AngularJS Version: Angular 4
AngularJS Material Version: 2.0.0-beta.12
Additional Information:

Browser Type: chrome, IE
OS:windows 7

**Comment by Chan4077** [comment] 2017-11-23 09:38
Duplicate of #5007.

See [this comment](https://github.com/angular/material2/issues/5007#issuecomment-315645280) on how to implement a workaround.

**Comment by crisbeto** [comment] 2017-11-23 09:44
Closing as a duplicate.

**Closed by crisbeto** 2017-11-23 09:44 UTC
