### ISSUE TITLE
make demo app online available for the public

### ISSUE THREAD

**Issue by maku** [angular/material2#7650] opened 2017-10-09 06:45 UTC
#### Bug, feature request, or proposal:
Feature

#### What is the expected behavior?
The demo app (src/demo-app) should be available online for the public (e.g. accessible via https://material.angular.io)

#### What is the current behavior?
You have to checkout the material2 project and build it by yourself (npm run demo-app). But this does not work with windows OS (at least for me)

**Comment by Chan4077** [comment] 2017-10-09 08:48
Duplicate of #7077.

**Comment by jelbourn** [comment] 2017-10-10 13:06
Duplicate of #7077.

**Closed by jelbourn** 2017-10-10 13:06 UTC
