### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by carneirocorp** [angular/material2#9806] opened 2018-02-06 17:41 UTC
#### Bug, feature request, or proposal:
Seems like MatDividerModule import is generating an error in all examples related to sidenav.

#### What is the expected behavior?
Example shown.

#### What is the current behavior?
Error...

#### What are the steps to reproduce?
Visit this website: https://material.angular.io/components/sidenav/overview
Open any "Edit in StackBlitz"

#### What is the use-case or motivation for changing an existing behavior?
Without examples, the developer life is not easy.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All examples on this page.

#### Is there anything else we should know?
Suggestion https://stackblitz.com/edit/angular-ibq1uc?file=main.ts

**Comment by donroyco** [comment] 2018-02-06 21:24
Duplicate of #9805

**Comment by jelbourn** [comment] 2018-02-13 23:14
Should be fixed now

**Closed by jelbourn** 2018-02-13 23:14 UTC
