### ISSUE TITLE
Autocomplete not working in ios safari

### ISSUE THREAD

**Issue by Saul-Simhon** [angular/material2#6819] opened 2017-09-03 13:52 UTC
#### Bug, feature request, or proposal:

Autocomplete does not work on latest version of iOS safari.

#### What is the expected behavior?

The suggestions should pop-up properly aligned with the textbox

#### What is the current behavior?
The suggestions pop-up initially too high above the textbox, and as one scrolls they disappear.
Further, as one enters text, the suggestion box also disappears out of view. See screenshot:

This problem seems to be correlated with the iOS keyboard display. 

![img_0670](https://user-images.githubusercontent.com/7129678/30003604-07e86e62-908e-11e7-821f-58c4da1d480e.PNG)

Suggestion box disappears after scrolling up: 

![img_0671](https://user-images.githubusercontent.com/7129678/30003606-0ccb13b2-908e-11e7-963f-a2b2f11c5a29.PNG)
  
Or, suggestion box disappears after entering text

![img_0669](https://user-images.githubusercontent.com/7129678/30003563-551f54b2-908d-11e7-83c7-3ab2c2c2494c.PNG)

#### What are the steps to reproduce?

Visit the DEMO site on an iPhone; see the example for autocomplete component and actually try using it.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
The component is completely not usable on iOS devices.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
The version used for the angular material demo site as of Sept 3.

**Comment by crisbeto** [comment] 2017-11-28 18:12
Closing as a dupe of https://github.com/angular/material2/issues/6341.

**Closed by crisbeto** 2017-11-28 18:12 UTC
