### ISSUE TITLE
Layout of docs page is broken

### ISSUE THREAD

**Issue by CramericaIndustries** [angular/material2#15363] opened 2019-03-02 10:40 UTC
#### What is the expected behavior?
Docs page text to be responsive, adjusting to the width of the browser window.

#### What is the current behavior?
Text is overflowing the browser window and no horizontal scrollbar is visible.
When viewing that page on an iPad it won't let you scroll down.

#### What are the steps to reproduce?
Go to [https://material.angular.io/cdk/drag-drop/overview](https://material.angular.io/cdk/drag-drop/overview) and resize your browser window. Or open that page on an iPad.
![untitled-1](https://user-images.githubusercontent.com/5860703/53680747-f35f6680-3cdf-11e9-83fc-95e6392ef09b.jpg)

**Comment by Sriharish** [comment] 2019-03-03 23:15
I can confirm this as well on Chrome v72.0.3626.105 for Android on Galaxy Note 5. The issue is present when viewing as mobile or even as "Desktop site", but I'm still able to scroll right/left with touch on the device.

**Comment by Sriharish** [comment] 2019-03-04 01:45
This is a duplicate of [Open Issue #550](https://github.com/angular/material.angular.io/issues/550). The issue belongs with the material.angular.io repo since it's an bug with the docs site and not the component library. I think it's safe to close here.

**Closed** 2019-03-04 07:07 UTC
