### ISSUE TITLE
Material Datepicker critical problem

### ISSUE THREAD

**Issue by filipemarruda** [angular/material2#7463] opened 2017-10-02 02:23 UTC
#### Bug:
The selected value and the input text value are different.

#### What is the expected behavior?
Is expected that the two values will be the same.

#### What is the current behavior?
The values are different.

#### What are the steps to reproduce?
Just access the official example on the forward example:

#### What is the use-case or motivation for changing an existing behavior?
It is a critical error to unexperienced users.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
The last version.

#### Is there anything else we should know?
There are other errors in the popup that we observed. If you click on it, the month will be show in an incorrect order and OCT button are show twice.

![screen shot 2017-10-01 at 23 19 57](https://user-images.githubusercontent.com/1718876/31062229-587ab2d6-a6ff-11e7-9bcc-2fb6a2fc5137.png)
![screen shot 2017-10-01 at 23 15 12](https://user-images.githubusercontent.com/1718876/31062228-5879970c-a6ff-11e7-8111-93bc0174132b.png)

**Comment by julianobrasil** [comment] 2017-10-04 02:26
Do you see this behaviour in diferent machines? It's working just fine over here. There was another issue similar to yours, but the problem apparently was with some specific  computer configuration.

**Comment by faelmorais** [comment] 2017-10-06 18:14
@julianobrasil I'm having the same issue, but only on Chrome 61.0.3163.91, Opera 48.0.2685.32 and Firefox 55.0.3-64 bits. Safari works fine. Do you have a link to the issue you mentioned? I could't find it.

**Comment by josephperrott** [comment] 2017-10-06 22:49
Can you provide a reproduction in either [Plunker](http://plnkr.co/edit/LSgU9X5sYVhx4bc3LBWm?p=preview) or [StackBlitz](https://stackblitz.com/edit/angular-material2-issue?file=app%2Fapp.component.ts)

**Comment by julianobrasil** [comment] 2017-10-07 00:01
@faelmorais , here it is: #6871

**Comment by jt-helsinki** [comment] 2017-10-17 06:32
I think this is related to #7167

**Comment by mmalerba** [comment] 2017-10-17 18:42
likely dupe of #7167

**Closed by mmalerba** 2017-10-17 18:42 UTC
Labels: cannot reproduce
