### ISSUE TITLE
Angular Material Table cannot center columns

### ISSUE THREAD

**Issue by DenisBarzanov** [angular/material2#14803] opened 2019-01-11 23:40 UTC
#### Bug, feature request, or proposal:
I am using Angular Material Table and I am trying to center all the columns
By these images I mean what I am trying to achieve and that is merely a **centering of the columns**. I have given a link to a <a href="https://stackblitz.com/angular/ndjvyykgoje?file=app%2Ftable-basic-example.ts">StackBlitz</a> demo, which is the one from the <a href="https://material.angular.io/components/table/overview">Offical Docs</a>.
It would be more than enough if you manage to **center the columns**.

I have tried 
<pre><code>display: flex;
justify-content: center;
</pre></code>
, but it worked ifff I used the `<mat-table>` tags, but as I want a **better horizontal scrolling**, but I had to move to `<table mat-table>`, which I like more btw and `<mat-table>` doesn't support horizontal scrolling well. 
When I apply the aforementioned CSS everything breaks. 

If I try to do it the old school way with `text-align: center`
<img width="100%" src="https://i.imgur.com/A3O88Je.png" />
The headers are misaligned and the columns are as well due to paddings inside the cells.

If you have any ideas, please share them.
#### What is the expected behavior?
All the columns are centered.
<img width="100%" src="https://i.imgur.com/zUl1TFR.png" />

#### What is the current behavior?
Nothing is centered

<img src="https://i.imgur.com/MOKqRrn.png" />

## 🔬 Minimal Reproduction
StackBlitz starter: https://stackblitz.com/angular/ndjvyykgoje?file=app%2Ftable-basic-example.ts
## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.1.3
Node: 10.14.2
OS: linux x64
Angular: 7.1.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.3
@angular-devkit/build-angular     0.11.3
@angular-devkit/build-optimizer   0.11.3
@angular-devkit/build-webpack     0.11.3
@angular-devkit/core              7.1.3
@angular-devkit/schematics        7.1.3
@angular/cdk                      7.2.0
@angular/cli                      7.1.3
@angular/flex-layout              7.0.0-beta.22
@angular/material                 7.2.0
@ngtools/webpack                  7.1.3
@schematics/angular               7.1.3
@schematics/update                0.11.3
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

</code></pre>

**Comment by lroedal** [comment] 2019-01-13 17:53
You should omit td and tr, and use <mat-table> instead of <table mat-table>. I've provided a Stackblitz where the columns are centered: https://stackblitz.com/edit/mat-table-centered-columns

**Comment by DenisBarzanov** [comment] 2019-01-13 18:02
I edited my question (The tags didn't show up before). I went on and used `<table mat-table>, because it provides support for horisontal scrolling. I couldn't find anything about centering `<table mat-table>`, nor did I find about horisontal scrolling on `<mat-table>`. 
I cannot center the columns, because of the `mat-sort-header`.

**Comment by lroedal** [comment] 2019-01-13 21:39
I edited the stackblitz to include horizontal scrolling. The thing is, when using flex, it will use the size available. That means, if you want it to 'overflow', you will have to set a specific size for the columns, either in % or px. For the sort headers, you can just offset the table header with the same size that the sort-button and padding occupies.

**Comment by DenisBarzanov** [comment] 2019-01-14 12:21
I really appreciate your StackBlitz example, but why does every example in the documentation use `<table mat-table>` as opposed to `<mat-table>`. Also, you are breaking some styles for the borders and then fixing them manually with CSS. 
For example <a href="https://stackoverflow.com/questions/50630623/angular-mat-table-weird-alignment-with-cells-containing-long-strings">this answer</a> from StackOverflow also says that you should instead use `<mat-table>`. I personally find it really frustrating and confusing. I kind of got it working using the css from your example (the overflow sort of broke my toolbar when the table was , but when I wanted to add sticky headers for instance - I had to do some manual css (which couldn't work out for me) instead of just `sticky: true` and `sticky`, which are available for `<table mat-table>`.
In the end I think that they didn't bother to make it easy, because maybe centering columns is a bad practice and should be avoided. 
Thanks for your time buddy!

**Comment by andrewseguin** [comment] 2019-01-15 22:07
Seems like you may not be centering the sorted headers. One way to do this would be to add this styling:

```css
:host ::ng-deep .mat-sort-header-container {
    display: flex;
    justify-content: center;
}
```

If you need more help, I suggest putting together a full reproduction in Stackblitz that others can help you  debug and style. I'll close this since its not an issue, but more of a troubleshooting question

**Closed by andrewseguin** 2019-01-15 22:07 UTC
