### ISSUE TITLE
input's maxLength=-1 property not works in MS Edge

### ISSUE THREAD

**Issue by davidgabrichidze** [angular/material2#388] opened 2016-05-04 10:07 UTC
When attribute 'maxLength' is removed from input, behavior is corrected.

changing to `@Input() maxLength: number = null;` in input.ts removes attribute.

angular: rc-0;
material2: alpha4;
Edge  version: 25.10

**Comment by sebakerckhof** [comment] 2016-05-11 07:38
Duplicate of https://github.com/angular/material2/issues/336

**Closed** 2016-05-12 00:50 UTC
