### ISSUE TITLE
Multi-line input hint overlaps with elements below

### ISSUE THREAD

**Issue by dobrevad** [angular/material2#6646] opened 2017-08-25 22:59 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Multi-line hint is properly wrapped in the input container. Doesn't overlap with other form fields below it.

#### What is the current behavior?
Multi-line hint is not supported. Overlaps with another input field below the current one.

#### What are the steps to reproduce?
https://plnkr.co/edit/gekgV5ULzXWrZE7VTHv1?p=preview

#### What is the use-case or motivation for changing an existing behavior?
n/a

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular v4.3.6, Material 2.0.0

#### Is there anything else we should know?
no

**Comment by jelbourn** [comment] 2017-08-29 17:26
Duplicate of #5227

**Closed by jelbourn** 2017-08-29 17:26 UTC
