### ISSUE TITLE
Select multiple does not respect ngModel updates

### ISSUE THREAD

**Issue by crutchcorn** [angular/material2#10044] opened 2018-02-20 16:03 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When you update the `ngModel` of a select with `multiple`, it should update the selection

#### What is the current behavior?
When you have a select with an `[(ngModel)]` and `multiple` and update the ngModel outside of the select, the select doesn't update with the correct selection

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-select-multi-bug

#### What is the use-case or motivation for changing an existing behavior?
I have a form that I'd like to dynamically update the selection,

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.5
Material 5.2.1

**Comment by crisbeto** [comment] 2018-02-20 17:42
That's because Angular's change detection compares by reference. When you pop the array, there's no way for the select to know that anything changed. You can work around it either by reassigning the array or setting the value through a `FormControl`, e.g.:

```ts
this.toppings = this.toppings.slice(0, -1);
```

**Closed by crisbeto** 2018-02-20 17:42 UTC

**Comment by Yogeshwar1992** [comment] 2018-07-27 09:55
Hi crisbeto, 

working like charmsssssssssssssssssss 

:)\\

thank you

**Comment by suseecheetah** [comment] 2019-04-24 05:21
> #### Bug, feature request, or proposal:
> Bug
> 
> #### What is the expected behavior?
> When you update the `ngModel` of a select with `multiple`, it should update the selection
> 
> #### What is the current behavior?
> When you have a select with an `[(ngModel)]` and `multiple` and update the ngModel outside of the select, the select doesn't update with the correct selection
> 
> #### What are the steps to reproduce?
> https://stackblitz.com/edit/angular-select-multi-bug
> 
> #### What is the use-case or motivation for changing an existing behavior?
> I have a form that I'd like to dynamically update the selection,
> 
> #### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
> Angular 5.2.5
> Material 5.2.1
> 
> #### Is there anything else we should know?

Steps to reproduce not found in stackblitz
