### ISSUE TITLE
mat-sort-header add noise to mat-cell for accessible users

### ISSUE THREAD

**Issue by sourabhsoni0711** [angular/material2#12784] opened 2018-08-22 04:30 UTC
#### Bug, feature request, or proposal:
Bug: Table header with mat-sort-header add noise "Change sorting" to all individual mat-cell for accessible users when traversing table using screen reader.

#### What is the expected behavior?
Sortable table headers are announced as '<column_name> sorted <sort_direction>'.
Grid cells are announced as '<column_name> <cell_value>'.

#### What is the current behavior?
Sortable table headers are announced as 'Change Sorting for Sorted by <sort_direction>'.
Grid cells are announced as ''Change Sorting for Sorted by <sort_direction> <cell_value>'.

#### What are the steps to reproduce?
https://drive.google.com/file/d/1-fIokzLKDbx15O8PkDF6uzjwHT5f8dZ6/view?usp=sharing
Try screen reader on the sorting demo example: https://material.angular.io/components/table/examples

#### What is the use-case or motivation for changing an existing behavior?
Reducing the cognitive load for screen-reader users.

**Comment by crisbeto** [comment] 2018-10-02 19:16
Closing as a duplicate of https://github.com/angular/material2/issues/13012.

**Closed by crisbeto** 2018-10-02 19:16 UTC
Labels: G, P2, a11y
