### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by jayakrishna-v** [angular/material2#10953] opened 2018-04-23 07:17 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Angular Material and its components to work normal in IE 11

#### What is the current behavior?
Not expected

#### What are the steps to reproduce?
https://material.angular.io/components/categories

#### What is the use-case or motivation for changing an existing behavior?
We would like to know the exact browser compatibility. It is changing day by day.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 1.7.3
Node: 8.9.4
OS: win32 x64
Angular: 5.2.9
typescript: 2.7.2
IE11

#### Is there anything else we should know?
Can you please provide the exact list of complete browser compatibility
![material issue in ie11](https://user-images.githubusercontent.com/34906838/39111873-2910e3c8-46c6-11e8-911f-dc264ec7eaba.png)

**Comment by donroyco** [comment] 2018-04-23 11:36
Duplicate of https://github.com/angular/material.angular.io/issues/391

**Closed** 2018-04-23 17:12 UTC
