### ISSUE TITLE
theming guide URL is broken

### ISSUE THREAD

**Issue by hibumbapartha** [angular/material2#2492] opened 2017-01-02 11:30 UTC
#### What is the expected behavior?
[Include the core and theme styles](https://github.com/angular/material2/blob/master/guides/getting-started.md#include-the-core-and-theme-styles) contains a  link with text 'theming guide' which should take user to a proper 'theming guide' page.

#### What is the current behavior?
This link is now taking user to `https://github.com/angular/material2/blob/master/guides/guides/theming.md` which is a broken link.

#### What are the steps to reproduce?
Click on `theming guide` link.

**Comment by DevVersion** [comment] 2017-01-02 13:26
We already have a PR for it. See #2400. And this issue is a duplicate of #2461

**Closed by DevVersion** 2017-01-02 13:26 UTC
