### ISSUE TITLE
md-select floatPlaceholder="always" not working in all md-tab's

### ISSUE THREAD

**Issue by mpschaeuble** [angular/material2#7070] opened 2017-09-14 11:50 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Placeholder floating behaviour should behave the same in all tabs.

#### What is the current behavior?
If floatPlaceholder is set to "always" on an md-select and the md-select is placed within an md-tab's, the label is only floating in the first tab.

#### What are the steps to reproduce?
https://plnkr.co/edit/q78H0wXLcJws8zeZQXQ7?p=preview

**Comment by djtahl** [comment] 2017-09-14 12:15
I have the same issue, it's really blocking when we have set our providers to `{ provide: MD_PLACEHOLDER_GLOBAL_OPTIONS, useValue: { float: 'always' } }` and we have this behavior in md-tab.
<img width="1572" alt="select_no-float" src="https://user-images.githubusercontent.com/19934211/30429246-0e5e4d44-9957-11e7-9aca-f4de3b8a0d41.png">

**Comment by julianobrasil** [comment] 2017-09-14 14:41
Maybe related to #5269: some animations kind of broke when inside the not visible md-tabs during the initialization. Take a look at this workaround (just hide and reshow the content when the md-tab is selected): https://plnkr.co/edit/RsefE2DZ7cGA2dIACx0m?p=preview

**Comment by mpschaeuble** [comment] 2017-09-20 09:27
Workaround works, but an error is logged "ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'."

**Comment by julianobrasil** [comment] 2017-09-20 09:47
@mpschaeuble, it's annoying and who knows what consequences it could bring in production environment? There's another way, not so elegant, using the **`selectChange`** output: https://plnkr.co/edit/C3WVOERgJQgM9qMW9aVq?p=preview

**Comment by julianobrasil** [comment] 2017-09-20 09:54
@mpschaeuble, @lula suggested another (better) way in https://github.com/angular/material2/issues/5269#issuecomment-326692430, very similar to the one I suggested above, but without throwing the "changed-after-checked" error. I've updated the plunk.

**Comment by josephperrott** [comment] 2017-09-26 22:22
Resolving as duplicate of #5269 as the same underlying issue is the cause.

**Closed by josephperrott** 2017-09-26 22:22 UTC
