### ISSUE TITLE
Getting the paginator with the renderer removes it from the DOM

### ISSUE THREAD

**Issue by trichetriche** [angular/material2#10875] opened 2018-04-16 12:21 UTC
#### Bug, feature request, or proposal:

**Bug**

#### What is the expected behavior?

When I use `Renderer2.selectRootElement('mat-paginator')`, I expect to get the DOM element.

#### What is the current behavior?

The DOM element is fetched, but it is removed from the DOM

#### What are the steps to reproduce?

Stackblitz : https://stackblitz.com/edit/angular-vrovzv?file=app/table-pagination-example.ts

#### What is the use-case or motivation for changing an existing behavior?

In this particular case, I want to access the element to get its CSS properties (because I can't get the nativeElement) to create an action line on the left of the paginator. I would like to get its height and background color.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

````
@angular@5.2.6
@angular/cdk@5.2.3
@angular/cli@1.7.1
@angular/material@5.2.3
typescript@2.4.2

Windows 10 Pro edition
Chrome
````

#### Is there anything else we should know?

I have already opened an issue about that (#10797) but it got closed by a contributor that thought had resolved my issue (but he didn't). Since I am without news, I'm opening a new one to report this issue again.

**Comment by andrewseguin** [comment] 2018-04-23 17:27
Dupe of #10797

**Closed by andrewseguin** 2018-04-23 17:27 UTC

**Comment by trichetriche** [comment] 2018-04-23 18:28
Is this a joke or something ?
