### ISSUE TITLE
FormsModule: untouched text input is not pristine in IE 11

### ISSUE THREAD

**Issue by macjohnny** [angular/material2#3256] opened 2017-02-23 10:55 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When showing a form in IE 11 with an input field, the initial state of the field is not pristine, leading to error messages being shown to the user before he touched the field.

**Expected behavior**
The field state should be pristine until the user first entered and removed some text. This works fine in e.g. Google Chrome

**Minimal reproduction of the problem with instructions**
http://embed.plnkr.co/fm7lH2/
The red error message should only be display when the user entered and removed some text.

**What is the motivation / use case for changing the behavior?**
Form validation errors should only be displayed when a user touched the form.

**Please tell us about your environment:**
Windows 7 / IE 11

* **Angular version:** 2.4.7

* **Browser:** IE 11
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =   v6.3.1

**Comment by macjohnny** [comment] 2017-02-23 10:55
see https://github.com/angular/angular/issues/14667

**Comment by macjohnny** [comment] 2017-02-23 10:56
according to https://github.com/angular/angular/issues/14667#issuecomment-281960545, this is a angular material issue.

**Comment by szykov** [comment] 2017-02-23 12:29
It is definitely a **material** issue. Removing **material** module from imports solves the issue.

**Comment by mmalerba** [comment] 2017-03-02 20:26
Interesting, it does seem to be somehow related to material, though not necessarily `mdInput`. I am able to reproduce by adding this to the input demo page of the material demo app, but putting this by itself in a plunker I do not see the issue:

```html
<input class="demo-dirty-test" ngModel [placeholder]="'placeholder'">
```

I will investigate further.

**Comment by mmalerba** [comment] 2017-03-03 00:41
It looks like the source of this bug is the fact that `MdInputDirective` sets up an `@Input()` on `placeholder` and then re-binds it in the `host`. Ideally this should be fixed in angular core.

Here's an example of this happening with pure angular, no material: http://plnkr.co/edit/cpLxYzEVceJ4MUGiOXi5?p=preview

**Comment by mmalerba** [comment] 2017-03-03 16:12
Will be fixed in core (follow https://github.com/angular/angular/issues/14667), so closing this one

**Closed by mmalerba** 2017-03-03 16:12 UTC
