### ISSUE TITLE
MatTableDataSource should delimit stringified properties with a special character

### ISSUE THREAD

**Issue by JacobBrandt** [angular/material2#12914] opened 2018-08-30 21:16 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The data table filter should filter on the individual value of cells of a row

#### What is the current behavior?
The data table filters on the combined value of all cells in a row

#### What are the steps to reproduce?
StackBlitz: https://stackblitz.com/edit/angular-prsrvj

#### What is the use-case or motivation for changing an existing behavior?
Given the provided StackBlitz I would expect when searching for "test" that I only get one row back.  However both are shown because the cell values are combined together without spacing.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by JacobBrandt** [comment] 2018-09-06 00:09
@manklu I know that I can provide my own filter function, I'm saying the default is really bizarre.

**Comment by josephperrott** [comment] 2018-09-07 13:58
Closing as this is working as intended.  To change from this default filtering function, you will need to provide your own function.

**Comment by JacobBrandt** [comment] 2018-09-07 15:31
Just because documentation says the default combines all values into one string doesn't mean its a good solution.  I was saying that a better solution is possible.
I read the read me and saw this:

> 
> What do we mean by "high-quality"?
> Behave as expected across a wide variety of use-cases without bugs.

I don't think this default filtering behaves as expected.

**Comment by JacobBrandt** [comment] 2018-09-07 17:56
Here is another example.  https://stackblitz.com/edit/angular-prsrvj-2nhdev.  I just reversed the column data from row 2 on the last row.


So are you saying that users should expect that when they enter test that the` Flute | Stop` row shows up but not the `Stop | Flute` row?  I'm not sure why this doesn't demonstrate unexpected behavior.

**Comment by JacobBrandt** [comment] 2018-09-08 00:18
@josephperrott Can you provide some clarification then.  It's not an obvious behavior so doesn't that go against the phrase "behave as expected".  When the teams says behave as expected do you guys really mean that it should do only what's documented?

**Comment by jelbourn** [comment] 2018-10-04 22:41
Thanks @JacobBrandt, the current behavior is indeed incorrect. There should be a delimiter here:
https://github.com/angular/material2/blob/0a25fca2d7457eafa923e24c54af779611e2560b/src/lib/table/table-data-source.ts#L177

The fix would be to just add a special character as a delimiter (something that wouldn't normally be typed) and a corresponding unit test.

**Comment by JacobBrandt** [comment] 2018-10-05 00:59
Thanks for reopening.  What delimiter do you have in mind that would work in all cases?

**Comment by StephenWTurner** [comment] 2018-10-12 07:31
Rather than a "weird unicode character" how about a specific non-printable character that is in the character set solely for the purposes of delimiting text? i.e.  '\037' 

https://en.wikipedia.org/wiki/Delimiter#ASCII_delimited_text

**Closed** 2018-10-19 15:08 UTC
Labels: P3, has pr, help wanted
