### ISSUE TITLE
md-dialog: pass additional content

### ISSUE THREAD

**Issue by ciesielskico** [angular/material2#2707] opened 2017-01-18 17:08 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
I would like to pass a string to the dialog when opening it with `this.dialog.open(...)` to be displayed in the dialog itself.

#### What is the current behavior?
I can't pass additional data directly to the dialog.

#### What is the use-case or motivation for changing an existing behavior?
I can pass data using an additional service, but that seems overkill when I just want to pass a string. 

Currently, you can set options for the dialog, it would be nice to have a `data` field in there to pass additional content along.

**Comment by codef0rmer** [comment] 2017-01-19 08:29
@ciesielskico You should grab the componentInstance to pass data in:

```
let dialogRef = this.dialog.open(MyComponent);
dialogRef.componentInstance['myProperty'] = "Value"
```

**Comment by ciesielskico** [comment] 2017-01-21 12:03
Looks hacky but I'll try this, thanks. Still I think there should be a more elegant and straightforward way to do the same.

**Comment by crisbeto** [comment] 2017-01-21 13:17
Closing as a duplicate of #2181 which has a pending PR.

**Closed by crisbeto** 2017-01-21 13:17 UTC
