### ISSUE TITLE
Table doesn't render new rows if passed trackBy and when predicate

### ISSUE THREAD

**Issue by clundberg1** [angular/material2#15771] opened 2019-04-09 19:47 UTC
#### What is the expected behavior?
Table should render new rows when the dataSource changes, whilst also making intelligent updates with trackBy function.

#### What is the current behavior?
The table initially renders correctly, but if the dataSource changes and a new item's been added, the table doesn't render a new row for it, if also making use of the when predicate.

#### What are the steps to reproduce?
```
<table mat-table [dataSource]="dataSource" multiTemplateDataRows [trackBy]="trackBy">
...
    <tr [class.expanded]="expandedEntity == row" class="grouped-row-header"
            *matRowDef="let row; columns: ['group']; when: shouldRenderTypeRow" mat-row></tr>
    <tr *matRowDef="let row; columns: columnsToDisplay; when: shouldRenderDocumentationRow" mat-row></tr>
    <tr [class.is-last-of-same-group]="isLastRowOfSameGroup(i)" class="grouped-row-body"
            [hidden]="shouldHideDocumentationRow(row)"
            *matRowDef="let row; columns: columnsToDisplay; when: shouldRenderNestedDocumentationRow;"
            mat-row></tr>
</table>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.2.3
Node: 8.10.0
OS: win32 x64
Angular: 7.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.12.3
@angular-devkit/build-angular      0.12.3
@angular-devkit/build-optimizer    0.12.3
@angular-devkit/build-webpack      0.12.3
@angular-devkit/core               7.2.3
@angular-devkit/schematics         7.2.3
@angular/cdk                       7.3.0
@angular/cli                       7.2.3
@angular/flex-layout               7.0.0-beta.23
@angular/material                  7.3.0
@angular/material-moment-adapter   7.3.1
@ngtools/webpack                   7.2.3
@schematics/angular                7.2.3
@schematics/update                 0.12.3
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.28.4

**Comment by andrewseguin** [comment] 2019-04-09 20:08
Duplicate of #9527

**Closed by andrewseguin** 2019-04-09 20:08 UTC
