### ISSUE TITLE
CDK Drag and Drop not working perfectly in multiple rows

### ISSUE THREAD

**Issue by Shankar1430** [angular/material2#15549] opened 2019-03-20 11:59 UTC
#### What is the expected behavior?
Drag is not working perfectly when items has wrapped.

#### What is the current behavior?
Drag and drop should work perfectly when items are to be wrapped.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7, 7, linux

#### Is there anything else we should know?
No

**Comment by crisbeto** [comment] 2019-03-20 19:05
Duplicate of https://github.com/angular/material2/issues/13372.

**Closed by crisbeto** 2019-03-20 19:05 UTC
