### ISSUE TITLE
dialog opened with TemplateRef that contains ng-content is not cleaned up properly on close, causing stacking issues

### ISSUE THREAD

**Issue by fxck** [angular/material2#3574] opened 2017-03-13 13:02 UTC
See https://gist.run/?id=f3741ab47081095d12931e25acb6ce80

1. open dialog
2. select something in autocomplete (optional)
3. close dialog
4. open again
5. click on autocomplete

![image](https://cloud.githubusercontent.com/assets/1303561/23855304/76492a12-07f5-11e7-9211-8682e29e9a45.png)

This stays in dom after closing the dialog for the first time

![image](https://cloud.githubusercontent.com/assets/1303561/23855325/8c02cdc2-07f5-11e7-9394-c04f96484aab.png)

causing stacking issues the next time it is opened

@crisbeto @jelbourn

**Comment by crisbeto** [comment] 2017-03-13 13:16
I tried looking into this a while ago and the issue is that a TemplateRef can't be associated with an injector. In the case of the close button we can fall back to closing the top dialog, but we probably need a better way of exposing the dialog.

**Closed** 2017-03-27 23:37 UTC
Labels: has pr
