### ISSUE TITLE
Table displays Transition 'T' by Default

### ISSUE THREAD

**Issue by SSCGPAlexPayne** [angular/material2#11370] opened 2018-05-16 20:08 UTC
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?
Table should not show the transition 'T' on load.

![image](https://user-images.githubusercontent.com/35273364/40140955-dc0dc63e-5919-11e8-8846-d644ecc18059.png)

#### What is the current behavior?

When Using a Table in a Tab the following occurs:

![image](https://user-images.githubusercontent.com/35273364/40140928-c3dab8f6-5919-11e8-8aed-6b731301ed85.png)

Hovering over the table header cell will remove the 'T' and they will stay removed until reload.
Lazy Loading each Tab is the only work around found for this issue.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-ruwgmh

In the stack blitz I have two tabs, one with a Table. Without lazy loading, i.e. the workaround, the table  will display with the undesired content.

#### What is the use-case or motivation for changing an existing behavior?

This is a minor bug, more of a polish concern it does make the Table a bit more confusing for the user.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

![image](https://user-images.githubusercontent.com/35273364/40141074-4c05cb6c-591a-11e8-972c-bcaf94ccbe4a.png)

**Comment by benb7760** [comment] 2018-05-16 20:10
Probably duplicate of #10088

**Closed** 2018-05-21 15:42 UTC
