### ISSUE TITLE
[Tabs] Nav bar doesn't show arrows when needed like <mat-tab-group> and stack lines of tabs

### ISSUE THREAD

**Issue by jeremyputeaux** [angular/material2#8795] opened 2017-12-04 14:20 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I'm expecting `mat-tab-nav-bar` and `<mat-tab-group>` to have the same behavior (keeping tabs inline and adding arrows when required).
`<mat-tab-group>` currently show arrows and keep tabs inline 
(visible in https://stackblitz.com/angular/jbnxpmvmvyg)

`mat-tab-nav-bar` keep them inline but stack lines instead of showing arrows.

#### What are the steps to reproduce?
1st time I make a stackblitz. I hope it works.
https://stackblitz.com/edit/mat-tab-nav-bar-not-showing-arrows

**Comment by ThomasLohmann** [comment] 2018-01-22 10:49
Hi jeremyputeaux, have you found any solution for this problem?

**Comment by aaronte** [comment] 2018-01-22 14:25
+1

**Comment by jeremyputeaux** [comment] 2018-01-22 14:30
Hi. I did not find any solution as my app is not in production yet. It's not urgent on my side. But It will be in few weeks. I hope It will be fixed by this time.

**Comment by ThomasLohmann** [comment] 2018-01-22 14:37
Let's hope that they will fix it. Tabs are one of the most elementary things in modern apps. I tried also this tabs out: https://trimox.github.io/angular-mdc-web/#/tab-demo

but it is also not perfect, especially for mobile view (swipable tabs are needed, without that arrow stuff).

**Comment by andrewseguin** [comment] 2018-01-23 23:27
Dupe of #2177

**Closed by andrewseguin** 2018-01-23 23:27 UTC
