### ISSUE TITLE
Mat-buttons that open dialogs regain ripple-color after dialog is closed

### ISSUE THREAD

**Issue by jspieker** [angular/material2#8711] opened 2017-11-29 13:19 UTC
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

After the dialog is closed, the button should not regain the (hover|ripple?) effect.

#### What is the current behavior?

I have some mat-buttons that open mat-dialogs. After the dialog is closed (either by submitting or dismissing) the buttons' ripple effect is shown until a different part of the page is clicked. 

#### What are the steps to reproduce?
The bug is visible in the [dialog example](https://material.angular.io/components/dialog/examples). Click the _Pick One_-Button to open the dialog and dismiss it. The _Pick One_-Button now has the grey overlay instead of reverting to its original color. Clicking anywhere else on the page will fix the issue.

#### What is the use-case or motivation for changing an existing behavior?
The buttons should regain their original color.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular ^5.0.0
Material ^5.0.0-rc0
OS: Linux Mint 18 & macOS High Sierra
TypeScript: ~2.6.1
Browser: 62.0.3202.94 (Official Build) (64-bit)
Firefox: 57.0 (64-bit)

**Comment by DevVersion** [comment] 2017-11-29 16:12
Duplicate of #8420

**Closed by DevVersion** 2017-11-29 16:12 UTC
