### ISSUE TITLE
mat-select does not update its value when the language is switched 

### ISSUE THREAD

**Issue by axmad22** [angular/material2#7938] opened 2017-10-21 01:45 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When the  mat-select is populated  with an array of  complex objects, and the language is switched it should update to the new values,  like how a select option would do

#### What is the current behavior?
When selected language is switch  the mat-select does not update its selected values until it clicked on

#### What are the steps to reproduce?
Using this array of objects in the view and when switching language the bug is produced
````JavaScript
  const genderList = [
      {id: 1, name: {gr: 'agory', en: 'Male'}},
      {id: 2, name: {gr: 'koritsi', en: 'Female'}}
  ];

// 'App.lang' is a string that switches from gr to en  
  <mat-form-field>
    <mat-select placeholder="Gender" [formControl]="gender">
      <mat-option *ngFor="let gender of genderList" [value]="gender.id">
        {{ gender.name['App.lang' | translate] }}
      </mat-option>
    </mat-select>
  </mat-form-field>
````

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular:  4.2.4
@angular/material:  2.0.0-beta.12

**Comment by Almar** [comment] 2017-10-22 00:38
This might be caused by the same issue as described in #7923.

**Comment by josephperrott** [comment] 2017-11-07 17:17
Closing as duplicate of #7923

**Closed by josephperrott** 2017-11-07 17:17 UTC
