### ISSUE TITLE
Drag and drop support in mat-grid-list

### ISSUE THREAD

**Issue by ducalai** [angular/material2#13878] opened 2018-10-30 14:44 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Fully support drag and drop functionalities in mat-grid-list. As annonced on blog https://blog.angular.io/version-7-of-angular-cli-prompts-virtual-scroll-drag-and-drop-and-more-c594e22e7b8c and illustrated with 
![image](https://user-images.githubusercontent.com/13022458/47726342-946ae180-dc5a-11e8-8512-be28bfa50ba5.png)

#### What is the current behavior?
cdkDropList supports vertical (default) or horizontal sorting orientation, but not both at the same time.

#### What are the steps to reproduce?
Examples provided on https://material.angular.io/cdk/drag-drop/examples show vertical or horizontal items sorting in list, but not both at the same time

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7, Angular Material 7

Maybe the key is not to use mat-grid-list component? Any ideas?

Thanks for your help
Alain

**Comment by josephperrott** [comment] 2018-10-30 20:40
Closing as duplicate of #13372

**Closed by josephperrott** 2018-10-30 20:40 UTC
