### ISSUE TITLE
Expansion panels opened method is get called for all panels in accordian

### ISSUE THREAD

**Issue by HemaVSitaram** [angular/material2#12482] opened 2018-08-02 09:00 UTC
#### Bug:
This is a bug in accordian, where multiple expansion panels are getting emitted for a click on one expansion panel.

#### What is the expected behavior?
It is supposed to emit opened method for only the selected panel. Not all the opened emits

#### What is the current behavior?
It is getting emitted for multiple expansion panels.

#### What are the steps to reproduce?
Code Snippet
`<mat-accordion *ngFor="let module of modules; let mi = index;">
      <mat-expansion-panel [expanded]="miStep === mi" 
        (opened)="openModulePanel(module.type, lang.code, mi)" hideToggle>
        <mat-expansion-panel-header>
          <mat-panel-title>
            {{ module?.metaData?.displayName }}
          </mat-panel-title>
        </mat-panel-title>
     </mat-expansion-panel-header>
   </mat-expansion-panel>
</mat-accordion>`

#### What is the use-case or motivation for changing an existing behavior?
Difficult to handle child panels

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.2.8
material: 5.2.5
Typescript: 2.4.2

#### Is there anything else we should know?
No

**Comment by josephperrott** [comment] 2018-08-02 21:35
Can you provide a reproduction of the issue you are seeing?  I was not able to reproduce what you described as you can see in this [stackblitz](https://stackblitz.com/edit/angular-material2-issue-rctuaf?file=app%2Fapp.component.html).

Please provide a stackblitz reproduction to be able to investigate the issue.

**Comment by HemaVSitaram** [comment] 2018-08-03 07:57
hey @josephperrott ,
i can see version mismatch. load the code in provided versions. Updated the code a bit as well.

`import {
  Component, ElementRef
} from '@angular/core';
import { VERSION } from '@angular/material';

@Component({
  selector: 'material-app',
  templateUrl: 'app.component.html'
})
export class AppComponent {
  version = VERSION;
  panels = [0, 1, 2];
  childPanels = [11,22,33]
  selectedPanel = 1;

  onPanelOpen(x: number) {
    console.log(this.version);
    console.log(`Panel ${x} opened. ${this}`);
  }

   onChildPanelOpen(x: number, y: number) {
    console.log(`Panel ${x} opened, Child Panel ${y} opened.`);
  }
}
`

`<mat-accordion>
	<mat-expansion-panel *ngFor="let panel of panels; let i = index;" (opened)="onPanelOpen(i)">
		<mat-expansion-panel-header>
			<mat-panel-title> {{ panel }} </mat-panel-title>
		</mat-expansion-panel-header>
		<p> Panel number {{panel}} content</p>
		<mat-accordion>
			<mat-expansion-panel *ngFor="let childPanel of childPanels; let j = index;" [expanded]="selectedPanel === j" (opened)="onChildPanelOpen(i, j)">
				<mat-expansion-panel-header>
					<mat-panel-title> {{ childPanel }} </mat-panel-title>
				</mat-expansion-panel-header>
				<p> childPanel number {{childPanel}} content</p>
			</mat-expansion-panel>
		</mat-accordion>
	</mat-expansion-panel>
</mat-accordion>`

**Comment by josephperrott** [comment] 2018-08-03 14:18
I updated the [stackblitz](https://stackblitz.com/edit/angular-material2-issue-rctuaf?file=app%2Fapp.component.ts) with the changes and versions you mentioned, but it still appears that the application works as expected.

**Comment by josephperrott** [comment] 2018-09-10 22:19
Closing as we are not be able to reproduce this issue.

**Closed by josephperrott** 2018-09-10 22:19 UTC
Labels: cannot reproduce
