### ISSUE TITLE
Can't bind to 'matMenuTriggerFor' since it isn't a known property of 'button'. ("">

### ISSUE THREAD

**Issue by JSilva94** [angular/material2#7301] opened 2017-09-25 18:12 UTC
#### Bug, feature request, or proposal:
this is for beta11

#### What is the expected behavior?
should bind submenu to button

#### What is the current behavior?
does not do that

#### What are the steps to reproduce?
try to bind [matMenuTriggerFor]="someSubMenu"

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material beta 11

**Comment by josephperrott** [comment] 2017-09-25 18:16
Can you provide a reproduction of the issue?

Based on the error you are receiving it appears that you are not importing `MatMenuModule`

**Comment by crisbeto** [comment] 2017-09-25 18:21
It looks like you could be on an older Angular version. Can you update to 4.4.3?

**Comment by JSilva94** [comment] 2017-09-25 19:32
I did it fixed the error!

However, now it does not like 

import {MatSnackbar} from '@angular/material'

suggestions?

**Comment by crisbeto** [comment] 2017-09-25 19:34
What error are you getting?

**Comment by JSilva94** [comment] 2017-09-25 19:36
Module '"path/to/node_modules/@angular/material/material"' has no exported member 'MatSnackBar'.

**Comment by crisbeto** [comment] 2017-09-25 19:40
You should be able to import `MdSnackBar`.

**Comment by JSilva94** [comment] 2017-09-25 19:41
I thought it was called MatSnackBar with the prefix changes

**Comment by crisbeto** [comment] 2017-09-25 19:43
We're still in the process of renaming a lot of things. See https://github.com/angular/material2/pull/7241.

**Comment by JSilva94** [comment] 2017-09-25 19:44
So for the time being, should I be using MdSnackBar?

**Comment by crisbeto** [comment] 2017-09-25 19:46
Yes, it is a little confusing but it will be sorted out by the time we hit stable. Your IDEs autocompletion should be able to give you the proper import names.

**Comment by JSilva94** [comment] 2017-09-25 19:46
Okay, is MdSnackBar now considered a service?

**Comment by JSilva94** [comment] 2017-09-25 19:50
I dont understand why an npm package is provided that renames everything to Mat from Md, however this is not stable. This may ruin alot of peoples code.

**Comment by axtho** [comment] 2017-09-26 08:44
It does ruin a lot of code. I also though that the tool would grab what is changeable, but it seems that it converted too much (i have similar issues with Modules like mat-option not liking [value] and styles being completely off). There should be a warning about using this service.

**Comment by josephperrott** [comment] 2017-09-26 16:44
Closing as the issue was resolved by updating to `@angular/angular@4.4.3`

**Closed by josephperrott** 2017-09-26 16:44 UTC
Labels: cannot reproduce

**Comment by bibekananda-pradhan** [comment] 2018-04-24 10:01
getting the same issue, please help me.

**Comment by Gavintek** [comment] 2018-05-10 15:30
Facing same issue with newer versions of material and angular. I only face the issue running the test specs. I will upgrade these to see if it still occurs.

>     "@angular/animations": "^5.2.4",
>     "@angular/cdk": "^5.2.1",
>     "@angular/common": "^5.2.4",
>     "@angular/compiler": "^5.2.4",
>     "@angular/core": "^5.2.4",
>     "@angular/forms": "^5.2.4",
>     "@angular/http": "^5.2.4",
>     "@angular/material": "^5.2.1",
>     "@angular/platform-browser": "^5.2.4",
>     "@angular/platform-browser-dynamic": "^5.2.4",
>     "@angular/router": "^5.2.4",

**Comment by DougReynolds** [comment] 2018-06-01 23:07
I am experiencing the same as @Gavintek.
`Angular CLI: 6.0.7
Node: 10.1.0
OS: darwin x64
Angular: 6.0.3
`
`@angular-devkit/architect         0.6.7
@angular-devkit/build-angular     0.6.7
@angular-devkit/build-optimizer   0.6.7
@angular-devkit/core              0.6.7
@angular-devkit/schematics        0.6.7
@angular/cdk                      6.2.0
@angular/cli                      6.0.7
@angular/material                 6.2.0
@ngtools/webpack                  6.0.7
@schematics/angular               0.6.7
@schematics/update                0.6.7
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3`

Test Spec:

`import { TestBed, async } from '@angular/core/testing';
import { AppComponent } from './app.component';
import { ToolmenuComponent } from './toolmenu/toolmenu.component';
import { ToolboxComponent } from './toolbox/toolbox.component';

describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent,
        ToolmenuComponent,
        ToolboxComponent
      ],
    }).compileComponents();
  }));
  it('should create the app', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  }));
 .....
});`

Implementation:
`<button class="tool-menu" mat-button [matMenuTriggerFor]="imageMenu">Image Tools</button>`

Karma Stack:

> Can't bind to 'matMenuTriggerFor' since it isn't a known property of 'button'. ("<div class="menu-bar">
  <button class="tool-menu" mat-button [ERROR ->][matMenuTriggerFor]="imageMenu">Image Tools</button>
  <mat-menu #imageMenu="matMenu" [overlapTrigger"): ng:///DynamicTestModule/ToolmenuComponent.html@1:39
There is no directive with "exportAs" set to "matMenu" ("utton class="tool-menu" mat-button [matMenuTriggerFor]="imageMenu">Image Tools</button>
  <mat-menu [ERROR ->]#imageMenu="matMenu" [overlapTrigger]="false">
    <button mat-menu-item>Item 1</button>
    <button "): ng:///DynamicTestModule/ToolmenuComponent.html@2:12
Can't bind to 'overlapTrigger' since it isn't a known property of 'mat-menu'.
1. If 'mat-menu' is an Angular component and it has 'overlapTrigger' input, then verify that it is part of this module.
2. If 'mat-menu' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("u" mat-button [matMenuTriggerFor]="imageMenu">Image Tools</button>
  <mat-menu #imageMenu="matMenu" [ERROR ->][overlapTrigger]="false">
    <button mat-menu-item>Item 1</button>
    <button mat-menu-item>Item 2<"): ng:///DynamicTestModule/ToolmenuComponent.html@2:33
'mat-menu' is not a known element:
1. If 'mat-menu' is an Angular component, then verify that it is part of this module.
2. If 'mat-menu' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("bar">
  <button class="tool-menu" mat-button [matMenuTriggerFor]="imageMenu">Image Tools</button>
  [ERROR ->]<mat-menu #imageMenu="matMenu" [overlapTrigger]="false">
    <button mat-menu-item>Item 1</button>
  "): ng:///DynamicTestModule/ToolmenuComponent.html@2:2
Can't bind to 'matMenuTriggerFor' since it isn't a known property of 'button'. ("
    <button mat-menu-item>Item 2</button>
  </mat-menu>
  <button class="tool-menu" mat-button [ERROR ->][matMenuTriggerFor]="svgMenu">SVG Tools</button>
  <mat-menu #svgMenu="matMenu" [overlapTrigger]="fal"): ng:///DynamicTestModule/ToolmenuComponent.html@6:39
There is no directive with "exportAs" set to "matMenu" ("  <button class="tool-menu" mat-button [matMenuTriggerFor]="svgMenu">SVG Tools</button>
  <mat-menu [ERROR ->]#svgMenu="matMenu" [overlapTrigger]="false">
    <button mat-menu-item>Item 1</button>
    <button ma"): ng:///DynamicTestModule/ToolmenuComponent.html@7:12
Can't bind to 'overlapTrigger' since it isn't a known property of 'mat-menu'.
1. If 'mat-menu' is an Angular component and it has 'overlapTrigger' input, then verify that it is part of this module.
2. If 'mat-menu' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("ol-menu" mat-button [matMenuTriggerFor]="svgMenu">SVG Tools</button>
  <mat-menu #svgMenu="matMenu" [ERROR ->][overlapTrigger]="false">
    <button mat-menu-item>Item 1</button>
    <button mat-menu-item>Item 2<"): ng:///DynamicTestModule/ToolmenuComponent.html@7:31
'mat-menu' is not a known element:
1. If 'mat-menu' is an Angular component, then verify that it is part of this module.
2. If 'mat-menu' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("mat-menu>
  <button class="tool-menu" mat-button [matMenuTriggerFor]="svgMenu">SVG Tools</button>
  [ERROR ->]<mat-menu #svgMenu="matMenu" [overlapTrigger]="false">
    <button mat-menu-item>Item 1</button>
    "): ng:///DynamicTestModule/ToolmenuComponent.html@7:2
    at syntaxError (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/fesm5/compiler.js:215:1)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/fesm5/compiler.js:14702:1)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/fesm5/compiler.js:22709:1)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/fesm5/compiler.js:22696:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/fesm5/compiler.js:22639:48
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/fesm5/compiler.js:22639:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/fesm5/compiler.js:22557:1
    at Object.then (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/fesm5/compiler.js:206:33)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/fesm5/compiler.js:22555:1)

**Comment by DougReynolds** [comment] 2018-06-04 16:57
It is not sufficient to add the imports to the application module, alone.  To fix this issue, add imports into any component spec beforeEach that is using the material as well.  e.g:

mycomponent.spec.ts
`imports: [ // Anything that uses the Materials lib needs to import in order to test
        MatMenuModule,
        MatIconModule,
        MatButtonModule
      ]`
In this case i am using Menu, Icon, and Buttons

**Comment by rageycomma** [comment] 2018-07-23 09:17
Thanks @DougReynolds  - this works, however, it'd maybe be a bit better to update the documentation section for the API to show that more than 1 module is required for this? 

At the moment I've had to do the same thing with other components, but it's just trial and error at this point. Everything else has worked perfectly :) <3

**Comment by JarekSour** [comment] 2018-09-02 22:29
Same problem with angular v6.1.6, i have MatMenuModule, MatIconModule, MatButtonModule and MatSnackBarModule

**Comment by fabiomilheiro** [comment] 2018-09-26 10:27
@JarekSour , how did you solve it?

**Comment by fabiomilheiro** [comment] 2018-09-26 10:31
Well:
`import { BrowserAnimationsModule, NoopAnimationsModule } from '@angular/platform-browser/animations';`

in the app.module.ts.

**Comment by btxtiger** [comment] 2019-04-10 21:49
` import { MatMenuModule} from '@angular/material';`
