### ISSUE TITLE
Datepicker Pop-up Doesn't Close when Overlay Background is Clicked

### ISSUE THREAD

**Issue by doctorhilarius** [angular/material2#5118] opened 2017-06-13 21:08 UTC
#### Bug, feature request, or proposal:

When using the touchUi feature of the datepicker, the overlay should close when the overlay background is clicked.

#### What is the current behavior?

Clicking outside the overlay removes the background but does not close the overlay. After the background is removed, clicking any button on the overlay closes the overlay instead of performing the button's action.

#### What is the expected behavior?

Clicking outside the overlay should close the overlay. The overlay should not close unless a date is selected or someone clicks outside the overlay.

#### What is the use-case or motivation for changing an existing behavior?

Improve usability

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular: 4.2.0
Material: 2.0.0-beta.6

#### Is there anything else we should know?

Adding the click listener to the Component's host property provides the correct behavior, even though no action is actually taken when the event occurs:

```
@Component({
   ...
   host: {
        '(document:click)': 'onClick()',
    }
})
export class MyComponent {
   ...
   private onClick(): void { }
}
```

**Comment by willshowell** [comment] 2017-06-14 03:10
Reproduction? It seems to be working fine here https://plnkr.co/edit/1FUa9Lv8Xmm38eVzPCX6?p=preview for Chrome, Safari, FF

**Comment by willshowell** [comment] 2017-06-14 14:02
Nevermind, I am occasionally seeing this too. Working on reproducing

**Comment by doctorhilarius** [comment] 2017-06-14 15:16
Ah--yes, you're correct. The issue only appears when the parent component uses OnPush. Thanks!

**Comment by z639** [comment] 2017-06-19 11:20
You likely already know (as it probably uses the same resource), but it seems the same is true for MdDialog.

**Comment by mmalerba** [comment] 2017-07-18 17:22
@crisbeto I assume this will be addressed by #5422?

**Comment by crisbeto** [comment] 2017-07-18 17:27
It could be @mmalerba, but I'm not completely sure. We can revisit this one after #5422 gets in.

**Comment by mmalerba** [comment] 2017-07-25 15:55
@crisbeto Actually I think this might be unrelated. Seems to be because the datepicker is explicitly setting the `viewContainerRef` rather than allowing the dialog to decide it. I'll create a PR

**Closed** 2017-07-27 16:43 UTC
Labels: has pr, P3: important
