### ISSUE TITLE
'ng add @angular/material@7.0.0-rc.0'  cannot find module

### ISSUE THREAD

**Issue by kuncevic** [angular/material2#13438] opened 2018-10-05 00:57 UTC
#### Bug, feature request, or proposal:
When trying to add the latest material via schematics `ng add @angular/material@7.0.0-rc.0` to the angular 7 project getting an error

#### What is the expected behavior?
No errors

#### What is the current behavior?
```
Cannot find module 'd:\Projects\2018\NEW\node_modules\@angular\material\schematics\ng-add\index'
Error: Cannot find module 'd:\Projects\2018\NEW\node_modules\@angular\material\schematics\ng-add\index'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at new ExportStringRef (d:\Projects\2018\NEW\node_modules\@angular-devkit\schematics\tools\export-ref.js:15:32)
    at NodeModulesEngineHost._resolveReferenceString (d:\Projects\2018\NEW\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:94:21)
    at NodeModulesEngineHost.createSchematicDescription (d:\Projects\2018\NEW\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:172:34)
    at SchematicEngine.createSchematic (d:\Projects\2018\NEW\node_modules\@angular-devkit\schematics\src\engine\engine.js:219:38)
    at CollectionImpl.createSchematic (d:\Projects\2018\NEW\node_modules\@angular-devkit\schematics\src\engine\engine.js:69:29)
    at AddCommand.getSchematic (d:\Projects\2018\NEW\node_modules\@angular\cli\models\schematic-command.js:130:27)
    at AddCommand.runSchematic (d:\Projects\2018\NEW\node_modules\@angular\cli\models\schematic-command.js:262:32)
    at AddCommand.run (d:\Projects\2018\NEW\node_modules\@angular\cli\commands\add-impl.js:48:31)
```

#### What are the steps to reproduce?
```
npm install @angular/cli@7.0.0-rc.1 -g
ng new porjectName --style scss --routing
ng add @angular/material@7.0.0-rc.0
```

**Comment by jelbourn** [comment] 2018-10-05 01:12
Duplicate of #13407

**Closed by jelbourn** 2018-10-05 01:12 UTC

**Comment by kuncevic** [comment] 2018-10-05 01:15
@jelbourn are you pushing the new version soon?
