### ISSUE TITLE
Error building Demo App

### ISSUE THREAD

**Issue by jagomf** [angular/material2#6564] opened 2017-08-20 17:02 UTC
Error when running `npm run demo-app`:

```
Starting 'build:devapp'...
Starting 'material:clean-build'...
Starting 'clean'...
Finished 'clean' after 37 ms
Starting 'material:build'...
Starting 'cdk:build'...
Starting 'cdk:build:esm'...
Starting 'cdk:assets:scss'...
Starting 'cdk:assets:copy-styles'...
Starting 'cdk:assets:html'...
'cdk:build:esm' errored after 2.47 s
TypeError: Cannot read property 'toString' of null
    at \material2-angular\tools\package-tools\secondary-entry-points.ts:42:13
    at Array.forEach (native)
    at Object.getSecondaryEntryPointsForPackage (\material2-angular\tools\package-tools\secondary-entry-points.ts:38:14)
    at BuildPackage.get [as secondaryEntryPoints] (\material2-angular\tools\package-tools\build-package.ts:36:36)
    at BuildPackage.<anonymous> (\material2-angular\tools\package-tools\build-package.ts:59:34)
    at step (\material2-angular\tools\package-tools\build-package.ts:32:23)
    at Object.next (\material2-angular\tools\package-tools\build-package.ts:13:53)
    at fulfilled (\material2-angular\tools\package-tools\build-package.ts:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Expected behavior, as it was happening until a couple or two of weeks was to be able to launch demo app on port 4200 correctly.

Current environment is Node v7.10.1 and NPM v4.2.0, but it seems to be happening as well in prior NPM v3.x versions.

OS: Windows 10 x64

**Comment by crisbeto** [comment] 2017-08-21 06:24
Closing as a duplicate of https://github.com/angular/material2/issues/6438.

**Closed by crisbeto** 2017-08-21 06:24 UTC
