### ISSUE TITLE
Prefixed Form-Field-Outline-Label-Gap not positioned correctly in Mat-Dialog in 7.0.1

### ISSUE THREAD

**Issue by OlufemiOyewole** [angular/material2#13769] opened 2018-10-23 12:07 UTC
#### Bug:
Form-Field-Outline-Label-Gap does not reposition correctly when it is opened in a dialog and the Form-Field has a prefix
<img width="392" alt="screenshot 2018-10-23 at 11 30 50 am" src="https://user-images.githubusercontent.com/17495353/47357899-a4614f00-d6b7-11e8-97c8-fb5953754e32.png">

#### What is the expected behavior?
The Form-Field-Outline-Label-Gap should be positioned correctly with or without a prefix.

#### What is the current behavior?
The Form-Field-Outline-Label-Gap does not reposition itself away from the form field prefix like the label does when it is opened in a dialog.

#### What are the steps to reproduce?
https://stackblitz.com/edit/form-field-outline-label-gap-position-error-in-dialog-701

#### What is the use-case or motivation for changing an existing behavior?
(not applicable)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.0.0
Angular Material 7.0.1
Chrome  69, Safari 12.0

#### Is there anything else we should know?
This seems related to #12782

**Comment by aeslinger0** [comment] 2018-10-23 16:45
I don't think mat-dialog has anything to do with it. You can reproduce it by taking the [demo](https://stackblitz.com/angular/mgnlbdkgqaa?file=app%2Fform-field-prefix-suffix-example.html) and just changing the form fields to use `appearance="outline"`

**Comment by OlufemiOyewole** [comment] 2018-10-24 01:50
@aeslinger0 , I am referring to the gap in the field outline that is for the mat-label when it is raised.

I believe that you are referring to the prefix/suffix not being aligned to the input characters.
For that, I found this issue #11831 that already addresses it.

**Comment by aeslinger0** [comment] 2018-10-24 01:58
Yes, you're right. My mistake.

**Comment by josephperrott** [comment] 2018-11-26 15:51
Closing as duplicate of #11831

**Closed by josephperrott** 2018-11-26 15:51 UTC

**Comment by OlufemiOyewole** [comment] 2018-11-30 21:21
@josephperrott , this is not a duplicate of 11831.

11831 is about vertical alignment of **characters** inside the field.
This is about the horizontal repositioning of the **outline gap** not taking effect in a one off scenario.

Please take a second look at the issue and consider reopening it.

**Comment by hanyu-natsu** [comment] 2019-01-02 16:37
This issue is still there in 7.2.0

To be clear, this happens when ouline gap is calculated before the label and container rendering being stable. I tried pausing the "updateOutlineGap" function when open the dialog and release it after all components are rendered, then the gap is correct.

Please reopen this issue.

**Comment by mohsini172** [comment] 2019-02-15 05:18
It's still an issue on 7.3.1.

**Comment by njsent** [comment] 2019-05-29 05:54
This occurs in any scenario using matPrefix - not just mat-dialog.  

![image](https://user-images.githubusercontent.com/8079162/58532586-afc7ac00-81ab-11e9-9665-3e3189488c0f.png)

`<mat-form-field appearance="outline" fxFlex>
              <mat-label>User Name</mat-label>
              <mat-icon matPrefix>account_box</mat-icon>
              <input matInput formControlName="userName" maxlength="50" required>
              <mat-error>User Name is required</mat-error>
            </mat-form-field>`

**Comment by rodmax** [comment] 2019-05-30 12:05
I have the same issue

@josephperrott could you please consider above comments
