### ISSUE TITLE
Mat-compatible inputs are not being initialized from the template

### ISSUE THREAD

**Issue by dshamgin** [angular/material2#6231] opened 2017-08-02 19:00 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Values of inputs `matSortActive`, `matSortDirection`, and `matSortStart` are to be propagated to the injectable MdSort instance.

#### What is the current behavior?
These values are not being initialized by the template.

#### What are the steps to reproduce?
Plunker template: [updated demo](https://plnkr.co/edit/hnqcQ0fBwjgaiMZSfXWV?p=preview)
* First, notice that in "md-mode" (i.e., non-compatible) values are being initially set from the template.
* Then, turn on the "mat-mode" (i.e., compatible) by uncommenting the `NoConflictStyleCompatibilityMode` and the switching to the `<mat-table...` template, and see that values aren't set.

#### What is the use-case or motivation for changing an existing behavior?
It seems that making sort inputs mat-compatible didn't affect the initialization process.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 1.6.4, Material 2.0.0, TypeScript 2.3.4

**Comment by andrewseguin** [comment] 2017-08-02 20:41
Dupe of #6067

**Closed by andrewseguin** 2017-08-02 20:41 UTC

**Comment by dshamgin** [comment] 2017-08-03 22:34
Not really a dupe of #6067, but according to the merged fixes it is not going to be an issue anymore.
