### ISSUE TITLE
Bug: Datepicker not Pop-up the calender in IE and edge

### ISSUE THREAD

**Issue by stevenmi** [angular/material2#6806] opened 2017-09-02 06:48 UTC
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
the Datepicker Pop-up the calender in IE and edge, when the datepicker is in a pop-up dialog and with touchui = true

#### What is the current behavior?
the Datepicker not Pop-up the calender in IE and edge, when the datepicker is in a pop-up dialog and with touchui = true

#### What are the steps to reproduce?
http://plnkr.co/edit/rdBHyklin5Prq2O0POXR?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular:2.0.0-beta.10-1b6b270
ie:11.540.15063.0
edge:40.15063.0.0

#### Is there anything else we should know?
chrome and firefox have no this bug

**Comment by crisbeto** [comment] 2017-09-02 09:16
Closing as a duplicate of https://github.com/angular/material2/issues/6719.

**Closed by crisbeto** 2017-09-02 09:16 UTC
