### ISSUE TITLE
[mat-menu] New Position like xPosition="'center'" for mat-menu

### ISSUE THREAD

**Issue by MJomaa** [angular/material2#9631] opened 2018-01-26 21:57 UTC
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
xPosition should accept the paramter 'center' .
This new position will center the menu horizontally in relation to the trigger.

#### What is the current behavior?
xPosition only accepts the parameters 'before' or 'after'.

#### What are the steps to reproduce?
https://material.angular.io/components/menu/api

#### What is the use-case or motivation for changing an existing behavior?
The component mat-menu becomes more flexible.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.2.2
Material: 5.1.0
TypeScript: 2.6.2

#### Is there anything else we should know?
--

**Comment by crisbeto** [comment] 2018-01-26 22:10
Adding support for it is only a matter of passing in another value to the `ConnectedPositionStrategy`, but the issue is that supporting it deviates from the spec and may end up looking weird.

**Comment by MJomaa** [comment] 2018-01-28 00:00
Ah too bad. 

Here is an example with an arbitrary x-position https://play.google.com/store.
When you click on the "Google-Apps" button in the top right a dropdown menu appears.
That's basically what I want to achieve.

![image](https://user-images.githubusercontent.com/9029497/35477576-078a5858-03c6-11e8-8d6e-ff599a5bb4a7.png)

**Comment by julianobrasil** [comment] 2018-01-28 02:16
@MJomaa, it seems you want a kind of popover, which is not planned to be added to Material. 

You have currently two options:

1. Make your own using something like [cdkOverlay](https://material.angular.io/cdk/overlay/overview)
2. use a third party component like the awesome [@willshowell's satPopover](https://github.com/ncstate-sat/popover)

**Comment by MJomaa** [comment] 2018-01-28 13:16
@julianobrasil Looks good thanks!

Also there is a third option:

3. Assign a selector for each mat-menu you need to change. 
Set/Override the margin and transform-origin for each mat-menu individually.

**Comment by Stephane-Peyroutet** [comment] 2018-01-30 17:51
I also need this kind of behavior and I will look into @MJomaa temporary solution.
I don't agree that this is a kind of custom popover...and the cdk overlay can be kind of overwhelming, especially if you just want to display a few simple menu elements.
So some options to tune the position a little further would be nice.

**Comment by josephperrott** [comment] 2018-02-13 23:14
Closing as it was noted in an above comment, center positioning of a menu is not conformant to the spec.

**Closed by josephperrott** 2018-02-13 23:14 UTC
