### ISSUE TITLE
side-nav example is not working in the site documentation

### ISSUE THREAD

**Issue by latchuk** [angular/material2#4984] opened 2017-06-06 12:06 UTC
In the site documentation of side-nav https://material.angular.io/components/component/sidenav the exemplo is not working.
About 5 days ago the site was working, but not now. 
It's only the exemplo in the site documentation with a bug or was the component side-nav code changed?

**Comment by willshowell** [comment] 2017-06-06 13:02
Dupe of https://github.com/angular/material2/issues/4944

**Closed** 2017-06-06 22:50 UTC

**Comment by latchuk** [comment] 2017-06-12 18:15
The documentation is not fixed yet.
