### ISSUE TITLE
Incorrect return type in MdGestureConfig.d.ts (?)

### ISSUE THREAD

**Issue by autopulous** [angular/material2#886] opened 2016-07-19 23:48 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
A happy transpiler.

#### What is the current behavior?
`...../node_modules/@angular2-material/core/gestures/MdGestureConfig.d.ts(4,40): error TS2304: Cannot find name 'HammerManager'.`

Here's the line in question:

    buildHammer(element: HTMLElement): HammerManager;

It looks like the type should be (based upon hammer_gestures.d.ts):

    buildHammer(element: HTMLElement): HammerInstance;

#### What are the steps to reproduce?
Compile something that uses MdGestureConfig.d.ts

#### What is the use-case or motivation for changing an existing behavior?
I am very afraid of transpilation errors (especially ones that involve the inability to find names)

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-alpha.6

#### Is there anything else we should know?
I'm using forms@0.2.0 (does this make me a bad person?)

**Comment by autopulous** [comment] 2016-07-20 00:03
Probably related to issue #797

**Comment by jelbourn** [comment] 2016-07-26 23:18
Dupe of #797

**Closed by jelbourn** 2016-07-26 23:18 UTC
