### ISSUE TITLE
Select multiple mat chips from mat-chip-list without clicking out and back in.

### ISSUE THREAD

**Issue by nomanahmedkhan** [angular/material2#12551] opened 2018-08-06 17:25 UTC
#### Bug, feature request, or proposal:

[x] Feature request

#### What is the expected behavior?

The user should be able to select multiple options from without having to click out of the box and clicking back in.

#### What is the current behavior?

When selecting an option from the user has to click out of the box and click back in to see the options again in order to select another option. The user can select another option without clicking out by using keyboard but cannot do so using mouse.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

The current behavior is reproduced here:
https://stackblitz.com/angular/njjrpopbpya?file=app%2Fchips-autocomplete-example.ts

Step 1: Click to select an option

Step2:  Without clicking out, try to select another option.

#### What is the use-case or motivation for changing an existing behavior?

Implementation for better user experience.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 6

**Comment by crisbeto** [comment] 2018-08-06 17:34
You can bring up the autocomplete dropdown again by pressing the up or down arrow key.

**Comment by nomanahmedkhan** [comment] 2018-08-06 17:59
The whole point is not to use the Keys. just do it using the Mouse.

**Comment by crisbeto** [comment] 2018-08-06 18:07
That's not how an autocomplete is supposed to work. If you really want it to work that way, you should be able to re-open the dropdown programmatically yourself.

**Comment by josephperrott** [comment] 2018-08-06 20:46
Closing as this is working as intended and is not something we expect to change.  The desired interaction being described is an entirely different a11y pattern that does not match up to the autocomplete pattern currently in use.

**Closed by josephperrott** 2018-08-06 20:46 UTC
