### ISSUE TITLE
Weird Expansion panel animation

### ISSUE THREAD

**Issue by petivagyok16** [angular/material2#10021] opened 2018-02-19 16:34 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Better animation

#### What is the current behavior?
Items show up sooner than animation ends.

#### What are the steps to reproduce?
![sidemenu](https://user-images.githubusercontent.com/16253571/36388039-f6d3ffc8-159a-11e8-9251-24b4f71fa532.gif)

#### What is the use-case or motivation for changing an existing behavior?
Its a bug

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.2.5
Material: 5.2.1
OS: Mac 10.13.3
Typescript 2.6.2
Chrome 64

**Comment by julianobrasil** [comment] 2018-02-20 14:22
Why "Sidenav" in title? This seems to be an expansion or something like that. Could you provide a stackblitz minimum reproduction?

**Comment by petivagyok16** [comment] 2018-02-20 14:32
True, i use the expansion panel as a sidenav so that i made the title mistake.

**Comment by josephperrott** [comment] 2018-02-20 15:21
Closing as duplicate of #8754

**Closed by josephperrott** 2018-02-20 15:21 UTC
