### ISSUE TITLE
No Select All or Unselect for groups in Mat-Select

### ISSUE THREAD

**Issue by gokul1794** [angular/material2#9948] opened 2018-02-14 14:10 UTC
#### Bug, feature request, or proposal:
Need a select/unselect all feature. There is already an issue at #9149 It would be nice to have that for groups too if any

#### What is the current behavior?
There's currently no way to select/unselect based on group.

#### What is the use-case or motivation for changing an existing behavior?
There's currently no way to select/unselect based on group.

It will be great if it was there probably in the circled or underlined area.
![image](https://user-images.githubusercontent.com/6311809/36208737-3821aba6-11b3-11e8-9d99-057dedd81cbf.png)

**Comment by josephperrott** [comment] 2018-02-14 15:52
Closing as duplicate of #9149

**Closed by josephperrott** 2018-02-14 15:52 UTC
