### ISSUE TITLE
Material Dialog trigger .open() from service not working or weird

### ISSUE THREAD

**Issue by doomsayer2** [angular/material2#12485] opened 2018-08-02 10:24 UTC
#### Bug, feature request, or proposal:
Calling a dialog or open it from a service doesn't work or acts weird. The problem is when we call the dialog .open() and pass a AlertComponent we customly created it produces several strange things. Only when opening the dialog with a traditional (click)="openDialog()" button trigger works.

#### What is the expected behavior?
Suppose we have a nfc tag that is put on our android phone and once near the angular application we have running in the android crosswalk opens a dialog that says "Found!" with options "ok" and "cancel". The dialog should be open once the nfc tag is registered at the phone and this works all fine we get the id of the tag to our service and we call the dialog open, but something strange happens.

#### What is the current behavior?
My collegue explains it very well here:
https://stackoverflow.com/questions/51608781/double-materialdialog-on-angular-6-project-in-android-webview

#### What is the use-case or motivation for changing an existing behavior?
We don't want to use a "ghost button", what we are currently doing, that is triggered by our service or more his (click) listener.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6 and latest material

#### Is there anything else we should know?
You are really great.

**Comment by crisbeto** [comment] 2018-08-02 13:56
It's hard to know what the issue is without looking at the code, but based on issues we've had in the past, it's probably because you're opening the dialog from outside the `NgZone`. You can try to run `MatDialog.open` from inside `NgZone.run` to see if it helps.

**Comment by josephperrott** [comment] 2018-08-06 16:04
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.  As currently outlined its a bit difficult for us to diagnose the issues.

**Comment by josephperrott** [comment] 2018-10-04 14:55
Closing as we are not be able to reproduce this issue.

**Closed by josephperrott** 2018-10-04 14:55 UTC
Labels: cannot reproduce
