### ISSUE TITLE
Open Menu positioning breaks when scrolling below top of root trigger

### ISSUE THREAD

**Issue by rickysandoval** [angular/material2#11679] opened 2018-06-05 15:14 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
It's expected that the menu stays positioned with the trigger

#### What is the current behavior?
When scrolling below the top of the trigger, the position of the open menu jumps down in proportion to the space between the trigger and top of the page + additional scroll

#### What are the steps to reproduce?
1. Open menu
2. Scroll down the page

https://stackblitz.com/edit/angular-rban4u

#### What is the use-case or motivation for changing an existing behavior?
user experience

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3
Angular Material 6.2.1, CDK 6.2.1
Typescript 2.7.2
OSX High Sierra
Chrome, Safari, Firefox

**Comment by crisbeto** [comment] 2018-06-06 20:08
Closing as a duplicate of https://github.com/angular/material2/issues/11365.

**Closed by crisbeto** 2018-06-06 20:08 UTC
