### ISSUE TITLE
Input working incorrect in RTL

### ISSUE THREAD

**Issue by theunreal** [angular/material2#657] opened 2016-06-08 14:36 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Input hover effect and label text position in the right place in RTL (right to left) layouts

#### What is the current behavior?
The position of the input hover effect and the label text is wrong and misplaced in RTL layouts

![image](https://cloud.githubusercontent.com/assets/6171883/15898106/9be57a86-2d9f-11e6-9cc3-220541df6de5.png)

#### What are the steps to reproduce?
Any input element on RTL page

#### What is the use-case or motivation for changing an existing behavior?
Angular2 Material to work on RTL pages

#### Which versions of Angular, Material, OS, browsers are affected?
Latest angular (beta17), Material latest (5-2), all browsers

**Comment by robertmesserle** [comment] 2016-06-08 21:38
@theunreal I think we need more details on how to reproduce your issues - using the demo app and toggling RTL doesn't seem to produce any errors for me.

**Comment by robertmesserle** [comment] 2016-06-08 21:42
@theunreal My guess is that you attempted to set the direction using CSS, but did not include the `dir` attribute to tell Material that the direction is RTL.

**Comment by robertmesserle** [comment] 2016-06-08 21:47
Closing for now - the proper way to do this is with the `dir` attribute since there is no efficient way for us to check the inherited CSS properties.  This is also typically the preferred method.

**Closed by robertmesserle** 2016-06-08 21:47 UTC

**Comment by theunreal** [comment] 2016-06-09 13:02
Good to know the input depends the `dir` attirubte. It works great. thanks.
