### ISSUE TITLE
Md-select and md-intput underlines are not aligned.

### ISSUE THREAD

**Issue by molcik** [angular/material2#3780] opened 2017-03-25 10:41 UTC
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
Md-select and md-intput underlines should be aligned.

#### What is the current behavior?
Md-select and md-intput underlines are not aligned.

#### What are the steps to reproduce?
<img width="774" alt="screen shot 2017-03-25 at 11 37 00" src="https://cloud.githubusercontent.com/assets/11929953/24321572/c7daf80c-114f-11e7-9307-cd078d938e55.png">

Plunker: [http://plnkr.co/edit/3NdcfzN8ixG6PsiBcx0Y](http://plnkr.co/edit/3NdcfzN8ixG6PsiBcx0Y?p=preview)

#### What is the use-case or motivation for changing an existing behavior?
consistency

#### Which versions of Angular, Material, OS, browsers are affected?
last

#### Is there anything else we should know?
no

**Comment by donroyco** [comment] 2017-03-25 12:30
It's also variating off in different browsers:

**Safari Version 10.0.3 (12602.4.8)**
![safari-md](https://cloud.githubusercontent.com/assets/1763537/24322086/29cf283c-115d-11e7-9829-10f7b3bf04c0.png)

**Firefox 50.1.0**
![firefox-md](https://cloud.githubusercontent.com/assets/1763537/24322092/39421fcc-115d-11e7-9a9e-a7a4164cfecc.png)

**Google Chrome Version 57.0.2987.110 (64-bit)**
![chrome-md](https://cloud.githubusercontent.com/assets/1763537/24322215/38353112-115f-11e7-98bc-a03ee0a6e173.png)


**Internet Explorer 11 (Version 11.0.9600.16663)**
![ie-md](https://cloud.githubusercontent.com/assets/1763537/24322205/2338aa78-115f-11e7-9855-4e85a1c190ac.png)

**Microsoft Edge 13**
![edge-md](https://cloud.githubusercontent.com/assets/1763537/24322201/183b8168-115f-11e7-9d11-dd4a1433c95c.png)

**Comment by tmburnell** [comment] 2017-04-06 14:21
I have noticed the same thing about the width when in a flex layout.
![image](https://cloud.githubusercontent.com/assets/25113013/24759194/4acd1732-1aaa-11e7-9a31-0966a4ee65ed.png)
I have 3 times in a row (with space-between). So I would assume they should be the same size.

**Comment by jelbourn** [comment] 2017-04-09 03:07
Dupe of #2124

**Closed by jelbourn** 2017-04-09 03:07 UTC
