### ISSUE TITLE
Does md-input supports the pattern property.?

### ISSUE THREAD

**Issue by codejith** [angular/material2#1706] opened 2016-11-03 08:03 UTC
#### Bug, feature request, or proposal:

feature request

Does md-input supports the pattern property.? Like the patterns in html5. If not when can we expect to see such a feature.?

**Comment by joejordanbrown** [comment] 2016-11-03 15:11
There is a PR that has not been merged that fixes this.

#873

**Comment by jelbourn** [comment] 2016-11-03 20:46
Dupe of #841

**Closed by jelbourn** 2016-11-03 20:46 UTC
