### ISSUE TITLE
both mat-line & matLine used in list docs

### ISSUE THREAD

**Issue by robphoenix** [angular/material2#13876] opened 2018-10-30 12:48 UTC
#### Bug, feature request, or proposal:

Documentation

I noticed that in the list docs, both `matLine` and `mat-line` are used. Is this correct? Is there a difference? Is one more recent? 
It would be good to be consistent in the docs, I'd be happy to open a PR if needs be?

**Comment by josephperrott** [comment] 2018-10-30 16:22
Closing as this is working as intended. Both [`matLine` and `mat-line` are selectors](https://github.com/angular/material2/blob/master/src/lib/core/line/line.ts#L25) for the `MatLine` directive.

**Closed by josephperrott** 2018-10-30 16:22 UTC
