### ISSUE TITLE
Creating incorrectly lazy-rendering MatMenu

### ISSUE THREAD

**Issue by acteralex** [angular/material2#15166] opened 2019-02-12 16:41 UTC
#### What is the expected behavior?
The mat-menu is rendered with sub-menu.
A sub-menu should be visible after hovering on mat-menu-item exists [matMenuTriggerFor].
![mat-menu](https://user-images.githubusercontent.com/668544/52651421-34443680-2efd-11e9-93a6-dc2c338a649d.png)

#### What is the current behavior?
The mat-menu component is rendered without arrow (to show the active mat-menu-item has sub-menu). But If you click on the element which has sub-menu, menu will appear and disappear once time.

#### What are the steps to reproduce?
Look here please https://stackblitz.com/edit/angular-bzbtmd

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
**Angular** version 7.2.2
**Angular Material** version 7.2.2
**OS** Windows 70
**TypeScript** 3.2.4
**browsers are affected?** No

**Comment by crisbeto** [comment] 2019-02-14 14:29
Closing as a duplicate of https://github.com/angular/material2/issues/9011.

**Closed by crisbeto** 2019-02-14 14:29 UTC
