### ISSUE TITLE
Md-Checkbox has no margin when using dynamic label after #2121

### ISSUE THREAD

**Issue by w3t** [angular/material2#4720] opened 2017-05-22 18:21 UTC
#### Bug, feature request, or proposal:
After upgrading to material 2.0.0-beta5, checkboxes on my login screen no longer have margin on their right.

Apparently due to this change:
https://github.com/angular/material2/pull/2121

and to the fact I use dynamic labels (translated by ngx-translate to be precise).

I use something like that:
<md-checkbox [(ngModel)]="savePassword">{{ "tx_Login_SavePassword" | translate }}</md-checkbox>
                
#### What is the expected behavior?

To have margin (space between the checkbox and its label) on the right of the checkbox (no mat-checkbox-inner-container-no-side-margin class)

#### What is the current behavior?

The class mat-checkbox-inner-container-no-side-margin is added to the checkbox when rendering the form. it only disappears when one clicks on the checkbox.

#### What are the steps to reproduce?
Here is the Plunker reproducing the problem (without ngx-translate but using a simple settimeout instead):

https://plnkr.co/5CFp9x

#### What is the use-case or motivation for changing an existing behavior?

Working as it was in previous 2.0.0-beta

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material 2.0.0-beta5

#### Is there anything else we should know?

Don't think so but please ask if I forgot something

**Comment by kgrvr** [comment] 2018-02-28 06:30
Same issue here too.
Material adds following class when using translate pipe:
`
.mat-checkbox-inner-container-no-side-margin {
margin-left: 0;
margin-right: 0;
}
`
Any fix for this, apart from overriding this class?

**Comment by andreasrueedlinger** [comment] 2018-06-26 12:44
@andrewseguin I don't think the issue is completely fixed.
I have the same issue using my own custom component with nested markup and a translate pipe. Here is stackblitz to reproduce the issue:
https://angular-material2-issue-r22sfw.stackblitz.io

Somehow the markForChecked is not called and thus the class is first removed after interacting with the UI in some other way.

**Comment by kaelumania** [comment] 2018-09-04 09:15
Same issue here, any proposed workarounds?

**Comment by andreasrueedlinger** [comment] 2018-09-04 09:17
@andrewseguin @DevVersion Could you please re-open the issue as the problem still exists?

**Comment by DevVersion** [comment] 2018-09-04 09:18
@andreasrueedlinger Thanks for the ping. I will have a look later this day and re-open if I can reproduce it.

**Comment by andreasrueedlinger** [comment] 2018-09-04 09:34
@DevVersion I created a new working stackblitz here: https://angular-material2-issue-z8w4ml.stackblitz.io

**Closed** 2018-09-18 21:19 UTC
Labels: has pr

**Comment by matze1234** [comment] 2019-06-11 10:18
This seems to be still an issue in @angular/material 7.3.6.
I've worked around it by appending &nbsp; to the dynamic label.
