### ISSUE TITLE
It seems that button press ripple effect stays in Chrome inside Sidenav, but not in Firefox or Safari. 

### ISSUE THREAD

**Issue by Nikki1993** [angular/material2#3332] opened 2017-02-28 08:45 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When the button with ripple effect enabled is pressed, after ripple animation concludes, the effect disappears at the end. 

#### What is the current behavior?
Pressing the button keeps the ripple effect after it ends (when the button is located inside sidenav), making button background gray until unfocused or another button is pressed. 

#### What are the steps to reproduce?

1. Create new sidenav
2. Insert a button via inside unordered list 
3. Click the button
4. See ripple animation get stuck on Chrome but work perfectly fine on Firefox and Safari. 

http://plnkr.co/edit/1jNN5lejEuo8VTIk3vsw?p=preview

#### What is the use-case or motivation for changing an existing behavior?
The unintended behavior I suppose. 

#### Which versions of Angular, Material, OS, browsers are affected?
Latest Angular 2.x branch, Material beta 2

**Comment by kara** [comment] 2017-03-01 00:16
Looks like a dupe of https://github.com/angular/material2/issues/3215. Should be fixed in https://github.com/angular/material2/pull/3294.

**Closed by kara** 2017-03-01 00:16 UTC
