### ISSUE TITLE
mat-select items move while scrolling on iphone and Ipad

### ISSUE THREAD

**Issue by NorhanSamir** [angular/material2#11787] opened 2018-06-14 13:00 UTC
#### Bug, feature request, or proposal:
Mat-select option list moves while scrolleing on iphone and ipad

#### What is the expected behavior?
it should be closed when scrolling

**Comment by josephperrott** [comment] 2018-06-25 16:17
Closing as this is working as intended, the select list is expected to stay open during scrolling.

**Closed by josephperrott** 2018-06-25 16:17 UTC
