### ISSUE TITLE
mat-table does not support resize/re-ordering of columns

### ISSUE THREAD

**Issue by palarnab** [angular/material2#11377] opened 2018-05-17 06:52 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Resizing columns of a grid/table (by mouse drag) is a useful feature for our business application.
Also reordering of columns (by mouse drag).

There should be drag-end and drop-end events which should respond with the final size parameters of the altered columns(s)

#### What is the current behavior?
Mat-table columns cannot be resized or re-ordered

#### What are the steps to reproduce?
NA

#### What is the use-case or motivation for changing an existing behavior?
Resize/reordering gris is a much useful feature and supported in many web applications for data presentation. 

Any user who want to re-order columns for a need to see data in a particular order 
OR
A user might want to expand a column with more data to see or shrink a column to make space for other columns.

These two features are reasonably basic for all grid/table controls in modern frameworks.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All browsers.
All angular versions upto angular5.

#### Is there anything else we should know?
NA

**Comment by JoshuaTurner** [comment] 2018-05-19 21:13
Resizable columns request is a duplicate of [#8312](https://github.com/angular/material2/issues/8312)
Reorderable columns request is a duplicate of [#6522](https://github.com/angular/material2/issues/6522)

**Closed** 2018-05-21 15:47 UTC

**Comment by lujian98** [comment] 2019-03-30 20:17
Come cross with angular material table column drag and drop.
Here is my solution: https://github.com/lujian98/Angular-material-table-DnD.
You may have to change the data source interface if you want use it.
Here is demo: https://stackblitz.com/edit/angular-p12rek

**Comment by lujian98** [comment] 2019-03-30 23:22
Angular material table column resize is here: https://github.com/lujian98/Angular-material-table-Resize

Demo at:  https://stackblitz.com/edit/angular-rtfc5v

**Comment by westor21** [comment] 2019-05-22 12:57
@lujian98  Your resize table implementation works great for me, thank you.
I opened a small issue regarding column selection.

**Comment by Swoox** [comment] 2019-05-23 06:54
@lujian98 I already use the drag and drop solution. 
Do you have an example of using them combined?
