### ISSUE TITLE
MdDialog error when opened onInit

### ISSUE THREAD

**Issue by ElecTreeFrying** [angular/material2#6815] opened 2017-09-03 06:12 UTC
#### Bug, feature request, or proposal:
Error in MdDialogContainer_Host.html, Line 1 
![image](https://user-images.githubusercontent.com/19801459/30000939-cbccf322-90af-11e7-91d4-781eabd616af.png)

Im calling my openModal function on my `ngOnInit`, just for testing purposes, and I got this error. 

**ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'dialog'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?**

#### What is the expected behavior?
Remove the error

#### What is the use-case or motivation for changing an existing behavior?
I could have a modal opened onInit in the future in one of my side projects, I will be a pain if there are errors doing this

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material@2.0.0-beta.10
@angular/cli: 1.3.1
os: win32 x64

#### Is there anything else we should know?
This is my first time doing this and I have no idea that there are errors if you will do this onInit, although i did this for testing purposes i...

**Comment by julianobrasil** [comment] 2017-09-03 09:36
This is already being tracked in #5268. Take a look over there. The using of **`setTimeout`** is a possible a workaround for you.

**Comment by ElecTreeFrying** [comment] 2017-09-03 10:43
@julianobrasil I see thank you

**Comment by ElecTreeFrying** [comment] 2017-09-03 10:47
@julianobrasil I see thanks

**Comment by crisbeto** [comment] 2017-09-03 16:20
Closing as a duplicate of #5268.

**Closed by crisbeto** 2017-09-03 16:20 UTC
