### ISSUE TITLE
md-select placeholder does not reset on quick close

### ISSUE THREAD

**Issue by ottosson** [angular/material2#5571] opened 2017-07-07 07:44 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Placeholder text should return to original position when closing menu before animation is done, if no value has been selected.

#### What is the current behavior?
If menu is closed before placeholder text animation is done, the placeholder text will stay over the component as if value was selected.

#### What are the steps to reproduce?
Open md-select menu and close it quickly (press escape or mouse click outside menu) before menu/placeholder animation finishes.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/pf3viLY24x9thuUOrQmH?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.5, Material 2.0.0.beta.8

**Comment by crisbeto** [comment] 2017-07-07 08:07
Closing as a duplicate of https://github.com/angular/material2/issues/4932.

**Closed by crisbeto** 2017-07-07 08:07 UTC
