### ISSUE TITLE
feature: md-grid-list define the number of columns based screen size (media)

### ISSUE THREAD

**Issue by jahtalab** [angular/material2#4575] opened 2017-05-15 21:48 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
To be able to set the number of columns for Grid list component, based on screen size (media)

#### What is the current behavior?
The same number of columns are used in any screen size.

**Comment by jelbourn** [comment] 2017-05-15 23:39
Dupe of #1072

**Closed by jelbourn** 2017-05-15 23:39 UTC
