### ISSUE TITLE
Autocomplete panel does not reposition on scroll of child element

### ISSUE THREAD

**Issue by grizzm0** [angular/material2#5797] opened 2017-07-16 12:50 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
While scrolling the autocomplete panel should reposition itself to follow the input.

#### What is the current behavior?
The panel repositions itself while scrolling body but not if the autocomplete is within a child element that has a scroll.

#### What are the steps to reproduce?
http://plnkr.co/edit/6Wzw5qBuUARyzgqI3foL?p=preview

**Comment by fxck** [comment] 2017-07-16 20:18
dupe of https://github.com/angular/material2/issues/3413

**Comment by crisbeto** [comment] 2017-07-17 07:34
@grizzm0 it'll work if you add `cdk-scrollable` to the `main` element. [Here's a forked Plunkr.](http://plnkr.co/edit/p6ZiYFTeRSmctHOcdfSh?p=preview)

**Closed by crisbeto** 2017-07-17 07:34 UTC

**Comment by kkblues** [comment] 2018-11-14 13:56
https://stackblitz.com/edit/angular-sc6bfp-ft5zvw?file=app%2Fautocomplete-overview-example.html

The issue is still there if you want bigger mat-option content.For example if we set the map-option height style , for example style="height:97px" by navigating with down arrow key the scrolling doesnt work properly
