### ISSUE TITLE
Custom themes don't change sidenav background color

### ISSUE THREAD

**Issue by pablochacin** [angular/material2#8618] opened 2017-11-23 16:51 UTC
#### Bug, feature request, or proposal:
Bug 

#### What is the expected behavior?
Applying a custom theme to a sidenav component should change the background color. Other attributes are changed.  if the same theme is set as the default material theme, the background is set correctly. 

#### What is the current behavior?
it is necessary to set the background color using a css class

#### What are the steps to reproduce?
https://stackblitz.com/edit/basic-sidenav-kcdgmr

#### What is the use-case or motivation for changing an existing behavior?
Control all the element's attributes from the custom theme. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.3
Angular material 2.0.0.beta-11

**Comment by donroyco** [comment] 2017-11-23 18:58
Have you checked #7152?

**Comment by pablochacin** [comment] 2017-11-28 11:12
@donroyco 

> If you are not generating your theme files during your build process, you definitely need to when upgrading because the css always changes between releases for various bug fixes and features.

This seems not to be not my case, as I'm generating the scss files during the build process (for instance, I see color changes if I change the base palette for my custom theme)

**Comment by isurendrasingh** [comment] 2017-11-28 12:39
Check this [https://github.com/angular/material2/issues/4344](url)

**Comment by pablochacin** [comment] 2017-11-28 15:27
@isurendrasingh  issue [4344](https://github.com/angular/material2/issues/4344) looks like a good candidate, thanks

**Comment by mmalerba** [comment] 2017-11-28 17:36
closing as duplicate of #4344

**Closed by mmalerba** 2017-11-28 17:36 UTC

**Comment by isurendrasingh** [comment] 2017-12-03 12:08
Your welcome @pablochacin
