### ISSUE TITLE
Dynamically created MatSpinner does not have the proper width/height

### ISSUE THREAD

**Issue by andreroggeri** [angular/material2#7868] opened 2017-10-18 00:16 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The component should resize based on the diameter property

#### What is the current behavior?
The component isn't resized when the diameter is changed

#### What are the steps to reproduce?
 - Create a `MatSpinner` using a `componentFactoryResolver`
 - Change the `MatSpinner` diameter
 - Check the mat-spinner style

**StackBlitz:** https://angular-material2-issue-35d6ak.stackblitz.io

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.4.5
Material beta.12:

**Comment by crisbeto** [comment] 2017-10-18 17:17
I wasn't able to reproduce it using CDK portals which use `componentFactoryResolver` internally. Can you post an example (the Stackblitz you have seems to be empty)?

**Comment by andreroggeri** [comment] 2017-10-18 17:25
Sorry for the empty Stackblitz.

Check this one: https://stackblitz.com/edit/angular-material2-issue-gxgwgh?file=app/app.module.ts

**Comment by crisbeto** [comment] 2017-10-18 17:48
I can reproduce the issue in your Stackblitz, but not locally which means that it should be fixed in master. Here's a Plunkr that runs the latest master build: http://plnkr.co/edit/V7gJuzZ1QHv6PAKLR72y?p=preview

**Closed by crisbeto** 2017-10-18 17:48 UTC

**Comment by andreroggeri** [comment] 2017-11-28 22:54
@crisbeto I'm upgrading to 5.0.0-rc and the behavior has changed:

Setting the diameter only changes the stroke width.

I made another stackblitz: https://angular-material2-issue-sadacl.stackblitz.io
