### ISSUE TITLE
Specify Accordion to ExpansionPanel

### ISSUE THREAD

**Issue by xSirrioNx** [angular/material2#10920] opened 2018-04-19 16:37 UTC
Hi!
In [docs](https://material.angular.io/components/expansion/api) i see that Expansion Panel has property accordion: MatAccordion
But i have no ideas how can i specify accordion...
Example in stackblitz: [stackblitz](https://stackblitz.com/github/xsirrionx/angular-task-manager)

In this example Acoordion used in parent component, and Expansion panels used in child components (parent - task-list, child - task). So if u expand any of them, you will not see spaces between them.
But if u uncomment lines in app/task-list/task-list.component.html and expand top element in list, you will see spaces between top and other expansion panels.

**Comment by josephperrott** [comment] 2018-04-24 15:06
Closing as duplicate of #6870 - see https://github.com/angular/material2/issues/6870#issuecomment-327847741

**Closed by josephperrott** 2018-04-24 15:06 UTC
