### ISSUE TITLE
Nested MatMenu and NgTemplateOutlet

### ISSUE THREAD

**Issue by the-avid-engineer** [angular/material2#11880] opened 2018-06-21 17:20 UTC
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
When a MatMenuItem with a MatMenuTrigger is added to a MatMenu via a template outlet, the following should happen:
1. When the parent MatMenu is opened, the MatMenuItem with a MatMenuTrigger should show an indicator (">" in the case of LTR) that there is a nested MatMenu
2. When the MatMenuItem with a MatMenuTrigger is hovered, the nested MatMenu should automatically open

#### What is the current behavior?
When a user opens a parent MatMenu, a MatMenuItem with a MatMenuTrigger (added via template outlet) does not show an indicator for a nested MatMenu, nor does hovering over a MatMenuItem with a MatMenuTrigger automatically open its nested MatMenu. Clicking on the MatMenuItem with a MatMenuTrigger *will* open the nested MatMenu, but it will also dismiss the parent MatMenu.

#### What are the steps to reproduce?
I forked the nested menu example from material.angular.io. The only difference is that the vertebrates are in a template, and that template has an outlet in the menu.

FORKED - https://stackblitz.com/edit/angular-fajpqk?file=app/nested-menu-example.html

![image](https://user-images.githubusercontent.com/36554739/41735253-0f418898-753e-11e8-862f-b1e4ceb4914b.png)

ORIGINAL - https://stackblitz.com/angular/vkgdjmxbqrxy?file=app%2Fnested-menu-example.ts

![image](https://user-images.githubusercontent.com/36554739/41735234-0190c268-753e-11e8-925d-64146a919627.png)

#### What is the use-case or motivation for changing an existing behavior?
At the very least, I believe the MatMenuItem should show an indicator that there is a nested MatMenu. The MatMenuItem knows that it is a MatMenuTrigger - that should be enough to show the indicator. The auto-open on hover would be nice to have, but I have very little insight into how much work that would be.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest version of packages, I'm on Windows/Chrome.

#### Is there anything else we should know?
¯\\\_(ツ)\_/¯

**Comment by the-avid-engineer** [comment] 2018-06-22 19:51
I see that the current behavior is due to the fact that MatMenuTrigger.triggersSubmenut() only returns true if MatMenuTrigger._parentMenu **and** MatMenuTrigger.__menuItemInstance are both set. Therefore, I would need a way to manually inject or specify the parent menu to get what I want here.

**Comment by the-avid-engineer** [comment] 2018-06-22 19:57
I would be happy with just #1 - if MatMenuItem._triggersSubmenu was set to true even when the parent menu is unknown. It would make the indicator appear.

**Comment by crisbeto** [comment] 2018-06-25 18:31
@the-avid-engineer even if the `_triggersSubmenu` was set to true, the child menus still won't open when you hover over them. Your issue comes from the fact that `matMenuTrigger` figures out its closest parent menu by going up the DOM. When you put the sub-menu in a separate `ng-template`, the trigger can no longer pick up the menu since it isn't a child of it anymore. You can test it out by yourself by moving the `#test` under `#vertebrates`. Closing since it works as expected.

**Closed by crisbeto** 2018-06-25 18:31 UTC

**Comment by the-avid-engineer** [comment] 2018-06-25 19:15
@crisbeto I concede that there is a good reason to not open a nested MatMenu in this scenario (it wouldn't be able to close all of the parent menu chain). However, I don't see a good reason why _triggersSubmenu cannot be set to true, so that the indicator will show up.

**Comment by the-avid-engineer** [comment] 2018-06-25 19:55
Yes, I understand that the "nested" menu is effectively a stand-alone menu. It can only be opened by clicking on the trigger. But that doesn't seem to me a good reason to not show the indicator.

**Comment by crisbeto** [comment] 2018-06-26 17:59
The issue is that even if we were to show the indicator, it wouldn't be very useful because the sub-menu won't open.

**Comment by the-avid-engineer** [comment] 2018-06-26 18:22
The sub-menu **will** open *if* you click on the trigger - I know this is true because it already opens if you click on the trigger. There is simply no indicator. Showing the indicator would be useful because then the user would know that there is a sub-menu. But I've belabored my point enough. If the angular team refuses to fulfill my feature request to show the indicator I will just manually add the class that makes the indicator show up.

**Comment by crisbeto** [comment] 2018-06-26 18:38
The issue is that even though the menu opens, the sub-menu's parent will close. Also the intended behavior is that the sub-menu opens on hover.

**Comment by the-avid-engineer** [comment] 2018-06-26 18:52
I've given up on this feature request - I've already got what I want by manually setting _triggersSubemenu to true. But I would love to see where the spec outlines this issue and where it says the user shouldn't see the indicator if the UI can't achieve a proper open-on-hover/close-all-on-click
