### ISSUE TITLE
ERROR in node_modules/@angular/material/typings/public-api.d.ts(40,1): error TS2308: Module '@angular/material/menu' has already exported a member named 'xxx'. Consider explicitly re-exporting to resolve the ambiguity.

### ISSUE THREAD

**Issue by esanzgar** [angular/material2#11855] opened 2018-06-20 11:32 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
Compilation fails

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.8
Node: 9.11.1
OS: darwin x64
Angular: 6.0.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.0.2
@angular/cli                      6.0.8
@angular/material                 6.3.0
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
ng-packagr                        3.0.3
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

✨  Done in 0.89s.
```

**Comment by crisbeto** [comment] 2018-06-20 12:40
Closing as a duplicate of https://github.com/angular/material2/issues/11844.

**Closed by crisbeto** 2018-06-20 12:40 UTC

**Comment by AshwinRaj123** [comment] 2019-08-06 10:42
Module 'd3-scale' has already exported a member named 'interpolateCool'. Consider explicitly re-exporting to resolve the ambiguity
