### ISSUE TITLE
vertical-stepper in tab[n!=0] not hides step

### ISSUE THREAD

**Issue by Vesuviao** [angular/material2#8354] opened 2017-11-10 11:02 UTC
#### What is the expected behavior?
the mat-vertical-stepper has the same behavior on each tab 

#### What is the current behavior?
If mat-vertical-stepper is in mat-tab-group, 
but not in the first tab, it does not hide the steps

#### What are the steps to reproduce?
read the short comment on appComponent
https://stackblitz.com/edit/angular-mat-stepper-in-mat-tab-group?file=app%2Fapp.component.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5; Material 5 rc0

#### Is there anything else we should know?
I love you ;)

**Comment by julianobrasil** [comment] 2017-11-10 12:25
It looks like It had the same root cause of #5269

**Comment by josephperrott** [comment] 2017-11-10 16:54
Closing as duplicate of #5269

**Closed by josephperrott** 2017-11-10 16:54 UTC

**Comment by Vesuviante** [comment] 2017-11-17 14:20
following the lula's comment in # 5269
I updated myStepper and now it works

https://stackblitz.com/edit/angular-mat-stepper-in-mat-tab-group?file=app%2Fstepper.component.ts
