### ISSUE TITLE
Inject data into an open Snackbar instead of closing and opening it with different content

### ISSUE THREAD

**Issue by mahdikianirad** [angular/material2#8208] opened 2017-11-03 11:26 UTC
**proposal:**
It should be possible to change the Snackbar content while it is open and visible instead of closing it and opening it again with new content

**expected behavior:**
once an instance of Snackbar is opened and application decided to change the content (for example number of selected items or any other dynamic variable), it should be possible to pass new content and update its content without closing it and opening it again an again

**current behavior:**
currently if I want to change the content I should use MatSnackBar.open('new message', snackBarConfig) which closes the currently open Snackbar and open it again

**use-case or motivation for changing an existing behavior:**
Imagine you have a constantly changing variable like line distance on a map and with each user interaction you want to update the measured distance. it is very annoying to open an close each time user change the distance measurements

**Comment by willshowell** [comment] 2017-11-03 13:43
This is already possible with `openFromComponent`. Just use a service to communicate between with the snackbar component.

https://stackblitz.com/edit/material2-beta12-mlvrtq?file=app%2Fapp.component.ts

**Comment by josephperrott** [comment] 2017-11-03 14:29
Closing as duplicate of #7323

**Closed by josephperrott** 2017-11-03 14:29 UTC
