### ISSUE TITLE
Maxlength in mdInput not working

### ISSUE THREAD

**Issue by JoseDRojasA** [angular/material2#6557] opened 2017-08-19 20:47 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If I put a N as my box's max length, i expect that I can't put more than N characters.

#### What is the current behavior?
I can put more than N characters.

#### What are the steps to reproduce?
<input mdInput maxlength="7" [(ngModel)]="client.telephone" name="telephone">

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
        "@angular/animations": "^4.3.3",
        "@angular/cdk": "^2.0.0-beta.8",
        "@angular/common": "^4.0.0",
        "@angular/compiler": "^4.0.0",
        "@angular/core": "^4.0.0",
        "@angular/forms": "^4.0.0",
        "@angular/http": "^4.0.0",
        "@angular/material": "^2.0.0-beta.8",
        "@angular/platform-browser": "^4.0.0",
        "@angular/platform-browser-dynamic": "^4.0.0",
        "@angular/router": "^4.0.0",
        "bootstrap": "^4.0.0-alpha.6",
        "core-js": "^2.4.1",
        "dotenv": "^4.0.0",
        "font-awesome": "^4.7.0",
        "rxjs": "^5.1.0",
        "zone.js": "^0.8.4"

**Comment by donroyco** [comment] 2017-08-20 09:06
Duplicate of #1934

**Closed** 2017-08-21 18:53 UTC
