### ISSUE TITLE
Date Picker has a today's date choice that I can't turn off how is this accomplished? 

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#13866] opened 2018-10-29 21:17 UTC
#### Bug, feature request, or proposal:
I don't know if the api just isn't explaining how to turn it off but I am using the input to open the calendar and it has this weird double calendar which one flashes with the today's date and the other is the full calendar.  How do you disable the today's date choice when clicking on the input?

#### What is the expected behavior?
to not have the today's date choice. 

#### What is the current behavior?
the today's date choice is flashing up 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
I dont' want it

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular and material 7.0.1

#### Is there anything else we should know?
thank you

**Comment by josephperrott** [comment] 2018-10-30 16:19
After reading your description, I am not quite sure what you are meaning.  Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

**Comment by xtianus79** [comment] 2018-10-30 19:53
@josephperrott you can use any stackblitz to see what i am referring to. 

https://stackblitz.com/angular/rooonlgxrlq?file=app%2Fdatepicker-overview-example.html

The simple part of it is when you click on the input a selection for today's date comes up.  Perhaps it is a chrome browser thing.

**Comment by josephperrott** [comment] 2018-11-05 23:31
@xtianus79 can you reiterate the issue you are seeing?

I am unable to see a reproduction because I am not sure how the current behavior differs from your explanation.

**Comment by xtianus79** [comment] 2018-11-14 20:53
@josephperrott howdy! I believe this is the chrome browser literally remembering the dates I picked so when i choose to encapsulate the entire field of the date picker as a pickable openable action for a split second the previous dates, i.e. today and whatever else will show up like a material date picker for a single day or multiple single days that have been picked. 

So, I ultimately believe this is a chrome thing  is there a way to escape that or turn that off in chrome?

**Comment by josephperrott** [comment] 2018-11-27 15:21
Closing as it sounds like it has been sorted as a chrome autofill issue.

You can read a conversation in the chromium bugs [here](https://bugs.chromium.org/p/chromium/issues/detail?id=370363#c7) but it looks like its not possible to disable it directly and instead the recommendation is to use unique names for inputs.

**Closed by josephperrott** 2018-11-27 15:21 UTC
Labels: cannot reproduce
