### ISSUE TITLE
Autocomplete - Unable to navigate using arrow keys

### ISSUE THREAD

**Issue by varunrramani** [angular/material2#12257] opened 2018-07-18 12:58 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
User should be able to navigate the autocomplete panel with arrow keys when nothing is typed in associated input field.

#### What is the current behavior?
When the autocomplete panel is opened and nothing is typed in the associated input field user cannot navigate the autocomplete panel with the arrow keys on the keyboard.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/animations": "^5.2.11",
"@angular/cdk": "5.2.4",
"@angular/common": "^5.2.11",
"@angular/compiler": "^5.2.11",
"@angular/core": "^5.2.11",
"@angular/forms": "^5.2.11",
"@angular/http": "^5.2.11",
"@angular/material": "5.2.4",
"@angular/platform-browser": "^5.2.11",
"@angular/platform-browser-dynamic": "^5.2.11",
"@angular/cli": "1.7.3",
"@angular/compiler-cli": "^5.2.11",
"@angular/language-service": "^5.2.0",
"ts-node": "~4.1.0",
"tslint": "~5.9.1",
"typescript": "~2.5.3"

Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by crisbeto** [comment] 2018-07-18 13:54
It seems to work on the [Material docs site](https://v5.material.angular.io/components/autocomplete/examples), both in 5.2.x and 6.x. Can you post an example of it breaking?

**Comment by varunrramani** [comment] 2018-07-20 09:14
`
<input matInput [matAutocomplete]="language" [formControl]="addItems" #itemInput id="itemInput" (keydown)="onKeyDown($event)"
        class="search-input" [style.width.px]="itemInputWidth" name="itemInput" [(ngModel)]="itemInputValue" />
    <mat-autocomplete id="searchAutocomplete" #searchAutocomplete autoActiveFirstOption #language="matAutocomplete" (optionSelected)="onAddItems($event)"
        [style.width.px]="autocompleteWidth">
        <mat-option *ngFor="let item of filteredItems | async" [value]="item">
            <span>{{item.displayName}}</span>
        </mat-option>
    </mat-autocomplete>
`

This is the code I'm using. Is there something I'm missing?

**Comment by crisbeto** [comment] 2018-07-20 09:18
Glancing over it, it looks like you have a `keydown` on the `input`. If you've got an `event.stopPropagation` in there, it might prevent Material from picking up the events.

**Comment by varunrramani** [comment] 2018-07-20 09:25
I dont have event.stopPropagation in there. If that was the case then it shouldn't be allowing navigation when there is something typed in the input field as well if I'm not wrong?

**Comment by crisbeto** [comment] 2018-07-20 09:27
It's still difficult to tell what's going on only from that snippet. Can you put together an example that shows it breaking? [You can fork this one](https://stackblitz.com/angular/kdqaenxonmr?file=app%2Fautocomplete-overview-example.ts).

**Comment by crisbeto** [comment] 2018-07-20 15:31
By the looks of it, there's probably something else in your app that's interfering with the keydown event. Closing the issue for now, but it can be reopened if you can reproduce it.

**Closed by crisbeto** 2018-07-20 15:31 UTC
Labels: cannot reproduce

**Comment by varunrramani** [comment] 2018-09-05 12:35
Is there a way we could manually bubble up the keydown event. Keydown event on the input field is hindering the default functioning. If I remove the keydown event on input field, it works fine.

Thanks!
