### ISSUE TITLE
md-autocomplete required validation is not there

### ISSUE THREAD

**Issue by Suresh918** [angular/material2#6449] opened 2017-08-14 06:16 UTC
#### What is the expected behavior?
There is no required attribute/field in autocomplete component, so i am unable to add required validation on autocomplete.

#### What is the current behavior?
There is no required attribute in autocomplete component.
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by CDDelta** [comment] 2017-08-14 09:09
The autocomplete component is supposed to be used with an <input>, so add your validation code there.

**Comment by willshowell** [comment] 2017-08-16 14:58
@CDDelta's comment probably had html in it, so

The autocomplete doesn't concern itself with the underlying input's validators. Either use `Validators.required` on your form control or make the `<input />` required.

**Comment by rafaelss95** [comment] 2017-08-25 21:20
I think what he wants is something like `md-require-match` that is present in [Autocomplete's AngularJs Material](https://material.angularjs.org/latest/api/directive/mdAutocomplete).

Related to #3334?

**Comment by josephperrott** [comment] 2017-09-27 16:27
Closing as duplicate of #3334

**Closed by josephperrott** 2017-09-27 16:27 UTC
