### ISSUE TITLE
Service worker on website

### ISSUE THREAD

**Issue by BePasquet** [angular/material2#11945] opened 2018-06-27 06:31 UTC
#### Bug, feature request, or proposal:
I spotted that service worker doesnt claim and reloads website

#### What is the expected behavior?
i assume you know all this but maybe helps
```ts
if ("serviceWorker" in navigator) {
        navigator.serviceWorker.register('sw.js').then(x => console.log('SW registered'));
        navigator.serviceWorker.addEventListener('controllerchange', (ev) => {
            console.log('controller-change');
            window.location.reload();
        });
    }
self.addEventListener('install', () => {
    self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    event.waitUntil(self.clients.claim());
});
```

#### What is the current behavior?
sometimes page just stay blank i have to skip awaiting on sw

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by BePasquet** [comment] 2018-06-27 06:32
just letting you know is not an issue for me

**Comment by mtrdp642** [comment] 2018-06-28 16:22
You may get more attention filing an issue against the [material.angular.io repo](https://github.com/angular/material.angular.io). [Issue #472](https://github.com/angular/material.angular.io/issues/472) is related.

**Comment by razvantomegea** [comment] 2018-07-14 10:09
I also noticed this issue a lot of times in Chrome and Firefox. I happens when a new version of the website is deployed. It is fixed if I clean the application cache storage (Force Refresh the page). The issue is caused by ngsw-worker, I believe, by not enforcing mime type to the stored files.

**Comment by amcdnl** [comment] 2018-07-15 17:47
I'm not able to reproduce this locally but I tweaked some settings on the SW that might resolve this issue - https://github.com/angular/material.angular.io/pull/485

**Comment by BePasquet** [comment] 2018-08-14 09:07
![image](https://user-images.githubusercontent.com/13737675/44082592-de7b6aee-9fdb-11e8-9b71-b6cb6a71ee4e.png)
posible solution: 
`import { Injectable } from "@angular/core";

import { SwUpdate } from "@angular/service-worker";

@Injectable()
export class SWActivate {
  constructor(private swUpdate: SwUpdate) {
    this.swUpdate.available.subscribe(evt => location.reload());
  }
}`
`import { SWActivate } from "../core/services/sw-activate.service";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"]
})
export class AppComponent {
  constructor(
    private swActivate: SWActivate
  ) {
  }
}`

**Comment by jelbourn** [comment] 2018-10-16 22:32
Closing since we've removed the SW from the docs site temporarily

**Closed by jelbourn** 2018-10-16 22:32 UTC
Labels: P2, has pr
