### ISSUE TITLE
[MdButton] styles get messed up

### ISSUE THREAD

**Issue by eagle-dan1349** [angular/material2#2059] opened 2016-12-02 08:07 UTC
#### Bug, feature request, or proposal:
[x] Bug

#### What is the expected behavior?
MdButton behavior is indifferent to hosting element, be it <a> or <button>

#### What is the current behavior?
When using 'md-button' on <a> element, it attaches 'disabled' attribute.
Presence of 'disabled' attribute causes disabled state styles to be applied to button (no matter what is attribute's value).
In case of <button> tag, everything is fine 

#### What are the steps to reproduce?
Create a page with <a> link
Use md-button on it.
See styles broken.

#### What is the use-case or motivation for changing an existing behavior?
Stable and consistent behavior of component.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.2.4
Material 2.0.0-alpha.10

**Comment by fxck** [comment] 2016-12-02 08:57
https://github.com/angular/material2/issues/1946

**Comment by eagle-dan1349** [comment] 2016-12-02 09:13
I used usual 'md-button', not 'md-raised-button'

**Comment by jelbourn** [comment] 2016-12-02 17:22
Dupe of #1946 (applies to all kinds of button)

**Closed by jelbourn** 2016-12-02 17:22 UTC
