### ISSUE TITLE
md-tab inkbar not showing on nested tabs

### ISSUE THREAD

**Issue by mathewblackberry** [angular/material2#4255] opened 2017-04-25 03:28 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-ink-bar should display correctly on nested tabs.

#### What is the current behavior?
md-ink-bar does not display on a nested tab-group if the tab-group is not in the tab body of the initial selected tab.  Once the nested tab header has been clicked it works as expected and the ink-bar appears and remains when changing between the parent tab-group's tabs.

#### What are the steps to reproduce?

http://plnkr.co/edit/74YDWj192schVQqXnx0p?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Current behaviour provides a poor user experience.

#### Which versions of Angular, Material, OS, browsers are affected?
 Angular 4.0.3, Material 2.0.0-beta 3, Mac OS X, Chrome.

**Comment by jefersonestevo** [comment] 2017-04-25 13:05
+1 for this.

In my application I'm not using nested tabs, but using tabs inside a component that "changes" the page using `<ng-template [ngTemplateOutlet]="myCurrentTemplate"></ng-template>` and the same behaviour happens. If you want I may create a plunker with this too, but I think the error is the same.

**Comment by ciesielskico** [comment] 2017-04-25 20:09
+1

**Comment by vultix** [comment] 2017-06-25 21:39
Are there any updates on this?

**Comment by jrood** [comment] 2017-07-25 00:46
In my case, the inkbar seems initially to be invisible because it has a width of 0.

**Comment by jelbourn** [comment] 2017-08-07 19:10
Dupe of #3335

**Closed by jelbourn** 2017-08-07 19:10 UTC
Labels: md-tabs, P3: important
