### ISSUE TITLE
`disabled` on mdInput doesn't work when formControl directive is used(works with native el)

### ISSUE THREAD

**Issue by fxck** [angular/material2#2667] opened 2017-01-16 11:09 UTC
see http://plnkr.co/edit/AvPMHB3lzqwaexypHkUR?p=preview

I've read some issues on `angular/angular` and apparently `disabled` shouldn't work at all when reactive forms are used. But it looks like it does on native elements and doesn't on element with `mdInput` directive.

cc @kara

**Comment by kara** [comment] 2017-01-17 18:37
cc @mmalerba

**Comment by RicardoVaranda** [comment] 2017-01-20 09:42
+1 Seems like disabled Input has a few issues:

https://plnkr.co/edit/HEJze0spwbiQS558SvrE?p=preview

**Comment by emin93** [comment] 2017-01-24 16:35
I can reproduce this bug, but it seems to work when adding the disabled directive manually.

```
<!-- Doesn't work properly -->
<input md-input [disabled]="false">
```

```
<!-- Works -->
<input md-input disabled>
```

**Comment by mmalerba** [comment] 2017-01-25 23:54
@kara I think this is a result of #2565. you changed it so that if a form control is present that takes precedence. Is this current behavior the correct behavior?

```typescript
get disabled() {
  return this._ngControl ? this._ngControl.disabled : this._disabled;
}
```

or do we want this?

```typescript
get disabled() {
  return this._ngControl ? this._ngControl.disabled || this._disabled : this._disabled;
}
```

**Comment by kara** [comment] 2017-01-26 00:58
Discussed offline with @mmalerba. In short, the behavior is right in that the control should always take precedence over the disabled property. Otherwise, if you disable the control programmatically without setting the disabled property (as is typical of reactive form pattern), the input will not pick up the new disabled state. The internal property is really intended for forms that aren't using either of the core forms modules.  

@fxck is correct that standalone (unbound) disabled values* do behave slightly differently from how they work in native inputs. While both throw warnings in the console that the pattern is not recommended, mdInput completely ignores the property, whereas native inputs *kind of* work in that they disable the UI (though they don't update the control).  I'm not certain that we want to spend time to make the unbound disabled property "kind of" work, given that it's already a pattern we're warning people not to use. This is an area that we should really work on in Angular core because the behavior still isn't consistent. For that reason, I'm closing this issue. If anything, a change should be on the other end. 

*As opposed to doing something like `[disabled]="isDisabled"`, where both inputs ignore it.

**Closed by kara** 2017-01-26 00:58 UTC
