### ISSUE TITLE
Mat-menu, problem with scrolling

### ISSUE THREAD

**Issue by striky1** [angular/material2#12128] opened 2018-07-10 09:34 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
It should stay in right position

#### What is the current behavior?
It going away during the scroll if body is bigger than viewport and mat-menu is also bigger than viewport

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-zjnop2

#### What is the use-case or motivation for changing an existing behavior?
Improve

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular v6.0.0
Material 6.3.3
Google Chrome v 67.0.3396.87 (Official Build) (64-bit)

#### Is there anything else we should know?
@angular/animations v6.0.6 was not working in this stackblitz, so, I was must downgrade to v6.0.0.

**Comment by crisbeto** [comment] 2018-07-10 09:50
Closing as a duplicate of https://github.com/angular/material2/issues/11365.

**Closed by crisbeto** 2018-07-10 09:50 UTC
