### ISSUE TITLE
ReferenceError: requestAnimationFrame is not defined  at MdProgressCircle._animateCircle 

### ISSUE THREAD

**Issue by hakonamatata** [angular/material2#700] opened 2016-06-16 13:51 UTC
When I build an app containing: 
    
`<md-progress-circle *shellRender mode="indeterminate" color="primary"></md-progress-circle>`

I get the following errror: 

```
[2K[1G[?25hLivereload server on http://localhost:49155
[2K[1G[?25hServing on http://localhost:4200/
The Broccoli Plugin: [AppShellPlugin] failed with:
Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "node D:\ng\puppy-love-io\node_modules\angular2-broccoli-prerender\dist\child_proc.js  --sourceHtml=D:\ng\puppy-love-io\tmp\app_shell_plugin-input_base_path-BIHf5ydY.tmp\0\index.html --optionsPath=D:\ng\puppy-love-io\tmp\app_shell_plugin-input_base_path-BIHf5ydY.tmp\0\main-app-shell --outputIndexPath=D:\ng\puppy-love-io\tmp\app_shell_plugin-output_path-Ss6o0A09.tmp\index.html"
EXCEPTION: Error in D:\ng\puppy-love-io\tmp\broccoli_type_script_compiler-cache_path-tz5FdUvU.tmp\src\app\puppy-love-io.component.js class PuppyLoveIoAppComponent - inline template:24:37
ORIGINAL EXCEPTION: ReferenceError: requestAnimationFrame is not defined
ORIGINAL STACKTRACE:
ReferenceError: requestAnimationFrame is not defined
    at MdProgressCircle._animateCircle (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:123:13)
    at animate (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:136:19)
    at MdProgressCircle._startIndeterminateAnimation (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:145:13)
    at MdProgressCircle.Object.defineProperty.set [as mode] (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:84:22)
    at DebugAppView._View_PuppyLoveIoAppComponent5.detectChangesInternal (PuppyLoveIoAppComponent.template.js:676:37)
    at DebugAppView.AppView.detectChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:200:14)
    at DebugAppView.detectChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:289:44)
    at DebugAppView.AppView.detectContentChildrenChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:215:37)
    at DebugAppView._View_PuppyLoveIoAppComponent0.detectChangesInternal (PuppyLoveIoAppComponent.template.js:252:8)
    at DebugAppView.AppView.detectChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:200:14)
ERROR CONTEXT:
DebugContext {
  _view: 
   DebugAppView {
     clazz: [Function: _View_PuppyLoveIoAppComponent5],
     componentType: 
      RenderComponentType {
        id: 'gxt-1',
        templateUrl: 'D:\\ng\\puppy-love-io\\tmp\\broccoli_type_script_compiler-cache_path-tz5FdUvU.tmp\\src\\app\\puppy-love-io.component.js class PuppyLoveIoAppComponent - inline template',
        slotCount: 0,
        encapsulation: 2,
        styles: [] },
     type: 2,
     viewUtils: 
      ViewUtils {
        _renderer: [Object],
        _appId: 'gxt',
        _nextCompTypeId: 7,
        sanitizer: DomSanitizationServiceImpl {} },
     parentInjector: ElementInjector { _view: [Object], _nodeIndex: 1 },
     declarationAppElement: 
      AppElement {
        index: 25,
        parentIndex: 1,
        parentView: [Object],
        nativeElement: [Object],
        nestedViews: [Object],
        componentView: null },
     cdMode: 2,
     contentChildren: [],
     viewChildren: [ [Object] ],
     viewContainerElement: 
      AppElement {
        index: 25,
        parentIndex: 1,
        parentView: [Object],
        nativeElement: [Object],
        nestedViews: [Object],
        componentView: null },
     cdState: 2,
     destroyed: false,
     ref: ViewRef_ { _view: [Circular] },
     renderer: DebugDomRenderer { _delegate: [Object] },
     staticNodeDebugInfos: [ [Object] ],
     _currentDebugContext: [Circular],
     context: {},
     _hasExternalHostElement: false,
     projectableNodes: [],
     _el_0: 
      { type: 'tag',
        name: 'md-progress-circle',
        namespace: 'http://www.w3.org/1999/xhtml',
        attribs: [Object],
        'x-attribsNamespace': {},
        'x-attribsPrefix': {},
        children: [Object],
        parent: [Object],
        prev: [Object],
        next: [Object] },
     _appEl_0: 
      AppElement {
        index: 0,
        parentIndex: null,
        parentView: [Circular],
        nativeElement: [Object],
        nestedViews: null,
        componentView: [Object],
        component: [Object],
        componentConstructorViewQueries: [] },
     _MdProgressCircle_0_4: 
      MdProgressCircle {
        _changeDetectorRef: [Object],
        _lastAnimationId: 1,
        _value: 0,
        _mode: 'determinate',
        _interdeterminateInterval: [Object] },
     _expr_0: {},
     _expr_1: {},
     _expr_2: {},
     rootNodesOrAppElements: [ [Object] ],
     allNodes: [ [Object] ],
     disposables: [],
     subscriptions: [] },
  _nodeIndex: 0,
  _tplRow: 24,
  _tplCol: 37 }
EXCEPTION: Error in D:\ng\puppy-love-io\tmp\broccoli_type_script_compiler-cache_path-tz5FdUvU.tmp\src\app\puppy-love-io.component.js class PuppyLoveIoAppComponent - inline template:24:37
ORIGINAL EXCEPTION: ReferenceError: requestAnimationFrame is not defined
ORIGINAL STACKTRACE:
ReferenceError: requestAnimationFrame is not defined
    at MdProgressCircle._animateCircle (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:123:13)
    at animate (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:136:19)
    at MdProgressCircle._startIndeterminateAnimation (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:145:13)
    at MdProgressCircle.Object.defineProperty.set [as mode] (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:84:22)
    at DebugAppView._View_PuppyLoveIoAppComponent5.detectChangesInternal (PuppyLoveIoAppComponent.template.js:676:37)
    at DebugAppView.AppView.detectChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:200:14)
    at DebugAppView.detectChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:289:44)
    at DebugAppView.AppView.detectContentChildrenChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:215:37)
    at DebugAppView._View_PuppyLoveIoAppComponent0.detectChangesInternal (PuppyLoveIoAppComponent.template.js:252:8)
    at DebugAppView.AppView.detectChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:200:14)
ERROR CONTEXT:
DebugContext {
  _view: 
   DebugAppView {
     clazz: [Function: _View_PuppyLoveIoAppComponent5],
     componentType: 
      RenderComponentType {
        id: 'gxt-1',
        templateUrl: 'D:\\ng\\puppy-love-io\\tmp\\broccoli_type_script_compiler-cache_path-tz5FdUvU.tmp\\src\\app\\puppy-love-io.component.js class PuppyLoveIoAppComponent - inline template',
        slotCount: 0,
        encapsulation: 2,
        styles: [] },
     type: 2,
     viewUtils: 
      ViewUtils {
        _renderer: [Object],
        _appId: 'gxt',
        _nextCompTypeId: 7,
        sanitizer: DomSanitizationServiceImpl {} },
     parentInjector: ElementInjector { _view: [Object], _nodeIndex: 1 },
     declarationAppElement: 
      AppElement {
        index: 25,
        parentIndex: 1,
        parentView: [Object],
        nativeElement: [Object],
        nestedViews: [Object],
        componentView: null },
     cdMode: 2,
     contentChildren: [],
     viewChildren: [ [Object] ],
     viewContainerElement: 
      AppElement {
        index: 25,
        parentIndex: 1,
        parentView: [Object],
        nativeElement: [Object],
        nestedViews: [Object],
        componentView: null },
     cdState: 2,
     destroyed: false,
     ref: ViewRef_ { _view: [Circular] },
     renderer: DebugDomRenderer { _delegate: [Object] },
     staticNodeDebugInfos: [ [Object] ],
     _currentDebugContext: [Circular],
     context: {},
     _hasExternalHostElement: false,
     projectableNodes: [],
     _el_0: 
      { type: 'tag',
        name: 'md-progress-circle',
        namespace: 'http://www.w3.org/1999/xhtml',
        attribs: [Object],
        'x-attribsNamespace': {},
        'x-attribsPrefix': {},
        children: [Object],
        parent: [Object],
        prev: [Object],
        next: [Object] },
     _appEl_0: 
      AppElement {
        index: 0,
        parentIndex: null,
        parentView: [Circular],
        nativeElement: [Object],
        nestedViews: null,
        componentView: [Object],
        component: [Object],
        componentConstructorViewQueries: [] },
     _MdProgressCircle_0_4: 
      MdProgressCircle {
        _changeDetectorRef: [Object],
        _lastAnimationId: 1,
        _value: 0,
        _mode: 'determinate',
        _interdeterminateInterval: [Object] },
     _expr_0: {},
     _expr_1: {},
     _expr_2: {},
     rootNodesOrAppElements: [ [Object] ],
     allNodes: [ [Object] ],
     disposables: [],
     subscriptions: [] },
  _nodeIndex: 0,
  _tplRow: 24,
  _tplCol: 37 }
EXCEPTION: Error in D:\ng\puppy-love-io\tmp\broccoli_type_script_compiler-cache_path-tz5FdUvU.tmp\src\app\puppy-love-io.component.js class PuppyLoveIoAppComponent - inline template:24:37
ORIGINAL EXCEPTION: ReferenceError: requestAnimationFrame is not defined
ORIGINAL STACKTRACE:
ReferenceError: requestAnimationFrame is not defined
    at MdProgressCircle._animateCircle (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:123:13)
    at animate (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:136:19)
    at MdProgressCircle._startIndeterminateAnimation (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:145:13)
    at MdProgressCircle.Object.defineProperty.set [as mode] (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:84:22)
    at DebugAppView._View_PuppyLoveIoAppComponent5.detectChangesInternal (PuppyLoveIoAppComponent.template.js:676:37)
    at DebugAppView.AppView.detectChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:200:14)
    at DebugAppView.detectChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:289:44)
    at DebugAppView.AppView.detectContentChildrenChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:215:37)
    at DebugAppView._View_PuppyLoveIoAppComponent0.detectChangesInternal (PuppyLoveIoAppComponent.template.js:252:8)
    at DebugAppView.AppView.detectChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:200:14)
ERROR CONTEXT:
DebugContext {
  _view: 
   DebugAppView {
     clazz: [Function: _View_PuppyLoveIoAppComponent5],
     componentType: 
      RenderComponentType {
        id: 'gxt-1',
        templateUrl: 'D:\\ng\\puppy-love-io\\tmp\\broccoli_type_script_compiler-cache_path-tz5FdUvU.tmp\\src\\app\\puppy-love-io.component.js class PuppyLoveIoAppComponent - inline template',
        slotCount: 0,
        encapsulation: 2,
        styles: [] },
     type: 2,
     viewUtils: 
      ViewUtils {
        _renderer: [Object],
        _appId: 'gxt',
        _nextCompTypeId: 7,
        sanitizer: DomSanitizationServiceImpl {} },
     parentInjector: ElementInjector { _view: [Object], _nodeIndex: 1 },
     declarationAppElement: 
      AppElement {
        index: 25,
        parentIndex: 1,
        parentView: [Object],
        nativeElement: [Object],
        nestedViews: [Object],
        componentView: null },
     cdMode: 2,
     contentChildren: [],
     viewChildren: [ [Object] ],
     viewContainerElement: 
      AppElement {
        index: 25,
        parentIndex: 1,
        parentView: [Object],
        nativeElement: [Object],
        nestedViews: [Object],
        componentView: null },
     cdState: 2,
     destroyed: false,
     ref: ViewRef_ { _view: [Circular] },
     renderer: DebugDomRenderer { _delegate: [Object] },
     staticNodeDebugInfos: [ [Object] ],
     _currentDebugContext: [Circular],
     context: {},
     _hasExternalHostElement: false,
     projectableNodes: [],
     _el_0: 
      { type: 'tag',
        name: 'md-progress-circle',
        namespace: 'http://www.w3.org/1999/xhtml',
        attribs: [Object],
        'x-attribsNamespace': {},
        'x-attribsPrefix': {},
        children: [Object],
        parent: [Object],
        prev: [Object],
        next: [Object] },
     _appEl_0: 
      AppElement {
        index: 0,
        parentIndex: null,
        parentView: [Circular],
        nativeElement: [Object],
        nestedViews: null,
        componentView: [Object],
        component: [Object],
        componentConstructorViewQueries: [] },
     _MdProgressCircle_0_4: 
      MdProgressCircle {
        _changeDetectorRef: [Object],
        _lastAnimationId: 1,
        _value: 0,
        _mode: 'determinate',
        _interdeterminateInterval: [Object] },
     _expr_0: {},
     _expr_1: {},
     _expr_2: {},
     rootNodesOrAppElements: [ [Object] ],
     allNodes: [ [Object] ],
     disposables: [],
     subscriptions: [] },
  _nodeIndex: 0,
  _tplRow: 24,
  _tplCol: 37 }
{ [Error: EXCEPTION: Error in D:\ng\puppy-love-io\tmp\broccoli_type_script_compiler-cache_path-tz5FdUvU.tmp\src\app\puppy-love-io.component.js class PuppyLoveIoAppComponent - inline template:24:37
ORIGINAL EXCEPTION: ReferenceError: requestAnimationFrame is not defined
ORIGINAL STACKTRACE:
ReferenceError: requestAnimationFrame is not defined
    at MdProgressCircle._animateCircle (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:123:13)
    at animate (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:136:19)
    at MdProgressCircle._startIndeterminateAnimation (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:145:13)
    at MdProgressCircle.Object.defineProperty.set [as mode] (D:\ng\puppy-love-io\node_modules\@angular2-material\progress-circle\progress-circle.js:84:22)
    at DebugAppView._View_PuppyLoveIoAppComponent5.detectChangesInternal (PuppyLoveIoAppComponent.template.js:676:37)
    at DebugAppView.AppView.detectChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:200:14)
    at DebugAppView.detectChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:289:44)
    at DebugAppView.AppView.detectContentChildrenChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:215:37)
    at DebugAppView._View_PuppyLoveIoAppComponent0.detectChangesInternal (PuppyLoveIoAppComponent.template.js:252:8)
    at DebugAppView.AppView.detectChanges (D:\ng\puppy-love-io\node_modules\@angular\core\src\linker\view.js:200:14)
ERROR CONTEXT:
[object Object]]
  _wrapperMessage: 'Error in D:\\ng\\puppy-love-io\\tmp\\broccoli_type_script_compiler-cache_path-tz5FdUvU.tmp\\src\\app\\puppy-love-io.component.js class PuppyLoveIoAppComponent - inline template:24:37',
  _originalException: [ReferenceError: requestAnimationFrame is not defined],
  _originalStack: 'ReferenceError: requestAnimationFrame is not defined\n    at MdProgressCircle._animateCircle (D:\\ng\\puppy-love-io\\node_modules\\@angular2-material\\progress-circle\\progress-circle.js:123:13)\n    at animate (D:\\ng\\puppy-love-io\\node_modules\\@angular2-material\\progress-circle\\progress-circle.js:136:19)\n    at MdProgressCircle._startIndeterminateAnimation (D:\\ng\\puppy-love-io\\node_modules\\@angular2-material\\progress-circle\\progress-circle.js:145:13)\n    at MdProgressCircle.Object.defineProperty.set [as mode] (D:\\ng\\puppy-love-io\\node_modules\\@angular2-material\\progress-circle\\progress-circle.js:84:22)\n    at DebugAppView._View_PuppyLoveIoAppComponent5.detectChangesInternal (PuppyLoveIoAppComponent.template.js:676:37)\n    at DebugAppView.AppView.detectChanges (D:\\ng\\puppy-love-io\\node_modules\\@angular\\core\\src\\linker\\view.js:200:14)\n    at DebugAppView.detectChanges (D:\\ng\\puppy-love-io\\node_modules\\@angular\\core\\src\\linker\\view.js:289:44)\n    at DebugAppView.AppView.detectContentChildrenChanges (D:\\ng\\puppy-love-io\\node_modules\\@angular\\core\\src\\linker\\view.js:215:37)\n    at DebugAppView._View_PuppyLoveIoAppComponent0.detectChangesInternal (PuppyLoveIoAppComponent.template.js:252:8)\n    at DebugAppView.AppView.detectChanges (D:\\ng\\puppy-love-io\\node_modules\\@angular\\core\\src\\linker\\view.js:200:14)',
  _context: 
   DebugContext {
     _view: 
      DebugAppView {
        clazz: [Function: _View_PuppyLoveIoAppComponent5],
        componentType: [Object],
        type: 2,
        viewUtils: [Object],
        parentInjector: [Object],
        declarationAppElement: [Object],
        cdMode: 2,
        contentChildren: [],
        viewChildren: [Object],
        viewContainerElement: [Object],
        cdState: 2,
        destroyed: false,
        ref: [Object],
        renderer: [Object],
        staticNodeDebugInfos: [Object],
        _currentDebugContext: null,
        context: {},
        _hasExternalHostElement: false,
        projectableNodes: [],
        _el_0: [Object],
        _appEl_0: [Object],
        _MdProgressCircle_0_4: [Object],
        _expr_0: {},
        _expr_1: {},
        _expr_2: {},
        rootNodesOrAppElements: [Object],
        allNodes: [Object],
        disposables: [],
        subscriptions: [] },
     _nodeIndex: 0,
     _tplRow: 24,
     _tplCol: 37 },
  _wrapperStack: 'Error: Error in D:\\ng\\puppy-love-io\\tmp\\broccoli_type_script_compiler-cache_path-tz5FdUvU.tmp\\src\\app\\puppy-love-io.component.js class PuppyLoveIoAppComponent - inline template:24:37\n    at ViewWrappedException.WrappedException [as constructor] (D:\\ng\\puppy-love-io\\node_modules\\@angular\\core\\src\\facade\\exceptions.js:34:31)\n    at new ViewWrappedException (D:\\ng\\puppy-love-io\\node_modules\\@angular\\core\\src\\linker\\exceptions.js:59:16)\n    at DebugAppView._rethrowWithContext (D:\\ng\\puppy-love-io\\node_modules\\@angular\\core\\src\\linker\\view.js:306:23)\n    at DebugAppView.detectChanges (D:\\ng\\puppy-love-io\\node_modules\\@angular\\core\\src\\linker\\view.js:292:18)\n    at DebugAppView.AppView.detectContentChildrenChanges (D:\\ng\\puppy-love-io\\node_modules\\@angular\\core\\src\\linker\\view.js:215:37)\n    at DebugAppView._View_PuppyLoveIoAppComponent0.detectChangesInternal (PuppyLoveIoAppComponent.template.js:252:8)\n    at DebugAppView.AppView.detectChanges (D:\\ng\\puppy-love-io\\node_modules\\@angular\\core\\src\\linker\\view.js:200:14)\n    at DebugAppView.detectChanges (D:\\ng\\puppy-love-io\\node_modules\\@angular\\core\\src\\linker\\view.js:289:44)\n    at DebugAppView.AppView.detectViewChildrenChanges (D:\\ng\\puppy-love-io\\node_modules\\@angular\\core\\src\\linker\\view.js:220:34)\n    at DebugAppView.AppView.detectChangesInternal (D:\\ng\\puppy-love-io\\node_modules\\@angular\\core\\src\\linker\\view.js:211:14)' }

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

The broccoli plugin was instantiated at: 
    at AppShellPlugin.Plugin (D:\ng\puppy-love-io\node_modules\angular2-broccoli-prerender\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at AppShellPlugin.CachingWriter [as constructor] (D:\ng\puppy-love-io\node_modules\angular2-broccoli-prerender\node_modules\broccoli-caching-writer\index.js:21:10)
    at new AppShellPlugin (D:\ng\puppy-love-io\node_modules\angular2-broccoli-prerender\dist\prerender.js:15:16)
    at Angular2App._buildTree (D:\ng\puppy-love-io\node_modules\angular-cli\lib\broccoli\angular2-app.js:153:48)
    at new Angular2App (D:\ng\puppy-love-io\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (D:\ng\puppy-love-io\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (D:\ng\puppy-love-io\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (D:\ng\puppy-love-io\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (D:\ng\puppy-love-io\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (D:\ng\puppy-love-io\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\serve.js:15:19)
    at D:\ng\puppy-love-io\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (D:\ng\puppy-love-io\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\ng\puppy-love-io\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\ng\puppy-love-io\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\ng\puppy-love-io\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
```

#### Which versions of Angular, Material, OS, browsers are affected?

angular-cli: 1.0.0-beta.6
node: 4.4.2
os: win32 x64

```
{
  "name": "puppy-love-io",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng server",
    "postinstall": "typings install",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "3.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "@angular2-material/button": "^2.0.0-alpha.5-2",
    "@angular2-material/card": "^2.0.0-alpha.5-2",
    "@angular2-material/core": "^2.0.0-alpha.5-2",
    "@angular2-material/icon": "^2.0.0-alpha.5-2",
    "@angular2-material/input": "^2.0.0-alpha.5-2",
    "@angular2-material/list": "^2.0.0-alpha.5-2",
    "@angular2-material/sidenav": "^2.0.0-alpha.5-2",
    "@angular2-material/toolbar": "^2.0.0-alpha.5-2",
    "@angular2-material/progress-circle": "^2.0.0-alpha.5-2",
    "@angular2-material/progress-bar": "^2.0.0-alpha.5-2",
    "angularfire2": "2.0.0-beta.0",
    "firebase": "2.4.2",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "^0.6.12"
  },

  "devDependencies": {
    "@angular/platform-server": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "@angular/service-worker": "^0.2.0",
    "@angular/app-shell": "^0.0.0",
    "angular2-broccoli-prerender": "^0.11.0",
    "angular2-universal": "0.100.0",
    "angular2-universal-polyfills": "^0.4.1",
    "preboot": "^2.0.10",
    "angular-cli": "^1.0.0-beta.5",
    "codelyzer": "0.0.19",
    "ember-cli-inject-live-reload": "^1.4.0",
    "jasmine-core": "^2.4.1",
    "jasmine-spec-reporter": "^2.4.0",
    "karma": "^0.13.15",
    "karma-chrome-launcher": "^0.2.3",
    "karma-jasmine": "^0.3.8",
    "protractor": "^3.3.0",
    "ts-node": "^0.5.5",
    "tslint": "^3.6.0",
    "typescript": "^1.8.10",
    "typings": "^0.8.1"
  }
}
```

**Comment by jelbourn** [comment] 2016-06-16 15:27
I'm assuming you're doing server-side pre-rendering with Angular Universal? That is generally important to know.

Sounds like a dupe of #459

**Closed by jelbourn** 2016-06-16 15:27 UTC
