### ISSUE TITLE
Input looks ready for input but does not have curosr

### ISSUE THREAD

**Issue by ricardosaracino** [angular/material2#15093] opened 2019-02-05 20:19 UTC
#### What is the expected behavior?
Cursor is in the input and its focused

#### What is the current behavior?
element is not accepting input
![image](https://user-images.githubusercontent.com/759253/52301771-39cbda80-2959-11e9-8ac1-8b0446445b4e.png)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/animations": "^7.2.3",
    "@angular/cdk": "^7.3.0",
    "@angular/common": "^7.2.3",
    "@angular/compiler": "^7.2.3",
    "@angular/core": "^7.2.3",
    "@angular/flex-layout": "^7.0.0-beta.23",
    "@angular/forms": "^7.2.3",
    "@angular/material": "^7.3.0",
    "typescript": "3.1.6"

    IE 11.2724

**Comment by ricardosaracino** [comment] 2019-02-06 01:48
Got it reproduced with minimal code
https://github.com/ricardosaracino/angular7-ie-issue

**Comment by macjohnny** [comment] 2019-02-07 07:14
@ricardosaracino Here is your example, working on stackblitz:
https://stackblitz.com/edit/github-nlkqcg?file=src%2Fapp%2Fcomponents%2Flogin%2Flogin.component.html
The issue occurs when exactly clicking the bottom line of the input.
![image](https://user-images.githubusercontent.com/5589029/52395873-f6d04b00-2aaf-11e9-850c-c31afa7e3b67.png)

![image](https://user-images.githubusercontent.com/5589029/52395759-9a6d2b80-2aaf-11e9-88c8-881e557e1df0.png)

Here is a minimal example: https://stackblitz.com/edit/angular-material2-issue-me7v5p?file=app/app.component.html
However, I was not able to reproduce the issue with the minimal example.

**Comment by macjohnny** [comment] 2019-02-08 11:32
@ricardosaracino the issue only occurs if the `placeholder` attribute is set in the input.
As a workaround until https://github.com/angular/material2/pull/15108 is merged, you can add the following css to your global styles
```css
/* workaround for https://github.com/angular/material2/issues/15093 */
:-ms-input-placeholder.mat-input-element {
  -ms-user-select: text !important;
}
```
See the working example here: https://angular-material2-issue-lznbpw.stackblitz.io
(https://stackblitz.com/edit/angular-material2-issue-lznbpw?file=styles.scss)

**Closed** 2019-02-12 15:27 UTC
Labels: P4, has pr, help wanted, ie11
