### ISSUE TITLE
[MatCheckbox] value should of type any instead of string

### ISSUE THREAD

**Issue by RelikDream** [angular/material2#10087] opened 2018-02-22 15:03 UTC
#### Bug, feature request, or proposal:

Proposal

#### What is the expected behavior?

value attribute in matCheckbox component should be declared accepting any type.

#### What is the current behavior?

value attribute in matCheckbox component is declared accepting only string type.

#### What is the use-case or motivation for changing an existing behavior?

basic angular checkbox accept any type as value.

**Comment by josephperrott** [comment] 2018-02-22 15:20
Closing as this is working as intended.  The value is a string because this is the type that is used in the underlying HTML checkbox.

**Closed by josephperrott** 2018-02-22 15:20 UTC

**Comment by GMaxera** [comment] 2018-11-13 21:09
@josephperrott @RelikDream 
I think this should be reopened because there is a clear inconsistency.

The MatRadioButton accepts as value any, while MatCheckbox accepts only string.
