### ISSUE TITLE
checkbox ID has increment BUG

### ISSUE THREAD

**Issue by nhhockeyplayer** [angular/material2#15602] opened 2019-03-25 22:51 UTC
#### What is the expected behavior?
when click checkbox it gets checked

#### What is the current behavior?
when click checkbox the next adjacent checkbox gets checked

#### What are the steps to reproduce?
sorry no repo

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular CLI: 7.3.6
Node: 8.12.0
OS: win32 x64
Angular: 7.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.6
@angular-devkit/build-angular     0.13.6
@angular-devkit/build-optimizer   0.13.6
@angular-devkit/build-webpack     0.13.6
@angular-devkit/core              7.3.6
@angular-devkit/schematics        7.3.6
@angular/cdk                      7.3.5
@angular/cli                      7.3.6
@angular/flex-layout              7.0.0-beta.19
@angular/material                 7.3.5
@ngtools/webpack                  7.3.6
@schematics/angular               7.3.6
@schematics/update                0.13.6
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
```

#### Is there anything else we should know?
its been in the code for past year

I have bit the bullet to isolate it finally

after chomping on inputs [ngModel] and [checked]
and crafting all the ways of doing ID's

I omitted all

and allowed material 2 to generate its own ID

and when I align my bitset of bits to retain state of all my checkboxes
the bitset reflects 0..n checkboxes fines and state is retained check and uncheck

but the markup is NOT being checked by material

I figured ID's generated for each checkbox would start with indice 0

to align with my bitset 0..10

only to find someone coded material to generate internal ID's

so when I check my checkbox 0 of 0..10

id's internally are generated mat-checkbox-1, mat-checkbox-2, mat-checkbox-3, ... N

and everytime I check my first checkbox

the subsequent next checkbox is the one being checked on my user interface component template

if someone could fix this

I do not have a workaround for am working on trying that now but have not gotten a workaround

refer to code like this in material

  private _uniqueId: string = `mat-checkbox-${++nextUniqueId}`;

either they are not considering indice 0
or they are pre-incrementing it errantly on the active checkbox instance
either way material checkbox not working and im surprised this hasnt been flagged yet
their ID logic IS being operated on internally in order to determine which checkbox gets checked
thats where the fix needs to be performed

a workaround would be appreciated

here are some snippets

```
                <mat-checkbox *ngFor="let bit of bits.getArray(); let i = index"
                              [labelPosition]="'after'"
                              class="example-margin"
                              (change)="onCheck($event)"
                >
                    {{i}}
                </mat-checkbox>
```

**Comment by nhhockeyplayer** [comment] 2019-03-25 23:35
generated markup for id=[i]

<mat-checkbox class="example-margin mat-checkbox mat-accent ng-star-inserted" ng-reflect-id="0" ng-reflect-label-position="after" id="0"><label class="mat-checkbox-layout" for="mat-checkbox-1-input"><div class="mat-checkbox-inner-container"><input class="mat-checkbox-input cdk-visually-hidden" type="checkbox" id="mat-checkbox-1-input" tabindex="0" aria-checked="false"><div class="mat-checkbox-ripple mat-ripple" matripple="" ng-reflect-centered="true" ng-reflect-radius="20" ng-reflect-animation="[object Object]" ng-reflect-disabled="false" ng-reflect-trigger="[object HTMLLabelElement]"><div class="mat-ripple-element mat-checkbox-persistent-ripple"></div></div><div class="mat-checkbox-frame"></div><div class="mat-checkbox-background"><svg xml:space="preserve" class="mat-checkbox-checkmark" focusable="false" version="1.1" viewBox="0 0 24 24"><path class="mat-checkbox-checkmark-path" d="M4.1,12.7 9,17.6 20.3,6.3" fill="none" stroke="white"></path></svg><div class="mat-checkbox-mixedmark"></div></div></div><span class="mat-checkbox-label"><span style="display:none">&nbsp;</span> 0 </span></label></mat-checkbox>


when checked the next checkbox gets checked instead of this one

does  id="mat-checkbox-1-input" have something to do with whats actually being checked ?

in some cases both the one I check gets checked including the one next to it

I choose to operate on id=0 and material chooses id=1 or both

feedback appreciated

**Comment by nhhockeyplayer** [comment] 2019-03-26 00:03
this is my bitset

its being thrown out of state by internal checkbox id 

```
/**
 *  models a set of bits
 */

type BitType = true | false

export class BitSet {
    private _vector: Array<BitType>

    constructor(size: number) {
        this._vector = new Array<BitType>(size + 1)
        this.resetAll()
    }

    resize(newSize: number) {
        this._vector = new Array<BitType>(newSize + 1)
    }

    get(position: number) {
        return this._vector[position]
    }

    set(position: number) {
        this._vector[position] = true
    }

    reset(position: number) {
        this._vector[position] = false
    }

    setAll() {
        for (let i = 0; i < this._vector.length; i++) {
            this._vector[i] = true
        }
    }

    resetAll() {
        for (let i = 0; i < this._vector.length; i++) {
            this._vector[i] = false
        }
    }

    size() {
        return this._vector.length
    }

    getArray() {
        return this._vector
    }

    isClear() {
        for (let i = 0; i < this._vector.length; i++) {
            if (this.get(i)) {
                return false
            }
        }
        return true
    }
}

```

**Comment by nhhockeyplayer** [comment] 2019-03-26 00:08
this attempt to make custom id fails for workaround

material continues to operate its own custom internal id's with a preincrement suspected problem

```
                <mat-checkbox *ngFor="let bit of bits.getArray(); let i = index"
                              [id]="i"
                              [labelPosition]="'after'"
                              class="example-margin"
                              (change)="onCheck($event)"
                >
                    {{i}}
                </mat-checkbox>
```

**Comment by nhhockeyplayer** [comment] 2019-03-26 00:09
here is my oncheck event

```
    onCheck(event) {
        if (event.checked) {
            this.bits.set(event.source.id)
        } else {
            this.bits.reset(event.source.id)
        }
    }
```

**Comment by alquifran** [comment] 2019-03-26 11:29
Try providing a `trackBy `function to the `ngFor`. [https://github.com/angular/angular/issues/18699](url)

**Comment by Eddygn** [comment] 2019-03-26 11:49
well, if you just need a workaround, you can just pass the index:

```
                <mat-checkbox *ngFor="let bit of bits.getArray(); let i = index"
                              [id]="i"
                              [labelPosition]="'after'"
                              class="example-margin"
                              (change)="onCheck($event, i)"
                >
                    {{i}}
                </mat-checkbox>
```

```
    onCheck(event, index) {
        if (event.checked) {
            this.bits.set(index)
        } else {
            this.bits.reset(index)
        }
    }
````

**Comment by nhhockeyplayer** [comment] 2019-03-26 18:36
thanks guys, i will take a look at workaround today and advise results

so at this point we do have a bug?

**Comment by jelbourn** [comment] 2019-03-26 20:13
It's not quite clear to me what you're actually trying to do with the IDs. Are you just trying to differentiate between different checkboxes inside an `ngFor`? If so, using the `ngFor` index is probably going to be the right thing. The ID on the internal `<input>` element is an implementation detail that doesn't officially conform to any particular rules or pattern.

**Comment by nhhockeyplayer** [comment] 2019-03-30 07:08
Im not doing anything with the IDs

I just want the checkboxes to function

my exploration of the IDs is just basically that... to get to the bottom of why the checkboxes are not functioning

maybe a reference issue with the variable?

have you created a demo to see it reproduced?

**Comment by nhhockeyplayer** [comment] 2019-03-30 21:54
ok so trying to embellish the ID to slip into the underlying logic with this workaround

                                [id]="'mat-checkbox-' + i"

seems to produce the KIND of id the underlying internal algorithm wants

produces reasonable orderly IDs

but yet still the check handler is not being invoked

getting close to a workaround

be nice to see patch in next release

**Comment by nhhockeyplayer** [comment] 2019-03-31 00:22
I appreciate the attempt by eddygn

```
If you just need a workaround, you can pass the index:

                <mat-checkbox *ngFor="let bit of bits.getArray(); let i = index"
                              [labelPosition]="'after'"
                              class="example-margin"
                              (change)="onCheck($event, i)"
                >
                    {{i}}
                </mat-checkbox>
    onCheck(event, index) {
        if (event.checked) {
            this.bits.set(index)
        } else {
            this.bits.reset(index)
        }
    }
```

but it failed due to the internal bug and whats dictating what actually is being checked

so when I use this

```
                <mat-checkbox *ngFor="let bit of bits.getArray(); let i = index"

                              [labelPosition]="'after'"
                              class="example-margin"
                              (change)="onCheck($event, i)"
                >
                    {{i}}
                </mat-checkbox>

    onCheck(event, i) {
        const splitUp = event.source.id.split('-')

        if (event.checked) {
            this.bits.set(i)
        } else {
            this.bits.reset(i)
        }
}
```

i see the original bug... the next adjacent checkbox gets checked

**Comment by Eddygn** [comment] 2019-03-31 01:15
I didn't understand the issue correctly, trackBy will solve it:

https://stackblitz.com/edit/angular-material2-checkbox-7-0-2?file=app%2Fapp.component.html

As I understand it, ngFor recreates the checkboxes on each change, and that will increment the Ids, if the ngmodel / checked inputs supposed to work by Id and be influenced in this way, that I don't know.

**Comment by nhhockeyplayer** [comment] 2019-03-31 01:48
not sure why i cant use banana box here

```
                <mat-checkbox *ngFor="let bit of bits.getArray(); let i = index"
                              [labelPosition]="'after'"
                              (change)="onCheck($event, i)"
                              [(ngModel)]="bits.get(i)"
                              [ngModelOptions]="{standalone: true}"
                >
```

```
Uncaught Error: Template parse errors:
Parser Error: Unexpected token '=' at column 12 in [bits.get(i)=$event] in ng:///...Module/...Component.html@56:30 (""'after'"
                              (change)="onCheck($event, i)"
                              [ERROR ->][(ngModel)]="bits.get(i)"
                              [ngModelOptions]="{standalone: true}"
```

**Comment by nhhockeyplayer** [comment] 2019-03-31 02:05
sorry I havent tried trackBy yet I kept pressing for whats documented.

OK kool... here is my workaorund

```
                <mat-checkbox *ngFor="let bit of bits.getArray(); let i = index; trackBy: trackByFn"
                              [labelPosition]="'after'"
                              (change)="onCheck($event, i)"
                              [(ngModel)]="bits.getArray()[i]"
                >
                    {{i}}
                </mat-checkbox>
```


change handler gets invoked to do added logic great

should this issue remain open for patch or should I close it? Feel free to take over that.

I appreciate the effort

Im kind of dismayed material2 isn't receiving the notoriety is deserves with all it's mobile features and standard foothold. Im seeing government grade corporations committing to primeng which I found to be a bit messy and already been thru several rewrites and buggy. What would compel a government grade corp commit to that framework over material2? ??

anyhow - cheers and 

thank you   : )

**Comment by nhhockeyplayer** [comment] 2019-03-31 02:14
just some more added feedback

Im running on an Intel(R) Core(TM) i7 CPU Q720@1.6Ghz
an intel QuadCore 8gDRAM
8 virtual cpu's

when I click a checkbox Im seeing a 2-3 second latency before the check actually happens

very noticeable

but its good enough for the girl I go out with

**Comment by jelbourn** [comment] 2019-04-01 18:20
Can you share a reproduction on stackblitz?

**Comment by Eddygn** [comment] 2019-04-01 18:24
@jelbourn 

The two bottom examples in the stackblitz I've posted earlier show the issue that happens without trackBy.

**Comment by jelbourn** [comment] 2019-04-01 18:47
Ah, I see; I missed that earlier. AFAICT this is working as expected. If you use `ngFor` to iterate over an array of primitive, `trackBy` is necessary for Angular to be able to differentiate between the items when they change because t defaults to using `===` comparison.

**Closed by jelbourn** 2019-04-01 18:47 UTC
Labels: cannot reproduce
