### ISSUE TITLE
User-friendly Sidenav Behavior

### ISSUE THREAD

**Issue by bradyshutt** [angular/material2#5649] opened 2017-07-10 17:41 UTC
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
A sidenav that behaves in an intuitive, user-friendly way on mobile. See the [**paper-drawer-panel** Polymer Element](https://www.webcomponents.org/element/PolymerElements/paper-drawer-panel/demo/demo/index.html) for an example. Notice how you can
1. Swipe right from the left edge to open the drawer
2. Swipe left to close the drawer
3. These "Swipes" aren't just triggers that open/close the drawer. If the mouse remains clicked (or finger remains on the screen) you are able to "control" the drawer, in a sense. Play around with the Polymer element to see what I mean.  

#### What is the current behavior?
Not ^
1. You cant swipe-right from left edge to open
2. **You can't close with a left swipe**

#### What is the use-case or motivation for changing an existing behavior?
In most native apps, sidebars are controlled with swipes. Users have, I believe, come to expect this behavior. I think the most important point is having the ability to close the sidebar with a swipe. When I want to close an opened sidebar, the first thing I think to do is "push" it away with a swipe.

**Comment by jelbourn** [comment] 2017-08-23 22:25
Duplicate of #5712

**Closed by jelbourn** 2017-08-23 22:25 UTC
