### ISSUE TITLE
backgroundColor attribute from mat-tab-group tag disable default ripple effect of mat-buttons inside mat-tabs tags

### ISSUE THREAD

**Issue by viniciusgouveia** [angular/material2#15270] opened 2019-02-21 18:01 UTC
#### What is the expected behavior?
Ripple effect is activated on button click

#### What is the current behavior?
Rippe effect is not activated on button click

#### What are the steps to reproduce?
StackBlitz starter: https://stackblitz.com/edit/angular-ytvijf<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
* Angular: 7.0.2
* Angular Material: 7.3.1
* OS: Ubuntu 18.04
* Typescript: 3.1.1
* Browsers: Chrome 71

#### Is there anything else we should know?
When open stackblitz, find tab-group-basic-example.html file on /app directory

**Comment by crisbeto** [comment] 2019-02-21 20:00
Closing as a duplicate of https://github.com/angular/material2/issues/14819.

**Closed by crisbeto** 2019-02-21 20:00 UTC
