### ISSUE TITLE
Breakpoint Observer triggers falsy media queries when scaling

### ISSUE THREAD

**Issue by caiusCitiriga** [angular/material2#9565] opened 2018-01-24 11:48 UTC
#### Bug, feature request, or proposal:
[Bug]?

#### What is the expected behavior?
I'd expect to see the very last match when scaling.

#### What is the current behavior?
When enabling the observer and passing the Bootstrap's breakpoints as rules (XL, L, MD, SM, XS) the observer correctly triggers the matches, but when I scale from let's say L to MD, and arrange the array of rules (see plunker) from XL to XS the trigger correctly matches MD. But if I go from MD to L, the trigger first matches L, then MD. 

This thing changes the opposite way if I invert the order of the rules. I wonder if I'm doing something wrong.

#### What are the steps to reproduce?
<p>Unfortunately I was not able to reproduce this on plunker since I don't know how to inject the BreakpointObserver. The code though is fairly simple and I can provide here the code.</p>
<ul>
    <li>Create a service and inject the observer</li>
    <li>Define an array of breakpoints (the order matters)</li>
    <li>Loop each array element and start an observer on that media query/ies</li>
    <li>Whenever a match is found, log it to the console.</li>
</ul>

```
import { Injectable } from '@angular/core';
import { BreakpointObserver } from '@angular/cdk/layout';

import { Subject } from 'rxjs/Subject';


class BreakPoint {
    name: string;
    mediaQuery: string | string[]
}

@Injectable()
export class LayoutService {
    private _$breakpointsChanges: Subject<BreakPoint> = new Subject();  // Don't use a $BS here.
    public $breakpointsChanges = this._$breakpointsChanges.asObservable();

    private breakpoints: BreakPoint[] = [
        {
            name: 'XL',
            mediaQuery: ['(min-width: 1500px)']
        },
        {
            name: 'L',
            mediaQuery: ['(min-width: 1200px)', '(max-width: 1500px)']
        },
        {
            name: 'MD',
            mediaQuery: ['(min-width: 992px)', '(max-width: 1200px)']
        },
        {
            name: 'SM',
            mediaQuery: ['(min-width: 768px)', '(max-width: 992px)']
        },
        {
            name: 'XS',
            mediaQuery: ['(min-width: 400px)', '(max-width: 768px)']
        },
    ]

    constructor(
        private breakpointObserver: BreakpointObserver
    ) {
        this.breakpoints.forEach(bp => {
            this.breakpointObserver.observe(bp.mediaQuery)
                .subscribe(res => {
                    if (res.matches) {
                        this._$breakpointsChanges.next(bp);
                    }
                });
        });
    }
}
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/cdk: 5.1.3,
angular/core: 5.1.3,
typescript: 2.4.2

As I said, I'm not sure that this is a bug. Maybe I'm using the queries in a wrong way. If so, I apologise if I'm making you guys waste your time. But I'd also really love to know where I'm doing wrong. 

Cheers! 
Caius

**Comment by josephperrott** [comment] 2018-01-24 16:31
Closing as this is actually working as expected.  The issue you are seeing is caused by how the media query matcher strings are written.

`'(min-width: 1200px)', '(max-width: 1500px)'` will be matched if either provided query is true, if `width` is `>1200` **OR** `<1500`.  What you are looking for is `>1200` **AND** `<1500`.

Instead of the media query  string should be written as `'(min-width: 1200px) and (max-width: 1500px)'`.

Switching to the corrected "and" logic should work as you expect.

**Closed by josephperrott** 2018-01-24 16:31 UTC

**Comment by caiusCitiriga** [comment] 2018-01-28 16:43
Thank you so much. Of course I was doing it wrong :D Good to know for the next time. Sorry for the falsy bug
