### ISSUE TITLE
Accordion conflict with sidenav (ver. 7+)

### ISSUE THREAD

**Issue by Knoxvillekm** [angular/material2#14267] opened 2018-11-25 21:28 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
Expansion-panel don't open in sidenav by [expanded]="routerLinkActive.isActive", but work fine in other place and in ver. 6+.
After load page can't open expanded panel.
![sidenav](https://user-images.githubusercontent.com/11072464/48984842-b9435f00-f109-11e8-9fbe-f960eac10f80.jpg)

#### What are the steps to reproduce?
StackBlitz: https://stackblitz.com/edit/angular-v2xdki?file=app%2Fexpansion-overview-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.1.0
Material: 7.1.0

**Comment by josephperrott** [comment] 2018-11-26 14:50
Closing as duplicate of #13870

**Closed by josephperrott** 2018-11-26 14:50 UTC
