### ISSUE TITLE
bug? 6.2.0 [Native `<table>` that only applies the Material styles]

### ISSUE THREAD

**Issue by enenxn** [angular/material2#11641] opened 2018-06-04 02:41 UTC
https://material.angular.io/components/table/overview

Native `<table>` that only applies the Material styles

![table bug 1](https://user-images.githubusercontent.com/39892302/40895275-ef7d949e-67e0-11e8-9462-505681000dde.png)

https://stackblitz.com/angular/lpbeykeoood?file=app%2Ftable-native-only-example.ts
![table bug 2](https://user-images.githubusercontent.com/39892302/40895747-c0488712-67e3-11e8-9edb-e68d8be2993b.png)

**Comment by maxencefrenette** [comment] 2018-06-04 17:57
Duplicate of #11442 ?

**Comment by jelbourn** [comment] 2018-06-06 17:50
Duplicate of #11442

**Closed by jelbourn** 2018-06-06 17:50 UTC
