### ISSUE TITLE
Bug: mat-menu issues on scroll

### ISSUE THREAD

**Issue by nazarkryp** [angular/material2#11471] opened 2018-05-23 09:31 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-menu should be sticked to the place whare it was triggered

#### What is the current behavior?
menu jumps when scrollin or moves in oposite direction

#### What are the steps to reproduce?
1. Go to your official docs: https://material.angular.io/components/menu/overview
2. Open menu
![image](https://user-images.githubusercontent.com/23178377/40415865-9205931c-5e84-11e8-8285-3db0b2cc3785.png)
3. Scroll to bottom. (After menu reaches top screen horizon it will jumb to bottom)
![image](https://user-images.githubusercontent.com/23178377/40415941-c71f52f4-5e84-11e8-9bdb-7571ca84e834.png)

#### What is the use-case or motivation for changing an existing behavior?
I think no comments are required here

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 6.0.3
Node: 8.11.1
OS: win32 x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.3
@angular/cdk                      6.1.0
@angular/cli                      6.0.3
@angular/flex-layout              6.0.0-beta.15
@angular/material                 6.1.0
@angular/pwa                      0.6.3
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

#### Is there anything else we should know?
You can reproduce it using google chrome developer tools just by toggling device toolbar (Ctrl + Shift + M on windows) 
![image](https://user-images.githubusercontent.com/23178377/40416122-2b3e39da-5e85-11e8-9ccb-657b14606340.png)

**Comment by crisbeto** [comment] 2018-05-23 11:49
Closing as a duplicate of https://github.com/angular/material2/issues/11365.

**Closed by crisbeto** 2018-05-23 11:49 UTC
