### ISSUE TITLE
MdDialog produces dialogs which look completely different to what the spec describes

### ISSUE THREAD

**Issue by pfeigl** [angular/material2#5389] opened 2017-06-28 09:39 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
MdDialogs should look the way they are described in https://material.io/guidelines/components/dialogs.html

Here is a nice Example
<img width="118" alt="components_dialogs_content1" src="https://user-images.githubusercontent.com/237891/27630219-1ec47536-5bf5-11e7-9342-b4d7d58a8caf.png">

- Buttons are right aligned
- Buttons are colored based on theme
- Correct font is used
- Content is "grayish"

#### What is the current behavior?
Here is a Screenshot on how the default dialog looks without special theming
<img width="293" alt="mddialog" src="https://user-images.githubusercontent.com/237891/27630522-0b8fdef0-5bf6-11e7-8bcd-d76844681d6a.png">

#### What are the steps to reproduce?
The HTML code is pretty much taken from the examples of the material2 docs
```
        <h2 md-dialog-title>{{ title }}</h2>
        <md-dialog-content>{{ message }}</md-dialog-content>
        <md-dialog-actions>
            <button type="button" md-button md-dialog-close>Cancel</button>
            <button type="button" md-button [md-dialog-close]="true">OK</button>
        </md-dialog-actions>
```
#### What is the use-case or motivation for changing an existing behavior?
The design spec should be followed

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular4, Material@master, Chrome

**Comment by crisbeto** [comment] 2017-06-28 10:08
Closing as a dupe of https://github.com/angular/material2/issues/2735.

**Closed by crisbeto** 2017-06-28 10:08 UTC
