### ISSUE TITLE
material.angular.io examples doesn't work on stackblits

### ISSUE THREAD

**Issue by arjunkneworld** [angular/material2#10414] opened 2018-03-14 09:49 UTC
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by arjunkneworld** [comment] 2018-03-14 09:50
Error: 
```
Uncaught (in promise) TypeError: Cannot read property 'defaultExtension' of undefined
    at Object.generateConfig (engineblock-c13ba99d8d070fecd8733495ceff2b583767e81295057f9635062c5fe737a0ea.js:3)
    at Object.start (engineblock-c13ba99d8d070fecd8733495ceff2b583767e81295057f9635062c5fe737a0ea.js:3)
    at preview-011e8381add39bb8861c.js:1
```

**Comment by arjunkneworld** [comment] 2018-03-14 09:52
https://gkmvlkvxvam.angular.stackblitz.io/

**Comment by WizardPC** [comment] 2018-03-14 13:39
Which example is it ?

**Comment by arjunkneworld** [comment] 2018-03-14 14:03
We can choose any, ie:-got to https://material.angular.io/components/input/overview > click on Edit in StackBlitz. Here I have taken input control but you can choose any controls and try it on StackBlitz.

**Comment by WizardPC** [comment] 2018-03-14 14:56
![noproblem](https://user-images.githubusercontent.com/11718892/37410141-3e58ab2a-27a0-11e8-836c-52d830a1f887.PNG)

No problem here.. meybe clear your cache, or you have a specific OS/Browser ?

**Comment by jelbourn** [comment] 2018-03-14 16:23
Visit chrome://serviceworker-internals/ and unregister the worker for material.angular.io. This will clear the service worker cache, which persists through hard refresh.

**Comment by tscislo** [comment] 2018-03-18 12:54
I have exactly the same problem with many of my examples, which do not use angular material: https://yqnimbal.github.stackblitz.io/

**Comment by josephperrott** [comment] 2018-03-26 16:01
Closing as we are not able to reproduce this issue anymore.

**Closed by josephperrott** 2018-03-26 16:01 UTC

**Comment by tscislo** [comment] 2018-03-26 16:55
Unfortunately this still does not work:

Uncaught (in promise) TypeError: Cannot read property 'defaultExtension' of undefined
    at Object.generateConfig (engineblock-146c780d9ccd7eca58c9775fadffeb836d7f8b198b9ddefc26cfde20a0cc7c00.js:3)
    at Object.start (engineblock-146c780d9ccd7eca58c9775fadffeb836d7f8b198b9ddefc26cfde20a0cc7c00.js:3)
    at preview-f5308a9ff66bc6021f97.js:1

**Comment by arjunkneworld** [comment] 2018-04-06 12:17
Non of the above methods (cache) worked for me. Looks like something is preventing from my office network and It works fine in my personal network. Thank you all.
