### ISSUE TITLE
mat-accordion does not render correctly when nested in Mat-Tab

### ISSUE THREAD

**Issue by yinghuip** [angular/material2#10151] opened 2018-02-26 09:41 UTC
#### Bug, feature request, or proposal:
mat-accordion does not render correctly when nested in Mat-Tab

#### What is the expected behavior?
Mat-Accordion should render correctly

#### What is the current behavior?
Mat-Accordion in Mat-Tab's tab 2 does not render correctly.
expansion panels in tab 2 are all expanded by default, and the control are not render correctly.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-s3cp3a

#### What is the use-case or motivation for changing an existing behavior?

-

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

material 5.2.2

#### Is there anything else we should know?
-

**Comment by julianobrasil** [comment] 2018-02-26 11:40
Dupe of #5269.

Take a look specifically at https://github.com/angular/material2/issues/5269#issuecomment-365343567

**Comment by josephperrott** [comment] 2018-02-28 15:32
Closing as duplicate of #5269

**Closed by josephperrott** 2018-02-28 15:32 UTC
