### ISSUE TITLE
Feature Request: range slider

### ISSUE THREAD

**Issue by zardilior** [angular/material2#12260] opened 2018-07-18 14:08 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Adding a range slider, two dots, two values min and max and highlighting the space between both dots, made from the regular slider, one dot, single value and highlighting from the start to the dot.

#### What is the current behavior?
The is no range slider only a regular slider.

#### What is the use-case or motivation for changing an existing behavior?
Range Sliders, are used in many modern filters' menus, angular material seeks to provide great out of the box UI elements, adding a range slider, among other more specialized UI elements, only furthers the completion behind angular material's purpose.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
This is beyond my knowledge

#### Is there anything else we should know?
I haven't contributed to open source projects, except a small bug fix, but I want to do this endeavor, seems simple enough basing of the regular slider and it is indeed a feature I need and I prefer to contribute than to seek an alternative.

**Comment by josephperrott** [comment] 2018-07-18 17:05
Closing as duplicate of #1331

**Closed by josephperrott** 2018-07-18 17:05 UTC
