### ISSUE TITLE
MdSelectModule should show selected option when value is 0{number}

### ISSUE THREAD

**Issue by pjir** [angular/material2#5044] opened 2017-06-09 12:14 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should show selected value when you have  zero{number} as value

#### What is the current behavior?
show empty string ""

#### What are the steps to reproduce?
Just set option value to 0 {number} and then past to model 0 to show as default, ngModel value is set but selected option is empty string.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
https://plnkr.co/edit/4HqTJGUHbuL7MRZ7SngX?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.1.1
node: 8.1.0
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.1
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3

**Comment by crisbeto** [comment] 2017-06-09 12:17
Closing as a dupe of https://github.com/angular/material2/issues/4854.

**Closed by crisbeto** 2017-06-09 12:17 UTC
