### ISSUE TITLE
Baseline of mat-icon-button is incorrect

### ISSUE THREAD

**Issue by benelliott** [angular/material2#8218] opened 2017-11-03 16:21 UTC
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

It should be easy to vertically align `mat-icon-button` with other elements.

#### What is the current behavior?

The baseline seems a little off.

#### What are the steps to reproduce?

See demo: https://stackblitz.com/edit/angular-material2-issue-3sbo9e?file=app/app.component.ts

1) The icon inside the "add" button is visibly not aligned with the checkbox text or the span text.
2) The icon content of the rotating "sync" button looks a little goofy because it is not vertically centred within the button.

#### What is the use-case or motivation for changing an existing behavior?

Aesthetics

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Latest StackBlitz (can also reproduce on plunkr), Angular 4.4.3, Material beta 12, Chrome 61.0

#### Is there anything else we should know?

No

**Comment by wolfhoundjesse** [comment] 2017-11-20 21:00
Referencing [this issue](https://github.com/google/material-design-icons/issues/206) in case they are related.

**Comment by josephperrott** [comment] 2018-06-28 21:16
Closing as duplicate of #8842

**Closed by josephperrott** 2018-06-28 21:16 UTC
Labels: has pr
