### ISSUE TITLE
Accordion toggle icon not animating

### ISSUE THREAD

**Issue by oxxa** [angular/material2#9843] opened 2018-02-08 15:08 UTC
#### Bug, feature request, or proposal:
`mat-accordion` used to show a rotation animation when the element expanded/collapsed.  It now seems to flip - with no transition - between up and down.

#### What is the expected behavior?
This stackblitz shows it working as it used to https://stackblitz.com/edit/expansion-panel-genvzr

#### What is the current behavior?

This shows it not showing an animation in the **toggle icon** https://stackblitz.com/edit/expansion-panel-pnkxcf

#### What are the steps to reproduce?

Use the mat-accordion with any version of `@angular/animations >= 5.0.3` .   Version 5.0.2 and below seems to work (this is the only difference between the two stackblitz examples above).

#### What is the use-case or motivation for changing an existing behavior?
The control looks less professional without the animation and surely must be down to a regression rather than an intentional change?

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular >= 5.0.3

#### Is there anything else we should know?
Just incase I'm not clear it is the highlighted element which does not show a rotation animation as it once did.
![image](https://user-images.githubusercontent.com/20371749/35979967-765a2db6-0ce1-11e8-83c2-f1dca15894b9.png)

**Comment by crisbeto** [comment] 2018-02-08 17:55
Closing as a duplicate of https://github.com/angular/material2/issues/8814.

**Closed by crisbeto** 2018-02-08 17:55 UTC

**Comment by oxxa** [comment] 2018-02-08 18:09
Hi @crisbeto , I had just found https://github.com/angular/angular/issues/20652 and adding the query solves it as you have said already in #8814 .  So can I ask if your PR is likely going to make it into a release soon or am I better to patch myself for the moment do you think?

**Comment by crisbeto** [comment] 2018-02-08 20:39
I can't guarantee when it would be merged/released. We have presubmit process that every PR goes through before it can be merged, which can take a while.
