### ISSUE TITLE
datetime picker

### ISSUE THREAD

**Issue by Masber** [angular/material2#6219] opened 2017-08-02 11:56 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
to have the possibility to choose date and time under same input element

#### What is the current behavior?
chosing date is the only option

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by willshowell** [comment] 2017-08-02 12:08
Duplicate of https://github.com/angular/material2/issues/5648

**Comment by jelbourn** [comment] 2017-08-03 23:54
Duplicate of #5648

**Closed by jelbourn** 2017-08-03 23:54 UTC

**Comment by torabian** [comment] 2018-11-23 11:05
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
