### ISSUE TITLE
Warning on 'ng build --configuration=omegagroup-out --prod'

### ISSUE THREAD

**Issue by ciukstar** [angular/material2#11851] opened 2018-06-20 08:48 UTC
#### Bug, feature request, or proposal:
Bug after upgrade to 6.3.0

#### What is the expected behavior?
No warnings at build time and no errors at runtime

#### What is the current behavior?
Warnings at build time and errors at runtime

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
`Angular CLI: 6.0.8
Node: 10.0.0
OS: linux x64
Angular: 6.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.3.0
@angular/cli                      6.0.8
@angular/material                 6.3.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3`

#### Is there anything else we should know?
`sergiu@ub:arm-analytics-spb$ ng build --configuration=omegagroup-out --prod
                                                                                          
Date: 2018-06-20T08:27:34.018Z
Hash: 41cc78c2fbd72bc9a082
Time: 86105ms
chunk {scripts} scripts.3613918a255749f9ea9f.js (scripts) 1.27 MB  [rendered]
chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.832187a1f5d1bc23b69b.css (styles) 406 kB [initial] [rendered]
chunk {2} polyfills.2f03b40eca31d170c7bf.js (polyfills) 59.6 kB [initial] [rendered]
chunk {3} main.2fac4263a9a892dd6e31.js (main) 6.09 MB [initial] [rendered]

WARNING in ./src/app/home/topbar/topbar.component.ngfactory.js
106:1111-1119 "export 'ɵf23' (imported as 'i13') was not found in '@angular/material/menu'

WARNING in ./src/app/home/content/map/map.component.ngfactory.js
113:162-169 "export 'ɵf23' (imported as 'i4') was not found in '@angular/material/menu'

WARNING in ./src/app/home/topbar/topbar.component.ngfactory.js
117:166-174 "export 'ɵf23' (imported as 'i13') was not found in '@angular/material/menu'

WARNING in ./src/app/home/content/echart/echart.component.ngfactory.js
128:1148-1156 "export 'ɵf23' (imported as 'i11') was not found in '@angular/material/menu'

WARNING in ./src/app/home/topbar/topbar.component.ngfactory.js
128:166-174 "export 'ɵf23' (imported as 'i13') was not found in '@angular/material/menu'

WARNING in ./src/app/home/content/map/map.component.ngfactory.js
129:162-169 "export 'ɵf23' (imported as 'i4') was not found in '@angular/material/menu'

WARNING in ./src/app/home/topbar/topbar.component.ngfactory.js
139:166-174 "export 'ɵf23' (imported as 'i13') was not found in '@angular/material/menu'

WARNING in ./src/app/home/content/echart/echart.component.ngfactory.js
143:166-174 "export 'ɵf23' (imported as 'i11') was not found in '@angular/material/menu'

WARNING in ./src/app/home/content/map/map.component.ngfactory.js
145:162-169 "export 'ɵf23' (imported as 'i4') was not found in '@angular/material/menu'

WARNING in ./src/app/home/topbar/topbar.component.ngfactory.js
154:166-174 "export 'ɵf23' (imported as 'i13') was not found in '@angular/material/menu'

WARNING in ./src/app/home/content/map/map.component.ngfactory.js
161:162-169 "export 'ɵf23' (imported as 'i4') was not found in '@angular/material/menu'

WARNING in ./src/app/home/content/echart/echart.component.ngfactory.js
170:166-174 "export 'ɵf23' (imported as 'i11') was not found in '@angular/material/menu'

WARNING in ./src/app/home/content/map/map.component.ngfactory.js
172:162-169 "export 'ɵf23' (imported as 'i4') was not found in '@angular/material/menu'

WARNING in ./node_modules/@angular/material/menu/typings/index.ngfactory.js
20:694-701 "export 'ɵd23' (imported as 'i1') was not found in '@angular/material/menu'

WARNING in ./src/app/home/content/echart/echart.component.ngfactory.js
233:166-174 "export 'ɵf23' (imported as 'i11') was not found in '@angular/material/menu'

WARNING in ./src/app/app.module.ngfactory.js
235:6377-6385 "export 'ɵd23' (imported as 'i64') was not found in '@angular/material/menu'

WARNING in ./src/app/home/content/echart/echart.component.ngfactory.js
272:167-175 "export 'ɵf23' (imported as 'i11') was not found in '@angular/material/menu'

WARNING in ./src/app/home/content/echart/echart.component.ngfactory.js
311:167-175 "export 'ɵf23' (imported as 'i11') was not found in '@angular/material/menu'

WARNING in ./src/app/home/content/echart/echart.component.ngfactory.js
350:167-175 "export 'ɵf23' (imported as 'i11') was not found in '@angular/material/menu'

WARNING in ./src/app/home/content/echart/echart.component.ngfactory.js
421:167-175 "export 'ɵf23' (imported as 'i11') was not found in '@angular/material/menu'

WARNING in ./src/app/home/content/echart/echart.component.ngfactory.js
432:167-175 "export 'ɵf23' (imported as 'i11') was not found in '@angular/material/menu'

WARNING in ./node_modules/@angular/material/menu/typings/index.ngfactory.js
49:191-198 "export 'ɵf23' (imported as 'i1') was not found in '@angular/material/menu'

WARNING in ./node_modules/@angular/material/menu/typings/index.ngfactory.js
68:152-159 "export 'ɵf23' (imported as 'i1') was not found in '@angular/material/menu'

WARNING in ./src/app/home/content/map/map.component.ngfactory.js
97:745-752 "export 'ɵf23' (imported as 'i4') was not found in '@angular/material/menu'`

**Comment by a616101** [comment] 2018-06-22 09:17
I have the same problem.
Can anyone help?

**Comment by josephperrott** [comment] 2018-06-25 15:25
Closing as duplicate of #11844, this looks to be caused by an issue with build optimizer

**Closed by josephperrott** 2018-06-25 15:25 UTC
