### ISSUE TITLE
Dynamic columns in Grid List

### ISSUE THREAD

**Issue by Exertive** [angular/material2#3844] opened 2017-03-30 09:37 UTC
#### Bug, feature request, or proposal:

Feature:
Have the number of columns in a GridList component change in response
to significant changes to screen/browser dimensions.

#### What is the use-case or motivation for changing an existing behavior?

While it is relatively straight-forward to determine the initial number of
columns that is optimal for displaying a Gridlist component on the current
device/browser. It is much more difficult to respond to signficant changes
in media size.

#### Is there anything else we should know?

I am already looking into this. If successful, I would be happy to share.

David Aspinall

**Comment by dahaupt** [comment] 2017-03-30 19:20
@Exertive You should probably have a look at [@angular/flex-layout](https://github.com/angular/flex-layout).

**Comment by Exertive** [comment] 2017-04-07 13:38
Thanks dahaupt. That is what I am now doing. It serves my purpose perfectly.

**Comment by jelbourn** [comment] 2017-05-01 23:03
Dupe of #1072 which we do plan to support eventually

**Closed by jelbourn** 2017-05-01 23:03 UTC
