### ISSUE TITLE
md-select doesn't line up (same height) as input

### ISSUE THREAD

**Issue by pauldaustin** [angular/material2#3627] opened 2017-03-15 21:45 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Input and Select when on the same row (flex layout) should have the same height to be visually appealing

#### What is the current behavior?
The select is a little taller and the ____ is 1 pixel lower

#### What are the steps to reproduce?

See the following in Chrome or Safari
https://plnkr.co/edit/jGB0EoMEWkQ5RZ8X29wz?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Visual consistency

#### Which versions of Angular, Material, OS, browsers are affected?
* Angular 2.4.8
* Material 2.0.0-beta.2
* Mac OSX (10.12.3)
* Safari (10.0.3)
* Chrome (57.0.2987.98)

**Comment by jmcgoldrick** [comment] 2017-03-16 05:23
See #2124 fix coming soon I hope

**Comment by jelbourn** [comment] 2017-03-16 23:16
Dupe of #2124

**Closed by jelbourn** 2017-03-16 23:16 UTC
