### ISSUE TITLE
md-chip Element not responding to color attribute.

### ISSUE THREAD

**Issue by martis347** [angular/material2#7337] opened 2017-09-26 18:10 UTC
#### Bug, feature request, or proposal:
Currently, md-chip component is always displayed as gray (color: "none") even though "primary" or "accent" color gets picked.

#### What is the expected behavior?
For md-chip element to change color accordingly to given "color" attribute.

#### What is the current behavior?
md-chip element always displayed as without color preset.

#### What are the steps to reproduce?
This can be even seen in the official docs:  [link](https://material.angular.io/components/chips/overview)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested with Chrome v61

#### Screenshot
![image](https://user-images.githubusercontent.com/10206279/30876336-00d245c0-a2ff-11e7-82fc-978c878df418.png)

**Comment by josephperrott** [comment] 2017-09-26 18:44
closing as duplicate of: #7261

**Closed by josephperrott** 2017-09-26 18:44 UTC
