### ISSUE TITLE
md-select: selected option not removed when ngModel updates

### ISSUE THREAD

**Issue by negberts** [angular/material2#2232] opened 2016-12-15 07:31 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When the options are updated and the selected option is no longer available the selected option should be cleared. 
When using enter to open the Md-Select options there should be no error

#### What is the current behavior?
The selected option is hold on to, although NgModel is null and the options no longer has the selected option available.

After that, when opening the Md-Select options dialog an error occurs: 'unable to get property focus of undefined or null reference'

#### What are the steps to reproduce?

http://plnkr.co/edit/USEs6VII79YJA7dnh31g?p=preview

Steps:
1. Choose option 1 on first select: selectedValue1 = 1
2. Choose option 2 on second select: selectedValue2 = 2
3. Choose option 2 on first select: selectedValue1 = 2, selectedValue2 = null
4. Option 2 remains 'selected' on second select 

#### Is there anything else we should know?
Callstack:

"TypeError: Unable to get property 'focus' of undefined or null reference
   at ListKeyManager.prototype.setFocus (eval code:4573:9)
   at MdSelect.prototype._focusCorrectOption (eval code:5106:13)
   at MdSelect.prototype._onPanelDone (eval code:5007:13)
   at View_MdSelect2.prototype.handleEvent_1 (Function code:459:5)

**Comment by negberts** [comment] 2016-12-16 09:02
Forgot to save the plunker :)

**Comment by crisbeto** [comment] 2016-12-18 11:13
@negberts I could reproduce it in your Plunkr, but not by running `master` locally. It might be worth to update to the latest version of Material or to wait for the next release.

**Comment by kara** [comment] 2016-12-20 07:43
@negberts This looks like a duplicate of https://github.com/angular/material2/issues/2109. Should have been fixed already in https://github.com/angular/material2/pull/2110, but it's only in master and not the released version.

**Closed by kara** 2016-12-20 07:43 UTC

**Comment by negberts** [comment] 2016-12-20 07:52
Okay, thank you :)
