### ISSUE TITLE
feat-req(table): row hover on desktop

### ISSUE THREAD

**Issue by TheRedD0t** [angular/material2#8204] opened 2017-11-03 10:43 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
If the used device is a desktop device, each row of the data table should have a background on hover:

![](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B3mOPoJlxiFhUDEyWVZTVDJCMHM/components-datatables-interaction-rowhover.png)

Display a background in a table row if a user hovers over any part of that row. If there are separate hover states on individual table cells, display both the hover state of the cell and row at the same time.

**Hover background**
- Grey 200 (#EEEEEE)

https://material.io/guidelines/components/data-tables.html#data-tables-interaction

**Comment by donroyco** [comment] 2017-11-03 11:09
Have you checked #6202?

**Comment by willshowell** [comment] 2017-11-03 12:55
@donroyco I dunno if it's clear from that issue whether there's a canonical issue tracking hover styles.

Or maybe it simply falls under https://github.com/angular/material2/issues/5889?

**Comment by TheRedD0t** [comment] 2017-11-03 15:47
> Have you checked #6202?

Nah, i didn't see that becuz it's closed. :\

But simply adding a `:hover` state to `.mat-row` would close this issue. 😕

**Comment by jelbourn** [comment] 2017-11-03 22:22
I'm leaning towards saying that it's best for users to add their own `:hover` state since it avoids us adding something that won't fit all use-cases. @andrewseguin thoughts?

**Comment by dhniels** [comment] 2018-02-07 19:31
Following this as well. I suppose adding our own :hover styles works, though I'm always in favor of built-in solutions for stuff like this.

**Comment by danger89** [comment] 2018-03-18 21:04
I also like to see some built-in feature in material2, especially with this checkbox + hover background combi.. :+1:

**Comment by andrewseguin** [comment] 2018-03-27 17:14
This should only be the case if the rows are selectable, which not all uses of `<mat-table>` are. We would like to provide a simple table that includes this use case.

For now, I definitely don't think adding a a CSS `:hover` state is hacking it, especially since the table does not natively know about selection.

Closing this as a duplicate of #5889 which will be such a table that comes with selection built-in

**Closed by andrewseguin** 2018-03-27 17:14 UTC
Labels: P4: minor, discussion, feature

**Comment by ppumkin** [comment] 2018-08-07 13:56
So if I add a light colour in :hover and then change to a dark theme dynamically... the hover wont show any more.

So how do I reuse the hover colour used on other elements? All my buttons, lists have a hover effect, except the table?
