### ISSUE TITLE
implementing cdk drag-and-drop

### ISSUE THREAD

**Issue by richard457** [angular/material2#11905] opened 2018-06-24 04:04 UTC
####proposal:
I would like to implement drag and drop for angular material, user case is google drive drag and drop exactly that but with the flexibility to be used on any two lists of objects.

#### What is the expected behavior?
Provide drag and drop, count of objects to be dropped, emit the object being dropped and extra output events

**Comment by jymdman** [comment] 2018-06-24 06:35
See [#11864](https://github.com/angular/material2/pull/11864)

**Comment by crisbeto** [comment] 2018-06-24 08:16
Closing as a duplicate of https://github.com/angular/material2/issues/8963.

**Closed by crisbeto** 2018-06-24 08:16 UTC
