### ISSUE TITLE
mdTextareaAutosize doesn't work when changing a FormControl instance

### ISSUE THREAD

**Issue by eyalhakim** [angular/material2#5247] opened 2017-06-20 15:07 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When changing the instance of the FormControl bound to the input, the input should resize according to the new value.

#### What is the current behavior?
The input does not resize

#### What are the steps to reproduce?

http://plnkr.co/edit/WJhcpwRK001maYYnu8AK?p=preview

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by jelbourn** [comment] 2017-06-20 23:12
Dupe of #4657

**Comment by eyalhakim** [comment] 2017-06-20 23:20
@jelbourn i saw this issue, but this one is about template-driven forms and mine is about reactive forms.

**Comment by jelbourn** [comment] 2017-06-21 00:01
I believe it's the same underlying cause

**Comment by eyalhakim** [comment] 2017-06-21 00:28
@jelbourn I see that it has been opened for more than a month. Do you guys have any plans on fixing it?

It's not just a minor bug since it misleads the user to think there is only one row of text whereas the rest is hidden.

**Comment by willshowell** [comment] 2017-06-21 02:14
@eyalhakim here is an example of a workaround until it is fixed

http://plnkr.co/edit/gdZ6jOmQyzj2gg7ori44?p=preview

**Comment by eyalhakim** [comment] 2017-06-21 09:35
@willshowell Thank you very much!
Can you show me how this would look like if i have more then one text area in my component?

**Comment by eyalhakim** [comment] 2017-06-21 11:48
@willshowell also, this doesn't work well when changing the entire form group like in my example.

**Comment by eyalhakim** [comment] 2017-06-23 09:10
@willshowell Thanks again!
The question is, when should i call it?

If i do so immediately after instantiating the FormGroup, it doesn't work because the new value was not bound to the input yet.

The valueChanges event is not called on first value initialization.

Currently, i simply call it after 50ms using setTimeout but that is a very ugly solution.

Do you have a better one?

**Comment by willshowell** [comment] 2017-06-23 13:54
Off the top of my head, another (very lame, not better) solution I could think of would be to use an `Observable.interval` to trigger resizing for all autosize inputs in your template every 50ms.

Alternatively, use the FormGroup api for `addControl`, `removeControl`, `setValue`, etc. instead of reassigning `this.form`. Then you can subscribe to `this.form.valueChanges`...

But really, your best bet is to just wait until until https://github.com/angular/material2/pull/5315 is merged in the next couple days.

**Comment by eyalhakim** [comment] 2017-06-23 14:02
@willshowell perfect, will wait. Thank you!

**Comment by eyalhakim** [comment] 2017-07-11 13:26
@willshowell Hi, i just installed the new version and the issue still exists.
Can you check?

Thanks

**Comment by willshowell** [comment] 2017-07-11 13:44
@eyalhakim Yeah you're right... @jelbourn could you reopen?

This updated plunker demos the original issue with master build

http://plnkr.co/edit/OWA1KW21Y14OxNkF39Br?p=preview

**Comment by eyalhakim** [comment] 2017-07-21 12:11
@jelbourn Hi, was wondering if you have an intention to fix this one soon?

**Comment by eyalhakim** [comment] 2017-07-25 15:12
@willshowell Hi, same question as above?

**Comment by willshowell** [comment] 2017-07-25 15:15
Can't speak for Jeremy, but I'll try to take a look as soon as https://github.com/angular/material2/pull/5692 is merged.

**Closed** 2017-09-01 14:59 UTC
Labels: has pr, P3: important

**Comment by eyalhakim** [comment] 2017-09-09 09:24
@jelbourn Hi! Issue still persist in beta 10. Is the fix part of it?

Thanks

**Comment by willshowell** [comment] 2017-09-09 16:10
@eyalhakim it was merged just after the beta 10 release

Not working with beta 10: http://plnkr.co/edit/roR3rA3GryBk3r4pR1Ro?p=preview
Working with the master build: http://plnkr.co/edit/nqbIJtKcXr7dDDup2A6c?p=preview
