### ISSUE TITLE
Buttons need to be tapped twice in order to fire the click event (iOS)

### ISSUE THREAD

**Issue by binarious** [angular/material2#1316] opened 2016-09-23 18:50 UTC
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

A tap on the button should fire the click event.
#### What is the current behavior?

The first tap highlights the button. The second tap fires the click event.
#### What are the steps to reproduce?

Click on the sidenav icon on an iPhone or iPad: http://material2-test.firebaseapp.com/
#### Which versions of Angular, Material, OS, browsers are affected?
- Angular 2.0.0
- Material Alpha 8-2
- iOS 10.0.1
- Safari

**Comment by spock123** [comment] 2016-09-23 20:07
Does it matter which browser it is? 
As far as I know, Apple doesn't allow for other browser engines on the platform? 

Chrome etc on Ios all render using Webkit under the hood...

**Comment by binarious** [comment] 2016-09-23 20:11
Same with Chrome on iOS.

**Comment by gjoang** [comment] 2016-09-25 22:29
I can confirm the same experience iPhone 6s, IOS 10, Mobile Safari - The first tap highlights the button. The second tap fires the click event.

**Comment by ccarrasc** [comment] 2016-10-07 18:53
I see the same, but only for md-icon-button.

**Comment by ciesielskico** [comment] 2016-10-10 10:10
+1, md-icon-button (sidenav toggle) needs two taps to open the sidenav on Safari, iOS 10, iPad

**Comment by mfodor** [comment] 2016-10-11 08:02
One workaround (maybe a not bad solution) is to have a CSS media query that removes the hover change(s) on mobile devices. In that case there will be no reason for the mobile browsers to fire the hover changes first.

**Comment by sunshineo** [comment] 2016-10-11 16:22
@mfodor How to do that?

**Comment by pcwa-ahendricks** [comment] 2016-10-11 23:31
@sunshineo The following worked me...

Download a build of Modernizr [link to a build](https://modernizr.com/download?touchevents-setclasses-cssclassprefix:mod-).  my `modernizr-config.json` contains:

```javascript
{
  "minify": true,
  "classPrefix": "mod-",
  "options": [
    "setClasses"
  ],
  "feature-detects": [
    "test/touchevents"
  ]
}
```

Then, tell SystemJS or Webpack where to find the generated modernizr.js file.

In my Angular2 component that contains my md-icon-button for my sidenav I define the following SCSS classes.

```scss 
// using Modernizer CSS classes to detect if user has a touchscreen device
:host-context(.mod-touchevents) [md-button]:hover::after, [md-icon-button]:hover::after {
	content: none;
}
```

**Comment by mfodor** [comment] 2016-10-12 06:53
@sunshineo Here is a [Plunkr](http://plnkr.co/edit/PDmOE1CPSLW3jAy9OsNJ?p=preview) showing my idea. It's without having a 3rdparty like modernizr, however, I can encourage you to use that. Also my solution is too simple so it not recognizes whether it's a touch device or just a really narrow window on a PC. So @pcwa-ahendricks 's solution looks much better.

**Comment by ciesielskico** [comment] 2016-10-12 11:42
Found a blog post explaining the issue 
https://css-tricks.com/annoying-mobile-double-tap-link-issue/

**Comment by sunshineo** [comment] 2016-10-12 22:37
Thank you @mfodor . Actually @pcwa-ahendricks 's solution is too complicated for me.
But ultimately, I hope this get fixed ASAP.

**Comment by jimarthurnilsen** [comment] 2016-11-02 14:36
md-raised-button fires on a single click on iOS chrome/safari.
md-icon-button and md-button requires 2 clicks

**Comment by jelbourn** [comment] 2016-11-04 01:25
@crisbeto do you have an iOS device to investigate this?

**Comment by crisbeto** [comment] 2016-11-05 15:47
@jelbourn, as @pcwa-ahendricks mentioned, this is due to the hover effect on the buttons. Touch device trigger the cover styles on the first tap and then do the click handler on the second one. The way I've dealt with this before is similar to @pcwa-ahendricks. We can have a `hover` mixin that we use to register all of the hover styles, e.g. 

```scss
@mixin hover() {
  .md-no-touch &:hover {
    @content;
  }
}

.md-button {
  @include hover {
    // hover styles
  }
}
```

We should keep in mind that this will add some bloat and will increase the specificity on the hover selectors.

**Comment by sunshineo** [comment] 2016-11-06 02:17
@crisbeto Are you saying end user should have these css code? I hope there is a way to make this project just not have this problem on touch device.

**Comment by crisbeto** [comment] 2016-11-06 09:23
Nope, I'm suggesting how we could solve it in Material.

**Comment by jkyoutsey** [comment] 2016-11-08 23:19
I've confirmed that this issue started with iOS 10.  9.3 did not have this problem.

**Comment by sunshineo** [comment] 2016-11-14 00:09
Which version will this fix be in?

**Comment by jkyoutsey** [comment] 2016-11-30 14:13
This does not appear to be fixed in Alpha 10.  Still have to click once to get the highlight, then again to get the click to go through.

**Comment by sunshineo** [comment] 2016-12-17 19:33
Is this really out??

**Comment by MrCroft** [comment] 2016-12-19 16:30
@sunshineo I've just checked, it works just fine now, with "2.0.0-alpha.11-3".
It must have made it with the first alpha.11 release

**Comment by jkyoutsey** [comment] 2017-01-04 21:18
I still have this issue, but oddly, it doesn't stop working until I've hit the button several times.  
First click toggles the icon and opens the nav.  
Second click toggles the icon and closes the nav.  
**Third click does nothing.**  
Fourth click toggles the icon and opens the nav.

**Comment by sunshineo** [comment] 2017-01-16 07:19
I just tried beta 1 and it seems to be working

**Comment by abansal77** [comment] 2017-02-10 11:19
I have latest angular 2. I am still facing this issue. In fact after initial taps, it just does not work. 


`<div fxLayout="row" fxLayoutAlign="center center">
  <div class="flex-item" fxFlex="50" fxLayoutAlign="start start">
    <md-button-toggle-group #group="mdButtonToggleGroup" [(ngModel)]="genderToggle">
      <md-button-toggle value="female" data-tap-disabled="true" checked="true">
        Female
      </md-button-toggle>
      <md-button-toggle data-tap-disabled="true" value="male">
        Male
      </md-button-toggle>
    </md-button-toggle-group>
  </div>
  <div class="flex-item" fxFlex="50" fxLayoutAlign="end center">
    <md-button-toggle-group #group="mdButtonToggleGroup" [(ngModel)]="serviceToggle">
      <md-button-toggle value="services" data-tap-disabled="true"  checked="true">
        Services
      </md-button-toggle>
      <md-button-toggle value="packages" data-tap-disabled="true"  (click)="getPackages()">
        Packages
      </md-button-toggle>
    </md-button-toggle-group>
  </div>
</div>`

**Comment by metavurt** [comment] 2017-02-24 17:58
Still an issue. 
I'm using material 2.0.0-beta.2 and testing on iOS 10.2, in the latest versions of Chrome, Safari, and Firefox for iPhone 6S. (@spock123, you can install any browser you want; it's Microsoft who inhibited their users on the MS phone that you're thinking)

FWIW I am using simply the following:
`
<nav>
    <button md-button md-no-ink routerLink="/about" routerLinkActive="active" [routerLinkActiveOptions]="{exact : true }">
        <md-icon>person</md-icon>
        <div class="caption">about</div>
    </button>
</nav>
`
I have *consistent* behavior, across all browsers on iOS: first-click, I see the hover affect briefly, second-click, works as intended.

Glad this is open again, as it seems to be a recurring theme across many devices. Thanks for all your work, devs who are on this; you are appreciated!

**Comment by jelbourn** [comment] 2017-03-08 17:21
@crisbeto can you investigate whether this still occurs in some cases?

**Comment by crisbeto** [comment] 2017-03-08 19:08
I wasn't able to reproduce it @metavurt. I tried both the exact same HTML as yours (aside from pointing it to a different URL) and one that triggers an alert on tap. Can you post an example of something that doesn't work as expected? [You can use this as a template.](https://goo.gl/DlHd6U)

**Comment by metavurt** [comment] 2017-03-08 23:59
@crisbeto - ah ok, interesting! And yes, I can; I am on west coast, US (GMT -8). I will try my best to post something this evening.

**Comment by mm420admin** [comment] 2017-03-12 18:37
I'm having the same problem with <md-raised-button>. Using 2.0.0-beta.2 in Chrome on iOs 10.2.1 in an angular-cli project.

First click highlights, second click actually clicks. Still trying to fix.

**Comment by metavurt** [comment] 2017-03-12 21:34
I'm building a separate, simple app right now to show test case, and associated build steps for others to test/reproduce. 60 minutes I will post repo and link to live url.

**Comment by metavurt** [comment] 2017-03-12 22:34
@crisbeto - sorry for the delay. I just did a quick build using a brand new -cli initialized base, and adding in bare bones navigation with icons. Just tested in Chrome on iOS 10.1 and the double tap is still necessary to get page(s) to load. First tap shows the overlay, second tap resolves the route.

Also, I just built this without using your suggested template - apologies for that; was just trying to put up something quickly and my personal domain is easy for that.

@mm420admin, thank you for listing which iOS you are using; that helps!

@sunshineo, can you please show us how or what you may or may not have done in order to get it working?

Current top level modules: 
````
├── @angular/cli@1.0.0-rc.1
├── @angular/common@2.4.9
├── @angular/compiler@2.4.9
├── @angular/compiler-cli@2.4.9
├── @angular/core@2.4.9
├── @angular/forms@2.4.9
├── @angular/http@2.4.9
├── @angular/material@2.0.0-beta.2
├── @angular/platform-browser@2.4.9
├── @angular/platform-browser-dynamic@2.4.9
├── @angular/router@3.4.9
├── @types/jasmine@2.5.38
├── @types/node@6.0.65
├── codelyzer@2.0.1
├── core-js@2.4.1
├── jasmine-core@2.5.2
├── jasmine-spec-reporter@3.2.0
├── karma@1.4.1
├── karma-chrome-launcher@2.0.0
├── karma-cli@1.0.1
├── karma-coverage-istanbul-reporter@0.2.3
├── karma-jasmine@1.1.0
├── karma-jasmine-html-reporter@0.2.2
├── protractor@5.1.1
├── rxjs@5.2.0
├── ts-node@2.0.0
├── tslint@4.4.2
├── typescript@2.0.10
└── zone.js@0.7.8
````

### To reproduce
#### Easy way: grab the repo [from here](https://github.com/metavurt/cli-double-click-test), which is visible at [http://www.weo3.com/howdy](http://www.weo3.com/howdy)

Please correct me if I am misusing Material Design. I do recognize that the flat buttons are not necessarily for use with md-icon, **however**, I do not believe this is the reason for the weird double tap necessity on mobile view. FWIW, I use the flat icons because I do not want circular buttons in any part of my apps, and it was easy implementing icons within flat than it was to negate the circular affect.

Let me know if there is anything else I can do to help clarify or test!

**Comment by mm420admin** [comment] 2017-03-13 03:32
I think it has something to do with css :hover::after on some material elements, but I can't seem to work around it.

**Comment by metavurt** [comment] 2017-03-13 04:22
@mm420admin - I did not post this earlier, as I would like to maintain focus on resolving it in the package, but I do have a workaround for you. In this css, (which comes from my testing repository) – 

````
nav .mat-button {
	flex: 1;
	border-radius: 0;
	line-height: 1;
	background: transparent;
}

	nav .mat-button, nav .mat-button:visited {
		color: #369;
	}

	nav .mat-button.active {
		background: #369;
	}

	.mat-button md-icon, .mat-button .caption {
		color: #369;
	}

	.mat-button.active md-icon, .mat-button.active .caption {
		color: #FFF;
	}

	.mat-button .caption {
		font-variant: small-caps;
		font-weight: 400;
	}

	/* the below makes the difference */

	.mat-button-focus-overlay, .mat-button-ripple {
		z-index: -1;
	}

	.mat-button-focus-overlay {
		display: none;
	}
````

– the first batch of code is just styling; but after, "the below makes the difference" it is the ```z-index: -1``` that does the real work. The following ```display:none``` may or may not have any affect.

Being able to use ```z-index``` is due to ```.mat-button-focus-overlay``` and ```.mat-button-ripple``` both being *positioned absolutely*. Setting the value of z-index to -1 places it behind other DOM elements, which block any taps, thereby allowing the button itself to receive the action of tapping, and directing the app to the designated route using a single tap. You can see this working at [weo3.com](http://www.weo3.com).

I hope that helps.

**Comment by mm420admin** [comment] 2017-03-13 05:53
@metavurt your workaround does the trick for now thanks. For anyone else interested, @metavurt's workaround basically just amounted to adding
`.mat-button-focus-overlay, .mat-button-ripple {
		z-index: -1;
	}

	.mat-button-focus-overlay {
		display: none;
	}`

to my main css file.

**Comment by crisbeto** [comment] 2017-03-13 21:38
Thanks for the repro case @metavurt. I still can't reproduce it against our demo app with the exact same styling that you provided, but I can reproduce it by running your example locally. It looks like the `.mat-button-ripple` is not capturing the taps.

**Comment by metavurt** [comment] 2017-03-13 23:02
Awesome, thanks for the feedback, @crisbeto! And derp on me with the ```md-no-ink```; some habits die hard. 😄 

So the [url I provided](http://www.weo3.com/howdy) with the repo live, works for you? I am **very** curious about this, as when I visit that link with my iOS device, the double-tap issue exists.

*If you have time*, could you please let me know if you are able to view the link with no issues; then I think we could say that the behavior would be attached to a particular iOS version, or a particular browser version, rather than the software itself.

**Comment by crisbeto** [comment] 2017-03-14 06:27
What I meant that I see the issue both against your link and the repo that you posted. I'm having a hard time getting it to break when I transfer the same code to the demo app that we use for testing.

**Comment by metavurt** [comment] 2017-03-17 18:53
Thank you @crisbeto for the clarification. That now causes me to ask then, what is in your test environment that fixes it? My repo and link is literally a brand new install using angular-cli, and including material design, and a tiny bit of css styling. That is it, and the issue exists.

Wondering if there is some css in your test environment that fixes it, either directly and with purpose, or indirectly, accidentally, with what appears to be a beneficial outcome.

**Comment by crisbeto** [comment] 2017-03-17 18:58
I'm not exactly sure. I spent some time trying to pinpoint it, a few days ago, with no luck. I'll be looking into it further.

**Comment by crisbeto** [comment] 2017-03-23 21:33
@metavurt I finally managed to reproduce your issue against our demo app. It seems like it happens because you haven't included a theme in your app. [You can check our theming guide on how to do it.](https://github.com/angular/material2/blob/master/guides/theming.md) I'll keep looking to see if I can pinpoint which style fixes the issue and whether we can move it into the button styles.

**Comment by crisbeto** [comment] 2017-03-24 19:36
Closing this, because including the theme is mandatory for other components to work properly, in addition to the button. There's a pending PR that will log a warning if these styles are missing.

**Closed by crisbeto** 2017-03-24 19:36 UTC
Labels: discussion

**Comment by jkyoutsey** [comment] 2017-03-24 19:39
I HAVE a theme!  In fact, I've customized my theme by building custom palettes.  Yet, I still have this issue.  I had this issue using orange primary and amber secondary.  Yep, using themes.  So, that's not the end-all-be-all solution to this problem.

**Comment by crisbeto** [comment] 2017-03-24 19:48
Can you post a Plunkr that shows the issue @jkyoutsey? You can use this as a template: https://goo.gl/DlHd6U.

**Comment by neromotion** [comment] 2017-07-12 02:19
I have to double click on Carousel in IOS device. Any solution for that?
