### ISSUE TITLE
Multiple selection checkboxes in md-table

### ISSUE THREAD

**Issue by pmjacinto** [angular/material2#7288] opened 2017-09-25 09:33 UTC
Hi,

#### Bug, feature request, or proposal:

Any plans to support selection checkboxes in md-table as outlined in the [Material Specification](https://material.io/guidelines/components/data-tables.html#data-tables-structure)?

![components-datatables-structure-basictable](https://user-images.githubusercontent.com/29306657/30801620-cbff1a86-a1db-11e7-9b9c-d2115700dea1.png)

#### What is the expected behavior?

- User would be able to select one or more rows.
- Row selection would trigger an UI change, as outlined in the material specs, sections "Row selection" and "Alternative headers".
- User would be able to select all rows.

![components-datatables-interaction-selectedrow](https://user-images.githubusercontent.com/29306657/30801922-cdad3272-a1dc-11e7-89f0-364418ca121a.png)
![components-datatables-cards-altheaders](https://user-images.githubusercontent.com/29306657/30801928-d0ee059c-a1dc-11e7-8aa5-2b2f01ff82ee.png)

**Comment by willshowell** [comment] 2017-09-25 13:42
There are plans to create a full-featured (and very opinionated) table that includes this:

https://github.com/angular/material2/issues/5889

However, this is all quite possible to implement on your own but putting a checkbox inside a cell. It just isn't yet baked-in.

**Comment by josephperrott** [comment] 2017-09-25 16:39
Closing as duplicate of #5889

**Closed by josephperrott** 2017-09-25 16:39 UTC
