### ISSUE TITLE
mat-select shows placeholder instead of option when ngModel is undefined (REGRESSION)

### ISSUE THREAD

**Issue by thw0rted** [angular/material2#9561] opened 2018-01-24 09:58 UTC
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

`mat-select` should show the `mat-option` with no `[value]` when its `ngModel` is `undefined`.

#### What is the current behavior?

It shows its `placeholder` value instead.

#### What are the steps to reproduce?
Open the [examples tab in the docs](https://material.angular.io/components/select/examples), change "Select with 2-way value binding" to "None".  Resulting control is blank, should show "None".

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 5.0.2, 5.1.0 (at least)

#### Is there anything else we should know?
This definitely used to work, though I'm not sure how long ago it broke.

**Comment by crisbeto** [comment] 2018-01-24 10:16
This is the expected behavior. Closing as a duplicate of https://github.com/angular/material2/issues/7758.

**Closed by crisbeto** 2018-01-24 10:16 UTC
