### ISSUE TITLE
md-icon-sidenav 

### ISSUE THREAD

**Issue by michaeljota** [angular/material2#1937] opened 2016-11-19 23:01 UTC
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?

![](https://material-design.storage.googleapis.com/publish/material_v_9/0B3321sZLoP_HSTd3UFY2aEp2ZDg/components_bottomnavigation_usage2.png)

#### What is the current behavior?

There is a issue with the bottom nav component, #408, but there this behavior it's excluded as is not in the spec of the material component, but as a suggestion.

#### What is the use-case or motivation for changing an existing behavior?

With this, the navigation should be more close to be the same regardless the platform.

**Comment by crisbeto** [comment] 2016-11-20 18:09
Closing as a dupe of https://github.com/angular/material2/issues/1728

**Closed by crisbeto** 2016-11-20 18:09 UTC
