### ISSUE TITLE
Autocomplete not working in iPad

### ISSUE THREAD

**Issue by zijianhuang** [angular/material2#9382] opened 2018-01-14 02:23 UTC
#### Bug:

Autocomplete in an Input is not appearing in iPad and iPhone, while it is working fine in Windows PC and Android phones

#### What is the expected behavior?

When the input has focus, a dropdown should appear.

#### What is the current behavior?

Not dropdown when having focus

#### What are the steps to reproduce?

On iPad or iPhone, browse to https://material.angular.io/components/autocomplete/overview, and test the examples there.

#### Is there anything else we should know?

iPad 2017, iPhone 6+, iOS 11, Safari. Angular 5.2.0, Material 5.0.4

**Comment by MatthieuBarthel** [comment] 2018-01-16 12:49
Additional information: this issue only appears when the input is in the lower part of the screen, the issue looks to be related to the iOS keyboard (when it moves up the input).

**Comment by josephperrott** [comment] 2018-01-16 16:57
closing as duplicate of #6341

**Closed by josephperrott** 2018-01-16 16:57 UTC
