### ISSUE TITLE
Select List Improvements - Add support for selection through Alpha/Numeric keys

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#5653] opened 2017-07-10 19:49 UTC
#### Bug, feature request, or proposal:
In html select list, users can navigate between options by pressing the alpha/numeric keys. For example if a select list has items starting with different alphabets, and on focus user presses key P. The focus is set on the first  list option starting with P. Similarly if we have a list of countries and the user presses P A K keys quickly, one would expect the focus to be set to list item Pakistan. 

#### What is the expected behavior?
Support for navigation through alpha/numeric keys would enhance user experience.

#### What is the current behavior?
There is no support for alpha/numeric keys

#### What are the steps to reproduce?
Visit https://material.angular.io/components/select/overview and set focus on the Favorite food select list, press key P or T, pressing these keys should set focus on the items starting with these letter i.e. Pizza if P key is pressed or Tacos if T key is pressed. But it does nothing.

**Comment by crisbeto** [comment] 2017-07-13 18:30
Closing as a dupe of https://github.com/angular/material2/issues/2668.

**Closed by crisbeto** 2017-07-13 18:30 UTC
