### ISSUE TITLE
Mat-chip selected input is broken

### ISSUE THREAD

**Issue by rubenlagus** [angular/material2#7324] opened 2017-09-26 09:38 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When an *md-chip/mat-chip* is **selected**, class **mat-chip-selected** should be applied

#### What is the current behavior?
**selected** state has no effect

#### What are the steps to reproduce?

See [here](http://plnkr.co/edit/fobuo4RxMfTZmp9gbyTm?p=preview)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Broken in  2.0.0-beta.11 (working in previous Beta)

**Comment by donroyco** [comment] 2017-09-26 10:11
Have you checked #7261?

**Comment by josephperrott** [comment] 2017-09-26 15:34
Closing as duplicate of #7261

**Closed by josephperrott** 2017-09-26 15:34 UTC
