### ISSUE TITLE
Tabs need to support scrolling

### ISSUE THREAD

**Issue by HeavenlyHost** [angular/material2#1243] opened 2016-09-15 09:05 UTC
#### Bug, feature request, or proposal:

Tabs component does not support scrolling
#### What is the expected behavior?

Support scrolling as per the Google Material Design Specs
#### What is the current behavior?

Tabs are cut off if larger than the width of page
#### What are the steps to reproduce?

Place more tabs into tab group than can fit on to page
#### What is the use-case or motivation for changing an existing behavior?

Responsive design
#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2.0.0, Material Alpha 8.1, All Browsers
#### Is there anything else we should know?

No

**Comment by daniele-zurico** [comment] 2016-11-03 09:41
any news on that one?

**Comment by andrewseguin** [comment] 2016-11-03 21:14
Hey Daniele, this has not yet been started as there are some higher priorities in the queue for tabs.

**Comment by andrewseguin** [comment] 2016-11-11 22:33
Duplicate of #769

**Closed by andrewseguin** 2016-11-11 22:33 UTC
