### ISSUE TITLE
[DateTimePicker] What I can do for choose month + year only (e.g. May 2017)

### ISSUE THREAD

**Issue by DE-TriNguyen** [angular/material2#6867] opened 2017-09-06 07:59 UTC
#### Bug, feature request, or proposal:

I read your document about DatePicker and saw about new Support for DatePicker is month + year only (e.g. May 2017). But I can't choose  month + year only. With [startview] = year, I see month show up first, but still choose date after that. 

#### What is the expected behavior?
I just want to choose month + year
#### What is the current behavior?
I can't do that
#### What are the steps to reproduce?
Set [startview] = year

**Comment by willshowell** [comment] 2017-09-06 13:15
See https://github.com/angular/material2/issues/4853

**Comment by josephperrott** [comment] 2017-09-27 16:36
Closing as duplicate of #4853

**Closed by josephperrott** 2017-09-27 16:36 UTC
