### ISSUE TITLE
[bug] chips placeholder overlaps content

### ISSUE THREAD

**Issue by amitport** [angular/material2#7806] opened 2017-10-15 11:17 UTC
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
placeholder should not overlap with content

#### What is the current behavior?
when starting to add content to an **empty** mat-input with mat-child-list. placeholder text overlaps with the added text

#### What are the steps to reproduce?
1) https://stackblitz.com/edit/angular-material2-issue-wpnssn?file=app/app.component.html
2) add text in input

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.4.5
material 2.0.0-beta.12

**Comment by julianobrasil** [comment] 2017-10-15 11:48
Dupe of #7481. Has a PR: #7509.

**Comment by amitport** [comment] 2017-10-15 12:44
@julianobrasil this issue is different (here the problem is overlap, not the disappearing of the placeholder)

Hopefully, the core cause is the same and your PR will solve it, but I suggest not to close this until validated.

**Comment by julianobrasil** [comment] 2017-10-15 19:53
Oh, it's not up to me to keep/close your issue. I'm just a regular Contributor (no powers to close anything) 😄

**Comment by Dumorya** [comment] 2017-10-17 09:02
I had the same problem, and I solved it, the issue came from the CSS. I did a custom CSS file to change the datepicker theme before the beta 12, but I forgot that the beta also changes the CSS haha ^^' So I had to change my CSS file and it works absolutely fine now :) (but I don't know exactely what changes in the CSS created this bug)

**Comment by josephperrott** [comment] 2017-10-31 18:37
Closing as this was addressed by #7509

**Closed by josephperrott** 2017-10-31 18:37 UTC
