### ISSUE TITLE
Examples, Templates, Angular-Cli

### ISSUE THREAD

**Issue by khwerhahn** [angular/material2#6196] opened 2017-08-01 14:29 UTC
#### **Proposal**:
I've been trying to use ng2 and material2 for a new project. Finding examples, boilerplate etc is quite hard. I learn new stuff by trying them out.

#### What is the expected behavior?

1. Examples from famous applications using material design i.e. mail.google.com. Cloning these projects helps to understand material2 (and ng2) much faster.
2. Generating basic layouts via angular-cli would be awesome. Applications tend to follow similar layout patterns.

#### What is the current behavior?
Missing boilerplates, examples etc. 

#### What is the use-case or motivation for changing an existing behavior?

1. Helping people to understand material2 faster
2. Get going much faster

**Comment by donroyco** [comment] 2017-08-01 14:58
As you can read in the project's [readme file](https://github.com/angular/material2/blob/master/README.md) it is part of the current roadmap: 

> *High level stuff planned for Q3 2017 (July - September):*
> As many bug fixes as humanly possible
Additional features for data-table
Continued accessibility improvements
Nested menus
All components are OnPush
**Improved documentation, guides, examples, and navigation on material.angular.io**
Improve library-wide API consistency
Stepper component
Sticky header helper
action-list and selection-list

Next to that, if you fork the Material2 repository and run the demo-app, there are a lot of examples built in which are not available on the [Material Component Library](https://material.angular.io/components).

**Comment by willshowell** [comment] 2017-08-01 15:23
Kind of a duplicate of https://github.com/angular/material2/issues/4976

And maybe https://github.com/EladBezalel/material2-start will help! Keep in mind though that Material is introducing a couple breaking changes each release (still in beta and reorganizing packaging structure), so quickstart guides will likely be outdated.

Also checkout the repo for the docs site https://github.com/angular/material.angular.io

**Comment by ksiabani** [comment] 2017-08-01 15:25
Demo apps are also discussed [here](https://github.com/angular/material2/issues/438)

**Comment by jelbourn** [comment] 2017-08-17 21:34
Closing this as isn't isn't really specific enough to be actionable. We're always working on making our docs better and more comprehensive

**Closed by jelbourn** 2017-08-17 21:34 UTC
