### ISSUE TITLE
[Feature request] Setting the maximum selection size in SelectionModel

### ISSUE THREAD

**Issue by darkbasic** [angular/material2#11733] opened 2018-06-09 17:30 UTC
`SelectionModel` allows you to set the `_multiple` attribute to determine how many items (one or many) you are allowed to select. In some cases, for examples when you want to plot some variables, you may want to allow selecting a certain numbers of rows at most. So instead of being a boolean `_multiple` could be a number, where you can specify how many items you are allowed to select (where 0 stands for unlimited).

**Comment by crisbeto** [comment] 2018-06-09 18:39
What would be the expected behavior if you've hit the maximum and you're trying to add a new item? Would the item not be added, would it remove the first item or would it throw an error?

**Comment by darkbasic** [comment] 2018-06-09 22:08
Ideally I think it should be configurable, but in our own implementation we're fine just dropping the first item.
I was reviewing some code while I noticed that we were not using `SelectionModel`, then I realized that it didn't support our use case. I would love to be able to drop our own code and simply use `SelectionModel`.

**Comment by crisbeto** [comment] 2018-06-10 07:33
I think that making it configurable will add a lot of complexity and choosing one option won't cover all the cases. It should be fairly easy to create your own abstraction on top of `SelectionModel` that adds the necessary functionality:

```ts
export class MaxSelectionModel<T> extends SelectionModel<T> {
  constructor(
    multiple = false,
    initiallySelectedValues?: T[],
    emitChanges = false,
    private _max?: number) {
    super(multiple, initiallySelectedValues, emitChanges);
  }

  select(value: T): void {
    if (this.selected.length === this._max) {
      this.deselect(this.selected[0]);
    }

    super.select(value);
  }
}
```

Closing since this is something that would be difficult to get into the CDK and is easy to implement on your own with the existing APIs.

**Closed by crisbeto** 2018-06-10 07:33 UTC
