### ISSUE TITLE
Child menu support

### ISSUE THREAD

**Issue by counsellorben** [angular/material2#3356] opened 2017-03-01 14:44 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Child menu will open as a flyout from its parent, using existing ConnectedPositionStrategy. The parent menu trigger item will open the child menu, and then stop the event from bubbling to close the parent menu and any ancestors

#### What is the current behavior?
None

#### What are the steps to reproduce?
n/a

#### What is the use-case or motivation for changing an existing behavior?
Child menu support is an important use case for many apps

#### Which versions of Angular, Material, OS, browsers are affected?
n/a

#### Is there anything else we should know?
pull request #3259 contains necessary functionality and tests

**Comment by kara** [comment] 2017-03-01 17:47
Dupe of https://github.com/angular/material2/issues/2961.

**Closed by kara** 2017-03-01 17:47 UTC

**Comment by counsellorben** [comment] 2017-03-01 17:59
I have submitted a pull request addressing the issue. Should I add the PR as a comment to #2961?
