### ISSUE TITLE
These npm links are and will continue to cause massive confusion

### ISSUE THREAD

**Issue by Cogitaria** [angular/material2#3723] opened 2017-03-22 15:49 UTC
#### Bug, feature request, or proposal:

https://www.npmjs.com/~angular2-material

#### What is the expected behavior?

Remove these defunct beta links or at least put some explanatory text warning folks not to use them for new projects. 

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by jelbourn** [comment] 2017-03-24 01:21
Dupe of #2103

**Closed by jelbourn** 2017-03-24 01:21 UTC
