### ISSUE TITLE
Mozilla firefox and Edge mat-menu scroll strategy not working

### ISSUE THREAD

**Issue by olcayusta** [angular/material2#11583] opened 2018-05-30 17:59 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
MatMenu scroll strategy should work properly in **Mozilla Firefox, Edge**
Go, https://material.angular.io/components/menu/overview 
Open a menu and scroll

#### What is the current behavior?
**Mozilla Firefox, Edge** MatMenu Scroll Strategy Not Working

![menubug](https://user-images.githubusercontent.com/24437654/40737278-f30d81c8-6448-11e8-8ede-932c7fac677a.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.2 - material.angular.io version
Browsers: Mozilla Firefox, Edge

**Comment by crisbeto** [comment] 2018-05-30 18:20
Closing as a duplicate of https://github.com/angular/material2/issues/11365.

**Closed by crisbeto** 2018-05-30 18:20 UTC
