### ISSUE TITLE
Variable height cdkDrag in vertical cdkDropList or variable width cdkDrag in horizontal cdkDropList becomes misaligned on sort

### ISSUE THREAD

**Issue by julio-castaneda** [angular/material2#13847] opened 2018-10-28 05:12 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When elements have a variable height/width, expect the placeholder to line up properly after sorting

#### What is the current behavior?
Placeholder element becomes misaligned on sort

#### What are the steps to reproduce?
[https://stackblitz.com/edit/angular-cdk-droplist-variable-height](https://stackblitz.com/edit/angular-cdk-droplist-variable-height)
Drag top element downwards in the list. You'll notice dragging upwards works perfectly.

[https://stackblitz.com/edit/angular-cdk-droplist-variable-width](https://stackblitz.com/edit/angular-cdk-droplist-variable-width)
Drag first element rightwards in the list. You'll notice dragging leftwards works perfectly.

#### What is the use-case or motivation for changing an existing behavior?
N/A

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CDK 7.0.0

#### Is there anything else we should know?
src/cdk/drag-drop/drop-list.ts
Line 266:
`const itemOffset = isHorizontal ? newPosition.left - currentPosition.left :
                                      newPosition.top - currentPosition.top;`
Suggested fix:
`const itemOffset = isHorizontal ? (newPosition.left - currentPosition.left) + (delta === -1 ? (newPosition.width - currentPosition.width) : 0) :
                                      (newPosition.top - currentPosition.top) + (delta === -1 ? (newPosition.height - currentPosition.height) : 0);`

Explanation:
The problem is with the calculation of the currentPosition and newPosition.
When the index of the item changes, the final offset of all moved siblings will be equal to the height of the placeholder. The siblings are always calculated correctly. The issue is with the placeholder. When going UP (delta = 1, currentIndex > newIndex), the calculations will always be correct because the top of the placeholder should move to the top of the element it is swapping with. The issue occurs when going DOWN (delta = -1, currentIndex < newIndex). The placeholder is always moving down with an offset equal to its height. This will cause the placeholder to be too far below an element with a height less than it, and to be overlapping the sibling that comes after. By adding the difference in the height to the difference in position, we arrive at the correct offset. The same concept/fix applies to the horizontal list except the variable is the width.

**Comment by crisbeto** [comment] 2018-10-28 09:36
Duplicate of https://github.com/angular/material2/issues/13483.

**Closed by crisbeto** 2018-10-28 09:36 UTC
