### ISSUE TITLE
sidenav CSS should use will-change: transform

### ISSUE THREAD

**Issue by iuliust** [angular/material2#2494] opened 2017-01-02 12:37 UTC
#### Bug, feature request, or proposal:
Sidenav should use `will-change: transform` in order to remove jank where possible

#### What is the expected behavior?
sidenavs should have their own rendering layer

#### What are the steps to reproduce?
just use a sidenav and look at its CSS properties

#### What is the use-case or motivation for changing an existing behavior?
sidenavs can be laggy on their first animation

#### Which versions of Angular, Material, OS, browsers are affected?
all

**Comment by DevVersion** [comment] 2017-01-02 13:25
There are a lot of recommendations about the use of `will-change`. See [here](https://developer.mozilla.org/de/docs/Web/CSS/will-change)

`will-change` should be only applied if the page is not performing well and shouldn't be used on many elements.

Since we aren't able to figure out if your page is performing well, I would say that developers should apply the `will-change` on their own.

Also the `md-sidenav` should already have its own layer, since it's using `transform3d`

**Comment by crisbeto** [comment] 2017-01-02 15:40
There definitely are some occasional frame drops when opening a sidenav, but I'm not sure that it's because of the `transform`.

**Comment by iuliust** [comment] 2017-01-03 11:56
Yep, I got frame drops too, even with a hello world. Maybe it would go away if I used AOT, although Chrome is supposed to drive animations on a separate process I believe... I had noticed the translateZ(0px), but it's kind of a hack. It's not as explicit as will-change: transform.

I know you're not supposed put tons of separate rendering layers in a page, but we can be almost sure that 99.99% of the time, there will be at most 2 sidenavs. That's just two layers. It's not like if it were 50... No ?

**Comment by DevVersion** [comment] 2017-01-03 11:59
@iuliust That's true. I will take a look at the performance of the sidenav and keep you updated.

**Comment by jelbourn** [comment] 2017-01-04 00:16
If this is something that the user should apply themselves, it should be part of the overview doc.

**Comment by DevVersion** [comment] 2017-01-04 00:18
Yeah good idea. We still need to evaluate whether the `will-change` should be applied by default or not. Thoughts on this @jelbourn?

**Comment by crisbeto** [comment] 2017-01-04 00:20
I'm not sure that the transform is to blame here. It might be better to spend some time investigating it instead.

**Comment by DevVersion** [comment] 2017-01-04 00:22
For sure, `transform3d` should already elevate the `md-sidenav` into its own rendering layer.

**Comment by mmalerba** [comment] 2017-11-22 00:08
The jank was caused by continually setting the width on every change detection, it should be fixed now.

**Closed by mmalerba** 2017-11-22 00:08 UTC
Labels: discussion, feature
