### ISSUE TITLE
md-autocomplete list doesn't stick on it's position when scrolling on iOS

### ISSUE THREAD

**Issue by molcik** [angular/material2#5187] opened 2017-06-17 16:36 UTC
#### What is the expected behavior?
md-autocomplete list should stick on it's position when scrolling on iOS

#### What is the current behavior?
md-autocomplete list doesn't stick on it's position when scrolling on iOS

#### What are the steps to reproduce?
![img_4562](https://user-images.githubusercontent.com/11929953/27254568-0f696690-538b-11e7-8bdb-f8f831e853b0.PNG)
![img_4564](https://user-images.githubusercontent.com/11929953/27254569-0f6d477e-538b-11e7-8843-480d88576e3c.PNG)
![img_4563](https://user-images.githubusercontent.com/11929953/27254570-0f712010-538b-11e7-9046-42e7a370fb02.PNG)

#### What is the use-case or motivation for changing an existing behavior?
Current behavior avoids using this component, because in specific circumstances list gets out of the view rectangle. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular - 4.1.3
OS - iOS 10.2.1

**Comment by RobJacobs** [comment] 2017-06-17 19:39
Possible duplicate of #4557

**Comment by skonx** [comment] 2017-06-20 09:09
+1

**Comment by crisbeto** [comment] 2017-06-20 18:18
This should be working in beta.7. Can you give it another shot?

**Comment by skonx** [comment] 2017-06-20 18:46
I'm using @angular/material: 2.0.0-beta.7 and it doesn't work yet.

**Comment by skonx** [comment] 2017-06-20 18:50
No more chance on https://material.angular.io/components/autocomplete/examples

![img_7692](https://user-images.githubusercontent.com/19473981/27350200-fcbd6d54-55f9-11e7-806f-b5c1ab06dd8b.PNG)

**Comment by skonx** [comment] 2017-06-21 13:49
Hi @molcik, did beta 7 solve your issue? I'm facing the same one.

**Comment by skonx** [comment] 2017-07-06 19:20
Still having the issue with beta 8

**Comment by skonx** [comment] 2017-07-06 19:22
![img_7703](https://user-images.githubusercontent.com/19473981/27928878-c3f43606-6288-11e7-85a7-a9c3e88b9e85.PNG)

**Comment by grizzm0** [comment] 2017-07-13 11:18
#3745 should have fixed repositioning while scrolling. I however noticed myself that it did not reposition in my project. This is because my autocomplete is inside an element with scroll. 
My site is separated into 3 sections. sidenav, toolbar and content. Only content scrolls.

If I add a scrollbar to the entire site it works. But I only want the scrollbar on the content element (ie, not stretching over the toolbar).

**Comment by sonderbazz** [comment] 2017-07-27 07:38
Also have this issue. Tested in your docs and in our own project.

**Comment by grizzm0** [comment] 2017-07-27 07:48
See #5797 and see if that helps you. Not sure if it's the same issue or not.

**Comment by sonderbazz** [comment] 2017-07-27 08:51
@grizzm0 thx for the info :) 
- but it sadly didn't solve my issue. 
So since the issue is also in the docs - I think the issue is still valid.

**Comment by PhilipSultanescu** [comment] 2017-08-02 09:12
Here's my [Plunker](https://plnkr.co/edit/Qkma97Yw8awqOlA4JyWz?p=preview) where i added some `<br>` above the input to better test the scrolling behaviour on iOS.

The scrolling also gets triggered when the virtual keyboard slides from below.

![screen shot 2017-08-02 at 10 58 33](https://user-images.githubusercontent.com/4140990/28866396-21eef490-7773-11e7-9478-cdd6a0ae75a1.png)

**Comment by skonx** [comment] 2017-08-02 22:40
@PhilipSultanescu thanks

**Comment by xiongemi** [comment] 2017-08-21 20:32
Any update on this issue? If you open the angular material2 website on the mobile safari, this issue still exists.

**Comment by skonx** [comment] 2017-08-23 15:17
Hi @xiongemi.
Correct, it seems to be the same issue :(

**Comment by aitboudad** [comment] 2017-08-23 15:26
Hi, FYI I solved that issue by using custom `MD_AUTOCOMPLETE_SCROLL_STRATEGY`

```ts
import {
    MdAutocompleteModule,
    MD_AUTOCOMPLETE_SCROLL_STRATEGY,
    Overlay, Platform,
   ...
} from '@angular/material';

export function MD_AUTOCOMPLETE_SCROLL_STRATEGY_FACTORY(overlay: Overlay, platform: Platform) {
    return () => platform.IOS ? overlay.scrollStrategies.block() : overlay.scrollStrategies.reposition();
}

@NgModule({
    imports: [
        MdAutocompleteModule,
        ...
    ],
    providers: [
        ...
        {
            provide: MD_AUTOCOMPLETE_SCROLL_STRATEGY,
            deps: [Overlay, Platform],
            useFactory: MD_AUTOCOMPLETE_SCROLL_STRATEGY_FACTORY,
        },
    ],
})
```

**Comment by kevinaud** [comment] 2017-08-26 21:32
@aitboudad I get 

'"node_modules/@angular/material/material"' has no exported member 'MD_AUTOCOMPLETE_SCROLL_STRATEGY'

when I try that. Any idea why? I'm on 2.0.0-beta.8

**Comment by aitboudad** [comment] 2017-08-27 10:52
@kevinaud `MD_AUTOCOMPLETE_SCROLL_STRATEGY` will be landed in `beta.9` in the meantime you can use the build snapshots for `angular/material`

```json
// package.json
"@angular/cdk": "angular/cdk-builds",
"@angular/material": "angular/material-builds",
```

**Comment by kevinaud** [comment] 2017-08-27 16:56
Oh okay, thanks for the help. 

I've got that all working and the behavior is as expected on my computer, it won't allow scrolling while the autocomplete is open, but its still messed up on my iphone for some reason... As soon as I focus on the autocomplete and the keyboard opens up it moves my view down so the autocomplete is no longer visible.

**Comment by Creiger** [comment] 2017-09-16 08:45
@aitboudad Thank you for your solution! Autocomplete works "somehow" on iOS when scrolling (it still does not scroll with body, but does not show over the input), but when i start filtering options it returns to reposition strategy. Any advice?

**Comment by josephperrott** [comment] 2017-09-27 18:35
Closing as duplicate of #4557

**Closed by josephperrott** 2017-09-27 18:35 UTC

**Comment by skonx** [comment] 2017-10-22 18:54
@aitboudad Thank you very much.
I've just used your code and it seems to be a real improvement so far. 
I'm using @angular/cdk: 2.0.0-beta.12 so I needed to swap Md selector to Mat but that's fine.

I've just pasted this in my root module (app.module.ts):

In the imports:

`import {MAT_AUTOCOMPLETE_SCROLL_STRATEGY} from '@angular/material';
import { Platform } from '@angular/cdk/platform';
import { Overlay } from '@angular/cdk/overlay';`

Before @NgModule annotation:

`export function MAT_AUTOCOMPLETE_SCROLL_STRATEGY_FACTORY(overlay: Overlay, platform: Platform) {
  return () => platform.IOS ? overlay.scrollStrategies.block() : overlay.scrollStrategies.reposition();
}`

And then the providers array of the module:

`{
      provide: MAT_AUTOCOMPLETE_SCROLL_STRATEGY,
      deps: [Overlay, Platform],
      useFactory: MAT_AUTOCOMPLETE_SCROLL_STRATEGY_FACTORY,
    }`

I would tell the autocomplete overlay is fixed under the input and is not floading all over the screen when I scroll (that was a real mess) but it seems to be still possible to hide the input field scrolling on the top. I mean that the overlay is not really fixed to the input. 
I've checked the CDK, there are directives but I don't believe we can use them on the pre-build component. 
I've also tested the cdkScrollable directive... doesn't solve the issue :(

**Comment by skonx** [comment] 2017-10-22 18:58
Obviously, this component doesn't work well on iOS (using Safari, Firefox and Chrome). 
Furthermore, I've tested on Chrome running on Android 7 and this is exactly the same.
So, I don't believe it's an issue due to a strange behavior on iOS because I've the same thing on Android. 
Hope it will be fixed soon.

**Comment by murilobd** [comment] 2017-11-07 13:53
Having the same issue here!! Hope this fix soon!!

**Comment by AndreiZaman** [comment] 2017-12-08 14:14
Faced with this issue,  provided solution with custom MAT_AUTOCOMPLETE_SCROLL_STRATEGY_FACTORY not worked for me due 

> error TS2345: Argument of type '{ imports: (typeof CommonModule | typeof Overlay | InjectionToken<() => ScrollStrategy>)[]; decla...' is not assignable to parameter of type 'NgModule'.
>   Types of property 'imports' are incompatible.
>     Type '(typeof CommonModule | typeof Overlay | InjectionToken<() => ScrollStrategy>)[]' is not assignable to type '(any[] | Type<any> | ModuleWithProviders)[]'.
>       Type 'typeof CommonModule | typeof Overlay | InjectionToken<() => ScrollStrategy>' is not assignable to type 'any[] | Type<any> | ModuleWithProviders'.
>         Type 'InjectionToken<() => ScrollStrategy>' is not assignable to type 'any[] | Type<any> | ModuleWithProviders'.
>           Type 'InjectionToken<() => ScrollStrategy>' is not assignable to type 'ModuleWithProviders'.
>             Property 'ngModule' is missing in type 'InjectionToken<() => ScrollStrategy>'.

Angular - 5.1.0

**Comment by carloscasal** [comment] 2018-08-04 12:54
Is this fixed? the samples on the site are fixed, I still experience it.

**Comment by juanidrobo** [comment] 2018-08-28 16:05
I have the same issue!
Anybody with a workaround solution??
