### ISSUE TITLE
Tab header (label) not rendered when in separate component

### ISSUE THREAD

**Issue by vincentsels** [angular/material2#11853] opened 2018-06-20 10:46 UTC
#### Bug, feature request, or proposal:

Bug

#### What is the current behavior?

- When the html *content* of a tab (so its `<ng-template mat-tab-label>` as well as its actual content) is a separate component, only the content is rendered. The header is just blank.
- When the entire `<mat-tab>` is in a separate component, neither the label nor the content is rendered.

It seems like the header and content of a tab cannot be contained in a separate component; or am I doing something wrong? In that case, it might be useful to include guidelines in the docs regarding using tab content in a separate component?

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-v1gquy

#### What is the use-case or motivation for changing an existing behavior?

I would like both the tab's label (header) as well as its content to be grouped in a separate component.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 6.0.4
Material 6.2.1

**Comment by crisbeto** [comment] 2018-06-20 19:35
This works as expected. We use a `ViewChild` to get a hold of the label, however Angular won't look for view children inside other components.

**Comment by josephperrott** [comment] 2018-06-25 16:44
Closing as this is working as intended as noted above.

**Closed by josephperrott** 2018-06-25 16:44 UTC
