### ISSUE TITLE
[Tabs] md-tab-link: routerLinkActive.isActive error

### ISSUE THREAD

**Issue by blyndcide** [angular/material2#1967] opened 2016-11-23 00:47 UTC
Trying to use the new md-tab-nav-bar like this:
```
<nav md-tab-nav-bar>
	<a md-tab-link routerLink="/admin/management" routerLinkActive #rla="routerLinkActive" [active]="rla.isActive">Management</a>
</nav>
```

but get an error

> TypeError: Cannot read property 'some' of undefined

Seems like this way should work after commit: https://github.com/angular/angular/commit/c9f58cf78cce420762c7f8c51172a10a497468ea

**Comment by DzmitryShylovich** [comment] 2016-11-23 11:17
Pls add a plunkr with repro.

**Comment by andrewseguin** [comment] 2016-11-29 18:32
Please use the issue template which helps us reproduce and diagnose the issue. Including a plunkr with this bug will help us determine what is happening.

**Comment by nayfin** [comment] 2016-12-01 05:04
This is exactly how I am trying to use this feature as well, super easy way to keep your tabs in line with your location. I am working on a [plunkr](https://plnkr.co/edit/pLZ4Iq?p=preview) but I am running into some issues just getting it set up. 

1. It seems like the Angular Material 2 template may not be getting the latest version of material, because if I try to add the `[active]="someBoolean"` directive to the anchor, I get yelled at by the compiler:

```
    VM1000 zone.min.js:1 Unhandled Promise rejection: Template parse errors:
Can't bind to 'active' since it isn't a known property of 'a'. ("ks" color="primary">
      <a md-tab-link *ngFor="let child of directory; let i = index;"
        [ERROR ->][active]="routerLinkActive"
        (click)="activateLink(i)">
```
I am assuming this is because it is a pretty new feature. I looked through systemjs.config and it seems to be asking for the latest, so I don't know where to go from here.

2. I set up the router in main.ts, but I am stuck. I think I set up everything correctly but am getting some errors. 

If someone can help me resolve these two issues I can finish up the plunkr and we can get this feature working.

**Comment by nayfin** [comment] 2016-12-04 03:31
Thanks for the fast update. I updated the [plunkr](http://plnkr.co/edit/pLZ4Iq?p=preview).  All the relevant code is in `app.component.html`. I commented the hell out of it explaining what we are looking for. Hopefully it is just a syntactic mistake. Please let me know if I can help in any way. Thanks for all your hard work, this is an amazing set of components and I hope that I can contribute soon.

**Comment by nayfin** [comment] 2016-12-05 21:31
I just tried adding the safe navigation operator to the `rla` template variable i.e. `[active]="rla?.isActive`. I was hoping that perhaps it just need time to load its values, but no dice, I am still getting the same error messages.

**Comment by paladinu** [comment] 2016-12-06 21:09
I'm getting the same error when trying to use the value in to set a class:
`[ngClass]="{'icon icon_contact' : (rla && rla.isActive)}"`
 Results in 
`core.umd.js:2838 EXCEPTION: Error in /js/app/templates/nav-primary.html:18:38 caused by: Cannot read property 'some' of undefinedErrorHandler.handleError @ core.umd.js:2838(anonymous function) @ core.umd.js:6362ZoneDelegate.invoke @ zone.js:229onInvoke @ core.umd.js:5976ZoneDelegate.invoke @ zone.js:228Zone.run @ zone.js:113(anonymous function) @ zone.js:509ZoneDelegate.invokeTask @ zone.js:262onInvokeTask @ core.umd.js:5967ZoneDelegate.invokeTask @ zone.js:261Zone.runTask @ zone.js:151drainMicroTaskQueue @ zone.js:405ZoneTask.invoke @ zone.js:336
core.umd.js:2840 ORIGINAL EXCEPTION: Cannot read property 'some' of undefinedErrorHandler.handleError @ core.umd.js:2840(anonymous function) @ core.umd.js:6362ZoneDelegate.invoke @ zone.js:229onInvoke @ core.umd.js:5976ZoneDelegate.invoke @ zone.js:228Zone.run @ zone.js:113(anonymous function) @ zone.js:509ZoneDelegate.invokeTask @ zone.js:262onInvokeTask @ core.umd.js:5967ZoneDelegate.invokeTask @ zone.js:261Zone.runTask @ zone.js:151drainMicroTaskQueue @ zone.js:405ZoneTask.invoke @ zone.js:336
core.umd.js:2843 ORIGINAL STACKTRACE:ErrorHandler.handleError @ core.umd.js:2843(anonymous function) @ core.umd.js:6362ZoneDelegate.invoke @ zone.js:229onInvoke @ core.umd.js:5976ZoneDelegate.invoke @ zone.js:228Zone.run @ zone.js:113(anonymous function) @ zone.js:509ZoneDelegate.invokeTask @ zone.js:262onInvokeTask @ core.umd.js:5967ZoneDelegate.invokeTask @ zone.js:261Zone.runTask @ zone.js:151drainMicroTaskQueue @ zone.js:405ZoneTask.invoke @ zone.js:336
core.umd.js:2844 TypeError: Cannot read property 'some' of undefined
    at RouterLinkActive.hasActiveLink (http://localhost:57777/modules/@angular/router/bundles/router.umd.js:3635:30)
    at RouterLinkActive.get [as isActive] (http://localhost:57777/modules/@angular/router/bundles/router.umd.js:3593:44)
    at CompiledTemplate.proxyViewClass.View_NavPrimaryComponent0.detectChangesInternal (/AppModule/NavPrimaryComponent/component.ngfactory.js:318:112)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:57777/modules/@angular/core/bundles/core.umd.js:9355:18)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:57777/modules/@angular/core/bundles/core.umd.js:9448:48)
    at CompiledTemplate.proxyViewClass.View_AppComponent0.detectChangesInternal (/AppModule/AppComponent/component.ngfactory.js:48:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:57777/modules/@angular/core/bundles/core.umd.js:9355:18)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:57777/modules/@angular/core/bundles/core.umd.js:9448:48)
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.detectChangesInternal (/AppModule/AppComponent/host.ngfactory.js:29:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:57777/modules/@angular/core/bundles/core.umd.js:9355:18)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:57777/modules/@angular/core/bundles/core.umd.js:9448:48)
    at ViewRef_.detectChanges (http://localhost:57777/modules/@angular/core/bundles/core.umd.js:7338:24)
    at eval (http://localhost:57777/modules/@angular/core/bundles/core.umd.js:6589:88)
    at Array.forEach (native)
    at ApplicationRef_.tick (http://localhost:57777/modules/@angular/core/bundles/core.umd.js:6589:42)ErrorHandler.handleError @ core.umd.js:2844(anonymous function) @ core.umd.js:6362ZoneDelegate.invoke @ zone.js:229onInvoke @ core.umd.js:5976ZoneDelegate.invoke @ zone.js:228Zone.run @ zone.js:113(anonymous function) @ zone.js:509ZoneDelegate.invokeTask @ zone.js:262onInvokeTask @ core.umd.js:5967ZoneDelegate.invokeTask @ zone.js:261Zone.runTask @ zone.js:151drainMicroTaskQueue @ zone.js:405ZoneTask.invoke @ zone.js:336`

**Comment by nayfin** [comment] 2016-12-07 03:57
If you just need to add a class to the active link and remove it when it's not active, Angular has a built in directive that does that.

`<a routerLink="/someUrl" [routerLinkActive]="['class1', 'class2']"> A cool link </a>`

So, yours would be:
 
`<a routerLink="/someUrl" [routerLinkActive]="['icon ', 'icon_contact']"> A cool link </a>`

[Here are some docs](https://angular.io/docs/ts/latest/api/router/index/RouterLinkActive-directive.html) that might help.

[Here is a plunkr](http://plnkr.co/edit/xtVKKh?p=preview) where `.class1` and `.class2` follow the active link.  

You will notice that it updates the classes even if the redirect comes from a link outside of the `md-tab-link`, but Material's `border-bottom` only registers `ng-reflect-active="true"` if  redirected by the `md-tab-link`. Though it would follow the active link if we can get `[active]="rla.isActive"` to work.

**Comment by paladinu** [comment] 2016-12-07 04:31
Yes, I use that else where.  The problem I am trying to solve is that I want to apply a class to something that is a child or my routerlink.  Like this:
`<a routerLink="/someUrl"><span [routerLinkActive]="['class1', 'class2']">I want the class on this span</span></a>`
From what I can tell that is what the RouterLinkActive directive export was trying to solve and it works fine if I throw it in as interpolation like `class="{{rla.isActive?'icon_contact':''}}",` but blows up when I try to use it inside the ngClass directive with the rla variable.  If that routerLinkActive is supposed to work on children and I'm just doing something wrong please let me know.

**Comment by nayfin** [comment] 2016-12-07 04:56
If you can update that plunkr to demonstrate what you are looking for, I think I should be able to help you.

**Comment by paladinu** [comment] 2016-12-07 15:08
Here is a fork of that plunkr.  My goal is to be able to apply a class to something within the router link rather than the routerlink itself.  I think it is the same issue as the OP because they are both trying to access the isActive within an expression.

http://plnkr.co/edit/cUl8VS?p=preview

**Comment by nayfin** [comment] 2016-12-08 04:04
Okay... I've done everything I can think of. It seems these particular attributes ,`[active]` and `[ngClass]`, don't want to wait for `rla.isActive` to load and return a boolean. They won't wait even wait when you using the Safe Navigation Operator `?.`, which is explicitly telling them to. 

You can however use [class bindings](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#class-binding) even in the child of the element containing `routerLinkActive`:

`<a md-tab-link routerLink="someLink"
        routerLinkActive
        #rla="routerLinkActive"> 
        <span [class.someClass]="rla.isActive">Working child link</span>
 </a>` 

I would argue that this is actually cleaner than using `ngClass`. [Here is the plunkr](http://plnkr.co/edit/VCLKzP?p=preview).

Can anyone help me get the same functionality out of `[active]='rla.isActive'`? I can't understand why binding to one attribute works perfectly while binding to another refuses to.

**Comment by nayfin** [comment] 2016-12-16 01:37
@DzmitryShylovich will your [pull request #13341](https://github.com/angular/angular/pull/13341) address these issues?

**Comment by DzmitryShylovich** [comment] 2016-12-16 07:19
@nayfin yes, but it's not clear when it will be merged

**Comment by antonmoiseev** [comment] 2016-12-25 11:42
@DzmitryShylovich AFAICS your PR doesn't introduce backwards incompatible changes at the moment, please correct me if I'm wrong.

@andrewseguin considering @DzmitryShylovich's PR is safe to merge, could you raise the priority of this issue. I believe this is pretty much how tabs component will be used in the most of the apps.

/cc @jelbourn

P.S. Sorry for bothering during the holidays 😉. Happy Christmas! 🎄 🎅

**Comment by jheinnic** [comment] 2017-01-02 21:39
Good afternoon!

I just ran into this very same issue today.  When debugging my own code stil left me blocked, I turned to the web and found this thread.  It changed the way I was looking at the issue and that helped me find a way to work around it in the immediate term.

I haven't enough time to draft an example at the moment.  I will follow up with one later on if this description is unclear, but want to offer what I have now in the meantime.

It looks like the problem here is that the RouterLinkActive.isActive() method is dependent upon a @ViewChildren query-induced injection to occur.  AFAIK, that happens during the content initialization stage of compilation.  The property annotated with @ViewChildren is "this.links".

The call to RouterLinkActive.isActive( ) is part of the same content model where RouterLinkActive is getting links injected from RouterLink.  which explains why "this.links.changes.some( )" causes  "Cannot read property 'some' of undefined" to be thrown--it isn't injected by the time the first call to isActive() expects it to be there, and the implementation of isActive( ) doesn't have a defensive check allowing it to return false when it's called so early.

I confirmed that adding that undefined check in isActive( ) solved my issue, but modifying the framework isn't really a viable workaround.  I couldn't make the framework tolerate an early call to isActive(), so I forced my component to defer its first call.

**Before workaround:**
`<a md-tab-link routerLink="/lobby" routerLinkActive #rla="routerLinkActive" [active]="rla.isActive">Lobby</a>`

**After workaround:**
`<a md-tab-link routerLink="/lobby" routerLinkActive #rla="routerLinkActive" [active]="**rlaSafe &&** rla.isActive">Lobby</a>`

**And in the Component code**
```
export class MyNavbarComponent implements AfterViewInit {
  private rlaSafe: boolean;

  constructor( ) {
    this.rlaSafe = false;
  }
  public ngAfterViewInit() {
    this.rlaSafe = true;
  }

```

The additional boolean stops the flow control from reaching isActive() until after the view initialization lifecycle event has passed, by which time the response to RouterLinkActive's @ViewChildren query has been injected and the call to isActive( ) therefore no longer gets tripped up on an uninitialized reference.

Its not transparent, so its a work-around and not a solution, but it unblocked the rest of what I have yet to do early this week, so I'm comfortable with it for now.

**Comment by Splaktar** [comment] 2017-01-03 01:54
@jheinnic thanks. That's very helpful as I ran into this today as well!

I had to make a small change to this to keep zone.js happy. 
```
  private rlaSafe: boolean = false;

  constructor(private changeDetectionRef: ChangeDetectorRef) {}

  public ngAfterViewInit() {
    this.rlaSafe = true;
    // Fix "Expression has changed after it was checked" exception from Zone.js
    this.changeDetectionRef.detectChanges();
  }
```

**Comment by jelbourn** [comment] 2017-01-03 17:13
@andrewseguin This looks like it's a bug in Angular, specifically `router_link_active.ts`. The function:
```ts
  private hasActiveLink(): boolean {
    return this.links.some(this.isLinkActive(this.router)) ||
        this.linksWithHrefs.some(this.isLinkActive(this.router));
  }
```
Should guard against `links` and `linksWithHrefs` being null/undefined. This is something we could fix.

**Comment by ChuckkNorris** [comment] 2017-01-05 23:46
Just a note: each `<a md-tab-link></a>` element must have a unique variable name for its routerLinkActive object or it will not correctly set its tab to active.

Is there maybe a way to reference specifically the element variable (e.g. `#rla="routerLinkActive" [active]="#rla.isActive"`)

**app.component.html**
```
<nav md-tab-nav-bar>
     <a md-tab-link routerLink="browse-pets" routerLinkActive #rla="routerLinkActive" [active]="rlaSafe && rla.isActive">Browse Pets</a>
     <a md-tab-link  routerLink="/sell-pet"  routerLinkActive #rlab="routerLinkActive" [active]="rlaSafe && rlab.isActive">Sell Pet</a>
</nav> 
```

**app.component.ts**

```
import { Component, AfterViewInit, ChangeDetectorRef } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements AfterViewInit{

  constructor(private changeDetectionRef: ChangeDetectorRef) {}
  private rlaSafe: boolean = false;

  ngAfterViewInit() {
    this.rlaSafe = true;
    this.changeDetectionRef.detectChanges();
  }
}
```

**Comment by nayfin** [comment] 2017-01-06 03:57
Thanks for the help, simple work around for until merge. I went to update example in Plunker, but it stopped working. I don't know from where it pulls its libraries, but it's throwing a 

`zone.min.js:1 Error: (SystemJS) XHR error (404) loading `

I haven't touched it in weeks so it must be a change in source. If anyone knows how to fix this I can update it so people can a have a working example.

**Comment by somombo** [comment] 2017-01-07 15:39
Hi everyone, I found this error after a sleepless night of thinking I was doing something wrong while trying to implement the documented MdTabNavBar Directive example shown at the bottom of https://material.angular.io/components/component/tabs#tabs-and-navigation (under "Tabs and Navigation")..

Obviously, since this is still an open issue, that example (written verbatim) wont work.
I think it would be great if someone put a quick note next to that example pointing to this issue so that people dont waste too much time thinking they are not following what they may think is documented correctly. Something like the following would suffice.

> **Note:** In it's current form, example above has a known bug and will not work, please consult Issue #1967 for more details and for for a work around whilst this issue is being resolved by the Angular team.

**Comment by somombo** [comment] 2017-01-07 15:41
After racking my head quite a while, I came to the same conclusion as @jelbourn. I think it's essential that in `RouterLinkActive.hasActiveLink()`, the values  `RouterLinkActive.links` and `RouterLinkActive.linksWithHrefs` are checked for null/undefined values as a guard, before doing the activeLink testing. 

Has anyone raised this as an issue in the https://github.com/angular/angular repo yet? Or perhaps created a quick PR?

**Comment by somombo** [comment] 2017-01-07 16:42
I would additionally like to suggest the change below to the  `MdTabLink` class in this repo. 
The reason again is for safety, so that we are only updating the nav bar's active link when the view /  content is ready. Haven't had time to test yet but, what do you all think? (refer to https://github.com/angular/material2/blob/master/src/lib/tabs/tab-nav-bar/tab-nav-bar.ts)

`
/* ... */
// New MdTabLink
@Directive({
  selector: '[md-tab-link], [mat-tab-link]',
})
export class MdTabLink  implements AfterContentInit {
  private _isActive: boolean = false;

  /** Whether the link is active. */
  @Input()
  get active(): boolean {
    return this._isActive;
  }
  set active(value: boolean) {
    this._isActive = value;
    this._setActiveNavLink();
  }
  
  //flag to help double check that nav update only occurs when content is ready
  private _contentReady: boolean = false;
 
  ngAfterContentInit(){
    this._contentReady = true;
    this._setActiveNavLink();
  }

  private _setActiveNavLink(){
    if (this.active && this._contentReady) {
      this._mdTabNavBar.updateActiveLink(this._element.nativeElement);
    }
  }

  constructor(private _mdTabNavBar: MdTabNavBar, private _element: ElementRef) {}
}
/* ... */
`

**Comment by Splaktar** [comment] 2017-01-07 20:00
@somombo yes, there is a [PR open](https://github.com/angular/angular/pull/13273) in the @angular/angular repo.

**Comment by vinagreti** [comment] 2017-01-16 19:46
Should we mention in the docs this `rlaSafe` workaround? I've spent a lot of time figuring out what I was doing wrong... There is differences between git Readme.md, material.angular.io docs and what we really  should do.

Just say the words and I can update the README.md to point this issue and th `rlaSafe` workaround.

**Comment by Splaktar** [comment] 2017-01-16 19:56
@vinagreti It does not look like they want to update any of the docs to address this bug. Instead they are trying to get the bug resolved ASAP. [My PR to update the docs](https://github.com/angular/material2/issues/2563) was declined.

It looks like the [PR in the core](https://github.com/angular/angular/pull/13273) is waiting on review still.

**Comment by blyndcide** [comment] 2017-01-23 16:22
Angular 2.4.4 fixes the error and tabs change successfully; however [active] is not being set.

**Comment by adrm** [comment] 2017-02-02 16:24
Setting version to Angular 2.4.5 fixed it for me!

**Comment by blyndcide** [comment] 2017-02-16 23:59
Ok I got [active] set correctly this way:

```
<nav md-tab-nav-bar>
	<a md-tab-link routerLink="/admin/management" routerLinkActive #rla1="routerLinkActive" [active]="rla1.isActive">Management</a>
	<a md-tab-link routerLink="/admin/profile" routerLinkActive #rla2="routerLinkActive" [active]="rla2.isActive">Profile</a>
</nav>
```

Thanks to all who helped fix this.

**Comment by aretheregods** [comment] 2017-05-14 18:39
This still seems to be an open issue on Angular 4 with Angular Material 2.0.0-beta5. I could get neither the example on material io nor the fix proposed in this thread to resolve the issue. The browser console says `Can't bind to 'active' since it isn't a known property of 'a'.`

**Comment by kfirufk** [comment] 2017-09-05 20:30
angular 4.4.0-RC0 and material 2.0.0-beta.10 and this issue still occurs. none of the work-arounds work. any ideas ? is there another way to add components to each selected tab besides <md-tab-link> ? what do I do ?

**Comment by ToonvanStrijp** [comment] 2017-09-20 20:45
It's still an issue. Im using the following routes:
```
{
    path: 'organisation/:id',
    component: OrganisationComponent,
    children: [
      {path: '', component: OrganisationEditComponent},
      {path: 'locations', component: LocationsComponent},
    ]
  }
```

Then this as my component html:
```
<nav md-tab-nav-bar>
  <a md-tab-link
     [routerLink]="['./']"
     routerLinkActive #rla="routerLinkActive"
     [active]="rla.isActive">Algemeen</a>
  <a md-tab-link
     [routerLink]="['./locations']"
     routerLinkActive #rlb="routerLinkActive"
     [active]="rlb.isActive">Locaties</a>
</nav>
<router-outlet></router-outlet>
```

So now it works on the initial load, but whenever I go back to the './' route the md-tab-link active doesn't get updated.

**Comment by dinvlad** [comment] 2017-10-12 18:28
+1, just upgraded from 10 (where it worked) to beta 12, and suddenly getting `Can't bind to 'active' since it isn't a known property of 'a'`

**Comment by dinvlad** [comment] 2017-10-12 18:31
Seems like recent deprecation of `md-` prefix broke the templates. For anyone still struggling with these, try using `mat-`..

**Comment by agborkowski** [comment] 2017-10-13 12:38
karma test fails on 

```code
Can't bind to 'active' since it isn't a known property of 'a'. ("
                routerLinkActive
                #rla="routerLinkActive"
                [ERROR ->][active]="rlaSafe && rla.isActive"
```

**Comment by ravishivt** [comment] 2017-12-23 01:46
Same issue with latest Angular 5.1.2 and Angular Material 5.02.  My hacky/flaky workaround:

```typescript
  ngAfterViewChecked() {
    setTimeout(() => {
      this.changeDetectionRef.detectChanges();
    });
  }
```

**Comment by reothues** [comment] 2018-01-18 16:01
@aretheregods Same issue with latest Angular 5.2.1 and Angular Material 5.1.0;
I believe it's that [active] should be bond to  mat-tab-link directive but instead it was bond to <a>
so any workaround would be to delay the [active] as later than mat-tab-link had bootstrapped

**Comment by jelbourn** [comment] 2018-01-25 23:50
This should be long ago fixed in Angular.

**Comment by reothues** [comment] 2018-02-04 03:16
and i'm still having it

**Comment by sopretty** [comment] 2018-02-09 15:58
I'm having the same problem here :(

**Comment by aretheregods** [comment] 2018-02-13 19:45
@jelbourn This is still an open issue for me on the latest version. Please consider reopening this.

**Comment by jscti** [comment] 2018-02-23 15:59
The docs example does not work, the *ngFor somewhat breaks the init of the inkBar (and take a huge time to display the links )..
I had to add a top level *ngIf to delay both mat-tab-nav-bar and mat-tab-link init at the same time, fixing the inkBar bug.

```
<nav *ngIf="navLinks" mat-tab-nav-bar>
  <a mat-tab-link
     *ngFor="let link of navLinks"
     [routerLink]="link.path"
     routerLinkActive #rla="routerLinkActive"
     [active]="rla.isActive">
    {{link.label}}
  </a>
</nav>
```

**Comment by hectorggp** [comment] 2018-03-05 19:18
I have the same problem here 👎

**Comment by jotatoledo** [comment] 2018-03-19 16:00
Having a similar issue, sadly I dont have the time to create a repro.
The method suggested by @ravishivt worked for me

**Comment by andrewseguin** [comment] 2018-03-27 17:20
If you are affected, please re-open if you can provide a reproduction of the issue, otherwise we won't be able to investigate.

**Closed by andrewseguin** 2018-03-27 17:20 UTC
Labels: P3: important

**Comment by AsantosCandor** [comment] 2018-05-24 11:36
Having the same error.

**Comment by beeman** [comment] 2018-06-15 07:52
In my case the error was fixed by importing `MatTabsModule` from `@angular/material`
