### ISSUE TITLE
bug(build): Gulp task build:release fails on windows

### ISSUE THREAD

**Issue by jimitndiaye** [angular/material2#1249] opened 2016-09-16 02:15 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should be able to run a release build. ```build:components``` works, but ```build:release``` doesn't

#### What is the current behavior?
C:\Dev\GitHub\material2>gulp build:release
(node:17036) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[03:02:24] Using gulpfile C:\Dev\GitHub\material2\gulpfile.js
[03:02:24] Starting 'build:release'...
[03:02:24] Starting 'clean'...
[03:02:25] Finished 'clean' after 270 ms
[03:02:25] Starting 'build:components'...
[03:02:25] Starting ':build:components:ts'...
[03:02:33] Finished ':build:components:ts' after 8.03 s
[03:02:33] Starting ':build:components:rollup'...
[03:02:34] Finished ':build:components:rollup' after 1.37 s
[03:02:34] Starting ':build:components:assets'...
[03:02:35] Finished ':build:components:assets' after 812 ms
[03:02:35] Starting ':build:components:scss'...
[03:02:36] Finished ':build:components:scss' after 1.16 s
[03:02:36] Starting ':inline-resources'...
[03:02:36] Finished ':inline-resources' after 56 ms
[03:02:36] Finished 'build:components' after 11 s
[03:02:36] Starting ':build:components:ngc'...
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1007:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at Object.exports.spawn (child_process.js:383:9)
    at ../../tools/gulp/task_helpers.ts:84:40
    at ../../tools/gulp/task_helpers.ts:128:41
    at C:\Dev\GitHub\material2\node_modules\resolve-bin\index.js:40:5
    at C:\Dev\GitHub\material2\node_modules\find-parent-dir\index.js:25:26
    at FSReqWrap.cb [as oncomplete] (fs.js:251:19)

#### What are the steps to reproduce?
Clone the source, install the dependencies then run ```gulp build:release``` on Windows
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Is there anything else we should know?
Running node v6.2.2 and npm v3.9.3

**Comment by jelbourn** [comment] 2016-09-16 17:09
Dupe of #1129

**Closed by jelbourn** 2016-09-16 17:09 UTC
