### ISSUE TITLE
Trigger new menu while another one is already open

### ISSUE THREAD

**Issue by patricknazar** [angular/material2#8666] opened 2017-11-27 16:08 UTC
#### Bug, feature request, or proposal:
Bug or feature request, not really sure here

#### What is the expected behavior?
To be able to click on a new menu trigger button and close any currently opened menus and open the new one - in one click.

#### What is the current behavior?
You have to click once to get out of the overlay, and a second time to open the new menu

#### What are the steps to reproduce?

https://menus-demo.stackblitz.io/

1. open the first menu
2. try to open the second one while the first one is open
3. notice how you had to click twice and it's really annoying

#### What is the use-case or motivation for changing an existing behavior?
A much nicer menu experience

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular@5.0.3, material@5.0.0-rc1, web, typescript@2.6.1

#### Is there anything else we should know?
I tried simply setting the pointer-events on the overlay class to 'all' but it resulted in multiple menu's open at the same time, which I don't want. Perhaps a way to trigger a menu close on the overlay's click event whilst still letting it through.

**Comment by willshowell** [comment] 2017-11-27 17:01
See #5938, #1956, and #3458

**Comment by patricknazar** [comment] 2017-11-27 17:21
That's sad. I'll close this

**Comment by patricknazar** [comment] 2017-11-27 17:27
Actually, I feel like that spec is only relating to mobile and tablet. There doesn't seem to be anything in the spec preventing this??

**Comment by jelbourn** [comment] 2017-11-28 17:02
Closing as working as intended- we have no intention to change this behavior, as it goes against how most people expect menus to work.

**Closed by jelbourn** 2017-11-28 17:02 UTC

**Comment by patricknazar** [comment] 2017-11-29 02:29
What about "Cascading menus (Desktop only)" as per https://material.io/guidelines/components/menus.html#menus-usage ??? That menu is used in google docs and it does behave like I'd expect. Can "Cascading menus" be implemented then?

**Comment by gatimus** [comment] 2017-12-22 17:59
@patricknazar I believe "Cascading menus" already are implemented.
https://material.angular.io/components/menu/overview see Nested menu
