### ISSUE TITLE
feat(input): Style and animate textarea according to Material Design

### ISSUE THREAD

**Issue by johnchristopherjones** [angular/material2#4266] opened 2017-04-25 18:35 UTC
#### Bug, feature request, or proposal:
Text areas are not styled according to current [Material Design](https://material.io/guidelines/components/text-fields.html#text-fields-field-types) guidelines.

#### What is the expected behavior?
Text areas should be outlined in a rounded box with hover and ripple animations.

#### What is the current behavior?
Text areas are basically unstyled.

#### What are the steps to reproduce?
Create a text area using md-input-container and mdInput:

```
    <md-input-container floatPlaceholder="always">
      <md-placeholder>Placeholder</md-placeholder>
      <textarea mdInput type="text" required></textarea>
      <md-hint>Hint Text</md-hint>
      <md-error>Error Message</md-error>
    </md-input-container>
```

#### What is the use-case or motivation for changing an existing behavior?
Using multi-line text areas with whitespace consistent with the rest of Material Design.  The current behavior styles text areas as resizable text inputs with extra initial height, which looks wrong.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.1, Material 2.0.0-beta.3

**Comment by jelbourn** [comment] 2017-04-25 18:37
Dupe of #3984

**Closed by jelbourn** 2017-04-25 18:37 UTC

**Comment by dewanganabhishek** [comment] 2017-08-07 05:58
fgfg
