### ISSUE TITLE
Dialog Component Demo - File Missing

### ISSUE THREAD

**Issue by Eja26** [angular/material2#9553] opened 2018-01-23 23:02 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Working demos of dialog.

#### What is the current behavior?
Demos are missing a file.

#### What are the steps to reproduce?
Go to the [Dialog component page](https://material.angular.io/components/dialog), open one of the demos (the link to stackblitz), and you should be presented with message saying that a file is missing.

#### Is there anything else we should know?
Just in case it's not obvious, I am talking about the actual [material](https://material.angular.io/components/dialog) website.

**Comment by jelbourn** [comment] 2018-01-23 23:29
Duplicate of #9541

**Closed by jelbourn** 2018-01-23 23:29 UTC
