### ISSUE TITLE
Sidenav with align="end" is jumping while opening after beta.11

### ISSUE THREAD

**Issue by paulogr** [angular/material2#2152] opened 2016-12-09 23:49 UTC
#### Bug, feature request, or proposal:

Bug: Sidenav with align="end" doesn't work as expected.

#### What is the expected behavior?

When click to open side nav it opens smoothly.

#### What is the current behavior?

Sidenav is jumping while opening.

#### What are the steps to reproduce?

Create a side nav layout, align it to "end" and click to open.

#### What is the use-case or motivation for changing an existing behavior?

Fix user experience.

#### Which versions of Angular, Material, OS, browsers are affected?

angular-cli: 1.0.0-beta.22-1
@angular: 2.2.3
@angular/material: 2.0.0-alpha.11-3
node: 6.5.0
os: darwin x64

#### Is there anything else we should know?

Here it goes a gif showing what's happening.

![material2-beta11-sidenav-jump](https://cloud.githubusercontent.com/assets/30919/21068456/439042e4-be59-11e6-84ae-2cd793836ac8.gif)

and with align="start" it works as expected.

Thank you.

**Comment by crisbeto** [comment] 2016-12-10 09:18
Closing as a duplicate of https://github.com/angular/material2/issues/2144

**Closed by crisbeto** 2016-12-10 09:18 UTC
