### ISSUE TITLE
Datepicker pop-up positioned incorrectly when inside of Dialog

### ISSUE THREAD

**Issue by MarcosJanuario** [angular/material2#9730] opened 2018-02-01 09:39 UTC
#### Bug, feature request, or proposal:
Bug

![a](https://user-images.githubusercontent.com/15744385/35671406-9c05c2c4-073b-11e8-9f55-1849998cc751.PNG)

#### What is the expected behavior?
The datepicker is shown right under the input field inside the dialog

#### What is the current behavior?
The datapicker is shown as absolute position top and left set to 0px

### For material Angular JS there was the same issue, and it was fixed 
https://github.com/angular/material/issues/5501

**Comment by crisbeto** [comment] 2018-02-01 16:05
Can you post an example that shows the issue? [You can use this Stackblitz as the base](https://goo.gl/wwnhMV).

**Comment by prashantwalavalkar** [comment] 2018-02-08 07:01
Any solution to this so far?

**Comment by MarcosJanuario** [comment] 2018-02-08 16:32
@prashantwalavalkar I did not get the datepicker to work as it should be (centralized even though it's called over a first dialog). However, I found a way around to have a datepicker as I wanted. What I did was simply getting the mat-calendar component that is used INSIDE THE DATEPICKER. By working with the MatCalendar I can set it where I want and style it the way I want.  The parameters expected to setup the calendar are pretty much similar to the ones used with Datepicker.

**Comment by jelbourn** [comment] 2018-02-13 23:23
Closing since we weren't able to reproduce this. Feel free to open a new issue with a reproduction.

**Closed by jelbourn** 2018-02-13 23:23 UTC

**Comment by prashantwalavalkar** [comment] 2018-04-05 15:28
Hey.. 

Sorry for late reply on over all issue. But I am able to resolve this. It was '.mat-input-underline' div which was made hidden as in my design it wasn't required. But it is neccessary for correct positioning of date picker. So I made it hidden visibility hidden & z index to negative value instead of display none.

It started working again as date picker uses position of underline for its position.

Let me know if you are doing same & if this solution works for you.

:)

**Comment by lbarbula** [comment] 2018-05-07 22:18
@prashantwalavalkar I was having the same issue and it was resolved by your fix. Thank you! How did you catch this?

**Comment by OlgaMatosova** [comment] 2018-09-21 09:08
> mat-input-underline

thank you for this fix!

**Comment by callmehomer** [comment] 2018-10-23 10:19
@prashantwalavalkar thanks!

In some cases you will also need ng-deep
`::ng-deep .mat-input-underline{
  visibility: visible;
  z-index: -999;
  display: block;
}`

**Comment by mani2448** [comment] 2019-02-01 12:11
@jelbourn 
Angular Material Datepicker is hsowing on left side sometimes and cdk-overlay-pane doesn't calculate its position according to datepicker input. 
here is the link to images of the issue:  https://stackoverflow.com/questions/54479177/why-angular-material-date-picker-sometimes-comes-on-top-left-side-of-screen-inst

**Comment by nibinbaby** [comment] 2019-08-09 03:18
@prashantwalavalkar : thanks for the fix
