### ISSUE TITLE
Datatable sortable header Icon is displayed as T on load

### ISSUE THREAD

**Issue by vibingopal** [angular/material2#8435] opened 2017-11-14 16:38 UTC
#### Bug, feature request, or proposal:
Hi Team,

We are using datatable in our application with sortable header feature.But when the screen loads the icon is getting displayed as T. Please find the attached.

Below is my configuration i used on header 

matSortActive="Pool" matSortDirection="desc" matSortDisableClear

Versions :
Material - 2.0.0-beta.12
Angular - 4.4.4

![image](https://user-images.githubusercontent.com/17860925/32792028-f8bae78a-c927-11e7-8178-6bc9a00414c4.png)

**Comment by jelbourn** [comment] 2017-11-14 17:17
Duplicate of #8396

**Closed by jelbourn** 2017-11-14 17:17 UTC
