### ISSUE TITLE
Dialog close() from <input> event no longer works.

### ISSUE THREAD

**Issue by arlowhite** [angular/material2#4287] opened 2017-04-26 17:20 UTC
#### Bug:

I have a dialog with an Input. When the user presses ENTER, the dialog closes.

My project is using builds from _github.com/angular/material2-builds.git_
This was working about 2 weeks ago, but when I last updated it broke.
So commit somewhere between April 17-April 25 caused this problem.

Now, pressing ENTER will briefly close and re-open the dialog over and over.
However, a button `(click)` can close using the API just fine.
See: http://plnkr.co/edit/K1TfpHfdPORKb7afApsZ?p=preview

I'm guessing one of these commits caused the issue?
https://github.com/angular/material2/commit/85bc3a6574c27e686512e282ec8f77eeb6b5fbed
https://github.com/angular/material2/commit/7428c49e104115fee30f43b2c586339f6d5979c0
https://github.com/angular/material2/commit/29968b8a6baffcaa7c03a42b967bb095ac66aa1a

#### What is the expected behavior?

Should be able to call `.close()` in a `(onKeyDown)` handler.

#### What is the current behavior?

Dialog closes and then re-opens instead of staying closed.

#### What are the steps to reproduce?

http://plnkr.co/edit/K1TfpHfdPORKb7afApsZ?p=preview

#### What is the use-case or motivation for changing an existing behavior?

Users expect simple dialogs to close when they press enter on an Input.

#### Which versions of Angular, Material, OS, browsers are affected?

Latest master. 607f5a645f31e0db437b0df1192f58e14562f126

**Comment by willshowell** [comment] 2017-04-26 20:59
I did a little bisect of the material2-builds to help narrow it down, and it looks like there were two regressions with using keydown to close the dialog:

**Regression 1**
* Commit [a7f58b8](https://github.com/angular/material2-builds/commit/a7f58b8a695550b944555e76ad1b6cfe6479c594) works perfectly
* The following commit [8e6fdfc](https://github.com/angular/material2-builds/commit/8e6fdfc2002386ff3268ba0863294992732dc9b6) works fine if you just tap ENTER, but opens hundreds of dialogs if you hold it down

This slight regression can be attributed to #3774

**Regression 2**
* Commit [58fe99c](https://github.com/angular/material2-builds/commit/58fe99c4c5a6bbe3cc303835df1f418de36b5e6c) works fine if you just tap ENTER, but opens hundreds of dialogs if you hold it down
* The following commit [667bb4e](https://github.com/angular/material2-builds/commit/667bb4e03f80ba205ca9a67f696820819e60a31f) always just reopens the dialog (like your issue states)

The only MdDialog commit between this merge range is #3892 and is probably your culprit

// cc @crisbeto

**Comment by crisbeto** [comment] 2017-04-29 10:19
It's because Material restore focus immediately, instead of waiting for the animation to finish. I've opened a PR that should fix it (https://github.com/angular/material2/pull/4329). Meanwhile you can work around it either by closing on `keyup` or disabling the open button while there's an open dialog.

**Closed** 2017-05-02 23:38 UTC
Labels: has pr
