### ISSUE TITLE
Tooltip blocking click event

### ISSUE THREAD

**Issue by heyanctil** [angular/material2#6027] opened 2017-07-25 16:08 UTC
We are using the tooltip in mdMenu and someone have raised an issue about the tooltip that blocking click event when clicking on menu element.

I've modified this plunker to reproduce the behavior. If you position the cursor on the first element of the menu, you'll see the tooltip. If you try to click rapidly on the second element of the menu, the click seems to be catched by the tooltip instead and nothing happen. If you take your time, the tooltip disappear and the event is fired:

https://plnkr.co/edit/kpn23qwKkfBOadykpof0?p=preview

![image](https://user-images.githubusercontent.com/7291291/28581997-e6574f00-7131-11e7-97e1-40665aa14007.png)

**Comment by jelbourn** [comment] 2017-07-25 20:18
I think this will be fixed in the next release by a39441893b0de9f7641411a05293b9d383cc334f. @DevVersion?

**Comment by DevVersion** [comment] 2017-07-25 20:24
Yeah should be fixed by https://github.com/angular/material2/commit/d04230c0848fd059f88d6d069ad2e6904a099df7. Tried to reproduce it in a Plunker using master and it looks like the fix works properly.

https://plnkr.co/edit/aMk0ZkabXWSPCazXbzjm?p=preview

**Closed by DevVersion** 2017-07-25 20:24 UTC
