### ISSUE TITLE
Converge <md-tab-group> and [md-tab-nav-bar] pagination implementation

### ISSUE THREAD

**Issue by oldchevy** [angular/material2#6767] opened 2017-08-31 19:05 UTC
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
For the "md-tab-nav-bar" directive, I would expect when the number of links exceeds the horizontal space available, for pagination arrows to appear and the the height to remain fixed, like the behavior in \<md-tab-group\>.

#### What is the current behavior?
Currently elements not fitting onto one row reflow into a second row, while the ink bar remains under the second row.

#### What are the steps to reproduce?
http://plnkr.co/edit/1wWoGqoX9lOVlBT1c8Pg?p=preview

#### What is the use-case or motivation for changing an existing behavior?
UI interface of both implementations should be the same.

It's a really nice feature to able to use the Angular router with the md-tab-group styling, but it would be even better if the UI interface was identical.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by willshowell** [comment] 2017-08-31 19:45
See https://github.com/angular/material2/issues/2177

**Comment by jelbourn** [comment] 2017-08-31 23:51
Duplicate of #2177

**Closed by jelbourn** 2017-08-31 23:51 UTC
