### ISSUE TITLE
CDK drag can not vertical and horizontal at the same time

### ISSUE THREAD

**Issue by markkoo** [angular/material2#14749] opened 2019-01-08 04:14 UTC
#### Please describe the feature you would like to request.
CDK drag can not vertical and horizontal at the same time

#### What is the use-case or motivation for this proposal?
Let's said user device viewport is 600px, then we have 4 elements which is 300px, 
`<body>`
`   <div style="width:300px; height:300px"></div>`
`   <div style="width:300px; height:300px"></div>`
`   <div style="width:300px; height:300px"></div>`
`   <div style="width:300px; height:300px"></div>`
`</body>`

you will get **2 columns x 2 rows**, then I want to reorder the first element to last element.

#### Is there anything else we should know?
-nothing

**Comment by lichangfeng** [comment] 2019-01-08 09:06
I have the same question.
https://stackblitz.com/edit/angular-furjhv

**Comment by raphael22** [comment] 2019-01-08 10:06
Tracked here but only tagged as "discussion, feature" not "critical bug, P1" :/
https://github.com/angular/material2/issues/13372

**Comment by andrewseguin** [comment] 2019-01-09 23:05
Closing as duplicate of #13372

**Closed by andrewseguin** 2019-01-09 23:05 UTC
