### ISSUE TITLE
The placeholder font-size of Input and Select should be same

### ISSUE THREAD

**Issue by xmeng1** [angular/material2#3322] opened 2017-02-27 09:56 UTC
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

The placeholder font-size of Input and Select should be same
#### What is the current behavior?

According to my usage, I found that the font-size of Input and Select are different:

Input: 20px
Select: 16px

So currently, I just reset it dynamically when the select change.

```
  setCssDynamical($event) {
    console.log($event);
    $event.source.trigger.nativeElement.childNodes[0].setAttribute("style", "font-size: 20px;font-weight: bold")
  }

      <md-select
        *ngIf="showTokenSelect"
        (change)="setCssDynamical($event)">
        <md-option *ngFor="let domain of domainsDemo" [value]="domain.value"
                   style="font-size: 20px">
          {{domain.viewValue}}
        </md-option>
      </md-select>
```
I think maybe these font-size should be same. 

#### Which versions of Angular, Material, OS, browsers are affected?

 "@angular/material": "^2.0.0-beta.2",
#### Is there anything else we should know?

According to my understand, I think just change the css of mat-select-trigger

```
.mat-select-trigger{display:flex;align-items:center;height:30px;min-width:112px;cursor:pointer;position:relative;box-sizing:border-box;font-size:16px}
```

font-size 16px to 20px

**Comment by janisr** [comment] 2017-02-27 15:13
it is not just font size - there is general misalignment in select and input when used side by side

![image](https://cloud.githubusercontent.com/assets/430983/23366576/e6be7f04-fd0f-11e6-847e-4a19700ca252.png)
placeholders and underline are on different levels

**Comment by rajendra2** [comment] 2017-02-28 13:57
I also has same issue as @janisr . any workaround while proper fix is released ?

I am not able to override .mat-select-trigger attributes from the component.css file.

**Comment by kara** [comment] 2017-03-01 00:23
This looks like a dupe of https://github.com/angular/material2/issues/2127. Input inherits its font size while select prescribes 16px. They should handle it the same way.

**Closed by kara** 2017-03-01 00:23 UTC
