### ISSUE TITLE
MdIconRegistry use deprecated HttpModule

### ISSUE THREAD

**Issue by alanpurple** [angular/material2#5939] opened 2017-07-21 13:48 UTC
#### Bug, feature request, or proposal:
request

#### What is the expected behavior?
should use proper @angular/common/http

#### What is the current behavior?
use deprecated HttpModule

#### What are the steps to reproduce?
see codes

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
unnecessary

**Comment by willshowell** [comment] 2017-07-21 14:08
Duplicate of https://github.com/angular/material2/issues/5814

**Closed** 2017-07-21 15:08 UTC
