### ISSUE TITLE
Angular Materials 6.3.0 Dialog is not center align after update?

### ISSUE THREAD

**Issue by Mds92** [angular/material2#11912] opened 2018-06-24 12:12 UTC
#### Bug, feature request, or proposal:
Angular Materials 6.3.0 Dialog is not center align after update?

#### What is the expected behavior?
Dialog must be in center horizontally and vertically as default

#### What is the current behavior?
Dialog is right align horizontally

#### What are the steps to reproduce?
It occurred after update material 6.2.1 to 6.3.0

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
6.3.0

#### Is there anything else we should know?
![modal](https://user-images.githubusercontent.com/4269991/41818949-9991fc08-77cd-11e8-9b09-c1006a09ff85.jpg)

**Comment by WandererInVoids** [comment] 2018-06-24 12:36
https://github.com/angular/material2/pull/11393 may be related. Share u code for open dialog

**Comment by Mds92** [comment] 2018-06-24 12:45
Thanks, I found what causes this problem.
Whenever I set `dir="rtl"` in html as follows `<html lang="en" dir="rtl">` above problem occurred.
How can I fix it?

**Comment by WandererInVoids** [comment] 2018-06-24 13:38
set options in root for MatDialogConfig or use wraper for all modal

**Comment by Mds92** [comment] 2018-06-25 02:20
I knew it, I don't know how we can set center align for dialog with `DialogPosition`

**Comment by WandererInVoids** [comment] 2018-06-25 11:18
Please see file dialog-overview-example-dialog.html, dialog-overview-example.ts it`s workaround https://stackblitz.com/edit/angular-rktjpm?file=app%2Fdialog-overview-example-dialog.html

**Comment by josephperrott** [comment] 2018-06-25 17:03
@Mds92 Please provide a reproduction of your issue as I am not able to reproduce it myself to be able to investigate the issue you are seeing.

**Comment by Mds92** [comment] 2018-06-26 02:23
Just add `dir="rtl"` to `html` tag

**Comment by josephperrott** [comment] 2018-06-26 16:49
Adding `dir="rtl"` in [this stackblitz](https://stackblitz.com/edit/angular-rktjpm-tfj3pd?file=app/dialog-overview-example.html) seems to work as expected.  Can you provide a reproduction from this fork?

**Comment by WandererInVoids** [comment] 2018-06-26 17:24
https://stackblitz.com/edit/angular-rktjpm-bemlsf?file=app%2Fdialog-overview-example.ts

**Comment by Abdullah-FAl** [comment] 2018-06-28 07:08
I have the same problem

Is there any solution

![image](https://user-images.githubusercontent.com/22343540/42018556-23fcc914-7abb-11e8-9dca-76b6c6cdbf01.png)

**Comment by Mds92** [comment] 2018-06-28 07:16
https://stackoverflow.com/questions/51009781/angular-materials-6-3-0-dialog-is-not-center-align-after-update/51063213#51063213

**Comment by josephperrott** [comment] 2018-07-02 16:14
Fixed by #11877

**Closed by josephperrott** 2018-07-02 16:14 UTC
Labels: P3, has pr
