### ISSUE TITLE
Angular cli build with AOT(--prod) is throwing error on run time on click of mat-autocomplete or any other material element, the error am getting is given below

### ISSUE THREAD

**Issue by hvngrp** [angular/material2#13210] opened 2018-09-20 08:05 UTC
`ERROR TypeError: this._document.createElement is not a function
at t._createHostElement (main.dbeb1735f9287d0af752.js:1)
at t.create (main.dbeb1735f9287d0af752.js:1)
at t._attachOverlay (main.dbeb1735f9287d0af752.js:1)
at t._handleFocus (main.dbeb1735f9287d0af752.js:1)
at Object.handleEvent (0.6098c61070f0a4810ed2.js:1)
at Object.handleEvent (main.dbeb1735f9287d0af752.js:1)
at Object.handleEvent (main.dbeb1735f9287d0af752.js:1)
at cr (main.dbeb1735f9287d0af752.js:1)
at main.dbeb1735f9287d0af752.js:1
at HTMLInputElement. (main.dbeb1735f9287d0af752.js:1)
`
 This appears only after building the angular 6 app with AOT(--PROD) and when clicking on mat-autocomplete element, this works fine without error when running the app with ng serve

Here is my package.json

{
"name": "mr",
"version": "2.1.0",
"scripts": {
"ng": "ng",
"start": "ng serve",
"build": "ng build",

},
"private": true,
"dependencies": {
"@agm/core": "1.0.0-beta.2",
"@angular/animations": "6.1.3",
"@angular/cdk": "6.4.6",
"@angular/common": "6.1.3",
"@angular/compiler": "6.1.3",
"@angular/core": "6.1.3",
"@angular/forms": "6.1.3",
"@angular/http": "6.1.3",
"@angular/material": "6.4.6",
"@angular/material-moment-adapter": "^6.4.7",
"@angular/platform-browser": "6.1.3",
"@angular/platform-browser-dynamic": "6.1.3",
"@angular/platform-server": "6.1.4",
"@angular/router": "6.1.3",
"@auth0/angular-jwt": "^2.0.0",
"ajv": "6.4.0",
"arrive": "2.4.1",
"bootstrap": "4.1.0",
"bootstrap-material-design": "4.1.1",
"bootstrap-notify": "3.1.3",
"chartist": "0.11.0",
"classlist.js": "1.1.20150312",
"core-js": "2.5.5",
"googleapis": "28.1.0",
"hammerjs": "2.0.8",
"jquery": "3.2.1",
"moment": "^2.22.2",
"ng-pick-datetime": "^5.2.6",
"ngx-bootstrap": "^3.0.1",
"perfect-scrollbar": "1.1.0",
"popper.js": "1.14.3",
"rxjs": "6.2.2",
"rxjs-compat": "6.2.2",
"web-animations-js": "2.3.1",
"zone.js": "0.8.26"
},
"devDependencies": {
"@angular-devkit/build-angular": "0.7.1",
"@angular/cli": "^6.1.4",
"@angular/compiler-cli": "6.1.4",
"@angular/language-service": "6.1.4",
"@types/bootstrap": "3.3.32",
"@types/chartist": "0.9.34",
"@types/googlemaps": "^3.30.8",
"@types/jasmine": "2.5.38",
"@types/jquery": "1.10.31",
"@types/node": "^6.0.73",
"codelyzer": "4.2.1",
"jasmine-core": "3.1.0",
"jasmine-spec-reporter": "4.2.1",
"karma": "2.0.0",
"karma-chrome-launcher": "2.2.0",
"karma-cli": "1.0.1",
"karma-coverage-istanbul-reporter": "1.4.2",
"karma-jasmine": "1.1.1",
"protractor": "^5.4.0",
"ts-node": "5.0.1",
"tslint": "5.9.1",
"typescript": "2.9.2"
}
}

Tried updating @angular-devkit/build-angular to 0.7.1 and downgrading @angular/material to 6.3.1 , still not working

**Comment by yharaskrik** [comment] 2018-09-21 21:03
This is happening to me as well
`Angular CLI: 6.2.3
Node: 8.11.3
OS: win32 x64
Angular: 6.1.8
... core

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.7.1
@angular-devkit/build-angular       0.7.1
@angular-devkit/build-optimizer     0.7.1
@angular-devkit/build-webpack       0.7.1
@angular-devkit/core                0.8.3
@angular-devkit/schematics          0.8.3
@angular/animations                 6.1.7
@angular/cdk                        6.4.7
@angular/cli                        6.2.3
@angular/common                     6.1.7
@angular/compiler                   6.1.7
@angular/compiler-cli               6.1.7
@angular/fire                       5.0.0
@angular/forms                      6.1.7
@angular/http                       6.1.7
@angular/language-service           6.1.7
@angular/material                   6.4.7
@angular/platform-browser           6.1.7
@angular/platform-browser-dynamic   6.1.7
@angular/platform-server            6.1.7
@angular/router                     6.1.7
@ngtools/webpack                    6.1.1
@schematics/angular                 0.8.3
@schematics/update                  0.8.3
rxjs                                6.3.2
typescript                          2.9.2
webpack                             4.9.2
`

**Comment by jelbourn** [comment] 2018-10-03 17:45
We can't reproduce this issue. Can someone share a repo with the issue?

**Comment by josephperrott** [comment] 2018-10-04 14:56
Closing as we are not be able to reproduce this issue.

**Closed by josephperrott** 2018-10-04 14:56 UTC
Labels: cannot reproduce, needs clarification
