### ISSUE TITLE
Unwanted right margin on hidden mat-badge with overlap=true

### ISSUE THREAD

**Issue by iget-master** [angular/material2#11649] opened 2018-06-04 17:06 UTC
#### Bug, feature request, or proposal:

Bug report.

#### What is the expected behavior?

If the mat-badge is hidden, the host element should not have right margin.

#### What is the current behavior?

Even with the mat-badge `hidden=true`, it's adding a right margin.

#### What are the steps to reproduce?

See the stackblitz: https://stackblitz.com/edit/angular-material2-issue-umayvp

#### What is the use-case or motivation for changing an existing behavior?

Try putting the `mat-badge` on a `span` inside a `mat-tab-label`, and you will see
that when the badge is hidden, the text keeps miss-aligned due the right margin:

![bug](https://user-images.githubusercontent.com/9434959/40931135-5097bfa6-6800-11e8-93df-acb5ea04377c.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 6.0.7
Angular Material 6.2.0
Any browsers, any OS.

**Comment by crisbeto** [comment] 2018-06-04 17:10
Closing as a duplicate of https://github.com/angular/material2/issues/11596 which will be resolved by https://github.com/angular/material2/pull/11599.

**Closed by crisbeto** 2018-06-04 17:10 UTC
