### ISSUE TITLE
md-dialog should block page scroll

### ISSUE THREAD

**Issue by improvise** [angular/material2#3908] opened 2017-04-05 02:39 UTC
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

When a dialog is open, the page should not scroll. Only the dialog should be scrollable.

#### What is the current behavior?

When a dialog is open, the user can still scroll the page.

#### What are the steps to reproduce?

https://plnkr.co/edit/70UnwmTG2mvLWkhOSU4a?p=preview

#### What is the use-case or motivation for changing an existing behavior?

When a dialog is open, a scrollable page in the background is confusing for the user.

In Angular Material 1, this is configurable with disableParentScroll https://material.angularjs.org/latest/api/service/$mdDialog . While that would be nice to have, disabling the behavior would work as well.

#### Which versions of Angular, Material, OS, browsers are affected?

I haven't tested extensively, but this affects at least the latest version of Angular / Material / Chrome that we're using.

**Comment by fxck** [comment] 2017-04-05 06:19
dupe of about 10 other issues.. also https://github.com/angular/material2/pull/1971

**Comment by jelbourn** [comment] 2017-04-13 22:45
Now tracking via #4093

**Closed by jelbourn** 2017-04-13 22:45 UTC
