### ISSUE TITLE
select2 component

### ISSUE THREAD

**Issue by ashgibson** [angular/material2#12816] opened 2018-08-24 08:54 UTC
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?

I build a lot of internal business applications and continuously come across the need for select2 (https://select2.org/). It would be great to get a mat-form-field compatible control that provides similar functionality to select2.

I imagine the usability would be very similar to the current mat-select but with a text input at the top of the list that appears when you click on the mat-select.

**Mat Select**
![image](https://user-images.githubusercontent.com/1744544/44575243-e6ad0380-a7ce-11e8-83fc-acafbd789e35.png)

**Select 2**
![image](https://user-images.githubusercontent.com/1744544/44575205-d006ac80-a7ce-11e8-8ae7-0c6a6ddf3f62.png)

I'd be happy to contribute to this but not sure where to start. Is there anything in the pipeline from the angular material team or can anyone recommend where to start using the cdk toolkit?

**Comment by benb7760** [comment] 2018-08-24 08:57
Duplicate of #2812

**Comment by jelbourn** [comment] 2018-08-25 19:53
This isn't something we would do directly, but any component can implement `MatFormFieldControl` to work with `<mat-form-field>`

**Closed by jelbourn** 2018-08-25 19:53 UTC
