### ISSUE TITLE
md-select field to validate on form submit even while pristine input

### ISSUE THREAD

**Issue by kenhernando** [angular/material2#5253] opened 2017-06-20 17:11 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Upon submission of form, md-select should validate even while pristine 

#### What is the current behavior?
Does not validate upon submitting untouched md-select field. Only validates after touching.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://embed.plnkr.co/0Q3kSR7wgQfCTJm6NpPY/

#### What is the use-case or motivation for changing an existing behavior?
For user to easily know which field still needs to be filled up;  to be consistent with md-input behavior.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4 - model driven forms

#### Is there anything else we should know?
Similar to this version 1 issue : [https://github.com/angular/material/issues/8529](url)

**Comment by willshowell** [comment] 2017-06-20 17:45
Looks like your plunker is broken

**Comment by crisbeto** [comment] 2017-06-20 18:14
Closing as a duplicate of https://github.com/angular/material2/issues/4611.

**Closed by crisbeto** 2017-06-20 18:14 UTC
