### ISSUE TITLE
[(ngModel)] + placeholder + Parent component OnPush = Bug

### ISSUE THREAD

**Issue by GustavoCostaW** [angular/material2#5654] opened 2017-07-10 20:05 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?

When I use a simple input like this

```html
<md-input-container>
  <input mdInput type="text" [(ngModel)]="assessment.title" name="title"
  placeholder="hello!" />
</md-input-container>
```

And the parent component is `OnPush`, the placeholder has a strange behavior:

![](https://s22.postimg.org/thlx99bm9/Screen_Shot_2017-07-10_at_16.51.55.png)

#### What are the steps to reproduce?

It's simple: http://plnkr.co/edit/g5J40Puh5rmd3saPxip5?p=preview

in `app.component.ts` uncomment the line 9 `changeDetection: ChangeDetectionStrategy.OnPush` 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular material beta 8

**Comment by willshowell** [comment] 2017-07-10 20:16
Dupe of https://github.com/angular/material2/issues/3005

**Comment by GustavoCostaW** [comment] 2017-09-21 02:04
Any update? @willshowell @ThomasBurleson

**Comment by josephperrott** [comment] 2017-09-27 21:38
It looks like this issue is no longer occuring as seen in this [reproduction](https://stackblitz.com/edit/angular-material2-issue-5654).

**Closed by josephperrott** 2017-09-27 21:38 UTC
