### ISSUE TITLE
Tooltip actually throws the exception "Failed to execute 'animate' on 'Element': Partial keyframes are not supported"

### ISSUE THREAD

**Issue by techla** [angular/material2#9247] opened 2018-01-05 10:08 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
No Exception thrown

#### What is the current behavior?
Tooltip actually throws the exception "Failed to execute 'animate' on 'Element': Partial keyframes are not supported"

#### What are the steps to reproduce?
go to angular material site on the tooltip section. Open the chrome devtool and hover some tooltiped button

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest :)

**Comment by crisbeto** [comment] 2018-01-05 10:22
I'm not getting any errors on the docs using the latest Chrome. Can you provide some more info? Also can you try running it in private mode, you might be getting a cached version of the site.

**Comment by mohlendo** [comment] 2018-01-10 09:05
It is happening on a button toggle group:

https://stackblitz.com/angular/ngypogdoyjm

**Comment by crisbeto** [comment] 2018-01-10 09:10
I'm still not seeing it. On what browser are you getting the error?

**Comment by mohlendo** [comment] 2018-01-10 09:15
Yep, it is only in beta Chrome build:
Chrome Version 64.0.3282.71 beta (64-Bit)

Cannot see it in Chrome Version 63.0.3239.132 (64-Bit)

**Comment by crisbeto** [comment] 2018-01-10 19:01
Not sure whether I'm missing anything, but I'm not getting any errors on Chrome@63.0.3239.132 stable, nor beta@64.0.3282.71 beta or Canary@65.0.3317.0.

**Comment by mohlendo** [comment] 2018-01-11 09:51
What weird sorcery is that? For me, it's gone, too! Wat?

**Comment by mohlendo** [comment] 2018-01-11 10:13
Just received a new Chrome Beta Version 64.0.3282.85 - it is definitely gone

**Comment by crisbeto** [comment] 2018-01-11 17:46
Closing the issue for now. It can be reopened if there's a repro example.

**Closed by crisbeto** 2018-01-11 17:46 UTC
Labels: cannot reproduce

**Comment by Gaulomatic** [comment] 2018-03-09 21:20
I can reproduce this, the issue is still there. Just go to the Tooltip demo on [Angular Material](https://material.angular.io/components/tooltip/overview) and open the basic example in [Stackblitz](https://stackblitz.com/angular/dyeqxmledxd?file=app%2Ftooltip-overview-example.html). Now, copy the `<span matTooltip="Tooltip!">I have a tooltip</span>` element a couple of times so you have more than one. If you then move the mouse over the `spans` fast enough, the error occurs. It's only in Chrome, neither does it happen in Safari or Firefox. My Chrome Version is `65.0.3325.146`.

**Comment by Gaulomatic** [comment] 2018-03-10 14:32
@crisbeto I investigated further. It seems to only happen on macOS, on Windows I was not able to reproduce this as well. I made a short screen cap [here](https://youtu.be/kXCUhdYpP1g).
