### ISSUE TITLE
md-radio-group not working with *ngFor and ngModel

### ISSUE THREAD

**Issue by amellnik** [angular/material2#1862] opened 2016-11-14 22:12 UTC
#### Bug, feature request, or proposal:
`md-radio-group` does not correctly bind with `ngModel` if the `ng-radio-button`s are generated dynamically with `*ngFor`.  This is one of the use cases given in the documentation for the component.  

#### What is the expected behavior?
`ngModel` should reflect the selected value.

#### What is the current behavior?
Upon loading, all values are selected.  After clicking on one item, nothing happens.  Clicking on a second item selects only that item, and further clicks move the selection around.  The variable bound with `ngModel` is always null.  

Note that if the `ng-radio-buttons` are not generated with `ngFor`, everything works as expected.

#### What are the steps to reproduce?

`ngModel` with `md-radio-group`  doesn't work on the [dev plunker](http://plnkr.co/edit/DaJBEOy5Kpb8llDPmwT1) at the moment (I'm not sure if it's pointed at an older version of material or what, but it's giving a `Can't bind to 'ngModel' since it isn't a known property of 'md-radio-group'` error).  

However, a simple example on 2.0.0-alpha.10 is:

```html
<md-radio-group [(ngModel)]="active_fish">
  <md-radio-button *ngFor="let f of fish" [value]="f.name">{{f.name}}</md-radio-button>
</md-radio-group>
```

which does not work as described above.  However, something like 

```html
<md-radio-group [(ngModel)]="active_fish">
  <md-radio-button value="Bob">Bob</md-radio-button>
  <md-radio-button value="Amir">Amir</md-radio-button>
  <md-radio-button value="Suzy">Suzy</md-radio-button>
</md-radio-group>
```

works as expected.  

(If more detail is needed to reproduce, I can generate a small project).  

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.1.1, Material 2.0.0-alpha10 and Chrome 54

#### Is there anything else we should know?

I could probably provided a plunker demo if anyone can figure out the error with it mentioned above.

**Comment by RoxKilly** [comment] 2016-11-14 22:30
@amellnik to write demos for which you control the Material and Angular version, feel free to fork from my setup and remove what you don't need. You can edit the versions near the top of `systemjs.config.js`.

[Here is the plunk](http://plnkr.co/edit/gl7dxnRv1ncauwAkxHJf?p=preview) I started for you.

**Comment by josephperrott** [comment] 2016-11-14 22:38
To use ngModel you will need to include the FormsModule from angular/forms.

```import {FormsModule}   from '@angular/forms';```

You can see a working fork from your plunkr here: http://plnkr.co/edit/WO5OL9cEBv3yxIXsttn9?p=preview

**Comment by amellnik** [comment] 2016-11-14 22:51
Thanks @RoxKilly and @josephperrott -- Joseph's version is clearly working, but a slight modification to [Rox's version](http://plnkr.co/edit/uGWVQeUf7GrkXU4mRaBj) doesn't work.  Joseph, what version of Material is yours pointing to?  I can't tell from the `system.config.js`.

**Comment by josephperrott** [comment] 2016-11-14 23:00
I just forked from the plnkr you linked to so I am unsure.

**Comment by jelbourn** [comment] 2016-11-14 23:17
@tinayuangao can you reproduce?

**Comment by tinayuangao** [comment] 2016-11-15 00:35
Can't reproduce this issue

**Comment by jelbourn** [comment] 2016-11-15 00:39
Closing as not reproducible.

**Closed by jelbourn** 2016-11-15 00:39 UTC
Labels: cannot reproduce

**Comment by ravivit9** [comment] 2017-07-19 15:31
I have the same issue with latest version of MD and angular 4.x, any input would be much helpful.

**Comment by monica7l** [comment] 2017-09-04 15:02
using _<md-radio-button [value]=_ instead of _<md-radio-button value=_ fixed it.
