### ISSUE TITLE
Allow configuration of tooltip hide delay

### ISSUE THREAD

**Issue by da45** [angular/material2#1806] opened 2016-11-10 13:58 UTC
BUG

**Comment by rolandjitsu** [comment] 2016-11-10 17:06
@da45 this is not a bug, it seems to be on purpose. Perhaps there is a plan to customize this timing globally.

**Comment by nkwood** [comment] 2016-11-10 17:08
The delay (1.5 seconds) actually conforms to the [material design spec](https://material.google.com/components/tooltips.html#tooltips-interaction): 

> On lift, display the tooltip for 1.5 seconds.

However I agree it seems too long and it would be nice if it was exposed as a configuration option.

**Comment by jelbourn** [comment] 2016-11-10 17:53
Working as intended now per [the spec](https://material.google.com/components/tooltips.html#tooltips-interaction). It will also go away if you interact with anything on the page. 

However, we should make this configurable.

**Comment by rolandjitsu** [comment] 2016-11-10 17:57
I opened a proper issue [here](https://github.com/angular/material2/issues/1808).

**Comment by jelbourn** [comment] 2016-11-10 17:57
Closing in favor of #1808

**Closed by jelbourn** 2016-11-10 17:57 UTC
