### ISSUE TITLE
md-select doesn't support typing text to move to an option

### ISSUE THREAD

**Issue by alex321** [angular/material2#5756] opened 2017-07-14 09:02 UTC
#### Feature:
Once the select is open, it should be possible to type text in order to go to (highlight) a specific option.

#### What is the current behaviour?
Typing text doesn't highlight any of the options.

#### What are the steps to reproduce?
https://material.angular.io/components/select/examples
and try to Type 'T'. It should highlight/scroll to the first option that starts with 'T' (i.e. 'Taccos') 

#### What is the use-case or motivation for changing an existing behavior?
It is a useful select functionality.

**Comment by crisbeto** [comment] 2017-07-14 09:28
Closing as a duplicate of https://github.com/angular/material2/issues/2668.

**Closed by crisbeto** 2017-07-14 09:28 UTC
