### ISSUE TITLE
Datepicker inside dialog with form execute NgSubmit when selected

### ISSUE THREAD

**Issue by richardlnnr** [angular/material2#4753] opened 2017-05-23 17:28 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Do not execute submit when selecting datepicker button.

#### What is the current behavior?
When the datepicker button is selected, the form submit is executed.

#### What are the steps to reproduce?
https://plnkr.co/edit/B2zJloz3J8IhRU6vWZQw

1º) Click in Launch dialog button.
2º) Click in datepicker button.
3º) The value of selectedOption will be 'Option 3' (ngSubmit value)

#### What is the use-case or motivation for changing an existing behavior?
When i built a dialog to insert data, this happened.

**Comment by willshowell** [comment] 2017-05-23 17:34
This is fixed in master https://github.com/angular/material2/pull/4531

**Comment by crisbeto** [comment] 2017-05-23 18:52
Closing as a duplicate of https://github.com/angular/material2/issues/4530.

**Closed by crisbeto** 2017-05-23 18:52 UTC
