### ISSUE TITLE
Should select overlay text colour change to be white in dark theme?

### ISSUE THREAD

**Issue by xmeng1** [angular/material2#4160] opened 2017-04-19 16:06 UTC
#### Bug, feature request, or proposal:

Should select overlay text colour change to be white in dark theme?

Currently, the text of overlay text colour is black which is very hard to recognise. See image below:

![iamge](http://storage6.static.itmages.com/i/17/0419/h_1492617852_7759835_081bf164fa.png)

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by kara** [comment] 2017-04-20 23:36
This looks like it could be a dupe of https://github.com/angular/material2/issues/4077, which was causing some of our sass selectors to be compiled incorrectly. Fix is here: https://github.com/angular/material2/pull/4145.  Also double-check that you've set your theme class in your overlay config if you haven't already.

**Closed by kara** 2017-04-20 23:36 UTC
