### ISSUE TITLE
Error on disposing AutoCompleteTrigger

### ISSUE THREAD

**Issue by negberts** [angular/material2#6243] opened 2017-08-03 06:55 UTC
#### Bug, feature request, or proposal:
An error occurs when trying to destroy MdAutoCompleteTrigger

TypeError: Cannot read property 'dispose' of null
    at MdAutocompleteTrigger._destroyPanel (datepicker.ts:226)
    at MdAutocompleteTrigger.ngOnDestroy (calendar.ts:301)
    at callProviderLifecycles (query.ts:1)
    at callElementProvidersLifecycles (provider.ts:619)
    at callLifecycleHooksChildrenFirst (provider.ts:603)
    at destroyView (view.ts:644)
    at callViewAction (view.ts:782)
    at execEmbeddedViewsAction (view.ts:726)
    at destroyView (view.ts:642)
    at callViewAction (view.ts:782)

#### What is the current behavior?
An error happens in the part of the code:

```
private _destroyPanel(): void {

    if (this._overlayRef) {

      this.closePanel();

      this._overlayRef.dispose();

      this._overlayRef = null;

    }

  }
```

When dispose is called the overlay is apparantly null, probably happening in closePanel?

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.2, Material Beta-8, Windows, Typescript 2.3.4

**Comment by crisbeto** [comment] 2017-08-03 09:20
How are you destroying the autocomplete?

**Comment by negberts** [comment] 2017-08-03 09:21
I am not destroying anything, it's not in the view anymore because an *ngIf is no longer valid and than the stacktrace occurs

**Comment by negberts** [comment] 2017-08-03 09:48
But obviously we are doing something wrong because a simple plunker with a ngIf works brilliantly :)

**Comment by crisbeto** [comment] 2017-08-03 10:08
We also have some tests with `ngIf` that are passing. Do you have the `ngIf` only around the trigger or is it around the `md-autocomplete` as well?

**Comment by negberts** [comment] 2017-08-03 10:38
```
<ng-template [ngIf]="currentBouwstofType">    
    <ng-template [ngIf]="currentBouwstofType.MerknaamJaNee">
        <!--Merknaam-->
        <div class="row">
            <div class="col-sm-12 col-lg-12">
                <md-input-container>
                    <input mdInput
                           autocomplete="off"
                           [(ngModel)]="merknaamTerm"
                           (blur)="onSelectMerknaam(true, merknaamTerm)"
                           #merknaamomschrijving="ngModel"
                           [mdAutocomplete]="merknaamTypeahead"
                           [registerForm]="bouwstofKaartForm"
                           [registerModel]="merknaamomschrijving"
                           name="merknaam"
                           placeholder="Merknaam"
                           maxlength="30"
                           required />
                    <span mdSuffix class="mat-input-suffix-icon">
                        <button type="button" md-icon-button [disabled]="!bouwstofModel.IsEigenaar" (click)="showMerknaamModal()" title="Bekijk merknamen" tooltip-position="below">
                            <i class="fa fa-search" aria-hidden="true"></i>
                        </button>
                    </span>
                </md-input-container>
                <md-autocomplete #merknaamTypeahead="mdAutocomplete">
                    <md-option *ngFor="let option of merknamenTypeAhead$ | async" [value]="option" (onSelectionChange)="onSelectMerknaam($event.source.selected, option)">
                        {{ option }}
                    </md-option>
                </md-autocomplete>
                <pim-validatie-meldingen [inputControl]="merknaamomschrijving"></pim-validatie-meldingen>
            </div>
        </div>
    </ng-template>
</ng-template>
```

and the field currentBouwstofType is a getter which is retrieved from a service.

```
get currentBouwstofType(): IBouwstofType {
        return this.bouwstofService.currentBouwstofType;
    }
```

**Comment by negberts** [comment] 2017-08-03 10:44
Before the value is changed a Dialog is shown with a confirm question. Maybe it uses the same overlay reference?

**Comment by hambyiii** [comment] 2017-08-04 13:57
I have a very similar setup, an autocomplete and a dialog showing and I have the same error, so you might not be far wrong to be honest. Will try and put a plunker together

**Comment by crisbeto** [comment] 2017-08-18 05:22
I don't think so. The other one was about the `ComponentRef.destroy`.

**Comment by jelbourn** [comment] 2017-08-18 15:28
Closing this one as cannot reproduce; feel free to re-open if you have more reproduction information

**Closed by jelbourn** 2017-08-18 15:28 UTC
Labels: cannot reproduce

**Comment by negberts** [comment] 2017-08-24 08:14
The error has moved somehow to datepicker with latest version? Strange thing is that we don't use the material datepicker in our app?? But it also refers to a line where a popupref is used.

TypeError: Cannot read property 'dispose' of null
    at t._destroyPanel (datepicker.ts:226)
    at t.ngOnDestroy (calendar.ts:300)
    at callProviderLifecycles (core.umd.js:11232)
    at callElementProvidersLifecycles (core.umd.js:11201)
    at callLifecycleHooksChildrenFirst (core.umd.js:11185)
    at destroyView (core.umd.js:12526)
    at callViewAction (core.umd.js:12672)
    at execEmbeddedViewsAction (core.umd.js:12610)
    at destroyView (core.umd.js:12524)
    at callViewAction (core.umd.js:12672)

**Comment by willshowell** [comment] 2017-08-24 13:32
@negberts note that the stack trace you just listed is the same as your original report, just with shortened class names. As in, I don't think anything is different between the versions.

Here's a plunk showing the autocomplete being destroyed cleanly. Any way you can reproduce with a dialog similar to what you have in your component?

https://plnkr.co/edit/Wd0Hn2iJyT20tDTorUNS?p=preview

**Comment by negberts** [comment] 2017-08-28 09:54
I couldn't reproduce with a simple plunker (https://plnkr.co/edit/FwMVjGNj5byrujFyhKFA?p=preview). I ended up with closing the yes/no modal after handling the confirm event and some extra changedetection rounds and the error went away.
