### ISSUE TITLE
Responsive Layout Directives

### ISSUE THREAD

**Issue by rachelmcgrane** [angular/material2#1078] opened 2016-08-18 23:40 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Layout directives similar to Angular Material (https://material.angularjs.org/latest/layout/container). Perhaps implemented similar to the following:
```
<div md-layout>
	<div md-layout-row>
		<div>...</div>
		<div>...</div>
	</div>
</div>
```

#### What is the current behavior?
Currently, does nothing

#### What is the use-case or motivation for changing an existing behavior?
Easily create responsive layouts using flexbox

#### Which versions of Angular, Material, OS, browsers are affected?
Angular2, angular2-material alpha 7

**Comment by m0t0r** [comment] 2016-08-19 01:32
@rachelmcgrane there is already issue #946 for it

**Comment by jelbourn** [comment] 2016-10-19 23:57
Dupe of #946

**Closed by jelbourn** 2016-10-19 23:57 UTC
