### ISSUE TITLE
md-input has different font-size within md-card

### ISSUE THREAD

**Issue by jakubweber** [angular/material2#5907] opened 2017-07-20 14:20 UTC
#### Bug, feature request, or proposal:
md-input has different font-size **within md-card,** for example if you have md-card which contains md-select, md-input on same line, it can't be aligned properly due to different font-sizes for placeholder.

#### What is the expected behavior?
Have placeholder font-size for the form elements like md-select within md-card consistent.

#### What is the current behavior?
md-input inherited style from` .mat-card-content` class, which has `font-size: 14px;` css rule. md-select has placeholder of 17px font-size.

#### What are the steps to reproduce?
Simply add md-input and md-select on the same line into md-card and you'll see the issue, the different size of placeholders.

#### What is the use-case or motivation for changing an existing behavior?
Make form elements consistent.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 2.0.0-beta.8

**Comment by crisbeto** [comment] 2017-07-20 14:53
Closing as a duplicate of https://github.com/angular/material2/issues/5262.

**Closed by crisbeto** 2017-07-20 14:53 UTC
