### ISSUE TITLE
add config to stop matdialog closing when browser back button is pressed

### ISSUE THREAD

**Issue by SpencerOdai** [angular/material2#8797] opened 2017-12-04 16:41 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
allow a config that can be set to enable/ disable location back button pressed from closing all dialog.

#### What is the current behavior?

when the back button on a browser is pressed the dialog with the form closes anyway disregarding my guard.

#### What is the use-case or motivation for changing an existing behavior?

I have a dialog with a form and deactivate guard that will open another dialog and prompt user about progressing or quitting. when the back button on a browser is pressed the dialog with the form closes anyway disregarding my guard.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/core": "^5.0.3",
    "@angular/forms": "^5.0.3",
    "@angular/http": "^5.0.3",
    "@angular/material": "^5.0.0-rc.1"

#### Is there anything else we should know?
NA

**Comment by SpencerOdai** [comment] 2017-12-15 10:49
Hi @jelbourn , any progress with this? thanks

**Comment by crisbeto** [comment] 2017-12-17 13:51
Closing as a dupe of https://github.com/angular/material2/issues/8983.

**Closed by crisbeto** 2017-12-17 13:51 UTC
Labels: discussion, feature, P5: nice to have
