### ISSUE TITLE
 mat-tab-nav-bar loses selection when focus lost

### ISSUE THREAD

**Issue by thehtcodes** [angular/material2#7993] opened 2017-10-24 11:50 UTC
#### Bug, feature request, or proposal:
The selected tab of a mat-tab-nav-bar is shown with an underline. When the focus is lost, the selected tab item is no longer shown as selected

#### What is the expected behavior?

Expected behavior would be the indicated selected tab stays selected

#### What is the current behavior?
When the focus is lost, the selected tab item is no longer shown as selected

Please advice.

Thank you!

**Comment by amcdnl** [comment] 2017-11-06 22:38
@thehtcodes - I'm not able to reproduce this. Can you make a demo showing the issue?

**Comment by josephperrott** [comment] 2018-02-22 20:31
Closing as this issue is out of date.

**Closed by josephperrott** 2018-02-22 20:31 UTC

**Comment by mariannafld** [comment] 2018-03-08 13:48
Hello
The problem (or as designed) is still exists.
When selecting tab (mat-tab in mat-tab-group), the tab is highlighted with animation and underline color is shown. If user click click outside (losing focus), the highlight is gone. Only underline color remains. It is shown in angular documentation : [https://material.angular.io/components/tabs/overview].
How can I override this behavior? Thank you in advance

**Comment by asmith2306** [comment] 2018-09-24 16:30
I also have this issue as described by @mariannafld The text color of the active tab goes back to inactive when the tab loses focus.  It is seen in the material docs linked above by @mariannafld 

This issue shouldn't have been closed.
