### ISSUE TITLE
Possible to allowthe entire customize theme not just color?  

### ISSUE THREAD

**Issue by justin73** [angular/material2#5216] opened 2017-06-19 18:26 UTC
#### Bug, feature request, or proposal:
feature request/ proposal

#### What is the expected behavior?
Be able to do deep CSS customization, not just change colors

#### What is the current behavior?
Didn't find any good solution to change angular material component CSS, such as border, margin for button, etc. 

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behaviour?
My team is creating a configurable workflow, so we will need to integrate with the customers' UI seamlessly, which means we need to adjust components CSS as much as we need, not just limited to only the color. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.1.0, Material: beta 5, OS: Win10, Typescript: 2.3.4, browsers: chrome, firefox, safari, opera, IE 

#### Is there anything else we should know?
project is angular cli based.

the only thing I've found which can allow me to change component CSS outside of its scope is to use /deep/. but chrome deprecated /deep/,  so I am not sure if this is good practice or not.

**Comment by willshowell** [comment] 2017-06-19 21:52
Looks like a duplicate of https://github.com/angular/material2/issues/3152 with resolution https://github.com/angular/material2/issues/3152#issuecomment-298454851

**Comment by jelbourn** [comment] 2017-06-20 00:56
See #3152 as @willshowell said

**Closed by jelbourn** 2017-06-20 00:56 UTC

**Comment by moravcik** [comment] 2017-10-17 15:05
@jelbourn why are you restricting this wonderful library from deeper customization or reuse in custom components? There is a whole bunch of issues demanding this feature and I think it's a pity you don't listen to users of your library. 

SCSS is not the source code at the same level as TypeScript code. You still expose types in `*.d.ts` files, so it is possible to reuse or extend every TypeScript class, but why restricting styles from customization? I believe most of concurrent UI frameworks allows such customization. We have used Bootstrap SCSS version to customize everythink we needed.

I just don't understand why there is so strict restriction when so many users are calling for it.

**Comment by jaetea** [comment] 2017-10-19 13:46
Yeah it really sucks having to set things like border-radius: 0 !important in css files.

I don't understand the point of having variables if we don't have access to changing them.
