### ISSUE TITLE
select only month and years

### ISSUE THREAD

**Issue by labyed** [angular/material2#10439] opened 2018-03-15 16:13 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
i want to choose only months and years, i don't want the user to access the day view

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by donroyco** [comment] 2018-03-15 17:30
Duplicate of #4853

**Closed** 2018-03-16 15:01 UTC
