### ISSUE TITLE
MatChip Autocomplete: setting matChipInputFor's value does not change the representation internally

### ISSUE THREAD

**Issue by Bored-Bohr** [angular/material2#12790] opened 2018-08-22 18:27 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Setting the nativeElement's value should set the state for formControl's change

#### What is the current behavior?
`input.nativeElement.value = ''` does not change the internal value.
Setting nativeElement's value does not trigger a change for formControl.

#### What are the steps to reproduce?
Change fails to occur when same letter is in input
1. type `a` into input
2. select the first autocomplete option
3. type `a` into input again
4. notice that the autocomplete fails to populate
5. type `p` as the second letter
6. autocomplete correctly populates after

Change occurs when different letter is in input
1. type `a` into input
2. select the first autocomplete option
3. type `l` into input
4. notice that the autocomplete correctly populates

Autocomplete example from material.angular.io
https://stackblitz.com/angular/lroeoekyaaj?file=app%2Fchips-autocomplete-example.ts

#### What is the use-case or motivation for changing an existing behavior?
If a user wants to rapidly add new chips, they should be able to use autocomplete.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 6.0.8
Node: 8.11.1
OS: win32 x64
Angular: 6.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.4.5
@angular/cli                      6.0.8
@angular/material                 6.4.5
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

Tested on Chrome and IE11

**Comment by josephperrott** [comment] 2018-09-07 15:11
Closing as duplicate of #12621

**Closed by josephperrott** 2018-09-07 15:11 UTC
