### ISSUE TITLE
Expansion Panel - Customize Expansion Panel Header Height Request

### ISSUE THREAD

**Issue by djarekg** [angular/material2#7073] opened 2017-09-14 13:36 UTC
#### Bug, feature request, or proposal:
Feature request.

#### What is the expected behavior?
Customize expansion panel header height.

#### What is the current behavior?
Currently the expansion panel header class is fixed. You can override the collapsed height, but the height is hard coded into the animations.

#### What are the steps to reproduce?
N/A

#### What is the use-case or motivation for changing an existing behavior?
If you have content to put in header that has a height larger than the fixed default.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.0-rc.0
Material 2.0.0-beta.10
Windows 10
TypeScript 2.5.2
Browsers (all)

**Comment by willshowell** [comment] 2017-09-14 14:17
You're in luck. This will be included in the next release https://github.com/angular/material2/pull/6643.

**Comment by crisbeto** [comment] 2017-09-14 16:36
Closing as a duplicate of https://github.com/angular/material2/issues/5641.

**Closed by crisbeto** 2017-09-14 16:36 UTC
