### ISSUE TITLE
dialogRef.close()

### ISSUE THREAD

**Issue by dharveshmydeen** [angular/material2#4118] opened 2017-04-17 07:27 UTC
Hi,
How do i close my dialog from  dialog calling compoent

(or)

I need to close my dialog while press the back button  in my browser

**Comment by Golosay** [comment] 2017-04-17 08:31
You should import **MdDialogRef** in your child component and use it with your component.
```
import {MdDialogRef} from '@angular/material';

export class ModalComponent implements OnInit {
   constructor(public dialogRef: MdDialogRef<ModalComponent>) {}

   closeModal() {
       this.dialogRef.close(); //call this code, when you want to close modal
   }
}
```

**Comment by crisbeto** [comment] 2017-04-17 19:57
The answer from @Golosay is correct. Closing as a non-issue.

**Closed by crisbeto** 2017-04-17 19:57 UTC

**Comment by VishalChorghe** [comment] 2017-10-05 08:58
I tried using this.dialogRef.close(). still not able to close popup. I am opening AdminComponent as a Popup.
Admin.component.ts- 
export class AdminComponent implements OnInit {
constructor( public dialogRef: MdDialogRef<AdminComponent>) {}
closeModal() {
          console.log('closing');
      this.dialogRef.close();
      }
}

Thank you for your help

**Comment by switch87** [comment] 2017-11-02 07:32
I have the same problem, dialogRef.close() does nothing. 
I tested with dialogRef.updateSize to be sure my import and initialization where correct. updateSize on the same modal works.
The problem is with 0ne modal only, this modal is opened om top of a other modal.

`onCancelClicked() {`
`    console.log("onCancelClicked"); //works`
`    this.dialogRef.close(); //does nothing`
`    this.dialogRef.updateSize("150px","20px"); //works`
`}`

**Comment by switch87** [comment] 2017-11-02 08:01
I solved my problem, it was a @input statement that was badly configured in the parent view. error had nothing to do with material.

**Comment by aykutyararbas** [comment] 2018-01-22 05:37
switch87 - Can you please describe the input issue. I am facing a similar issue, it'd be really helpful.

**Comment by switch87** [comment] 2018-01-22 12:38
@aykutyararbas I don't know what it was anymore. But it didn't have anything to do with the dialog at all.

**Comment by aykutyararbas** [comment] 2018-01-23 03:07
@switch87  No worries, thanks.
