### ISSUE TITLE
Progress Spinner Example Color Doesn't Update

### ISSUE THREAD

**Issue by gioragutt** [angular/material2#4727] opened 2017-05-22 20:37 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
https://material.angular.io/components/component/progress-spinner

The progress spinner color should change when you click the different color radio buttons

#### What is the current behavior?

The spinner color always stays `primary`

#### What are the steps to reproduce?

Enter the link above, click the different radio buttons

#### What is the use-case or motivation for changing an existing behavior?

...

#### Is there anything else we should know?

Looking at the code behind the example, it seems that `[attr.color]` is used instead of `[color]`. I believe this is the cause of the bug

**Comment by DevVersion** [comment] 2017-05-22 20:52
Here is a PR that fixes the issue https://github.com/angular/material2/pull/4687. Also closing this as a duplicate of #4617

**Closed by DevVersion** 2017-05-22 20:52 UTC
