### ISSUE TITLE
DatePicker with TimePicker or DateTime Picker

### ISSUE THREAD

**Issue by ameya** [angular/material2#10522] opened 2018-03-22 06:10 UTC
proposal: DataPicker UI modified to add time picker options.

What is the expected behavior?
Need time picker option in the current date picker provided.

What is the current behavior?
Onlyb date picker is available

What are the steps to reproduce?
Implement data picker material component.

What is the use-case or motivation for changing an existing behavior?
Scheduling an event we need to add time also.

Which versions of Angular, Material, OS, TypeScript, browsers are affected?
2

**Comment by donroyco** [comment] 2018-03-22 07:52
Please use the search function before opening duplicate issues. Duplicate of #5648 and also 
a [couple of times requested](https://github.com/angular/material2/issues?utf8=%E2%9C%93&q=is%3Aissue+%22time+picker%22+is%3Aclosed+).

**Comment by josephperrott** [comment] 2018-03-27 15:06
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate

**Closed by josephperrott** 2018-03-27 15:06 UTC

**Comment by torabian** [comment] 2018-11-23 11:02
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
