### ISSUE TITLE
md-tab: Option to turn off the content sliding animation.

### ISSUE THREAD

**Issue by geshort** [angular/material2#4004] opened 2017-04-10 00:59 UTC
#### Bug, feature request, or proposal:
When you click on a tab, the content from the new tab sides in. This is cute, but it is dis-orientating to the user for the way we are using the tab group. Each tab has slightly varying content, which is hard to detect with the animation. 

There needs to be a way to turn off this sliding in/out of the tab content?

#### What is the expected behavior?
No sliding of the tab content, it should just appear when you click on a new tab header.

#### What is the current behavior?
The old tab content slides out and the new tab content slides in.

#### What are the steps to reproduce?
This the the default behavior for the md-tab tag.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
The sliding of the content is dis-orientating for the user, especially when the content has only minor differences.

#### Which versions of Angular, Material, OS, browsers are affected?
The latest as of April 2017.

**Comment by dmacfarlane** [comment] 2017-04-12 00:27
Duplicate of #2706?

**Comment by geshort** [comment] 2017-04-12 01:24
Yes, this looks like the same issue as #2706

**Closed** 2017-10-19 18:23 UTC
Labels: discussion, feature, mat-tabs
