### ISSUE TITLE
Material form components should support RC.2 REACTIVE_FORM_DIRECTIVES

### ISSUE THREAD

**Issue by udos86** [angular/material2#704] opened 2016-06-16 22:37 UTC
#### Bug, feature request, or proposal: 
Proposal

#### What is the expected behavior? 
Material Components fully supporting `REACTIVE_FORM_DIRECTIVES` (`[formControlName]`, etc.)  of RC.2 [angular/forms](https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub)

#### What is the current behavior?
An exception `No value accessor` is thrown when trying to bind `[formControlName]` from `REACTIVE_FORM_DIRECTIVES` to a Material component

**Comment by jelbourn** [comment] 2016-06-17 17:45
Dupe of #696

**Closed by jelbourn** 2016-06-17 17:45 UTC
