### ISSUE TITLE
StaticInjectorError for 'MAT_DRAWER_DEFAULT_AUTOSIZE' on Server Side Render production build

### ISSUE THREAD

**Issue by zahid492** [angular/material2#10272] opened 2018-03-05 14:58 UTC
#### Bug, feature request, or proposal:
```
ERROR Error:StaticInjectorError[InjectionToken MAT_DRAWER_DEFAULT_AUTOSIZE]: 
  StaticInjectorError[InjectionToken MAT_DRAWER_DEFAULT_AUTOSIZE]: 
    NullInjectorError: No provider for InjectionToken MAT_DRAWER_DEFAULT_AUTOSIZE!
```
![0bdb55240a3507ebba8b06330655a478819dfc5f121d7e273c pimgpsh_mobile_save_distr](https://user-images.githubusercontent.com/5306919/36981603-cfcca704-20b7-11e8-96ad-49edd2f85dd1.jpg)

#### What is the current behavior?
Server side render not possible, app broken at initial stage. 

#### What are the steps to reproduce?

Aot and normal ng serve is fine. When produce production build for server side render . Build have smoth without have any error but when goes to browser same error occurred. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.0.3
Angular Material: 5.0.3
Angular CLI: 1.6.5
Typescript: 2.4.2
Browsers : All
OS: Windows-10 (64 Bit)

**Comment by crisbeto** [comment] 2018-03-05 18:04
Could you post how you're overriding the token?

**Comment by josephperrott** [comment] 2018-03-26 15:05
Closing as we are unable to reproduce the issue.

**Closed by josephperrott** 2018-03-26 15:05 UTC

**Comment by cyphercodes96** [comment] 2018-05-08 13:50
Same Issue when upgrading to angular 6
