### ISSUE TITLE
matInput with "type" = "search fails to show X symbol

### ISSUE THREAD

**Issue by inthegarage** [angular/material2#13315] opened 2018-09-26 10:31 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If I specify type="search" then I should see a angular material styled cross by the matinput

#### What is the current behavior?
No cross is observed

#### What are the steps to reproduce?
https://angular-ifg1fb.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?
There should be a cross for search inputs. Otherwise there's no point in supporting this control.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All, the material CSS overrides the original web-kit directive:

    -webkit-appearance: searchfield;

With the following:
    -webkit-appearance: none;

#### Is there anything else we should know?
The CSS in question:
.mat-input-element, .mat-input-element::-webkit-search-cancel-button, .mat-input-element::-webkit-search-decoration, .mat-input-element::-webkit-search-results-button, .mat-input-element::-webkit-search-results-decoration {

Angular material version ="@angular/material": "^6.4.1",

**Comment by crisbeto** [comment] 2018-09-26 10:38
The native browser button was hidden, because not all browsers support it and it could conflict with any icons that are set as a `matPrefix`. You can set your own clear button using a `matSuffix` which will look and behave the same in all browsers. [There are some examples in the docs](https://material.angular.io/components/form-field/overview).

**Comment by jelbourn** [comment] 2018-09-27 00:16
Closing as intended behavior.

**Closed by jelbourn** 2018-09-27 00:16 UTC

**Comment by inthegarage** [comment] 2018-09-27 08:04
@jelbourn @crisbeto 
The following page has no mention of matSuffix and states that this type is supported:
https://material.angular.io/components/input/overview

I'm not sure supported really constitutes hiding the very feature that gives an input field a search feature.
I will add some override CSS to my project to override this behaviour, , however I'm not convinced that angular material is supporting type="search" and that adding more directives is the solution. 
Wouldn't it be easier to check if type="search" is specified and act accordingly for each browser, looking at this it seems this feature is supported everywhere:
https://caniuse.com/#search=search

At least can we update the documentation so that it's clear what supported means in this case and to use matSuffix? It's ambiguous at the moment.
