### ISSUE TITLE
[Bug] Datepicker shows incorrect month

### ISSUE THREAD

**Issue by rafaelss95** [angular/material2#4955] opened 2017-06-03 19:56 UTC
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
The datepicker should open at the correct month.

#### What is the current behavior?
Datepicker doesn't display the correct month if you use a custom locale like this: `this.dateAdapter.setLocale('pt-BR');` and select a day **lower** than 13.

#### What are the steps to reproduce?
Select a day **lower** than 13 and open the datepicker again.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
https://plnkr.co/edit/gkYoHKauuzfvtRDMmwtl?p=info

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.1.3
Material: 2.0.0-beta.6
Browsers: Chrome (I only tested on this).

**Comment by julianobrasil** [comment] 2017-06-03 20:08
Dupe of #4832. Take a look at that. You'll have to build up your adapter.

**Comment by julianobrasil** [comment] 2017-06-03 20:12
In fact, just copy the [one provided by the Angular team](https://github.com/angular/material2/tree/master/src/lib/core/datetime) here in the github and customize it a little bit:

```
/** The default month names to use if Intl API is not available. */
const DEFAULT_MONTH_NAMES = {
  'long': [
    'January', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro',
    'Outubro', 'Novembro', 'Dezembro'
  ],
  'short': ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
  'narrow': ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D']
};


/** The default date names to use if Intl API is not available. */
const DEFAULT_DATE_NAMES = range(31, i => String(i + 1));


/** The default day of the week names to use if Intl API is not available. */
const DEFAULT_DAY_OF_WEEK_NAMES = {
  'long': ['Domingo', 'Segunda-Feira', 'Terça-Feira', 'Quarta-Feira', 'Quinta-Feira', 'Sexta-Feira', 'Sábado'],
  'short': ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
  'narrow': ['D', 'W', 'T', 'Q', 'Q', 'S', 'S']
};
```

and change the parse function:

```
parse(value: any, parseFormat: Object): Date | null {
    // We have no way using the native JS Date to set the parse format or locale, so we ignore these
    // parameters.
    if (value && (typeof value !== 'object') && (value.indexOf('/') > -1)) {
      const str = value.split('/');
      value = new Date(Number(str[2]), Number(str[1]) - 1, Number(str[0])).toString();
    }
    const timestamp = typeof value === 'number' ? value : Date.parse(value);
    return isNaN(timestamp) ? null : new Date(timestamp);
  }
```

**Comment by rafaelss95** [comment] 2017-06-03 22:58
Hi @julianobrasil, I saw that issue and that's why I found the `setLocale` (I haven't found anywhere else)... 

In my opinion, I don't need to build my own adapter since almost everything are being correctly displayed. The only issue that I'm facing is that you can in plunker: 

1 - Select a day lower than 13;
2 - Open the datepicker... you'll see that it'll open in a different month.

I really don't know why it happens only if I select a day lower than 13... maybe a conflict with months (0 - 12)?

**Comment by julianobrasil** [comment] 2017-06-03 23:09
It's the parse function. And that's why you need to build your adapter. By
default, it expects the english Format (month/data/year) date at the input
(and that is also the reason the problem apears to be just in days greater
than 12 (the parser thinks that number is a month).

Em 3 de jun de 2017 7:58 PM, "Rafael Santana" <notifications@github.com>
escreveu:

**Comment by julianobrasil** [comment] 2017-06-03 23:42
Take a look at this plunker, it's working: https://plnkr.co/edit/FlgGpjqyDlypas0VZJzo?p=preview

**Closed** 2017-06-06 01:00 UTC

**Comment by rafaelss95** [comment] 2017-06-10 01:46
Hey @julianobrasil,  

Again thanks for sharing this adapter. Now that you pointed me to the right direction on creating adapters I'm just wondering if it can be set dynamically. 

In a nutshell: I have some custom _adapters_, how to provide it?

Once the language is changed, all the datepickers in application must change to this specific format (language).

Did you understand me? I'm sorry to asking it, but it's totally unclear in docs.

**Comment by julianobrasil** [comment] 2017-06-10 11:11
@rafaelss95 , technically you can overide the parse function directly in the component. So, create a function with this signature: `(value: any) => Date | null` and set it to the parse attribute of the DateAdapter.

See this modified plunker (a took away the CustomAdapter and made everything in the component class): https://plnkr.co/edit/KaRCs7?p=preview

Well, from here, I think you can find a way (maybe a service) to make it globally from your custom adapters.

**Comment by angular2fan** [comment] 2017-06-16 11:22
@julianobrasil - thanks for sharing the plnkr and that gave me a headstart. However, I am trying to limit the date input to contain only numbers and if anything else is entered, it has to display me the error message. I am playing with the plnkr link you provided but not able to achieve it. Can you please help me. thanks

**Comment by julianobrasil** [comment] 2017-06-16 11:30
You have a few options here. One is building a directive that allows just numbers and the date separator (slashes, dashes, points etc).  It would also have to check whether the user typed the right numbers of digits  for days, months and year. You'd end up having to build a masking component. It's not that complicated, but you have a mddatepicker to save you from all this work.

Instead of using a trigger button, just use a (focus) event to open the datepicker. It forces the user to choose a date from calendar instead of typing it. Take a look at it over here: https://plnkr.co/edit/wkD1HZ?p=preview

**Comment by angular2fan** [comment] 2017-06-16 11:49
hmmm, i tried this approach but one problem is if the field is not a mandatory field and want to clear off the existing selection, i am not able to do it..:(

**Comment by julianobrasil** [comment] 2017-06-16 12:01
I didn't get it... why didn't you manage to clear it? I've updated the plunker, but don't know if I'm following you: https://plnkr.co/edit/wkD1HZ?p=preview

**Comment by angular2fan** [comment] 2017-06-16 12:04
@julianobrasil - :). it's my bad. I am in a time crunch and my mind is not functioning properly. Thanks so much for your help. this is the best solution.
