### ISSUE TITLE
Mobile responsiveness ?

### ISSUE THREAD

**Issue by lakinmohapatra** [angular/material2#7182] opened 2017-09-19 20:17 UTC
#### Bug, feature request, or proposal:

Feature request
#### What is the expected behavior?
mobile responsiveness

#### What is the current behavior?
No mobile responsiveness

Please add components for adding mobile responsiveness as like materialize.css grids.

**Comment by wyers** [comment] 2017-09-19 20:34
there is a separate project that helps do this
https://github.com/angular/flex-layout

**Comment by josephperrott** [comment] 2017-09-19 23:02
Closing as duplicate of #45

**Closed by josephperrott** 2017-09-19 23:02 UTC
