### ISSUE TITLE
md-input-containers text and floating label misaligned when using mdPrefix

### ISSUE THREAD

**Issue by WillAnd31** [angular/material2#3229] opened 2017-02-21 19:40 UTC
When using a `md-icon` as a prefix to an input inside of an `md-input-container` the floating label gets misaligned when using a `mdPrefix`, as you can see below:

<img width="343" alt="screen shot 2017-02-21 at 12 30 40 pm" src="https://cloud.githubusercontent.com/assets/11418316/23181315/c29b510c-f831-11e6-8c5e-5b51b7bc34e4.png">
<img width="336" alt="screen shot 2017-02-21 at 12 31 33 pm" src="https://cloud.githubusercontent.com/assets/11418316/23181318/c502634a-f831-11e6-8a12-5dfaee7ce59a.png">

The expected behavior is to have the text aligned with the icon and also have the floating label be at the correct position. As you can see when there is no `mdPrefix` icon the text is all aligned how it should be:

<img width="321" alt="screen shot 2017-02-21 at 12 31 01 pm" src="https://cloud.githubusercontent.com/assets/11418316/23181407/21b2790e-f832-11e6-8c50-83ff13159d4b.png">
<img width="333" alt="screen shot 2017-02-21 at 12 31 16 pm" src="https://cloud.githubusercontent.com/assets/11418316/23181408/23890d92-f832-11e6-81ea-c23abb6539aa.png">

To reproduce this simply add a `mdPrefix` to a `md-input-container`.
Before:
```
<md-input-container>
    <input mdInput placeholder="text" type="text" name="example">
</md-input-container>
```
and after:
```
<md-input-container>
    <md-icon mdPrefix>email</md-icon>
    <input mdInput placeholder="text" type="text" name="example">
</md-input-container>
```

Right now using `mdPrefix` is making the input not look good. If I am using mdPrefix wrong please let me know.

**Comment by fxck** [comment] 2017-02-22 16:22
dupe of https://github.com/angular/material2/issues/2586 I believe

**Closed** 2017-03-13 21:21 UTC
Labels: has pr, P3: important
