### ISSUE TITLE
Support validation errors on checkboxes and radio buttons

### ISSUE THREAD

**Issue by anthony-o** [angular/material2#11333] opened 2018-05-15 09:02 UTC
#### Bug, feature request, or proposal:
Support validation errors in checkboxes and radio buttons. For instance, displaying radio button labels in red when required `mat-radio-group` was not filled-in.

#### What is the expected behavior?
[This stackblitz](https://mat-radio-group-validation.stackblitz.io) should display red label on the radio buttons when clicking on "Submit".
It contains one required `mat-radio-group` (with multiple `mat-radio-button`s in it) and one required `input`.

#### What is the current behavior?
Currently, only the text `input` in the `mat-form-field` is correctly displayed in red when clicking on Submit.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.0 as well as 6.0.0

**Comment by josephperrott** [comment] 2018-05-30 20:55
Duplicate of #7891

**Closed by josephperrott** 2018-05-30 20:55 UTC

**Comment by andresroberto** [comment] 2019-08-01 20:13
#7891 was about using checkbox and radio inside a form-field. This issue is about supporting error highlighting in checkboxes and radio buttons not necessarily by using checkbox and radio inside a form-field, so even though they are related I don't think this is a duplicate. And I also think that it would be awesome to have the required radio buttons get red when trying to submit them empty.
