### ISSUE TITLE
Better positioning of an icon in mat-icon-button

### ISSUE THREAD

**Issue by AlexNasonov** [angular/material2#10404] opened 2018-03-13 22:01 UTC
#### Bug, feature request, or proposal:
` <button mat-icon-button><mat-icon>icon</mat-icon></button>`
Change mat-icon CSS `line-height` from 24px to 20px to make icon position exactly in the center of the ripple circle. With 24px it seems to be closer to the bottom.

**Comment by josephperrott** [comment] 2018-03-26 15:43
Closing as the styling is working as intended.  The `line-height` and `height` are set as the same so the icon's imagery is placed centered.

**Closed by josephperrott** 2018-03-26 15:43 UTC

**Comment by maxisam** [comment] 2018-07-12 17:43
So my case is a bit different. If I use icon inside a raised button, it doesn't align correctly. I noticed there is no line-height set in the mat-icon https://github.com/angular/material2/blob/master/src/lib/icon/icon.scss
, should we have something like this there?

```
line-height: $mat-icon-size;
```
