### ISSUE TITLE
Button and Input typography not configurable via mat-typography-config function

### ISSUE THREAD

**Issue by bellizio** [angular/material2#13063] opened 2018-09-10 18:35 UTC
#### Bug, feature request, or proposal:
Bug, proposal

#### What is the expected behavior?
Calling `mat-typography-config` function should allow customization of buttons and input typography.

#### What is the current behavior?
Button and input typography cannot be customized via the `mat-typography-config` function.

#### What are the steps to reproduce?
Refer to the steps describing typography customization [here](https://github.com/angular/material2/blob/master/guides/typography.md#customization). 
1. Adjust the parameters of the `mat-typography-config` so that it looks like the code below:
```
$custom-typography: mat-typography-config(
  $button: mat-typography-level(16px, 16px, 400),
  $input: mat-typography-level(18px, 18px, 500)
);
```
2. Include the following mixin:
```
@include mat-base-typography($custom-typography);
```
3. Run/view app in browser
4. Inspect any `button` or `input` element
5. Observe that a `button` or `input` element's styles are not overridden (i.e. custom font-size, etc. defined above are not applied)

#### What is the use-case or motivation for changing an existing behavior?
In order to override button and input typography, it requires calling the `mat-button-typography` or `mat-input-typography` mixins directly. A simplified approach would be to have the option to override button and input typography via the `mat-typography-config` function.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.x, Material 6.4.7, MacOS, Typescript 2.9.x, Chrome browser

#### Is there anything else we should know?
The `mat-typography-config` function in `~@angular/material/theming` includes $button and $input parameters, but __does not include__ .mat-* selectors for buttons and inputs to apply the custom styles passed into it, which I believe to be the reason why the typography for those elements cannot be customized via that function.

**Comment by crisbeto** [comment] 2018-09-10 18:44
The `mat-base-typography` only includes the basic typography styles for things like body text, headers etc. You can use `angular-material-typography` if you want to change the typography for all components (including the base) or `mat-button-typography` and `mat-input-typography` to target those two components in particular.

**Comment by bellizio** [comment] 2018-09-10 18:58
@crisbeto right, yeah I was aware of the alternatives. However, as mentioned in the issue above, I think it is misleading to have $button and $input included as parameters of the `mat-typography-config` function:

<img width="557" alt="screenshot 2018-09-10 14 57 57" src="https://user-images.githubusercontent.com/2282499/45318095-e79d9f00-b509-11e8-9cb7-a0575e534684.png">

**Comment by crisbeto** [comment] 2018-09-10 19:17
The properties are called `button` and `input`, because they're based on the previous iteration of the Material Design spec. You can see that there's still a `button` in the new iteration as well: https://material.io/design/typography/the-type-system.html#type-scale.

**Comment by bellizio** [comment] 2018-09-10 19:55
@crisbeto I know. My point is that inside the function the styles are not applied to button and input elements with their respective class name selectors. E.g. `.mat-button`

**Comment by crisbeto** [comment] 2018-09-11 15:14
That's because the function only defines the breakpoints and then it's up to the individual mixins to apply the values. See: https://github.com/angular/material2/blob/master/src/lib/button/_button-theme.scss#L122.

**Comment by jelbourn** [comment] 2018-09-11 20:14
Closing this since it is working as intended; the "core" typography intentionally doesn't affect specific components because there's no guarantee that a user will be consuming those components. Someone may want to make a custom button component while still consuming the "button" typographic settings.

**Closed by jelbourn** 2018-09-11 20:14 UTC
