### ISSUE TITLE
Gesture doesn't work on android

### ISSUE THREAD

**Issue by csbenjamin** [angular/material2#13374] opened 2018-10-01 12:30 UTC
#### Bug, feature request, or proposal:
tap or press event does not fire on android/chrome

#### What are the steps to reproduce?
See the example below. On linux/chrome when you click the button, it logs the click and tap event. When you long press it logs the press event and when you release the button after long press, it logs the click event. On android/chrome if you tap the button it logs only the click event and if you long press it logs nothing.

https://angular-kicomb.stackblitz.io

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
See the exemple above.

**Comment by josephperrott** [comment] 2018-10-02 15:19
Closing as this is unrelated to @angular/material as these are native events from the `button`.

Additionally, I was not able to reproduce this.  Opening your stackblitz reproduction on an android device, taps and presses were fired as expected.

**Closed by josephperrott** 2018-10-02 15:19 UTC

**Comment by csbenjamin** [comment] 2018-10-03 01:18
@josephperrott Thanks for the answer. what is the version of your android and what browser are you using to test it? Have a look at [this video](https://youtu.be/dyjREfpCWEY) and see what happens on my galaxy note 5.
