### ISSUE TITLE
The width of options of select input are not dynamically.

### ISSUE THREAD

**Issue by Dominik-Andreas-Geng** [angular/material2#8952] opened 2017-12-12 11:16 UTC
#### Bug, feature request, or proposal:
**Bug**

#### What is the expected behavior?
The width of options in a select input have to be the same width as parent.

#### What is the current behavior?
The options overflows the parent if the size has changed (to smaller size).
On browser resize or sidenav hide / show. The options width is set on first click on mat-select.

#### What are the steps to reproduce?
1. Click on mat-select to view options. (options width is same as parent)
2. Resize the mat-select indirectly by parents. (e.g. browser or sidenav toggle)
3. Click on mat-select again to view the options. (options width is over- or underflow. not the same width as parent)

#### What is the use-case or motivation for changing an existing behavior?
Looks ugly and is a terrible ux. The page looks buggy. It's fact that this is a bad behavior.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
**5.0.1** (but also occurs below) 

#### Is there anything else we should know?
[See Example on Stackblitz](https://stackblitz.com/edit/angular-material-select-width-bug)
Or download the exported project of original stackblitz demonstration.
[angular-material-select-width-bug.zip](https://github.com/angular/material2/files/1551323/angular-material-select-width-bug.zip)

Here's a screen record.
![screen](https://user-images.githubusercontent.com/28209992/33881844-65327ff8-df36-11e7-9ac4-1eecfa1e5bab.gif)

**Comment by julianobrasil** [comment] 2017-12-12 11:35
It seems to be tracked in #7811.

**Comment by crisbeto** [comment] 2017-12-12 19:36
Closing as a dupe of https://github.com/angular/material2/issues/7811.

**Closed by crisbeto** 2017-12-12 19:36 UTC
