### ISSUE TITLE
Indeterminate progress bar animation broken on Firefox 57

### ISSUE THREAD

**Issue by praneetloke** [angular/material2#8469] opened 2017-11-16 05:26 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Progress bar animation plays smoothly.

#### What is the current behavior?
Progress bar animation shows breaks in frames.

#### What are the steps to reproduce?
The issue can be seen on the docs site. https://material.angular.io/components/progress-bar/overview
I have also uploaded a gif of what I am seeing to https://imgur.com/a/lKxdL.

#### What is the use-case or motivation for changing an existing behavior?
N/A

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
The versions of Angular, Material, and TypeScript that the https://material.angular.io site is using at the time of writing. The browser is Firefox 57.

#### Is there anything else we should know?
The progress spinner is fine. It's just the progress bar that seems to be experiencing an issue whilst playing the animation.

Granted that the FF 57 has only been out in release form for a day but I thought this should be tracked for a fix.

**Comment by melton3** [comment] 2017-11-16 06:25
works fine in my firefox v57

**Comment by crisbeto** [comment] 2017-11-16 07:30
Closing as a duplicate of https://github.com/angular/material2/issues/7606.

**Closed by crisbeto** 2017-11-16 07:30 UTC
