### ISSUE TITLE
Transform to center dialog blurs content in Chrome

### ISSUE THREAD

**Issue by glendaviesnz** [angular/material2#1538] opened 2016-10-20 00:47 UTC
I realise the MdDialog is not finished yet, but just in case this has not been noticed/covered off already yet

I would expect that text content in the dialog would have the same appearance as in standard browser window.

However, in Chrome text content is currently blurred compared to text in main window.

If the 
transform: translateX(-50%) translateX(0px) translateY(-50%) translateY(0px); 
that is applied the md-overlay-pane to center it is removed the text displays as expected. 

Attached images show the difference in text display between transform on and off. 
with transform
![transform](https://cloud.githubusercontent.com/assets/3629020/19542443/af1948aa-96ca-11e6-9bb3-9297d7b52346.png)
without transform
![notransform](https://cloud.githubusercontent.com/assets/3629020/19542444/af1a8c2e-96ca-11e6-812e-0fb50ba0a8ca.PNG)

I see there was a similar issue with Angular Material 1. Screenshots are from Chrome version 53.0.2785.143

**Comment by jelbourn** [comment] 2016-10-20 15:48
Dupe of #932

**Closed by jelbourn** 2016-10-20 15:48 UTC
