### ISSUE TITLE
Sugestion: show the value inside the determinate md-progress-spinner

### ISSUE THREAD

**Issue by MaickelHubner** [angular/material2#6940] opened 2017-09-08 12:57 UTC
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Show the value inside the determinate md-progress-spinner

#### What is the current behavior?
Nothing is showed

#### What is the use-case or motivation for changing an existing behavior?
To use in dashboards, etc.

**Comment by willshowell** [comment] 2017-09-08 13:15
See https://github.com/angular/material2/issues/1488. There is a PR (https://github.com/angular/material2/pull/1994) that got held up for accessibility reasons.

**Comment by MaickelHubner** [comment] 2017-09-08 13:33
(Y)

**Comment by MaickelHubner** [comment] 2017-09-08 13:33
Ok. Thanks

**Comment by josephperrott** [comment] 2017-09-11 20:07
Closing as duplicate of #1488

**Closed by josephperrott** 2017-09-11 20:07 UTC
