### ISSUE TITLE
Sidenav: In mode='over', first element in md-sidenav with an md-button attribute is being focused incorrectly.

### ISSUE THREAD

**Issue by joh04667** [angular/material2#3289] opened 2017-02-24 17:14 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-buttons will display hover or focus CSS only when they are focused or hovered.

#### What is the current behavior?
When there is an element with an `md-button` attribute in the sidenav, the first element will be focused (i.e. gain the `"mat-button-focus"` class) as soon as any element with the `md-button` attribute is moused over. It will retain this class even as other `md-buttons` are moused over. It will be removed on normal blur events, i.e. mouse click

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker: https://plnkr.co/edit/i572Ask8Lxlj8uKffFkO?p=preview
(A workaround is to place an invisible element with `md-button` first in the sidenav; uncomment the `<a>` tag for example)

#### Which versions of Angular, Material, OS, browsers are affected?
All browers, Angular 2.4.8, Material 2.0.0-beta.2.

#### Is there anything else we should know?
This only happens in `mode="over"`. Also tested with no `md-list` and with using `<button>`s instead of `<a>`s

**Comment by kara** [comment] 2017-02-24 17:45
This looks like a dupe of https://github.com/angular/material2/issues/3282

**Closed by kara** 2017-02-24 17:45 UTC
