### ISSUE TITLE
Table-http example errors.

### ISSUE THREAD

**Issue by Batisska** [angular/material2#7521] opened 2017-10-04 07:41 UTC
I copy the [example](https://github.com/angular/material2/blob/master/src/material-examples/table-http/table-http-example.html) into my educational project. What is the error and how to fix it?

```
core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: The "mat-" prefix cannot be used in ng-material v1 compatibility mode. It was used on an "mat-table" element.
Error: The "mat-" prefix cannot be used in ng-material v1 compatibility mode. It was used on an "mat-table" element.
    at getMdCompatibilityInvalidPrefixError (core.es5.js:55)

```

users.component.ts
```import {Component, OnInit, ViewChild} from '@angular/core';
import {Http} from '@angular/http';
import {DataSource} from '@angular/cdk/collections';
import {MatPaginator, MatSort} from '@angular/material';
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/merge';
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/startWith';
import 'rxjs/add/operator/switchMap';

@Component({
  selector: 'app-users',
  templateUrl: './users.component.html',
  styleUrls: ['./users.component.scss']
})

export class UsersComponent implements OnInit {
  displayedColumns = ['created_at', 'state', 'number', 'title'];
  exampleDatabase: ExampleHttpDao | null;
  dataSource: ExampleDataSource | null;

  @ViewChild(MatPaginator) paginator: MatPaginator;
  @ViewChild(MatSort) sort: MatSort;

  constructor(private http: Http) {}

  ngOnInit() {
    this.exampleDatabase = new ExampleHttpDao(this.http);
    this.dataSource = new ExampleDataSource(
      this.exampleDatabase, this.paginator, this.sort);
  }
}

export interface GithubApi {
  items: GithubIssue[];
  total_count: number;
}

export interface GithubIssue {
  created_at: string;
  number: string;
  state: string;
  title: string;
}

/** An example database that the data source uses to retrieve data for the table. */
export class ExampleHttpDao {
  constructor(private http: Http) {}

  getRepoIssues(sort: string, order: string, page: number): Observable<GithubApi> {
    const href = 'https://api.github.com/search/issues';
    const requestUrl =
      `${href}?q=repo:angular/material2&sort=${sort}&order=${order}&page=${page + 1}`;

    return this.http.get(requestUrl)
      .map(response => response.json() as GithubApi);
  }
}

/**
 * Data source to provide what data should be rendered in the table. Note that the data source
 * can retrieve its data in any way. In this case, the data source is provided a reference
 * to a common data base, ExampleHttpDao. It is not the data source's responsibility to manage
 * the underlying data. Instead, it only needs to take the data and send the table exactly what
 * should be rendered.
 */
export class ExampleDataSource extends DataSource<GithubIssue> {
  // The number of issues returned by github matching the query.
  resultsLength = 0;
  isLoadingResults = false;
  isRateLimitReached = false;

  constructor(private exampleDatabase: ExampleHttpDao,
              private paginator: MatPaginator,
              private sort: MatSort) {
    super();
  }

  /** Connect function called by the table to retrieve one stream containing the data to render. */
  connect(): Observable<GithubIssue[]> {
    const displayDataChanges = [
      this.sort.sortChange,
      this.paginator.page
    ];

    // If the user changes the sort order, reset back to the first page.
    this.sort.sortChange.subscribe(() => this.paginator.pageIndex = 0);

    return Observable.merge(...displayDataChanges)
      .startWith(null)
      .switchMap(() => {
        this.isLoadingResults = true;
        return this.exampleDatabase.getRepoIssues(
          this.sort.active, this.sort.direction, this.paginator.pageIndex);
      })
      .map(data => {
        // Flip flag to show that loading has finished.
        this.isLoadingResults = false;
        this.isRateLimitReached = false;
        this.resultsLength = data.total_count;

        return data.items;
      })
      .catch(() => {
        this.isLoadingResults = false;
        // Catch if the GitHub API has reached its rate limit. Return empty data.
        this.isRateLimitReached = true;
        return Observable.of([]);
      });
  }

  disconnect() {}
}
```
users.component.html

```
<div class="example-container mat-elevation-z8">
  <div class="example-loading-shade"
       *ngIf="dataSource.isLoadingResults || dataSource.isRateLimitReached">
    <mat-spinner *ngIf="dataSource.isLoadingResults"></mat-spinner>
    <div class="example-rate-limit-reached" *ngIf="dataSource.isRateLimitReached">
      GitHub's API rate limit has been reached. It will be reset in one minute.
    </div>
  </div>

  <mat-table #table [dataSource]="dataSource" class="example-table"
             matSort matSortActive="created_at" matSortDisableClear matSortDirection="asc">

    <!--- Note that these columns can be defined in any order.
          The actual rendered columns are set as a property on the row definition" -->

    <!-- Number Column -->
    <ng-container matColumnDef="number">
      <mat-header-cell *matHeaderCellDef>#</mat-header-cell>
      <mat-cell *matCellDef="let row">{{ row.number }}</mat-cell>
    </ng-container>

    <!-- Title Column -->
    <ng-container matColumnDef="title">
      <mat-header-cell *matHeaderCellDef>Title</mat-header-cell>
      <mat-cell *matCellDef="let row">{{ row.title }}</mat-cell>
    </ng-container>

    <!-- State Column -->
    <ng-container matColumnDef="state">
      <mat-header-cell *matHeaderCellDef>State</mat-header-cell>
      <mat-cell *matCellDef="let row">{{ row.state }}</mat-cell>
    </ng-container>

    <!-- Created Column -->
    <ng-container matColumnDef="created_at">
      <mat-header-cell *matHeaderCellDef
                       mat-sort-header
                       disableClear="true">
        Created
      </mat-header-cell>
      <mat-cell *matCellDef="let row">{{ row.created_at | date }}</mat-cell>
    </ng-container>

    <mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
    <mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>
  </mat-table>

  <mat-paginator [length]="dataSource.resultsLength"
                 [pageSize]="30">
  </mat-paginator>
</div>

```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
npm -v 
5.4.2
node -v 
v6.11.3
Ubuntu 
17.04

**Comment by atluriajith** [comment] 2017-10-04 08:36
Refer [#7253](https://github.com/angular/material2/issues/7253)

**Comment by josephperrott** [comment] 2017-10-05 20:48
Closing as duplicate of #7253

Be sure that you are not using the `CompatibilityModule` for compatibility mode.

**Closed by josephperrott** 2017-10-05 20:48 UTC
