### ISSUE TITLE
animation trigger "transformMenu" has failed to build

### ISSUE THREAD

**Issue by kostia-lev** [angular/material2#11044] opened 2018-04-27 10:17 UTC
#### Bug, feature request, or proposal:
using angular 5.2, error occurs when using universal ssr renderer

#### What is the expected behavior?
ERROR Error: The animation trigger "transitionMessages" has failed to build due to the following errors:
 - The provided animation property "transform" is not a supported CSS property for animations
 - The provided animation property "transform" is not a supported CSS property for animations

#### What are the steps to reproduce?
use mat-form-field, to create form

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/material": "^5.2.4

**Comment by kostia-lev** [comment] 2018-04-27 10:19
I already try to mock many things using domino package

const template = readFileSync(join(DIST_FOLDER, 'browser', 'index.html')).toString();
const win = domino.createWindow(template);
global['window'] = win;
global['document'] = win.document;
global['DOMTokenList'] = win.DOMTokenList;
global['Node'] = win.Node;
global['Text'] = win.Text;
global['HTMLElement'] = win.HTMLElement;
global['navigator'] = win.navigator;
global['localStorage'] = { getItem: () => {}, setItem: () => {} };
global['MutationObserver'] = getMockMutationObserver();

**Comment by minirobotdan** [comment] 2018-05-02 12:42
I'm having a similar issue, mine stops at "transform" but I expect it's just determine by whatever mat element it hits first. I've included noop animations in my serverside app module and regular animations in my browser one, no luck.

**Comment by mmalerba** [comment] 2018-05-02 15:50
I am able to prerender our test app which includes a form field without issues

**Comment by jcdickman** [comment] 2018-05-18 14:47
Having same issue material 5.2.4 + Universal 5.0.0

`Error: The animation trigger "state" has failed to build due to the following errors:
 - The provided animation property "transform" is not a supported CSS property for animations`

**Comment by Supamiu** [comment] 2018-06-07 13:58
I can reproduce too in my Angular 6 project (see commit just above this comment).

I'm using MatMenu in various components so I can't confirm it's coming from it, but what is sure is that I get the same error message:

> ERROR Error: The animation trigger "transitionMessages" has failed to build due to the following errors:
>  - The provided animation property "transform" is not a supported CSS property for animations
>  - The provided animation property "transform" is not a supported CSS property for animations
>     at InjectableAnimationEngine.AnimationEngine.registerTrigger (webpack:///./node_modules/@angular/animations/fesm5/browser.js?:3779:23)
>     at eval (webpack:///./node_modules/@angular/platform-browser/fesm5/animations.js?:163:33)
>     at Array.forEach (<anonymous>)
>     at AnimationRendererFactory.createRenderer (webpack:///./node_modules/@angular/platform-browser/fesm5/animations.js?:162:27)
>     at Object.createComponentView (webpack:///./node_modules/@angular/core/fesm5/core.js?:11451:56)
>     at createViewNodes (webpack:///./node_modules/@angular/core/fesm5/core.js?:11492:46)
>     at callViewAction (webpack:///./node_modules/@angular/core/fesm5/core.js?:11843:13)
>     at execComponentViewsAction (webpack:///./node_modules/@angular/core/fesm5/core.js?:11762:13)
>     at createViewNodes (webpack:///./node_modules/@angular/core/fesm5/core.js?:11555:5)
>     at createRootView (webpack:///./node_modules/@angular/core/fesm5/core.js?:11441:5)
> 

Dependencies: 

```
    "@angular/animations": "6.0.1",
    "@angular/cdk": "6.0.1",
    "@angular/common": "6.0.1",
    "@angular/compiler": "6.0.1",
    "@angular/core": "6.0.1",
    "@angular/forms": "6.0.1",
    "@angular/http": "6.0.1",
    "@angular/material": "6.0.1",
    "@angular/platform-browser": "6.0.1",
    "@angular/platform-browser-dynamic": "6.0.1",
    "@angular/router": "6.0.1",
```

**Comment by rickysandoval** [comment] 2018-06-12 17:54
Workaround if you're using domino to mock things:

```
Object.defineProperty(win.document.body.style, 'transform', {
  value: () => {
    return {
      enumerable: true,
      configurable: true
    };
  },
});
```

with `win` being the mocked window

**Comment by Supamiu** [comment] 2018-06-13 15:10
@rickysandoval Seems like your workaround changes things but didn't fix the issue : 

> ERROR Error: The animation trigger "transform" has failed to build due to the following errors:
>  - The provided animation property "box-shadow" is not a supported CSS property for animations
>     at InjectableAnimationEngine.AnimationEngine.registerTrigger (webpack:///./node_modules/@angular/animations/fesm5/browser.js?:3779:23)
>     at eval (webpack:///./node_modules/@angular/platform-browser/fesm5/animations.js?:163:33)
>     at Array.forEach (<anonymous>)
>     at AnimationRendererFactory.createRenderer (webpack:///./node_modules/@angular/platform-browser/fesm5/animations.js?:162:27)
>     at Object.createComponentView (webpack:///./node_modules/@angular/core/fesm5/core.js?:11451:56)
>     at createViewNodes (webpack:///./node_modules/@angular/core/fesm5/core.js?:11492:46)
>     at callViewAction (webpack:///./node_modules/@angular/core/fesm5/core.js?:11843:13)
>     at execComponentViewsAction (webpack:///./node_modules/@angular/core/fesm5/core.js?:11762:13)
>     at createViewNodes (webpack:///./node_modules/@angular/core/fesm5/core.js?:11555:5)
>     at createRootView (webpack:///./node_modules/@angular/core/fesm5/core.js?:11441:5)

**Comment by rickysandoval** [comment] 2018-06-13 15:12
Do the same thing for box-shadow

```
Object.defineProperty(win.document.body.style, 'box-shadow', {
  value: () => {
    return {
      enumerable: true,
      configurable: true
    };
  },
});
```

**Comment by Supamiu** [comment] 2018-06-13 15:42
Alright, works for me with domino and property definitions on box-shadow and transform.

**Comment by dojchek** [comment] 2018-07-31 23:50
Any update on this one?
I'm getting the same error on IE9 - Works fine on IE10+ and all the other browsers.

**Comment by 3fuyu** [comment] 2018-08-02 02:53
@dojchek Microsoft has gave up IE, and you?

**Comment by mmalerba** [comment] 2018-08-02 04:49
@dojchek Angular Material only supports IE11+, see: https://github.com/angular/material2#browser-and-screen-reader-support

**Comment by dojchek** [comment] 2018-08-02 13:59
Thanks guys.
I would gladly gave up on it, but there are browser compatibility requirements on current proj.
I made it work with IE10+ but IE9 is cheeky one.. tried all I could, but couldn't find any decent workaround.
Guess I'll have to settle with IE10+

**Comment by josephperrott** [comment] 2018-09-10 22:16
Closing as we still have not be able to reproduce this issue on a supported browser.

**Closed by josephperrott** 2018-09-10 22:16 UTC
Labels: cannot reproduce
