### ISSUE TITLE
Can't drag slider bullet unless I manually import Hammer.js

### ISSUE THREAD

**Issue by odahcam** [angular/material2#10665] opened 2018-04-02 14:08 UTC
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
I expect the slider to be draggable.

#### What is the current behavior?
I can not drag the slider bullet, it just moves when I click in the bar.

#### What are the steps to reproduce?
Create a blank app, add material, add slider component and try to use it.

#### What is the use-case or motivation for changing an existing behavior?
I have to manually import `import 'hammerjs/hammer';` to be able to drag the bullet **or** add it as a polyfill, but I think that is not cool to have it globally imported.

**Slider-toggle (switch) works even when no Hammer.js is imported.**

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material ^5.

#### Is there anything else we should know?
The slider works fine when importing Hammer.js manually. I think it should be imported [here](https://github.com/angular/material2/tree/master/src/lib/slider/slider.ts).

**Comment by Chan4077** [comment] 2018-04-02 16:03
I'm pretty sure that's intentional.

In the docs ([Slider > Overview](https://material.angular.io/components/slider/overview)):

> Note: the sliding behavior for this component requires that HammerJS is loaded on the page.

It's also in the guide for [Getting started](https://material.angular.io/guide/getting-started#step-5-gesture-support):

> Some components (`mat-slide-toggle`, `mat-slider`, `matTooltip`) rely on [HammerJS](http://hammerjs.github.io/) for gestures. In order to get the full feature-set of these components, HammerJS must be loaded into the application.

It even says that HammerJS import should be ideally included in `src/main.ts`:
> After installing, import it on your app's entry point (e.g. src/main.ts).
> ```typescript
> import 'hammerjs';
> ```

**Comment by josephperrott** [comment] 2018-04-02 16:34
Closing as this is working as intended.  For touch/drag to work `hammer.js` will need to be loaded.

**Closed by josephperrott** 2018-04-02 16:34 UTC

**Comment by odahcam** [comment] 2018-04-02 18:08
So why the switch doesn't need that?

**Comment by Chan4077** [comment] 2018-04-02 18:09
@odahcam Doesn't need what?

**Comment by odahcam** [comment] 2018-04-02 18:37
Yes, when I used the `MatSlideToggleModule` it's touch functionalities worked fine without importing Hammer, also it made the Slider drag work, when I removed the toggle, the Slider stopped working again. So I think SliderToggle imports Hammer by itself, while the common Slider doesn't. My question is, if I'm right of course, why they have different behaviors?

**Comment by matthewdfleming** [comment] 2019-03-06 19:55
Just putting this here in case someone else runs into this.

I was also having issue with the dragging working. For my app (Angular 7) I had to do these things to get the slider working:

1. add dependency: (package.json dependency - `"hammerjs": "^2.0.8"`)
2. add it to the app: (polyfills.ts - `import 'hammerjs'`)
3. in app.module.ts: `{provide: HAMMER_GESTURE_CONFIG, useClass: GestureConfig}`

If I didn't do the last step the dragging of the thumb/disc wouldn't work.

**Comment by felixchiang86** [comment] 2019-04-08 10:09
> 3. in app.module.ts: `{provide: HAMMER_GESTURE_CONFIG, useClass: GestureConfig}`

The above made my slider draggable, thanks @matthewdfleming !!!
