### ISSUE TITLE
Is possible to change the animation styles for Angular MatDialog in MaterialDesign ?

### ISSUE THREAD

**Issue by surya5353** [angular/material2#12527] opened 2018-08-04 13:51 UTC
Dear All,
I have tried to so many ways to change the **MatDialog** animation style but not possible.
ex:Existing **MatDialog** comes with bottom to top but i want to show **Right to Left** ,or **Fade**, or **Top to Bottom** instead of Bottom to Top. I tried css **@keyframes, Transitions , javascript** but not possible in any way.

**Comment by Chan4077** [comment] 2018-08-04 15:08
Duplicate of #8857

**Comment by crisbeto** [comment] 2018-08-04 15:56
Closing as a duplicate of #8857.

**Closed by crisbeto** 2018-08-04 15:56 UTC
