### ISSUE TITLE
[Docs] - API docs aren't being displayed correctly

### ISSUE THREAD

**Issue by rafaelss95** [angular/material2#7788] opened 2017-10-13 23:56 UTC
#### Bug, feature request, or proposal:
Bug(s) and a proposal.

#### What is the current behavior?
Currently, a lot of places in API docs shows the **default** value (or even the complete function - paginator case) instead of the **type** of the property. 

Some examples (there are a lot):

https://material.angular.io/components/datepicker/api

- Note that all ***Label** properties have the default value instead of the type (in this case string).

https://material.angular.io/components/paginator/api

- See `getRangeLabel`.

#### What is the expected behavior?
I guess these "bugs" happens when you don't specify the type of the property. For example:

```
@Input()
overlapTrigger = this._defaultOptions.overlapTrigger;
```

The API generator seems to always expect the type of the property (even when it's completely redundant):

```
@Input()
overlapTrigger: MatMenuDefaultOptions = this._defaultOptions.overlapTrigger;
```

In this case `this._defaultOptions.overlapTrigger` already returns `MatMenuDefaultOptions`, so it's correct to omit this specification. 

**Proposal:**

I'm wonder if you can get the type inference from the `default` value, so it won't be really necessary to write this redundant assignment. 

This will be really great in many places. Currently you've to write something really redundant (just to make it appear right in API docs):

```
@Output() optionSelected: EventEmitter<MatAutocompleteSelectedEvent> =
      new EventEmitter<MatAutocompleteSelectedEvent>();
```

Also, I'd like to propose to create a new column in API docs (something like Default value).

So we can have the following:

| Name | Type | Default value | Description |
| ------------- | ------------- | ------------- | ------------- |
| @Input() overlapTrigger | MatMenuDefaultOptions  | this._defaultOptions.overlapTrigger (**not sure about this**) | Whether the menu should overlap its trigger.

#### What is the use-case or motivation for changing an existing behavior?
A better documentation.

#### Is there anything else we should know?
The `menu` case was just an example, but I hope you get the idea.

An example of a clear docs is the `ng-bootstrap`:

https://ng-bootstrap.github.io/#/components/accordion/api

**Comment by rafaelss95** [comment] 2017-10-20 23:50
@jelbourn can you please take a look?

**Comment by jelbourn** [comment] 2017-10-20 23:52
This was caused by a recent update to some combination of dgeni / typescript. @amcdnl has a PR open to fix it

**Comment by amcdnl** [comment] 2017-11-05 16:17
PR is #7711

**Comment by rafaelss95** [comment] 2017-11-05 19:47
Hey @amcdnl can you post a pic to show a preview of the "new look"?

**Comment by josephperrott** [comment] 2018-03-07 20:55
Closing as #7711 is merged.

**Closed by josephperrott** 2018-03-07 20:55 UTC
Labels: P2: required, docs, has pr
