### ISSUE TITLE
Tooltip TypeError with web.animations.js

### ISSUE THREAD

**Issue by chrchm** [angular/material2#3846] opened 2017-03-30 14:41 UTC
`####` Bug:
Material Tooltip with web.animations.js, do not work properly if we trigger a tooltip more than two consecutive times in a short time is thrown this error (only Safari):
'TypeError: e [0] .push is not a function. (In 'and [0] .push (1)', 'and [0] .push' is undefined)  --- web-animations.min.js:16:6248

#### What is the expected behavior?
No error

#### What is the current behavior?
This error on mouse enter more times in small piece of time: 
![error_tooltip-md2](https://cloud.githubusercontent.com/assets/20452405/24509811/b152e790-1567-11e7-962f-42dc970951a8.png)

'TypeError: e [0] .push is not a function. (In 'and [0] .push (1)', 'and [0] .push' is undefined) '

#### What are the steps to reproduce?

Plunker template: http://plnkr.co/edit/GqVcNkh0GRxCYUmcj7fv?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I'm using 2 Material for a big project and I find difficulty with this bug.

#### Which versions of Angular, Material, OS, browsers are affected?
MAC OSX,material2-builds, and latest, web.animations 2.2.2. Safari on Sierra, not Chrome.

#### Is there anything else we should know?

**Comment by donroyco** [comment] 2017-03-30 18:08
This is a duplicate of #3694

**Comment by karlhaas** [comment] 2017-03-31 06:29
Maybe also a duplicate of https://github.com/angular/material2/issues/3384

**Comment by chrchm** [comment] 2017-03-31 17:53
vHi,I believe is a duplicate of this, can you excuse me, please?

Bye

**Comment by jelbourn** [comment] 2017-04-09 02:36
Seems to be working fine in the latest version. 

Be sure to check out [the changelog for the latest release](https://github.com/angular/material2/blob/master/CHANGELOG.md) in regards to changes w/ animations.

**Closed by jelbourn** 2017-04-09 02:36 UTC

**Comment by karlhaas** [comment] 2017-04-09 16:38
@jelbourn still the same error with material v. 2.0.0-beta.3 in Safari

**Comment by compitDanielos** [comment] 2017-05-16 12:53
Same error 2.0.0-beta.5 in Safari

**Comment by compitDanielos** [comment] 2017-05-16 12:58
updating "web-animations-js": "2.2.5" should fix
