### ISSUE TITLE
feat(expansion): custom expansion height on collapsed or expanded

### ISSUE THREAD

**Issue by RainingNight** [angular/material2#7198] opened 2017-09-20 10:13 UTC
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?

Custom expansion height on expansion collapsed or expanded.

#### What is the current behavior?

The collapsed height is fixed 48px, and expanded height is fixed 64px.

#### What is the use-case or motivation for changing an existing behavior?

Keep collapsed height stay the same when collapsed or expanded.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular Material 2.0.0-beta.10

**Comment by ghd8** [comment] 2017-09-20 10:49
Duplicate of #5461  and will be available in the next release #6643.

**Comment by josephperrott** [comment] 2017-09-20 16:18
Closed via #6643

**Closed by josephperrott** 2017-09-20 16:18 UTC
