### ISSUE TITLE
Ink bar does not initially appear on a tab group inside a parent tab group's tab body

### ISSUE THREAD

**Issue by awormasi** [angular/material2#12862] opened 2018-08-27 23:04 UTC
#### Bug, feature request, or proposal:
The ink bar for a tab group inside the tab body of a parent tab group does not appear if that tab body is not immediately shown.

#### What is the expected behavior?
The ink bar should always appear for the selected tab in the embedded tab group inside the tab body of a parent tab group.

#### What is the current behavior?
If you have an embedded tab group as the content of a parent tab group and the embedded tab group is not immediately shown because that tab is not selected, when the tab is selected and the embedded tab group is shown, the ink bar for the embedded tab group will be missing.

#### What are the steps to reproduce?
See https://stackblitz.com/edit/github-vktvqc. The ink bar for the embedded tab group for tab 'Air Nomads' is shown but when switching to 'Water Tribe', the ink bar for its embedded tab group does not appear.

#### What is the use-case or motivation for changing an existing behavior?
I have an app that uses a tab group inside the tab body of a parent tab group.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material/CDK 6.3.0
MacOS 10.13.6
TypeScript 2.7.2
Chrome 68.0.3440.106

#### Is there anything else we should know?
It looks like _setStyles() on the MatInkBar class is called for the embedded tab group when it is not yet rendered (since it's the content of a non-selected tab) and so the position function returns { start: '0px', size: '0px' }. When this tab is selected, _setStyles() is not called again so the ink bar is not shown at all on the embedded tab group.

**Comment by josephperrott** [comment] 2018-09-06 22:52
Closing as this is working as expected, the spec actually warns against nesting tabs.

This is caused by the fact that when `_setStyles` is called on the inner tab group the elements are not in the DOM and cannot be measured.  You can delay when this occurs by using the async loading of tab content for tabs.

**Closed by josephperrott** 2018-09-06 22:52 UTC
