### ISSUE TITLE
Enhancement: mat-icon set current page absolute path on filter urls for compatibility with safari

### ISSUE THREAD

**Issue by MikaAK** [angular/material2#9276] opened 2018-01-08 05:49 UTC
#### Feature request:
mat-icon is super useful for using svg's inline in the browser. However what's the solution when you need to filter. Since `<base href='/'>` is in use for history you must append svg filters with the current url. 
Example: 
```svg
<svg viewBox="0 0 96 96" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <mask id="b" fill="#fff">
      <use xlink:href="#a"/>
    </mask>
  </defs>
  <path d='SOMEAMOUNTOFPOINTS' mask='url(http://example.com/my-page#b)'
</svg>
```

This works because url is set to absolute path. Anything else and the svg works in chrome but not in safari! This used to be an issue in chrome a few years ago but it seems chrome got smarter, however safari has not 😢 

#### What are the steps to reproduce?
I tried to reproduce on plunker but since there's no baseUrl being set and it doesn't seem possible to set I cannot reproduce.

#### What is the use-case or motivation for changing an existing behavior?
Safari Compatibility

#### Other Info
As a workaround you can skip setting baseUrl in the index document and set it with

```typescript
import {APP_BASE_HREF} from '@angular/common'

providers: [{provide: APP_BASE_HREF, useValue: '/'}]
```

**Comment by jelbourn** [comment] 2018-01-09 23:20
Possible duplicate of #4263

**Comment by MikaAK** [comment] 2018-01-10 10:15
Not quite @jelbourn that issue seems to be around allowing urls passed to the register to be relative. This is more around either changing the actual url's of the svg's filters/masks when referencing defs (since it must change on a per page basis this would need to be done at render).

see https://github.com/jeffbcross/angular-svg-base

**Comment by MikaAK** [comment] 2018-01-17 11:58
New findings, the workaround I provided above doesn't seem to work on subroutes. For example when navigating to `http://localhost:3000/pain-module/quieting-the-pain-alarm` it tries to request packages from `http://localhost:3000/pain-module/`

**Comment by tenbits** [comment] 2018-06-27 15:47
Also `clip-path="url(#a)"` doesn't work in safari. Painful.

**Closed** 2018-10-05 16:07 UTC
Labels: P4, discussion, feature, has pr

**Comment by FingalP** [comment] 2018-10-17 15:07
We tried upgrading to Material 7, and this broke icons on our header in Chrome. As they are in our header, they get rendered on the first page which is opened, and the url is set to that path. Once we navigate from there, they aren't re-rendered, so the url is now wrong, and they vanish.

**Comment by MikaAK** [comment] 2018-10-17 16:30
That is a probably issue with doing this and having icons persistant across pages. The icons would need a url update

**Comment by FingalP** [comment] 2018-10-18 13:37
It turns out, all of our icons are broken, not just the ones which are persistent across pages, as the _location is cached by the location factory.
However, a fix should also also consider supporting icons which are persistent across pages.
