### ISSUE TITLE
mat-table row does not update when matRowDef.when matches differently

### ISSUE THREAD

**Issue by robertorfischer** [angular/material2#14011] opened 2018-11-06 18:45 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When `trackBy` is set on `mat-table` and it has multiple `matRowDef` with `when` predicates set, and the `when` predicates evaluate differently, `mat-table` should change which `matRowDef` template is used to display a row.

#### What is the current behavior?
`mat-table` never changes which `matRowDef` is used for any row with the same `trackBy` value after it has already been displayed once.

Workaround is to make `trackBy` use a function that also changes when the `matRowDef.when` predicates change.

#### What are the steps to reproduce?

Basic setup to reproduce has this skeleton:
```
<mat-table [trackBy]="getRowId" [dataSource]="data">
  <!-- define some columns -->
  <tr mat-row *matRowDef="let row; columns: columns"></tr>
  <tr mat-row *matRowDef="let row; columns: otherColumns; when: useOtherColumns"></tr>
</mat-table>
```

In the previous example, when `getRowId` returns the same value for a row, but `useOtherColumns` returns a different value, I expected the `<tr>` to be replaced with the appropriate one, based on the result from `useOtherColumns`. I added a bunch of `console.log` statements to show how `when` is indeed evaluated, but it doesn't seem to matter.

For a full working project that reproduces:
https://stackblitz.com/edit/angular-fckmvg?file=app%2Ftable-basic-example.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material2 v7.0.2

**Comment by andrewseguin** [comment] 2018-12-11 18:58
Thanks for the reporting the issue. This is a duplicate of #9527 so we'll track the progress there

**Closed by andrewseguin** 2018-12-11 18:58 UTC
Labels: P3
