### ISSUE TITLE
md-sidenav displaces content when align="end"

### ISSUE THREAD

**Issue by benjamin-wilson** [angular/material2#4908] opened 2017-06-01 14:01 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Sidenav should open and close without displacing content

#### What is the current behavior?
If you set the alignment of the sidenav to align="end" and then aggressively open the sidenav, click inside the nav then click outside the nav to close it, it will sometimes displace its content. 

#### What are the steps to reproduce?
https://plnkr.co/edit/p5rn1klp18ujLHGL0g62?p=preview

Very quickly click 'Open sidenav' then click inside the nav that just opened, then click outside the nav to close it. You may have to do this several times/spam it. You will see the 'Open sidenav' button shift to the left when the problem occurs. 

#### What is the use-case or motivation for changing an existing behavior?
We have navs on the right side for our website and when this bug occurs, it offsets all of the website content to the left making it mostly unusable.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Seen in beta 6, Chrome, Firefox and IE 11. Seems to affect IE 11 the worst.

**Comment by mmalerba** [comment] 2017-07-17 20:55
I am not able to reproduce this, even turning the animation speed down to 10% using the chrome inspector.

**Comment by mmalerba** [comment] 2017-07-22 22:15
Closing since I am unable to reproduce

**Closed by mmalerba** 2017-07-22 22:15 UTC
Labels: cannot reproduce

**Comment by willshowell** [comment] 2017-07-23 01:29
@benjamin-wilson I remember being able to repro this when I first saw this issue (like 1/20 times with no apparent consistency). I wonder if it could be related to https://github.com/angular/material2/issues/5743 or https://github.com/angular/material2/issues/4932 which could be a bug in @angular/animations

**Comment by benjamin-wilson** [comment] 2017-08-03 00:02
Doesn't look like I can reproduce this anymore.
