### ISSUE TITLE
Slider: how to add multi handles to single slider ?

### ISSUE THREAD

**Issue by ayyazzafar** [angular/material2#11529] opened 2018-05-27 04:31 UTC
#### Bug, feature request, or proposal:

I need 2 handles to a single slider something like in following screenshot
![image](https://user-images.githubusercontent.com/5826477/40582438-683c5ff2-6190-11e8-9b2d-88cc8ea92b6c.png)

#### What is the expected behavior?
We should be able to select min and max values from a single slider

#### What is the current behavior?
Currently I cannot see any such option to add second handle.

#### What is the use-case or motivation for changing an existing behavior?
This feature can help us to select min and maximum values from a single slider.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6

**Comment by pfeigl** [comment] 2018-05-27 10:58
Duplicate of #4613 and #5861, seems like this is not planned to be implemented.

**Comment by josephperrott** [comment] 2018-05-31 20:47
Duplicate of #4613

**Closed by josephperrott** 2018-05-31 20:47 UTC
