### ISSUE TITLE
Autocomplete noSelectionClose event proposal

### ISSUE THREAD

**Issue by radoslavpetranov** [angular/material2#4796] opened 2017-05-25 11:06 UTC
#### Feature request / discussion
Expose an event that gets fired when the user closes an autocomplete without selecting an option

#### What is the expected behavior?
User clicks on Autocomplete and writes some text but doesn't select an option and then clicks somewhere to close the autocomplete. The written text should be replaced by `null`.

#### What is the current behavior?
What the user wrote remains in the autocomplete / form control.

#### What is the use-case or motivation for changing an existing behavior?
I have autocompletes for different enum-type structures that I've set up. I would like to make sure that if the user doesn't select an option I set the value to `null` instead of leaving invalid text in the form control value. I tried implementing this with a `blur` handler on the input but that gets fired even when the user selects an option from the list which is a show stopper.

**Comment by fxck** [comment] 2017-05-25 11:19
dupe of https://github.com/angular/material2/issues/3334

**Comment by mmalerba** [comment] 2017-05-30 23:42
Closing as dupe

**Closed by mmalerba** 2017-05-30 23:42 UTC
