### ISSUE TITLE
maxLength on input not working for `type="number"`

### ISSUE THREAD

**Issue by robindijkhof** [angular/material2#4940] opened 2017-06-02 19:41 UTC
#### What is the expected behavior?
maxLength should work for input type number.

#### What is the current behavior?
It doesn't work

#### What are the steps to reproduce?
https://plnkr.co/edit/Fn3W5yPofeNFtXZCynpW?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material beta-6
Angular 4.1.3
Chrome 58
FireFox 53.0.3

**Comment by donroyco** [comment] 2017-06-02 19:43
Dupe of #1934

**Closed** 2017-06-02 22:37 UTC
