### ISSUE TITLE
Documentation example for `md-nav-list` gives unexpected user feedback

### ISSUE THREAD

**Issue by thw0rted** [angular/material2#6617] opened 2017-08-24 08:29 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Clicks / touches that trigger a ripple effect should cause some action.

#### What is the current behavior?
Clicks / touches in the example nav-list item always create a ripple effect, but only trigger an action when on the item text.

#### What are the steps to reproduce?
Create a list with the example code in the nav-list section of [the current docs](https://material.angular.io/components/list/overview).  Click or touch in the padding around the link text.  Observe that the ripple effect triggers as though you did something, but no navigation occurs.

#### What is the use-case or motivation for changing an existing behavior?
Poor feedback is confusing to users.  It's more pronounced for very short link text, where the list item is mostly whitespace.  Users who click the whitespace and see a ripple will think the application is broken when nothing happens.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I don't think this is specific to any version, it's mostly a docs problem.

#### Is there anything else we should know?
At the very least, I'd like to see @kara's example from #1391 included in the docs -- how to make a multiline nav-list item where clicking anywhere in the item counts as a link click.  If users are going to continue to create list items with more than one link in the item, then the ripple should be scoped to each link, not the whole item, to make it clear that clicking different lines of text have different effects.  (If there's an allowance for this in the Material spec, though, I can't find it.)

**Comment by thw0rted** [comment] 2017-08-24 08:52
I threw together [a Plunker for this](https://embed.plnkr.co/GUtuEJ/) with an added border to highlight the problem.  Clicking anywhere between the blue (around the `<a>`) and the red (around the list item) results in a ripple with no action.

**Comment by willshowell** [comment] 2017-08-24 14:09
See https://github.com/angular/material2/issues/5132

**Comment by josephperrott** [comment] 2017-09-27 18:49
Closing as duplicate of #5132

**Closed by josephperrott** 2017-09-27 18:49 UTC
