### ISSUE TITLE
Mat-Bottom-Sheet renders incorrectly in IE

### ISSUE THREAD

**Issue by KristopherTadlock** [angular/material2#15207] opened 2019-02-16 00:06 UTC
In internet explorer, Mat-bottom-sheet-container will be visible for one frame, before moving to the bottom of the screen. This causes a visible "flash". This is caused by IE incorrectly painting elements before calculating their styles.

This can be fixed by adding "opacity: 0" to the mat-bottom-sheet css class, and then changing opacity to 1 in javascript one animation frame after invoking "open". 

This has no ill effects on standards compliant browsers, because they will correctly calculate the style of the sheet before painting to the screen, where it will always be opaque. For IE, the bottom sheet will be visible for one less frame, but will otherwise render the same as in other browsers.

**Comment by crisbeto** [comment] 2019-02-16 08:14
Thank you for the report, however I wasn't able to reproduce it. If you seeing this in a VM, it might be the animation skipping frames because the VM is underpowered.

![demo2](https://user-images.githubusercontent.com/4450522/52896669-4955e980-31cb-11e9-9677-8da13455e34a.gif)

**Comment by crisbeto** [comment] 2019-03-21 19:13
Closing since there hasn't been a response in over a month.

**Closed by crisbeto** 2019-03-21 19:13 UTC
Labels: ie11
