### ISSUE TITLE
Feature request: Infinite scroll (with fixed headers)

### ISSUE THREAD

**Issue by amaneer94** [angular/material2#10391] opened 2018-03-13 08:39 UTC
#### Bug, feature request, or proposal:
There should be way to have infinite scroll in which we can have fixed headers until we scroll to bottom of the content, same as implemented in Google Inbox.

**Comment by jelbourn** [comment] 2018-03-14 16:24
Duplicate of #823

**Closed by jelbourn** 2018-03-14 16:24 UTC
