### ISSUE TITLE
[mdInput] placeholder over registered password

### ISSUE THREAD

**Issue by TomDemulierChevret** [angular/material2#6909] opened 2017-09-07 13:44 UTC
#### Bug, feature request, or proposal:
When using an `<input mdInput type="password">` with a placeholder on a login form, ifthe browser register the password and I come back on the login screen, the placeholder doesn't animate and stay over the password.

Screenshot of the problem : 
![input-password-issue](https://user-images.githubusercontent.com/22638671/30165915-0ccc23f4-93e2-11e7-901b-1f5d86cf526a.PNG)

When I click on the page (anywhere) the animation does play and the placeholder goes to the right place.

This issue has been reported to me since the last update (beta-10) and didn't seem to have been seen before (but I'm not sure).
May be it's linked to the OnPush detection strategy set on every component ?

#### What is the expected behavior?
The placeholder should animate and go to his place when the input is pre-filled with the registered password.

#### What is the use-case or motivation for changing an existing behavior?
This is not a major issue but it's still quite disturbing for the user since it will often be the first page they see.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular: 4.3.6
@angular/material: 2.0.0-beta.10
Chrome: 60.0.3112.113 (64 bits)

#### Is there anything else we should know?
The issue doesn't exist on `<input mdInput type="text">`.

**Comment by julianobrasil** [comment] 2017-09-07 16:00
Dupe: #6837

**Comment by josephperrott** [comment] 2017-09-07 16:41
Closing as duplicate of #6837

**Closed by josephperrott** 2017-09-07 16:41 UTC
