### ISSUE TITLE
Add  mat-error within a mat-checkbox

### ISSUE THREAD

**Issue by dgouissem** [angular/material2#10995] opened 2018-04-25 08:38 UTC
Hey,

I'm wondering if it is possible to add  validation error message  (mat-error)  for a checkbox.

kind regards

**Comment by donroyco** [comment] 2018-04-25 10:46
Duplicate of #8662. 
As @jelbourn stated:
>The Material Design spec does not prescribe an error display for toggle controls, so we leave that to the user to implement at the application level.

See [the comment there](https://github.com/angular/material2/issues/8662#issuecomment-350191631) for a working solution.

**Comment by jelbourn** [comment] 2018-04-25 17:25
What @donroyco said

**Closed by jelbourn** 2018-04-25 17:25 UTC
