### ISSUE TITLE
[Bug] mat-table with matsort in mat-tab rendering arrow issue

### ISSUE THREAD

**Issue by pjmagee** [angular/material2#11338] opened 2018-05-15 12:41 UTC
#### Bug, feature request, or proposal:

The sorting arrows seem to glitch but fix themselves once the mouse is hovered over and clicking on them.

#### What is the expected behavior?

For the icons to appear as the arrows correctly

#### What is the current behavior?

The sort icons appear glitched and blurry (T shaped)

#### What are the steps to reproduce?

https://stackblitz.com/edit/data-table-sort-render-bug?embed=1&file=app/app.component.ts

#### What is the use-case or motivation for changing an existing behavior?

It causes the product/framework of material design to look bad

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
 
Framework: Angular 6.0.1 and Material 6.0.1
Chrome version: 66.0.3359
OS: Windows 10 x64

#### Is there anything else we should know?

Once you use the sorting arrows the issue appears to go away. Seems to only happen on first render.

Workaround is to apply some styling which transforms to fix the animation bug. Workaround from this issue comment https://github.com/angular/material2/issues/7291#issuecomment-375697611

```
::ng-deep .mat-sort-header-arrow.ng-trigger.ng-trigger-arrowPosition {
    opacity: 0;
}

::ng-deep .mat-sort-header-pointer-left.ng-trigger.ng-trigger-leftPointer {
    transform: rotate(-45deg);
}
::ng-deep .mat-sort-header-pointer-right.ng-trigger.ng-trigger-rightPointer {
    transform: rotate(45deg);
}
```

**Comment by gabaril** [comment] 2018-05-15 13:35
It looks like lazy-loading the tab content by putting \<ng-template matTabContent\>\</ng-template> around it fix this issue.

**Comment by tinayuangao** [comment] 2018-05-15 23:32
Closing it because it's a duplicate of issue #7291

**Closed by tinayuangao** 2018-05-15 23:32 UTC
