### ISSUE TITLE
Need a way to configure animations on material components

### ISSUE THREAD

**Issue by BlindDespair** [angular/material2#14293] opened 2018-11-27 16:00 UTC
#### Bug, feature request, or proposal:
Would it be possible to make animations used for angular material elements configurable?

#### What is the use-case or motivation for changing an existing behavior?
We were previously on angular 6 using material design and it looked quite good. After migrating to angular 7 animations of most elements change and it looks a lot worse to us. We would like not to be limited in upgrading to newer versions just because some UI specific things changed. It would be great to keep animations from angular material 6 while in angular material 7. E.g. have injectable animation configuration or have some kind of themes for it.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.1.0
Typescript 3.1.0

**Comment by josephperrott** [comment] 2018-11-27 16:08
This is something we would like to do but unfortunately have not had the resources to make happen as of yet.  I am going to close this out a duplicate of that effort, though we have separate tracking issues for customizing the animations for components.  You can see examples in issues like 10544 and  8857

**Closed by josephperrott** 2018-11-27 16:08 UTC
