### ISSUE TITLE
md-sidenav-layout child element with fixed position not being fixed

### ISSUE THREAD

**Issue by baruchvlz** [angular/material2#2416] opened 2016-12-27 07:08 UTC
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

For fixed position element to be fixed

#### What is the current behavior?

Fixed position element does not get fixed and scrolls up

#### What are the steps to reproduce?

http://plnkr.co/edit/N9qjtrQTHf13uCWdUPNb?p=preview
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?

In my case I'm trying to create a sticky on scroll sub-nav, but it's not working properly.

#### Which versions of Angular, Material, OS, browsers are affected?

```
angular-cli: 1.0.0-beta.24
node: 7.2.1
os: darwin x64
@angular/common: 2.3.1
@angular/compiler: 2.3.1
@angular/core: 2.3.1
@angular/forms: 2.3.1
@angular/http: 2.3.1
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.3.1
@angular/platform-browser-dynamic: 2.3.1
@angular/router: 3.2.1
@angular/compiler-cli: 2.3.1
@angular/material: 2.0.0-beta.1
```

#### Is there anything else we should know?

Possibly related to #1793

**Edit**
I was trying to tackle this myself and realized it the `transform: translate3d(...)` that's cause the issue, more here: http://stackoverflow.com/questions/15194313/webkit-css-transform3d-position-fixed-issue

Also my inial search through the issues didn't show #998

**Comment by Splaktar** [comment] 2017-04-22 01:36
This is a duplicate of https://github.com/angular/material2/issues/998

**Comment by jelbourn** [comment] 2017-06-06 22:14
See #998

**Closed by jelbourn** 2017-06-06 22:14 UTC
