### ISSUE TITLE
"GlobalPositionStrategy" is not assignable to type 'PositionStrategy'.

### ISSUE THREAD

**Issue by HeavenlyHost** [angular/material2#585] opened 2016-05-31 09:17 UTC
#### Bug, feature request, or proposal:

Material 2 Alpha 5 Overlay issue when using npm run tsc

#### What is the expected behavior?

Not fail on tsc build

#### What is the current behavior?

I am not using webpack, I am using systemjs and am seeing the following when attempting to build the ts with tsc. It is within material2 core overlay but I don't understand why, used to work on alpha 4.

error TS2322: Type 'GlobalPositionStrategy' is not assignable to type 'PositionStrategy'.
Property 'apply' is missing in type 'GlobalPositionStrategy'.

#### What are the steps to reproduce?

Simply attempt to create a new overlay using the following;

`              
let config = new OverlayState();
config.positionStrategy = this.overlay.position()
    .global()
    .centerHorizontally()
    .top('20px')
this.overlay.create(config).then(ref => {
    ref.attach(this.templatePortals.first);
});
` 

#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2 RC1
Angular 2 Material Alpha 5
SystemJS
Chrome 
Windows 7

#### Is there anything else we should know?

Not using webpack !!!

**Comment by jelbourn** [comment] 2016-05-31 16:16
Dupe of #535 
(same underlying issue)

**Closed by jelbourn** 2016-05-31 16:16 UTC
