### ISSUE TITLE
How to set width of autocomplete popover

### ISSUE THREAD

**Issue by doorman02** [angular/material2#3643] opened 2017-03-16 18:54 UTC
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
The width of the autocomplete popover should be customizable 

#### What is the current behavior?
The width is very small

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
Content of the autocomplete can vary in size

#### Which versions of Angular, Material, OS, browsers are affected?
Latest angular material, chrome

**Comment by willshowell** [comment] 2017-03-16 19:10
Looks like a dupe of #3198 and was fixed by #3297.

**Comment by doorman02** [comment] 2017-03-16 19:13
Hi @willshowell will this fix be included in the next beta release? Do you know when it is planned?

**Comment by willshowell** [comment] 2017-03-16 19:20
It should be a part of the next beta release, but I have no clue when it's planned. I'd guess early April probably?

If you want to go ahead and use all the latest changes, you can do this:  (from the README)
```
npm install --save https://github.com/angular/material2-builds.git
```

**Comment by jelbourn** [comment] 2017-03-16 23:08
Closing as duplicate of #3198

**Closed by jelbourn** 2017-03-16 23:08 UTC

**Comment by thw0rted** [comment] 2017-09-10 14:50
This was not exactly fixed in #3297.  That disabled the (erroneous) max-width constraint, but there is still no way to control the width of the autocomplete independent from the "parent" input.  The original request is that it should be "customizeable".

**Comment by willshowell** [comment] 2017-09-10 14:54
@thw0rted see https://github.com/angular/material2/pull/6618 for adding a panel class

**Comment by thw0rted** [comment] 2017-09-12 08:21
That's not actually in the release version yet, though, right?  I don't know how the release cycle works; when I can expect an `npm install` to include this?

**Comment by willshowell** [comment] 2017-09-12 12:22
@thw0rted no it isn't available yet - figured you may want to subscribe to it for updates. Once it's reviewed and merged, it will be available via the master-builds. Releases have typically happened ~monthly, but I think the goal is to increase the frequency.
