### ISSUE TITLE
mat-select width resize in IE 11

### ISSUE THREAD

**Issue by derSidge** [angular/material2#12404] opened 2018-07-27 12:29 UTC
#### Bug, feature request, or proposal:
mat-select resizes in IE 11, Chrome is working fine.
![ie-bugmatselect](https://user-images.githubusercontent.com/16681701/43320559-24239634-91a9-11e8-812c-74fa49ae5215.gif)

#### What is the expected behavior?
size should match the whole form field element, as in Chome

#### What is the current behavior?
width decreases (less than content)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-d27t8j-hx1rbv

#### What is the use-case or motivation for changing an existing behavior?
IE 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 6.4.1

#### Is there anything else we should know?
IE 11

**Comment by crisbeto** [comment] 2018-07-27 14:24
Closing as a duplicate of https://github.com/angular/material2/issues/11609.

**Closed by crisbeto** 2018-07-27 14:24 UTC
