### ISSUE TITLE
(click) event generates twice on md-slide-toggle and md-chekbox

### ISSUE THREAD

**Issue by geelus** [angular/material2#671] opened 2016-06-12 10:36 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
(click) to generate a single event

#### What is the current behavior?
it generates double event

#### What are the steps to reproduce?
on the md-checkbox and md-slide-toggle create a (click) event binding and you will see it runs the function twice.
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/FxHKvcNJe2Zq5Mq5Imni?p=info

#### Is there anything else we should know?
This issue might exist on other components but I haven't tested them.

**Comment by DevVersion** [comment] 2016-06-12 12:21
The issue with the Checkbox is already in progress. 
- https://github.com/angular/material2/pull/613 - https://github.com/angular/material2/pull/664

**Comment by rushi216** [comment] 2016-06-13 04:56
Even change event fires twice in md-slide-toggle

http://plnkr.co/edit/JPZHqfnMbOvsKWGRL2dM?p=preview

**Comment by DevVersion** [comment] 2016-06-13 05:23
@rushi216 This is already fixed in `master`.

**Comment by jelbourn** [comment] 2016-06-13 15:25
Dupe of #651

**Closed by jelbourn** 2016-06-13 15:25 UTC
