### ISSUE TITLE
md-menu open on the bad side

### ISSUE THREAD

**Issue by Socolin** [angular/material2#2658] opened 2017-01-14 20:49 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Menu should open on the defined side

#### What is the current behavior?
See plunker 

#### What are the steps to reproduce?

Click on button
Scroll down
Click again on button
http://plnkr.co/edit/jsQ5z1nu51iEqB0pk9kW?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Material beta 2.0
Angular 2.3.1

**Comment by crisbeto** [comment] 2017-01-15 09:50
In this case the menu doesn't open on the proper side, because it would go outside of the viewport and the user wouldn't be able to see the content. This is the intended behaviour.

**Comment by Socolin** [comment] 2017-01-15 18:19
If it appear on the proper side in this case it would be visible, but it open on the bad side and the menu is not readable.

When it open with no scroll it open on good side and its visible
When it open with scroll it open on the other side and is hidden

**Comment by crisbeto** [comment] 2017-01-15 18:24
I'm not sure what you mean. It opens up properly for me:

![jbiujrp](https://cloud.githubusercontent.com/assets/4450522/21965057/38dc3774-db58-11e6-898c-406ca0f8cc72.png)

**Comment by Socolin** [comment] 2017-01-15 19:25
The bug is when open after scroll when the md-card is moved down with [style.top] to stay on screen

![image](https://cloud.githubusercontent.com/assets/539620/21965459/414ca58a-db2e-11e6-889a-c9129efeb8cb.png)

![image](https://cloud.githubusercontent.com/assets/539620/21965461/461d394e-db2e-11e6-97e8-eb9fdb42ee7f.png)

**Comment by crisbeto** [comment] 2017-01-15 19:48
Alright, I see it now. Sorry for closing it initially.

**Closed** 2017-01-18 05:23 UTC
Labels: has pr
