### ISSUE TITLE
ChangeDetectionStrategy.OnPush causes tooltips to break after upgrade to beta 3

### ISSUE THREAD

**Issue by alexjlockwood** [angular/material2#4014] opened 2017-04-10 15:21 UTC
#### Bug, feature request, or proposal:

Tooltips started looking glitchy after I upgraded to beta 3 (see the gif and plunkr below).

It seems like the glitch has to do with setting `changeDetection: ChangeDetectionStrategy.OnPush` on the component, because when I remove that line the tooltips look fine.

#### What is the expected behavior?

The tooltip shouldn't flicker.

#### What is the current behavior?

The tooltip flickers:

![tooltipbug](https://cloud.githubusercontent.com/assets/1380747/24868886/8d631014-1ddf-11e7-98d3-c03b919c0c62.gif)

#### What are the steps to reproduce?

Here is a Plunkr that reproduces the issue: https://plnkr.co/edit/uqE0gm?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?

I am using Chrome, the latest version of Material (beta 3), and the latest version of Angular (4.0.1).

**Comment by willshowell** [comment] 2017-04-10 16:11
Looks like dupe of #3497, with PR on the way #3671

**Comment by jelbourn** [comment] 2017-04-11 23:26
Yep, should be fixed by #3671 in the next release.

**Closed by jelbourn** 2017-04-11 23:26 UTC
