### ISSUE TITLE
md-datepicker setFormat (other than english) not well formatted (month and day)

### ISSUE THREAD

**Issue by emreavsar** [angular/material2#4889] opened 2017-05-31 07:27 UTC
#### What is the expected behavior?
Using a `md-datepicker` in another language than english should work same as it works in english. When entering a date via keyboard and selecting date over the datepicker, the format should remain the same.

#### What is the current behavior?
Selected date from datepicker seems to format the date correctly, however when you change the day and re-visit the datepicker, the month jumps to the day and the day jumps to the month.

#### What are the steps to reproduce?

1. Open plunkr: https://plnkr.co/edit/lmeLuWfm2bwTcTrCtVgg?p=preview
2. Select date: 1st of April 2017
3. Update the day via text-input from 1st to 2nd
4. Re-open the datepicker

_Expected behaviour_: Selected date should be 2nd April 2017
_Current behaviour_: Selected date is 4th February 2017

#### What is the use-case or motivation for changing an existing behavior?
not applicable

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.x
material2 master
mac os
angular-cli

#### Is there anything else we should know?
nope.

**Comment by fxck** [comment] 2017-05-31 08:42
dupe of https://github.com/angular/material2/issues/4358

**Comment by jelbourn** [comment] 2017-06-07 20:50
See #4358 and the [documentation on internationalization](https://material.angular.io/components/component/datepicker).

**Closed by jelbourn** 2017-06-07 20:50 UTC
