### ISSUE TITLE
radio and checkbox are not rendered properly (native elements are visible)

### ISSUE THREAD

**Issue by maciejsobala** [angular/material2#2628] opened 2017-01-13 12:02 UTC
#### expected behavior
Radio and checkbox native elements should be hidden

#### current behavior
native elements are visible

![screen shot 2017-01-13 at 12 56 43 pm](https://cloud.githubusercontent.com/assets/15926528/21929378/84465f1a-d990-11e6-8298-a3d3b4be3c4e.png)
![screen shot 2017-01-13 at 12 56 53 pm](https://cloud.githubusercontent.com/assets/15926528/21929379/847d2fcc-d990-11e6-8b98-3112fdb3bbb3.png)

#### Which versions of Angular, Material, OS, browsers are affected?
OSX - Safari, Chrome (I did not check other browsers)
angular - 2.4.3
material - 2.0.0-beta.1

**Comment by dahaupt** [comment] 2017-01-13 14:30
@maciejsobala Can you provide a plunker, so we can reproduce your issue and investigate further?
Here is the template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

This should be fixed with including a theme, looks like you didn't have one.
Theming Guide: https://github.com/angular/material2/blob/master/guides/theming.md

**Comment by maciejsobala** [comment] 2017-01-13 15:20
@dahaupt 
1. Unfornatelly template provided by you is not working

2. I am using a theme:

My style.scss file begins with:

`@import './palette';`

And here is palette.scss

```
@import '../../../node_modules/@angular/material/core/theming/all-theme';
// Plus imports for other components in your app.

// Include the base styles for Angular Material core. We include this here so that you only
// have to load a single css file for Angular Material in your app.
@include md-core();

// Define the palettes for your theme using the Material Design palettes available in palette.scss
// (imported above). For each palette, you can optionally specify a default, lighter, and darker
// hue.

$primary: md-palette($md-light-blue, 600);
$accent:  md-palette($md-light-blue, 800);
$secondary: md-palette($md-teal, 400);

// The warn palette is optional (defaults to red).
$warn:    md-palette($md-deep-orange);

$foreground: md-palette($md-teal);

$background: md-palette($md-blue-grey, 200);



// Create the theme object (a Sass map containing all of the palettes).
$theme: md-light-theme($primary, $accent, $warn);



// Include theme styles for core and each component used in your app.
// Alternatively, you can import and @include the theme mixins for each component
// that you are using.
@include angular-material-theme($theme);
```


I am using 'raw-loader' and 'node-sass' for compiling styles:
```
{
          test: /\.scss$/,
          loaders: ['raw-loader', 'sass-loader'] // sass-loader not scss-loader
        }
```

**Comment by maciejsobala** [comment] 2017-01-13 15:27
I think, that the problem is that `_a11y.scss` file is not included to my final css bundle.

I see in my website code, takt checkbox input have class `.cdk-visually-hidden`,
but styles from `_a11y.scss` are not applied:

@mixin cdk-a11y {
  .cdk-visually-hidden {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    text-transform: none;
    width: 1px;
  }
}

**Comment by dahaupt** [comment] 2017-01-13 15:36
@maciejsobala Why is the punker template not working? Working fine here, it's the official issue template by @DevVersion :)

**Comment by maciejsobala** [comment] 2017-01-13 20:50
<img width="1341" alt="screen shot 2017-01-13 at 9 49 37 pm" src="https://cloud.githubusercontent.com/assets/15926528/21945202/4442677a-d9da-11e6-83bc-a5822d726d59.png">

**Closed** 2017-01-18 11:28 UTC

**Comment by adrian-mitangi** [comment] 2017-01-19 04:20
I'm noticing the same issue with the version of material that I'm using "@angular/material": "^2.0.0-beta.1".  I don't see a class declaration for .cdk-visually-hidden.

**Comment by maxailloud** [comment] 2017-02-14 11:41
I have the same issue. ``.cdk-visually-hidden`` is not present and so I can see the native checkbox .

**Comment by andrewGlee** [comment] 2017-02-17 11:42
I have the issue too

**Comment by maxailloud** [comment] 2017-02-17 11:48
I fixed the problem by theming the material design, I used https://material.angular.io/guide/theming to do it.
Basically it will import the material design style, that's what currently missing.

**Comment by andrewGlee** [comment] 2017-02-17 11:53
Thanks, yes that makes sense.  I will probably end up going down that path, but at the end of the day, the guide for 'Using a pre-built theme' doesn't work, so I'm not sure why this issue is closed.

**Comment by JaserAkuly** [comment] 2017-04-10 19:01
@maxailloud I am also using Angular Material, and having the same exact issue, unable to hide the extra square on top.

**Comment by dgavigan** [comment] 2017-04-10 19:24
@JaserAkuly make sure the material css is loading properly. If you'r using Webpack, make sure your using the `style-loader`. 

The CSS was loading with the main bundle. Extracting it out to its own file and ensuring it loaded first fixed my problem. Hope this helps!

**Comment by simeyla** [comment] 2017-06-17 00:16
If you are trying to add the theme to a .css or .scss file with something like:

@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';

You may need to disable view encapsulation

@Component({
  selector: 'app-root',
  template: require('./app.component.html'),
  styles: [require('./app.component.scss')],
  encapsulation: ViewEncapsulation.None 
})

This is because the css gets rewritten to something like this :

.cdk-visually-hidden[_ngcontent-c0]{border:0;clip:rect(0 0 0 0);

You're better off including it globally as a static file. In other words this may explains why it may be failing for you but I'm not enough of an Angular expert to know the best solution - or other ways to include it where view encapsulation isn't used.

**Comment by avrilfanomar** [comment] 2018-03-13 13:58
@simeyla thanks a lot for a "ViewEncapsulation.None" tip! That was problem in my case.
