### ISSUE TITLE
Selection list options do not support avatars

### ISSUE THREAD

**Issue by CDDelta** [angular/material2#11071] opened 2018-04-30 12:36 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
![Selection list with avatar](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bx4BSt6jniD7YUQ5TEFVT3ZJQjg/components-listcontrols-checkbox2.png)

#### What is the current behavior?
Selection list options do not support avatars

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
https://stackblitz.com/edit/angular-material2-issue-yqu5b5

#### What is the use-case or motivation for changing an existing behavior?
To be in line with material specs.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material: 6.0.0.rc-1

**Comment by crisbeto** [comment] 2018-05-01 18:02
Closing as a duplicate of https://github.com/angular/material2/issues/10192.

**Closed by crisbeto** 2018-05-01 18:02 UTC
