### ISSUE TITLE
[NPM Package] @angular2-material/all

### ISSUE THREAD

**Issue by Pixcell** [angular/material2#1083] opened 2016-08-19 06:56 UTC
#### Bug, feature request, or proposal:

Proposal

#### What is the expected behavior?

installing @angular2-material/all through npm should install all available components, including the bottleneck module MaterialModule

#### What is the current behavior?

@angular2-material/all is not a npm repository

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?

A quick way to install, and update all materials components available.

#### Is there anything else we should know?

I am sorry if this was not the place to ask for this. Feel free to close the issue and redirect me to were I am supposed to do such proposals.

**Comment by jelbourn** [comment] 2016-08-22 15:27
Dupe of #236

**Closed by jelbourn** 2016-08-22 15:27 UTC
