### ISSUE TITLE
Error after Upgrade to aplpha.11-3

### ISSUE THREAD

**Issue by divramod** [angular/material2#2187] opened 2016-12-12 22:31 UTC
#### Bug, feature request, or proposal:
Bug?

#### What is the expected behavior?
No Error Message

After Upgrading Material to alpha.11-3 i am getting the following error message:

```
Error: Unexpected value 'CommonModule' imported by the module 'MdButtonModule'
```

thx in advance for help

**Comment by belev** [comment] 2016-12-12 22:49
@divramod Are you using Angular CLI? I tested it now with it and everything seems to be working correctly with the button module. Can you provide some more information about the project structure you are using so that it will be easier for someone to reproduce your issue and help you?

**Comment by jelbourn** [comment] 2017-01-27 02:54
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Closed by jelbourn** 2017-01-27 02:54 UTC
