### ISSUE TITLE
Proposal: Refactor overlay 

### ISSUE THREAD

**Issue by shlomiassaf** [angular/material2#715] opened 2016-06-17 20:03 UTC
@jelbourn While trying to use Overlay as the underlaying container for my angular2-modal component I found myself playing with the structure a bit to get better WebWorker support, less DOM interaction and more flexibility (custom classes, pane, container).

This is a bit long, I wanted to make sure I'm clear.

I ended up with a nice solid design for the overlay that reduces DOM interaction to almost nothing. This design will also work in native script, for example...

I didn't post PR since it pointless, so I put up a proposal, you can review my branch to get an idea.

#### What is the expected behavior?
Reduce DOM interaction, support WebWorker and make the overlay container and pane more "angularish" 

#### What is the current behavior?
Overlay service is using the DOM to manually insert both `overlay container` and `overlay pane`s 
This in turn "forces" all implementations `PositionStrategy` to use direct DOM access.

#### What is the use-case or motivation for changing an existing behavior?
Support universal, reduce DOM access, use one position strategy for all platforms (layout will apply using bindings), support declarative overlay component. Use angular component's for the overlay container and for panes... In short the angular way.

#### Is there anything else we should know?
**Basic design:**
The `Overlay` service should be platform agnostic. The overlay-container and overlay-pane children are both angular **components**.  
The generic `Overlay` service expects an overlay-container to be declared in a template  (1 only, inside app root template). This means an `OverlayContainer` component is used, which publish it's creation/destruction to the `Overlay` service.  
The `ContainerComponent` is in charge of adding panes to itself which reduce the complexity of the `Overlay` service, aligns with SRP and also with angular since only components should add child components to their tree (manually), since only they have access to the `ViewContainerRef`, i.e: `AppElement`.
This can be done using a `CompoenentFactory` or by letting angular do the work via `*ngFor` of plain **Pane** objects (more complex since addPane() need to return the pane element)  
I used the manual approach in my branch.

**Browser specific design:**
In a browser, a `DOMOverlay` service (extends `Overlay`) is used (override via provider config).
The `DOMOverlay` reflects the original behavior, which is - material needs to insert the overlay container manually into the DOM.
The `DOMOverlay` apply 2 changes to the the base `Overlay` service while not changing logic or flow, we still have the container and panes as angular Components.  

**Change 1**: Hook to the  request overlay-container process,  add it to the DOM (appendChild), return control. From here `Overlay` will take it, the `OverlayContainer` component will identify our newly added element that matches it's selector and create itself + let `Overlay` know about it. There is a catch, see change 2. 

Change 2: After creating a Pane, fire a change detection on the container tree to reflect ID and class (bindings). This is mandatory since our root overlay container is not connected, in any place, to the root host view (app root component). This results in it not being a part of change detection and life cycle hooks. This change will make sure to trigger change detection. 

[Here is a link](https://github.com/shlomiassaf/material2/commit/4b6556211d8e58da369259b5bfbada76c58413be) to a commit with the implementation of the above, with all unit tests passing and demo updated to use `DOMOverlay`

> Note1: Implementation in the link does not refactor the `PositionStrategy` implementations, if the proposal turns into a PR I will update all `PositionStrategy` implementations to binding expression instead of direct DOM manipulation, this will eliminate all `Element` usage within the overlay service, we will only deal with `ComponentRef`s

  
>Note2: this proposal doesn't not care about `Portal` implementation, it assumes its platform agnostic as well.

**Comment by jelbourn** [comment] 2016-06-17 22:51
I don't quite understand the need to make overlay platform agnostic- the entire reason it exists is to handle all of the difficult behaviors (positioning, scrolling, animation, etc.) that are inherently specific to the DOM. Other rendering environments, like in NativeScript, would use [native pop-ups](http://docs.nativescript.org/ui/ui-dialogs) that would require completely different code to drive them. Angular Material only aims to build components/foundation for the web, so as far as I can see, separating `Overlay` and `DomOverlay` wouldn't serve much of a purpose. 

There is a known bug with the overlay preventing it from working in Universal, but the fix for this is straightforward: the overlay container element shouldn't be created until the first overlay is actually created (which should only occur once the app is on the browser). I'm having a hard time seeing a valid use-case for creating some kind of overlay _during_ the pre-render, especially since the positioning will typically depend on viewport size and calls to `getBoundingClientRect`.

For WebWorkers, we're waiting for a feature in Angular core (custom renderers) to support this. This will let us continue to have specific classes that deal with the DOM while Angular deals with the marshaling between UI and WebWorker threads. 

The primary problem with forcing the overlay container to be a part of the Angular app is that you can start running into clipping issues. _We cannot assume that a page consists of only one single Angular 2 application_. A page may have more than one Angular 2 app, or it may have a side-by-side Angular 1 and Angular 2 app (such as during migration), or it maybe simply be just a subsection of the page. As such, you have no guarantee that the parent of your Angular app will not clip (via `overflow: hidden`) floating content:
![image](https://cloud.githubusercontent.com/assets/838736/16166264/bf46628c-349e-11e6-91ba-36a1034d7be8.png)

The way to work around this restriction is to always add the overlay element directly to the document body, which requires directly touching the DOM. While this is generally something that you want to avoid, you'll never be able to get away from it completely (especially for a component library). 

Doing it this way has the side-effect of not requiring the users to ever add anything special to their app templates to make overlays work (no leaking implementation details). This allows users to simply consume a service, such as `MdDialog`, and say `dialog.open(UserProfile)`, and it _just works_.

**Comment by shlomiassaf** [comment] 2016-06-17 23:43
@jelbourn Thanks you for the informative response! 

It actually supports adding it as the last child of `<body`> by default, as for the forcing it to be a part of the app, it was just a sample, you can also put the tag outside of the root component as the last child, it will still work. BTW, it's never part of the app since it's not connected to and host view, it's a standalone something like a new app without change detection...

Anyway, it's your'e call.
I think the proposed design offers more flexibility while behavior is the same (last child of `<body`).
It also allows greater customisation, ability to change the component and other things. Something the core should provide considering it's not aiming for material only, it will target wider audience.
It can also bind styles to the container/pane instead of manually setting them, no impact here, just more angular :)

I don't think there's a compromise here, only benefits.

As for having `Overlay` and `DOMOverlay`, it can be merged into once, thing is I wanted to have a non DOM generic service, having the `DOMOverlay` inside will not allow that.

Other then that, more use cases are there, we don't know them because it's still early. Since the `core` is going to be used widely, more the material2 components, I think it should allow some level of flexibility. It's not that we're complicating things, it's just separation.

Anyway, I accept any decision with love, it's was fun to get into the `Portal`\`Overlay` concepts.

**Comment by shlomiassaf** [comment] 2016-06-18 00:13
btw, current limitation is that when displaying a `Component` in a portal/overlay you must supply a `ViewContainerRef`. It's nothing serious but some boilerplate and some extra work since if you invoke it from a component you can get a `ViewContainerRef`.

 if the container is a component you're free of that.

**Comment by jelbourn** [comment] 2016-06-18 00:27
@shlomiassaf I've got a PR in the works on angular core that would let you get a `ViewContainerRef` without explicitly passing one.

**Comment by shlomiassaf** [comment] 2016-06-18 01:04
@jelbourn OK, that's cool, been waiting for this :) will solve my #9254
Do you have a link?

**Comment by pkozlowski-opensource** [comment] 2016-06-18 17:19
@jelbourn would you mind sharing more info about [the solution you are working on](https://github.com/angular/material2/issues/715#issuecomment-226910186)? I guess we all feel like there is sth missing in the core to properly handle overly-like use-cases.

I've briefly discussed this with both @mhevery and @tbosch and opened #9293 as the result.

**Comment by jelbourn** [comment] 2016-06-20 16:43
@pkozlowski-opensource I had talked with @tbosch and his suggestion was to make `ViewContainerRef` (and other per-component injectables) able to be injected into service as well as directives. When doing this, you would get the instance from the point in the tree where the service is _provided_. I have a branch with the change, but I put it aside temporarily because building/testing angular core was such a nightmare.

**Comment by rigolepe** [comment] 2016-07-29 17:32
I'm not sure if this question belongs in this thread, but I noticed that the connected-overlay position is not recalculated when a browser window is resized. This is easily reproduced by opening the overlay-demo on a wide (normal) screen width click the "Open menu" button to show the overlay and then make the browser window really narrow so that this button is moved to the next line. Open en close the overlay again and notice that it's still on the old position. I would open a new issue if I was sure this isn't a duplicate.

**Comment by jelbourn** [comment] 2016-07-29 17:43
Resize and scroll behavior haven't been added to the overlay yet.

**Comment by jelbourn** [comment] 2016-09-02 00:16
Closing this as we're going with overlay as it is now. It will eventually be improved by custom renderers when they're added to angular.

**Closed by jelbourn** 2016-09-02 00:16 UTC
