### ISSUE TITLE
mat-icon-button shows focus circle after snav.close()

### ISSUE THREAD

**Issue by ericuldall** [angular/material2#11403] opened 2018-05-18 17:18 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The mat-icon-button will not be focused after closing the sidebar via `snav.close()`

#### What is the current behavior?
The mat-icon-button is focused after closing the sidebar via `snav.close()`

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ubvx8j?file=app%2Fsidenav-responsive-example.html

#### What is the use-case or motivation for changing an existing behavior?
UI/UX Is not intuitive or easily controlled. Any workaround seems hacky at this point.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Currently testing latest in Chrome on MacOS.

**Comment by AndrewEckart** [comment] 2018-05-18 20:07
I've noticed an issue which is probably related - When using a button to open a MatDialog, the button will still have its focus style applied once the dialog is closed. This is actually visible in the current docs for AM 6.0.1: https://material.angular.io/components/dialog/overview

I suspect this may be intentional for accessibility, but it looks weird. According to [this blog post](https://marcysutton.com/button-focus-hell/), this issue used to exist in all AM buttons and the proper behavior is to give the element focus but remove the focus style.

**Comment by ericuldall** [comment] 2018-05-18 21:08
It may be intentional, but I think it's reasonable to make this configurable. It should be an implementation detail. As of now I'm thinking there's a couple hacks to get rid of that:

1. Apply custom style to `.cdk-focused .cdk-program-focused` on the element in question
2. Remove the `.cdk-focused .cdk-program-focused` classes from the element after the former event

Ideally there could just be some flag similar to the following:
```
<button mat-icon-button [disableFocus]="true"><mat-icon>menu</mat-icon></button>
```

**Comment by AndrewEckart** [comment] 2018-05-18 21:20
@ericuldall It can be solved pretty easily by adding `onclick="this.blur()"` to the desired element, though it is a bit annoying to add it everywhere. I forked your Stackblitz and added a 2nd button to demonstrate: https://stackblitz.com/edit/angular-ubvx8j-hgza91?file=app/sidenav-responsive-example.html

**Comment by ericuldall** [comment] 2018-05-18 21:56
Yea, that seems to be a trivial fix for now. I didn't want to ripple at all so I just removed the `mat-icon-button` directive.

**Comment by crisbeto** [comment] 2018-05-19 07:03
Closing as a duplicate of https://github.com/angular/material2/issues/8420.

**Closed by crisbeto** 2018-05-19 07:03 UTC

**Comment by pablomario** [comment] 2019-03-04 14:40
In my case, the real problem stay in button structure, 'material' build various sub components and last one is a 'div' with css class 'mat-button-focus-overlay':

My solution is simply, in 'style.css' file, add or sobrescribe the 'mat-button-focus-overlay' 

`.mat-button-focus-overlay {
    background-color: transparent!important;
}`

**Comment by LeandroDoldan** [comment] 2019-04-15 23:01
Still an issue.

**Comment by daundkarmangesh1109** [comment] 2019-05-30 04:53
Simply set [disableRipple]="true" in html.
<button mat-icon-button [disableRipple]="true">
    <mat-icon>menu</mat-icon>
</button>

**Comment by simeyla** [comment] 2019-08-18 04:37
Simply throw your computer out the window...

**Comment by simeyla** [comment] 2019-08-18 05:01
Inspired by @AndrewEckart answer - and in agreement of how it is more than a bit annoying here's my solution:

The following function finds and stores the `currentTarget` (which is the button or other element that initiated the dialog open). Then when the dialog is closed it blurs the button. Put this function somewhere accessible everywhere.

```
export const fixDialogFocus = (dialogRef: MatDialogRef<any>) => 
{
    if (event && event.currentTarget && (<any> event.currentTarget).blur)
    {
        const initiator: any = event.currentTarget;

        dialogRef.afterClosed().subscribe(() => 
        {
            setTimeout(() => {
                try { initiator.blur(); } catch {}    
            }, 0);
        });
    }
}
```

I just add this to each of my dialog constructors, or `onInit()` method:

```
export class DialogChoicesComponent<T extends {}> implements OnInit {

constructor(@Inject(MAT_DIALOG_DATA) public model: DialogChoicesModel<T>,
            public dialogRef: MatDialogRef<DialogChoicesModel<T>, DialogChoicesResult<T>>) { }

    ngOnInit() 
    {
        // magically unfocus initiator after dialog is closed
        fixDialogFocus(this.dialogRef);   
    }
```

Much easier to find everywhere you've used `MatDialogRef<...` than to find every individual button.
