### ISSUE TITLE
Datepicker Selection off by 1 day IF the year is 1964 and below.

### ISSUE THREAD

**Issue by eddiederk** [angular/material2#6538] opened 2017-08-18 05:11 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When you click on a date, the input value should be the day you click

#### What is the current behavior?
If you select a date that is BOTH in the year 1964 or below AND the day is AFTER the 10th then the date displayed in the input box shows the day before the selected date. (But the calendar shows the correct date) 

#### What are the steps to reproduce?
Enter the date 9/12/1963 into the input box
Open the calendar and select 9/15/1963
Notice the input box says 9/14/1963

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

https://material.angular.io/components/datepicker/overview

You can use the material demo site to reproduce.
No coding required! Yeah.

#### What is the use-case or motivation for changing an existing behavior?
Old people get frustrated when they cant select their birth date 🥇 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.1.2
Material: 2.0.0-beta.8
Doesn't work on ->Chrome OS: Version 60.0.3112.101 <-
It works just fine on -> Microsoft Edge 40.15063.0.0  <-

#### Is there anything else we should know?
You guys are crazy amazing!
Keep it up!

**Comment by donroyco** [comment] 2017-08-18 06:12
If I reproduce your issue, the date states `14/09/1963` (09 February 1964 if counting), while at first it was `09/12/1963` (12 September 1963).

The focus on the particular date in 1963 is also gone, see attachment. It jumps back to 2017. 
![date-picker-issue](https://user-images.githubusercontent.com/1763537/29446533-f1bb2862-83ec-11e7-9a92-fb1253269e49.png)

**Comment by julianobrasil** [comment] 2017-08-18 09:58
It depends on the locale and it affect daylight summer time in past dates when they don't follow today's dst rules. #5747 corrects it and will be available in the next release.

**Comment by mmalerba** [comment] 2017-08-28 21:57
closing since this has been fixed by #5747

**Closed by mmalerba** 2017-08-28 21:57 UTC
