### ISSUE TITLE
Add rectangular fill to input fields

### ISSUE THREAD

**Issue by jasekiw** [angular/material2#7327] opened 2017-09-26 12:43 UTC
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?

The ability to specify a rectangular fill on an  input field for either light or dark theme.

#### What is the current behavior?
There is no option to specify a field with rectangular fill.

#### What is the use-case or motivation for changing an existing behavior?
It would help us serve customers who are more accustomed to the rectangle style of input.
It is also in the material design spec.

https://material.io/guidelines/components/text-fields.html#text-fields-text-field-boxes

**Comment by willshowell** [comment] 2017-09-26 14:23
I think this will be covered by https://github.com/angular/material2/issues/3984

**Comment by josephperrott** [comment] 2017-09-26 15:44
Closing as duplicate of #3984

**Closed by josephperrott** 2017-09-26 15:44 UTC
