### ISSUE TITLE
Switching tabs reset the content.

### ISSUE THREAD

**Issue by Salma7amed** [angular/material2#1585] opened 2016-10-24 21:07 UTC
On switching tab the content of the form fields are reset to default.

Example I have 2 tabs that contain forms. When filling and switch back and forth between them, I expect to get the input fields of the form to contained the entered values and not to be reseted on switching.

Here is a plunker http://plnkr.co/edit/oK7TAQ64lAZspL0G7ZA4

**Comment by ZeBigDuck** [comment] 2016-10-25 20:07
I've got the same problem.

The problem is that content is destroyed while switching to another tab. That make this md-tabs usable only for static content...

**Comment by RoxKilly** [comment] 2016-10-26 06:29
@Salma7amed , if you link your form inputs to class variables -- eg: by using `formGroup` or `formControl`  --, I think the form state will be rebuilt for you when you switch tabs since the underlying variables would be unchanged.

**Comment by Salma7amed** [comment] 2016-10-26 07:28
@ZeBigDuck so the fix will be applied in the next release ?.

@RoxKilly the thing is I don't want it to rebuild the form on each switch. Because in case of tabs containing huge amount of data, it causes unnecessary lag due to the rebuild on each switch.

**Comment by jelbourn** [comment] 2016-10-27 16:56
Dupe of #1472

**Closed by jelbourn** 2016-10-27 16:56 UTC
