### ISSUE TITLE
Dynamically changing mat-option names

### ISSUE THREAD

**Issue by tudor2004** [angular/material2#9129] opened 2017-12-26 19:24 UTC
#### FEATURE REQUEST

Dynamically changing mat-option names

#### What is the expected behavior?

The <mat-option> element should automatically change its name if the name content has changed

#### What is the current behavior?

Although the name variable is changed, the <mat-option> element isn't showing it correctly

#### What are the steps to reproduce?

```
              <mat-form-field class="full-width">
                    <span *ngFor="let location of locations">
                        {{ location.name[showLang] }}
                    </span>

                    <mat-select
                            [placeholder]="'Location"
                            [(ngModel)]="service.locationId">
                        <mat-option
                                [value]="location.id" *ngFor="let location of locations">
                            {{ location.name }}
                        </mat-option>
                    </mat-select>
                </mat-form-field>
```

The expected behavior is: Whenever the `location.name` property changes, the `<mat-option> `element should display its content, exactly like it happens in the `span` above.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular ^5.0.0
Angular Material ^5.0.0-rc.2
OS macOS Sierra 10.12.6
TypeScript ~2.4.2
Any browsers

**Comment by crisbeto** [comment] 2017-12-26 19:37
Closing as a duplicate of https://github.com/angular/material2/issues/7923.

**Closed by crisbeto** 2017-12-26 19:37 UTC
