### ISSUE TITLE
Not able to print the angular material site in Firefox

### ISSUE THREAD

**Issue by admosity** [angular/material2#10706] opened 2018-04-04 19:59 UTC
#### Bug:
Seems like there is some scenario that printing on a flex based angular site on Firefox only prints out the first page and cuts off the rest of the content. Also seems that fixed content is also duplicated across multiple pages.

#### What is the expected behavior?
Should print correctly.

##### Mac print preview:
![image](https://user-images.githubusercontent.com/4655972/38330373-6b821a80-381e-11e8-9a7b-85a4834f5ca9.png)

##### Physical print out 
![image](https://user-images.githubusercontent.com/4655972/38330906-cf938b98-381f-11e8-9117-f941b52785af.jpg)

##### Print preview from chrome works as expected
![image](https://user-images.githubusercontent.com/4655972/38331360-05b54242-3821-11e8-8333-bd233ae87bbb.png)

#### What are the steps to reproduce?
Use Firefox or Firefox developer edition and try printing/previewing (done on mac)
https://material.angular.io/

#### What is the use-case or motivation for changing an existing behavior?
We are having the same issue on a site that needs a print view.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Firefox Quantum 59.0.2 (64-bit)
Firefox Developer Edition 60.0b7 (64-bit)

#### Is there anything else we should know?
Setting the top level container to block appears to alleviate some problems.

**Comment by mtrdp642** [comment] 2018-04-04 20:55
Duplicate issue [from the angular/material.angular.io repo](https://github.com/angular/material.angular.io/issues/333).

**Comment by admosity** [comment] 2018-04-04 21:01
Thanks. Also a dupe of #8378.

It seems that chrome prints better now since the last issue that was filed.

**Comment by jelbourn** [comment] 2018-04-09 23:04
Duplicate of https://github.com/angular/material.angular.io/issues/333

I'll be honest, it's not particularly a priority.

**Closed by jelbourn** 2018-04-09 23:04 UTC

**Comment by admosity** [comment] 2018-04-17 15:43
@jelbourn Thanks for the affirmation.

**Comment by jzgoda** [comment] 2019-01-15 15:06
@jelbourn, I understand that this isn't a priority, but printing in Firefox is still broken.
So why was this issue closed? 

This isn't limited to to just the Angular Material docs site, but also the sites that us consumers of Material are building; so this issue seems more appropriate than angular/material.angular.io#333.
Issue #8378 was also closed without a fix, even when the "working" examples sited there don't actually work in Firefox.

Are there any reliable workarounds to get this working?

**Comment by admosity** [comment] 2019-01-16 19:41
@jzgoda We've taken the path that the angular.io site itself took which was quite painful and just go through on a case by case basis to provide print style overrides. This may require isolating specific components that are problematic with regards to printing. You can see in the print stylesheet below, there are direct overrides on Material components as well.

Here's the print stylesheet from angular.io:

https://github.com/angular/angular/blob/master/aio/src/styles/_print.scss

**Comment by jzgoda** [comment] 2019-01-18 20:36
@admosity, thanks for getting back to me. I was hoping for a more elegant solution, similar to how it "just works" in Chrome; but I'll head down the painful path if that's the only one.

It also appears that this might be part of the real issue: https://bugzilla.mozilla.org/show_bug.cgi?id=939897
