### ISSUE TITLE
Expansion panel auto expanded when used within tabs 

### ISSUE THREAD

**Issue by sndpmhr** [angular/material2#6982] opened 2017-09-11 11:37 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
It should be in that state in which developer wants.

#### What is the current behavior?
Let say there are three tabs and all have expansion panels populated via ngFor. When loaded then all the expansion panel of active tab remain collapsed. When switching to another tab then that particular tab's expansion panel opened n matter what to be intended. 

#### What are the steps to reproduce?
Simply populate three tabs having expansion panel via ngFor

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material beta.8

**Comment by julianobrasil** [comment] 2017-09-11 11:55
Duple: #5269

**Comment by rayabhagis** [comment] 2017-09-24 06:39
I am seeing this behavior as well. Is there a workaround for this one.

**Comment by josephperrott** [comment] 2017-09-25 23:31
Closing as duplicate of #5269

**Closed by josephperrott** 2017-09-25 23:31 UTC

**Comment by ThomasAdr** [comment] 2019-07-31 14:52
Issue still exists in version 8.
