### ISSUE TITLE
MatDatepicker -> range selector

### ISSUE THREAD

**Issue by xAqweRx** [angular/material2#9404] opened 2018-01-15 15:56 UTC
#### Bug, feature request, or proposal:
feature

#### What is the expected behavior?
Is there any plans to make range datepicker

**Comment by lihanyu23** [comment] 2018-01-15 16:25
duplicate of #4763

**Comment by josephperrott** [comment] 2018-01-16 16:59
Closing as duplicate of #4763

**Closed by josephperrott** 2018-01-16 16:59 UTC
