### ISSUE TITLE
MatCheckbox: binding to 'checked' property doesn't initialize checked appearance properly when on dialog

### ISSUE THREAD

**Issue by gtranter** [angular/material2#9363] opened 2018-01-12 22:30 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Binding 'checked' property on a mat-checkbox should initialize the checked appearance of the checkbox.

#### What is the current behavior?
Checkbox's checked property does not match checked appearance on initialization when opened in a dialog.

#### What are the steps to reproduce?
http://plnkr.co/edit/cptbZhIRj1yCgR5JsLO1?p=preview

The use case is a 'select all' override switch for a group of checkbox options. The 'checked' property of each checkbox is bound to the override value ORed with the checkbox's model value. The select all switch does not update the checkboxes' models, it just affects the 'checked' state which changes the appearance only. The purpose is to allow the user to revert a select all operation anb go back to the original selections (without having to implement backup and restore operations).

It works fine after the dialog is opened - but the initial state when the dialog is opened is not correct.

1. Click the' Select Items' button to open the selection dialog
2. Enable 'Select All Items'
3. Close dialog
4. Open the dialog again
5. Notice that checkboxes 1 and 3 are not checked even though 'Select All Items' is enabled.
6. Inspect one of the unchecked checkboxes. Notice that on mat-checkbox, ng-reflect-checked="true" but the class 'mat-checkbox-checked' is missing.

#### What is the use-case or motivation for changing an existing behavior?
Works incorrectly - user experience is not correct.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
5.0.4

#### Is there anything else we should know?
This is an odd one. I think the disagreement between the ng-reflect-checked value and the mat-checkbox-checked class indicates a true problem in the framework not the application.

**Comment by julianobrasil** [comment] 2018-01-13 00:14
You're binding the checkboxes values to `ngModel` and to `checked` property at the same time. During the initialization, `ngModel` updates the checkboxes after the `checked` property, so the values set by `checked` are overriden by `ngModel`. You can avoid it by using `setTimeout`'s in checked property.

**Comment by gtranter** [comment] 2018-01-15 17:01
Thanks @julianobrasil. I've implemented a different workaround but your suggestion helped.

**Comment by josephperrott** [comment] 2018-01-16 16:44
Closing as this is caused by binding to both `checked` and `ngModel` as @julianobrasil outlined.

**Closed by josephperrott** 2018-01-16 16:44 UTC

**Comment by gtranter** [comment] 2018-01-16 18:04
Can you enlighten me as to why this is wrong? Are not state and model two independent things that should be allowed to be bound? If you can, could you point to source code that shows how 'checked' and ng-model are interdependent? It puzzles me that this works fine except on initialization and yet the approach is deemed wrong not the component, despite the obvious inconsistency between ng-reflect-checked and mat-checkbox-checked. Thanks.

**Comment by gtranter** [comment] 2018-01-16 19:19
Follow-up question - if binding to checked is discouraged - would applying mat-checkbox-checked via ngClass be an acceptable approach? I'm basically looking for suggestions on how to do this "properly."

**Comment by Abadii** [comment] 2018-10-17 10:41
It also happens when there are multiple checkboxes with the same name (when used ngModel in *ngFor loop). After giving a different name to checkbox (e.g. [name]="'booRequired-'+i") it should work.
