### ISSUE TITLE
md-checkbox will distortion when width is very small

### ISSUE THREAD

**Issue by zealitude** [angular/material2#1851] opened 2016-11-14 09:40 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-checkbox with long text keep square shape when container element width is very small

#### What is the current behavior?
md-checkbox with long text shape distort when container element width is very small

#### Which versions of Angular, Material, OS, browsers are affected?
Material 2.0.0-alpha.10
Google Chrome Version 54.0.2840.99 m

**Comment by krigton** [comment] 2016-11-14 14:55
Would you please provide plunkr for this problem? thanks

**Comment by jelbourn** [comment] 2016-11-14 23:22
@zealitude Please provide a reproduction or steps to reproduce.

**Comment by zealitude** [comment] 2016-11-14 23:39
Hi all, you can reproduce the bug from the Readme md-checkbox demo link
https://plnkr.co/edit/P7qce8lN9n2flS6kBhDy?p=preview
just try to change the preview windows (right hand side view) width 

ps. I found that the bug will occur when one line text become two lines in very small width.

**Comment by krigton** [comment] 2016-11-14 23:55
@zealitude @jelbourn A quick fix would be to set the md-checkbox-frame's and the md-checkbox-background's width to 18px. Also set the label's white-space to nowrap. There is not enough space so the browser tries to rearrange the children of the checkbox. I'll try to see I can find a better solution for this.

**Comment by tinayuangao** [comment] 2016-11-15 01:03
This is a duplicate of issue #1097. It's fixed on current master.

**Closed by tinayuangao** 2016-11-15 01:03 UTC
