### ISSUE TITLE
md-list-option in md-selection-list not calling selectChange and deselect when toggled

### ISSUE THREAD

**Issue by orwtech** [angular/material2#7529] opened 2017-10-04 15:33 UTC
#### Bug, feature request, or proposal:
md-list-option in md-selection-list not calling selectChange and deselect when toggled

#### What is the expected behavior?
Call selectChange and deselect EventEmitter inside toggled() method

#### What is the current behavior?
selectChange and deselect EventEmitter not called inside when toggled() method

#### What are the steps to reproduce?

<md-selection-list #stateList >
        <md-list-option *ngFor="let state of availableStates" (selectChange)="selectChange($event)" checkboxPosition="before" value="state.id" >
          {{state.name}}
        </md-list-option>
      </md-selection-list>

#### What is the use-case or motivation for changing an existing behavior?
Collect information about checked states and save the value in an array for later processing outside the child component having the md-list-selection

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/cdk": "^2.0.0-beta.11",
"@angular/material": "^2.0.0-beta.11",

**Comment by CRollin** [comment] 2017-10-04 15:47
Duplicate of #7396. Looks like it will be fixed by #6901 :)

**Comment by josephperrott** [comment] 2017-10-04 15:49
Closing as duplicate of #7396

**Closed by josephperrott** 2017-10-04 15:49 UTC
