### ISSUE TITLE
Bootstrap grid and Angular Material

### ISSUE THREAD

**Issue by avechuche** [angular/material2#11294] opened 2018-05-11 22:25 UTC
#### Bug, feature request, or proposal:
Bug?

#### What is the expected behavior?
I need that the checkbox does not overlap on the control that has to its side

#### What is the current behavior?
The checkbox is superimposed on the control it has at its side

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-kqbrkb?file=src%2Fapp%2Fapp.component.html

![1](https://user-images.githubusercontent.com/11781418/39949384-e9ee0cb8-5550-11e8-9d3e-1ca24d569175.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 5.2.4

#### Is there anything else we should know?
I am trying to create a "row" with 3 components, 1 checkbox and 2 mat-select, the problem is that the checkbox is superimposed over the next element. How can I solve that? Will it be possible that Material is not 100% compatible with bootstrap grid?

**Comment by julianobrasil** [comment] 2018-05-12 10:35
That's because `.mat-checkbox-label` class has `white-space: nowrap;` by design. There are some related discutions about it: #2019, #8416, #10954 and others. You can: set `encapsulation: ViewEncapsulation.None` and override `.mat-checkbox-label` in component css (it stil o:

```css
.my-class .mat-checkbox-label {
  white-space: normal;
} 
```
```html
<mat-checkbox class="my-class">Large text</mat-checkbox>
```

Or you can apply bootstrap classes directly to `mat-checkbox` to make shure it takes the space specified by `*col-*` attributes (no wrapping):

```html
<mat-checkbox class="col-sm-2 col-md-2 col-12">Large text</mat-checkbox>
```

**Comment by amcdnl** [comment] 2018-05-13 17:52
Closing since this is not related to the Angular Material project.

**Closed by amcdnl** 2018-05-13 17:52 UTC
