### ISSUE TITLE
Weird ripple effect

### ISSUE THREAD

**Issue by BenevidesLecontes** [angular/material2#972] opened 2016-08-09 20:45 UTC
#### Bug, feature request, or proposal:

[x] Bug
#### What is the expected behavior?
Expecting ripple effect on buttons

#### What is the current behavior?
On click ripple effect makes my button wide and ripple color appears like in image below

<img width="835" alt="screen shot 2016-08-09 at 17 36 47" src="https://cloud.githubusercontent.com/assets/1839361/17532698/36d3eeb8-5e58-11e6-8d3a-bf08c1a18a62.png">

#### What are the steps to reproduce?
```
<button md-button md-ripple [md-ripple-color]="rippleColor" (click)="openSideNav($event)"  type="button"
                *ngIf="navigationUrl!=='/' && navigationUrl!=='/login'">
            <md-icon>menu</md-icon>
        </button>
```
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular material alpha.7, chrome 52.0.2743.116 (64-bit) MacOS Sierra

#### Is there anything else we should know?
I'm trying to use the ripple effects on buttons am I missing something? I have my imports like this:
```
imports: [
        BrowserModule,
        MdCardModule,
        MdInputModule,
        MdIconModule,
        MdListModule,
        MdSidenavModule,
        MdToolbarModule,
        MdButtonModule,
        MdTabsModule,
        MdRippleModule,
        ReactiveFormsModule,
        MdMenuModule,
        FormsModule,
        RouterModule.forRoot([...routes], {})
    ]
```

**Comment by jelbourn** [comment] 2016-08-09 20:52
@BenevidesLecontes can you reproduce the issue in a pluker or similar? I don't follow on your steps to reproduce.

**Comment by BenevidesLecontes** [comment] 2016-08-09 21:11
@jelbourn git escaping the html, i update with what i'm using to make this ripple showing like this. And i'll try to make the plunker work with rc5, after that i'll try to update with plunker.

**Comment by jelbourn** [comment] 2016-08-09 21:16
cc @dozingcat

**Comment by dozingcat** [comment] 2016-08-09 21:22
md-button uses the ripple effect by default; you don't need to (and shouldn't) add a md-ripple attribute. You can set the disableRipple property to true to disable the ripple.

**Comment by BenevidesLecontes** [comment] 2016-08-09 21:25
@dozingcat but if i don't use the attribute i can't change the ripple color, i need to disable it and then use the atribute to set the color?

**Comment by BenevidesLecontes** [comment] 2016-08-09 21:30
@jelbourn @dozingcat also md-ripple is creating scroll on my page after several clicks. I think this the cause.
<img width="907" alt="screen shot 2016-08-09 at 18 28 40" src="https://cloud.githubusercontent.com/assets/1839361/17534374/429c5436-5e5f-11e6-87e2-215bb0f140c2.png">

**Comment by dozingcat** [comment] 2016-08-09 22:25
If you get the Plunker set up I can take a look. There's currently not a supported way to change the ripple color on md-buttons. Disabling the existing ripple and adding your own might be a workaround, but that's not the intended use.

**Comment by BenevidesLecontes** [comment] 2016-08-09 23:44
@dozingcat any plunker with material alpha 7 and rc5 to fork? I Forked from here, but i can't make it work.

**Comment by sunshineo** [comment] 2016-08-10 06:38
+1
I'm experiencing exactly the same thing.

**Comment by fernandogomesdf** [comment] 2016-08-10 07:02
I think the folowing error is something related, after upgranding alpha.7 and angular rc.5 : Can't bind to 'md-ripple-trigger' since it isn't a known property of 'div'. ("*ngIf="isRippleEnabled()" class="md-button-ripple" [class.md-button-ripple-round]="isRoundButton()" [ERROR ->][md-ripple-trigger]="getHostElement()" [md-ripple-color]="isRoundButton() ? 'rgba(255, 255, 255, 0.2)"): MdButton@0:180

**Comment by colinfang** [comment] 2016-08-10 12:07
@fernandogomesdf  I encountered this error as well, but it disappeared as soon as I import `MdButtonModule` instead of using directives.

**Comment by colinfang** [comment] 2016-08-10 12:42
I have got the same problem.

Each click of the bottom inserts a

```
<div class="md-ripple-foreground md-ripple-fade-in"
 style="left: -12.3584px; top: -17.7959px; width: 64.7168px;
 height: 64.7168px; transition-duration: 0.1s;
 background-color: rgba(255, 255, 255, 0.2);"></div>
```

Into my html, and it keeps stacking and never goes away.

**Comment by ivoviz** [comment] 2016-08-10 13:54
@dozingcat [Here](http://plnkr.co/edit/bbiUbA489wYtzkqKjS7y?p=preview) is a plunker with RC.5 and alpha.7 to demonstrate the issue. Just press the button a couple of times and you'll see the vertical scrollbar appears. As said by @colinfang above, every time you press the button those divs stack up.

**Comment by BenevidesLecontes** [comment] 2016-08-10 14:20
@dozingcat @ivoviz and also notice in this plunker, no ripple effect after all.

**Comment by dozingcat** [comment] 2016-08-10 14:25
The problem may be that the ripples depend on styles in core.css, which needs to be included in the page (for example https://github.com/angular/material2/blob/master/src/demo-app/index.html#L17 in the demo app). @jelbourn was there going to be a way to automatically include this?

**Comment by ivoviz** [comment] 2016-08-10 14:38
@dozingcat Indeed, I can confirm that adding core.css solves every problem, although it would be nice to have it automatically included somehow.

**Comment by BenevidesLecontes** [comment] 2016-08-10 19:35
@ivoviz adding core.css solved the scroll problem?

**Comment by ivoviz** [comment] 2016-08-10 19:38
@BenevidesLecontes Yes it did for me.

**Comment by BenevidesLecontes** [comment] 2016-08-11 16:23
This Ripple effect doesn't seem reasonable, I can't even seen the effect on dark background.

**Comment by fernandogomesdf** [comment] 2016-08-11 19:40
@colinfang thank you, it was my mistake

**Comment by Mufasa** [comment] 2016-08-12 01:42
Hi,

I am experiencing the same issue in my angular 2 app and was wondering how I can get hold of the core.css file that @ivoviz claims will solve this issue?

Alternatively, can anyone give me an ETA as to when this is officially likely to get fixed?

Thanks in advance

**Comment by jelbourn** [comment] 2016-08-12 01:44
It is in `node_modules/@angular2-material/core`

**Comment by sspilleman** [comment] 2016-08-14 09:08
```
styleUrls: [
    '../../node_modules/@angular2-material/core/style/core.css',
    '../../node_modules/@angular2-material/core/overlay/overlay.css',
    '../../public/styles/main.scss'
]
```

**Comment by Mufasa** [comment] 2016-08-14 12:09
Thanks both - that fixed my issue.

BTW: I had also reported this at [Google Groups - angular-material2](https://groups.google.com/forum/#!topic/angular-material2/vtNOVWK9jvk) and have mentioned these work-arounds there as well.

**Comment by xhite** [comment] 2016-08-18 10:07
@jelbourn @sspilleman it doesn't work for me on alpha7-4. The issue persists even after loading those css files

**Comment by colinfang** [comment] 2016-08-18 11:46
@xhite Maybe because of #1004?

**Comment by jelbourn** [comment] 2016-08-18 15:30
You should load the css files with a `<link>` element rather than `styleUrls` in a component.

alpha.7-4 isn't all the way up to master; it only includes very minor changes that won't affect most users (in this case fixing an issue with `ngc` running on the ripple).

**Comment by xhite** [comment] 2016-08-18 16:02
@jelbourn thanks it works when loading globally with <link>

**Comment by mentatxx** [comment] 2016-08-20 18:17
Also you can just disable ripple for a while

```html
<button md-mini-fab [disableRipple]="true">
    <md-icon>add</md-icon>
</button>
```

**Comment by RoxKilly** [comment] 2016-08-26 11:54
@jelbourn If you get the chance, please write a sentence or two about why you chose to put the styles in a separate CSS that we have to `link` to, rather than stay consistent with Angular's isolated scopes approach that keeps styles within the block scope of their component.  Is this just temporary?

**Comment by jelbourn** [comment] 2016-08-30 16:24
There are some styles that are used between multiple components (such as ripples), so including them directly in the component css instead of globally would lead to a pretty sizable chunk of duplicate payload.

**Comment by jelbourn** [comment] 2016-08-31 01:32
Closing into #1139

**Closed by jelbourn** 2016-08-31 01:32 UTC

**Comment by mgpeng** [comment] 2016-09-02 13:48
Using rc5 and m2 alpha7-4, md-menu html like this:
      <md-menu>
          <button md-menu-item> Refresh </button>
          <button md-menu-item> Settings </button>
          <button md-menu-item> Help </button>
          <button md-menu-item disabled> Sign Out </button>
      </md-menu>
showed like this after rendering:
  <md-menu _ngcontent-dup-2 role="menu">
       
       
  </md-menu>

**Comment by KKrisu** [comment] 2016-10-02 14:58
Currently (angular 2.0, material 2.0.0-alpha.9)  the solution is to include theme in styles.css like:
```
/* You can add global styles to this file, and also import other style files */
@import '../node_modules/@angular/material/core/theming/prebuilt/indigo-pink.css';
```

**Comment by alexlevy0** [comment] 2016-10-13 22:44
I'm also with angular 2.0, material 2.0.0-alpha.9 a solution is to create theme [doc](https://github.com/angular/material2/blob/master/docs/theming.md#defining-a-custom-theme) and link to your project
