### ISSUE TITLE
md-datepicker - should set the input to touched when date is selected with the calendar

### ISSUE THREAD

**Issue by wilker7ribeiro** [angular/material2#6001] opened 2017-07-24 16:09 UTC
#### What is the expected behavior?
Picking a date with the calendar should mark the input as touched

#### What is the current behavior?
It doesn't

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/fdVbAAC4oLLifTsCHdwp

#### What is the use-case or motivation for changing an existing behavior?
I'm creating a date interval component that uses 2 md-datepickes, and not triggering touched is messing up with my validations. (I still can set it programmatically)
Example: 2 datepickers

Initial: initialDate
min: null
max: null

Final: finalDate:
min: initialDate + 7 days
max: null

1 - Set initialDate to 7/1/2017
2 - Set finalDate to 15/1/2017 (touched should be set to true)
3 - Set InitialDate to 20/8/2017
4 - finalDate should be invalid and the error message should appear

**Comment by mmalerba** [comment] 2017-07-24 17:40
duplicate of #5074

**Closed by mmalerba** 2017-07-24 17:40 UTC
Labels: P3: important
