### ISSUE TITLE
[md-slide-toggle][universal-starter] window is not defined

### ISSUE THREAD

**Issue by morriq** [angular/material2#1323] opened 2016-09-24 18:24 UTC
Hello. 

When I've added MdSlideToggle to main.node.ts then my project has stopped building. Similar issue is with MdTooltipModule.

> var __decorate$1 = (window && window.__decorate) || function (decorators, target, key, desc) {
>                     ^
> 
> ReferenceError: window is not defined
>     at /www/sites/fakturomat/wwwroot/node_modules/@angular2-material/core/core.umd.js:7:21
>     at c (/www/sites/fakturomat/wwwroot/node_modules/@angular2-material/core/core.umd.js:2:68)
>     at Object.<anonymous> (/www/sites/fakturomat/wwwroot/node_modules/@angular2-material/core/core.umd.js:5:2)

**Comment by m0t0r** [comment] 2016-09-24 21:03
@morriq see #308

**Comment by jelbourn** [comment] 2016-09-25 00:29
Dupe of #308

**Closed by jelbourn** 2016-09-25 00:29 UTC
