### ISSUE TITLE
input placeholder and hint nomenclature is misleading

### ISSUE THREAD

**Issue by ilovett** [angular/material2#6479] opened 2017-08-15 16:42 UTC
https://material.io/guidelines/components/text-fields.html#text-fields-layout

`MdPlaceholder` acts like what should be the "Label" from the spec, perhaps rename it `MdLabel`

`MdHint` acts like what should be "Helper Text" from the spec, perhaps rename `MdHelperText`

"Placeholder Text (hint text)" from the spec appears to be unimplemented, AND conflicts with what I would assume should be named`MdPlaceholder` and/or `MdHint`

**Comment by rafaelss95** [comment] 2017-08-15 17:07
The `MdPlaceholder` part is a dupe of #6240.

About `MdHint` I really prefer the actual name than `MdHelperText`.

**Comment by jelbourn** [comment] 2017-08-16 21:17
Placeholder part is captured in #6240

We don't have any plans to change `MdHint`

**Closed by jelbourn** 2017-08-16 21:17 UTC
