### ISSUE TITLE
md-select get items using key board typing 

### ISSUE THREAD

**Issue by dimuthulakshan** [angular/material2#5928] opened 2017-07-21 06:17 UTC
#### What is the expected behavior?
Select Item in md-select when type keyboard characters. 

#### What is the current behavior? 
Nothing happens when type  characters after selecting md-select

**Comment by donroyco** [comment] 2017-07-21 06:45
Already tracked at #2668

**Comment by crisbeto** [comment] 2017-07-21 08:15
Closing as a duplicate of #2668.

**Closed by crisbeto** 2017-07-21 08:15 UTC
