### ISSUE TITLE
[Feature] reusable mat-table column components

### ISSUE THREAD

**Issue by StickNitro** [angular/material2#14038] opened 2018-11-08 10:56 UTC
#### Bug, feature request, or proposal:

I don't know if it is possible to create a “column” component for use with mat-table, if not then would like to see this feature added.

The use case is where you may have commonly re-usable columns in tables (a good example is a multi select column) so you could create a component that could then be reused across multiple tables. 

For example, suppose we have the following column definition below:

```
@Component({
  selector: 'iam-select-column',
  template: `
  <ng-container>
    <mat-header-cell *matHeaderCellDef>
      <mat-checkbox ...></mat-checkbox>
    </mat-header-cell>
    <mat-cell *matCellDef="let row">
      <mat-checkbox ...></mat-checkbox>
    </mat-cell>
  </ng-container>
  `,
  styles: [`
  `]
})
export class SelectColumnComponent implements OnInit {
  constructor() { }
  ngOnInit() {
  }
}
```

then we could use this in a `mat-table` to define the column (kinda like a template)
```
<mat-table class="mat-elevation-z8">

  <iam-select-column matColumnDef="select"></iam-select-column>

  <mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
  <mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>

</mat-table>
```

and assuming the displayedColumns are:
```
  displayedColumns = [
    'select'
  ];
```

Apologies if this Is already possible (if it is could someone provide a working example please?)

**Comment by andrewseguin** [comment] 2018-12-11 18:43
This is supported with the table now but I'm currently working on polishing the experience (at least better docs, with the release of an example e.g. `mat-text-column`)

https://stackblitz.com/edit/angular-5xthcl?file=app%2Ftable-simple-column-example.html

**Comment by andrewseguin** [comment] 2018-12-11 18:44
Closing as a duplicate of #5889 which captures the intent to create column wrappers

**Closed by andrewseguin** 2018-12-11 18:44 UTC
Labels: P3
