### ISSUE TITLE
[Dialog] mat-dialog-actions not sticking to bottom when setting the height of dialog

### ISSUE THREAD

**Issue by dpolicastro** [angular/material2#14335] opened 2018-11-30 14:28 UTC
#### Bug, feature request, or proposal:
The actions row is not sticking to bottom.

#### What is the expected behavior?
When setting the property align="end" it should stick to the bottom.
![image](https://user-images.githubusercontent.com/29067941/49294678-c90ccb80-f49a-11e8-925f-95be39f79cb6.png)

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/29067941/49294885-636d0f00-f49b-11e8-84e8-3e601411933b.png)

#### What are the steps to reproduce?
I'm setting the width and height of the modal passing the configuration object
```js
const dialogRef = this.dialog.open(MyDialog, {
      width: '80%',
      minHeight: '500px',
      data: { id: this.id }
    });
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
<pre><code>
{
  "@angular/material": "^7.0.3"
}
Angular CLI: 7.0.5
Node: 8.13.0
OS: linux x64
Angular: 7.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.5
@angular-devkit/build-angular     0.10.5
@angular-devkit/build-optimizer   0.10.5
@angular-devkit/build-webpack     0.10.5
@angular-devkit/core              7.0.5
@angular-devkit/schematics        7.0.5
@angular/cli                      7.0.5
@ngtools/webpack                  7.0.5
@schematics/angular               7.0.5
@schematics/update                0.10.5
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
    
</code></pre>

**Comment by josephperrott** [comment] 2018-11-30 21:00
Closing as duplicate of #4609

**Closed by josephperrott** 2018-11-30 21:00 UTC
