### ISSUE TITLE
Allow for sidenav to collapse horizontally but leaving an icon nav visible

### ISSUE THREAD

**Issue by xikky** [angular/material2#2021] opened 2016-11-29 13:28 UTC
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Once the sidenav is closed, a portion of it will still remain visible. Very similar to WordPress' admin menu, where the sidenav shows text and an icon for each menu item, and the same sidenav can be closed, leaving the icons only showing.

#### What is the current behavior?
Sidenav totally hides once the toggled to close.

#### What are the steps to reproduce?
The way I go around this is to override the translation in md-sidenav.md-sidenav-closed and md-sidenav.md-sidenav-closing css classes, keeping the sidenav still partly visible. That's fine, but in order to slide the content box with the new translation of sidenav, I had to animate the content box, for which I am pretty sure this can be done in a better way or in-house, within the sidenav component, thus adding this type of feature as a quick option.
Please check my plunker to see what I mean with the above.
http://plnkr.co/edit/LcRDIHNFjHKLFTaMdNEM?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Mainly I would like to know the proper way to do this, if there is a better way than having to animate the content box. But it would also be great if this feature is added to sidenav component so we can quickly set an option to make collapsing act like explained.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 2.1.1
Material: alpha-10
chrome

**Comment by chouclee** [comment] 2016-11-29 19:01
#1728 I think this is what you want.

**Comment by xikky** [comment] 2016-11-29 19:06
Yes precisely. I was missing the drawer keyword

**Comment by jelbourn** [comment] 2016-11-30 00:06
@mmalerba has a proposal for this already; it's something we'd like to add after beta

**Comment by Ravi-Rajpurohit** [comment] 2017-09-28 18:33
this may help ..
https://github.com/Ravi-Rajpurohit/mini-md-sidenav

**Comment by AyushiSrivastava20** [comment] 2017-10-11 19:17
@Ravi-Rajpurohit so can push mode work for your code?

**Comment by matte00** [comment] 2017-11-16 07:56
@jelbourn 
> @mmalerba has a proposal for this already; it's something we'd like to add after beta

Any news in RC?

**Comment by willshowell** [comment] 2017-11-16 14:11
Sounds like a dupe of #1728

**Closed** 2017-11-16 16:31 UTC
Labels: feature, P3: important

**Comment by George35mk** [comment] 2018-08-25 19:01
I have solved this try this code is pure typescript.

https://stackoverflow.com/questions/48479524/how-to-impliment-a-sidenav-navigation-drawer-with-a-mini-variant/49884854?noredirect=1#comment90117208_49884854
