### ISSUE TITLE
[Feature Request]: add calendar functionality to CDK

### ISSUE THREAD

**Issue by sfabriece** [angular/material2#10685] opened 2018-04-03 21:19 UTC
#### Bug, feature request, or proposal:

feature request
#### What is the expected behavior?

add calendar functionality to cdk
#### What is the current behavior?

None exist

#### What is the use-case or motivation for changing an existing behavior?

Customization of calendar styling

**Comment by jelbourn** [comment] 2018-04-03 22:45
Duplicate of #10686

**Closed by jelbourn** 2018-04-03 22:45 UTC
