### ISSUE TITLE
Material Sample App broken

### ISSUE THREAD

**Issue by slmyers** [angular/material2#3812] opened 2017-03-28 06:59 UTC
#### Bug, feature request, or proposal:
The [sample app](https://material.angular.io/guide/material2-app) from [getting started](https://material.angular.io/guide/getting-started) at material.angular.io is broken.

#### What is the expected behavior?
Demo app does not throw error

#### What is the current behavior?
App throws `Cannot read property 'document' of undefined` on loading.

#### What are the steps to reproduce?
Click the link on getting started.

#### What is the use-case or motivation for changing an existing behavior?
Devs should be able to check out the sample app. I saw this [thread](https://www.reddit.com/r/Angular2/comments/61uj4w/material_sample_app/) on Reddit and thought "well that's a shame".

**Comment by Chan4077** [comment] 2017-03-28 07:02
Duplicate of #3388

**Closed** 2017-03-28 07:45 UTC
