### ISSUE TITLE
Can't build app with aot compilation

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#2376] opened 2016-12-23 16:43 UTC
#### Bug:
Error thrown:
`Cannot read property 'MdAutocompleteModule' of undefined, resolving symbol MaterialRootModule in D:/ng/material-test-app/node_modules/@angular/material/module.d.ts, resolving symbol MaterialRootModule in D:/ng/material-test-app/node_modules/@angular/material/module.d.ts`

#### What is the expected behavior?
Build app with AOT

#### What is the current behavior?
Can't build app with AOT

#### What are the steps to reproduce?
With angular-cli create an app and build it with --aot parameter

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/material beta.0
angular-cli 24

#### Additional info
Building without aot works fine

**Comment by wheredoesyourmindgo** [comment] 2016-12-23 17:30
same issue here

**Comment by antonmoiseev** [comment] 2016-12-23 17:40
I replaced all `@angular/material` imports with import statements for individual components (e.g. `@angular/material/button`) this error has gone, but now I get another one:

```
Error: Cannot read property 'MdTabNavBar' of undefined, resolving symbol MdTabsModule in /Users/username/p/projectname/node_modules/@angular/material/tabs/tab-group.d.ts, resolving symbol MdTabsModule in /Users/username/p/projectname/node_modules/@angular/material/tabs/tab-group.d.ts
```

**Comment by jelbourn** [comment] 2016-12-23 18:56
Can you share more information about your issue? Our docs site (material.angular.io) is using the latest version and AoT works fine. 

@antonmoiseev you should avoid deep imports into the package. The structure there is neither intended for public consumption nor stable.

**Comment by Rob-Post** [comment] 2016-12-23 19:40
@jelbourn I think the 'Configuring SystemJS' section on the docs site is still using the old path without the **bundles** folder in the path

**Comment by daBishMan** [comment] 2016-12-23 19:41
I can build (using aot) no problem with latest, angular 2.4.1, beta.0

what I am running into, is including the hammerjs,  please take a look at #2379 , if I include types, and import into app.module.ts 

I build I get: 

C:\git\dabishman\ngx-material>ng build --aot
Hash: 7965e695f7d3fd76e316
Time: 14737ms
chunk    {0} main.bundle.js, main.bundle.map (main) 151 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.css, styles.bundle.map, styles.bundle.map (styles) 23.4 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 2.16 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'hammerjs' in 'C:\git\dabishman\ngx-material\src\app'
 @ ./src/app/app.module.ts 15:0-18
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi main

C:\git\dabishman\ngx-material>

**Comment by antonmoiseev** [comment] 2016-12-23 20:13
@jelbourn I can confirm the issue is fixed in beta.1

**Comment by daBishMan** [comment] 2016-12-23 20:17
does that address the hammejs issue I raised as well @antonmoiseev

**Comment by jelbourn** [comment] 2016-12-23 20:40
Either way, `MdAutocompleteModule` was accidentally added in beta.0, removed in beta.1 now.

**Closed by jelbourn** 2016-12-23 20:40 UTC

**Comment by antonmoiseev** [comment] 2016-12-23 22:19
@daBishMan I didn't have HammerJS issue, but I see Jeremy updated the getting started guide with HammerJS [setup instructions](https://github.com/angular/material2/blob/master/guides/getting-started.md#additional-setup-for-gestures)
