### ISSUE TITLE
md-select deselects when the value is 0 (instead of selecting the item with value of zero)

### ISSUE THREAD

**Issue by geelus** [angular/material2#5031] opened 2017-06-08 17:25 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Selecting the value 0

#### What is the current behavior?
Deselects everything

#### What are the steps to reproduce?
One your changes for version beta 6 is: 
"select: allow option with undefined or null value to clear selection (#3141) (13524c1), closes #3110 #2634"
This causes the issue of deselecting if the value is 0. So it deselects the mdselect if it's null or undefined or zero.
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
beta 6

**Comment by crisbeto** [comment] 2017-06-08 17:33
This has been fixed in master and will be in the next release. See https://github.com/angular/material2/commit/2e3910c86c1a1486222f639bb9404aaaf5661d9b.

**Closed by crisbeto** 2017-06-08 17:33 UTC

**Comment by geelus** [comment] 2017-06-08 17:43
Perfect. Thanks

**Comment by geelus** [comment] 2017-06-08 17:45
I checked the link and I guess it's a different issue. My problem is that when my ngModel is zero, instead of selecting the option zero, it deselects it all.

**Comment by crisbeto** [comment] 2017-06-08 18:06
It should be the same issue. Can you reproduce it in a Plunkr? You can use [this one which runs the latest build.](http://plnkr.co/edit/o077B6uEiiIgkC0S06dd)

**Comment by crisbeto** [comment] 2017-06-08 18:17
We had a similar PR today and I wasn't able to [reproduce it in this Plunkr](http://plnkr.co/edit/uEWZlHX3PXBuKI0WPguy?p=preview). I'm not sure whether you have a different setup though.

**Comment by geelus** [comment] 2017-06-08 18:49
Here is the plunker:
http://embed.plnkr.co/showVK2SkoBhUyBFOyKr/

but I'm getting a strange error:
"Can't bind to 'ngModel' since it isn't a known property of 'md-select'"
how come???!!!

**Comment by crisbeto** [comment] 2017-06-08 18:53
It's because the template doesn't include the `FormsModule`. [Here's a fixed version](https://plnkr.co/edit/mE1noIfgFVGCU9h02ni6?p=preview) and it also looks like selecting 0 works.

**Comment by geelus** [comment] 2017-06-10 01:36
Thank you for fixing the issue. Is the plunker you sent the one in dev (fixed) or beta 6 (released)?

**Comment by crisbeto** [comment] 2017-06-10 06:16
The Plunkr is using the latest `master` build.

**Comment by geelus** [comment] 2017-06-10 17:25
Perfect! so it's fixed.

**Comment by jonsamwell** [comment] 2017-06-14 08:55
Any idea when the next release is that will deliver this fix?

**Comment by geelus** [comment] 2017-06-14 09:31
Good question. I would love to know too.
