### ISSUE TITLE
mat-tab-link component should be disabled if disabled is set 

### ISSUE THREAD

**Issue by denpiv** [angular/material2#8880] opened 2017-12-08 12:45 UTC
#### Bug, feature request, or proposal:
bug: mat-tab-link can not be disabled any more since moved to 5.0 (worked earlier)

#### What is the expected behavior?
mat-tab-link component should be disabled if disabled is set 

#### What is the current behavior?
mat-tab-link component is enabled if disabled is set 

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-cnfz79?file=app%2Ftabs-overview-example.html

#### What is the use-case or motivation for changing an existing behavior?
Tab sometimes should be disabled

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.1.0
Material 5.0.0
TypeScript 2.4.2
OS Ubuntu 16.04
Browser Chrome Version 62.0.3202.75 (Official Build) (64-bit)

**Comment by DevVersion** [comment] 2017-12-09 10:44
@josephperrott This seems to be caused by https://github.com/angular/material2/pull/7364. Since `pointer-events` are now enabled, the `:focus` pseudo selector will work. If you still have a `[routerLink]` specified on a disabled link, the route will become active on click.

Also while we are at it, I don't think that the attribute `tabIndex` is valid. The real attribute would be `tabindex` in lowercase.

**Comment by josephperrott** [comment] 2018-01-12 17:29
After more investigation, this is actually caused by routerLink not being able to be disabled.  After discussing with the core team, I opened [this issue](https://github.com/angular/angular/issues/21457) to allow for `routerLink` to respect `event.preventDefault()`.

We are able to partially address this within Material by calling `preventDefault()` on click, which will properly be handled for normal `<a>` without `routerLink`s.

A potential workaround for the issue with `routerLink` is to set the route to be the same as the current page when the link should be disabled.

**Comment by josephperrott** [comment] 2018-01-24 16:33
Closed by #9357

**Closed by josephperrott** 2018-01-24 16:33 UTC
Labels: P3: important, has pr, regression
