### ISSUE TITLE
Enable Dragging based on Condition

### ISSUE THREAD

**Issue by ikismail** [angular/material2#13893] opened 2018-10-31 06:21 UTC
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Want to add conditional check whether this element is draggable or not.
`[cdkDrag]="true"`

#### What is the current behavior?
currently all the objects in the list are draggable.
![](https://cdn-images-1.medium.com/max/1000/1*T73wO_iEhhQzRJ2Z9pXjyA.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm using 
Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
Angular CLI: 7.0.3
Angular Material: 7.0.2
Node: 8.11.1
OS: win32 x64
typescript:  3.1.3
Angular: 7.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

#### Is there anything else we should know?
No

**Comment by crisbeto** [comment] 2018-10-31 06:42
Duplicate of https://github.com/angular/material2/issues/13651.

**Closed by crisbeto** 2018-10-31 06:42 UTC
