### ISSUE TITLE
Snackbar wrongly positioned if opened from global error handler

### ISSUE THREAD

**Issue by mzernetsch** [angular/material2#13181] opened 2018-09-18 14:53 UTC
#### Bug, feature request, or proposal:
I use a [global error handler](https://angular.io/api/core/ErrorHandler) in my app which shows a snackbar to the user if a certain type of exception is beeing thrown. 
If the exception originates from an async function (in my case a promise handler after a http request), the snackbar will be rendered at a wrong position.
The snackbar will only correct its position if the user triggers the change detection (click, mousemove, etc..).

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-td5qwb

1. Define a global error handler which shows a snackbar.
2. Throw an (uncaught) exception from an async function.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/core 6.0.7
@angular/material 6.3.2
Chrome 69
Windows 7

#### Is there anything else we should know?
My current workaround is to show an empty snackbar and manually trigger a change detection cycle before showing the actual snackbar:
```typescript
try {
  this.snackBar.open("");
  this.snackBar.dismiss();
  this.applicationRef.tick();
} catch (error) {}

this.snackBar.open("MESSAGE");
```

**Comment by josephperrott** [comment] 2018-09-18 15:03
Closing as duplicate of #7233

**Closed by josephperrott** 2018-09-18 15:03 UTC
