### ISSUE TITLE
extra 'span' element added in mat-option of autocomplete makes impossible to style the internals

### ISSUE THREAD

**Issue by xagon** [angular/material2#8561] opened 2017-11-20 21:07 UTC
#### Bug, feature request, or proposal:
I would consider it a bug unless told otherwise.

#### What is the expected behavior?
Extra ```span``` element is not added, in my opinion - not needed.

#### What is the current behavior?
Additional element is added to the form, making it impossible to style the internals.
![image](https://user-images.githubusercontent.com/20299573/33041628-454c1e40-ce3f-11e7-9452-2bb950322fe5.png)

#### What are the steps to reproduce?

1. http://plnkr.co/edit/dKYBn6NFpMbknwKbVfgP?p=preview
2. hit F12
3. hoover over the ```mat-option```

#### What is the use-case or motivation for changing an existing behavior?
styling of the internals is very hard becuase of the extra span which is added

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0-rc0-40d6bcb
the rest as per plunk example

#### Is there anything else we should know?
Nope, that's it.

**Comment by crisbeto** [comment] 2017-11-20 21:21
That span is there to collapse some whitespace, as well as truncate long labels (once https://github.com/angular/material2/pull/7857 gets in). Note that the text isn't the only content that can be put inside an option, there's also a checkbox that will be shown if the select is in `multiple` mode.

**Comment by jelbourn** [comment] 2017-11-20 22:00
Closing as "working as intended". You can always target descendants with css

**Closed by jelbourn** 2017-11-20 22:00 UTC

**Comment by xagon** [comment] 2017-11-21 22:26
yep, understood.
cheers guys!

**Comment by prashantpimpale93** [comment] 2019-07-04 05:47
@jelbourn I need the option text to appear to the next line after the text overflow from the min-width. 

What I did:

```
.mat-autocomplete-panel mat-option.mat-option {
  height: unset;
}

.mat-option-text.mat-option-text {
  white-space: normal;
}
```

But not working!

Can you suggest something?
