### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by anuj-pandit** [angular/material2#7677] opened 2017-10-10 05:20 UTC
#### Bug, feature request, or proposal:
Provide a dropdown to select Year in Date picker

#### What is the expected behavior?
If we want to select an year which is 40-50 years back, we should be able to quickly select the year via a dropdown or likewise.

#### What is the current behavior?
If we want to select an year which is 40-50 years back, we need to use the arrows and keep clicking to get the appropriate year selected.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Enhance user experience

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by donroyco** [comment] 2017-10-10 05:41
Duplicate of #5845

**Comment by jelbourn** [comment] 2017-10-10 13:01
Duplicate of #5845

**Closed by jelbourn** 2017-10-10 13:01 UTC
