### ISSUE TITLE
Dialog open differently by an eventEmitter from a diffrent module

### ISSUE THREAD

**Issue by ssavajols** [angular/material2#7777] opened 2017-10-13 18:03 UTC
#### Bug, feature request, or proposal:
There is a bug when I try to open a dialog. I have one dialog which is open with two different ways.

First, I have a component which is triggering an event with EventEmitter. The dialog is situated into the same module as the one which is triggering the event. In this case, the dialog open normally.

Second, Same as before, the dialog is open by an EventEmitter but in this case the component which is triggering the event is in another module. When I do this, the dialog is firstly opening empty then after few seconds re-open with data's.

#### What is the expected behavior?
The dialog open in the same way.

#### What is the current behavior?
The dialog is'nt opening the same way.

#### What are the steps to reproduce?
Create two submodules and an eventBus.
Create a component which is in charge to open a dialog from the eventBus.
Trigger the event from the module with the dialog. => Open normally
Trigger the event from the module without the dialog => Open in two steps with the first open empty.

Structure : 
- AppModule
    - ModuleA
        - DialogContentComponent
        - DialogComponent  => trigger from here the eventEmitter result in a normal open
        - EventBus with event Emitter
  - ModuleB
        - SomeComponent  => trigger from here the eventEmitter result in an abnormal open

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.2.4 
angular material 2.0.0-beta.11

**Comment by julianobrasil** [comment] 2017-10-13 18:12
Could you try do reproduce it here, please: https://stackblitz.com/edit/angular-material2-issue?file=app%2Fapp.component.ts

**Comment by ssavajols** [comment] 2017-10-13 19:13
Ok so, I tried to reproduce the bug and I didn't succeed. 

I can add some new informations about the issue. Apparently it's not a bug with modules. It's about dom. I explain the point : 

I have a google map on the page. When I click on the map, I open a dialog. When the dialog opened it is rendering with the static content, no-data. The when I move the mouse, the dialog re open with data. 

This issue appear only if I open the dialog with a click on the google map. 

I think it's a bug with the mouseover event, angular material dialog is listening to this event ? It's only when i move the mouse on the dialog that the dialog appear correctly.

Have you any information about this ?

**Comment by willshowell** [comment] 2017-10-13 19:30
This is probably a change detection thing. Does the dialog actually re-open with animation or does it just suddenly show the new data? How are you passing that data through? Is it through a service or are you just setting it manually on the dialogRef?

**Comment by ssavajols** [comment] 2017-10-13 19:36
The overlay is still here, but the dialog close and re-open with animation but with performance issue. If I don't have data through the dialog, it's still the same. Getting it by a service or not.

In my code, I open the dialog in the callback. The service end before I stating to open the dialog.

**Comment by willshowell** [comment] 2017-10-13 19:38
Is the callback from google maps? I think there are some zone-related issues with doing that.

**Comment by ssavajols** [comment] 2017-10-13 19:41
The callback is a promise.

```
open(marker: google.maps.Marker) {
    if ( marker ) {
        this.profileServices
            .getProfileById(marker.profile.id)
            .then(profile => {
                if ( profile ) {
                    const [p, n] = this.profileServices.getPreviousNextProfile(profile);
                    this.show = this.SHOW;

                    this.uiDialog.simple({
                          component: ProfileDetailDialogComponent,
                          data: {
                            nextProfile: n,
                            previousProfile: p,
                            profile: this.computeDistanceColor(profile),
                            PROFILE_DEFAULT_IMAGE: AppConstant.PROFILE_DEFAULT_IMAGE
                          }
                        })
                        .afterClosed()
                        .subscribe(result => {
                          switch (result) {
                            case 'itinary':
                              const coordsSrc = this.gmapService.getCurrentPosition().join(',');
                              const coordsDest = profile.profile.location[0] + ',' + profile.profile.location[1];
                              window.open( 'https://www.google.fr/maps/dir/' + coordsSrc + '/' + coordsDest + '/');
                              break;
                            case 'next':
                              ProfileEvents.profileDetailOpen.emit({ profile: n });
                              break;
                            case 'previous':
                              ProfileEvents.profileDetailOpen.emit({ profile: p });
                              break;
                          }
                        });
                }

            });
    }
  }
```

**Comment by ssavajols** [comment] 2017-10-13 19:44
```javascript
export class UiDialogService {

  constructor(public dialog: MatDialog) { }

  simple(params: any) {
    const {component} = params;
    delete params.component;
    return this.dialog.open(component, params);
  }

  confirm(title, content) {
    return this.dialog.open(DialogConfirmComponent, {
      data: {
        content,
        title
      }
    });
  }
}

```

**Comment by ssavajols** [comment] 2017-10-17 08:18
Any progress one this issue ? Opening a dialog with a click on a google map is the main feature of my webapp. How can I help on this issue ? 

Thank's in advance.

**Comment by Hagith** [comment] 2017-10-20 14:22
I was able to reproduce very similar behavior in my use case. When dialog is opened for the first time, there is no animation and data interpolation.

**Use case context**
I'm catching all unhandled exceptions in one place and displaying error message in a dialog. To achieve this I'm providing [custom Angular ErrorHandler](https://angular.io/api/core/ErrorHandler) which is publishing exceptions through `ErrorService` (Rx/Subject) and "root" component is observing this service.

Please see example here: https://stackblitz.com/edit/angular-material2-issue-7777?file=app/app.component.ts

Click on "Start error interval" button and wait 4 seconds. First dialog is empty, second displays error data.
As a "bonus", dialog which is opened this way (without user interaction) can't be closed by `mat-dialog-close` directive.
Second button in the example is opening the same dialog directly, and is working properly.

**Comment by willshowell** [comment] 2017-10-20 18:16
@Hagith see https://github.com/angular/material2/issues/7470#issuecomment-333601828 and this working fork

https://stackblitz.com/edit/angular-material2-issue-7777-dzymva

@ssavajols if @Hagith's example looks like what you're seeing, you're almost certainly seeing an NgZone issue

**Comment by ssavajols** [comment] 2017-10-20 20:15
The example is not exactly the same but it is very close.

In my case, I need user interaction.

**Comment by ssavajols** [comment] 2017-10-20 20:45
Ok, so calling ngZone.run() is solving the problem.

If I understand correctly, when I click on the map, I go outside of angular event system and I need to manually call ngZone.run to go back inside angular routines.

Right?

**Comment by Hagith** [comment] 2017-10-20 21:26
Interesting! It looks that we are experiencing the same situation. In both scenarios we are showing dialog from outside of Angular's "zone". I'm quite new in Angular development so I still need to catch up what it really means ;)
But during few hours of debugging I noticed that showing dialog from "outside" (global error handler or 3rd party DOM) skips some kind of  "Angular's event loop". In my scenario I solved this using **veeeeery ugly!** hack - by generating additional "click" event on the dialog element.
Thank you for pointing me `ngZone.run()`, I will read more about it, try to use it in my code (Monday of course) and return to you with the result.
Have a nice weekend, stay curious! 
Rafal

**Comment by jelbourn** [comment] 2017-10-20 23:28
Closing since it appears to be an "escaping the zone" issue not related to material per @willshowell

**Closed by jelbourn** 2017-10-20 23:28 UTC

**Comment by ssavajols** [comment] 2017-10-21 08:32
May Have we an explanation about this ? 

What good practice may we use ? 

I am new to angular 2/4 and will appreciate to have a technical explanation about zoning in angular 2.

Thanks.

**Comment by Hagith** [comment] 2017-10-21 10:01
I think it's out of scope of Material to explain why there is `NgZone` and why it should be used. There are a lot of articles explaining this in depth. For example [this brief introduction](https://medium.com/@MertzAlertz/what-the-hell-is-zone-js-and-why-is-it-in-my-angular-2-6ff28bcf943e).

**Comment by ssavajols** [comment] 2017-10-21 11:59
Thanks it's clearer now. The point is that replace on some words $scope.$digest() from angular 1.
