### ISSUE TITLE
proposal : datepicker add popup position

### ISSUE THREAD

**Issue by stevenmi** [angular/material2#4543] opened 2017-05-14 07:24 UTC
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
if the datepicker in the bottom of a page, the calendar popup above the input

#### What is the current behavior?
only under the input ,when the touch ui is false

#### What are the steps to reproduce?
https://material.angular.io/components/component/datepicker go to examples and click the calendar button

#### What is the use-case or motivation for changing an existing behavior?
to the purpose that i can select date,if the datepicker input is put in the bottom of page,or there is no enough space to display the calendar under the input in the case of the page is scroll to the bottom of a page.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta.5
Google Chrome 58

**Comment by donroyco** [comment] 2017-05-14 08:36
This has already been mentioned in #4406

**Comment by jelbourn** [comment] 2017-06-07 15:06
Dupe of #4406

**Closed by jelbourn** 2017-06-07 15:06 UTC
