### ISSUE TITLE
md-input-container / md-form-field with *ngIf not working

### ISSUE THREAD

**Issue by thormentor** [angular/material2#6789] opened 2017-09-01 14:07 UTC
#### Bug
After updating angular from 4.3.5 to 4.3.6 using angular/material from 2.0.0-beta.8 the md-input-container stop working with the ngIf directive. I've updated angular/material to 2.0.0-beta.10 to check if the problem was fixed but with the same results. I've made the necessary changes and replace all md-input-container with md-form-field.

#### What is the expected behavior?
SHOW THE INPUT FIELD:
<md-form-field hideRequiredMarker="true"  *ngIf="true">
    <input mdInput >
</md-form-field>

HIDE THE INPUT FIELD:
<md-form-field hideRequiredMarker="true"  *ngIf="false">
    <input mdInput >
</md-form-field>

#### What is the current behavior?
The input field is not shown.

**Comment by willshowell** [comment] 2017-09-01 14:09
If you look at the dom, does it exist but with just `display: none`? If so, duplicate of https://github.com/angular/material2/issues/6696

**Comment by julianobrasil** [comment] 2017-09-01 15:09
Oh... that explains a few things 😄

**Comment by crisbeto** [comment] 2017-09-01 15:54
Definitely a duplicate of #6696.

**Closed by crisbeto** 2017-09-01 15:54 UTC
