### ISSUE TITLE
close scroll stragety not working on tooltip

### ISSUE THREAD

**Issue by fxck** [angular/material2#8020] opened 2017-10-25 10:14 UTC
See https://stackblitz.com/edit/angular-material2-issue-s7p3py?file=app%2Fapp.module.ts

1) hover over text 
2) scroll down
3) tooltip doesn't close 

block scroll strategy works btw

@crisbeto @jelbourn

**Comment by crisbeto** [comment] 2017-10-25 10:37
Closing as a dupe of https://github.com/angular/material2/issues/7922.

**Closed by crisbeto** 2017-10-25 10:37 UTC
