### ISSUE TITLE
Nested mat-menu (sub-item) disappeared.

### ISSUE THREAD

**Issue by irowbin** [angular/material2#10081] opened 2018-02-22 07:50 UTC
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
Submenu of  `mat-menu`  should not hide when moving mouse over it.

#### What is the current behavior?
When moving mouse over sub menu, it disappear but if i downgrade to `v5.2.0` It worked.

#### What are the steps to reproduce?

I've reproduced at [stackblitz](https://stackblitz.com/edit/angular-pj7qwr?file=app%2Fapp.component.html)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.2.6
Material: 5.2.2

#### Is there anything else we should know?

Take a look:
![video_001 1](https://user-images.githubusercontent.com/13050078/36526050-bbaf4cea-17d4-11e8-89dd-537d8c570e15.gif)

**Comment by julianobrasil** [comment] 2018-02-22 10:23
It works fine in 5.2.1. The issue has begun in 5.2.2.

**Comment by HitomiTenshi** [comment] 2018-02-22 11:35
I can confirm. Works fine in 5.2.1 but happens in 5.2.2.

**Comment by julianobrasil** [comment] 2018-02-22 11:36
@irowbin, you can work it around encapsulating the submenu in a component: https://stackblitz.com/edit/angular-material-nested-submenu

**Comment by crisbeto** [comment] 2018-02-22 12:46
Your Stackblitz appears to be missing the Material core theme which also contains some base styling that makes the overlays work. I couldn't reproduce the issue after moving it to [a Stackblitz that has everything set up correctly](https://stackblitz.com/angular/xbdlaqmbddv?file=app%2Fmenu-overview-example.ts).

**Comment by rafaelcgdf** [comment] 2018-02-22 12:54
@crisbeto I'm using a custom theme, how do I fix for that? I'm using 5.2.1 in the meanwhile

**Comment by crisbeto** [comment] 2018-02-22 12:57
This isn't something that is likely to have broken between 5.2.1 and 5.2.2. As mentioned in the [theming guide](https://material.angular.io/guide/theming#defining-a-custom-theme) when you're defining a custom theme, you need to `@include mat-core()` at least once in your codebase.

**Comment by julianobrasil** [comment] 2018-02-22 13:04
@crisbeto, I was reproduce this issue in a template of the docs site: https://stackblitz.com/edit/angular-material-nested-submenu-nwwsr6

**Comment by crisbeto** [comment] 2018-02-22 13:37
I see what you mean now. The issue was introduced in https://github.com/angular/material2/pull/9971 which caused the top-level menu to pick up the items inside the submenu as its own.

**Closed** 2018-02-22 22:44 UTC
Labels: P2: required, has pr, regression
