### ISSUE TITLE
Ability to import RippleModule from '@angular/material/ripple'

### ISSUE THREAD

**Issue by MurhafSousli** [angular/material2#10869] opened 2018-04-15 20:26 UTC
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?

`import { RippleModule } from '@angular/material/ripple'`

#### What is the current behavior?

`import { RippleModule } from  '@angular/material'`

#### What is the use-case or motivation for changing an existing behavior?

Sometimes only RippleModule is needed.
User cannot include the ripple module without including the core module which has a size > 100kb

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 5.2.0
Material 5.2.4

**Comment by crisbeto** [comment] 2018-04-15 20:35
Closing as a duplicate of https://github.com/angular/material2/issues/7543.

**Closed by crisbeto** 2018-04-15 20:35 UTC
