### ISSUE TITLE
Date picker component is not working as expected on Internet explorer 11

### ISSUE THREAD

**Issue by srinrao2** [angular/material2#11768] opened 2018-06-12 20:05 UTC
#### Bug, feature request, or proposal:
On Internet explorer 11 angular date picker component input field is auto converting to wrong date example: if i enter 15/05/2018 converting into 3/5/2019 

#### What is the expected behavior?
On Internet explorer 11 angular date picker component input field should not auto convert to wrong date example: if i enter 15/05/2018 it should remain same.

#### What is the current behavior?
On Chrome browser date picker component input field is not converting to wrong date example: if i enter 15/05/2018 remains 15/05/2018

On Internet explorer 11 angular date picker component input field is auto converting to wrong date example: if i enter 15/05/2018 converting into 3/5/2019 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
Enter this url on internet explorer 11 and manually type 15/05/2018 in datepicker input field its auto converting to wrong date
https://stackblitz.com/angular/dqnnmyyvlpr?file=app%2Fdatepicker-overview-example.ts

#### What is the use-case or motivation for changing an existing behavior?
On IE 11 browser if i manually enter 15/05/2018 in date picker input and click on out side the field its automatically converting to 3/5/2019.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 5 , @angular/material@5.2.4 , typescript: 2.6.2

#### Is there anything else we should know?
No

**Comment by Tetrygon** [comment] 2018-06-13 16:48
It looks like you are trying to set the date to a DD/MM/YYYY. It looks like IE is trying to parse it in a way it makes sense. Chrome looks like it accepts the value, but on closer inspection.. it doesn't. You have to customize the date picker to accept a certain format, by default it is designed to accept MM/DD/YYYY. Take a gander at https://material.angular.io/components/datepicker/overview#customizing-the-parse-and-display-formats

**Comment by josephperrott** [comment] 2018-06-25 16:24
Closing, as mentioned above you will need to customize the date format to allow for DD/MM/YYYY syntax.

**Closed by josephperrott** 2018-06-25 16:24 UTC

**Comment by maximus1989** [comment] 2019-01-22 08:12
Actually it's not a problem with date format.
The problem is with NativeDateAdapter.
For correct working matDatePickers in IE we should use MomentDateAdapter.
https://stackblitz.com/edit/angular-sr2k7y?file=main.ts

**Comment by cloudcodemaster** [comment] 2019-01-31 22:48
Hi there, I have the same problem than srinrao2 and I don't think what Tetrygon said about dd/mm/yyyy instead mm/dd/yyyy, in addition maximus1989 your stackblitz demo is a dead link now, could you please give a quick explanation about how you fixed that issue. We, the developers hate IE... it always gives us terrible headaches!

**Comment by maximus1989** [comment] 2019-02-01 09:50
Hi, cloudcodemaster.
I corrected link of example.
Please check.

Quick explanation:
use MomentDateAdapter in provider.
...
  providers: [
    { provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE] },
    { provide: MAT_DATE_FORMATS, useValue: MY_DATE_FORMATS }
  ]
...
export class AppModule {}
