### ISSUE TITLE
Feature: date range picker

### ISSUE THREAD

**Issue by MatanYed** [angular/material2#9336] opened 2018-01-11 14:01 UTC
#### Bug, feature request, or proposal:
Date range picker, choose start date and end date, like in hotels booking sites

#### What is the expected behavior?
https://docs.webix.com/media/desktop/daterange_picker.png
https://www.jqueryscript.net/images/Beautiful-ES5-ES6-Date-Daterange-Picker-For-jQuery.jpg
https://camo.githubusercontent.com/1083660a91a3d95a2dd4e8e5e74dfc9703fcdadd/687474703a2f2f692e696d6775722e636f6d2f4c62414d6633442e706e67

**Comment by donroyco** [comment] 2018-01-11 14:20
Already requested. Duplicate of #4763

**Comment by Chan4077** [comment] 2018-01-11 15:04
By the way @MatanYed, can you change those links to inline images? The image markdown syntax goes like this:

```markdown
![My example jpeg file](https://example.com/example.jpg)
```

Where the text in square brackets are the alternate text if the image doesn't exist, doesn't load, etc. and the text in parenthesis is the link to the image.

**Comment by jelbourn** [comment] 2018-01-11 23:00
Duplicate of #4763

**Closed by jelbourn** 2018-01-11 23:00 UTC
