### ISSUE TITLE
Fixed First Column in Mat Table

### ISSUE THREAD

**Issue by agokulravikumar** [angular/material2#11001] opened 2018-04-25 13:31 UTC
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
In few cases where we have a horizontal scrolling, would require the first column to be fixed. Similar to the column lock/freeze that we do in excel

#### What is the current behavior?
Currently horizontal scrolling table scrolls the entire table

#### What are the steps to reproduce?
https://angular-material2-issue-wfbfte.stackblitz.io
The first 2 columns in the table should be a fixed one and others to scroll when scrolled horizontally.

**Comment by agokulravikumar** [comment] 2018-05-03 07:16
@andrewseguin : Any updates on this ?

**Comment by andrewseguin** [comment] 2018-05-03 14:17
Dupe of https://github.com/angular/material2/issues/5890

**Closed by andrewseguin** 2018-05-03 14:17 UTC

**Comment by andrewseguin** [comment] 2018-05-03 14:18
@agokulravikumar Working on the feature now along with sticky header and footer, currently the highest priority upcoming feature
