### ISSUE TITLE
How can I hide/delete underline input in the latest version?

### ISSUE THREAD

**Issue by anavarrom** [angular/material2#11383] opened 2018-05-17 10:39 UTC
How can I hide/delete underline input in the latest version of material2?

UnderlineRef is now deprecated.

Thanks.

**Comment by pfeigl** [comment] 2018-05-17 14:18
See #6623 for possible solution using CSS (which is probably better than removing it entirly under the hoods anyways)

**Comment by crisbeto** [comment] 2018-05-19 13:09
Closing as a duplicate of https://github.com/angular/material2/issues/6623.

**Closed by crisbeto** 2018-05-19 13:09 UTC
