### ISSUE TITLE
$theme variable is not defined in pre-built themes.

### ISSUE THREAD

**Issue by davidshen84** [angular/material2#13476] opened 2018-10-07 08:44 UTC
#### Bug, feature request, or proposal:
But

#### What is the expected behavior?
The `$theme` variable should be defined in the pre-built themes.

#### What is the current behavior?
After `@import` a pre-built theme, the `$theme` variable is not defined.

#### What are the steps to reproduce?
@import "~@angular/material/prebuilt-themes/indigo-pink.css";

#### What is the use-case or motivation for changing an existing behavior?
Follow the guide on https://material.angular.io/guide/theming-your-components#how-to-use-code-mixin-code- to define my own theme.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@schematics/angular          0.6.8
@schematics/update           0.6.8
rxjs                         6.2.1
typescript                   2.7.2
```

**Comment by crisbeto** [comment] 2018-10-07 09:00
It looks like your import is pointing to a .css file which is compiled and doesn't have any of the variables.

**Comment by manklu** [comment] 2018-10-07 09:11
Duplicate of #5152

**Comment by jelbourn** [comment] 2018-10-10 23:09
Duplicate of #5152

The docs will be updated with v7

**Closed by jelbourn** 2018-10-10 23:09 UTC
