### ISSUE TITLE
<mat-icon> not work on edge browser

### ISSUE THREAD

**Issue by BamiGorengo** [angular/material2#11917] opened 2018-06-25 09:13 UTC
```
Angular CLI: 6.0.8
Node: 8.11.1
OS: win32 x64
Angular: 6.0.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.3.0-c276e26
@angular/cli                      6.0.8
@angular/material                 6.3.0-c276e26
@angular/pwa                      0.6.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```

I used the `<mat-icon>` like this:

```
<button mat-icon-button>
    <mat-icon>remove_circle</mat-icon>
</button>
```

They work on Firefox and Chrome well, but on edge browser totaly buggy and invisible.
Here you can see the Webseite to test and reproduce: https://expense-calculator.com/

**Comment by mtrdp642** [comment] 2018-06-25 11:56
Can you reproduce the issue in a StackBlitz? [The one I made works in both Chrome and Edge](https://stackblitz.com/edit/angular-h63buu) without issue, so I suspect there is something else going on.

**Comment by crisbeto** [comment] 2018-06-25 16:59
Which icons are breaking for you? As far as I can tell, everything works on Edge:

![expensecalculator_ -_microsoft_edge_2018-06-25_18-58-53](https://user-images.githubusercontent.com/4450522/41864333-e67ce1b8-78a9-11e8-8c73-26f8be77fe75.png)

**Comment by BamiGorengo** [comment] 2018-06-25 17:02
i use now on the live page `<mat-icon svgIcon="thumbs-up"></mat-icon>` with:

```
iconRegistry.addSvgIcon(
  'thumbs-up',
  sanitizer.bypassSecurityTrustResourceUrl('assets/img/examples/thumbup-icon.svg'));
```

Thats why you can see the icons in this site.

**Comment by mtrdp642** [comment] 2018-06-26 13:45
Make if you're using the Material Icon ligatures, make sure you include the required HTML in your index.html, [as documented here](https://material.angular.io/components/icon/overview#font-icons-with-ligatures):
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`

**Comment by josephperrott** [comment] 2018-06-26 15:56
Unfortunately without a reproduction case we won't really be able to investigate too much into the issue.  If you can provide a stackblitz reproduction of the issue we should be able to look into it more.

**Comment by BamiGorengo** [comment] 2018-06-26 16:48
Yeah no problem. I dont understand why it works in stackblitz, i did exactly the same. but however, i think that including the svg icons is anyway a better way then including the whole icon lib. :)

**Comment by dmeagor** [comment] 2018-08-08 12:51
Same problem here on edge after updating to latest version of angular material.  It was working ok before I updated some modules including switching material from ~6.0.0 to ^6.4.3

![image](https://user-images.githubusercontent.com/714902/43837666-2189daac-9b11-11e8-83a0-7211be72e641.png)


{
    "name": "shout",
    "version": "0.0.0",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "hmr": "ng serve --configuration hmr",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
        "@agm/core": "1.0.0-beta.3",
        "@angular/animations": "~6.1.1",
        "@angular/cdk": "~6.4.2",
        "@angular/common": "~6.1.1",
        "@angular/compiler": "~6.1.1",
        "@angular/core": "~6.1.1",
        "@angular/flex-layout": "6.0.0-beta.17",
        "@angular/forms": "~6.1.1",
        "@angular/http": "~6.1.1",
        "@angular/material": "^6.4.3",
        "@angular/platform-browser": "~6.1.1",
        "@angular/platform-browser-dynamic": "~6.1.1",
        "@angular/pwa": "^0.6.1",
        "@angular/router": "~6.1.1",
        "@angular/service-worker": "~6.1.1",
        "angular-calendar": "^0.24.1",
        "angular-sortablejs": "^2.6.0",
        "chart.js": "^2.7.2",
        "chart.piecelabel.js": "^0.9.0",
        "classlist.js": "^1.1.20150312",
        "core-js": "^2.4.1",
        "hammerjs": "^2.0.8",
        "highlight.js": "^9.12.0",
        "lodash-es": "^4.17.5",
        "moment": "^2.20.1",
        "ngx-quill": "^3.4.0",
        "normalize.css": "^7.0.0",
        "quill": "^1.3.6",
        "rxjs": "^6.2.2",
        "rxjs-compat": "^6.2.2",
        "screenfull": "^3.3.2",
        "smooth-scrollbar": "^8.2.6",
        "sortablejs": "^1.7.0",
        "typings": "^2.1.1",
        "zone.js": "^0.8.20"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.7.0",
        "@angular/cli": "~6.1.2",
        "@angular/compiler-cli": "^6.1.1",
        "@angular/language-service": "^6.1.1",
        "@angularclass/hmr": "^2.1.3",
        "@types/jasmine": "~2.8.6",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "~9.4.6",
        "codelyzer": "~4.3.0",
        "jasmine-core": "~2.99.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~1.7.1",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.0",
        "karma-jasmine": "~1.1.1",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.3.0",
        "ts-node": "~5.0.1",
        "tslint": "~5.9.1",
        "typescript": "~2.9.2"
    }
}

**Comment by dmeagor** [comment] 2018-08-08 12:53
rolling back angular material fixes everything.

**Comment by crisbeto** [comment] 2018-08-08 12:58
@dmeagor are you using SVG icons or font icons?

**Comment by dmeagor** [comment] 2018-08-08 13:17
Looks like 6.4.3 was added a short time ago, after upgrading from 6.4.2 everything's now working.

I simply ran npm install --save @angular/material @angular/cdk

**Comment by josephperrott** [comment] 2018-09-10 22:17
Closing as we still have not be able to reproduce this issue on a supported browser.

**Closed by josephperrott** 2018-09-10 22:17 UTC
Labels: cannot reproduce
