### ISSUE TITLE
Please add in sidenav Navigation drawer a (Mini variant)

### ISSUE THREAD

**Issue by George35mk** [angular/material2#9640] opened 2018-01-27 14:56 UTC
#### Bug, feature request, or proposal:
feature 

#### What is the expected behavior?
is very hard or impossible to add min variant

#### What is the current behavior?
The sidenave is hiding completely, I want to control the min-width on close
![7](https://user-images.githubusercontent.com/20750445/35472963-893cddf2-0381-11e8-8173-6c77a6082d97.PNG)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
I very hard for me to make this, is very important for me because I build most of the time Desktop apps with google material.

Add this feature ass extra for desktop developers

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
the latest:
- Windows 10 Pro
- "@angular/cli": "1.6.5",
- "typescript": "~2.5.3"
- "@angular/material": "^5.1.0",

#### Is there anything else we should know?

Yes Add this
![8](https://user-images.githubusercontent.com/20750445/35473011-37ebc084-0382-11e8-8e9d-b085d240ea5b.PNG)

```html
 <mat-sidenav-container>

    <mat-sidenav 
      #adminNavMenu 
      mode="side" 
      opened="true"
      variantMin="60px"     <=== I need to add this input is importand.
      variantMax="250px">   <=== I need to add this input is importand.

      <!-- MENU LEFT -->
      <app-admin-menu-left></app-admin-menu-left>

    </mat-sidenav>

</mat-sidenav-container>
```
```javascript
@input variantMin = the min-width, default set this to 0
@input variantMax = the max-width, default set this to 250 || auto
```

**Comment by donroyco** [comment] 2018-01-27 15:04
Duplicate of #1728

**Comment by George35mk** [comment] 2018-01-27 15:06
Roy yes but this feature request is from  **4 Nov 2016**  now we have **2018** and nothing solved

**Comment by George35mk** [comment] 2018-01-27 15:07
I want to contribute but I never in my life contribute on project can you guide me were I can find the sidenave files to make the changes and push a new request

**Comment by George35mk** [comment] 2018-01-27 15:08
I struggle to find were are this sidenave files but I cant find anything

**Comment by donroyco** [comment] 2018-01-27 23:04
It’s still a duplicate request. Opening a similar issue won’t get it solved faster. Please use the original issue to address your need for this feature.

**Comment by josephperrott** [comment] 2018-02-13 23:15
Closing as duplicate of #1728

**Closed by josephperrott** 2018-02-13 23:15 UTC
