### ISSUE TITLE
md-expansion-panel-header has incorrect height when put into a mat-tab-group

### ISSUE THREAD

**Issue by wngjw** [angular/material2#8058] opened 2017-10-26 19:59 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Heights of headers in expansion panels are homogenous between tabs

#### What is the current behavior?
Here's what I did:
- Create a `mat-tab-group` with at least 2 tabs
- Place a `mat-expansion-panel` in each tab, with a `mat-expansion-panel-header` and `mat-panel-title` on each
On the second tab, the title on the header is missing padding, while on the first tab, the padding is present.

#### What are the steps to reproduce?
See attached Plunker: http://plnkr.co/edit/S73nzA?p=preview

#### What is the use-case or motivation for changing an existing behavior?
These tabs should have consistent behavior according the material design standard

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material 2.0.0-beta.12
Angular 4.4.6

Reproduced on Plunker and on Chrome

**Comment by shonderdos** [comment] 2017-10-26 20:30
To further explain the issue: 
Bug seems to be within `mat-expansion-panel-header`.
`mat-expansion-panel-header` within the **first** tab got `height: 48px;` applied to it.
`mat-expansion-panel-header` within the **second** tab didn't have height applied to it.

**Comment by wngjw** [comment] 2017-10-26 20:58
In addition, it seems that adding an `expanded="true"` attribute to the `mat-expansion-panel` does not expand the second/subsequent tabs the same way as it does the first.
These elements seem to behave normally when manually expanding and closing them, but not when they are first rendered.

Updated original plunker accordingly.

**Comment by tytskyi** [comment] 2017-10-26 21:05
Duplicate of https://github.com/angular/material2/issues/5269. See also workaround in the comments https://github.com/angular/material2/issues/5269#issuecomment-326692430

**Comment by josephperrott** [comment] 2017-10-26 21:49
Closing as duplicate of #5269

**Closed by josephperrott** 2017-10-26 21:49 UTC
